/* corners/stories/companions-little/abubakr.js — أبو بكر الصديق للصغار (٣–٦) · ٨ حكايات */
window.COMPANIONS_LITTLE = window.COMPANIONS_LITTLE || {};
window.COMPANIONS_LITTLE.abubakr = {
  id:'abubakr', icon:'🕋', color:'#C9A227', title:'أَبُو بَكْرٍ الصِّدِّيق', tag:'أَوَّلُ الرِّجَالِ إِسْلَامًا',
  stories:[

{ id:'first', icon:'🌟', color:'#C9A227', title:'أَوَّلُ مَنْ آمَن',
  tag:'صَدَّقَ فَوْرًا بِلَا تَرَدُّد',
  pages:[
    { emoji:'🤝', text:'كَانَ أَبُو بَكْرٍ صَدِيقَ النَّبِيِّ ﷺ الْحَبِيب، وَأَوَّلَ الرِّجَالِ إِيمَانًا بِه.',
      prompt:'Two loyal friends silhouettes under warm light in old Makkah, deep friendship, no faces' },
    { emoji:'💚', text:'حِينَ دَعَاهُ النَّبِيُّ ﷺ لِلْإِسْلَام، آمَنَ فَوْرًا بِلَا تَرَدُّد، لِأَنَّهُ يَعْرِفُ صِدْقَه.',
      prompt:'A glowing heart accepting truth instantly with warm light, immediate faith, tender' },
    { emoji:'⭐', text:'قَالَ النَّبِيُّ ﷺ: مَا دَعَوْتُ أَحَدًا إِلَى الْإِسْلَامِ إِلَّا كَانَتْ عِنْدَهُ كَبْوَة، إِلَّا أَبَا بَكْر.',
      prompt:'A bright golden star shining first among others, foremost in faith, warm radiant' },
    { emoji:'💛', text:'فَأَتَعَلَّمُ مِنْه: إِذَا عَرَفْتُ الْحَقَّ اتَّبَعْتُهُ فَوْرًا بِلَا تَأْخِير.',
      prompt:'A child confidently choosing the right path with a warm glow, following truth, uplifting' },
  ],
  moral:'إِذَا عَرَفْتُ الْحَقَّ اتَّبَعْتُهُ فَوْرًا مِثْلَ أَبِي بَكْر. 💛',
  game:{ type:'pairs', title:'صِلْ كُلَّ شَيْءٍ بِأَبِي بَكْر', pairs:[
    ['🤝 صَدِيقُ النَّبِيِّ ﷺ','الْحَبِيبُ الْوَفِيّ'],
    ['🌟 أَوَّلُ الرِّجَال','إِيمَانًا بِالنَّبِيّ'],
    ['💚 آمَنَ فَوْرًا','بِلَا تَرَدُّد'] ] },
  act:{ q:'مَنْ أَوَّلُ الرِّجَالِ إِسْلَامًا؟', yay:'أَحْسَنْت! أَبُو بَكْرٍ الصِّدِّيق', opts:[
    { e:'🤝', t:'أَبُو بَكْرٍ الصِّدِّيق', ok:true },
    { e:'🤷', t:'لَا أَعْرِف' },
    { e:'👑', t:'مَلِكُ مَكَّة' } ] },
  dua:'اللَّهُمَّ ارْزُقْنِي اتِّبَاعَ الْحَقِّ فَوْرًا' },

{ id:'siddiq', icon:'🌙', color:'#2980B9', title:'لِمَاذَا سُمِّيَ الصِّدِّيق؟',
  tag:'صَدَّقَ بِالْإِسْرَاءِ وَالْمِعْرَاج',
  pages:[
    { emoji:'🌙', text:'لَمَّا أَخْبَرَ النَّبِيُّ ﷺ النَّاسَ أَنَّهُ ذَهَبَ إِلَى الْقُدْسِ ثُمَّ عُرِجَ بِهِ إِلَى السَّمَاءِ فِي لَيْلَةٍ وَاحِدَة، تَعَجَّبَ النَّاس!',
      prompt:'A starry night sky with a path of light rising up, the Night Journey, awe, no figures' },
    { emoji:'😲', text:'قَالَ الْمُشْرِكُونَ لِأَبِي بَكْر: هَلْ تُصَدِّقُ صَاحِبَك؟ فَقَال: إِنْ كَانَ قَالَ فَقَدْ صَدَق!',
      prompt:'A crowd questioning and one calm confident figure, unwavering trust, warm, no faces' },
    { emoji:'⭐', text:'فَسُمِّيَ «الصِّدِّيق» لِأَنَّهُ صَدَّقَ فَوْرًا، لِأَنَّ إِيمَانَهُ بِاللهِ وَنَبِيِّهِ قَوِيٌّ جِدًّا.',
      prompt:'A radiant golden star of certainty, deep unshakable faith, warm reverent' },
    { emoji:'💚', text:'فَأَتَعَلَّمُ الْيَقِينَ: أُصَدِّقُ اللهَ وَرَسُولَهُ وَإِنْ لَمْ أَفْهَمْ كُلَّ شَيْء.',
      prompt:'A child with a steady glowing heart of certainty, trust in Allah, warm tender' },
  ],
  moral:'الْيَقِينُ أَنْ أُصَدِّقَ اللهَ وَرَسُولَهُ بِلَا تَرَدُّد مِثْلَ الصِّدِّيق. 💚',
  game:{ type:'sort', title:'مَاذَا فَعَلَ أَبُو بَكْرٍ حِينَ سَمِعَ خَبَرَ الْإِسْرَاء؟', bins:['يَقِينٌ وَتَصْدِيق ✅','شَكٌّ 🚫'], items:[
    { e:'⭐', t:'صَدَّقَ فَوْرًا', bin:0 },
    { e:'😕', t:'شَكَّ وَتَرَدَّد', bin:1 },
    { e:'💚', t:'قَالَ: إِنْ قَالَ فَقَدْ صَدَق', bin:0 },
    { e:'🙅', t:'كَذَّبَ النَّبِيّ', bin:1 } ] },
  act:{ q:'لِمَاذَا سُمِّيَ أَبُو بَكْرٍ بِالصِّدِّيق؟', yay:'أَحْسَنْت! لِأَنَّهُ صَدَّقَ فَوْرًا بِيَقِين', opts:[
    { e:'⭐', t:'لِأَنَّهُ صَدَّقَ النَّبِيَّ فَوْرًا', ok:true },
    { e:'💰', t:'لِأَنَّهُ غَنِيّ' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ ارْزُقْنِي يَقِينًا كَيَقِينِ الصِّدِّيق' },

{ id:'freeing', icon:'⛓️', color:'#C0392B', title:'مُحَرِّرُ الْعَبِيد',
  tag:'أَعْتَقَ بِلَالًا وَغَيْرَه',
  pages:[
    { emoji:'⛓️', text:'كَانَ الْمُشْرِكُونَ يُعَذِّبُونَ الضُّعَفَاءَ مِنَ الْمُسْلِمِين، مِثْلَ بِلَالٍ الَّذِي عُذِّبَ عَلَى الرَّمْلِ الْحَارّ.',
      prompt:'Hot desert sand under a harsh sun, hardship of the weak believers, warm but gentle, no faces' },
    { emoji:'💰', text:'فَكَانَ أَبُو بَكْرٍ الْغَنِيُّ يَشْتَرِيهِم بِمَالِهِ وَيُحَرِّرُهُم لِوَجْهِ الله، وَمِنْهُم بِلَال.',
      prompt:'Coins given generously to free someone, buying freedom, warm compassionate scene, no faces' },
    { emoji:'🕊️', text:'أَنْفَقَ أَبُو بَكْرٍ مَالَهُ كُلَّهُ فِي سَبِيلِ الله، وَلَمْ يَبْخَلْ بِشَيْء.',
      prompt:'An open generous hand releasing doves of freedom, generosity for Allah, warm radiant' },
    { emoji:'💚', text:'فَأَتَعَلَّمُ الْكَرَمَ وَالرَّحْمَة: أُنْفِقُ مِمَّا أُحِبُّ لِمُسَاعَدَةِ الضُّعَفَاء.',
      prompt:'A child sharing generously with someone in need, kindness and giving, warm bright' },
  ],
  moral:'أَتَعَلَّمُ الْكَرَمَ مِنْ أَبِي بَكْر: أُنْفِقُ لِمُسَاعَدَةِ الضُّعَفَاءِ لِوَجْهِ الله. 💚',
  game:{ type:'find', title:'حَرِّرِ الْمُسْتَضْعَفِين! اجْمَعْ قُلُوبَ الْكَرَمِ الْخَمْس', target:'💚', count:5, distractors:['⛓️','☁️'], size:12 },
  act:{ q:'مَاذَا فَعَلَ أَبُو بَكْرٍ بِمَالِهِ لِلضُّعَفَاء؟', yay:'أَحْسَنْت! اشْتَرَاهُم وَأَعْتَقَهُم لِوَجْهِ الله', opts:[
    { e:'💰', t:'اشْتَرَاهُم وَحَرَّرَهُم', ok:true },
    { e:'😴', t:'لَمْ يَفْعَلْ شَيْئًا' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ اجْعَلْنِي كَرِيمًا رَحِيمًا بِالضُّعَفَاء' },

{ id:'cave', icon:'🕳️', color:'#5B4B8A', title:'رَفِيقُ الْغَار',
  tag:'ثَانِيَ اثْنَيْنِ إِذْ هُمَا فِي الْغَار',
  pages:[
    { emoji:'🌙', text:'حِينَ هَاجَرَ النَّبِيُّ ﷺ مِنْ مَكَّةَ إِلَى الْمَدِينَة، اخْتَارَ أَبَا بَكْرٍ لِيَكُونَ رَفِيقَهُ فِي الرِّحْلَة.',
      prompt:'Two travelers journeying under a starry desert night, the Hijra, warm, no faces' },
    { emoji:'🕳️', text:'اخْتَبَآ فِي غَارِ ثَوْر، وَالْأَعْدَاءُ يُفَتِّشُونَ فَوْقَهُمَا! خَافَ أَبُو بَكْرٍ عَلَى النَّبِيّ.',
      prompt:'A cave entrance with a spider web and a nesting dove, protection at the cave, warm serene' },
    { emoji:'💚', text:'فَطَمْأَنَهُ النَّبِيُّ ﷺ: لَا تَحْزَنْ إِنَّ اللهَ مَعَنَا! فَحَفِظَهُمَا اللهُ بِعَنْكَبُوتٍ وَحَمَامَة.',
      prompt:'A protective spider web across a cave mouth with soft light, divine protection, warm tender' },
    { emoji:'📖', text:'ذَكَرَ اللهُ أَبَا بَكْرٍ فِي الْقُرْآن: ثَانِيَ اثْنَيْنِ إِذْ هُمَا فِي الْغَار — شَرَفٌ عَظِيم!',
      prompt:'A glowing Quran page with warm light, honor of being mentioned, reverent serene' },
  ],
  moral:'مَنْ كَانَ اللهُ مَعَهُ فَلَا يَخَاف: لَا تَحْزَنْ إِنَّ اللهَ مَعَنَا. 💚',
  game:{ type:'maze', title:'اهْرُبْ مَعَ النَّبِيِّ ﷺ وَأَبِي بَكْرٍ إِلَى غَارِ ثَوْر', avatar:'🚶', goal:'🕳️', wall:'🌵', map:['S..#.','##.#.','.#...','.#.##','...#G'] },
  act:{ q:'مَاذَا قَالَ النَّبِيُّ ﷺ لِأَبِي بَكْرٍ فِي الْغَار؟', yay:'أَحْسَنْت! فَاطْمَأَنَّ قَلْبُهُ', opts:[
    { e:'💚', t:'لَا تَحْزَنْ إِنَّ اللهَ مَعَنَا', ok:true },
    { e:'😱', t:'اهْرُبْ وَحْدَك!' },
    { e:'🤷', t:'لَا شَيْء' } ] },
  dua:'حَسْبُنَا اللهُ وَنِعْمَ الْوَكِيل، لَا تَحْزَنْ إِنَّ اللهَ مَعَنَا' },

{ id:'generous', icon:'🎁', color:'#27AE60', title:'أَنْفَقَ كُلَّ مَالِه',
  tag:'السَّبْقُ إِلَى الْخَيْر',
  pages:[
    { emoji:'🎁', text:'فِي إِحْدَى الْغَزَوَات، طَلَبَ النَّبِيُّ ﷺ مِنَ الصَّحَابَةِ أَنْ يَتَصَدَّقُوا لِنُصْرَةِ الْإِسْلَام.',
      prompt:'People bringing donations for a good cause, generous giving, warm community scene, no faces' },
    { emoji:'💰', text:'جَاءَ عُمَرُ بِنِصْفِ مَالِه، أَمَّا أَبُو بَكْرٍ فَجَاءَ بِمَالِهِ كُلِّه!',
      prompt:'A generous pile of wealth given entirely with a warm glow, giving everything, radiant' },
    { emoji:'❓', text:'سَأَلَهُ النَّبِيُّ ﷺ: مَاذَا أَبْقَيْتَ لِأَهْلِك؟ قَال: أَبْقَيْتُ لَهُمُ اللهَ وَرَسُولَه!',
      prompt:'An open trusting hand giving all with light, complete trust in Allah, warm tender' },
    { emoji:'💚', text:'فَأَتَعَلَّمُ السَّبْقَ إِلَى الْخَيْرِ وَالثِّقَةَ بِأَنَّ اللهَ خَيْرُ حَافِظ.',
      prompt:'A child eagerly giving to a good cause with joy, racing to good, warm bright' },
  ],
  moral:'أُسَابِقُ إِلَى الْخَيْر، وَأَثِقُ أَنَّ اللهَ خَيْرُ حَافِظٍ وَرَازِق. 💚',
  game:{ type:'sort', title:'كَيْفَ أَكُونُ سَبَّاقًا لِلْخَيْر؟', bins:['سَبْقٌ لِلْخَيْر 💚','بُخْلٌ وَتَأْخِير 🚫'], items:[
    { e:'🎁', t:'أُبَادِرُ بِالصَّدَقَة', bin:0 },
    { e:'😤', t:'أَبْخَلُ بِمَالِي', bin:1 },
    { e:'🤝', t:'أُسَاعِدُ فَوْرًا', bin:0 },
    { e:'⏰', t:'أُؤَجِّلُ الْخَيْرَ دَائِمًا', bin:1 } ] },
  act:{ q:'كَمْ تَصَدَّقَ أَبُو بَكْرٍ فِي الْغَزْوَة؟', yay:'أَحْسَنْت! بِمَالِهِ كُلِّهِ ثِقَةً بِالله', opts:[
    { e:'💰', t:'بِمَالِهِ كُلِّه', ok:true },
    { e:'🪙', t:'بِقَلِيلٍ فَقَط' },
    { e:'🙅', t:'لَمْ يَتَصَدَّق' } ] },
  dua:'اللَّهُمَّ اجْعَلْنِي مِنَ الْمُسَارِعِينَ فِي الْخَيْرَات' },

{ id:'khalifa', icon:'👑', color:'#B8862E', title:'أَوَّلُ الْخُلَفَاء',
  tag:'قَادَ الْأُمَّةَ بِحِكْمَة',
  pages:[
    { emoji:'😢', text:'حِينَ تُوُفِّيَ النَّبِيُّ ﷺ حَزِنَ الْمُسْلِمُونَ حُزْنًا شَدِيدًا، وَاضْطَرَبَ بَعْضُهُم.',
      prompt:'A somber but hopeful gathering under soft light, grief of the community, warm, no faces' },
    { emoji:'🗣️', text:'فَقَامَ أَبُو بَكْرٍ بِثَبَاتٍ وَقَال: مَنْ كَانَ يَعْبُدُ مُحَمَّدًا فَإِنَّ مُحَمَّدًا قَدْ مَات، وَمَنْ كَانَ يَعْبُدُ اللهَ فَإِنَّ اللهَ حَيٌّ لَا يَمُوت.',
      prompt:'A steadfast figure calming a crowd with wisdom, firm leadership, warm reverent, no face' },
    { emoji:'👑', text:'فَاخْتَارَهُ الْمُسْلِمُونَ أَوَّلَ خَلِيفَة، فَقَادَ الْأُمَّةَ بِحِكْمَةٍ وَعَدْلٍ وَقُوَّة.',
      prompt:'A wise leader guiding a united community, first caliph, warm dignified scene, no face' },
    { emoji:'💚', text:'كَانَ رَحِيمًا بِالنَّاس، قَوِيًّا فِي الْحَقّ، مُتَوَاضِعًا لَا يَتَكَبَّر.',
      prompt:'A humble leader helping ordinary people, humility in leadership, warm tender scene' },
  ],
  moral:'أَتَعَلَّمُ الثَّبَاتَ وَالْحِكْمَة: عِنْدَ الشِّدَّةِ أَثْبُتُ وَأَتَوَكَّلُ عَلَى الله. 💚',
  game:{ type:'order', title:'رَتِّبْ مَرَاحِلَ أَبِي بَكْرٍ الصِّدِّيق', items:[
    { e:'🌟', t:'أَوَّلُ الرِّجَالِ إِسْلَامًا' },
    { e:'🕳️', t:'رَفِيقُ الْغَار' },
    { e:'🎁', t:'أَنْفَقَ مَالَهُ كُلَّه' },
    { e:'👑', t:'أَوَّلُ الْخُلَفَاء' } ] },
  act:{ q:'مَنْ أَوَّلُ خَلِيفَةٍ لِلْمُسْلِمِينَ بَعْدَ النَّبِيِّ ﷺ؟', yay:'أَحْسَنْت! أَبُو بَكْرٍ الصِّدِّيق', opts:[
    { e:'👑', t:'أَبُو بَكْرٍ الصِّدِّيق', ok:true },
    { e:'🤷', t:'لَا أَعْرِف' },
    { e:'🦁', t:'أَحَدُ الْمُلُوك' } ] },
  dua:'اللَّهُمَّ ثَبِّتْنِي عِنْدَ الشَّدَائِد' },

{ id:'humble', icon:'🤲', color:'#8E44AD', title:'تَوَاضُعُ الصِّدِّيق',
  tag:'خَلِيفَةٌ يَخْدُمُ النَّاس',
  pages:[
    { emoji:'👑', text:'صَارَ أَبُو بَكْرٍ خَلِيفَةً يَحْكُمُ الْمُسْلِمِين، لَكِنَّهُ بَقِيَ مُتَوَاضِعًا كَمَا كَان.',
      prompt:'A humble leader in simple clothes among people, humility despite power, warm, no faces' },
    { emoji:'🐐', text:'كَانَ يَحْلُبُ الْغَنَمَ لِلْأَرَامِلِ وَالْمَسَاكِين، وَيَقْضِي حَوَائِجَ الضُّعَفَاءِ بِنَفْسِه.',
      prompt:'A caring figure helping widows and the poor with daily needs, servant-leadership, warm tender' },
    { emoji:'💰', text:'وَلَمْ يَأْخُذْ مِنْ مَالِ الْمُسْلِمِينَ إِلَّا قَلِيلًا يَكْفِيه، فَكَانَ أَمِينًا عَادِلًا.',
      prompt:'A simple modest meal and plain living, honesty and restraint, warm humble scene' },
    { emoji:'💚', text:'فَأَتَعَلَّمُ التَّوَاضُع: مَهْمَا كَبِرْتُ أَبْقَى مُتَوَاضِعًا أَخْدِمُ النَّاسَ وَأُحِبُّهُم.',
      prompt:'A child humbly helping others with a warm smile, humility and service, uplifting bright' },
  ],
  moral:'التَّوَاضُعُ خُلُقُ الْعُظَمَاء: مَهْمَا عَلَا قَدْرِي أَبْقَى مُتَوَاضِعًا خَادِمًا. 💚',
  game:{ type:'sort', title:'أَيُّهَا مِنَ التَّوَاضُع؟', bins:['تَوَاضُع 💚','كِبْر 🚫'], items:[
    { e:'🤝', t:'أَخْدِمُ النَّاسَ وَأُسَاعِدُهُم', bin:0 },
    { e:'😤', t:'أَتَكَبَّرُ عَلَى غَيْرِي', bin:1 },
    { e:'😊', t:'أَتَوَاضَعُ مَعَ الصِّغَارِ وَالْكِبَار', bin:0 },
    { e:'🙄', t:'أَحْتَقِرُ الْفُقَرَاء', bin:1 } ] },
  act:{ q:'كَيْفَ كَانَ أَبُو بَكْرٍ وَهُوَ خَلِيفَة؟', yay:'أَحْسَنْت! مُتَوَاضِعًا يَخْدُمُ النَّاس', opts:[
    { e:'💚', t:'مُتَوَاضِعًا يَخْدُمُ الضُّعَفَاء', ok:true },
    { e:'😤', t:'مُتَكَبِّرًا' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ ارْزُقْنِي التَّوَاضُعَ وَحُبَّ النَّاس' },

{ id:'jannah', icon:'🌟', color:'#1F8B6E', title:'الْمُبَشَّرُ بِالْجَنَّة',
  tag:'رَفِيقُ النَّبِيِّ ﷺ فِي الْجَنَّة',
  pages:[
    { emoji:'🌟', text:'بَشَّرَ النَّبِيُّ ﷺ أَبَا بَكْرٍ بِالْجَنَّة، فَهُوَ أَوَّلُ الْعَشَرَةِ الْمُبَشَّرِينَ بِهَا.',
      prompt:'A radiant golden star among ten shining in a warm sky, glad tidings of Paradise, serene' },
    { emoji:'🚪', text:'وَأَخْبَرَ ﷺ أَنَّ أَبَا بَكْرٍ يُنَادَى مِنْ كُلِّ أَبْوَابِ الْجَنَّةِ الثَّمَانِيَة لِكَثْرَةِ خَيْرِه!',
      prompt:'Eight glowing gates of paradise welcoming, honored entry, warm radiant light' },
    { emoji:'💞', text:'أَحَبَّهُ النَّبِيُّ ﷺ حُبًّا عَظِيمًا وَقَال: لَوْ كُنْتُ مُتَّخِذًا خَلِيلًا لَاتَّخَذْتُ أَبَا بَكْر.',
      prompt:'Two hearts of light joined in warm friendship, deep love and companionship, tender' },
    { emoji:'💚', text:'فَأُحِبُّ أَبَا بَكْر، وَأَقْتَدِي بِصِدْقِهِ وَكَرَمِهِ وَتَوَاضُعِهِ لِأَكُونَ مِثْلَه.',
      prompt:'A child looking up at a bright guiding star with aspiration, following a role model, uplifting' },
  ],
  moral:'أُحِبُّ الصِّدِّيقَ وَأَقْتَدِي بِصِدْقِهِ وَكَرَمِهِ وَتَوَاضُعِه. 💚',
  game:{ type:'find', title:'أَبُو بَكْرٍ مُبَشَّرٌ بِالْجَنَّة! اجْمَعِ النُّجُومَ الذَّهَبِيَّةَ الْخَمْس', target:'🌟', count:5, distractors:['☁️','🌙'], size:12 },
  act:{ q:'بِمَ بَشَّرَ النَّبِيُّ ﷺ أَبَا بَكْر؟', yay:'أَحْسَنْت! بَشَّرَهُ بِالْجَنَّة', opts:[
    { e:'🌟', t:'بَشَّرَهُ بِالْجَنَّة', ok:true },
    { e:'💰', t:'بِالْمَالِ الْكَثِير' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ ارْزُقْنِي الْجَنَّةَ وَصُحْبَةَ النَّبِيِّ ﷺ فِيهَا' },

]};
