/* problem-1.js — الكذب · Lying */
window.BEHAVIOR.problems.push({
  id:'p1', ic:'🤥', c:'#2A6FDB',
  nm:{ar:'الكذب', en:'Lying'},
  sub:{ar:'حين يقول الطفلُ غيرَ الحقيقة', en:'When a child says what isn\u2019t true'},
  intro:{ar:'الكذبُ من أكثرِ ما يُقلِق الأهلَ لأنّه يمسُّ الأمانةَ والدين. لكنّ كذبَ الطفلِ في معظمِه ليس فسادًا أخلاقيًّا، بل سلوكٌ له دافع: خوفٌ من العقاب، أو خيالٌ لم ينضج، أو طلبُ انتباه، أو تقليد. فهمُ الدافعِ هو نصفُ العلاج، وردُّ الفعلِ الحكيمُ هو نصفُه الآخر. والعقابُ القاسي يصنع كاذبًا ماهرًا لا طفلًا صادقًا.',
    en:'Lying worries parents most because it touches honesty & faith. But a child\u2019s lying is mostly not moral corruption but a behaviour with a motive: fear of punishment, immature imagination, attention-seeking, or imitation. Understanding the motive is half the cure; a wise reaction is the other half. Harsh punishment makes a skilled liar, not an honest child.'},
  glance:[
    {ic:'🎯', k:{ar:'الدافعُ الأشيع',en:'Top motive'}, v:{ar:'الخوفُ من العقاب',en:'Fear of punishment'}},
    {ic:'🧒', k:{ar:'السنُّ الحرجة',en:'Key age'}, v:{ar:'٣–٧ سنوات',en:'3\u20137 years'}},
    {ic:'🔑', k:{ar:'مفتاحُ العلاج',en:'Key to cure'}, v:{ar:'بيتٌ آمنٌ للصدق',en:'A home safe for truth'}},
    {ic:'🚫', k:{ar:'الخطُّ الأحمر',en:'Red line'}, v:{ar:'وصمُه بـ«كذّاب»',en:'Labeling him \u201cliar\u201d'}},
  ],
  normal:{
    intro:{ar:'ليس كلُّ «كذب» كذبًا أخلاقيًّا؛ الطفلُ الصغيرُ قد يخلط الخيالَ بالواقع. هذا الجدولُ يفرّق بين ما هو مرحلةُ نموٍّ وما يستدعي الانتباه.',
      en:'Not every \u201clie\u201d is a moral lie; a young child may blur imagination & reality. This table separates a growth phase from what needs attention.'},
    rows:[
      {k:{ar:'٣–٤ سنوات',en:'3\u20134 yrs'}, nat:{ar:'خلطُ الخيالِ بالواقع («رأيتُ ديناصورًا!») — لا يقصد الكذب.',en:'Mixing fantasy & reality (\u201cI saw a dinosaur!\u201d) \u2014 no intent to deceive.'}, abn:{ar:'كذبٌ متعمّدٌ مدروسٌ لإيذاءِ غيره في هذه السنّ المبكّرة.',en:'Deliberate, calculated lies to harm others this early.'}},
      {k:{ar:'٥–٧ سنوات',en:'5\u20137 yrs'}, nat:{ar:'كذبٌ لتجنّبِ العقابِ أو نيلِ رغبة — عَرَضيٌّ ويستجيب للتوجيه.',en:'Lying to avoid punishment or get a want \u2014 occasional, responds to guidance.'}, abn:{ar:'كذبٌ يوميٌّ مستمرٌّ رغم العلاجِ الصحيح.',en:'Daily, persistent lying despite right handling.'}},
      {k:{ar:'٨+ سنوات',en:'8+ yrs'}, nat:{ar:'كذبةٌ بيضاءُ أحيانًا، أو مبالغةٌ للفخر — يميّز الصوابَ ويندم.',en:'An occasional white lie or boastful exaggeration \u2014 knows right & regrets.'}, abn:{ar:'كذبٌ بلا سببٍ واضح، أو مع سرقةٍ وغشٍّ وعدوان.',en:'Lying with no clear reason, or with stealing, cheating & aggression.'}},
      {k:{ar:'الدافع',en:'Motive'}, nat:{ar:'خوفٌ أو خيالٌ أو طلبُ انتباه — مفهوم.',en:'Fear, fantasy or attention-seeking \u2014 understandable.'}, abn:{ar:'كذبٌ قهريٌّ متلذّذٌ بلا فائدةٍ ولا ندم.',en:'Compulsive lying, enjoyed, pointless & remorseless.'}},
    ],
    specialist:[
      {ar:'كذبٌ مستمرٌّ يوميٍّ بعد سنِّ السابعةِ رغم برنامجِ علاجٍ ثابتٍ لأشهر.',en:'Daily persistent lying after age seven despite a steady program for months.'},
      {ar:'كذبٌ يصحبه سرقةٌ أو إيذاءٌ للحيوانِ أو عدوانٌ أو حرائق.',en:'Lying with stealing, cruelty to animals, aggression or fire-setting.'},
      {ar:'كذبٌ مفاجئٌ مع تغيّرٍ حادٍّ في المزاجِ أو انطواءٍ أو تراجعٍ دراسيّ (قد يخفي ضغطًا أو إيذاءً).',en:'Sudden lying with sharp mood change, withdrawal or academic decline (may hide stress or abuse).'},
      {ar:'كذبٌ لا يميّز فيه الطفلُ الكبيرُ الواقعَ من الخيالِ إطلاقًا.',en:'An older child who cannot tell reality from fantasy at all.'},
    ],
  },
  religious:{ar:'الصدقُ أصلٌ عظيمٌ في ديننا: «عليكم بالصدقِ فإنّ الصدقَ يهدي إلى البرّ»، والكذبُ بابُ الفجور. لكنّ الشرعَ راعى مرحلةَ الطفلِ فلم يكلّفه قبل البلوغ، وجعل التربيةَ على الصدقِ تدرّجًا بالقدوةِ والترغيبِ لا بالقهر.\n\nوأعظمُ ما يغرس الصدقَ صدقُ الوالدِ نفسِه؛ فقد عدَّ النبيُّ ﷺ الوعدَ الكاذبَ للطفلِ كذبةً تُكتَب: من قال لصبيٍّ «تعالَ هاكَ» ثمّ لم يُعطِه فهي كذبة. فكيف نطلب منه صدقًا ونكذب أمامه؟ التربيةُ على الصدقِ تبدأ من لسانِ الأبِ قبل لسانِ الابن.\n\nومن حكمةِ الشرعِ السترُ والرفقُ: لا تَجعل بيتَك محكمةً تُرعِب الطفلَ حتى يكذب نجاةً، بل اجعله مأمنًا يَصدُق فيه لأنّه يثق أنّ الصدقَ لا يُقابَل بالقسوة. وكافِئ الصادقَ ولو أخطأ؛ فالاعترافُ بالخطأِ بصدقٍ خيرٌ من إخفائه بكذب.',
    en:'Truthfulness is a great root in our religion: \u201cHold to truth, for truth guides to righteousness,\u201d while lying is a door to wickedness. Yet the Shari\u2019ah considered the child\u2019s stage, not holding him accountable before puberty, & made training in truth gradual \u2014 by example & encouragement, not coercion.\n\nWhat plants truth most is the parent\u2019s own truthfulness; the Prophet ﷺ counted a false promise to a child as a recorded lie: whoever tells a child \u201ccome, take this\u201d then gives nothing has lied. How can we demand truth while we lie before him? Training in truth begins on the father\u2019s tongue before the son\u2019s.\n\nPart of the Shari\u2019ah\u2019s wisdom is covering & gentleness: don\u2019t make your home a court that terrifies the child into lying to escape, but a refuge where he tells the truth because he trusts truth won\u2019t be met with harshness. Reward the truthful even when he errs; an honest admission beats a hidden lie.'},
  educational:{ar:'تربويًّا، الكذبُ سلوكٌ مكتسبٌ يُعالَج بتعديلِ البيئةِ لا بمحاكمةِ الطفل. القاعدةُ الذهبيّة: «لا تنصب فخًّا ثمّ تعاقب». إذا رأيتَ الحقيقةَ بعينك فلا تسأل «هل فعلتَ؟» لتدفعه للكذب؛ بل قل «رأيتُ ما حدث، تعالَ نُصلِحه معًا».\n\nاصنع بيئةً يكون فيها الصدقُ أرخصَ ثمنًا من الكذب: خفِّف عقابَ الخطأ المعترَفِ به، وامدح الاعترافَ صراحةً («شجاعٌ أنّك قلت الحقيقةَ، هذا أهمُّ عندي من الخطأ»). كرّر القصصَ التي تُمجّد الصادقين، وكن قدوةً في الوفاءِ بالوعد.\n\nوتجنّب الوصمَ نهائيًّا؛ فالطفلُ الذي يُنادى بـ«الكذّاب» يتقمّص الدورَ ويصدّق أنّه كذلك. صحّح السلوكَ لا الهُويّة: «هذا الكلامُ غيرُ صحيح» لا «أنت كذّاب».',
    en:'Educationally, lying is a learned behaviour treated by adjusting the environment, not trying the child. The golden rule: \u201cdon\u2019t set a trap then punish.\u201d If you saw the truth with your eyes, don\u2019t ask \u201cdid you?\u201d to push him to lie; say \u201cI saw what happened, let\u2019s fix it together.\u201d\n\nBuild an environment where truth is cheaper than lying: lighten the punishment for an admitted mistake, & praise the admission openly (\u201cyou\u2019re brave to tell the truth \u2014 that matters more to me than the mistake\u201d). Repeat stories glorifying the truthful, & model keeping promises.\n\nAvoid labeling entirely; a child called \u201cliar\u201d adopts the role & believes it of himself. Correct the behaviour, not the identity: \u201cthat statement isn\u2019t true,\u201d not \u201cyou are a liar.\u201d'},
  psych:{ar:'يرى علمُ النفسِ النموّيُّ أنّ القدرةَ على الكذبِ علامةُ نموٍّ معرفيٍّ طبيعيّة! فالطفلُ لا يكذب قبل أن يدرك أنّ في رأسِه معلومةً تخالف ما في رأسِك (نظريّةُ العقل، تنضج نحو ٤ سنوات). لذلك أوّلُ الأكاذيبِ علامةُ ذكاءٍ لا فساد.\n\nأكثرُ دوافعِ الكذبِ شيوعًا: تجنّبُ العقاب (الأشيع)، وتضخيمُ الذاتِ أمام الأقران، وطلبُ الانتباه، وتجنّبُ مهمّةٍ مزعجة، والخيالُ عند الصغار. الأداةُ النفسيّةُ الأقوى هي التعزيزُ التفاضليّ: تجاهل أثرَ الكذبةِ قدرَ الإمكان، وضخِّم الاهتمامَ والمكافأةَ حين يصدُق، فيتعلّم الدماغُ أنّ الصدقَ «يُربِح» أكثر.\n\nالعقابُ القاسي يأتي بعكسِ المقصود: يرفع كلفةَ الاعترافِ فيتقن الطفلُ الكذبَ للنجاة. أمّا الأمانُ النفسيُّ — أن يعرف أنّ الصدقَ يخفّف لا يضاعف — فيقتل دافعَ الكذبِ من جذره.',
    en:'Developmental psychology sees the ability to lie as a sign of normal cognitive growth! A child can\u2019t lie before realizing his head holds information differing from yours (theory of mind, maturing around age 4). So a first lie is a sign of intelligence, not corruption.\n\nThe commonest motives: avoiding punishment (most common), self-inflation before peers, attention-seeking, dodging an unpleasant task, & fantasy in the young. The strongest psychological tool is differential reinforcement: minimize the lie\u2019s payoff as far as possible, & amplify attention & reward when he tells the truth, so the brain learns truth \u201cpays\u201d more.\n\nHarsh punishment backfires: it raises the cost of admitting, so the child perfects lying to survive. Psychological safety \u2014 knowing truth lightens rather than doubles the consequence \u2014 kills the motive to lie at its root.'},
  medical:{ar:'طبّيًّا، الكذبُ ليس مرضًا في ذاته بل سلوك؛ لكنّه أحيانًا عَرَضٌ ضمن صورةٍ أكبر. في فرطِ الحركةِ وتشتّتِ الانتباه (ADHD) قد يكذب الطفلُ اندفاعًا أو نسيانًا لا خبثًا. وفي اضطراباتِ السلوكِ (Conduct Disorder) يقترن الكذبُ بالعدوانِ والسرقةِ وانتهاكِ الحقوقِ على نحوٍ يحتاج تقييمًا.\n\nانتبه: الكذبُ المفاجئُ الجديدُ قد يكون إشارةَ ضائقة — تعرّضٌ لتنمّرٍ أو ضغطٍ أو إيذاء، يخفيه الطفلُ خوفًا. كذلك الكذبُ القهريُّ المستمرُّ بلا فائدةٍ يستحقّ نظرَ المختصّ.\n\nمتى الطبيب؟ إذا اقترن الكذبُ بسرقةٍ أو عدوانٍ أو إيذاءٍ للحيوان، أو استمرّ يوميًّا بعد السابعةِ رغم العلاج، أو صحبه تراجعٌ دراسيٌّ أو انطواءٌ أو تغيّرُ مزاجٍ حاد. التقييمُ المبكّرُ يفتح بابَ العلاجِ السلوكيِّ المعرفيِّ (CBT) الذي أثبت فعاليّتَه.',
    en:'Medically, lying is not a disease in itself but a behaviour; yet it is sometimes a symptom within a larger picture. In ADHD a child may lie impulsively or from forgetfulness, not malice. In Conduct Disorder lying pairs with aggression, stealing & rights-violations in a way needing evaluation.\n\nNote: sudden new lying may signal distress \u2014 exposure to bullying, stress or abuse the child hides from fear. Likewise persistent compulsive lying with no benefit warrants a specialist\u2019s look.\n\nWhen a doctor? If lying pairs with stealing, aggression or cruelty to animals; persists daily after seven despite treatment; or comes with academic decline, withdrawal or sharp mood change. Early evaluation opens the door to cognitive-behavioural therapy (CBT), proven effective.'},
  causes:[
    {ic:'😨', t:{ar:'الخوفُ من العقابِ القاسي (الأشيع)',en:'Fear of harsh punishment (most common)'}},
    {ic:'🦸', t:{ar:'تضخيمُ الذاتِ والمباهاةُ أمام الأقران',en:'Self-inflation & boasting before peers'}},
    {ic:'👀', t:{ar:'طلبُ الانتباهِ وجذبُ اهتمامِ الوالدين',en:'Attention-seeking from the parents'}},
    {ic:'🧚', t:{ar:'الخيالُ غيرُ الناضجِ عند الصغار',en:'Immature imagination in the young'}},
    {ic:'🧎', t:{ar:'تقليدُ كذبِ الكبارِ ووعودِهم الكاذبة',en:'Imitating adults\u2019 lies & false promises'}},
    {ic:'🛟', t:{ar:'الهروبُ من مهمّةٍ أو موقفٍ مزعج',en:'Escaping a task or unpleasant situation'}},
  ],
  evidences:[
    {type:'hadith', text:{ar:'«عليكم بالصدقِ فإنّ الصدقَ يهدي إلى البرّ، وإنّ البرَّ يهدي إلى الجنّة».',en:'\u201cHold to truth, for truth guides to righteousness, & righteousness guides to Paradise.\u201d'}, ref:{ar:'متفق عليه',en:'Bukhari & Muslim'}, note:{ar:'الصدقُ طريقٌ، يُغرَس بالتعويدِ لا بالقهر.',en:'Truth is a path, planted by habit, not coercion.'}},
    {type:'hadith', text:{ar:'«من قال لصبيٍّ: تعالَ هاكَ، ثمّ لم يُعطِه، فهي كذبة».',en:'\u201cWhoever says to a child \u2018come, take this\u2019 then gives nothing \u2014 it is a lie.\u201d'}, ref:{ar:'أحمد',en:'Ahmad'}, note:{ar:'صدقُك مع طفلك أصلُ صدقِه معك.',en:'Your truth with your child is the root of his with you.'}},
    {type:'athar', text:{ar:'قالت عائشةُ رضي الله عنها: ما كان خُلقٌ أبغضَ إلى أصحابِ النبيِّ ﷺ من الكذب.',en:'\u2018A\u2019ishah said: no trait was more hateful to the Companions than lying.'}, ref:{ar:'الترمذيّ',en:'Tirmidhi'}, note:{ar:'بيئةٌ تُبغِض الكذبَ تصنع صادقين.',en:'A home that hates lying raises the truthful.'}},
  ],
  examples:[
    {title:{ar:'كسر كوبًا وأنكر',en:'He broke a cup & denied it'}, scene:{ar:'ترى الكوبَ مكسورًا وهو يقول «لم أفعل أنا!».',en:'You see the broken cup & he says \u201cit wasn\u2019t me!\u201d'},
      do:{ar:'لا تستجوبه. قل بهدوء: «الكوبُ انكسر، يحدث. تعالَ ننظّفه معًا، وفي المرّةِ القادمة احذر». وامدحه إن اعترف.',en:'Don\u2019t interrogate. Say calmly: \u201cthe cup broke, it happens. Let\u2019s clean it together, & be careful next time.\u201d Praise him if he admits it.'},
      dont:{ar:'لا تسأله «هل كسرتَه؟» وأنت تعرف، ولا تصرخ ولا تقل «كذّاب».',en:'Don\u2019t ask \u201cdid you break it?\u201d when you know, don\u2019t shout or say \u201cliar.\u201d'},
      root:{ar:'السؤالُ الفخُّ يصنع الكذب؛ الأمانُ يصنع الاعتراف.',en:'A trap-question makes lies; safety makes admissions.'}},
    {title:{ar:'يبالغ أمام أصدقائه',en:'He exaggerates before friends'}, scene:{ar:'يقول لأصحابه إنّ عنده سيّارةً طائرة.',en:'He tells his friends he has a flying car.'},
      do:{ar:'لاحقًا على انفراد، العب معه على حدودِ الخيالِ والواقع: «تتمنّى لو كانت لديك، أليس كذلك؟»، واغرس قيمةَ الصدقِ بلا تجريح.',en:'Later, privately, play with the line of fantasy & reality: \u201cyou wish you had one, right?\u201d & plant the value of truth without shaming.'},
      dont:{ar:'لا تفضحه أمام أصدقائه ولا تسخر منه.',en:'Don\u2019t expose him before his friends or mock him.'},
      root:{ar:'المبالغةُ طلبُ مكانة؛ عزّز قيمتَه الحقيقيّةَ يَكفُف.',en:'Exaggeration seeks status; affirm his real worth & it stops.'}},
  ],
  program:{
    name:{ar:'برنامجُ «بيتٌ آمنٌ للصدق» — ٤ أسابيع',en:'The \u201cHome Safe for Truth\u201d program \u2014 4 weeks'},
    intro:{ar:'هدفُ البرنامجِ نقلُ الطفلِ من الكذبِ خوفًا إلى الصدقِ أمانًا، عبر تغييرِ ردِّ فعلِك أنت أوّلًا.',
      en:'The program\u2019s goal: move the child from lying out of fear to truth out of safety, by changing your reaction first.'},
    steps:[
      {n:1,t:{ar:'الأسبوع ١: كُن قدوةَ الصدق',en:'Week 1: model truth'},d:{ar:'راقب وعودَك: لا تَعِد إلّا بما تفي به، واعترف بأخطائك أمامه («أخطأتُ، آسف»). الطفلُ يحفظ ما يرى.',en:'Watch your promises: promise only what you keep, & admit your own mistakes before him. He records what he sees.'}},
      {n:2,t:{ar:'الأسبوع ١–٢: ألغِ فخَّ السؤال',en:'Weeks 1\u20132: end trap-questions'},d:{ar:'إذا عرفتَ الحقيقةَ لا تستجوبه؛ صف ما حدث واطلب الإصلاح. لا تمنحه فرصةً للكذب.',en:'If you know the truth, don\u2019t interrogate; describe what happened & ask to fix it. Don\u2019t give him a chance to lie.'}},
      {n:3,t:{ar:'الأسبوع ٢: كافِئ الاعتراف',en:'Week 2: reward admission'},d:{ar:'كلّما صدَق — ولو في خطأ — خفِّف النتيجةَ وامدح شجاعةَ الصدقِ صراحةً. اجعل الصدقَ مُربِحًا.',en:'Whenever he tells the truth \u2014 even about a mistake \u2014 lighten the consequence & openly praise the courage. Make truth pay.'}},
      {n:4,t:{ar:'الأسبوع ٣: لوحةُ الصدق',en:'Week 3: a truth chart'},d:{ar:'ضع نجمةً كلَّ مرّةٍ يَصدُق فيها في موقفٍ صعب، مع مكافأةٍ أسبوعيّةٍ بسيطة.',en:'Add a star each time he tells the truth in a hard moment, with a small weekly reward.'}},
      {n:5,t:{ar:'الأسبوع ٣–٤: القصّةُ والقدوة',en:'Weeks 3\u20134: story & example'},d:{ar:'احكِ أسبوعيًّا قصّةً عن صدقِ النبيِّ ﷺ (الصادقُ الأمين) وثمرةِ الصدق، واربطها بحياتِه.',en:'Weekly, tell a story of the Prophet\u2019s ﷺ truthfulness (al-Sadiq al-Amin) & truth\u2019s fruit, tied to his life.'}},
      {n:6,t:{ar:'متابعةٌ مستمرّة',en:'Ongoing follow-up'},d:{ar:'بعد ٤ أسابيع: إن قلّ الكذبُ فاستمرّ. إن استمرّ يوميًّا بلا تحسّنٍ فاستشر مختصًّا.',en:'After 4 weeks: if lying drops, continue. If it persists daily with no improvement, consult a specialist.'}},
    ],
    tip:{ar:'<b>القاعدة:</b> عاقِب الكذبةَ بلطفٍ، وكافِئ الصدقَ بسخاء؛ يجب أن يشعر الطفلُ أنّ الصدقَ دائمًا أربحُ من الكذب.',
      en:'<b>The rule:</b> respond to lying gently & reward truth generously; the child must feel truth always pays more than lying.'},
  },
  checklist:[
    {ar:'أوفي بوعودي ولا أكذب أمام طفلي ولو مزاحًا',en:'I keep my promises & never lie before my child, even jokingly'},
    {ar:'لا أنصب له فخَّ السؤالِ حين أعرف الحقيقة',en:'I don\u2019t set trap-questions when I know the truth'},
    {ar:'أمدح اعترافَه بالخطأ أكثرَ ممّا أعاقب الخطأ',en:'I praise his admission more than I punish the mistake'},
    {ar:'لا أصفه أبدًا بـ«الكذّاب»؛ أصحّح القولَ لا الهُويّة',en:'I never call him \u201cliar\u201d; I correct the statement, not the identity'},
    {ar:'جعلتُ بيتي آمنًا: الصدقُ يخفّف العقابَ لا يضاعفه',en:'I made my home safe: truth lightens the consequence, not doubles it'},
    {ar:'أحكي قصصَ الصدقِ وأربطها بسيرةِ النبيِّ ﷺ',en:'I tell truth-stories tied to the Prophet\u2019s ﷺ life'},
    {ar:'أراقب: إن صحب الكذبَ سرقةٌ أو عدوانٌ أستشير مختصًّا',en:'I watch: if lying pairs with stealing/aggression I consult a specialist'},
  ],
});
