/* ============================================================
   ACTIVITIES — البيانات الكاملة لـ 50 نشاطاً
   كل نشاط: رقم، عنوان، آلية، أيقونة، صعوبة، حالة
   حالات: featured | normal | done | locked
   ============================================================ */

const SECTIONS = [
  {
    id: "worship",
    color: "peach",
    title: "العبادات والإيمان", titleEn: "Worship & Faith",
    sub: "الأركان، الأذكار، السنن، والقيم الإيمانية", subEn: "Pillars, dhikr, sunnahs & faith values",
    icon: "1",
    activities: [
      { n: 1,  t: "عجلة الأذكار", te: "Wheel of Dhikr",        m: "Wheel Spin Logic",     g: "wheel",    d: 1, status: "featured", href: "activities/wheel-of-dhikr.html" },
      { n: 2,  t: "ذاكرة الأسماء الحسنى", te: "Memory of the Beautiful Names", m: "Card Flip Engine",     g: "memory",   d: 2, status: "normal", href: "activities/memory-names.html" },
      { n: 3,  t: "ترتيب الوضوء", te: "Wudu Order",        m: "Drag & Drop API",      g: "wudu",     d: 1, status: "normal", href: "activities/wudu-order.html" },
      { n: 4,  t: "فرز حلال وحرام", te: "Sort Halal & Haram",      m: "Collision Detection",  g: "sort",     d: 2, status: "normal", href: "activities/sort-halal.html" },
      { n: 5,  t: "بناء المسجد", te: "Build the Mosque",         m: "Sticker Book Logic",   g: "mosque",   d: 2, status: "normal", href: "activities/build-mosque.html" },
      { n: 6,  t: "المحقّق الذكي", te: "The Smart Detective",        m: "Coordinates Mapping",  g: "spy",      d: 2, status: "normal", href: "activities/smart-detective.html" },
      { n: 7,  t: "متاهة الصدق", te: "Honesty Maze",         m: "Canvas Maze Gen",      g: "maze",     d: 3, status: "normal", href: "activities/honesty-maze.html" },
      { n: 8,  t: "ساعي بريد الجنة", te: "Paradise Postman",     m: "Form Handling",        g: "mail",     d: 1, status: "normal", href: "activities/paradise-post.html" },
      { n: 9,  t: "من هو النبي؟", te: "Who Is the Prophet?",        m: "Quiz Engine",          g: "quiz",     d: 2, status: "normal", href: "activities/prophet-quiz.html" },
      { n: 10, t: "تحدي السنن المنسية", te: "Forgotten Sunnahs Challenge",   m: "Hidden Object Logic",  g: "sunnah",   d: 3, status: "normal", href: "activities/hidden-sunnahs.html" },
    ],
  },
  {
    id: "language",
    color: "sky",
    title: "اللغة والمعرفة", titleEn: "Language & Knowledge",
    sub: "الكلمات، الحروف، الأحاديث والمعلومات", subEn: "Words, letters, hadith & knowledge",
    icon: "2",
    activities: [
      { n: 11, t: "تتبع الكلمات", te: "Word Tracing",         m: "SVG Path Tracing",    g: "trace",       d: 1, status: "normal", href: "activities/word-trace.html" },
      { n: 12, t: "كلمات متقاطعة مصورة", te: "Picture Crossword",   m: "Grid Logic",          g: "crossword",   d: 2, status: "normal", href: "activities/picture-crossword.html" },
      { n: 13, t: "شيفرة الأرقام", te: "Number Cipher",         m: "Mapping Logic",       g: "cipher",      d: 2, status: "normal", href: "activities/number-cipher.html" },
      { n: 14, t: "ترتيب الحديث الشريف", te: "Order the Hadith",   m: "Sortable List",       g: "hadith",      d: 2, status: "normal", href: "activities/hadith-order.html" },
      { n: 15, t: "شبكة البحث عن الكلمات", te: "Word Search Grid", m: "2D Array Grid",       g: "wordsearch",  d: 2, status: "normal", href: "activities/word-search.html" },
      { n: 16, t: "ترتيب الحروف المبعثرة", te: "Anagram Letters", m: "Anagram Solver",      g: "anagram",     d: 1, status: "normal", href: "activities/anagram.html" },
      { n: 17, t: "ألغاز الأدوات", te: "Tool Riddles",        m: "Riddles Engine",      g: "riddle",      d: 3, status: "normal", href: "activities/riddles.html" },
      { n: 18, t: "الحروف المختبئة", te: "Hidden Letters",      m: "Opacity & Seek",      g: "hidden",      d: 2, status: "normal", href: "activities/hidden-letters.html" },
      { n: 19, t: "الفوارق الخمسة", te: "Spot the Differences",      m: "Compare & Detect",    g: "diff",        d: 2, status: "normal", href: "activities/spot-differences.html" },
      { n: 20, t: "اختبار المعلومات السريع", te: "Quick Knowledge Quiz", m: "Timer-based Quiz",   g: "timedquiz",   d: 3, status: "normal", href: "activities/timed-quiz.html" },
    ],
  },
  {
    id: "art",
    color: "lavender",
    title: "الفن والإبداع", titleEn: "Art & Creativity",
    sub: "التلوين، التصميم، الأناشيد، والقصص", subEn: "Coloring, design, nasheeds & stories",
    icon: "3",
    activities: [
      { n: 21, t: "تلوين الزخارف الإسلامية", te: "Color Islamic Patterns", m: "Flood Fill Algorithm", g: "pattern",     d: 2, status: "normal", href: "activities/pattern-color.html" },
      { n: 22, t: "شجرة تتبع الصلاة", te: "Prayer Tracking Tree",      m: "Interactive SVG",     g: "tree",        d: 1, status: "normal", href: "activities/prayer-tree.html" },
      { n: 23, t: "مسرح العرائس", te: "Puppet Theater",         m: "Z-index Stage",       g: "theater",     d: 2, status: "normal", href: "activities/puppet-theater.html" },
      { n: 24, t: "مصمم السجادة", te: "Carpet Designer",          m: "Canvas Drawing",      g: "carpet",      d: 2, status: "normal", href: "activities/carpet-designer.html" },
      { n: 25, t: "كاريوكي الأناشيد", te: "Nasheed Karaoke",       m: "Synchronized Text",   g: "karaoke",     d: 1, status: "normal", href: "activities/nasheed-karaoke.html" },
      { n: 26, t: "تلوين الآيات", te: "Color the Ayahs",          m: "Pattern Fill",        g: "ayah",        d: 1, status: "normal", href: "activities/ayah-color.html" },
      { n: 27, t: "مفكرة الامتنان", te: "Gratitude Journal",        m: "CRUD Operations",     g: "gratitude",   d: 1, status: "normal", href: "activities/gratitude.html" },
      { n: 28, t: "خريطة الأنبياء", te: "Prophets' Map",        m: "Map Hotspots",        g: "map",         d: 3, status: "normal", href: "activities/prophet-map.html" },
      { n: 29, t: "تعهّد الصدق", te: "Honesty Pledge",           m: "Certificate Gen",     g: "certificate", d: 1, status: "normal", href: "activities/honesty-pledge.html" },
      { n: 30, t: "بنغو الصالحات", te: "Good Deeds Bingo",         m: "5×5 Grid Checker",    g: "bingo",       d: 2, status: "normal", href: "activities/good-bingo.html" },
    ],
  },
  {
    id: "science",
    color: "mint",
    title: "العلوم والاستكشاف", titleEn: "Science & Discovery",
    sub: "العالم من حولنا، المخلوقات، والكون", subEn: "The world around us, creatures & cosmos",
    icon: "4",
    activities: [
      { n: 31, t: "مختبر المخلوقات", te: "Creatures Lab",       m: "Step Animation",      g: "lab",         d: 2, status: "normal", href: "activities/creature-lab.html" },
      { n: 32, t: "فرز البر والبحر", te: "Land & Sea Sorting",       m: "Bucket Sorting",      g: "landsea",     d: 1, status: "normal", href: "activities/landsea.html" },
      { n: 33, t: "توفير المياه", te: "Save the Water",          m: "Timing Game",         g: "water",       d: 2, status: "normal", href: "activities/water-save.html" },
      { n: 34, t: "منظار النجوم", te: "Star Telescope",         m: "Parallax Scroll",     g: "telescope",   d: 3, status: "normal", href: "activities/star-telescope.html" },
      { n: 35, t: "دورة المطر", te: "The Rain Cycle",            m: "Flowchart Logic",     g: "cycle",       d: 2, status: "normal", href: "activities/rain-cycle.html" },
      { n: 36, t: "حقيبة الأخلاق", te: "The Akhlaq Bag",         m: "Card Deck Logic",     g: "bag",         d: 1, status: "normal", href: "activities/akhlaq-bag.html" },
      { n: 37, t: "أصحاب المهن النبوية", te: "Prophets' Professions",   m: "Matching Pairs",      g: "tool",        d: 2, status: "normal", href: "activities/prophet-professions.html" },
      { n: 38, t: "ماذا لو؟", te: "What If?",              m: "Scenario Branching",  g: "branch",      d: 3, status: "normal", href: "activities/what-if.html" },
      { n: 39, t: "أحجية المعالم", te: "Landmarks Puzzle",         m: "Jigsaw Puzzle",       g: "puzzle",      d: 3, status: "normal", href: "activities/landmarks-puzzle.html" },
      { n: 40, t: "شريط الزمن الهجري", te: "Hijri Timeline",     m: "Timeline Drag",       g: "timeline",    d: 2, status: "normal", href: "activities/hijri-timeline.html" },
    ],
  },
  {
    id: "challenges",
    color: "butter",
    title: "تحديات السيرة واللغة", titleEn: "Seerah & Language Challenges",
    sub: "ألعاب سريعة، تحديات، وألغاز ممتعة", subEn: "Quick games, challenges & fun puzzles",
    icon: "5",
    activities: [
      { n: 41, t: "صيد حروف المد", te: "Catch the Madd Letters",        m: "Falling Objects",     g: "catch",       d: 2, status: "normal", href: "activities/catch-madd.html" },
      { n: 42, t: "الكلمة وعكسها", te: "Word & Opposite",         m: "Connection Logic",    g: "opposite",    d: 1, status: "normal", href: "activities/opposite-words.html" },
      { n: 43, t: "لعبة الحركات", te: "Tashkeel Game",          m: "Vowel Placement",     g: "tashkeel",    d: 1, status: "normal", href: "activities/tashkeel-game.html" },
      { n: 44, t: "المقرأة الذكية", te: "Smart Reciter",        m: "Audio Comparison",    g: "speaker",     d: 3, status: "normal", href: "activities/smart-reciter.html" },
      { n: 45, t: "شجرة العائلة النبوية", te: "Prophetic Family Tree", m: "Hierarchy Tree",      g: "family",      d: 2, status: "normal", href: "activities/family-tree.html" },
      { n: 46, t: "بطل الأركان الخمسة", te: "Five Pillars Hero",    m: "2D Platformer",       g: "hero",        d: 3, status: "normal", href: "activities/pillars-hero.html" },
      { n: 47, t: "سودوكو إسلامي", te: "Islamic Sudoku",         m: "Logical Grid",        g: "sudoku",      d: 3, status: "normal", href: "activities/islamic-sudoku.html" },
      { n: 48, t: "تحدي الـ 30 ثانية", te: "30-Second Challenge",     m: "Click Counter",       g: "stopwatch",   d: 1, status: "normal", href: "activities/thirty-second.html" },
      { n: 49, t: "من أنا؟", te: "Who Am I?",               m: "Hint System",         g: "who",         d: 2, status: "normal", href: "activities/who-am-i.html" },
      { n: 50, t: "حقيبة المسافر", te: "Traveler's Bag",         m: "Inventory Mgmt",      g: "suitcase",    d: 2, status: "normal", href: "activities/traveler-bag.html" },
    ],
  },
  {
    id: "faith",
    color: "teal",
    title: "رحلة الإيمان", titleEn: "Journey of Faith",
    sub: "الحج، الصيام، الصلاة وأركان الإيمان", subEn: "Hajj, fasting, prayer & pillars of iman",
    icon: "6",
    activities: [
      { n: 51, t: "مناسك الحج الصغير", te: "The Little Pilgrim's Hajj", m: "Hajj Simulation", g: "kaaba", d: 2, status: "normal", href: "activities/hajj-sim.html" },
      { n: 52, t: "يوم مع الصائم", te: "A Day with a Fasting Kid", m: "Day-Cycle Sim", g: "fasting", d: 1, status: "normal", href: "activities/fasting-day.html" },
      { n: 53, t: "مهمة القِبلة", te: "Qibla Quest", m: "Compass Physics", g: "compass", d: 2, status: "normal", href: "activities/qibla-quest.html" },
      { n: 54, t: "حصّالة الزكاة", te: "The Zakat Jar", m: "Coin Physics", g: "jar", d: 1, status: "normal", href: "activities/zakat-jar.html" },
      { n: 55, t: "رحلة الروح الطيبة", te: "The Good Soul's Journey", m: "Branching Story", g: "soul", d: 2, status: "normal", href: "activities/soul-journey.html" },
      { n: 56, t: "صدى الأذان", te: "Echo of the Adhan", m: "Listen & Repeat", g: "adhan", d: 2, status: "normal", href: "activities/adhan-echo.html" },
      { n: 57, t: "ميزان الحسنات", te: "The Scale of Good Deeds", m: "Balance Physics", g: "scale", d: 1, status: "normal", href: "activities/deeds-scale.html" },
      { n: 58, t: "نجوم الصلوات الخمس", te: "The Five Prayer Stars", m: "Orbit Puzzle", g: "orbit", d: 2, status: "normal", href: "activities/prayer-orbit.html" },
      { n: 59, t: "سباق الفجر", te: "Fajr Dash", m: "Jump & Run", g: "run", d: 2, status: "normal", href: "activities/fajr-run.html" },
      { n: 60, t: "غرفة أركان الإيمان", te: "The Room of the Pillars of Iman", m: "Escape Room", g: "escape", d: 3, status: "normal", href: "activities/iman-room.html" },
    ],
  },
  {
    id: "wahy",
    color: "sand",
    title: "كنوز الوحي", titleEn: "Treasures of Revelation",
    sub: "القرآن، التجويد، الحديث والحفظ", subEn: "Qur'an, tajweed, hadith & memorization",
    icon: "7",
    activities: [
      { n: 61, t: "المقرئ الصغير", te: "The Little Reciter's Studio", m: "Record & Compare", g: "mic", d: 2, status: "normal", href: "activities/qari-studio.html" },
      { n: 62, t: "سلسلة الإسناد", te: "The Golden Chain", m: "Chain Builder", g: "chain", d: 2, status: "normal", href: "activities/isnad-chain.html" },
      { n: 63, t: "بستان السور", te: "The Surah Garden", m: "Garden Grower", g: "garden", d: 1, status: "normal", href: "activities/surah-garden.html" },
      { n: 64, t: "قطار الآيات", te: "The Ayah Train", m: "Train Ordering", g: "train", d: 1, status: "normal", href: "activities/ayah-train.html" },
      { n: 65, t: "مختبر التجويد", te: "The Tajweed Sound Lab", m: "Sound-Wave Lab", g: "wave", d: 3, status: "normal", href: "activities/tajweed-lab.html" },
      { n: 66, t: "صيّاد المعاني", te: "The Meaning Catcher", m: "Word Catch", g: "net", d: 2, status: "normal", href: "activities/meaning-catch.html" },
      { n: 67, t: "مشكاة الحديث", te: "The Lantern of Hadith", m: "Scenario Story", g: "lantern", d: 2, status: "normal", href: "activities/hadith-lantern.html" },
      { n: 68, t: "فسيفساء جزء عمّ", te: "The Juz Amma Mosaic", m: "Mosaic Builder", g: "mosaic", d: 2, status: "normal", href: "activities/juz-mosaic.html" },
      { n: 69, t: "أذن الحافظ", te: "The Hafiz's Ear", m: "Audio Detective", g: "ear", d: 3, status: "normal", href: "activities/hafiz-ear.html" },
      { n: 70, t: "إشارة الوقف والوصل", te: "Stop & Continue Signals", m: "Reflex Signals", g: "signal", d: 1, status: "normal", href: "activities/waqf-signals.html" },
    ],
  },
  {
    id: "qudwa",
    color: "coral",
    title: "على خطى القدوات", titleEn: "In the Footsteps of Role Models",
    sub: "السيرة، الصحابة، والحضارة الإسلامية", subEn: "Seerah, companions & Islamic civilization",
    icon: "8",
    activities: [
      { n: 71, t: "رحلة الهجرة", te: "The Hijrah Journey", m: "Branching Adventure", g: "route", d: 2, status: "normal", href: "activities/hijrah-journey.html" },
      { n: 72, t: "مجلس الصحابة", te: "The Companions' Duel", m: "2-Player Duel", g: "duel", d: 2, status: "normal", href: "activities/sahaba-duel.html" },
      { n: 73, t: "مخترعو الحضارة", te: "Inventors of Civilization", m: "Invention Lab", g: "invent", d: 2, status: "normal", href: "activities/invention-lab.html" },
      { n: 74, t: "سوق المدينة", te: "The Madinah Market", m: "Market Simulation", g: "market", d: 2, status: "normal", href: "activities/madinah-market.html" },
      { n: 75, t: "فرسان القصص", te: "Story Knights Theater", m: "Story Theater", g: "stage", d: 1, status: "normal", href: "activities/story-theater.html" },
      { n: 76, t: "خطى الفاتحين", te: "Paths of the Openers", m: "Map Timeline", g: "conquest", d: 3, status: "normal", href: "activities/conquest-map.html" },
      { n: 77, t: "مكتبة بيت الحكمة", te: "The House of Wisdom Library", m: "Book Sorting", g: "library", d: 2, status: "normal", href: "activities/hikmah-library.html" },
      { n: 78, t: "بطاقات القدوة", te: "Role-Model Collectible Cards", m: "Collectible Cards", g: "cards", d: 1, status: "normal", href: "activities/qudwa-cards.html" },
      { n: 79, t: "راوي السيرة", te: "The Seerah Narrator", m: "Audio Storybook", g: "narrator", d: 1, status: "normal", href: "activities/seerah-narrator.html" },
      { n: 80, t: "حفر الخندق", te: "Digging the Trench", m: "Dig Physics", g: "dig", d: 2, status: "normal", href: "activities/trench-dig.html" },
    ],
  },
  {
    id: "ghad",
    color: "olive",
    title: "صنّاع الغد", titleEn: "Makers of Tomorrow",
    sub: "القيادة، الرياضة، الإبداع والعطاء", subEn: "Leadership, sports, creativity & giving",
    icon: "9",
    activities: [
      { n: 81, t: "مهندس المآذن", te: "The Minaret Engineer", m: "Block Building", g: "minaret", d: 2, status: "normal", href: "activities/minaret-builder.html" },
      { n: 82, t: "قائد الفريق", te: "The Team Leader", m: "Leadership Scenarios", g: "leader", d: 2, status: "normal", href: "activities/team-leader.html" },
      { n: 83, t: "سباق الفروسية", te: "The Horse Race", m: "Gallop & Jump", g: "horse", d: 2, status: "normal", href: "activities/horse-race.html" },
      { n: 84, t: "رماية السهام", te: "Archery", m: "Archery Physics", g: "bow", d: 2, status: "normal", href: "activities/archery.html" },
      { n: 85, t: "استوديو النشيد", te: "The Nasheed Studio", m: "Rhythm Composer", g: "notes", d: 2, status: "normal", href: "activities/nasheed-studio.html" },
      { n: 86, t: "سبّاح النهر", te: "The River Swimmer", m: "Rhythm Swimming", g: "swim", d: 2, status: "normal", href: "activities/river-swim.html" },
      { n: 87, t: "مصنع الأفكار", te: "The Idea Factory", m: "Idea Combiner", g: "idea", d: 2, status: "normal", href: "activities/idea-factory.html" },
      { n: 88, t: "خيمة القيادة", te: "The Leadership Tent", m: "2-Player Strategy", g: "tent", d: 3, status: "normal", href: "activities/leadership-tent.html" },
      { n: 89, t: "حديقة العطاء", te: "The Garden of Giving", m: "Care & Grow", g: "plant", d: 1, status: "normal", href: "activities/giving-garden.html" },
      { n: 90, t: "عدّاء الخير", te: "The Good Deeds Runner", m: "Endless Runner", g: "runner", d: 2, status: "normal", href: "activities/good-runner.html" },
    ],
  },
  {
    id: "ummah",
    color: "berry",
    title: "أمتي الواحدة", titleEn: "My One Ummah",
    sub: "القدس، فلسطين، ووحدة الأمة", subEn: "Al-Quds, Palestine & the unity of the Ummah",
    icon: "10",
    activities: [
      { n: 91, t: "حارس القدس الصغير", te: "The Little Guardian of Al-Quds", m: "Interactive Story", g: "dome", d: 2, status: "normal", href: "activities/quds-guardian.html" },
      { n: 92, t: "مفتاح العودة", te: "The Key of Return", m: "Key Puzzle Journey", g: "key", d: 2, status: "normal", href: "activities/return-key.html" },
      { n: 93, t: "زيتونة فلسطين", te: "The Olive of Palestine", m: "Tree Care Sim", g: "olive", d: 1, status: "normal", href: "activities/olive-tree.html" },
      { n: 94, t: "جسور الأمة", te: "Bridges of the Ummah", m: "Bridge Physics", g: "bridge", d: 2, status: "normal", href: "activities/ummah-bridge.html" },
      { n: 95, t: "قافلة الخير", te: "The Convoy of Good", m: "Convoy Simulation", g: "convoy", d: 2, status: "normal", href: "activities/aid-convoy.html" },
      { n: 96, t: "فسيفساء الأقصى", te: "The Al-Aqsa Jigsaw", m: "Jigsaw Builder", g: "jigsaw", d: 2, status: "normal", href: "activities/aqsa-jigsaw.html" },
      { n: 97, t: "أطفال العالم المسلم", te: "Children of the Muslim World", m: "Culture Match", g: "globe", d: 1, status: "normal", href: "activities/muslim-kids.html" },
      { n: 98, t: "إذاعة الأمة", te: "Ummah Radio Studio", m: "Broadcast Studio", g: "radio", d: 2, status: "normal", href: "activities/ummah-radio.html" },
      { n: 99, t: "سفير السلام", te: "The Peace Envoy", m: "Diplomacy Story", g: "dove", d: 2, status: "normal", href: "activities/peace-envoy.html" },
      { n: 100, t: "نسيج الأمة الواحد", te: "The One Ummah Weave", m: "2-Player Weaving", g: "weave", d: 2, status: "normal", href: "activities/ummah-weave.html" },
    ],
  },
];

window.SECTIONS = SECTIONS;
