/* stage-1.js — المرحلة الأولى · 0–3 · الحضن والأمان */
window.TARBIYAH.stages.push({
  id:'s1', age:'0–3', ic:'🍼', c:'#1A9B7B',
  nm:{ar:'الحضنُ والأمان', en:'Bonding & Security'},
  sub:{ar:'مرحلةُ الرضاعة والحضانة — بناءُ الثقةِ الأولى', en:'Infancy — building the first trust'},
  intro:{ar:'في هذه السنواتِ الثلاثِ الأولى لا نُعلّم الطفلَ عقيدةً ولا نأمره بعبادة؛ إنّما نبني الأرضَ التي سيُغرَس فيها كلُّ ذلك لاحقًا: الأمانَ، والثقةَ، والرابطةَ الدافئةَ بالوالدين. هي مرحلةُ «اللعبِ» الأولى في الهَدي النبويّ، ومرحلةُ «الثقةِ» في علم النفس. كلُّ حضنٍ، وكلُّ استجابةٍ لبكاءٍ، وكلُّ كلمةٍ هادئة، لبنةٌ في قلبٍ سيُحبُّ اللهَ لأنّه عرف الحبَّ أوّلًا من أبويه.',
    en:'In these first three years we teach no creed and command no worship; we build the soil in which all that will later be planted: security, trust, and a warm bond with the parents. It is the first \u201cplay\u201d stage in the prophetic guidance, and the stage of \u201ctrust\u201d in psychology. Every hug, every answered cry, every calm word is a brick in a heart that will love Allah because it first knew love from its parents.'},
  glance:[
    {ic:'⏳', k:{ar:'جرعةُ الوقت',en:'Time dose'}, v:{ar:'حضورٌ شبهُ دائم + لمسٌ كثيرٌ كلَّ يوم',en:'Near-constant presence + much daily touch'}},
    {ic:'🎯', k:{ar:'المهمّةُ الكبرى',en:'Core task'}, v:{ar:'بناءُ التعلّقِ الآمن',en:'Build secure attachment'}},
    {ic:'🚫', k:{ar:'الخطُّ الأحمر',en:'Red line'}, v:{ar:'لا شاشاتٍ قبل العامين',en:'No screens before age 2'}},
    {ic:'🗝️', k:{ar:'الكلمةُ المفتاح',en:'Keyword'}, v:{ar:'الرحمة',en:'Mercy'}},
  ],
  scholar:{ar:'مرحلةُ الرحمةِ المطلقة. هَديُ النبيِّ ﷺ يبدأ من أوّل لحظة: التأذينُ في أُذنِ المولود، والتسميةُ الحسنة، والعقيقةُ والتحنيكُ، والرضاعةُ والحِضنُ والتقبيل. لمّا رأى الأقرعُ بنُ حابسٍ النبيَّ ﷺ يُقبّل الحسنَ قال: «إنّ لي عشرةً من الولدِ ما قبّلتُ منهم أحدًا!» فقال ﷺ: «مَن لا يَرحمْ لا يُرحَم».\n\nقرّر العلماءُ أنّ الطفلَ في هذه السنّ غيرُ مكلّفٍ ولا مأمور؛ فلا صلاةَ تُطلَب ولا أدبَ يُفرَض بالقوّة، إنّما يُروى قلبُه بالحبِّ ويُعوَّد سماعَ اسمِ اللهِ في جوٍّ من الطمأنينة. قال ابنُ القيّم في «تحفة المودود» إنّ صلاحَ الولدِ يبدأ من حُسنِ اختيارِ الأمّ، ثمّ الرحمةِ به والعنايةِ بغذائه ونومِه وطهارته. فالعنايةُ الجسديّةُ هنا عبادةٌ، والحنانُ تربيةٌ، والبيتُ الهادئُ المذكورُ فيه اسمُ الله هو أوّلُ مدرسة.',
    en:'The stage of pure mercy. The Prophet\u2019s ﷺ guidance begins at the first moment: the adhan in the newborn\u2019s ear, a good name, the \u2018aqiqah and tahnik, breastfeeding, holding and kissing. When al-Aqra\u2019 saw the Prophet ﷺ kiss al-Hasan he said, \u201cI have ten children and have never kissed one!\u201d The Prophet ﷺ replied: \u201cHe who shows no mercy is shown none.\u201d\n\nThe scholars held that at this age the child is neither accountable nor commanded; no prayer is demanded and no adab is forced — his heart is watered with love and accustomed to hearing Allah\u2019s name in an atmosphere of calm. Ibn al-Qayyim in \u201cTuhfat al-Mawdud\u201d says the child\u2019s soundness begins with choosing a good mother, then mercy and care for his food, sleep and cleanliness. Here physical care is worship, tenderness is nurture, and a calm home in which Allah\u2019s name is mentioned is the first school.'},
  psych:{ar:'يصف إريك إريكسون أوّلَ مهمّةٍ نفسيّةٍ في الحياة بأنّها «الثقةُ مقابل الريبة» (٠–١٫٥)، تليها «الاستقلالُ مقابل الخجلِ والشكّ» (١٫٥–٣). حين يستجيب الوالدُ لبكاءِ الرضيعِ وجوعِه وخوفِه بثباتٍ، يتكوّن لديه «نموذجٌ داخليٌّ» مفادُه: العالمُ آمنٌ، وأنا محبوبٌ، وحاجاتي تُلبّى. هذا هو «التعلّقُ الآمن» الذي وصفه جون بولبي، وهو الأساسُ النفسيُّ لكلِّ علاقةٍ لاحقة — بل لعلاقتِه بربِّه.\n\nالدماغُ في هذه السنوات ينمو أسرعَ من أيِّ وقتٍ لاحق؛ تتكوّن ملايينُ الوصلاتِ العصبيّةِ عبر اللمسِ والصوتِ والنظرِ والكلام. لذلك فالحضنُ ليس تدليلًا بل غذاءٌ عصبيّ، والروتينُ الثابتُ ليس رفاهيّةً بل أمانٌ يخفّض هرموناتِ التوتّر. والحرمانُ العاطفيُّ أو كثرةُ الشاشاتِ في هذه السنِّ تُضعِف اللغةَ والانتباهَ والرابطةَ بشكلٍ يصعب تداركُه.',
    en:'Erikson describes life\u2019s first psychological task as \u201ctrust vs mistrust\u201d (0\u20131.5), followed by \u201cautonomy vs shame & doubt\u201d (1.5\u20133). When a parent answers the infant\u2019s crying, hunger and fear consistently, an \u201cinternal working model\u201d forms: the world is safe, I am loved, my needs are met. This is Bowlby\u2019s \u201csecure attachment,\u201d the psychological foundation of every later relationship \u2014 even his relationship with his Lord.\n\nThe brain grows faster now than ever again; millions of neural connections form through touch, sound, gaze and speech. So holding is not spoiling but neural nourishment; a steady routine is not a luxury but a safety that lowers stress hormones. Emotional neglect or heavy screens at this age weaken language, attention and bonding in ways hard to undo.'},
  specialists:[
    {q:{ar:'«الطفلُ يُولَد بخزّانِ حبٍّ يحتاج أن يُملأ؛ فإن مُلئ في الصِّغرِ فاض في الكِبر».',en:'\u201cA child is born with a love-tank that must be filled; filled young, it overflows when grown.\u201d'}, by:{ar:'من تربية الطفولة المبكّرة',en:'Early-childhood education'}},
    {q:{ar:'«لا يُفسِد الرضيعَ حملُه؛ المبالغةُ في تركِه يبكي هي ما يُفسِد إحساسَه بالأمان».',en:'\u201cHolding an infant does not spoil him; leaving him to cry is what damages his sense of safety.\u201d'}, by:{ar:'جون بولبي · نظريّة التعلّق',en:'John Bowlby · attachment theory'}},
    {q:{ar:'«الاستجابةُ الثابتةُ تصنع طفلًا هادئًا؛ التذبذبُ بين الإهمالِ والإغراقِ يصنع طفلًا قلِقًا».',en:'\u201cConsistent response makes a calm child; swinging between neglect & smothering makes an anxious one.\u201d'}, by:{ar:'علم نفس النموّ',en:'Developmental psychology'}},
  ],
  evidences:[
    {type:'hadith', text:{ar:'«مَن لا يَرحمِ الناسَ لا يَرحمْه الله».',en:'\u201cHe who does not show mercy to people, Allah will not show mercy to him.\u201d'}, ref:{ar:'متفق عليه',en:'Bukhari & Muslim'}, note:{ar:'أصلُ المرحلة: الرحمةُ لا التكليف.',en:'The stage\u2019s root: mercy, not obligation.'}},
    {type:'hadith', text:{ar:'«ما نَحَلَ والدٌ ولدًا من نَحْلٍ أفضلَ من أدبٍ حسن».',en:'\u201cNo father gives his child a gift better than good manners.\u201d'}, ref:{ar:'الترمذيّ',en:'Tirmidhi'}, note:{ar:'والأدبُ يبدأ بالقدوةِ والجوِّ لا بالأمر.',en:'And adab begins with example & atmosphere, not commands.'}},
    {type:'athar', text:{ar:'كان النبيُّ ﷺ يُصلّي فإذا سجد ركِب الحسنُ والحسينُ ظهرَه، فيُطيل السجودَ رفقًا بهما.',en:'The Prophet ﷺ would prolong his prostration when al-Hasan & al-Husayn climbed his back, out of gentleness to them.'}, ref:{ar:'النسائيّ',en:'al-Nasa\u2019i'}, note:{ar:'الرفقُ بالصغيرِ يُقدَّم حتى في العبادة.',en:'Gentleness to the small is honoured even within worship.'}},
  ],
  rewards:[
    {ic:'🌳', t:{ar:'صدقةٌ جاريةٌ وولدٌ صالح',en:'Ongoing charity & a righteous child'}, d:{ar:'كلُّ لبنةِ أمانٍ تضعها اليومَ تُثمِر ولدًا صالحًا يدعو لك بعد موتك.',en:'Every brick of security you lay today yields a righteous child who prays for you after you die.'}},
    {ic:'💞', t:{ar:'رحمةٌ تُجزى بمثلها',en:'Mercy repaid in kind'}, d:{ar:'«مَن لا يَرحمْ لا يُرحَم»؛ ورحمتُك بطفلك بابٌ لرحمةِ اللهِ بك.',en:'\u201cWho shows no mercy is shown none\u201d; your mercy to him is a door to Allah\u2019s mercy to you.'}},
    {ic:'🕊️', t:{ar:'طفلٌ مطمئنٌّ يثق بالله',en:'A settled child who trusts Allah'}, d:{ar:'القلبُ الذي عرف الأمانَ من أبويه يسهُل أن يطمئنَّ لربِّه ويُحسِن الظنَّ به.',en:'A heart that knew safety from its parents settles easily with its Lord.'}},
  ],
  needs:[
    {ar:'الرضاعةُ والتغذيةُ السليمةُ والنومُ المنتظم',en:'Breastfeeding, sound nutrition & regular sleep'},
    {ar:'الحضنُ واللمسُ والاستجابةُ الفوريّةُ للبكاء',en:'Holding, touch & prompt response to crying'},
    {ar:'ثباتُ الروتينِ ووجوهٌ مألوفةٌ قليلةُ التبديل',en:'A stable routine & few, familiar caregivers'},
    {ar:'سماعُ القرآنِ والأذكارِ بصوتٍ هادئٍ في البيت',en:'Hearing Qur\u2019an & adhkar calmly at home'},
    {ar:'تنبيهٌ حسّيٌّ آمن: كلامٌ، ألوانٌ، لعبٌ بسيط',en:'Safe sensory input: talk, colours, simple play'},
    {ar:'بيئةٌ آمنةٌ من الإصابات ومن التوتّرِ والصراخ',en:'An environment safe from injury, tension & shouting'},
  ],
  risks:[
    {ar:'الإهمالُ العاطفيُّ وتركُ البكاءِ بلا استجابة',en:'Emotional neglect & unanswered crying'},
    {ar:'الشاشاتُ المبكّرة (تأخّرُ اللغةِ والانتباه)',en:'Early screens (language & attention delay)'},
    {ar:'القسوةُ والصراخُ وعدمُ ثباتِ المربّي',en:'Harshness, shouting & an inconsistent caregiver'},
    {ar:'كثرةُ تبديلِ الحاضنين وعدمُ الاستقرار',en:'Frequent change of caregivers & instability'},
    {ar:'إهمالُ النومِ المنتظمِ والتغذيةِ السليمة',en:'Neglecting regular sleep & sound nutrition'},
    {ar:'توتّرُ البيتِ وخلافاتُ الوالدينِ أمامه',en:'A tense home & parents quarrelling before him'},
  ],
  values:[
    {ar:'الأمانُ والطمأنينةُ الداخليّة',en:'Security & inner calm'},
    {ar:'الثقةُ بالوالدينِ وبالعالم',en:'Trust in the parents & the world'},
    {ar:'الرحمةُ والحنانُ المتبادل',en:'Mutual mercy & tenderness'},
    {ar:'ارتباطُ اسمِ اللهِ بالحبِّ والدفء',en:'Linking Allah\u2019s name to love & warmth'},
  ],
  dose:{ar:'لا يُقاس وقتُ هذه المرحلةِ بالدقائق بل بالحضور: ليكن الطفلُ في حِضنٍ دافئٍ معظمَ يومه. الأبُ خصوصًا: ٣٠–٦٠ دقيقةً يوميًّا من اللمسِ المباشرِ (حمل، تدليك، ملاعبة، تغيير) تبني رابطةً لا تُعوَّض، وتُثبت أنّ الأمومةَ ليست وحدها.',
    en:'This stage\u2019s time is measured not in minutes but in presence: keep the child in a warm embrace most of his day. The father especially: 30\u201360 min daily of direct touch (carrying, massage, play, changing) builds an irreplaceable bond and shows fathering is not the mother\u2019s job alone.'},
  daily:[
    {t:{ar:'الاستيقاظ',en:'Waking'}, dur:{ar:'١٠ د',en:'10 min'}, act:{ar:'وجهٌ مبتسمٌ، دعاءُ الاستيقاظ يُتلى عليه، حضنُ الصباح',en:'A smiling face, the waking du\u2019a read over him, a morning hug'}, who:{ar:'الأم/الأب',en:'Mother/Father'}},
    {t:{ar:'اللعبُ الحسّيّ',en:'Sensory play'}, dur:{ar:'٢٠ د ×٢',en:'20 min ×2'}, act:{ar:'أصواتٌ، ألوانٌ، تسميةُ الأشياء، «أين أنفُك؟»',en:'Sounds, colours, naming objects, \u201cwhere\u2019s your nose?\u201d'}, who:{ar:'الأب',en:'Father'}},
    {t:{ar:'الطعام',en:'Meals'}, dur:{ar:'حسب الحاجة',en:'as needed'}, act:{ar:'التسميةُ بصوتٍ مسموع، طعامٌ هادئٌ بلا شاشة',en:'Bismillah aloud, calm screen-free feeding'}, who:{ar:'الأم/الأب',en:'Mother/Father'}},
    {t:{ar:'القيلولة/النوم',en:'Nap/Sleep'}, dur:{ar:'ثابت',en:'fixed'}, act:{ar:'طقسُ نومٍ ثابت: أذكارُ النوم، صوتٌ هادئ، ربتة',en:'A fixed sleep ritual: sleep adhkar, a soft voice, a pat'}, who:{ar:'الأم/الأب',en:'Mother/Father'}},
    {t:{ar:'حضنُ المساء',en:'Evening cuddle'}, dur:{ar:'١٥ د',en:'15 min'}, act:{ar:'تلاوةٌ هادئةٌ أو أناشيدُ فطريّة، احتضانٌ قبل النوم',en:'Calm recitation or gentle nasheed, a pre-sleep cuddle'}, who:{ar:'الأب',en:'Father'}},
  ],
  weekly:[
    {d:{ar:'يوميًّا',en:'Daily'}, act:{ar:'حضنٌ ولمسٌ كثير + تلاوةٌ تُسمَع + روتينٌ ثابت',en:'Much holding & touch + audible recitation + steady routine'}},
    {d:{ar:'٣ مرّات/أسبوع',en:'3×/week'}, act:{ar:'خروجٌ قصيرٌ للهواءِ الطلق وتنبيهٌ بصريٌّ جديد',en:'A short outdoor outing & fresh visual stimulation'}},
    {d:{ar:'الجمعة',en:'Friday'}, act:{ar:'طقسٌ أسريٌّ ثابت: غسلٌ وطيبٌ وأجواءُ فرحٍ يربطها بالجمعة',en:'A fixed family ritual: bathing, scent & joy tied to Jumu\u2019ah'}},
  ],
  fatherFocus:{ar:'كثيرٌ من الآباء يظنّ أنّ هذه المرحلةَ «أمومةٌ خالصة»؛ وهذا خطأ. الأبُ الذي يحمل ويُبدّل ويُلاعب ويُهدهد يبني رابطةً تحميه لاحقًا في المراهقة. خصِّص نافذتَين يوميًّا (صباحًا ومساءً) للمسٍ مباشرٍ ولعبٍ وجهًا لوجه؛ ودَع أمَّه ترتاح. حضورُك المبكّرُ هو أوّلُ رسالةٍ بأنّك أبٌ موجود.',
    en:'Many fathers think this stage is \u201cpure mothering\u201d \u2014 a mistake. A father who carries, changes, plays and soothes builds a bond that will protect him later in adolescence. Set two daily windows (morning & evening) for direct touch and face-to-face play; and give the mother rest. Your early presence is the first message that you are a present father.'},
  activities:[
    {ic:'🤲', t:{ar:'التلاوةُ الهادئة',en:'Calm recitation'}, how:{ar:'اقرأ الفاتحةَ وقصارَ السورِ بصوتٍ منخفضٍ أثناء حملِه أو إنامته.',en:'Recite al-Fatihah & short surahs softly while holding or settling him.'}, why:{ar:'يألف صوتَ القرآنِ ويرتبط بالسكينة.',en:'He grows familiar with the Qur\u2019an, linked to calm.'}},
    {ic:'👀', t:{ar:'لعبةُ الوجوه',en:'The face game'}, how:{ar:'قرِّب وجهَك، ابتسِم، أخرِج لسانَك، كرِّر اسمَه — انتظر تفاعلَه.',en:'Bring your face close, smile, stick out your tongue, repeat his name \u2014 wait for his response.'}, why:{ar:'يبني التواصلَ البصريَّ واللغةَ المبكّرة.',en:'Builds eye contact & early language.'}},
    {ic:'🎵', t:{ar:'أناشيدُ الفطرة',en:'Gentle nasheed'}, how:{ar:'غنِّ له أناشيدَ هادئةً وأنت تحمله وتتمايل برفق.',en:'Sing calm nasheed while holding & gently swaying him.'}, why:{ar:'يهدّئ، ويبني الإيقاعَ واللغة.',en:'Soothes, and builds rhythm & language.'}},
    {ic:'🧺', t:{ar:'تسميةُ العالم',en:'Naming the world'}, how:{ar:'سَمِّ كلَّ شيءٍ تمرّ به: «هذا ماء، هذه تفاحة، قال اللهُ خلقها».',en:'Name everything you pass: \u201cthis is water, an apple \u2014 Allah made it.\u201d'}, why:{ar:'يفجّر اللغةَ ويغرس أنّ اللهَ خالقُ كلِّ شيء.',en:'Explodes language & plants that Allah made everything.'}},
    {ic:'🚶', t:{ar:'مشيُ الطبيعة',en:'A nature walk'}, how:{ar:'احمِله في نزهةٍ قصيرةٍ وأرِه الشجرَ والطيرَ والسماء.',en:'Carry him on a short walk, show him trees, birds, sky.'}, why:{ar:'تنبيهٌ حسّيٌّ صحّيٌّ بديلٌ عن الشاشة.',en:'Healthy sensory input instead of a screen.'}},
  ],
  examples:[
    {title:{ar:'الرضيعُ يبكي ليلًا',en:'The baby cries at night'}, scene:{ar:'يستيقظ باكيًا للمرّةِ الثالثة وأنت مُنهَك.',en:'He wakes crying a third time and you\u2019re exhausted.'},
      do:{ar:'احمِله بهدوءٍ، تحقّق من حاجتِه (جوع/حفاض/حرارة)، اقرأ المعوّذاتِ عليه برفقٍ حتى يطمئن.',en:'Pick him up calmly, check his need (hunger/diaper/temperature), recite the mu\u2019awwidhat over him gently until he settles.'},
      dont:{ar:'لا تتركه يبكي طويلًا «ليتعوّد»، ولا تهزّه بعنفٍ، ولا تُظهِر غضبَك.',en:'Don\u2019t leave him crying long \u201cto toughen him,\u201d don\u2019t shake him, don\u2019t show anger.'},
      root:{ar:'البكاءُ لغتُه الوحيدة؛ الاستجابةُ تبني الثقةَ لا الدلال.',en:'Crying is his only language; responding builds trust, not spoiling.'}},
    {title:{ar:'يرفض الطعامَ الجديد',en:'He refuses new food'}, scene:{ar:'يبصق الطعامَ الجديدَ ويبكي.',en:'He spits out new food and cries.'},
      do:{ar:'قدِّمه مرّاتٍ متعدّدةً بهدوءٍ وبكمّياتٍ صغيرة، وكُل أمامه بشهيّةٍ، وسمِّ الله.',en:'Offer it calmly many times in tiny amounts, eat it before him with relish, & say Bismillah.'},
      dont:{ar:'لا تُجبره بالقوّةِ ولا تُهدّده ولا تربط الطعامَ بالعقاب.',en:'Don\u2019t force-feed, threaten, or tie food to punishment.'},
      root:{ar:'النفورُ من الجديدِ طبيعيٌّ؛ التكرارُ الهادئُ يحلّه.',en:'Aversion to novelty is normal; calm repetition resolves it.'}},
  ],
  problems:[
    {p:{ar:'نوباتُ البكاءِ الشديدةُ والتعلّقُ المفرط',en:'Intense crying spells & clinginess'},
      why:{ar:'حاجةٌ للأمانِ غيرُ مُشبَعة، أو تعبٌ/جوع، أو قلقُ انفصال (طبيعيٌّ ٨–١٨ شهرًا).',en:'An unmet need for safety, tiredness/hunger, or separation anxiety (normal at 8\u201318 months).'},
      islamic:{ar:'الرفقُ سُنّةٌ؛ «إنّ الرفقَ لا يكون في شيءٍ إلّا زانه». احتسب صبرَك أجرًا.',en:'Gentleness is sunnah; \u201cgentleness beautifies whatever it is in.\u201d Count your patience as reward.'},
      psych:{ar:'التعلّقُ ليس ضعفًا بل علامةُ رابطةٍ صحّية؛ يُعالَج بالحضورِ المطمئنِّ لا بالدفع.',en:'Attachment is not weakness but a sign of a healthy bond; treated by reassuring presence, not pushing away.'},
      steps:[{ar:'احتضنه وسمِّ شعورَه بصوتٍ هادئ.',en:'Hold him & name his feeling calmly.'},{ar:'ثبِّت الروتينَ ومواعيدَ النومِ والطعام.',en:'Stabilize routine, sleep & meal times.'},{ar:'ودِّعه ودّاعًا قصيرًا واثقًا عند الانفصالِ، ولا تتسلّل.',en:'Say a short, confident goodbye when leaving \u2014 never sneak away.'},{ar:'إن استمرّ شديدًا مع شحوبٍ أو فقدِ وزنٍ راجِع الطبيب.',en:'If severe with pallor/weight loss, see a doctor.'}]},
    {p:{ar:'اضطرابُ النومِ ومقاومتُه',en:'Sleep disruption & resistance'},
      why:{ar:'غيابُ طقسِ نومٍ ثابت، أو شاشاتٌ مساءً، أو إفراطٌ في التنبيه.',en:'No fixed sleep ritual, evening screens, or over-stimulation.'},
      islamic:{ar:'اقرأ آيةَ الكرسيِّ والمعوّذاتِ ونفِّث عليه؛ سنّةٌ تجمع البركةَ والطمأنينة.',en:'Recite Ayat al-Kursi & the mu\u2019awwidhat over him; a sunnah uniting blessing & calm.'},
      psych:{ar:'الدماغُ يحتاج إشاراتِ نومٍ ثابتة؛ الإضاءةُ الخافتةُ والروتينُ يُفرزان الميلاتونين.',en:'The brain needs consistent sleep cues; dim light & routine release melatonin.'},
      steps:[{ar:'طقسٌ ثابت: حمّامٌ دافئ، أذكار، إضاءةٌ خافتة، صوتٌ هادئ.',en:'Fixed ritual: warm bath, adhkar, dim light, soft voice.'},{ar:'أوقِف الشاشاتِ قبل النومِ بساعتين.',en:'Stop screens two hours before sleep.'},{ar:'موعدُ نومٍ ثابتٌ كلَّ ليلةٍ ولو في العطلة.',en:'A fixed bedtime nightly, even on holidays.'}]},
  ],
  checklist:[
    {ar:'أُلبّي حاجاتِه الجسديّةَ والعاطفيّةَ بسرعةٍ وثبات',en:'I meet his physical & emotional needs promptly & consistently'},
    {ar:'أحمله وأُقبّله وأُلاعبه يوميًّا بلا مقابل',en:'I hold, kiss & play with him daily, freely'},
    {ar:'الأبُ يقضي نافذتَين يوميّتَين على الأقلّ في اللمسِ واللعب',en:'The father spends at least two daily windows in touch & play'},
    {ar:'يسمعُ القرآنَ والأذكارَ في جوٍّ هادئ',en:'He hears Qur\u2019an & adhkar in a calm setting'},
    {ar:'له روتينٌ ثابتٌ للنومِ والطعام',en:'He has a stable sleep & feeding routine'},
    {ar:'منعتُ الشاشاتِ قبل العامين تمامًا',en:'I keep screens away entirely before age 2'},
    {ar:'لا أصرخُ في وجهه ولا أتشاجرُ أمامه',en:'I never shout at him nor quarrel before him'},
    {ar:'أدعو له بالصلاحِ والحفظِ كلَّ يوم',en:'I pray for his righteousness & protection daily'},
  ],
  followup:[
    {period:{ar:'يوميًّا',en:'Daily'}, item:{ar:'هل نام وأكل واطمأنّ؟ هل حظِيَ بحضنٍ كافٍ من كلا الوالدين؟',en:'Did he sleep, eat & settle? Did he get enough holding from both parents?'}},
    {period:{ar:'أسبوعيًّا',en:'Weekly'}, item:{ar:'هل تطوّرت لغتُه/حركتُه؟ هل بقي البيتُ هادئًا بلا شاشات؟',en:'Did his language/movement progress? Did the home stay calm & screen-free?'}},
    {period:{ar:'كلَّ ٣ أشهر',en:'Every 3 months'}, item:{ar:'مراجعةُ معالمِ النموّ مع الطبيب (سمع، بصر، حركة، تفاعل).',en:'Review developmental milestones with the doctor (hearing, sight, motor, social).'}},
  ],
  practice:{
    track:{ar:'قبل المسارات — مرحلةُ التأسيس',en:'Before the tracks — the foundation stage'},
    items:[
      {ar:'اجعل البيتَ مسموعًا فيه القرآنُ والأذكار؛ ابدأ من «واحة العبادة» بأذكارِ النومِ والاستيقاظ تقرؤها عليه.',en:'Fill the home with Qur\u2019an & adhkar; begin with the sleep/waking adhkar from Worship Oasis, read over him.'},
      {ar:'في «ركن الأهل» سجِّل عاداتِك أنت (الحضن، الدعاء له، وقت الأب) لا عاداتِه؛ فأنت المُربَّى أوّلًا في هذه المرحلة.',en:'In the Parents\u2019 Corner, log your own habits (hugging, du\u2019a, father-time) \u2014 you are the one being trained at this stage.'},
    ]},
});
