/* stage-2.js — المرحلة الثانية · 3–6 · اللعب والتلقين */
window.TARBIYAH.stages.push({
  id:'s2', age:'3–6', ic:'🧸', c:'#C9A227',
  nm:{ar:'اللعبُ والتلقين', en:'Play & First Words of Faith'},
  sub:{ar:'الطفولةُ المبكّرة — القدوةُ والتقليد', en:'Early childhood — modeling & imitation'},
  intro:{ar:'هنا ينفتح عقلُ الطفلِ كالإسفنجةِ: لغةٌ تنفجر، وخيالٌ يطير، وسؤالٌ لا ينتهي. ما زلنا في مرحلةِ «اللعب»، فلا تكليفَ ولا عقاب، لكنّها سنواتُ الغرسِ الأولى: نلقّنه «لا إله إلا الله»، ونحبّب إليه اللهَ ورسولَه ﷺ بالقصّةِ والكلمةِ الطيّبة، ونعلّمه الأدبَ بالقدوةِ لا بالموعظة. الطفلُ في هذه السنّ مرآةٌ تعكس ما تراه لا ما تسمعه؛ فكُن أنت أوّلَ قصّةٍ يحفظها.',
    en:'Here the child\u2019s mind opens like a sponge: language explodes, imagination soars, questions never end. We are still in the \u201cplay\u201d stage \u2014 no obligation, no punishment \u2014 yet these are the first years of planting: we teach \u201cLa ilaha illa Allah,\u201d endear Allah and His Messenger ﷺ through story and kind words, and teach manners by example, not sermons. At this age the child mirrors what he sees, not what he hears; so be the first story he memorizes.'},
  glance:[
    {ic:'⏳', k:{ar:'جرعةُ الوقت',en:'Time dose'}, v:{ar:'٤٥–٩٠ دقيقةً لعبًا موجَّهًا يوميًّا',en:'45\u201390 min guided play daily'}},
    {ic:'🎯', k:{ar:'المهمّةُ الكبرى',en:'Core task'}, v:{ar:'تحبيبُ الله + القدوة',en:'Endearing Allah + modeling'}},
    {ic:'🚫', k:{ar:'الخطُّ الأحمر',en:'Red line'}, v:{ar:'لا تخويفٌ بالله ولا وعدٌ كاذب',en:'No fear of Allah, no false promises'}},
    {ic:'🗝️', k:{ar:'الكلمةُ المفتاح',en:'Keyword'}, v:{ar:'القدوة',en:'Example'}},
  ],
  scholar:{ar:'هذه أعتابُ التكليفِ وما زال بعيدًا، فالحكمةُ النبويّةُ أن نُحبّب لا أن نُلزِم. أوصى السلفُ: «افتحوا على صبيانكم أوّلَ كلمةٍ بلا إله إلا الله، ولقّنوهم عند الموتِ لا إله إلا الله». فالكلمةُ الأولى توحيد، والقصّةُ الأولى عن اللهِ الخالقِ الرحيم.\n\nوهذه سنُّ القدوةِ بامتياز؛ قال ابنُ القيّم: «والطفلُ ينشأ على ما عوّده المربّي». والنبيُّ ﷺ علّم الأدبَ بالموقفِ لا بالخطبة: قال لعمرَ بنِ أبي سلمةَ وهو غلامٌ يأكل: «يا غلامُ، سمِّ اللهَ، وكُل بيمينك، وكُل ممّا يليك». ثلاثُ كلماتٍ في لحظةِ طعام، لا محاضرةَ آداب.\n\nواحذر الوعدَ الكاذب؛ فقد رأى النبيُّ ﷺ أمًّا تنادي طفلَها: «تعالَ أُعطِك»، فقال: «ما أردتِ أن تُعطيه؟» قالت: تمرًا، قال: «أما إنّكِ لو لم تُعطِه شيئًا كُتبت عليكِ كذبة». فالصدقُ مع الطفلِ بناءٌ للثقة، والكذبُ عليه أوّلُ ثقبٍ فيها.',
    en:'These are the thresholds of accountability, still far off, so the prophetic wisdom is to endear, not compel. The early Muslims advised: \u201cLet the first word you open upon your children be La ilaha illa Allah.\u201d The first word is tawhid; the first story is of Allah, the Creator, the Merciful.\n\nThis is supremely the age of example. Ibn al-Qayyim said: \u201cThe child grows upon what his guardian accustoms him to.\u201d The Prophet ﷺ taught manners through the moment, not the lecture: he told the boy \u2018Umar b. Abi Salamah while eating, \u201cBoy, say Bismillah, eat with your right hand, and eat from what is near you.\u201d Three phrases at a meal, not a lecture on etiquette.\n\nBeware the false promise; the Prophet ﷺ saw a mother call her child, \u201cCome, I\u2019ll give you,\u201d and asked, \u201cWhat did you mean to give him?\u201d \u201cDates,\u201d she said. He replied: \u201cHad you given him nothing, a lie would have been recorded against you.\u201d Truth with a child builds trust; lying to him is the first hole in it.'},
  psych:{ar:'يسمّي إريكسون هذه المرحلةَ «المبادرة مقابل الذنب» (٣–٦): الطفلُ يريد أن يفعلَ ويجرّبَ ويقودَ لعبَه. إن شجّعتَ مبادرتَه نشأ واثقًا مِقدامًا، وإن قابلتَها بالسخريةِ والكبتِ والعقابِ الزائدِ نشأ متردّدًا يشعر بالذنبِ كلّما بادر.\n\nوبحسب بياجيه، تفكيرُ الطفلِ هنا «ما قبل إجرائيّ»: حسّيٌّ تصوّريٌّ يتعلّم باللعبِ والتقليدِ والقصّة، لا بالمنطقِ المجرّد ولا بالوعظ الطويل. لذلك القصّةُ أبلغُ من النصيحة، واللعبُ هو لغةُ التعلّم، والتكرارُ هو طريقُ الترسيخ.\n\nوأنماطُ التربيةِ (باومريند) تُظهِر أنّ الأسلوبَ الأنجحَ هو «الحازمُ الحاني»: حدودٌ واضحةٌ ثابتةٌ مع دفءٍ عالٍ واحترام. لا التساهلُ المُفرِط الذي يربّي طاغيةً صغيرًا، ولا التسلّطُ القاسي الذي يربّي خائفًا أو متمرّدًا.',
    en:'Erikson calls this \u201cinitiative vs guilt\u201d (3\u20136): the child wants to do, try and lead his play. Encourage his initiative and he grows confident and enterprising; meet it with mockery, suppression and excess punishment and he grows hesitant, feeling guilty whenever he initiates.\n\nPer Piaget, the child\u2019s thinking here is \u201cpre-operational\u201d: concrete and imaginative, learning through play, imitation and story \u2014 not abstract logic or long sermons. So a story is mightier than advice, play is the language of learning, and repetition is the road to consolidation.\n\nParenting-style research (Baumrind) shows the most successful approach is \u201cauthoritative\u201d: clear, consistent limits with high warmth and respect. Neither over-permissiveness that raises a little tyrant, nor harsh authoritarianism that raises the fearful or the rebellious.'},
  specialists:[
    {q:{ar:'«ربِّ ابنَك على القصّةِ لا على المحاضرة؛ القصّةُ تدخل القلبَ من غيرِ استئذان».',en:'\u201cRaise your child on story, not lecture; a story enters the heart without knocking.\u201d'}, by:{ar:'منهجُ التربيةِ بالقصّة',en:'Education-by-story method'}},
    {q:{ar:'«أنجحُ الأساليبِ حازمٌ حانٍ: حدودٌ واضحةٌ مع دفءٍ عالٍ» — لا تساهلَ مفسد ولا تسلّطَ كاسر.',en:'\u201cThe most successful style is authoritative: clear limits with high warmth\u201d \u2014 not spoiling permissiveness nor crushing control.'}, by:{ar:'ديانا باومريند · علم النفس',en:'Diana Baumrind · psychology'}},
    {q:{ar:'«سمِّ مشاعرَ طفلك له: أراك غاضبًا، أراك خائفًا؛ الطفلُ الذي يُسمّى شعورُه يتعلّم ضبطَه».',en:'\u201cName your child\u2019s feelings for him: I see you\u2019re angry, scared; a child whose feeling is named learns to regulate it.\u201d'}, by:{ar:'جون غوتمان · التدريبُ الانفعاليّ',en:'John Gottman · emotion-coaching'}},
  ],
  evidences:[
    {type:'hadith', text:{ar:'«يا غلامُ، سمِّ اللهَ، وكُل بيمينك، وكُل ممّا يليك».',en:'\u201cBoy, say Bismillah, eat with your right hand, and eat from what is near you.\u201d'}, ref:{ar:'متفق عليه',en:'Bukhari & Muslim'}, note:{ar:'التعليمُ في الموقفِ بكلماتٍ قليلةٍ لا بالخطبة.',en:'Teaching in the moment, with few words, not a sermon.'}},
    {type:'hadith', text:{ar:'«مَن كان له صبيٌّ فليتصابَ له» — أي يلاعبه وينزل إلى مستواه.',en:'\u201cWhoever has a child, let him be childlike with him\u201d \u2014 play with him at his level.'}, ref:{ar:'حديثٌ حسن',en:'Hasan hadith'}, note:{ar:'اللعبُ مع الطفلِ سُنّةٌ لا تنازل.',en:'Playing with the child is sunnah, not beneath you.'}},
    {type:'hadith', text:{ar:'«ما نَحَلَ والدٌ ولدًا من نَحْلٍ أفضلَ من أدبٍ حسن».',en:'\u201cNo father gives his child a gift better than good manners.\u201d'}, ref:{ar:'الترمذيّ',en:'Tirmidhi'}, note:{ar:'الأدبُ أعظمُ ميراثٍ تورِّثه في هذه السنّ.',en:'Good manners are the greatest inheritance at this age.'}},
  ],
  rewards:[
    {ic:'🌱', t:{ar:'كلمةُ التوحيدِ أوّلَ ما يَنطِق',en:'Tawhid as his first speech'}, d:{ar:'مَن فتح على ولده بلا إله إلا الله غرس أصلَ الإيمانِ في فطرةٍ نقيّةٍ لم تتلوّث.',en:'Opening with tawhid plants faith\u2019s root in a pure, untainted fitrah.'}},
    {ic:'🤝', t:{ar:'قدوةٌ تُكتَب لك حسناتُها',en:'An example whose good is recorded for you'}, d:{ar:'«مَن سنَّ سُنّةً حسنة فله أجرُها وأجرُ مَن عمل بها»؛ وأنت أوّلُ قدوةٍ لولدك.',en:'\u201cWhoever sets a good example has its reward and the reward of who follows it\u201d \u2014 you are his first example.'}},
    {ic:'😊', t:{ar:'طفلٌ يحبُّ اللهَ لا يخافه فقط',en:'A child who loves Allah, not only fears Him'}, d:{ar:'حين تربط الدينَ بالفرحِ والأمان ينشأ محبًّا للعبادةِ لا نافرًا منها.',en:'Tying faith to joy & safety raises a child who loves worship rather than flees it.'}},
  ],
  needs:[
    {ar:'اللعبُ الحرُّ والموجَّهُ والحركةُ الكثيرة',en:'Free & guided play and lots of movement'},
    {ar:'الإجابةُ عن أسئلتِه بصبرٍ وبساطةٍ وصدق',en:'Patient, simple, honest answers to his questions'},
    {ar:'قدوةٌ صالحةٌ يراها (صلاة، أدب، صدق)',en:'A good model he sees (prayer, adab, truth)'},
    {ar:'قصصُ الأنبياءِ والصالحين بأسلوبٍ محبَّب',en:'Stories of prophets & the righteous, endearingly'},
    {ar:'تلقينُ التوحيدِ وحبِّ اللهِ ورسولِه ﷺ',en:'Planting tawhid & love of Allah and His Prophet'},
    {ar:'تسميةُ المشاعرِ وتعليمُ ضبطِها برفق',en:'Naming feelings & gently teaching their control'},
  ],
  risks:[
    {ar:'تقليدُ السلوكِ السيّئِ من المحيطِ والشاشات',en:'Imitating bad behaviour from surroundings & screens'},
    {ar:'تخويفُه من اللهِ أو ربطُ الدينِ بالعقاب',en:'Frightening him of Allah or tying faith to punishment'},
    {ar:'الوعدُ الكاذبُ وكثرةُ «لا» بلا تعليلٍ ولا بديل',en:'False promises & constant unexplained \u201cno\u201d'},
    {ar:'العقابُ القاسي الذي يكبت المبادرةَ والفضول',en:'Harsh punishment crushing initiative & curiosity'},
    {ar:'الإفراطُ في الشاشاتِ وضعفُ اللعبِ الواقعيّ',en:'Excess screens & weak real-world play'},
    {ar:'المقارنةُ بالإخوةِ والسخريةُ من محاولاته',en:'Comparison with siblings & mocking his attempts'},
  ],
  values:[
    {ar:'حبُّ اللهِ ورسولِه ﷺ والتوحيد',en:'Love of Allah, His Prophet ﷺ & tawhid'},
    {ar:'الصدقُ ومطابقةُ القولِ للفعل',en:'Truthfulness — words matching deeds'},
    {ar:'آدابُ الطعامِ والسلامِ والاستئذان',en:'Adab of eating, greeting & permission'},
    {ar:'المشاركةُ والرحمةُ وضبطُ الانفعال',en:'Sharing, mercy & managing emotion'},
  ],
  dose:{ar:'٤٥–٩٠ دقيقةً من اللعبِ والتفاعلِ الموجَّهِ يوميًّا، موزّعةً على نوافذَ قصيرة (انتباهُ الطفلِ قصير). الأب: نافذةٌ يوميّةٌ لا تقلّ عن ٢٠–٣٠ دقيقةً لعبًا خشِنًا ممتعًا (مصارعةٌ لطيفة، بناءُ مكعّبات، قصّةٌ قبل النوم). الجودةُ (انتباهٌ كامل بلا هاتف) أهمُّ من الكمّ.',
    en:'45\u201390 min of guided play & interaction daily, split into short windows (a child\u2019s attention is brief). The father: a daily window of at least 20\u201330 min of fun rough-and-tumble (gentle wrestling, block-building, a bedtime story). Quality (full, phone-free attention) matters more than quantity.'},
  daily:[
    {t:{ar:'الصباح',en:'Morning'}, dur:{ar:'١٠ د',en:'10 min'}, act:{ar:'دعاءُ الاستيقاظ معًا، حضنٌ، «ماذا سنفعل اليوم؟»',en:'Waking du\u2019a together, a hug, \u201cwhat shall we do today?\u201d'}, who:{ar:'الأم/الأب',en:'Mother/Father'}},
    {t:{ar:'لعبُ التعلّم',en:'Learning play'}, dur:{ar:'٢٠ د',en:'20 min'}, act:{ar:'حروفٌ وأرقامٌ باللعب، ألوان، تلوينُ شخصيّةٍ من حيّنا الصغير',en:'Letters & numbers via play, colours, colour a Little-District character'}, who:{ar:'الأم',en:'Mother'}},
    {t:{ar:'الصلاةُ بالقدوة',en:'Prayer by example'}, dur:{ar:'٥ د',en:'5 min'}, act:{ar:'يقف بجوارك في الصلاةِ يقلّد الحركات، بلا إلزام',en:'He stands beside you in prayer imitating the motions, no compulsion'}, who:{ar:'الأب',en:'Father'}},
    {t:{ar:'لعبُ الأب',en:'Father play'}, dur:{ar:'٢٥ د',en:'25 min'}, act:{ar:'لعبٌ حركيٌّ ممتع، بناءٌ، مغامرةٌ خياليّة',en:'Active fun play, building, an imaginative adventure'}, who:{ar:'الأب',en:'Father'}},
    {t:{ar:'قصّةُ النوم',en:'Bedtime story'}, dur:{ar:'١٥ د',en:'15 min'}, act:{ar:'قصّةُ نبيٍّ أو خُلُقٍ، دعاءُ النوم، حضنٌ وكلمةُ حبّ',en:'A prophet/manner story, sleep du\u2019a, a hug & a loving word'}, who:{ar:'الأب/الأم',en:'Father/Mother'}},
  ],
  weekly:[
    {d:{ar:'يوميًّا',en:'Daily'}, act:{ar:'قصّةٌ هادفة + صلاةٌ يراها + لعبٌ مع الأب + خُلُقُ الأسبوع',en:'A purposeful story + visible prayer + father-play + manner of the week'}},
    {d:{ar:'٣ مرّات/أسبوع',en:'3×/week'}, act:{ar:'لعبٌ خارجيٌّ حركيّ (حديقة، رمل، كرة) لتفريغِ الطاقة',en:'Outdoor active play (park, sand, ball) to release energy'}},
    {d:{ar:'الجمعة',en:'Friday'}, act:{ar:'طقسُ الجمعة: اغتسالٌ وطيبٌ، نشيدٌ، نزهةٌ أسريّةٌ ممتعة',en:'Jumu\u2019ah ritual: bath & scent, a nasheed, a fun family outing'}},
  ],
  fatherFocus:{ar:'في هذه السنّ يبدأ الطفلُ يميّز «أبي» ويتعلّق به. اللعبُ الخشِنُ الآمنُ مع الأب (المطاردة، الحملُ على الكتف، المصارعةُ اللطيفة) يبني الثقةَ بالنفسِ ويعلّم ضبطَ القوّة. كُن أنت مَن يصلّي أمامه فيقلّدك، ومَن يحكي له قصّةَ النومِ ليرتبط الدينُ بصوتِك الحنون. عشرون دقيقةً منك تساوي ساعةً من أيِّ شخصٍ آخر.',
    en:'At this age the child begins to recognize \u201cmy father\u201d and attach to him. Safe rough play with the father (chasing, shoulder-rides, gentle wrestling) builds self-confidence and teaches control of strength. Be the one he sees pray, so he imitates you, and the one who tells the bedtime story, so faith is tied to your tender voice. Twenty minutes from you equal an hour from anyone else.'},
  activities:[
    {ic:'📖', t:{ar:'مسرحُ القصّة',en:'Story theatre'}, how:{ar:'احكِ قصّةَ نبيٍّ بصوتٍ متغيّرٍ وحركة، ودَع الطفلَ يمثّل دورًا.',en:'Tell a prophet\u2019s story with changing voices & motion; let the child act a part.'}, why:{ar:'يرسّخ القيمةَ عبر الخيالِ والمشاركة.',en:'Cements the value through imagination & participation.'}},
    {ic:'🧱', t:{ar:'نبني المسجد',en:'Let\u2019s build the masjid'}, how:{ar:'ابنِ بالمكعّباتِ مسجدًا أو الكعبةَ وتحدّثا عن الصلاةِ والحجّ بفرح.',en:'Build a masjid or the Ka\u2019bah from blocks & talk joyfully about prayer & hajj.'}, why:{ar:'يربط العبادةَ باللعبِ والمتعة.',en:'Links worship to play & delight.'}},
    {ic:'🎨', t:{ar:'تلوينُ القيم',en:'Colour the values'}, how:{ar:'لوِّنا معًا صفحاتِ «حيّنا الصغير» وتحدّثا عن الخُلُقِ الذي فيها.',en:'Colour Little-District pages together & discuss the manner shown.'}, why:{ar:'يثبّت الخُلُقَ بصريًّا ويدويًّا.',en:'Fixes the manner visually & by hand.'}},
    {ic:'🤲', t:{ar:'صندوقُ الأدعية',en:'The du\u2019a jar'}, how:{ar:'اصنعا صندوقًا فيه أدعيةٌ مصوّرة، يسحب كلَّ يومٍ دعاءً يحفظه.',en:'Make a jar of illustrated du\u2019as; he draws one daily to memorize.'}, why:{ar:'يحفظ أذكارَ اليومِ باللعبِ لا بالتلقين.',en:'Learns daily adhkar by play, not rote.'}},
    {ic:'🌟', t:{ar:'لوحةُ النجوم',en:'The star chart'}, how:{ar:'ألصِق نجمةً عند كلِّ خُلُقٍ حسن (سلام، مشاركة، صدق).',en:'Add a star for each good manner (salam, sharing, truth).'}, why:{ar:'يحوّل القيمَ إلى عادةٍ محبوبةٍ بالتشجيع.',en:'Turns values into a loved habit through encouragement.'}},
    {ic:'🍽️', t:{ar:'مائدةُ الآداب',en:'The manners table'}, how:{ar:'اجعل الطعامَ درسَ أدبٍ ممتعًا: تسمية، يمين، شكرٌ لله بعده.',en:'Make meals a fun adab lesson: Bismillah, right hand, thanking Allah after.'}, why:{ar:'يعلّم الأدبَ في موقفِه الطبيعيّ.',en:'Teaches adab in its natural moment.'}},
  ],
  examples:[
    {title:{ar:'نوبةُ غضبٍ في السوق',en:'A tantrum at the shop'}, scene:{ar:'يريد لُعبةً، تَرفُض، فيرمي نفسَه أرضًا يصرخ أمام الناس.',en:'He wants a toy, you refuse, and he throws himself down screaming in public.'},
      do:{ar:'انزل لمستواه بهدوء، سمِّ شعورَه: «أنت غاضبٌ لأنك تريدها». احتضنه، اثبُت على «لا» بلا صراخ، واصرف انتباهَه لشيءٍ آخر.',en:'Get down to his level calmly, name the feeling: \u201cYou\u2019re angry because you want it.\u201d Hug him, hold the \u201cno\u201d without shouting, & redirect his attention.'},
      dont:{ar:'لا تستسلم لتسكته (تعلّمه أنّ الصراخ يُفلح)، ولا تضربه أو تُهدّده أمام الناس.',en:'Don\u2019t give in to silence him (it teaches screaming works), don\u2019t hit or threaten him in public.'},
      root:{ar:'النوبةُ عجزٌ عن ضبطِ المشاعرِ لا تمرّد؛ مهمّتُك تهدئتُه وتعليمُه الكلماتِ بدل الصراخ.',en:'A tantrum is inability to regulate emotion, not defiance; your job is to calm him & teach words instead of screams.'}},
    {title:{ar:'سؤالٌ صعب: «أين الله؟»',en:'A hard question: \u201cWhere is Allah?\u201d'}, scene:{ar:'يسألك فجأةً سؤالًا عن اللهِ أو الموتِ بفضولٍ بريء.',en:'He suddenly asks about Allah or death with innocent curiosity.'},
      do:{ar:'أجِب بصدقٍ وبساطةٍ تناسب سنَّه: «اللهُ فوق السماءِ، يرانا ويحبّنا ويرزقنا». اربط الجوابَ بالحبِّ والعظمة.',en:'Answer truthfully & simply for his age: \u201cAllah is above the heavens, He sees us, loves us & provides for us.\u201d Tie it to love & majesty.'},
      dont:{ar:'لا تنهره ولا تقل «لا تسأل»، ولا تخوّفه بالنار، ولا تعطه تفصيلًا فلسفيًّا يربكه.',en:'Don\u2019t rebuke him or say \u201cdon\u2019t ask,\u201d don\u2019t frighten him with Hell, don\u2019t give confusing philosophy.'},
      root:{ar:'كلُّ سؤالٍ فرصةُ غرسٍ؛ والإجابةُ المحبَّبةُ تبني عقيدةً مطمئنّة.',en:'Every question is a chance to plant; a loving answer builds a serene creed.'}},
  ],
  problems:[
    {p:{ar:'نوباتُ الغضبِ المتكرّرة',en:'Frequent tantrums'},
      why:{ar:'الدماغُ الانفعاليُّ أسرعُ من العقلِ الضابط في هذه السنّ؛ يُضاف إليه التعبُ أو الجوعُ أو طلبُ الانتباه.',en:'The emotional brain outruns the regulating brain at this age; add tiredness, hunger, or attention-seeking.'},
      islamic:{ar:'الرفقُ والهدوء؛ «إنّ اللهَ رفيقٌ يحبّ الرفقَ ويعطي عليه ما لا يعطي على العنف». ولا تدعُ عليه.',en:'Gentleness & calm; \u201cAllah is gentle & loves gentleness, giving for it what He gives not for harshness.\u201d And never curse him.'},
      psych:{ar:'سمِّ الشعورَ واحتوِه أوّلًا (تدريبٌ انفعاليّ)، ثمّ علّمه كلماتٍ بديلة؛ تجاهلُ النوبةِ مع الأمانِ يُطفئها.',en:'Name & contain the feeling first (emotion-coaching), then teach alternative words; calmly not rewarding the tantrum extinguishes it.'},
      steps:[{ar:'اهدأ أنت أوّلًا ولا تقابل الصراخَ بصراخ.',en:'Calm yourself first; don\u2019t meet screaming with screaming.'},{ar:'انزل لمستواه، احتضنه، سمِّ شعورَه.',en:'Get to his level, hug him, name his feeling.'},{ar:'اثبُت على القرارِ بهدوءٍ ولا تكافئ النوبة.',en:'Hold the decision calmly; don\u2019t reward the tantrum.'},{ar:'بعد الهدوءِ علّمه: «قُل: أنا غاضب» بدل الصراخ.',en:'After calm, teach: \u201cSay: I\u2019m angry\u201d instead of screaming.'},{ar:'تحقّق من النوم والجوعِ كأسبابٍ خفيّة.',en:'Check sleep & hunger as hidden causes.'}]},
    {p:{ar:'إدمانُ الشاشةِ ورفضُ تركها',en:'Screen addiction & refusing to stop'},
      why:{ar:'الشاشاتُ تُفرز جرعاتِ دوبامين سريعةً تجعل الواقعَ يبدو بطيئًا ممِلًّا؛ والطفلُ لا يملك كبحَها.',en:'Screens release quick dopamine that makes reality feel slow & dull; the child can\u2019t self-regulate it.'},
      islamic:{ar:'حفظُ الوقتِ أمانة، وملءُ الفراغِ بالنافعِ سُنّة؛ كُن أنت البديلَ الممتعَ لا المانعَ الغاضب.',en:'Guarding time is a trust, and filling idleness with benefit is sunnah; be the fun alternative, not the angry banner.'},
      psych:{ar:'الحدُّ يكون بحدودٍ ثابتةٍ مُعلَنةٍ مسبقًا وبدائلَ جاذبة؛ المنعُ المفاجئُ يولّد نوبة.',en:'Limit via fixed, pre-announced boundaries & attractive alternatives; sudden cut-off triggers a tantrum.'},
      steps:[{ar:'حدٌّ يوميٌّ واضحٌ ومحتوًى منتقًى ومتفقٌ عليه مسبقًا.',en:'A clear daily limit, curated content, agreed in advance.'},{ar:'نبّه قبل الإيقافِ بخمسِ دقائقَ لتجنّبِ الصدمة.',en:'Give a 5-minute warning before stopping to avoid the shock.'},{ar:'جهّز بديلًا ممتعًا فورًا (لعب، خروج، نشاطُ أب).',en:'Have a fun alternative ready immediately (play, an outing, father-activity).'},{ar:'لا شاشةَ في غرفةِ النومِ ولا قبلَ النومِ بساعتين.',en:'No screen in the bedroom or within two hours of sleep.'},{ar:'كُن قدوة: قلِّل شاشتَك أمامه.',en:'Model it: reduce your own screen before him.'}]},
  ],
  checklist:[
    {ar:'أحكي له قصّةً هادفةً (نبيٍّ أو خُلُق) بانتظام',en:'I tell him a purposeful story (prophet/manner) regularly'},
    {ar:'يراني أُصلّي وأذكُر اللهَ فيقلّدني',en:'He sees me pray & remember Allah, and imitates me'},
    {ar:'لقّنتُه التوحيدَ وحبَّ النبيِّ ﷺ',en:'I have taught him tawhid & love of the Prophet ﷺ'},
    {ar:'ألعبُ معه يوميًّا (الأبُ ٢٠–٣٠ دقيقة) وأشجّع مبادرتَه',en:'I play with him daily (father 20\u201330 min) & encourage his initiative'},
    {ar:'لا أُخوّفه باللهِ ولا أعِدُه ثمّ أُخلِف',en:'I never frighten him with Allah, nor break a promise'},
    {ar:'أُسمّي مشاعرَه وأعلّمه كلماتٍ بدل الصراخ',en:'I name his feelings & teach words instead of screaming'},
    {ar:'أضبطُ الشاشةَ محتوًى ووقتًا بحدودٍ ثابتة',en:'I control screens by content & fixed time limits'},
    {ar:'أتعاملُ مع نوباتِه بهدوءٍ وثباتٍ لا بعنف',en:'I handle his tantrums with calm firmness, not force'},
  ],
  followup:[
    {period:{ar:'يوميًّا',en:'Daily'}, item:{ar:'هل نال قصّةً ولعبًا مع الأب؟ هل رآني أُصلّي؟ كم وقتَ الشاشة؟',en:'Did he get a story & father-play? Did he see me pray? How much screen time?'}},
    {period:{ar:'أسبوعيًّا',en:'Weekly'}, item:{ar:'أيُّ خُلُقٍ غرسناه؟ كم سورةً/دعاءً حفِظ باللعب؟ هل قلّت النوبات؟',en:'Which manner did we plant? How many surahs/du\u2019as via play? Did tantrums lessen?'}},
    {period:{ar:'شهريًّا',en:'Monthly'}, item:{ar:'مراجعةُ تطوّرِ اللغةِ والتواصلِ والاستقلالِ في اللبسِ والطعام.',en:'Review language, social skills & independence in dressing/eating.'}},
  ],
  practice:{
    track:{ar:'مسارُ «البراعم» (٤–٦) في كتاب خارطة طريق المربّي',en:'The \u201cLittle Sprouts\u201d track (4\u20136) in the Parent Roadmap book'},
    items:[
      {ar:'اتبع خطّةَ «البراعم»: ١٠–١٥ دقيقةً يوميًّا باللعبِ والتكرار — الفاتحةُ وقصارُ السورِ من «بستان القرآن»، وحركاتُ الصلاةِ من «واحة العبادة».',en:'Follow the Sprouts plan: 10\u201315 min/day through play \u2014 al-Fatihah & short surahs (Qur\u2019an Garden), prayer motions (Worship Oasis).'},
      {ar:'احكِ قصصَ الأنبياءِ المصوّرةَ من «حصن الأبطال»، ولوِّن خُلُقًا أسبوعيًّا من «حيّنا الصغير»، وسجِّل النجومَ في «ركن الأهل».',en:'Tell the illustrated prophet-stories (Heroes\u2019 Fortress), colour a weekly manner (Little District), & log stars in the Parents\u2019 Corner.'},
    ]},
});
