/* stage-5.js — المرحلة الخامسة · 12–15 · الصداقة والتكليف */
window.TARBIYAH.stages.push({
  id:'s5', age:'12–15', ic:'🤝', c:'#C0392B',
  nm:{ar:'الصداقةُ والتكليف', en:'Friendship & Accountability'},
  sub:{ar:'المراهقةُ المبكّرة — عاملْه كصديقٍ لا كطفل', en:'Early adolescence — treat as friend, not child'},
  intro:{ar:'دخلنا مرحلةَ «صاحِبْه سبعًا». غالبًا يقع البلوغُ هنا، فيصير ابنُك مكلّفًا تُكتَب حسناتُه وسيّئاتُه — تحوّلٌ جوهريٌّ يستدعي تحوّلًا في معاملتك. لم يَعُد طفلًا يُؤمَر، بل شابًّا يُشاوَر ويُحترَم ويُصاحَب. هذه أصعبُ المراحلِ على الآباءِ وأخطرُها، لكنّها أثمنُها: من كسب ثقةَ مراهقِه ربح قلبَه، ومن قهره خسره. سلاحُك الآن ليس العصا بل الصداقةُ والقدوةُ والدعاء.',
    en:'We\u2019ve entered \u201cbefriend for seven.\u201d Puberty usually falls here, so your child becomes accountable \u2014 his good & bad deeds now recorded \u2014 a fundamental shift that demands a shift in how you treat him. He is no longer a child to command but a youth to consult, respect & befriend. This is the hardest stage for parents and the most dangerous, yet the most precious: whoever wins his adolescent\u2019s trust wins his heart; whoever subdues him loses him. Your weapon now is not the rod but friendship, example & du\u2019a.'},
  glance:[
    {ic:'⏳', k:{ar:'جرعةُ الوقت',en:'Time dose'}, v:{ar:'٤٥–٦٠ دقيقةً صحبةً وحوارًا يوميًّا',en:'45\u201360 min companionship & talk daily'}},
    {ic:'🎯', k:{ar:'المهمّةُ الكبرى',en:'Core task'}, v:{ar:'حفظُ الثقةِ وبناءُ الهُويّة',en:'Keep trust & build identity'}},
    {ic:'🚫', k:{ar:'الخطُّ الأحمر',en:'Red line'}, v:{ar:'لا تحقيرَ أمام الناسِ ولا قهر',en:'No public humiliation, no coercion'}},
    {ic:'🗝️', k:{ar:'الكلمةُ المفتاح',en:'Keyword'}, v:{ar:'الاحترامُ والصحبة',en:'Respect & companionship'}},
  ],
  scholar:{ar:'هذه مرحلةُ المصاحبةِ التي أرشد إليها الأثرُ: «ووزيرٌ سبعًا». وغالبًا يقع البلوغُ فيها فيصير الولدُ مكلّفًا؛ تحوّلٌ عظيمٌ في الميزانِ الشرعيّ يقابله تحوّلٌ في الأسلوب: من الأمرِ إلى الإقناع، ومن التوجيهِ إلى المشاورة.\n\nكان النبيُّ ﷺ يحترم الشبابَ ويُشركهم؛ ولّى أسامةَ بنَ زيدٍ قيادةَ الجيشِ وهو دون العشرين، وكان ابنُ عبّاسٍ الفتى يجلس في مجلسِ كبارِ الصحابةِ بإجلاسِ عمرَ له. واستأذن النبيُّ ﷺ الغلامَ الصغيرَ — وعن يمينِه — في أن يُعطيَ الأشياخَ، تعليمًا لاحترامِ حقِّه. وهذا كلُّه تكريمٌ للشابِّ يفتح قلبَه.\n\nوالقاعدةُ الذهبيّة: المراهقُ يُطيع من يحترمه، ويصدُّ من يقهره ويُذلّه. فالإقناعُ لا الإكراه، والصداقةُ لا الوصايةُ الفوقيّة، والسترُ لا الفضح. قال عمرُ: «لاعِب ابنك سبعًا، وأدّبه سبعًا، وصاحبه سبعًا، ثمّ اترك له الحبل على الغارب». ومع المصاحبةِ يبقى الغرسُ: العفّةُ، والصلاةُ عن قناعة، والهُويّةُ، والرفقةُ الصالحة.',
    en:'This is the companionship stage the report points to: \u201ca minister for seven.\u201d Puberty usually falls here, so the youth becomes accountable \u2014 a great shift in the Shari\u2019ah\u2019s scale, met by a shift in method: from command to persuasion, from directing to consulting.\n\nThe Prophet ﷺ respected the young & involved them; he put Usamah b. Zayd in command of an army under twenty, and the youth Ibn \u2018Abbas sat among senior Companions because \u2018Umar seated him. The Prophet ﷺ sought a young boy\u2019s permission \u2014 the boy being on his right \u2014 to give the elders first, teaching respect for the young one\u2019s right. All this honours the youth & opens his heart.\n\nThe golden rule: the adolescent obeys who respects him & resists who subdues & humiliates him. So persuasion not coercion, friendship not top-down guardianship, covering not exposing. \u2018Umar said: \u201cPlay with your son seven, discipline him seven, befriend him seven, then loosen the rope.\u201d With companionship the planting continues: chastity, prayer by conviction, identity & good company.'},
  psych:{ar:'يصف إريكسون المراهقةَ بأنّها صراعُ «الهُويّة مقابل اضطرابِ الدور» (١٢–١٨): السؤالُ الأكبر هو «مَن أنا؟». البلوغُ والهرموناتُ تُحدِث تقلّبًا عاطفيًّا حادًّا، ويصبح الأقرانُ المرجعَ الأوّلَ، ويسعى المراهقُ للاستقلالِ وإثباتِ ذاتِه ولو بالمعارضة.\n\nهذا التمرّدُ الظاهريُّ ليس رفضًا لك بل بحثٌ عن الذات؛ والدماغُ المراهقُ يكتمل فيه مركزُ الانفعالِ قبل مركزِ الكبحِ (الفصِّ الجبهيّ)، فتفسَّر الاندفاعيّةُ وتقلّبُ المزاج. يحتاج المراهقُ ثلاثةً: أن يُحترَم، وأن يُمنَح استقلالًا مسؤولًا، وأن يُسمَع بلا حكم.\n\nأخطرُ ما يفعله الأبُ هنا: المحاضراتُ الطويلة، والقهر، والتحقيرُ أمام الأصدقاء — كلُّها تُنتِج إمّا تمرّدًا صريحًا أو «ازدواجيّة» (وجهٌ في البيتِ وآخرُ خارجه). وأنجعُ نهجٍ هو الحفاظُ على التعلّقِ (نوفيلد): ابقَ مرساتَه العاطفيّةَ، فالمراهقُ المتّصلُ بقلبِ أبيه يتبعه، والمنقطعُ عنه يتبع أقرانَه.',
    en:'Erikson describes adolescence as the conflict of \u201cidentity vs role confusion\u201d (12\u201318): the great question is \u201cwho am I?\u201d Puberty & hormones bring sharp emotional volatility, peers become the primary reference, and the teen seeks independence & self-assertion \u2014 even through opposition.\n\nThis apparent rebellion is not a rejection of you but a search for self; the adolescent brain matures its emotional center before its braking center (the frontal lobe), explaining impulsivity & mood swings. The teen needs three things: to be respected, granted responsible autonomy, & heard without judgment.\n\nThe most damaging things a father does here: long lectures, coercion, & humiliation before friends \u2014 all produce either open rebellion or a \u201cdouble life\u201d (one face at home, another outside). The most effective approach is to preserve attachment (Neufeld): remain his emotional anchor \u2014 a teen connected to his father\u2019s heart follows him; one disconnected follows his peers.'},
  specialists:[
    {q:{ar:'«المراهقُ لا يحتاج ناصحًا جديدًا بقدرِ ما يحتاج صديقًا قديمًا يثق به».',en:'\u201cThe teen needs less a new adviser than an old friend he can trust.\u201d'}, by:{ar:'في مصاحبةِ المراهق',en:'On befriending teens'}},
    {q:{ar:'«اربط المراهقَ بقلبك أوّلًا يتبعك في كلِّ أمرٍ بعد ذلك» — التعلّقُ قبل التوجيه.',en:'\u201cBind your teen to your heart first, and he follows in everything\u201d \u2014 attachment before direction.'}, by:{ar:'جوردون نوفيلد · علم النفس',en:'Gordon Neufeld · psychology'}},
    {q:{ar:'«التحقيرُ أمام الأصدقاءِ جرحٌ لا يُنسى؛ عاتِب سرًّا وامدح علنًا».',en:'\u201cHumiliation before friends is an unforgettable wound; reproach in private, praise in public.\u201d'}, by:{ar:'من إرشادِ المراهقين',en:'Adolescent counselling'}},
  ],
  evidences:[
    {type:'hadith', text:{ar:'«رُفِع القلمُ عن ثلاثة... وعن الصبيِّ حتى يحتلم».',en:'\u201cThe pen is lifted from three... and from the child until he reaches puberty.\u201d'}, ref:{ar:'أبو داود',en:'Abu Dawud'}, note:{ar:'فإذا بلغ صار مكلّفًا مسؤولًا — فعامِله كذلك.',en:'Once he reaches puberty he is accountable \u2014 treat him so.'}},
    {type:'athar', text:{ar:'استأذن النبيُّ ﷺ الغلامَ — وعن يمينه أشياخ — أن يُعطيَهم، فقال الغلام: «لا أوثر بنصيبي منك أحدًا».',en:'The Prophet ﷺ asked a youth\u2019s leave to give the elders first; the youth said: \u201cI will not prefer anyone over my share of you.\u201d'}, ref:{ar:'متفق عليه',en:'Bukhari & Muslim'}, note:{ar:'احترامُ حقِّ الشابِّ يكسب قلبَه.',en:'Respecting the youth\u2019s right wins his heart.'}},
    {type:'athar', text:{ar:'ولّى النبيُّ ﷺ أسامةَ بنَ زيدٍ قيادةَ الجيشِ وهو شابٌّ يافع.',en:'The Prophet ﷺ appointed the young Usamah b. Zayd to lead an army.'}, ref:{ar:'متفق عليه',en:'Bukhari & Muslim'}, note:{ar:'الثقةُ والمسؤوليّةُ تصنعان الرجولةَ مبكّرًا.',en:'Trust & responsibility make manhood early.'}},
  ],
  rewards:[
    {ic:'🤲', t:{ar:'شابٌّ في طاعةِ الله من السبعة',en:'A youth in Allah\u2019s obedience \u2014 of the seven'}, d:{ar:'«شابٌّ نشأ في عبادةِ الله» من السبعةِ الذين يُظلّهم اللهُ في ظلِّه؛ وأنت مَن رعى نشأتَه.',en:'\u201cA youth who grew up worshipping Allah\u201d is among the seven Allah shades; and you nurtured that.'}},
    {ic:'🔗', t:{ar:'قلبٌ يبقى موصولًا بك',en:'A heart that stays connected to you'}, d:{ar:'مَن صاحَب مراهقَه بقي قريبًا منه في أخطرِ سنواتِه، فحماه من تيهِ الأقرانِ والفتن.',en:'Whoever befriends his teen stays close in his most dangerous years, shielding him from peers\u2019 lure & temptation.'}},
    {ic:'🌟', t:{ar:'هُويّةٌ راسخةٌ يعتزُّ بدينه',en:'A firm identity, proud of his deen'}, d:{ar:'حين تُحسِن هذه المرحلةَ يخرج شابٌّ يعرف مَن هو ولماذا يؤمن، لا تهزّه الشبهات.',en:'Done well, this stage yields a youth who knows who he is & why he believes, unshaken by doubts.'}},
  ],
  needs:[
    {ar:'الاحترامُ والمعاملةُ كصديقٍ ناضج',en:'Respect & treatment as a maturing friend'},
    {ar:'الشورى وإشراكُه في القرارِ والرأي',en:'Consultation & inclusion in decisions'},
    {ar:'استقلالٌ مسؤولٌ وأن يُسمَعَ ويُفهَم',en:'Responsible autonomy & being heard'},
    {ar:'هدفٌ ومعنًى ودورٌ يشعر بقيمتِه فيه',en:'Purpose, meaning & a role that gives worth'},
    {ar:'رفقةٌ صالحةٌ وقدوةٌ من خارجِ البيت',en:'Good company & a role model beyond home'},
    {ar:'مساحةُ خصوصيّةٍ مع متابعةٍ واعيةٍ لا تجسّس',en:'Privacy with conscious follow-up, not spying'},
  ],
  risks:[
    {ar:'القهرُ والمحاضراتُ فيولّدان التمرّد',en:'Coercion & lecturing breeding rebellion'},
    {ar:'رفقاءُ السوءِ وضغطُ الأقرانِ ووسائلُ التواصل',en:'Bad peers, peer pressure & social media'},
    {ar:'التحقيرُ أمام الناسِ وكسرُ كرامتِه',en:'Humiliation in public & breaking his dignity'},
    {ar:'اضطرابُ الهُويّةِ والشبهاتُ والعزلة',en:'Identity confusion, doubts & isolation'},
    {ar:'الازدواجيّة: وجهٌ في البيتِ وآخرُ خارجه',en:'A double life: one face at home, another outside'},
    {ar:'فتنةُ الشهوةِ والعلاقاتِ المحرّمةِ المبكّرة',en:'Temptation of desire & early forbidden relations'},
  ],
  values:[
    {ar:'الهُويّةُ الإسلاميّةُ والاعتزازُ بها',en:'A firm, proud Islamic identity'},
    {ar:'تملّكُ الصلاةِ والعبادةِ مسؤوليّةً ذاتيّة',en:'Owning prayer & worship as personal duty'},
    {ar:'العفّةُ والحياءُ وحفظُ النفس',en:'Chastity, modesty & self-restraint'},
    {ar:'المسؤوليّةُ وحُسنُ اختيارِ الصحبة',en:'Responsibility & choosing companions well'},
  ],
  dose:{ar:'٤٥–٦٠ دقيقةً يوميًّا، لكن نوعُها تغيّر تمامًا: لا «دروس» بل «صحبة». وقتٌ جنبًا إلى جنبٍ (رياضة، قيادة، عملٌ مشترك، مشروبٌ في مقهًى) يكون فيه الحوارُ عفويًّا لا استجوابًا. الأبُ مع الابن خصوصًا: نشاطٌ أسبوعيٌّ مميّزٌ يُنتظَر. القاعدة: دقائقُ من الإصغاءِ الصادقِ بلا حكمٍ تساوي ساعاتٍ من النصح.',
    en:'45\u201360 min daily, but its kind has wholly changed: not \u201clessons\u201d but \u201ccompanionship.\u201d Side-by-side time (sport, driving, shared work, a caf\u00e9 drink) where talk is spontaneous, not interrogation. The father with a son especially: an anticipated special weekly activity. The rule: minutes of honest, non-judging listening equal hours of advice.'},
  daily:[
    {t:{ar:'الفجر',en:'Fajr'}, dur:{ar:'١٠ د',en:'10 min'}, act:{ar:'تشجيعٌ على الصلاةِ بالقدوةِ لا الإكراه، أذكارٌ، دعاءٌ له',en:'Encourage prayer by example not force, adhkar, du\u2019a for him'}, who:{ar:'الأب',en:'Father'}},
    {t:{ar:'حوارُ الطاولة',en:'Table talk'}, dur:{ar:'٢٠ د',en:'20 min'}, act:{ar:'وجبةٌ مشتركةٌ بلا هواتف، حديثٌ عن يومِه واهتماماتِه باحترام',en:'A shared phone-free meal, respectful talk about his day & interests'}, who:{ar:'الأسرة',en:'The family'}},
    {t:{ar:'وقتُ الصحبة',en:'Companion time'}, dur:{ar:'٢٠ د',en:'20 min'}, act:{ar:'نشاطٌ يحبّه (رياضة، لعبة، مشروع) جنبًا إلى جنب',en:'An activity he loves (sport, a game, a project), side by side'}, who:{ar:'الأب',en:'Father'}},
    {t:{ar:'مشورة',en:'Consultation'}, dur:{ar:'١٠ د',en:'10 min'}, act:{ar:'استشِره في أمرٍ أسريٍّ حقيقيّ، واسمع رأيَه وقدّره',en:'Consult him on a real family matter; hear & value his view'}, who:{ar:'الأب/الأم',en:'Father/Mother'}},
    {t:{ar:'قبل النوم',en:'Before sleep'}, dur:{ar:'حسب الحال',en:'as it flows'}, act:{ar:'لحظةٌ هادئةٌ يفتح فيها قلبَه أحيانًا؛ كُن متاحًا بلا إلحاح',en:'A calm moment when his heart sometimes opens; be available without pressing'}, who:{ar:'الأب/الأم',en:'Father/Mother'}},
  ],
  weekly:[
    {d:{ar:'يوميًّا',en:'Daily'}, act:{ar:'وجبةٌ بلا هواتف + إصغاءٌ بلا حكم + تشجيعُ صلاةٍ بالقدوة',en:'A phone-free meal + non-judging listening + prayer by example'}},
    {d:{ar:'أسبوعيًّا',en:'Weekly'}, act:{ar:'نشاطٌ مميّزٌ ينتظره (رياضة، رحلة، مشروع) صداقةً خالصة',en:'An anticipated special activity (sport, an outing, a project) \u2014 pure friendship'}},
    {d:{ar:'الجمعة',en:'Friday'}, act:{ar:'صلاةُ الجمعةِ معًا، حديثٌ عن قدوةٍ شابّة، دورٌ له في الأسرة',en:'Jumu\u2019ah together, talk of a young role model, a family role for him'}},
  ],
  fatherFocus:{ar:'الأبُ هو القدوةُ الأهمُّ للابنِ في هذه السنّ، والمرساةُ التي تمنعه من الانجرافِ مع الأقران. لا تُحاضِره؛ صاحِبْه. اخرج معه، مارِس رياضةً معه، أشركه في عملٍ رجوليّ، واطلب رأيَه في أمورِ البيت. عاتِبه على انفرادٍ دائمًا ولا تجرح كرامتَه أمام أحد. إن أخطأ فاستُره وعالِج الخطأ بحبّ. أكبرُ استثمارٍ الآن: أن يشعر أنّك صفُّه وسندُه لا خصمُه ورقيبُه — فيأتيك بمشكلاتِه بدل أن يخبّئها.',
    en:'The father is the most important role model for a son at this age, and the anchor that keeps him from drifting with peers. Don\u2019t lecture him; befriend him. Go out with him, play sport with him, involve him in \u201cgrown-up\u201d work, & ask his opinion on household matters. Always reproach him privately & never wound his dignity before anyone. If he errs, cover him & treat the error with love. The greatest investment now: that he feels you are his ally & support, not his opponent & watchman \u2014 so he brings you his problems instead of hiding them.'},
  activities:[
    {ic:'⚽', t:{ar:'رياضةُ الصداقة',en:'Friendship sport'}, how:{ar:'مارِس معه رياضةً أسبوعيّةً ثابتةً نِدًّا لنِدّ؛ اخسر أحيانًا واضحك معه.',en:'Play a fixed weekly sport with him as an equal; lose sometimes & laugh together.'}, why:{ar:'يبني الصداقةَ والثقةَ ويفرّغ طاقتَه.',en:'Builds friendship & trust & releases his energy.'}},
    {ic:'🗳️', t:{ar:'مجلسُ الشورى',en:'The consultation council'}, how:{ar:'أشركه في قرارٍ أسريٍّ حقيقيّ (رحلة، شراء، تنظيم) واعملوا برأيه أحيانًا.',en:'Involve him in a real family decision (a trip, a purchase, organizing) & act on his view sometimes.'}, why:{ar:'يشبع حاجةَ الاحترامِ والاستقلالِ والقيمة.',en:'Satisfies his need for respect, autonomy & worth.'}},
    {ic:'💬', t:{ar:'حوارُ الشبهات',en:'The doubts dialogue'}, how:{ar:'افتح بابًا آمنًا لأسئلتِه عن الدينِ والحياةِ والشبهات، وناقشها بعلمٍ وصدرٍ رحب.',en:'Open a safe door for his questions on faith, life & doubts; discuss them with knowledge & an open chest.'}, why:{ar:'يحصّن إيمانَه ويمنعه من مصادرَ ملوّثة.',en:'Fortifies his faith & keeps him from polluted sources.'}},
    {ic:'🛠️', t:{ar:'مشروعٌ رجوليّ',en:'A man\u2019s project'}, how:{ar:'أنجِزا معًا شيئًا حقيقيًّا (إصلاح، مشروعٌ صغير، عملٌ تطوّعيّ) وثِق بقدرته.',en:'Build something real together (a repair, a small business, volunteering) & trust his ability.'}, why:{ar:'يبني الكفاءةَ والرجولةَ والمسؤوليّة.',en:'Builds competence, manhood & responsibility.'}},
    {ic:'🕌', t:{ar:'رفقةُ الخير',en:'Good company'}, how:{ar:'اربطه بحلقةِ مسجدٍ أو نشاطٍ شبابيٍّ صالحٍ وقدوةٍ شابّةٍ يحترمها.',en:'Connect him to a masjid circle or wholesome youth activity & a young role model he respects.'}, why:{ar:'الأقرانُ مرجعُه الآن؛ فلتكن صالحة.',en:'Peers are his reference now; make them good.'}},
    {ic:'🎯', t:{ar:'اكتشافُ الموهبة',en:'Discovering his gift'}, how:{ar:'ساعِده على اكتشافِ موهبتِه (خطابة، برمجة، خطّ، تجارة) وادعمها.',en:'Help him discover his talent (speaking, coding, calligraphy, trade) & back it.'}, why:{ar:'يبني هُويّةً إيجابيّةً ويملأ فراغَه بالنافع.',en:'Builds a positive identity & fills idleness with benefit.'}},
  ],
  examples:[
    {title:{ar:'تركَ صلاةً أو تهاون فيها',en:'He skipped or slacked on a prayer'}, scene:{ar:'تكتشف أنّه ترك صلاةً أو يصلّيها بتكاسلٍ بعد البلوغ.',en:'You find he skipped a prayer or prays it lazily after puberty.'},
      do:{ar:'ذكّره بهدوءٍ على انفرادٍ أنّه صار مسؤولًا أمام الله، صلِّ معه، اربط الصلاةَ بحاجتِه هو (راحة، نجاح، علاقة بالله)، وكن أنت قدوةً ثابتة.',en:'Remind him calmly & privately that he\u2019s now accountable to Allah, pray with him, link prayer to his own needs (peace, success, closeness to Allah), & be a steady example.'},
      dont:{ar:'لا تجبره بالعنفِ أو الفضحِ أو التهديد؛ يصلّي نفاقًا أو يتركها عنادًا.',en:'Don\u2019t force by violence, exposure or threats; he\u2019ll pray hypocritically or quit defiantly.'},
      root:{ar:'بعد البلوغِ العبادةُ قناعةٌ لا إلزام؛ مهمّتك أن تحبّبها لا أن تفرضها.',en:'After puberty, worship is conviction not compulsion; your task is to endear it, not impose it.'}},
    {title:{ar:'ثورةٌ وكلامٌ حادّ: «أنتم لا تفهمونني»',en:'An outburst: \u201cyou don\u2019t understand me\u201d'}, scene:{ar:'يرفع صوتَه ويعترض بحدّةٍ ويتّهمك بعدمِ الفهم.',en:'He raises his voice, objects sharply, & accuses you of not understanding.'},
      do:{ar:'لا تردّ بالمثل؛ اخفض صوتك، تقبّل شعورَه: «أرى أنّك غاضبٌ ومحقٌّ أن تُسمَع»، وأجِّل النقاشَ حتى يهدأ ثمّ استمع له بصدق.',en:'Don\u2019t match him; lower your voice, validate: \u201cI see you\u2019re angry & deserve to be heard,\u201d & postpone the discussion till calm, then truly listen.'},
      dont:{ar:'لا تصرخ ولا تقل «اخرس» ولا تحقّره؛ كلُّ إذلالٍ يقطع الجسرَ بينكما.',en:'Don\u2019t shout, say \u201cbe quiet,\u201d or belittle him; every humiliation cuts the bridge between you.'},
      root:{ar:'ثورتُه دماغٌ مراهقٌ لم يكتمل كبحُه، لا عداوةٌ لك؛ هدوؤك يعلّمه ضبطَ نفسه.',en:'His outburst is an adolescent brain whose brakes aren\u2019t mature, not enmity; your calm teaches him self-control.'}},
  ],
  problems:[
    {p:{ar:'التمرّدُ ومعارضةُ كلِّ شيء',en:'Rebellion & opposing everything'},
      why:{ar:'بحثٌ عن الهُويّةِ والاستقلال، ودماغٌ اندفاعيٌّ، وشعورٌ بأنّه لا يُحترَم أو لا يُسمَع.',en:'A search for identity & autonomy, an impulsive brain, & feeling disrespected or unheard.'},
      islamic:{ar:'الرفقُ والمشاورة؛ «وشاورهم في الأمر»، وقد لان النبيُّ ﷺ للشبابِ وأشركهم. ولا تقابل السيّئةَ بمثلها.',en:'Gentleness & consultation; \u201cconsult them,\u201d & the Prophet ﷺ was gentle with youth & involved them. Don\u2019t meet a wrong with its like.'},
      psych:{ar:'قلّل المعاركَ واختر أهمَّها، امنحه استقلالًا في الصغائرِ ليقبل حدودك في الكبائر، وحافِظ على التعلّقِ قبل التوجيه.',en:'Pick fewer battles & only the important ones, grant autonomy in small things so he accepts limits in big ones, & keep attachment before direction.'},
      steps:[{ar:'اختر معاركك: تجاهل الصغائرَ واثبُت في الأصول.',en:'Pick your battles: overlook trifles, stand firm on essentials.'},{ar:'حوّل الأمرَ إلى خيارٍ أو اتفاقٍ متبادل.',en:'Turn commands into choices or mutual agreements.'},{ar:'عاتِب سرًّا، امدح علنًا، ولا تجرح كرامتَه.',en:'Reproach privately, praise publicly, never wound his dignity.'},{ar:'حافِظ على وقتِ الصحبةِ مهما اشتدّ التوتّر.',en:'Keep companion-time no matter how tense things get.'},{ar:'كن قدوةً في ضبطِ غضبك أمامه.',en:'Model anger-control before him.'}]},
    {p:{ar:'الانجرافُ مع رفقةِ السوءِ ووسائلِ التواصل',en:'Drifting with bad company & social media'},
      why:{ar:'الأقرانُ مرجعُه الآن، والحاجةُ للانتماءِ قويّة، والفراغُ يجذبه لأيِّ جماعةٍ تقبله.',en:'Peers are his reference now, the need to belong is strong, & idleness pulls him to any group that accepts him.'},
      islamic:{ar:'«المرءُ على دينِ خليله»؛ والرفقةُ الصالحةُ حصنٌ. ووفِّر له الانتماءَ الطيّبَ بدل المنعِ وحده.',en:'\u201cA person follows his friend\u2019s way\u201d; good company is a fortress. Provide good belonging rather than only banning.'},
      psych:{ar:'لا تهاجم أصدقاءَه مباشرةً؛ قوِّ قيمَه من الداخل، ووفّر بيئةً بديلةً جاذبة، وراقِب بوعيٍ لا بتجسّسٍ يكسر الثقة.',en:'Don\u2019t attack his friends directly; strengthen his values from within, provide an attractive alternative environment, & monitor consciously \u2014 not spying that breaks trust.'},
      steps:[{ar:'اعرف أصدقاءَه واستضِفهم لتراهم عن قُرب.',en:'Know his friends & host them to see them up close.'},{ar:'وفّر رفقةً صالحةً جاذبةً (نشاط، حلقة، نادٍ).',en:'Provide attractive good company (an activity, circle, club).'},{ar:'ناقش صفاتِ الصديقِ الحقّ بدل ذمِّ أشخاص.',en:'Discuss the traits of a true friend rather than condemning people.'},{ar:'اتّفقا على حدودِ وسائلِ التواصلِ بالحوار.',en:'Agree on social-media limits through dialogue.'},{ar:'املأ فراغَه بهدفٍ ونشاطٍ ومسؤوليّة.',en:'Fill his idleness with purpose, activity & responsibility.'}]},
  ],
  checklist:[
    {ar:'أعامله كصديقٍ: أُشاوره وأحترمُ رأيَه ولا أُذِلّه',en:'I treat him as a friend: consult, respect his view, never humiliate'},
    {ar:'علّمتُه أنّه مكلّفٌ مسؤولٌ أمام الله بعد البلوغ',en:'I taught him he is now accountable before Allah'},
    {ar:'يملكُ صلاتَه وعبادتَه عن قناعةٍ ذاتيّة',en:'He owns his prayer & worship by personal conviction'},
    {ar:'أعرفُ أصدقاءَه ومتابعاتِه على وسائل التواصل',en:'I know his friends & what he follows on social media'},
    {ar:'أُنصِتُ أكثرَ ممّا أُحاضِر، وأناقشُ شبهاتِه بصدرٍ رحب',en:'I listen more than I lecture, & discuss his doubts openly'},
    {ar:'أعطيتُه دورًا ومسؤوليّةً حقيقيّةً في البيت',en:'I gave him a real role & responsibility at home'},
    {ar:'أعاتبه سرًّا وأمدحه علنًا ولا أجرح كرامتَه',en:'I reproach privately, praise publicly, & never wound his dignity'},
    {ar:'لنا نشاطٌ أسبوعيٌّ صداقةً خالصةً لا استجواب',en:'We have a weekly activity \u2014 pure friendship, not interrogation'},
  ],
  followup:[
    {period:{ar:'يوميًّا',en:'Daily'}, item:{ar:'هل احتفظتُ بهدوئي معه؟ هل أصغيتُ بلا حكم؟ هل صلّى عن رضا؟',en:'Did I keep calm with him? Did I listen without judging? Did he pray willingly?'}},
    {period:{ar:'أسبوعيًّا',en:'Weekly'}, item:{ar:'هل تمّ نشاطُ الصحبة؟ كيف حالُ رفقتِه ومزاجِه؟ أيُّ شبهةٍ أو همٍّ ظهر؟',en:'Did the companion-activity happen? How is his company & mood? Any doubt or worry surfaced?'}},
    {period:{ar:'شهريًّا',en:'Monthly'}, item:{ar:'مراجعةُ علاقتِه بالصلاةِ والهُويّةِ والأصدقاء، ومستوى الثقةِ والحوارِ بيننا.',en:'Review his bond with prayer, identity & friends, & the level of trust & dialogue between us.'}},
  ],
  practice:{
    track:{ar:'ما بعد المسارات — مرحلةُ المصاحبة',en:'Beyond the tracks — the companionship stage'},
    items:[
      {ar:'حوّل الموقعَ من «منهجٍ» إلى «حوار»: ناقشه في رحلاتِ «القدس والأمة» و«حصن الأبطال» كنقاشِ ندٍّ لندّ، لا كدرسٍ يُلقَّن.',en:'Turn the site from \u201ccurriculum\u201d into \u201cconversation\u201d: discuss the Al-Quds & Heroes\u2019 Fortress journeys peer-to-peer, not as a lecture.'},
      {ar:'أعطه دورًا حقيقيًّا: يُعلّم إخوتَه الصغارَ من كتبِ الأنشطة، ويقود «نقاطَ السلوك» للأسرةِ في «ركن الأهل».',en:'Give him a real role: teaching younger siblings from the activity books, & leading the family\u2019s behaviour-points in the Parents\u2019 Corner.'},
    ]},
});
