/* stage-7.js — المرحلة السابعة · +18 · الرشد والإطلاق */
window.TARBIYAH.stages.push({
  id:'s7', age:'+18', ic:'🌳', c:'#0E7C66',
  nm:{ar:'الرشدُ والإطلاق', en:'Adulthood & Release'},
  sub:{ar:'ما بعد الثامنة عشرة — من ابنٍ إلى صديقٍ راشد', en:'Beyond eighteen — from child to grown friend'},
  intro:{ar:'انتهت سنواتُ الولايةِ التربويّةِ وبدأت سنواتُ الأخوّةِ والنصح. ابنُك الآن رجلٌ مسؤولٌ عن نفسِه، يبني حياتَه ويتّخذ قرارَه. لم يَعُد دورُك أن تُربّي بل أن تُرافِق: مستشارٌ حين يُستشار، داعٍ له دائمًا، وقاعدةٌ آمنةٌ يعود إليها. أعظمُ نجاحِ التربيةِ أن تُخرّج رجلًا يستغني عنك في قرارِه ويبقى موصولًا بك في قلبه. وتذكّر أنّ برَّك به لا ينقطع، وأنّ دعاءَك له يبقى أنفعَ ما تُهديه ما حييت.',
    en:'The years of guardianship have ended; the years of brotherhood & counsel begin. Your child is now a man responsible for himself, building his life & making his decisions. Your role is no longer to raise but to accompany: a consultant when consulted, always a supplicant for him, & a secure base he returns to. The greatest success of tarbiyah is to graduate a man independent of you in decision yet connected to you in heart. Remember your kindness to him never ends, & your du\u2019a for him remains the most beneficial gift you can give as long as you live.'},
  glance:[
    {ic:'⏳', k:{ar:'جرعةُ الوقت',en:'Time dose'}, v:{ar:'حضورٌ متاحٌ عند الطلب + دعاءٌ دائم',en:'Available on request + constant du\u2019a'}},
    {ic:'🎯', k:{ar:'المهمّةُ الكبرى',en:'Core task'}, v:{ar:'الإطلاقُ مع بقاءِ الرابطة',en:'Release while keeping the bond'}},
    {ic:'🚫', k:{ar:'الخطُّ الأحمر',en:'Red line'}, v:{ar:'لا تدخّلَ في بيتِه ولا محاسبةَ طفل',en:'No intruding in his home, no treating him as a child'}},
    {ic:'🗝️', k:{ar:'الكلمةُ المفتاح',en:'Keyword'}, v:{ar:'الثقةُ والدعاء',en:'Trust & du\u2019a'}},
  ],
  scholar:{ar:'تمَّ المثلُ النبويُّ: «لاعِبه سبعًا، وأدِّبه سبعًا، وصاحِبه سبعًا، ثمّ اترك له الحبلَ على الغارب». انتهى زمنُ الولايةِ وبدأ زمنُ الصحبةِ الكاملةِ والنصحِ بالحكمة. الابنُ الآن مكلّفٌ مسؤولٌ عن نفسِه أمام الله، وحقُّه عليك أن تُعينَه على برِّك لا أن تُثقِله، وأن تُحسِنَ تزويجَه إن أراد، وأن تحترمَ استقلالَه وقرارَه.\n\nقال النبيُّ ﷺ: «إذا أتاكم من ترضَون دينَه وخُلُقَه فزوّجوه». فالإعانةُ على الزواجِ من تمامِ التربية. ودورُك تحوّل إلى الدعاءِ والمشورةِ عند الطلبِ والدعمِ المتاح. ولا ينقطع برُّك به ولا حبُّك له؛ بل يبقى «وقُل ربِّ ارحمهما كما ربّياني صغيرًا» شاهدًا أنّ الرحمةَ متبادلةٌ وممتدّة.\n\nواحذر آفتَين: أن تُحاسبَه كطفلٍ أو تتدخّلَ في بيتِه وزوجتِه وقرارِه؛ فالحكمةُ أن تكونَ مرجعَه لا رقيبَه، ومستشارَه لا وصيَّه. وأعظمُ ثمرةٍ ترجوها: ولدٌ صالحٌ يدعو لك بعد موتك، فيبقى أجرُك جاريًا ما دعا.',
    en:'The prophetic maxim is complete: \u201cPlay with him seven, discipline him seven, befriend him seven, then loosen the rope.\u201d Guardianship has ended & the time of full companionship & wise counsel begins. The son is now accountable for himself before Allah; his right upon you is that you help him honour you rather than burden him, help him marry well if he wishes, & respect his independence & decisions.\n\nThe Prophet ﷺ said: \u201cWhen one whose religion & character please you proposes, marry him.\u201d Helping toward marriage completes the upbringing. Your role shifts to du\u2019a, counsel when asked, & available support. Your kindness & love never cease; \u201cMy Lord, have mercy on them as they raised me young\u201d testifies that mercy is mutual & enduring.\n\nBeware two pitfalls: treating him as a child, or intruding in his home, wife & decisions. Wisdom is to be his reference, not his watchman; his consultant, not his guardian. The greatest fruit you hope for: a righteous child who prays for you after your death \u2014 so your reward keeps flowing as long as he prays.'},
  psych:{ar:'يصف إريكسون مطلعَ الرشدِ بـ«الألفة مقابل العزلة»: مهمّةُ هذه السنِّ بناءُ علاقاتٍ ناضجةٍ، وزواجٍ، وعملٍ، وهُويّةٍ مستقلّة. يحتاج الراشدُ الناشئ أن يُستقَلَّ ماليًّا وعاطفيًّا، وأن يُحترَم استقلالُه وقراراتُه حتى لو خالفت رأيَك.\n\nتدخّلُ الوالدينِ المفرطُ في حياةِ الراشدِ (الزواج، العمل، تربيةُ أبنائه) يعطّل نضجَه ويولّد إمّا تبعيّةً عاجزةً أو قطيعةً نافرة. وربطُه عاطفيًّا بالشعورِ بالذنبِ («ضحّينا من أجلك») يكبّله ولا يقرّبه. أمّا الدعمُ المتاحُ بلا فرضٍ — القاعدةُ الآمنةُ التي يعود إليها — فيصنع راشدًا متّزنًا قادرًا على بناءِ أسرةٍ سويّة.\n\nأنت تنتقل نفسيًّا من «مدير» إلى «مستشار»: لا تُصدِر الأوامرَ بل تُتيح الخبرةَ حين تُطلَب. ونظريّةُ التعلّقِ في الرشدِ تؤكّد أنّ العلاقةَ الدافئةَ الممتدّةَ بين الوالدِ وابنِه الراشدِ من أقوى عواملِ استقرارِه النفسيِّ وسعادتِه — لا تنتهي الحاجةُ إليك، بل يتغيّر شكلُها.',
    en:'Erikson describes early adulthood as \u201cintimacy vs isolation\u201d: this age\u2019s task is building mature relationships, marriage, work & an independent identity. The emerging adult needs financial & emotional independence, & respect for his autonomy & decisions even when they differ from yours.\n\nParents\u2019 over-involvement in an adult\u2019s life (marriage, work, raising his children) stalls his maturity & breeds either helpless dependence or resentful estrangement. Binding him through guilt (\u201cwe sacrificed for you\u201d) shackles rather than draws him near. Available support without imposition \u2014 the secure base he returns to \u2014 produces a balanced adult capable of building a healthy family.\n\nYou move psychologically from \u201cmanager\u201d to \u201cconsultant\u201d: not issuing orders but offering experience when asked. Adult attachment theory confirms that a warm, enduring parent\u2013adult-child relationship is among the strongest factors in his psychological stability & happiness \u2014 the need for you doesn\u2019t end; its form changes.'},
  specialists:[
    {q:{ar:'«أنجحُ الآباءِ من ربّى ابنَه ليستغنيَ عنه؛ غايةُ التربيةِ استقلالٌ لا تبعيّة».',en:'\u201cThe best parents raise a child to not need them; the goal of tarbiyah is independence, not dependence.\u201d'}, by:{ar:'من غاياتِ التربية',en:'On the aims of tarbiyah'}},
    {q:{ar:'«كُن قاعدتَه الآمنة: متاحًا حين يُطلَب، صامتًا حين لا يُطلَب، داعيًا له دائمًا».',en:'\u201cBe his secure base: available when sought, silent when not, praying for him always.\u201d'}, by:{ar:'نظريّةُ التعلّقِ في الرشد',en:'Adult attachment theory'}},
    {q:{ar:'«لا تربط برَّه بالذنب؛ البرُّ المفروضُ بالعتابِ يَجفُّ، والبرُّ النابعُ من الحبِّ يدوم».',en:'\u201cDon\u2019t tie his devotion to guilt; devotion forced by reproach dries up, but devotion from love endures.\u201d'}, by:{ar:'من إرشادِ الأسرة',en:'Family counselling'}},
  ],
  evidences:[
    {type:'hadith', text:{ar:'«إذا مات الإنسانُ انقطع عملُه إلّا من ثلاث... أو ولدٍ صالحٍ يدعو له».',en:'\u201cWhen a person dies his deeds end, except three... or a righteous child who prays for him.\u201d'}, ref:{ar:'مسلم',en:'Muslim'}, note:{ar:'ثمرةُ تربيتِك تبقى بعد موتك.',en:'The fruit of your upbringing remains after your death.'}},
    {type:'hadith', text:{ar:'«إذا أتاكم من ترضَون دينَه وخُلُقَه فزوّجوه».',en:'\u201cWhen one whose religion & character please you proposes, marry him.\u201d'}, ref:{ar:'الترمذيّ',en:'Tirmidhi'}, note:{ar:'الإعانةُ على الزواجِ من تمامِ البرّ.',en:'Helping toward marriage completes devotion.'}},
    {type:'ayah', text:{ar:'﴿وَقُل رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا﴾',en:'\u201cMy Lord, have mercy on them as they raised me when I was small.\u201d'}, ref:{ar:'الإسراء ٢٤',en:'al-Isra 24'}, note:{ar:'البرُّ والرحمةُ متبادلةٌ تدوم مدى الحياة.',en:'Devotion & mercy are mutual & lifelong.'}},
  ],
  rewards:[
    {ic:'🌳', t:{ar:'أجرٌ جارٍ بعد الموت',en:'Reward flowing after death'}, d:{ar:'الولدُ الصالحُ الذي يدعو لك يُبقي صحيفتَك مفتوحةً وأنت في قبرك.',en:'A righteous child who prays for you keeps your record open while you lie in your grave.'}},
    {ic:'🤲', t:{ar:'برٌّ متبادلٌ وصِلةٌ تدوم',en:'Mutual devotion & a lasting tie'}, d:{ar:'من أحسن تربيةَ ابنِه جنى برَّه رجلًا، وبقيت بينهما مودّةٌ يظلّلها الدعاء.',en:'Whoever raised his child well reaps his devotion as a man, with an enduring affection shaded by du\u2019a.'}},
    {ic:'🕋', t:{ar:'جيلٌ صالحٌ يمتدّ بعدك',en:'A righteous generation extending beyond you'}, d:{ar:'حين يصير هو مربّيًا صالحًا، امتدّ أثرُك في أحفادِك وأجرُهم في ميزانك.',en:'When he becomes a good educator, your impact extends to your grandchildren, their reward in your scale.'}},
  ],
  needs:[
    {ar:'الاحترامُ الكاملُ لاستقلالِه وقراراتِه',en:'Full respect for his independence & decisions'},
    {ar:'المشورةُ عند الطلبِ لا التدخّلُ المفروض',en:'Counsel when asked, not imposed interference'},
    {ar:'الإعانةُ على الزواجِ وبناءِ بيتِه',en:'Help toward marriage & building his home'},
    {ar:'بقاءُ الرابطةِ: الزيارةُ والدعاءُ والحبُّ المعلَن',en:'A lasting bond: visits, du\u2019a & expressed love'},
    {ar:'الثقةُ بثمرةِ تربيتِك وتسليمُ الأمرِ لله',en:'Trust in the fruit of your tarbiyah & reliance on Allah'},
    {ar:'دعمٌ متاحٌ بلا منٍّ ولا ربطٍ بالذنب',en:'Available support, without reproach or guilt-tripping'},
  ],
  risks:[
    {ar:'التدخّلُ في بيتِه وزواجِه وقراراتِه',en:'Intruding in his home, marriage & choices'},
    {ar:'محاسبتُه كطفلٍ أو ربطُه عاطفيًّا بالذنب',en:'Treating him as a child or binding him with guilt'},
    {ar:'القطيعةُ عند اختلافِ الرأيِ أو الطريق',en:'Estrangement over a difference of view or path'},
    {ar:'إهمالُ الدعاءِ له والظنُّ أنّ الدورَ انتهى',en:'Neglecting du\u2019a for him, thinking the role is over'},
    {ar:'المقارنةُ بينه وبين إخوتِه أو أبناءِ غيره',en:'Comparing him to siblings or others\u2019 children'},
    {ar:'تحميلُه ما لا يطيق من توقّعاتٍ ومطالب',en:'Burdening him with expectations beyond his capacity'},
  ],
  values:[
    {ar:'البرُّ المتبادلُ وصِلةُ الرحم',en:'Mutual devotion & keeping kinship ties'},
    {ar:'الاستقلالُ وتحمّلُ مسؤوليّةِ أسرتِه',en:'Independence & owning his family\u2019s responsibility'},
    {ar:'استمرارُ طلبِ العلمِ والعملِ الصالح',en:'Continuing knowledge & righteous action'},
    {ar:'حملُ الرسالةِ إلى الجيلِ التالي',en:'Carrying the mission to the next generation'},
  ],
  dose:{ar:'لم يَعُد الوقتُ يُقاس بجرعةٍ يوميّةٍ مفروضة، بل بحضورٍ متاحٍ حين يحتاج، وزيارةٍ ووصلٍ منتظمٍ بلا إثقال، ودعاءٍ دائمٍ في ظهرِ الغيب. اجعل لقاءاتِكم مودّةً لا محاسبة، ومكالماتِك سؤالًا عن حالِه لا تفتيشًا عن أخطائه. القاعدة: قُربٌ بلا خنق، ودعمٌ بلا فرض، وبابٌ مفتوحٌ دائمًا.',
    en:'Time is no longer a fixed daily dose but available presence when he needs it, regular visiting & connection without burdening, & constant du\u2019a in his absence. Make your meetings affection, not accountability, & your calls an asking after him, not an inspection of his faults. The rule: closeness without smothering, support without imposing, & an always-open door.'},
  daily:[
    {t:{ar:'في سجودك',en:'In your sujood'}, dur:{ar:'دائم',en:'always'}, act:{ar:'الدعاءُ له بالصلاحِ والتوفيقِ والثباتِ والبركةِ في أهله',en:'Du\u2019a for his righteousness, success, steadfastness & blessing in his family'}, who:{ar:'الأب/الأم',en:'Father/Mother'}},
    {t:{ar:'تواصلٌ خفيف',en:'Light contact'}, dur:{ar:'قصير',en:'brief'}, act:{ar:'رسالةٌ أو مكالمةٌ مودّةٍ تسأل عن حالِه بلا تفتيش',en:'A message or call of affection, asking after him without inspecting'}, who:{ar:'الأب/الأم',en:'Father/Mother'}},
    {t:{ar:'عند الطلب',en:'When asked'}, dur:{ar:'كما يحتاج',en:'as needed'}, act:{ar:'مشورةٌ صادقةٌ بخبرتِك حين يستشيرك، ثمّ تترك له القرار',en:'Honest counsel from your experience when consulted, then leave him the decision'}, who:{ar:'الأب/الأم',en:'Father/Mother'}},
  ],
  weekly:[
    {d:{ar:'أسبوعيًّا',en:'Weekly'}, act:{ar:'زيارةٌ أو لقاءٌ أو مكالمةٌ تجمع الأسرةَ مودّةً وصِلةً',en:'A visit, gathering or call uniting the family in affection & ties'}},
    {d:{ar:'عند القرار',en:'At decisions'}, act:{ar:'كُن متاحًا للمشورةِ في الزواجِ والعملِ دون أن تفرض رأيَك',en:'Be available for counsel on marriage & work without imposing your view'}},
    {d:{ar:'دائمًا',en:'Always'}, act:{ar:'بابٌ مفتوحٌ وقاعدةٌ آمنةٌ يعود إليها وقتَ الشدّة',en:'An open door & a secure base he returns to in hardship'}},
  ],
  fatherFocus:{ar:'دورُك الآن أن تكون الأبَ الصديقَ والمستشارَ، لا المديرَ والرقيب. إن استشارك فأعطِه خلاصةَ خبرتِك بصدقٍ ثمّ اترك له القرارَ واحترمه ولو خالفك. أعِنه على الزواجِ وبناءِ حياتِه ما استطعت، ولا تتدخّل في بيتِه ولا تربيةِ أبنائه إلّا إذا طُلِب. صِل رحمَه وزُره، وأظهِر له حبَّك بالكلمةِ والفعل، وادعُ له في خلواتك. وتذكّر أنّ أجملَ ما يبقى بينكما رابطةُ حبٍّ واحترامٍ لا سلطةُ أمرٍ ونهي؛ فأنت الآن تجني ثمرةَ سنواتٍ من الغرس.',
    en:'Your role now is to be the father-friend & consultant, not the manager & monitor. If he consults you, give the essence of your experience honestly, then leave him the decision & respect it even if it differs from yours. Help him toward marriage & building his life as you can, & don\u2019t interfere in his home or raising his children unless asked. Keep kinship & visit him, show your love in word & deed, & pray for him in your private moments. Remember the most beautiful thing remaining between you is a bond of love & respect, not the authority of command & prohibition; you are now reaping the fruit of years of planting.'},
  activities:[
    {ic:'🤲', t:{ar:'دعاءُ الغيب',en:'Du\u2019a in his absence'}, how:{ar:'اجعل له نصيبًا ثابتًا في سجودك وأدبارِ صلواتك بالصلاحِ والتوفيق.',en:'Give him a fixed share in your sujood & after prayers \u2014 for righteousness & success.'}, why:{ar:'أنفعُ هديّةٍ وأبقاها، ودعوةُ الوالدِ مستجابة.',en:'The most beneficial, lasting gift; a parent\u2019s du\u2019a is answered.'}},
    {ic:'💍', t:{ar:'عونُ الزواج',en:'Help toward marriage'}, how:{ar:'أعِنه على الزواجِ بالمشورةِ والمالِ والتيسيرِ متى أراد، وفق سُنّةِ التيسير.',en:'Help him marry with counsel, means & ease when he wishes, per the sunnah of facilitation.'}, why:{ar:'من تمامِ التربيةِ والبرِّ وإعفافِ الولد.',en:'Completes upbringing & devotion & guards his chastity.'}},
    {ic:'🪑', t:{ar:'مجلسُ المشورة',en:'The counsel seat'}, how:{ar:'كُن مستشارًا متاحًا: أعطِ خبرتَك حين يطلب، واصمت حين لا يطلب.',en:'Be an available consultant: give your experience when asked, stay silent when not.'}, why:{ar:'يحفظ قُربَه ويحترم رجولتَه واستقلالَه.',en:'Keeps him close while respecting his manhood & autonomy.'}},
    {ic:'🔗', t:{ar:'وصلُ الرحم',en:'Keeping the tie'}, how:{ar:'زيارةٌ ومكالمةٌ وتجمّعٌ أسريٌّ منتظمٌ يُبقي الدفءَ والانتماء.',en:'Regular visits, calls & family gatherings that keep warmth & belonging.'}, why:{ar:'الرابطةُ الدافئةُ سرُّ استقرارِه وسعادتِه.',en:'The warm bond is the secret of his stability & happiness.'}},
    {ic:'📿', t:{ar:'تسليمُ الراية',en:'Passing the banner'}, how:{ar:'سلّمه أدواتِ التربيةِ وخبرتَك ليربّيَ أبناءَه، وكُن سندَه جدًّا حانيًا.',en:'Hand him the tools of tarbiyah & your experience to raise his children, & be a tender grandfather.'}, why:{ar:'يمتدّ أثرُك في الجيلِ الثالثِ وأجرُك معه.',en:'Your impact extends to the third generation, your reward with it.'}},
    {ic:'💌', t:{ar:'كلمةُ الحبِّ الصريحة',en:'The explicit word of love'}, how:{ar:'قُل له إنّك تحبّه وتفخر به وتثق فيه؛ لا تكتفِ بإضمارِ ذلك.',en:'Tell him you love him, are proud of him & trust him; don\u2019t merely imply it.'}, why:{ar:'كلمةُ الأبِ الصريحةُ تثبّت قلبَه مهما كبر.',en:'A father\u2019s explicit word steadies his heart however old he grows.'}},
  ],
  examples:[
    {title:{ar:'يتّخذ قرارًا تخالفه فيه',en:'He makes a decision you disagree with'}, scene:{ar:'يختار عملًا أو تخصّصًا أو شريكَ حياةٍ يخالف ما كنتَ تتمنّى.',en:'He picks a job, major or spouse different from what you wished.'},
      do:{ar:'أبدِ رأيَك مرّةً بوضوحٍ وأدبٍ وبخبرتِك، ثمّ احترِم قرارَه إن كان مشروعًا، وادعُ له، وابقَ سندَه مهما اختار.',en:'State your view once, clearly, politely & from experience, then respect his decision if it is lawful, pray for him, & remain his support whatever he chooses.'},
      dont:{ar:'لا تفرض رأيَك بالضغطِ أو التهديدِ بالقطيعةِ أو الربطِ بالذنب؛ تخسر قلبَه ولا تكسب رأيَه.',en:'Don\u2019t impose your view by pressure, threats of estrangement, or guilt; you lose his heart & don\u2019t win his mind.'},
      root:{ar:'صار مسؤولًا أمام الله عن قراره؛ دورُك المشورةُ لا الوصاية، والاحترامُ يُبقي الجسر.',en:'He is now accountable to Allah for his choice; your role is counsel not guardianship, & respect keeps the bridge.'}},
    {title:{ar:'انشغل عنك بعد الزواج',en:'He gets busy with you after marriage'}, scene:{ar:'تشعر أنّه قلّت زيارتُه واتّصالُه بعد أن بنى بيتَه.',en:'You feel his visits & calls have lessened after he built his home.'},
      do:{ar:'تواصل أنت بمودّةٍ بلا عتابٍ جارح، تفهّم انشغالَه ببيتِه الجديد، رحّب بزوجتِه، واجعل بيتَك محبّبًا يقصده فرحًا لا واجبًا ثقيلًا.',en:'Reach out yourself with affection, without wounding reproach; understand his busyness with his new home, welcome his wife, & make your home so beloved he comes joyfully, not as a heavy duty.'},
      dont:{ar:'لا تُشعِره بالذنبِ («نسيتنا») ولا تُنافِس زوجتَه ولا تتدخّل في بيتِهما.',en:'Don\u2019t guilt him (\u201cyou forgot us\u201d), compete with his wife, or interfere in their home.'},
      root:{ar:'بناءُ بيتٍ مستقلٍّ نضجٌ صحّيّ؛ الودُّ يجذبه والعتبُ يُبعده، والصلةُ تُبنى بالحبِّ لا باللوم.',en:'Building an independent home is healthy maturity; affection draws him & reproach repels him; ties are built by love, not blame.'}},
  ],
  problems:[
    {p:{ar:'التوتّرُ عند اختلافِ القراراتِ والطريق',en:'Tension over differing decisions & paths'},
      why:{ar:'رغبةُ الوالدِ في الحمايةِ والسيطرةِ تصطدم بحاجةِ الراشدِ للاستقلالِ وإثباتِ ذاته.',en:'The parent\u2019s wish to protect & control collides with the adult\u2019s need for independence & self-assertion.'},
      islamic:{ar:'الشورى ثمّ ترك القرار؛ النبيُّ ﷺ شاور أصحابَه وأخذ برأيِهم. والرفقُ واحترامُ العقلِ من البرّ المتبادل.',en:'Consultation, then leaving the decision; the Prophet ﷺ consulted his Companions & took their view. Gentleness & respecting his reason are mutual devotion.'},
      psych:{ar:'انتقل من «المدير» إلى «المستشار»؛ أعطِ رأيك مرّةً واحترِم اختياره. الفرضُ يولّد القطيعةَ أو التبعيّة.',en:'Move from \u201cmanager\u201d to \u201cconsultant\u201d; give your view once & respect his choice. Imposition breeds estrangement or dependence.'},
      steps:[{ar:'أبدِ رأيك مرّةً بوضوحٍ وخبرةٍ ثمّ توقّف.',en:'State your view once, clearly & from experience, then stop.'},{ar:'احترِم قرارَه المشروعَ ولو خالف رغبتَك.',en:'Respect his lawful decision even against your wish.'},{ar:'لا تربط حبَّك أو رضاك بطاعتِه لرأيك.',en:'Don\u2019t tie your love or approval to his obeying your view.'},{ar:'ابقَ سندَه إن تعثّر بلا «قلتُ لك».',en:'Remain his support if he stumbles, without \u201cI told you so.\u201d'},{ar:'ادعُ له بالتوفيقِ وسلّم الأمرَ لله.',en:'Pray for his success & entrust the matter to Allah.'}]},
    {p:{ar:'تباعدٌ وفتورٌ في الصلةِ بعد الاستقلال',en:'Drifting & cooling of ties after independence'},
      why:{ar:'انشغالُ الراشدِ ببيتِه وعملِه، أو تراكمُ عتابٍ قديمٍ، أو شعورُه بأنّ الزيارةَ محاسبةٌ لا مودّة.',en:'The adult\u2019s busyness with home & work, accumulated old reproach, or feeling visits are accountability not affection.'},
      islamic:{ar:'صِلةُ الرحمِ تَصِل من قطعك؛ «ليس الواصلُ بالمكافئ». بادِر أنت بالوصلِ ولو قصّر، فالأجرُ في المبادرة.',en:'Keeping ties means connecting who cut you off; \u201cthe one who keeps ties is not he who merely reciprocates.\u201d Initiate connection even if he falls short \u2014 the reward is in initiating.'},
      psych:{ar:'اجعل اللقاءَ مكافأةً عاطفيّةً لا عبئًا؛ الترحيبُ والدفءُ يجذبان، والعتبُ والمحاسبةُ تُبعدان.',en:'Make meeting an emotional reward, not a burden; welcome & warmth attract, reproach & accounting repel.'},
      steps:[{ar:'بادِر بالتواصلِ بمودّةٍ بلا عتابٍ ولا منّة.',en:'Initiate contact with affection, without reproach or favours held over him.'},{ar:'تفهّم ظروفَه وانشغالاتِه الجديدة.',en:'Understand his new circumstances & busyness.'},{ar:'رحّب بزوجتِه وأسرتِه واجعل بيتَك محبّبًا.',en:'Welcome his wife & family & make your home beloved.'},{ar:'اجعل اللقاءَ فرحًا وذكرى طيّبةً لا تحقيقًا.',en:'Make meeting joyful & a fond memory, not an interrogation.'},{ar:'ادعُ له وتذكّر أنّ برَّه يكبر مع دفءِ علاقتِكما.',en:'Pray for him & remember his devotion grows with your relationship\u2019s warmth.'}]},
  ],
  checklist:[
    {ar:'أحترمُ استقلالَه وقراراتِه ولا أتدخّل في بيتِه',en:'I respect his independence & decisions, & don\u2019t intrude in his home'},
    {ar:'أُشيرُ عليه حين يطلب، وأصمتُ حين لا يطلب',en:'I advise when asked, & stay silent when not'},
    {ar:'أعنتُه على الزواجِ وبناءِ حياتِه ما استطعت',en:'I helped him toward marriage & building his life as I could'},
    {ar:'أبقى على صِلتِه بالزيارةِ والحبِّ المعلَن',en:'I keep our bond through visits & expressed love'},
    {ar:'لا أربط برَّه بالذنبِ ولا أُحاسبه كطفل',en:'I don\u2019t tie his devotion to guilt nor treat him as a child'},
    {ar:'أدعو له في سجودي ولا أظنّ أنّ دوري انتهى',en:'I pray for him in my sujood & never think my role is over'},
    {ar:'أُرحّب بزوجتِه وأسرتِه ولا أُنافسهم على قلبه',en:'I welcome his wife & family & don\u2019t compete for his heart'},
    {ar:'سلّمتُه أدواتِ التربيةِ ليربّيَ جيلَه القادم',en:'I handed him the tools of tarbiyah to raise the next generation'},
  ],
  followup:[
    {period:{ar:'دائمًا',en:'Always'}, item:{ar:'هل دعوتُ له اليوم؟ هل كان حضوري دعمًا لا تدخّلًا؟',en:'Did I pray for him today? Was my presence support, not interference?'}},
    {period:{ar:'أسبوعيًّا',en:'Weekly'}, item:{ar:'هل وصلتُه بمودّة؟ هل احترمتُ استقلالَه وقراراته؟',en:'Did I connect with affection? Did I respect his independence & decisions?'}},
    {period:{ar:'عند المنعطفات',en:'At milestones'}, item:{ar:'الزواجُ، العملُ، المولودُ: هل أعنتُه وفرحتُ معه بلا فرضٍ ولا تدخّل؟',en:'Marriage, work, a newborn: did I help & rejoice with him without imposing or interfering?'}},
  ],
  practice:{
    track:{ar:'دورةُ الحياةِ تكتمل — يصير هو المربّي',en:'The cycle completes — he becomes the educator'},
    items:[
      {ar:'سلّمه هذا الدليلَ وكتبَ «ركن الأهل» ليربّيَ أبناءَه؛ فأنت تُخرّج مربّيًا لا تُنهي مهمّة.',en:'Hand him this guide & the Parents\u2019-Corner books to raise his own children; you are graduating an educator, not ending a task.'},
      {ar:'ابقَ مرجعَه: شاركه ما ينفعه عند الطلب، وادعُ له في سجودك، واجعل بيتَك قاعدةً آمنةً يعود إليها.',en:'Remain his reference: share what benefits him when asked, pray for him in your sujood, & keep your home a secure base he returns to.'},
    ]},
});
