/* stage-3.js — المرحلة الثالثة · 6–9 · التعليم والتأديب */
window.TARBIYAH.stages.push({
  id:'s3', age:'6–9', ic:'📿', c:'#2A6FDB',
  nm:{ar:'التعليمُ والتأديب', en:'Teaching & Discipline'},
  sub:{ar:'الطفولةُ الوسطى — بدءُ المسؤولية', en:'Middle childhood — responsibility begins'},
  intro:{ar:'تبدأ هنا مرحلةُ «أدِّبْه سبعًا». الطفلُ صار قادرًا على الفهمِ والتعلّمِ المنظّمِ وتحمّلِ مسؤوليّاتٍ صغيرة. الأمرُ النبويُّ بالصلاةِ في السابعةِ يفتح بابَ التعويدِ بالحبِّ لا القهر. هذه سنواتُ بناءِ العاداتِ: صلاةٌ، ووِردُ قرآن، وأدبٌ، ومسؤوليّة — كلُّها تُغرَس بالتشجيعِ والقدوةِ والصبر، فما يُبنى الآن من عاداتٍ يصير طبعًا في الكبر.',
    en:'Here begins the stage of \u201cdiscipline for seven.\u201d The child can now understand, learn in a structured way, and carry small responsibilities. The prophetic command to pray at seven opens the door of habituation through love, not coercion. These are the habit-building years: prayer, a Qur\u2019an portion, manners, responsibility \u2014 all planted through encouragement, example & patience. What is built now as habit becomes nature later.'},
  glance:[
    {ic:'⏳', k:{ar:'جرعةُ الوقت',en:'Time dose'}, v:{ar:'٦٠–٩٠ دقيقةً يوميًّا تعليمًا ولعبًا',en:'60\u201390 min daily teaching & play'}},
    {ic:'🎯', k:{ar:'المهمّةُ الكبرى',en:'Core task'}, v:{ar:'تعويدُ الصلاةِ وبناءُ العادة',en:'Habituate prayer & build habits'}},
    {ic:'🚫', k:{ar:'الخطُّ الأحمر',en:'Red line'}, v:{ar:'لا قهرَ على العبادةِ ولا مقارنة',en:'No coercion in worship, no comparison'}},
    {ic:'🗝️', k:{ar:'الكلمةُ المفتاح',en:'Keyword'}, v:{ar:'الإتقانُ والتشجيع',en:'Mastery & encouragement'}},
  ],
  scholar:{ar:'الأمرُ النبويُّ صريحٌ في فتحِ هذه المرحلة: «مُروا أولادَكم بالصلاةِ وهم أبناءُ سبعِ سنين». وهو أمرُ تعويدٍ وتعليمٍ لا أمرُ تكليفٍ ومحاسبة، فالطفلُ لم يبلُغ بعد. والمقصودُ أن يتعلّمَ الطهارةَ والصلاةَ ويألفَها بالحبّ، حتى إذا بلغ كانت عادةً راسخةً لا فريضةً ثقيلة.\n\nقال العلماءُ: يُبدأ في هذه السنّ بحفظِ قصارِ السورِ، وتعليمِ فرائضِ الوضوءِ والصلاة، والتمييزِ بين الحلالِ والحرامِ في الطعامِ واللباسِ والكلام، وغرسِ الصدقِ والأمانةِ واحترامِ الكبير. قال الغزاليُّ في «الإحياء»: «الصبيُّ أمانةٌ عند والديه، وقلبُه الطاهرُ جوهرةٌ نفيسةٌ قابلةٌ لكلِّ نقش، فإن عُوِّد الخيرَ نشأ عليه».\n\nوالتأديبُ في هذه المرحلةِ يكون بالقدوةِ أوّلًا، ثمّ بالتشجيعِ والثوابِ، ثمّ بالعتابِ اللطيف، والعقابُ آخرُ الدواءِ وأخفُّه؛ فالنبيُّ ﷺ ما ضرب خادمًا ولا امرأةً ولا شيئًا قطّ بيده. والثوابُ المعنويُّ (المدحُ والثقة) أبلغُ أثرًا من الماديّ.',
    en:'The prophetic command opens this stage explicitly: \u201cCommand your children to pray when they are seven.\u201d It is a command of habituation & teaching, not of obligation & accounting, for the child has not yet reached puberty. The aim is that he learn purity & prayer and grow fond of them through love, so that at puberty it is a firm habit, not a heavy duty.\n\nScholars said: at this age begin with memorizing short surahs, teaching the obligations of wudu & prayer, distinguishing halal from haram in food, dress & speech, and planting truthfulness, trustworthiness & respect for elders. Al-Ghazali said in al-Ihya\u2019: \u201cThe child is a trust with his parents; his pure heart is a precious jewel receptive to every engraving \u2014 if accustomed to good, he grows upon it.\u201d\n\nDiscipline at this stage is first by example, then by encouragement & reward, then by gentle reproach; punishment is the last and lightest remedy \u2014 the Prophet ﷺ never struck a servant, a woman, or anything with his hand. Moral reward (praise & trust) is mightier than material reward.'},
  psych:{ar:'يصف إريكسون هذه السنواتِ بـ«الكفاءة (الاجتهاد) مقابل الدونيّة» (٦–١٢): الطفلُ يدخل المدرسةَ، ويقيس نفسَه بأقرانه، ويتوق إلى أن يُتقنَ ويُنجزَ ويُمدَح. كلُّ مهارةٍ يُتقنها (قراءة، حفظ، رياضة، مسؤوليّة منزليّة) تبني تقديرَ ذاتِه؛ وكلُّ تحقيرٍ أو مقارنةٍ جارحةٍ تزرع «عقدةَ النقص».\n\nوفي نظريّة بياجيه، انتقل تفكيرُه إلى «العملياتِ المحسوسة»: صار يفهم القواعدَ والمنطقَ الملموسَ والتسلسلَ، لكنّه ما زال يحتاج الأمثلةَ المحسوسةَ لا المجرّدات. لذلك يصلح هنا التعليمُ المنظّمُ، وربطُ السببِ بالنتيجة، وقواعدُ البيتِ الواضحة.\n\nيؤكّد علماءُ السلوكِ أنّ العادةَ تُبنى بالتكرارِ والثباتِ والتعزيزِ الإيجابيّ (نقطة، نجمة، مدح)، لا بالعقاب. والطفلُ في هذه السنّ يميل لإرضاءِ مَن يحبّ ويثق به؛ فعلاقتُك الدافئةُ هي محرّكُ طاعتِه، لا خوفُه منك.',
    en:'Erikson describes these years as \u201cindustry (competence) vs inferiority\u201d (6\u201312): the child enters school, measures himself against peers, and longs to master, achieve & be praised. Every skill he masters (reading, memorizing, sport, a chore) builds his self-esteem; every belittling or wounding comparison plants an \u201cinferiority complex.\u201d\n\nIn Piaget\u2019s theory his thinking has moved to \u201cconcrete operations\u201d: he now grasps rules, tangible logic & sequence, but still needs concrete examples, not abstractions. So structured teaching, cause-and-effect, and clear house rules all fit here.\n\nBehavioural science confirms that habit is built by repetition, consistency & positive reinforcement (a point, a star, praise), not by punishment. At this age the child wants to please those he loves and trusts; your warm relationship is the engine of his obedience, not his fear of you.'},
  specialists:[
    {q:{ar:'«علِّق العقابَ بالخطأ لا بالطفل؛ صحّح الفعلَ ولا تجرح الذات».',en:'\u201cTie correction to the act, not the child; fix the deed without wounding the self.\u201d'}, by:{ar:'أصولُ التأديبِ الإيجابيّ',en:'Positive-discipline principles'}},
    {q:{ar:'«حاجةُ هذا السنِّ أن يُنجزَ ويُمدَح؛ امنحه مسؤوليّةً صغيرةً ينجح فيها كلَّ يوم».',en:'\u201cThis age needs to achieve & be praised; give a small daily responsibility he can succeed at.\u201d'}, by:{ar:'إريكسون · علم النفس',en:'Erikson · psychology'}},
    {q:{ar:'«المقارنةُ سُمٌّ بطيء؛ قارن الطفلَ بنفسِه بالأمسِ لا بأخيه ولا بجاره».',en:'\u201cComparison is a slow poison; compare the child to his own yesterday, not to a sibling or neighbour.\u201d'}, by:{ar:'من إرشادِ الأسرة',en:'Family counselling'}},
  ],
  evidences:[
    {type:'hadith', text:{ar:'«مُروا أولادَكم بالصلاةِ وهم أبناءُ سبعِ سنين».',en:'\u201cCommand your children to pray when they are seven.\u201d'}, ref:{ar:'أبو داود',en:'Abu Dawud'}, note:{ar:'أمرُ تعويدٍ وتحبيبٍ لا تكليفٍ ومحاسبة.',en:'A command of habit & endearment, not yet obligation.'}},
    {type:'hadith', text:{ar:'«كلُّكم راعٍ وكلُّكم مسؤولٌ عن رعيّته».',en:'\u201cEach of you is a shepherd, and each is responsible for his flock.\u201d'}, ref:{ar:'متفق عليه',en:'Bukhari & Muslim'}, note:{ar:'تعليمُ الطفلِ المسؤوليّةَ من تعليمِ الراعي رعيّتَه.',en:'Teaching the child responsibility flows from this trust.'}},
    {type:'athar', text:{ar:'قال عمرُ رضي الله عنه: «علّموا أولادكم السباحةَ والرمايةَ وركوبَ الخيل».',en:'\u2018Umar (RA) said: \u201cTeach your children swimming, archery & horsemanship.\u201d'}, ref:{ar:'أثرٌ مشهور',en:'A well-known report'}, note:{ar:'تعليمُ المهاراتِ البدنيّةِ والنافعةِ من التربية.',en:'Teaching useful physical skills is part of tarbiyah.'}},
  ],
  rewards:[
    {ic:'🕌', t:{ar:'صلاةٌ تُكتَب لك في ميزانه',en:'A prayer that weighs in your scale'}, d:{ar:'كلُّ صلاةٍ يصلّيها بعد أن علّمتَه إيّاها صدقةٌ جاريةٌ في صحيفتك.',en:'Every prayer he prays after you taught him is ongoing charity in your record.'}},
    {ic:'📖', t:{ar:'تاجُ الوقارِ لمن علّمه القرآن',en:'The crown of honour for teaching Qur\u2019an'}, d:{ar:'«مَن قرأ القرآنَ وعمل به أُلبِس والداه تاجًا يومَ القيامة».',en:'\u201cWhoever recites & acts by the Qur\u2019an, his parents are crowned on Judgment Day.\u201d'}},
    {ic:'💪', t:{ar:'طفلٌ كفؤٌ يثق بنفسه',en:'A capable, self-confident child'}, d:{ar:'الإتقانُ والمسؤوليّةُ يبنيان ثقةً تحميه من الانكسارِ والتبعيّة.',en:'Mastery & responsibility build a confidence that shields him from collapse & dependency.'}},
  ],
  needs:[
    {ar:'تعليمٌ منظّم: قرآنٌ وطهارةٌ وفقهُ الصلاة',en:'Structured teaching: Qur\u2019an, purity & prayer-fiqh'},
    {ar:'تدريبُ الصلاةِ بالحبِّ والتعويدِ والقدوة',en:'Prayer training by love, habit & example'},
    {ar:'مسؤوليّاتٌ صغيرةٌ تناسب سنَّه في البيت',en:'Small age-fit responsibilities at home'},
    {ar:'التشجيعُ والثناءُ والثقةُ على كلِّ إنجاز',en:'Encouragement, praise & trust for each achievement'},
    {ar:'أصدقاءُ صالحون ولعبٌ بدنيٌّ كافٍ',en:'Good friends & enough physical play'},
    {ar:'قواعدُ بيتٍ واضحةٌ وثابتةٌ وعادلة',en:'Clear, consistent, fair house rules'},
  ],
  risks:[
    {ar:'القسوةُ التي تُنفّر من العبادةِ وتقتل الثقة',en:'Harshness that repels worship & kills confidence'},
    {ar:'المقارنةُ بالإخوةِ أو الأقرانِ والتحقير',en:'Comparison with siblings/peers & belittling'},
    {ar:'إهمالُ تدريبِ الصلاةِ في وقتِها',en:'Neglecting timely prayer training'},
    {ar:'رفقاءُ السوءِ وبدايةُ التأثّرِ بالخارج',en:'Bad company & early outside influence'},
    {ar:'التحميلُ فوق الطاقةِ وقتلُ اللعبِ والطفولة',en:'Overloading him & killing play & childhood'},
    {ar:'الشاشاتُ والألعابُ التي تسرق وقتَ التعلّم',en:'Screens & games that steal learning time'},
  ],
  values:[
    {ar:'المحافظةُ على الصلاةِ وحبُّها',en:'Keeping & loving the prayer'},
    {ar:'المسؤوليّةُ والاعتمادُ على النفس',en:'Responsibility & self-reliance'},
    {ar:'الصدقُ والأمانةُ واحترامُ الكبير',en:'Truth, trustworthiness & respect for elders'},
    {ar:'حبُّ العلمِ والإتقانِ والنظام',en:'Love of knowledge, mastery & order'},
  ],
  dose:{ar:'٦٠–٩٠ دقيقةً يوميًّا موزّعةً: نحو ٢٠ دقيقةً قرآنًا وحفظًا، ١٥–٢٠ متابعةَ صلاةٍ ووضوء، والبقيّةُ لعبٌ ومسؤوليّةٌ وحوار. الأب: نصفُ ساعةٍ يوميًّا للصلاةِ معه والمتابعةِ والمدح، ووقتٌ أسبوعيٌّ مميّز (رياضة، رحلة) يجعلُك صديقَه قبل المراهقة.',
    en:'60\u201390 min daily, split: ~20 min Qur\u2019an & memorizing, 15\u201320 following prayer & wudu, the rest play, responsibility & talk. The father: half an hour daily to pray with him, follow up & praise, plus a special weekly time (sport, an outing) that makes you his friend before adolescence.'},
  daily:[
    {t:{ar:'الفجر/الصباح',en:'Dawn/Morning'}, dur:{ar:'١٠ د',en:'10 min'}, act:{ar:'إيقاظٌ لطيفٌ للصلاة، أذكارُ الصباح، كلمةُ تحفيز',en:'A gentle wake for prayer, morning adhkar, a motivating word'}, who:{ar:'الأب/الأم',en:'Father/Mother'}},
    {t:{ar:'وِردُ القرآن',en:'Qur\u2019an portion'}, dur:{ar:'٢٠ د',en:'20 min'}, act:{ar:'حفظٌ ومراجعةٌ من خطّةِ الحفظِ، تشجيعٌ ونجمة',en:'Memorize & review from the plan, encouragement & a star'}, who:{ar:'الأم',en:'Mother'}},
    {t:{ar:'الصلواتُ بالمتابعة',en:'Prayers, followed up'}, dur:{ar:'موزّع',en:'spread'}, act:{ar:'الصلاةُ معه، تصحيحُ الوضوءِ والحركاتِ برفقٍ ومدح',en:'Pray with him, gently correct wudu & motions, praise'}, who:{ar:'الأب/الأم',en:'Father/Mother'}},
    {t:{ar:'المسؤوليّة',en:'Responsibility'}, dur:{ar:'١٠ د',en:'10 min'}, act:{ar:'مهمّةٌ يوميّةٌ (ترتيبُ سريره، سقيُ نبتة) وثناءٌ عليها',en:'A daily task (make his bed, water a plant) with praise'}, who:{ar:'الأم/الأب',en:'Mother/Father'}},
    {t:{ar:'وقتُ الأب/القصّة',en:'Father-time/story'}, dur:{ar:'٣٠ د',en:'30 min'}, act:{ar:'لعبٌ أو رياضةٌ أو قصّةُ بطلٍ من «حصن الأبطال» وحوار',en:'Play, sport, or a hero-story from Heroes\u2019 Fortress & a chat'}, who:{ar:'الأب',en:'Father'}},
  ],
  weekly:[
    {d:{ar:'يوميًّا',en:'Daily'}, act:{ar:'وِردُ قرآنٍ + متابعةُ صلاةٍ + مسؤوليّةٌ صغيرة + قصّةٌ هادفة',en:'Qur\u2019an portion + prayer follow-up + a small chore + a purposeful story'}},
    {d:{ar:'٣ مرّات/أسبوع',en:'3×/week'}, act:{ar:'نشاطٌ بدنيّ (سباحة، كرة، دراجة) — جسمٌ قويٌّ وثقةٌ بالنفس',en:'Physical activity (swim, ball, cycling) \u2014 a strong body & confidence'}},
    {d:{ar:'الجمعة',en:'Friday'}, act:{ar:'اصطحابُه للمسجدِ إن أمكن، وقتٌ أسريٌّ مميّز، مراجعةُ نجومِ الأسبوع',en:'Take him to the masjid if possible, special family time, review the week\u2019s stars'}},
  ],
  fatherFocus:{ar:'هذه آخرُ مرحلةٍ قبل أن يتّجه قلبُ ابنك للأقرانِ والخارج؛ فاغتنمها لتكون صديقَه الأوّل. خُذه إلى المسجدِ ليرتبط بالصلاةِ والرجالِ الصالحين، وعلّمه السباحةَ والرمايةَ كما أوصى عمر، وأشركه في أعمالٍ رجوليّةٍ صغيرةٍ تشعره بالكفاءة. صلاتُك به وثناؤك عليه هما أقوى محرّكٍ لطاعته؛ فالطفلُ يصلّي حبًّا فيك قبل أن يصلّي خوفًا من ربّه، ثمّ ينتقل الحبُّ إلى ربّه.',
    en:'This is the last stage before your child\u2019s heart turns toward peers and the outside; seize it to be his first friend. Take him to the masjid to bond with prayer & righteous men, teach him swimming & archery as \u2018Umar advised, and involve him in small \u201cgrown-up\u201d tasks that make him feel competent. Praying with him and praising him are the strongest engines of his obedience; a child prays out of love for you before love for his Lord \u2014 then the love transfers to his Lord.'},
  activities:[
    {ic:'⭐', t:{ar:'جدولُ نجومِ الصلاة',en:'Prayer star chart'}, how:{ar:'لوحةٌ أسبوعيّةٌ بخمسِ صلوات؛ نجمةٌ لكلِّ صلاةٍ في وقتها، وجائزةٌ معنويّةٌ آخرَ الأسبوع.',en:'A weekly five-prayer board; a star for each on-time prayer, a moral reward at week\u2019s end.'}, why:{ar:'يحوّل الصلاةَ إلى عادةٍ محبوبةٍ بالتعزيز.',en:'Turns prayer into a loved habit via reinforcement.'}},
    {ic:'🏊', t:{ar:'سُنّةُ عمر',en:'\u2018Umar\u2019s sunnah'}, how:{ar:'علّمه السباحةَ أو الرمايةَ أو ركوبَ الدرّاجة؛ نشاطٌ بدنيٌّ أسبوعيٌّ ثابت.',en:'Teach swimming, archery or cycling; a fixed weekly physical activity.'}, why:{ar:'جسمٌ قويٌّ، ثقةٌ بالنفس، تفريغُ طاقة.',en:'A strong body, self-confidence & energy release.'}},
    {ic:'📿', t:{ar:'مشروعُ الحفظ',en:'The memorizing project'}, how:{ar:'هدفٌ واضحٌ (جزء عمّ) بخطّةٍ يوميّةٍ صغيرةٍ ولوحةِ تقدّمٍ يراها.',en:'A clear goal (Juz \u2019Amma) with a small daily plan & a visible progress board.'}, why:{ar:'يربط القرآنَ بالإنجازِ والفرح.',en:'Links the Qur\u2019an to achievement & joy.'}},
    {ic:'🛠️', t:{ar:'مهمّةُ الرجلِ الصغير',en:'The little man\u2019s task'}, how:{ar:'كلّفه عملًا حقيقيًّا (مساعدةٌ في التسوّق، إصلاحٌ بسيط) واشكره عليه.',en:'Give him a real job (help shopping, a simple fix) & thank him.'}, why:{ar:'يبني الكفاءةَ والمسؤوليّةَ وتقديرَ الذات.',en:'Builds competence, responsibility & self-worth.'}},
    {ic:'🏰', t:{ar:'قصّةُ البطلِ الأسبوعيّة',en:'The weekly hero story'}, how:{ar:'اقرأ معه سيرةَ صحابيٍّ من «حصن الأبطال» وتحدّثا: ماذا نتعلّم منه؟',en:'Read a companion\u2019s story (Heroes\u2019 Fortress) & discuss: what do we learn?'}, why:{ar:'يغرس القدوةَ ويبني الشخصيّة.',en:'Plants role models & builds character.'}},
    {ic:'🤝', t:{ar:'مجلسُ العائلة',en:'The family council'}, how:{ar:'جلسةٌ أسبوعيّةٌ قصيرةٌ يُسمَع فيها رأيُه ويُشكَر تحسّنُه وتُوضَع أهدافٌ صغيرة.',en:'A short weekly sit-down where his view is heard, his progress praised, small goals set.'}, why:{ar:'يشعره بالقيمةِ والانتماءِ والمسؤوليّة.',en:'Gives him worth, belonging & responsibility.'}},
  ],
  examples:[
    {title:{ar:'يتهرّب من الصلاة',en:'He dodges the prayer'}, scene:{ar:'تناديه للصلاةِ فيتباطأ أو يقول «بعد قليل» ويستمرّ في اللعب.',en:'You call him to pray; he stalls or says \u201cin a bit\u201d and keeps playing.'},
      do:{ar:'صلِّ أمامه ونادِه ليقف بجوارك، اجعلها ممتعةً (يؤذّن، يؤمّكم أحيانًا)، امدح حضورَه، وذكّره بلوحةِ النجوم بهدوء.',en:'Pray before him & call him to stand beside you, make it enjoyable (he gives adhan, sometimes leads), praise his attendance, calmly point to the star chart.'},
      dont:{ar:'لا تضربه على الصلاةِ في هذه السنّ، ولا تربطها بالغضبِ والصراخ فتصير بغيضة.',en:'Don\u2019t hit him over prayer at this age, nor tie it to anger & shouting so it becomes hateful.'},
      root:{ar:'الهدفُ تحبيبُ الصلاةِ لا مجرّدُ أدائها؛ الحبُّ يُبنى بالقدوةِ والتشجيعِ لا بالقهر.',en:'The goal is to endear prayer, not merely perform it; love is built by example & encouragement, not coercion.'}},
    {title:{ar:'كذبةٌ صغيرة',en:'A small lie'}, scene:{ar:'يكسر شيئًا ثمّ ينكر أنّه الفاعل خوفًا من العقاب.',en:'He breaks something then denies it, fearing punishment.'},
      do:{ar:'اهدأ، طمئنه أنّ الصدقَ لا يُعاقَب، اشكره حين يصدُق، وعالِج الخطأ بنتيجةٍ بسيطةٍ (يساعد في الإصلاح). علّمه أنّ اللهَ يحبّ الصادقين.',en:'Stay calm, reassure him that honesty isn\u2019t punished, thank him when he tells the truth, address the act with a small consequence (help fix it). Teach that Allah loves the truthful.'},
      dont:{ar:'لا تعاقبه بشدّةٍ عند صدقه فيتعلّم أنّ الكذبَ أأمن، ولا تصِفه بـ«الكذّاب».',en:'Don\u2019t punish him harshly when he\u2019s honest (he\u2019ll learn lying is safer), and never label him \u201ca liar.\u201d'},
      root:{ar:'الكذبُ في هذه السنِّ هروبٌ من العقابِ غالبًا؛ اجعل الصدقَ آمنًا يَصدُق.',en:'Lying at this age is usually escape from punishment; make honesty safe and he\u2019ll be honest.'}},
  ],
  problems:[
    {p:{ar:'التهرّبُ من الصلاةِ والكسلُ عنها',en:'Dodging & laziness toward prayer'},
      why:{ar:'لم تترسّخ العادةُ بعد، أو رُبطت الصلاةُ بالتوبيخِ والقهرِ فصارت ثقيلة.',en:'The habit isn\u2019t yet rooted, or prayer got tied to scolding & coercion so it became heavy.'},
      islamic:{ar:'الأمرُ بالرفقِ والتدرّج؛ النبيُّ ﷺ رغّب في الصلاةِ ولم يُنفّر، وقال: «يسّروا ولا تعسّروا».',en:'Command with gentleness & gradualness; the Prophet ﷺ made prayer beloved, saying \u201cmake things easy, not hard.\u201d'},
      psych:{ar:'العادةُ تُبنى بالثباتِ والتعزيزِ الإيجابيّ؛ القدوةُ والصلاةُ الجماعيّةُ والمدحُ أقوى من العقاب.',en:'Habit is built by consistency & positive reinforcement; example, congregational prayer & praise beat punishment.'},
      steps:[{ar:'صلِّ أمامه وادعُه ليصلّي معك، لا تكتفِ بالأمر.',en:'Pray before him & invite him to join you; don\u2019t just command.'},{ar:'اجعلها ممتعة: أذانٌ، سجّادةٌ خاصّة، إمامةٌ أحيانًا.',en:'Make it fun: adhan, his own prayer-mat, leading sometimes.'},{ar:'لوحةُ نجومٍ وتشجيعٌ ثابتٌ ومدحٌ أمام الأسرة.',en:'A star chart, steady encouragement & praise before the family.'},{ar:'ثباتُ المواعيدِ، وصلاةُ الأسرةِ جماعةً ما أمكن.',en:'Fixed times & family congregation whenever possible.'},{ar:'تجنّب الضربَ والقهر؛ التحبيبُ هو الطريق.',en:'Avoid hitting & coercion; endearment is the path.'}]},
    {p:{ar:'العنادُ ورفضُ الأوامرِ والمسؤوليّة',en:'Defiance & refusing tasks/responsibility'},
      why:{ar:'سعيٌ للاستقلالِ والكفاءة، أو ردُّ فعلٍ على أوامرَ كثيرةٍ متناقضةٍ أو قاسية.',en:'A drive for autonomy & competence, or a reaction to many, contradictory or harsh commands.'},
      islamic:{ar:'العدلُ بين الأبناء، والمشاورةُ والرفق؛ «وشاورهم في الأمر». واللينُ يفتح القلوبَ المغلقة.',en:'Justice between children, consultation & gentleness; \u201cconsult them in the matter.\u201d Gentleness opens closed hearts.'},
      psych:{ar:'امنحه خياراتٍ محدودةً (هذا أو ذاك) تشبع حاجتَه للاستقلالِ ضمن حدودك؛ وقلّل الأوامرَ واجعلها واضحة.',en:'Give limited choices (this or that) that satisfy his autonomy within your limits; reduce commands & make them clear.'},
      steps:[{ar:'قلّل الأوامرَ، واجعل المهمّ منها واضحًا وثابتًا.',en:'Reduce commands; keep the important ones clear & consistent.'},{ar:'أعطه خيارَين بدل الأمرِ المباشر.',en:'Offer two choices instead of a direct order.'},{ar:'اربط النتيجةَ بالفعلِ بهدوءٍ (لا لعبَ قبل الواجب).',en:'Tie consequence to act calmly (no play before the duty).'},{ar:'امدح التعاونَ فورًا وكافئه معنويًّا.',en:'Praise cooperation immediately & reward it morally.'},{ar:'تأكّد من عدلِك بينه وبين إخوته.',en:'Ensure your justice between him & his siblings.'}]},
  ],
  checklist:[
    {ar:'بدأتُ أمرَه بالصلاةِ تعويدًا وتحبيبًا منذ السابعة',en:'I began commanding prayer as habit & endearment from seven'},
    {ar:'له وِردٌ يوميٌّ من القرآنِ يحفظ ويراجع',en:'He has a daily Qur\u2019an portion he memorizes & reviews'},
    {ar:'علّمتُه الطهارةَ وفقهَ الصلاةِ المبسّط',en:'I taught him purity & simple prayer-fiqh'},
    {ar:'أُكلّفه مسؤوليّةً يوميّةً وأُثني على إنجازه',en:'I give him a daily responsibility & praise his effort'},
    {ar:'لا أُقارنه بإخوته ولا أُحقّر محاولاتِه',en:'I never compare him to siblings nor belittle his attempts'},
    {ar:'أتابعُ أصدقاءَه وأوجّهه لرفقةٍ صالحة',en:'I monitor his friends & guide him to good company'},
    {ar:'الأبُ يصلّي معه ويخصّص له وقتًا يوميًّا',en:'The father prays with him & gives him daily time'},
    {ar:'الثوابُ والتشجيعُ عندي أكثرُ من العقاب',en:'I use reward & encouragement far more than punishment'},
  ],
  followup:[
    {period:{ar:'يوميًّا',en:'Daily'}, item:{ar:'كم صلاةً صلّى في وقتها؟ هل أدّى وِردَه ومسؤوليّتَه؟ هل مدحتُه؟',en:'How many prayers on time? Did he do his portion & chore? Did I praise him?'}},
    {period:{ar:'أسبوعيًّا',en:'Weekly'}, item:{ar:'مراجعةُ لوحةِ النجوم، تقدّمُ الحفظ، حالُ أصدقائه، نشاطُه البدنيّ.',en:'Review the star chart, memorizing progress, his friends, his physical activity.'}},
    {period:{ar:'كلَّ فصلٍ دراسيّ',en:'Each school term'}, item:{ar:'تقييمُ تحصيله، ثقتِه بنفسه، علاقتِه بالصلاةِ والقرآنِ، وأيِّ مهارةٍ أتقنها.',en:'Assess his learning, self-confidence, relationship with prayer & Qur\u2019an, & a skill mastered.'}},
  ],
  practice:{
    track:{ar:'مسارُ «البُناة» (٧–٩) في كتاب خارطة طريق المربّي',en:'The \u201cYoung Builders\u201d track (7\u20139) in the Parent Roadmap book'},
    items:[
      {ar:'ابدأ خطّةَ الحفظِ من «كتاب خطة حفظ القرآن» (جزء عمّ)، واجعل الصلاةَ عادةً عبر رحلةِ الصلاةِ في «واحة العبادة».',en:'Begin the plan in the Qur\u2019an Memorization Plan book (Juz \u2019Amma), and make prayer a habit via the Prayer journey in Worship Oasis.'},
      {ar:'استخدم «نقاطَ السلوك» وجداولَ النجومِ والشهاداتِ في «ركن الأهل» لتثبيتِ العاداتِ والاحتفاءِ بالإنجاز، واقرأ سيرَ الأبطالِ من «حصن الأبطال».',en:'Use behaviour-points, star charts & certificates in the Parents\u2019 Corner to lock in habits & celebrate achievement, and read the hero-stories in Heroes\u2019 Fortress.'},
    ]},
});
