/* stage-4.js — المرحلة الرابعة · 9–12 · الحياء والاستعداد */
window.TARBIYAH.stages.push({
  id:'s4', age:'9–12', ic:'🧭', c:'#8E44AD',
  nm:{ar:'الحياءُ والاستعداد', en:'Modesty & Readiness'},
  sub:{ar:'ما قبل المراهقة — التهيئةُ للبلوغ', en:'Pre-adolescence — preparing for puberty'},
  intro:{ar:'هذه مرحلةٌ مفصليّةٌ يغفل عنها كثيرٌ من الآباء. الطفلُ على أعتابِ البلوغ، يتغيّر جسدُه وعقلُه ومشاعرُه، ويزداد تأثُّرُه بالأقرانِ والأجهزة. مهمّتُك الكبرى أن تُهيّئه للبلوغِ بهدوءٍ ووضوحٍ قبل أن يفجأَه، وأن تغرس الحياءَ والسترَ وثباتَ الصلاةِ عن قناعة، وأن تبني جسرَ الثقةِ والحوارِ الذي ستعبر عليه معه طوالَ المراهقة. مَن أحسن في هذه السنواتِ الثلاثِ جنى ثمرتَها أمانًا في العشرِ التالية.',
    en:'This is a pivotal stage many parents overlook. The child is on the threshold of puberty: his body, mind & emotions are changing, and peer & device influence grows. Your great task is to prepare him for puberty \u2014 calmly & clearly, before it surprises him \u2014 to plant modesty, covering & steadfast prayer by conviction, and to build the bridge of trust & dialogue you will cross with him throughout adolescence. Whoever does well in these three years reaps its fruit as safety in the next ten.'},
  glance:[
    {ic:'⏳', k:{ar:'جرعةُ الوقت',en:'Time dose'}, v:{ar:'٦٠–٩٠ دقيقةً حوارًا ونشاطًا يوميًّا',en:'60\u201390 min daily talk & activity'}},
    {ic:'🎯', k:{ar:'المهمّةُ الكبرى',en:'Core task'}, v:{ar:'تهيئةُ البلوغ + جسرُ الثقة',en:'Puberty prep + the trust bridge'}},
    {ic:'🚫', k:{ar:'الخطُّ الأحمر',en:'Red line'}, v:{ar:'لا فراغَ معرفيٍّ ولا جهازَ بلا رقابة',en:'No knowledge gap, no unmonitored device'}},
    {ic:'🗝️', k:{ar:'الكلمةُ المفتاح',en:'Keyword'}, v:{ar:'الحياءُ والحوار',en:'Modesty & dialogue'}},
  ],
  scholar:{ar:'تشتدّ العنايةُ بالصلاةِ في هذه السنّ؛ تمامُ الحديث: «مُروهم بالصلاةِ وهم أبناءُ سبع، واضربوهم عليها وهم أبناءُ عشر، وفرّقوا بينهم في المضاجع». والضربُ هنا متأخّرٌ مشروطٌ غيرُ مبرّحٍ بعد استنفادِ التحبيبِ والتعويد، وكثيرٌ من المربّين لا يحتاجه إن أحسن المرحلةَ السابقة. والتفريقُ في المضاجعِ تعليمٌ للحياءِ وحدودِ الجسد.\n\nهذه مرحلةُ التهيئةِ للبلوغ: من فقهِ التربيةِ أن يُعلَّم الولدُ أحكامَ الطهارةِ والغُسلِ والاحتلام، وتُعلَّم البنتُ أحكامَ الحيضِ، قبل وقوعِ ذلك بسكينةٍ ووضوحٍ لا خجلٍ يدفعه للجهلِ أو للسؤالِ الخفيّ. كان السلفُ يُعلّمون أبناءهم أحكامَ البلوغِ قبل بلوغِهم. قال ابنُ عبّاسٍ: «تعلّمتُ عامّةَ ما تعلّمتُ من فقهٍ قبل أن أحتلم».\n\nويُغرَس في هذه السنِّ الحياءُ — وهو «شعبةٌ من الإيمان» — والسترُ والعفّةُ، ويُربَط الولدُ بالمسجدِ والرفقةِ الصالحة، ويُدرَّب على الاستئذانِ وغضِّ البصرِ وآدابِ التعاملِ مع الجنسِ الآخر، استعدادًا لمرحلةٍ تشتدّ فيها الفتن.',
    en:'Care for prayer intensifies now; the full hadith: \u201cCommand them to pray at seven, and at ten, and separate their beds.\u201d The smacking here is late, conditional, non-injurious, and only after endearment & habituation are exhausted \u2014 many parents never need it if the earlier stage went well. Separating beds teaches modesty & bodily boundaries.\n\nThis is the puberty-preparation stage: it is part of the fiqh of upbringing that a boy be taught the rulings of purity, ghusl & wet-dreams, and a girl the rulings of menstruation, before they occur \u2014 calmly & clearly, not with a shyness that pushes him to ignorance or to secret asking. The early Muslims taught their children the rulings of puberty before it arrived. Ibn \u2018Abbas said: \u201cI learned most of my fiqh before I reached puberty.\u201d\n\nAt this age modesty is planted \u2014 \u201ca branch of faith\u201d \u2014 along with covering & chastity; the child is bonded to the masjid & righteous company, and trained in seeking permission, lowering the gaze & the manners of dealing with the other gender, in readiness for a stage where temptations intensify.'},
  psych:{ar:'ما قبلَ المراهقة: تتسارع الاستقلاليّةُ، ويبدأ التفكيرُ المجرّد، ويتعاظم تأثيرُ الأقرانِ حتى يصير رأيُ الأصدقاءِ أثقلَ من رأيِ الأهلِ أحيانًا. يحتاج الطفلُ حدودًا واضحةً مع احترام، ومساحةَ خصوصيّةٍ معقولة، ومسؤوليّاتٍ تشعره بالكفاءة.\n\nالفجوةُ المعرفيّةُ هنا خطيرةٌ جدًّا: إن لم يجد المعلومةَ عن جسدِه وتغيّراتِه منك، أخذها مشوّهةً من الإنترنتِ والأقران، وغالبًا قبل أن تظنّ. الدراساتُ تُظهِر أنّ متوسّطَ أوّلِ تعرّضٍ للمحتوى غيرِ اللائقِ صار مبكّرًا جدًّا؛ فالرقابةُ على الأجهزةِ والحوارُ المفتوحُ ضرورةٌ لا رفاهية.\n\nوهذه آخرُ نافذةٍ يكون فيها قلبُ ابنك مفتوحًا لك بالكامل قبل أن «يُقفله» البلوغ. كلُّ رصيدِ ثقةٍ تبنيه الآن (إصغاءٌ بلا حكم، حوارٌ بلا محاضرة، احترامٌ لمشاعره) هو الحصنُ الذي سيحميه من الانحرافِ في المراهقة. الثقةُ المبنيّةُ الآن لا تُشترى لاحقًا.',
    en:'Pre-adolescence: independence accelerates, abstract thinking begins, and peer influence grows until friends\u2019 opinions sometimes outweigh parents\u2019. The child needs clear boundaries with respect, reasonable privacy, and responsibilities that make him feel competent.\n\nThe knowledge gap here is very dangerous: if he doesn\u2019t get information about his body & its changes from you, he\u2019ll take a distorted version from the internet & peers \u2014 usually earlier than you think. Studies show the average age of first exposure to inappropriate content has become very young; so device monitoring & open dialogue are a necessity, not a luxury.\n\nThis is the last window in which your child\u2019s heart is fully open to you before puberty \u201ccloses\u201d it. Every credit of trust you build now (listening without judging, talking without lecturing, respecting his feelings) is the fortress that will protect him from deviation in adolescence. Trust built now cannot be bought later.'},
  specialists:[
    {q:{ar:'«مَن لم يُربِّ ابنَه على الحياءِ والمعرفةِ قبل البلوغ، ربّاه الإنترنتُ والأقران».',en:'\u201cWhoever doesn\u2019t teach modesty & knowledge before puberty \u2014 the internet & peers will teach it.\u201d'}, by:{ar:'فقهُ التربيةِ المعاصر',en:'Contemporary tarbiyah'}},
    {q:{ar:'«افتح بابَ الحوارِ قبل أن يُقفله البلوغ؛ الثقةُ المبنيّةُ الآن هي حصنُ المراهقة».',en:'\u201cOpen the door of dialogue before puberty closes it; trust built now is the fortress of adolescence.\u201d'}, by:{ar:'مختصّو نموِّ المراهقين',en:'Adolescence specialists'}},
    {q:{ar:'«كُن أنت مصدرَ المعلومةِ الأوّل؛ الصمتُ خجلًا يترك ابنَك فريسةً لمصادرَ ملوّثة».',en:'\u201cBe his first source of information; bashful silence leaves your child prey to polluted sources.\u201d'}, by:{ar:'من الإرشادِ التربويّ',en:'Educational counselling'}},
  ],
  evidences:[
    {type:'hadith', text:{ar:'«...واضربوهم عليها وهم أبناءُ عشرٍ، وفرّقوا بينهم في المضاجع».',en:'\u201c...and at ten, and separate their beds.\u201d'}, ref:{ar:'أبو داود',en:'Abu Dawud'}, note:{ar:'تأديبٌ متدرّجٌ وتعليمٌ للحياءِ وحدودِ الجسد.',en:'Gradual discipline & teaching modesty & bodily limits.'}},
    {type:'hadith', text:{ar:'«الحياءُ شعبةٌ من الإيمان».',en:'\u201cModesty is a branch of faith.\u201d'}, ref:{ar:'متفق عليه',en:'Bukhari & Muslim'}, note:{ar:'الحياءُ ركيزةُ هذه المرحلة.',en:'Modesty is the pillar of this stage.'}},
    {type:'athar', text:{ar:'قال ابنُ عبّاسٍ: «تعلّمتُ عامّةَ ما تعلّمتُ من الفقهِ قبل أن أحتلم».',en:'Ibn \u2018Abbas said: \u201cI learned most of my fiqh before I reached puberty.\u201d'}, ref:{ar:'أثرٌ صحيح',en:'An authentic report'}, note:{ar:'التعليمُ يسبق البلوغَ لا يتأخّر عنه.',en:'Teaching precedes puberty, not lags behind it.'}},
  ],
  rewards:[
    {ic:'🛡️', t:{ar:'ولدٌ محصّنٌ قبل العاصفة',en:'A fortified child before the storm'}, d:{ar:'التهيئةُ والحياءُ والثقةُ تحمي ابنك من فتنِ المراهقةِ التي تُغرِق غيرَه.',en:'Preparation, modesty & trust shield your child from the adolescent storms that drown others.'}},
    {ic:'🤝', t:{ar:'جسرُ ثقةٍ يدوم سنوات',en:'A trust bridge lasting years'}, d:{ar:'حوارُك المفتوحُ الآن يجعله يأتيك بأسرارِه غدًا بدل أن يخفيَها عنك.',en:'Your open dialogue now makes him bring you his secrets tomorrow instead of hiding them.'}},
    {ic:'🌸', t:{ar:'حياءٌ يزيّن ويُؤجَر',en:'Modesty that beautifies & is rewarded'}, d:{ar:'«الحياءُ لا يأتي إلّا بخير»؛ وغرسُه أمانةٌ تُثاب عليها وتقي ولدَك العمر.',en:'\u201cModesty brings only good\u201d; planting it is a trust you\u2019re rewarded for, shielding your child for life.'}},
  ],
  needs:[
    {ar:'تهيئةٌ هادئةٌ وواضحةٌ للبلوغِ وتغيّراتِ الجسد',en:'Calm, clear preparation for puberty & bodily change'},
    {ar:'تعليمُ الطهارةِ والغُسلِ وأحكامِ البلوغ',en:'Teaching purity, ghusl & the rulings of buloogh'},
    {ar:'حدودٌ واضحةٌ مع احترامٍ وخصوصيّةٍ معقولة',en:'Clear boundaries with respect & reasonable privacy'},
    {ar:'حوارٌ مفتوحٌ يوميٌّ وثقةٌ متبادلة',en:'Daily open dialogue & mutual trust'},
    {ar:'مسؤوليّاتٌ أكبرُ وثقةٌ في قدراته',en:'Bigger responsibilities & trust in his abilities'},
    {ar:'رقابةٌ واعيةٌ على الأجهزةِ والرفقة',en:'Conscious monitoring of devices & company'},
  ],
  risks:[
    {ar:'الفراغُ المعرفيّ فيأخذ المعلومةَ مشوّهةً',en:'A knowledge gap filled by distorted sources'},
    {ar:'التعرّضُ للمحتوى غيرِ اللائقِ على الأجهزة',en:'Exposure to inappropriate content on devices'},
    {ar:'رفقاءُ السوءِ والسرّيّةُ والانغلاق',en:'Bad peers, secrecy & withdrawal'},
    {ar:'التشدّدُ الزائدُ فيولّد التمرّدَ المبكّر',en:'Over-control breeding early rebellion'},
    {ar:'الخجلُ الذي يمنع الحوارَ عن الجسدِ والبلوغ',en:'Shyness that blocks talk about the body & puberty'},
    {ar:'إهمالُ ثباتِ الصلاةِ عند انشغالِه بالمدرسة',en:'Letting prayer slip amid school distraction'},
  ],
  values:[
    {ar:'الحياءُ والسترُ وحدودُ الجسد',en:'Modesty, covering & bodily boundaries'},
    {ar:'المسؤوليّةُ وضبطُ النفس',en:'Responsibility & self-discipline'},
    {ar:'ثباتُ الصلاةِ عن قناعةٍ لا إلزام',en:'Steadfast prayer by conviction'},
    {ar:'الهُويّةُ الإيمانيّةُ والاعتزازُ بالدين',en:'Faith-identity & pride in the deen'},
  ],
  dose:{ar:'٦٠–٩٠ دقيقةً يوميًّا، لكنّ ثقلَها تحوّل من «التعليم» إلى «الحوار»: ٢٠ دقيقةً قرآنًا/علمًا، ونحو ٣٠ دقيقةً حوارًا وإصغاءً ونشاطًا مشتركًا. الأبُ خصوصًا للولد، والأمُّ للبنت: جلسةٌ خاصّةٌ أسبوعيّةٌ (مشيٌ، مقهًى، رياضة) يكون فيها الحديثُ صداقةً لا استجوابًا — هي التي تفتح القلبَ قبل أن يُقفله البلوغ.',
    en:'60\u201390 min daily, but its weight shifts from \u201cteaching\u201d to \u201cdialogue\u201d: 20 min Qur\u2019an/learning, ~30 min talking, listening & a shared activity. The father especially with a son, the mother with a daughter: a private weekly session (a walk, a caf\u00e9, sport) where the talk is friendship, not interrogation \u2014 this is what opens the heart before puberty closes it.'},
  daily:[
    {t:{ar:'الفجر/الصباح',en:'Dawn/Morning'}, dur:{ar:'١٠ د',en:'10 min'}, act:{ar:'صلاةُ الفجرِ معًا ما أمكن، أذكارٌ، كلمةُ ثقةٍ وتحفيز',en:'Fajr together when possible, adhkar, a word of trust & motivation'}, who:{ar:'الأب/الأم',en:'Father/Mother'}},
    {t:{ar:'القرآن/العلم',en:'Qur\u2019an/learning'}, dur:{ar:'٢٠ د',en:'20 min'}, act:{ar:'مراجعةُ الحفظِ وقراءةٌ نافعة، ربطُ الآياتِ بالحياة',en:'Review memorizing & beneficial reading, linking verses to life'}, who:{ar:'الأم/الأب',en:'Mother/Father'}},
    {t:{ar:'حوارُ القلب',en:'Heart-to-heart'}, dur:{ar:'٢٠ د',en:'20 min'}, act:{ar:'إصغاءٌ ليومِه بلا حكم، أسئلةٌ مفتوحة، مناقشةُ ما يشغله',en:'Listen to his day without judging, open questions, discuss what concerns him'}, who:{ar:'الأب/الأم',en:'Father/Mother'}},
    {t:{ar:'مسؤوليّة/نشاط',en:'Responsibility/activity'}, dur:{ar:'٢٠ د',en:'20 min'}, act:{ar:'مهمّةٌ يثق بها، أو رياضةٌ، أو مهارةٌ يتعلّمها',en:'A task he\u2019s trusted with, sport, or a skill he\u2019s learning'}, who:{ar:'الأب',en:'Father'}},
    {t:{ar:'قبل النوم',en:'Before sleep'}, dur:{ar:'١٠ د',en:'10 min'}, act:{ar:'أذكارُ النوم، مراجعةُ يومِه بإيجابيّة، دعاءٌ له وأمامه',en:'Sleep adhkar, a positive review of his day, du\u2019a for & before him'}, who:{ar:'الأب/الأم',en:'Father/Mother'}},
  ],
  weekly:[
    {d:{ar:'يوميًّا',en:'Daily'}, act:{ar:'صلاةٌ يُتابَع ثباتُها + وِردُ قرآن + حوارُ قلبٍ بلا استجواب',en:'Prayer (steadiness tracked) + Qur\u2019an portion + heart-talk, not interrogation'}},
    {d:{ar:'أسبوعيًّا',en:'Weekly'}, act:{ar:'جلسةٌ خاصّةٌ (أبٌ-ابن / أمٌّ-بنت): مشيٌ أو رياضةٌ وحديثٌ صديق',en:'A private session (father-son / mother-daughter): a walk or sport & friendly talk'}},
    {d:{ar:'عند الحاجة',en:'As needed'}, act:{ar:'حوارٌ هادئٌ مخطّطٌ عن تغيّراتِ الجسدِ والبلوغِ قبل وقوعها',en:'A calm, planned talk on bodily changes & puberty, in advance'}},
  ],
  fatherFocus:{ar:'دورُ الأبِ هنا حاسمٌ مع الولد (والأمِّ مع البنت): أنت مَن يجب أن يُجري حوارَ البلوغ، بوضوحٍ وطهارةٍ وبلا خجلٍ يدفعه لمصدرٍ ملوّث. اجعل لك معه «طقسًا رجوليًّا» أسبوعيًّا (مشيٌ، رياضةٌ، عملٌ مشترك) يفتح فيه قلبَه. أصغِ أكثرَ ممّا تتكلّم، ولا تجعل كلَّ حوارٍ محاضرةً أو استجوابًا. إن شعر أنّك صديقُه الآمن الآن، عاد إليك في عواصفِ المراهقةِ بدل أن يهرب منك.',
    en:'The father\u2019s role here is decisive with a son (the mother\u2019s with a daughter): you must be the one to have the puberty talk \u2014 clearly, purely, without a shyness that drives him to a polluted source. Build a weekly \u201cmen\u2019s ritual\u201d with him (a walk, sport, shared work) where his heart opens. Listen more than you speak, and don\u2019t make every talk a lecture or interrogation. If he feels you are his safe friend now, he\u2019ll return to you in adolescence\u2019s storms instead of fleeing you.'},
  activities:[
    {ic:'🚶', t:{ar:'مشيُ الأسرار',en:'The secrets walk'}, how:{ar:'مشيٌ أسبوعيٌّ ثابتٌ بلا هاتف؛ اسأله أسئلةً مفتوحةً وأنصِت بلا مقاطعةٍ أو حكم.',en:'A fixed weekly phone-free walk; ask open questions & listen without interrupting or judging.'}, why:{ar:'يفتح قناةَ الحوارِ قبل المراهقة.',en:'Opens the dialogue channel before adolescence.'}},
    {ic:'📓', t:{ar:'دفترُ البلوغ',en:'The puberty booklet'}, how:{ar:'هيّئ له (أو لها) معلوماتٍ صحيحةً عن تغيّراتِ الجسدِ وأحكامِ الطهارةِ بهدوءٍ ووضوحٍ قبل وقوعها.',en:'Prepare correct info on bodily changes & purity rulings, calmly & clearly, in advance.'}, why:{ar:'يسدّ الفجوةَ المعرفيّةَ ويمنع التشوّه.',en:'Closes the knowledge gap & prevents distortion.'}},
    {ic:'🕌', t:{ar:'رفيقُ المسجد',en:'Masjid companion'}, how:{ar:'خُذه لصلاةِ الجماعةِ وحلقةِ علمٍ، وعرّفه برفقةٍ صالحةٍ في سنّه.',en:'Take him to congregation & a study circle; introduce good company his age.'}, why:{ar:'يبني الهُويّةَ والرفقةَ الصالحةَ مبكّرًا.',en:'Builds identity & good company early.'}},
    {ic:'💪', t:{ar:'مشروعُ مسؤوليّة',en:'A responsibility project'}, how:{ar:'كلّفه مسؤوليّةً حقيقيّةً (إدارةُ مصروفِه، مهمّةٌ أسريّةٌ كبيرة) وثِق به.',en:'Entrust a real responsibility (managing his allowance, a bigger family task) & trust him.'}, why:{ar:'يشبع حاجةَ الاستقلالِ ويبني الكفاءة.',en:'Feeds his autonomy & builds competence.'}},
    {ic:'📱', t:{ar:'ميثاقُ الأجهزة',en:'The device charter'}, how:{ar:'اتّفقا على قواعدَ مكتوبةٍ لاستخدامِ الجهازِ (وقت، مكان، محتوى) بالحوارِ لا الفرض.',en:'Agree on written device rules (time, place, content) by dialogue, not decree.'}, why:{ar:'يحميه ويعلّمه ضبطَ النفسِ لا مجرّدَ المنع.',en:'Protects him & teaches self-control, not mere banning.'}},
    {ic:'🛡️', t:{ar:'حصنُ القيم',en:'The values fortress'}, how:{ar:'ناقشا مواقفَ واقعيّةً: ماذا تفعل لو عرض صديقٌ شيئًا خاطئًا؟ تدرّبا على الرفضِ بثقة.',en:'Discuss real scenarios: what if a friend offers something wrong? Rehearse confident refusal.'}, why:{ar:'يحصّنه ضدّ ضغطِ الأقرانِ المقبل.',en:'Fortifies him against coming peer pressure.'}},
  ],
  examples:[
    {title:{ar:'وجدتَ محتوًى غيرَ لائقٍ على جهازه',en:'You found inappropriate content on his device'}, scene:{ar:'تكتشف أنّه شاهد أو بحث عن محتوًى غيرِ لائق.',en:'You discover he viewed or searched for inappropriate content.'},
      do:{ar:'اهدأ ولا تنفعل، تحدّث معه بهدوءٍ وحياءٍ ومن غيرِ تجريم، فسّر له لماذا يضرّه، أعِد ضبطَ القواعدِ والرقابةِ معًا، وأكّد أنّ بابَك مفتوحٌ لأيِّ سؤال.',en:'Stay calm, don\u2019t explode; speak gently & modestly without criminalizing, explain why it harms him, reset rules & monitoring together, & affirm your door is open for any question.'},
      dont:{ar:'لا تفضحه أمام الأسرة، ولا تصفه بالفاسد، ولا تكتفِ بمصادرةِ الجهازِ بلا حوارٍ يفهمه.',en:'Don\u2019t expose him to the family, don\u2019t call him corrupt, don\u2019t just confiscate the device without a talk he understands.'},
      root:{ar:'الفضولُ في هذه السنِّ طبيعيّ؛ ردّةُ فعلِك تحدّد: هل يعود إليك بثقةٍ أم يختبئ ويتعمّق؟',en:'Curiosity at this age is natural; your reaction decides whether he returns to you in trust or hides & goes deeper.'}},
    {title:{ar:'صديقٌ سيّئُ التأثير',en:'A bad-influence friend'}, scene:{ar:'لاحظتَ صديقًا يجرّه لسلوكٍ سيّئ أو كلامٍ بذيء.',en:'You noticed a friend pulling him toward bad behaviour or foul talk.'},
      do:{ar:'لا تهاجم الصديقَ مباشرةً، بل وسّع دائرتَه برفقةٍ صالحة (مسجد، نادٍ)، وناقشه في صفاتِ الصديقِ الحقّ، وعزّز قيمَه ليختار بنفسه.',en:'Don\u2019t attack the friend directly; widen his circle with good company (masjid, a club), discuss the traits of a true friend, & strengthen his values so he chooses himself.'},
      dont:{ar:'لا تمنعه بقرارٍ فوقيٍّ فقط (يزيده تعلّقًا سرّيًّا)، ولا تحتقر الصديقَ أمامه.',en:'Don\u2019t just ban by decree (it deepens secret attachment), and don\u2019t belittle the friend before him.'},
      root:{ar:'في هذه السنِّ يثقل رأيُ الأقران؛ حصّنه من الداخلِ بالقيمِ بدل الاكتفاءِ بالمنعِ من الخارج.',en:'Peers\u2019 opinion weighs heavily now; fortify him from within with values rather than only banning from without.'}},
  ],
  problems:[
    {p:{ar:'الانشغالُ بالأجهزةِ والألعابِ على حسابِ الصلاةِ والواجب',en:'Devices & games crowding out prayer & duty'},
      why:{ar:'جاذبيّةُ المكافأةِ السريعة، وضعفُ ضبطِ النفسِ في هذه السنّ، وغيابُ البديلِ الممتع.',en:'The pull of quick reward, weak self-control at this age, & no fun alternative.'},
      islamic:{ar:'حفظُ الوقتِ والصلاةِ في وقتها أمانة؛ ووازن بين حقِّ بدنِه في اللعبِ وحقِّ ربِّه في الطاعة.',en:'Guarding time & timely prayer is a trust; balance his body\u2019s right to play & his Lord\u2019s right to obedience.'},
      psych:{ar:'القواعدُ المتّفقُ عليها مسبقًا والبدائلُ الجاذبةُ أنجحُ من المنعِ المفاجئ؛ وإشراكُه في وضعِ القاعدةِ يزيد التزامَه.',en:'Pre-agreed rules & attractive alternatives beat sudden bans; involving him in making the rule increases compliance.'},
      steps:[{ar:'ميثاقٌ مكتوبٌ للأجهزةِ متّفقٌ عليه (وقت، مكان، محتوى).',en:'A written, agreed device charter (time, place, content).'},{ar:'لا جهازَ قبل الصلاةِ والواجبِ ولا في غرفةِ النوم.',en:'No device before prayer & duty, none in the bedroom.'},{ar:'وفّر بديلًا ممتعًا (رياضة، مشروع، وقتُ أب).',en:'Provide a fun alternative (sport, a project, father-time).'},{ar:'كُن قدوةً في ضبطِ جهازِك أمامه.',en:'Model device-control before him.'},{ar:'راقِب بوعيٍ مع احترامِ خصوصيّتِه المعقولة.',en:'Monitor consciously while respecting reasonable privacy.'}]},
    {p:{ar:'الانطواءُ وكتمانُ ما يدور في داخله',en:'Withdrawal & bottling things up'},
      why:{ar:'بدايةُ تشكّلِ عالمٍ داخليٍّ خاصّ، أو خوفٌ من حكمٍ قاسٍ، أو شعورٌ بأنّه لا يُسمَع.',en:'A private inner world forming, or fear of harsh judgment, or feeling unheard.'},
      islamic:{ar:'الرفقُ والإنصاتُ من هَدي النبيِّ ﷺ؛ كان يُصغي للصغيرِ ويُكنّيه ويحترم شعورَه.',en:'Gentleness & listening are prophetic; he ﷺ listened to the young, gave them kunyas & respected their feelings.'},
      psych:{ar:'لا تجبره على الكلام؛ اقترب بنشاطٍ مشتركٍ (الحوارُ يسهل جنبًا إلى جنبٍ لا وجهًا لوجه)، وتقبّل مشاعرَه بلا حكم.',en:'Don\u2019t force talk; approach via a shared activity (talk flows side-by-side, not face-to-face), & accept his feelings without judgment.'},
      steps:[{ar:'خصّص وقتًا منتظمًا جنبًا إلى جنب (مشي، قيادة، رياضة).',en:'Set regular side-by-side time (walking, driving, sport).'},{ar:'أصغِ بلا مقاطعةٍ أو حلٍّ فوريّ أو محاضرة.',en:'Listen without interrupting, instant fixing, or lecturing.'},{ar:'تقبّل شعورَه: «أفهم أنّ هذا أزعجك».',en:'Validate the feeling: \u201cI understand this upset you.\u201d'},{ar:'شاركه شيئًا من نفسك ليشعر بالندّيّةِ والأمان.',en:'Share something of yourself so he feels safe & equal.'},{ar:'إن طال الانطواءُ مع حزنٍ وعزلةٍ استشر مختصًّا.',en:'If withdrawal persists with sadness & isolation, consult a specialist.'}]},
  ],
  checklist:[
    {ar:'هيّأتُه لتغيّراتِ البلوغِ بوضوحٍ وسكينةٍ قبل وقوعها',en:'I prepared him for puberty\u2019s changes clearly & calmly, in advance'},
    {ar:'علّمتُه الطهارةَ والغُسلَ وأحكامَ البلوغ',en:'I taught him purity, ghusl & the rulings of buloogh'},
    {ar:'صلاتُه شبهُ منتظمةٍ عن قناعةٍ لا إجبار',en:'His prayer is near-regular by conviction, not force'},
    {ar:'بيني وبينه حوارٌ يوميٌّ يسألني فيه بلا خوف',en:'We have daily dialogue; he asks me without fear'},
    {ar:'أحفظُ خصوصيّتَه وأمنحُه حدودًا واضحةً باحترام',en:'I respect his privacy & give clear boundaries respectfully'},
    {ar:'أتابعُ أجهزتَه ومحتواه وأصدقاءَه عن قُربٍ ووعي',en:'I monitor his devices, content & friends closely & consciously'},
    {ar:'لنا جلسةٌ أسبوعيّةٌ خاصّةٌ يفتح فيها قلبَه',en:'We have a private weekly session where his heart opens'},
    {ar:'غرستُ الحياءَ والسترَ وحدّثتُه عن غضِّ البصر',en:'I planted modesty & covering & spoke of lowering the gaze'},
  ],
  followup:[
    {period:{ar:'يوميًّا',en:'Daily'}, item:{ar:'هل صلّى عن رضا؟ هل حدّثني بصدقٍ عن يومه؟ كم وقتَ الجهاز؟',en:'Did he pray willingly? Did he tell me honestly about his day? How much device time?'}},
    {period:{ar:'أسبوعيًّا',en:'Weekly'}, item:{ar:'هل تمّت الجلسةُ الخاصّة؟ كيف حالُ أصدقائه؟ هل ظهرت بوادرُ البلوغ؟',en:'Did the private session happen? How are his friends? Any signs of puberty?'}},
    {period:{ar:'كلَّ بضعةِ أشهر',en:'Every few months'}, item:{ar:'مراجعةُ ما يحتاج معرفتَه قبل البلوغ، ومستوى ثقتِه بنفسه واستقلالِه.',en:'Review what he needs to know before puberty, & his confidence & independence.'}},
  ],
  practice:{
    track:{ar:'مسارُ «الفرسان» (١٠–١٢) في كتاب خارطة طريق المربّي',en:'The \u201cKnights\u201d track (10\u201312) in the Parent Roadmap book'},
    items:[
      {ar:'عمّق العقيدةَ بالبرهان من «منارة العقيدة» (المختبر والتوحيد)، وثبّت الحياءَ والقيمَ من «القلب السليم» و«حيّنا الصغير».',en:'Deepen creed with proof from Faith Minaret (Lab & Tawheed), & anchor modesty & values via Pure Heart & Our Little District.'},
      {ar:'استعِن بكتابِ خطةِ المربّي في فتحِ حوارِ البلوغِ الهادئ، وبسيرِ شبابِ الصحابةِ في «حصن الأبطال» قدوةً لهذه السنّ.',en:'Use the Roadmap book to open the calm puberty talk, and the young-companions\u2019 stories in Heroes\u2019 Fortress as role models for this age.'},
    ]},
});
