/* stage-6.js — المرحلة السادسة · 15–18 · الرسالة والاستقلال */
window.TARBIYAH.stages.push({
  id:'s6', age:'15–18', ic:'🦅', c:'#E67E22',
  nm:{ar:'الرسالةُ والاستقلال', en:'Purpose & Independence'},
  sub:{ar:'المراهقةُ المتأخّرة — نحو الرجولةِ والرشد', en:'Late adolescence — toward maturity'},
  intro:{ar:'هنا تكتمل مرحلةُ «الوزارةِ والصُّحبة». ابنُك شابٌّ مكلّفٌ كامل، يكتمل عقلُه وتتّسع نظرتُه ويبحث عن معنى حياتِه ومكانِه في العالم. مهمّتك تحوّلت من «المربّي» إلى «المستشارِ والشريك»: تُهيّئه للرسالةِ والمسؤوليّةِ الكبرى — الزواجِ، والعملِ، والعفّةِ، وحملِ الدين — وتحصّنه فكريًّا ضدّ الشبهاتِ والفتن، لا بالحجرِ بل بالعلمِ والثقةِ والصحبة. أنت تُعدّ الآن رجلًا سيغادر بيتَك قريبًا؛ فاجعله رجلًا تفخر به.',
    en:'Here the \u201cminister & companion\u201d stage completes. Your child is a fully accountable youth; his mind matures, his view widens, & he searches for life\u2019s meaning & his place in the world. Your task shifts from \u201ceducator\u201d to \u201cconsultant & partner\u201d: you prepare him for purpose & greater responsibility \u2014 marriage, work, chastity, bearing the deen \u2014 and fortify him intellectually against doubts & temptations, not by confinement but by knowledge, trust & company. You are now preparing a man who will soon leave your home; make him a man you are proud of.'},
  glance:[
    {ic:'⏳', k:{ar:'جرعةُ الوقت',en:'Time dose'}, v:{ar:'٣٠–٦٠ دقيقةً حوارًا ناضجًا يوميًّا',en:'30\u201360 min mature dialogue daily'}},
    {ic:'🎯', k:{ar:'المهمّةُ الكبرى',en:'Core task'}, v:{ar:'الرسالةُ + التحصينُ الفكريّ',en:'Purpose + intellectual fortification'}},
    {ic:'🚫', k:{ar:'الخطُّ الأحمر',en:'Red line'}, v:{ar:'لا وصايةَ خانقةَ ولا انفصالَ بارد',en:'No smothering control, no cold detachment'}},
    {ic:'🗝️', k:{ar:'الكلمةُ المفتاح',en:'Keyword'}, v:{ar:'الثقةُ والرسالة',en:'Trust & mission'}},
  ],
  scholar:{ar:'تمامُ مرحلةِ المصاحبةِ، والشابُّ الآن مكلّفٌ كامل البلوغِ والعقل. تُبنى علاقتُه على الثقةِ والمشورةِ والشراكةِ في همومِ الأسرةِ والأمّة. ومن فقهِ التربيةِ تهيئتُه للرسالةِ الكبرى: العفّةُ وحفظُ النفسِ، والإعدادُ للزواجِ متى استطاع — قال ﷺ: «يا معشرَ الشبابِ من استطاع منكم الباءةَ فليتزوّج» — والبرُّ، والدعوةُ، ونفعُ الناس، وحملُ الدين.\n\nوقد غُذِّيَ شبابُ الصحابةِ بالمسؤوليّةِ مبكّرًا فأثمروا عظماء: أسامةُ قائدًا، ومعاذٌ قاضيًا في اليمن، ومصعبُ بنُ عميرٍ سفيرَ الإسلامِ الأوّلَ للمدينةِ شابًّا، وعليٌّ وابنُ الزبيرِ وابنُ عبّاسٍ نجومًا في شبابِهم. لم يُعامَلوا كأطفالٍ بل كرجالٍ يُحمَّلون ويُوثَق بهم.\n\nوحفظُه من الفتنِ والشبهاتِ يكون بالتحصينِ لا بالتعمية: حصّن عقلَه بالعلمِ الصحيحِ والحوارِ المفتوح، وقلبَه بالصحبةِ الصالحةِ والعبادة. فالحجرُ والمنعُ وحدَه لا يصنع رجلًا بل يصنع هاربًا. ومن لم يجد في بيتِه جوابًا لأسئلتِه الكبرى التمسه عند غيره، فكُن أنت أوّلَ من يجيب.',
    en:'The completion of the companionship stage; the youth is now fully accountable in puberty & reason. His relationship rests on trust, consultation & partnership in the concerns of family & ummah. Part of the fiqh of upbringing is preparing him for the great mission: chastity & self-restraint, readiness for marriage when able \u2014 \u201cO youth, whoever can marry, let him\u201d \u2014 devotion to parents, da\u2019wah, benefiting people & bearing the deen.\n\nThe young Companions were fed responsibility early & bore great fruit: Usamah a commander, Mu\u2018adh a judge in Yemen, Mus\u2018ab b. \u2018Umayr Islam\u2019s first envoy to Madinah as a youth, and \u2018Ali, Ibn al-Zubayr & Ibn \u2018Abbas stars in their youth. They were treated not as children but as men, entrusted & trusted.\n\nProtecting him from temptations & doubts is through fortification, not blindfolding: fortify his mind with sound knowledge & open dialogue, & his heart with good company & worship. Mere confinement & banning does not make a man but a fugitive. Whoever finds no answer to his great questions at home seeks it elsewhere \u2014 so be the first to answer.'},
  psych:{ar:'يصف إريكسون هذه المرحلةَ بتثبيتِ الهُويّةِ والتوجّهِ نحو المستقبل؛ يكتمل التفكيرُ المجرّدُ والأخلاقيُّ ويبدأ التخطيطُ للحياة. يسعى الشابُّ للاستقلالِ الكاملِ وبناءِ مشروعِه، ويحتاج أن يُعامَل كراشدٍ يُوثَق به لا كطفلٍ يُراقَب.\n\nاكتمل نضجُ الفصِّ الجبهيِّ تقريبًا، فصار أقدرَ على ضبطِ النفسِ والتفكيرِ في العواقب، لكنّه ما زال يحتاج توجيهًا غيرَ مباشرٍ ومهاراتٍ حياتيّةً وحوارًا فكريًّا ناضجًا. الفراغُ من أخطرِ ما يواجهه؛ فالطاقةُ بلا رسالةٍ تتحوّل إلى شهوةٍ أو عبثٍ أو شكّ.\n\nأخطرُ خطأين الآن: الوصايةُ المفرطةُ التي تخنق نضجَه فيتمرّد أو ينفصل، أو الانفصالُ العاطفيُّ بحجّةِ أنّه «كبر». الصحُّ بينهما: الثقةُ مع الحضورِ الدافئِ — قاعدةٌ آمنةٌ يعود إليها. وأمّا الشبهاتُ الفكريّةُ فلا تُعالَج بالإنكارِ والخوفِ بل بالعلمِ والنقاشِ المفتوحِ الذي يحترم عقلَه.',
    en:'Erikson marks this stage by identity consolidation & future orientation; abstract & moral reasoning mature & life-planning begins. The youth seeks full independence & to build his project, & needs to be treated as a trusted adult, not a watched child.\n\nThe frontal lobe is nearly mature, so he\u2019s better at self-control & weighing consequences, but still needs indirect guidance, life skills & mature intellectual dialogue. Emptiness is among the gravest dangers he faces; energy without a mission turns to desire, idleness or doubt.\n\nThe two worst errors now: over-control that suffocates his maturity (he rebels or detaches), or emotional detachment under the excuse that \u201che\u2019s grown.\u201d The right path between them: trust with warm presence \u2014 a secure base he returns to. Intellectual doubts are treated not by denial & fear but by knowledge & open discussion that respects his mind.'},
  specialists:[
    {q:{ar:'«أعطِ الشابَّ رسالةً يعيش لها، وإلّا عاش لشهوةٍ تستهلكه؛ الفراغُ أخطرُ أعدائه».',en:'\u201cGive the youth a mission to live for, or he\u2019ll live for a desire that consumes him; emptiness is his worst enemy.\u201d'}, by:{ar:'في تربيةِ الشبابِ على الرسالة',en:'On raising youth with purpose'}},
    {q:{ar:'«حصّن عقلَه بالحوارِ لا بالمنع؛ الشبهةُ تُعالَج بالعلمِ والنقاشِ المفتوح لا بالإنكارِ والخوف».',en:'\u201cFortify his mind with dialogue, not prohibition; doubt is treated with knowledge & open discussion, not denial & fear.\u201d'}, by:{ar:'مختصّو الإرشادِ الفكريّ',en:'Intellectual-mentoring specialists'}},
    {q:{ar:'«عامِل ابنَك المراهقَ كراشدٍ يُوثَق به، يرتفع إلى مستوى ثقتِك؛ عامِله كطفلٍ ينزل إليه».',en:'\u201cTreat your teen as a trusted adult & he rises to your trust; treat him as a child & he sinks to it.\u201d'}, by:{ar:'من علم نفسِ النموّ',en:'Developmental psychology'}},
  ],
  evidences:[
    {type:'hadith', text:{ar:'«يا معشرَ الشبابِ، من استطاع منكم الباءةَ فليتزوّج، فإنّه أغضُّ للبصرِ وأحصنُ للفرج».',en:'\u201cO youth, whoever among you can marry, let him; it lowers the gaze & guards chastity.\u201d'}, ref:{ar:'متفق عليه',en:'Bukhari & Muslim'}, note:{ar:'خطابٌ مباشرٌ للشبابِ في العفّةِ والزواج.',en:'A direct address to youth on chastity & marriage.'}},
    {type:'hadith', text:{ar:'«وشابٌّ نشأ في عبادةِ الله» — من السبعةِ الذين يُظلّهم اللهُ في ظلِّه يومَ لا ظلَّ إلّا ظلُّه.',en:'\u201cA youth who grew up worshipping Allah\u201d \u2014 of the seven Allah shades on the Day of no shade but His.'}, ref:{ar:'متفق عليه',en:'Bukhari & Muslim'}, note:{ar:'فضلٌ عظيمٌ لشبابِ الطاعة.',en:'A great virtue for youth of obedience.'}},
    {type:'athar', text:{ar:'بعث النبيُّ ﷺ مصعبَ بنَ عميرٍ — وهو شابّ — مُعلّمًا وداعيةً إلى المدينةِ قبل الهجرة.',en:'The Prophet ﷺ sent the young Mus\u2018ab b. \u2018Umayr as teacher & caller to Madinah before the Hijrah.'}, ref:{ar:'السيرة',en:'The Seerah'}, note:{ar:'الشابُّ يُحمَّل رسالةً تصنع رجولتَه.',en:'The youth is entrusted with a mission that forges his manhood.'}},
  ],
  rewards:[
    {ic:'🌟', t:{ar:'شابٌّ في ظلِّ العرش',en:'A youth in the shade of the Throne'}, d:{ar:'«شابٌّ نشأ في عبادةِ الله» من السبعة؛ ومن ربّاه على ذلك له مثلُ أجره.',en:'\u201cA youth raised in Allah\u2019s worship\u201d is of the seven; who raised him so has its like in reward.'}},
    {ic:'🕋', t:{ar:'صدقةٌ جاريةٌ ودعوةٌ تمتدّ',en:'Ongoing charity & a reach that extends'}, d:{ar:'إذا صار داعيةً نافعًا جرى لك أجرُ كلِّ من اهتدى على يديه.',en:'If he becomes a beneficial caller, the reward of all guided by him flows to you.'}},
    {ic:'🏡', t:{ar:'رجلٌ صالحٌ يبني بيتًا صالحًا',en:'A righteous man who builds a righteous home'}, d:{ar:'تهيئتُه للزواجِ والرسالةِ تُثمر أسرةً صالحةً وجيلًا بعده على الخير.',en:'Preparing him for marriage & mission yields a righteous family & a generation after him upon good.'}},
  ],
  needs:[
    {ar:'الثقةُ والمعاملةُ كراشدٍ مسؤول',en:'Trust & treatment as a responsible adult'},
    {ar:'هدفٌ ورسالةٌ ومشروعُ حياةٍ واضح',en:'A purpose, mission & clear life-project'},
    {ar:'مهاراتٌ حياتيّةٌ واستقلالٌ متدرّج',en:'Life skills & gradual independence'},
    {ar:'حوارٌ فكريٌّ ناضجٌ حول الإيمانِ والمعنى',en:'Mature intellectual dialogue on faith & meaning'},
    {ar:'تهيئةٌ للزواجِ والعفّةِ ومسؤوليّةِ المستقبل',en:'Preparation for marriage, chastity & future duty'},
    {ar:'حضورٌ دافئٌ بلا وصايةٍ خانقة',en:'Warm presence without smothering control'},
  ],
  risks:[
    {ar:'الانفصالُ العاطفيُّ أو الوصايةُ المفرطة',en:'Emotional detachment or smothering control'},
    {ar:'الشبهاتُ الفكريّةُ والإلحادُ بلا تحصين',en:'Intellectual doubts & atheism without fortification'},
    {ar:'العلاقاتُ المحرّمةُ وفتنُ الشهوات',en:'Forbidden relationships & temptations of desire'},
    {ar:'ضياعُ الهدفِ والفراغُ والرفقةُ الضائعة',en:'Loss of purpose, emptiness & lost company'},
    {ar:'الانجرافُ خلف المالِ أو الشهرةِ بلا قيم',en:'Chasing money or fame without values'},
    {ar:'كبتُ طموحِه أو السخريةُ من أحلامِه',en:'Suppressing his ambition or mocking his dreams'},
  ],
  values:[
    {ar:'الرسالةُ والهدفُ ونفعُ الأمّة',en:'Mission, purpose & serving the ummah'},
    {ar:'رسوخُ الإيمانِ عن علمٍ وقناعة',en:'Faith grounded in knowledge & conviction'},
    {ar:'العفّةُ والمسؤوليّةُ وحُسنُ الخُلُق',en:'Chastity, responsibility & good character'},
    {ar:'الاستقلالُ والبرُّ وتحمّلُ التبعات',en:'Independence, devotion & accountability'},
  ],
  dose:{ar:'٣٠–٦٠ دقيقةً يوميًّا من الحوارِ الناضجِ والشراكة — والكيفُ هنا أهمُّ من الكمّ. لم يَعُد يحتاج «وقتَ لعب» بل «وقتَ ندٍّ»: نقاشُ فكرة، مشروعٌ مشترك، استشارةٌ حقيقيّة، صلاةٌ جنبًا إلى جنب. الأبُ شريكٌ ومستشار: اجعل له بابًا مفتوحًا دائمًا، ونشاطًا أو مشروعًا يجمعكما، وحوارًا أسبوعيًّا عميقًا عن الحياةِ والمستقبلِ والإيمان.',
    en:'30\u201360 min daily of mature dialogue & partnership \u2014 quality matters more than quantity here. He no longer needs \u201cplaytime\u201d but \u201cpeer-time\u201d: discussing an idea, a shared project, real consultation, prayer side by side. The father is partner & consultant: keep an always-open door, an activity or project that unites you, & a deep weekly conversation about life, future & faith.'},
  daily:[
    {t:{ar:'الفجر',en:'Fajr'}, dur:{ar:'—',en:'—'}, act:{ar:'القدوةُ في القيامِ للصلاة، دعاءٌ له بظهرِ الغيب',en:'Example in rising for prayer, du\u2019a for him in his absence'}, who:{ar:'الأب',en:'Father'}},
    {t:{ar:'حوارُ الفكر',en:'Idea talk'}, dur:{ar:'٢٠ د',en:'20 min'}, act:{ar:'نقاشُ خبرٍ أو فكرةٍ أو شبهةٍ بعقلٍ منفتحٍ واحترامٍ لرأيه',en:'Discuss a news item, idea or doubt with an open mind & respect for his view'}, who:{ar:'الأب',en:'Father'}},
    {t:{ar:'مشروع/مهارة',en:'Project/skill'}, dur:{ar:'٢٠ د',en:'20 min'}, act:{ar:'عملٌ مشتركٌ أو مهارةُ حياةٍ (مال، قيادة، تصليح، عمل)',en:'Shared work or a life skill (finance, driving, fixing, work)'}, who:{ar:'الأب',en:'Father'}},
    {t:{ar:'شراكةُ القرار',en:'Decision partnership'}, dur:{ar:'١٠ د',en:'10 min'}, act:{ar:'أشركه في قرارٍ أسريٍّ حقيقيٍّ وثِق برأيه واعمل به أحيانًا',en:'Include him in a real family decision; trust & sometimes act on his view'}, who:{ar:'الأب/الأم',en:'Father/Mother'}},
    {t:{ar:'لحظةُ القلب',en:'Heart moment'}, dur:{ar:'حسب الحال',en:'as it flows'}, act:{ar:'حضورٌ متاحٌ بلا إلحاح؛ كُن قاعدتَه الآمنةَ حين يحتاج',en:'Available presence without pressing; be his secure base when needed'}, who:{ar:'الأب/الأم',en:'Father/Mother'}},
  ],
  weekly:[
    {d:{ar:'يوميًّا',en:'Daily'}, act:{ar:'حوارٌ فكريٌّ ناضج + شراكةٌ في قرار + قدوةٌ في العبادة',en:'Mature idea-talk + decision partnership + example in worship'}},
    {d:{ar:'أسبوعيًّا',en:'Weekly'}, act:{ar:'جلسةٌ عميقةٌ عن الحياةِ والمستقبلِ والإيمان، أو مشروعٌ يجمعكما',en:'A deep session on life, future & faith, or a project that unites you'}},
    {d:{ar:'الجمعة',en:'Friday'}, act:{ar:'صلاةُ الجمعةِ معًا كرجلَين، حديثٌ عن رسالتِه ودورِه في الأمّة',en:'Jumu\u2019ah together as two men, talk of his mission & role in the ummah'}},
  ],
  fatherFocus:{ar:'في هذه السنّ يصير الأبُ مرآةً لما سيكونه الابنُ رجلًا. عامِله كصديقٍ ورجلٍ ومستشار، لا كطفلٍ تُملي عليه. أشركه في همومِك ومشاريعك واستشِره بصدق، وافتح معه حوارًا صريحًا عن العفّةِ والزواجِ والمالِ والمستقبلِ والشبهات. لا تخَف من أسئلتِه الكبرى عن الدين؛ استقبِلها بصدرٍ رحبٍ فأنت أأمنُ من يجيبها. أعطه مساحةَ استقلالٍ يثبت فيها نفسَه، وابقَ قاعدتَه الآمنة. وأعظمُ هديّةٍ: أن تجعله يشعر أنّه رجلٌ تثق به وتفخر به.',
    en:'At this age the father becomes a mirror of the man the son will be. Treat him as a friend, a man & a consultant, not a child you dictate to. Involve him in your concerns & projects & consult him sincerely, & open frank talk about chastity, marriage, money, the future & doubts. Don\u2019t fear his big questions about faith; receive them with an open chest \u2014 you are the safest to answer them. Give him space of independence to prove himself, & remain his secure base. The greatest gift: making him feel he is a man you trust & are proud of.'},
  activities:[
    {ic:'🧠', t:{ar:'مجلسُ الفكر',en:'The thought circle'}, how:{ar:'ناقشا أسبوعيًّا قضيّةً أو شبهةً أو كتابًا بعقلَين منفتحَين، واسمح له بالاختلاف.',en:'Weekly, discuss an issue, doubt or book with two open minds, & allow him to disagree.'}, why:{ar:'يحصّن عقلَه ويبني تفكيرًا نقديًّا مؤمنًا.',en:'Fortifies his mind & builds faithful critical thinking.'}},
    {ic:'💼', t:{ar:'مهاراتُ الرجل',en:'A man\u2019s skills'}, how:{ar:'علّمه إدارةَ المالِ والوقتِ والعمل، وشجّعه على عملٍ صيفيٍّ أو مشروعٍ صغير.',en:'Teach managing money, time & work; encourage a summer job or small venture.'}, why:{ar:'يبني الاستقلالَ والمسؤوليّةَ والكفاءة.',en:'Builds independence, responsibility & competence.'}},
    {ic:'🎯', t:{ar:'مشروعُ الرسالة',en:'The mission project'}, how:{ar:'ساعِده على تحديدِ هدفٍ كبيرٍ ينفع به نفسَه وأمّتَه (علم، دعوة، مهنة، خدمة).',en:'Help him define a big goal benefiting himself & his ummah (knowledge, da\u2019wah, a profession, service).'}, why:{ar:'يملأ فراغَه بمعنًى ويقيه ضياعَ الهدف.',en:'Fills his idleness with meaning & guards against lost purpose.'}},
    {ic:'🤲', t:{ar:'حوارُ العفّةِ والزواج',en:'The chastity & marriage talk'}, how:{ar:'تحدّث معه بصراحةٍ ووقارٍ عن العفّةِ وغضِّ البصرِ والاستعدادِ للزواجِ مستقبلًا.',en:'Speak frankly & with dignity about chastity, lowering the gaze & readiness for future marriage.'}, why:{ar:'يحميه ويهيّئه لأعظمِ مسؤوليّاتِ الرشد.',en:'Protects him & prepares him for adulthood\u2019s greatest duty.'}},
    {ic:'🕌', t:{ar:'صحبةُ الكبار',en:'Company of the mature'}, how:{ar:'اربطه بمعلّمٍ أو داعيةٍ أو حلقةِ شبابٍ صالحةٍ يأخذ عنها ويُقتدى بها.',en:'Connect him to a teacher, caller or wholesome youth circle to learn from & emulate.'}, why:{ar:'قدوةٌ من خارجِ البيتِ ترسّخ الهُويّةَ والرسالة.',en:'An outside role model cements identity & mission.'}},
    {ic:'👥', t:{ar:'شريكٌ في القرار',en:'A partner in decisions'}, how:{ar:'أشركه في قراراتِ الأسرةِ الكبرى واستشِره وقدّر رأيَه أمام الجميع.',en:'Include him in major family decisions, consult him & value his view before all.'}, why:{ar:'يشعره بالرجولةِ والثقةِ والانتماء.',en:'Gives him a sense of manhood, trust & belonging.'}},
  ],
  examples:[
    {title:{ar:'يطرح شبهةً عن الدين',en:'He raises a doubt about religion'}, scene:{ar:'يسألك سؤالًا حادًّا: «كيف أتأكّد أنّ اللهَ موجود؟» أو يردّد شبهةً سمِعها.',en:'He asks a sharp question: \u201chow do I know Allah exists?\u201d or repeats a doubt he heard.'},
      do:{ar:'افرح بثقتِه فيك، اشكره على سؤاله، أجِب بعلمٍ وهدوءٍ أو ابحثا معًا، واربطه بمصدرٍ موثوقٍ (عالم، كتاب، رحلةُ منارة العقيدة).',en:'Rejoice at his trust, thank him for asking, answer with knowledge & calm or research together, & connect him to a trusted source (a scholar, a book, the Faith Minaret journey).'},
      dont:{ar:'لا تنفعل ولا تتّهمه في دينه ولا تقل «حرامٌ أن تسأل»؛ فتدفعه لكتمانِ الشبهةِ حتى تكبر.',en:'Don\u2019t react angrily, accuse his faith, or say \u201cit\u2019s forbidden to ask\u201d; that pushes him to bury the doubt till it grows.'},
      root:{ar:'الشبهةُ المكتومةُ تكبر، والمناقَشةُ بعلمٍ تُحصّن؛ ثقتُه أنّك تجيب بصدرٍ رحبٍ هي حمايتُه.',en:'A buried doubt grows; one discussed with knowledge fortifies; his trust that you answer openly is his protection.'}},
    {title:{ar:'فراغٌ وضياعُ هدف',en:'Idleness & a lost sense of purpose'}, scene:{ar:'تراه يقضي ساعاتٍ في اللهوِ بلا هدفٍ ويشكو الملل.',en:'You see him spend hours idling without a goal, complaining of boredom.'},
      do:{ar:'أشركه في اكتشافِ موهبتِه ورسالته، اقترِح مشروعًا أو عملًا أو تطوّعًا، واجعله يشعر أنّ له دورًا تنتظره الأمّة.',en:'Involve him in discovering his talent & mission, suggest a project, job or volunteering, & make him feel he has a role the ummah awaits.'},
      dont:{ar:'لا توبّخه بـ«أنت كسولٌ فاشل»؛ التحقيرُ يزيد الفراغَ انغلاقًا واكتئابًا.',en:'Don\u2019t scold him as \u201clazy & a failure\u201d; belittling deepens the idleness into withdrawal & depression.'},
      root:{ar:'الطاقةُ بلا رسالةٍ تتحوّل لشهوةٍ أو عبث؛ امنحه معنًى يملأ فراغَه.',en:'Energy without a mission turns to desire or futility; give him meaning to fill the void.'}},
  ],
  problems:[
    {p:{ar:'الشبهاتُ الفكريّةُ وضعفُ اليقين',en:'Intellectual doubts & weak certainty'},
      why:{ar:'انفتاحٌ على أفكارِ الإنترنتِ بلا تحصين، وعقلٌ ناقدٌ يبحث عن أجوبةٍ مقنعة.',en:'Exposure to internet ideas without fortification, & a critical mind seeking convincing answers.'},
      islamic:{ar:'العلمُ النافعُ حصنٌ؛ ربطُه برحلاتِ العقيدةِ بالبرهان (منارة العقيدة) وبالعلماءِ الموثوقين، وتعليمُه أنّ السؤالَ ليس كفرًا.',en:'Beneficial knowledge is a fortress; connect him to evidence-based creed (Faith Minaret) & trusted scholars, & teach him that questioning is not disbelief.'},
      psych:{ar:'لا تُنكِر الشبهةَ ولا تُخوّف؛ ناقشها بعقلٍ منفتحٍ يحترم تفكيرَه، فالقمعُ يرسّخها والحوارُ يحلّها.',en:'Don\u2019t deny the doubt or instill fear; discuss it open-mindedly, respecting his reasoning \u2014 suppression entrenches it, dialogue dissolves it.'},
      steps:[{ar:'استقبِل السؤالَ بترحيبٍ لا بصدمةٍ أو اتّهام.',en:'Receive the question with welcome, not shock or accusation.'},{ar:'إن لم تعرف الجوابَ ابحثا معًا أو اسألا عالمًا.',en:'If you don\u2019t know, research together or ask a scholar.'},{ar:'اربطه بمصادرَ علميّةٍ موثوقةٍ تحصّن عقلَه.',en:'Connect him to trusted scholarly sources that fortify his mind.'},{ar:'قوِّ يقينَه بآياتِ التفكّرِ في الخلقِ والنفس.',en:'Strengthen his certainty with verses pondering creation & the self.'},{ar:'حافِظ على عبادتِه وصحبتِه الصالحةِ فهي حصنُ القلب.',en:'Maintain his worship & good company \u2014 the heart\u2019s fortress.'}]},
    {p:{ar:'فتنةُ الشهوةِ والعلاقاتِ المحرّمة',en:'Temptation of desire & forbidden relations'},
      why:{ar:'فورانُ الغريزةِ في سنِّها، ومحتوًى محرّضٌ في كلِّ مكان، وفراغٌ ووقتٌ بلا رقابة.',en:'The surge of instinct at its peak, provocative content everywhere, & idle, unmonitored time.'},
      islamic:{ar:'العفّةُ عبادةٌ وأجرُها عظيم؛ «وشابٌّ نشأ في عبادةِ الله». رغّبه في الزواجِ متى استطاع، وعلّمه غضَّ البصرِ والصومَ لمن لم يستطع.',en:'Chastity is worship with great reward; \u201ca youth raised in worship.\u201d Encourage marriage when able, & teach lowering the gaze & fasting for who cannot.'},
      psych:{ar:'الكبتُ بالتخويفِ يفشل؛ الأنجعُ توجيهُ الطاقةِ (رياضة، هدف، مشروع)، وحوارٌ صريحٌ بلا عيبٍ يحفظ كرامتَه ويعلّمه ضبطَ النفس.',en:'Suppression by fear fails; better to channel the energy (sport, a goal, a project), with frank, non-shaming talk that preserves his dignity & teaches self-control.'},
      steps:[{ar:'حوارٌ صريحٌ وقورٌ عن العفّةِ بلا خجلٍ ولا تجريم.',en:'A frank, dignified talk on chastity, without shyness or criminalizing.'},{ar:'وجّه طاقتَه لرياضةٍ وهدفٍ ومشروعٍ يملأ وقتَه.',en:'Channel his energy to sport, a goal & a project that fills his time.'},{ar:'رغّبه في الزواجِ متى استطاع، وعلّمه الصومَ والغضَّ.',en:'Encourage marriage when able; teach fasting & lowering the gaze.'},{ar:'ضع حدودًا واعيةً للأجهزةِ والخلوةِ بلا تجسّسٍ مهين.',en:'Set conscious limits on devices & seclusion, without degrading spying.'},{ar:'اربطه بصحبةٍ صالحةٍ تعينه على العفّة.',en:'Connect him to good company that helps him stay chaste.'}]},
  ],
  checklist:[
    {ar:'أعامله كراشدٍ موثوقٍ وأُشركه في قراراتِ الأسرة',en:'I treat him as a trusted adult & include him in family decisions'},
    {ar:'حصّنتُه ضدّ الشبهاتِ بالعلمِ والحوارِ المفتوح',en:'I fortified him against doubts with knowledge & open dialogue'},
    {ar:'أعنتُه على اكتشافِ رسالتِه وهدفِه ومشروعِ حياته',en:'I help him discover his mission, purpose & life-project'},
    {ar:'علّمتُه مهاراتٍ حياتيّةً ومنحتُه استقلالًا متدرّجًا',en:'I taught him life skills & gave gradual independence'},
    {ar:'تحدّثنا بوضوحٍ عن العفّةِ والزواجِ والمسؤوليّة',en:'We spoke clearly about chastity, marriage & responsibility'},
    {ar:'أبقى حاضرًا بالحبِّ والثقةِ لا بالرقابةِ والقهر',en:'I stay present through love & trust, not surveillance & force'},
    {ar:'أستقبلُ أسئلتَه الكبرى عن الدينِ بصدرٍ رحبٍ لا بخوف',en:'I receive his big faith-questions openly, not fearfully'},
    {ar:'أدعو له بالصلاحِ والثباتِ والتوفيقِ في رسالته',en:'I pray for his righteousness, steadfastness & success in his mission'},
  ],
  followup:[
    {period:{ar:'يوميًّا',en:'Daily'}, item:{ar:'هل أبقيتُ بابَ الحوارِ مفتوحًا؟ هل عاملتُه كرجلٍ يُوثَق به؟',en:'Did I keep dialogue open? Did I treat him as a trusted man?'}},
    {period:{ar:'أسبوعيًّا',en:'Weekly'}, item:{ar:'هل تمّ الحوارُ العميق؟ كيف حالُ يقينِه وعفّتِه وهدفِه ورفقتِه؟',en:'Did the deep talk happen? How is his certainty, chastity, purpose & company?'}},
    {period:{ar:'كلَّ بضعةِ أشهر',en:'Every few months'}, item:{ar:'مراجعةُ تقدّمِه نحو رسالتِه واستقلالِه وتهيئتِه للزواجِ والمستقبل.',en:'Review his progress toward his mission, independence & readiness for marriage & the future.'}},
  ],
  practice:{
    track:{ar:'مرحلةُ الإطلاقِ — من متعلّمٍ إلى شريكٍ ومُعلّم',en:'The launch stage — from learner to partner & teacher'},
    items:[
      {ar:'وجّهه ليُتمّ رحلاتِ «منارة العقيدة» و«القدس والأمة» تحصينًا فكريًّا، وليصير مُعلّمًا لإخوتِه في الموقع.',en:'Steer him to complete the Faith Minaret & Al-Quds journeys as intellectual fortification, & to become a teacher of his siblings on the site.'},
      {ar:'أشركه في قيادةِ خطّةِ الأسرةِ من «ركن الأهل»، وافتح معه حوارًا عن مشروعِه ورسالتِه وتهيئةِ الزواج.',en:'Involve him in leading the family\u2019s plan from the Parents\u2019 Corner, & open a conversation about his project, mission & marriage-readiness.'},
    ]},
});
