/* ═══ ورشة الصانع الصغير — بيانات الأنشطة ═══ */
window.WS = {

/* ── الفئات ── */
cats: [
  { id:'crafts',  ic:'🎨', ar:'أشغالٌ يدوية',      en:'Handicrafts',      stamp:'🏵️' },
  { id:'science', ic:'🔬', ar:'تجاربُ علمية',      en:'Science at Home',  stamp:'⚗️' },
  { id:'garden',  ic:'🌱', ar:'زراعةٌ وعناية',     en:'Planting & Care',  stamp:'🌻' },
  { id:'nature',  ic:'🔭', ar:'استكشافُ الطبيعة',  en:'Nature Explorer',  stamp:'🦋' },
  { id:'life',    ic:'🏡', ar:'مهاراتٌ حياتية',    en:'Life Skills',      stamp:'🗝️' },
  { id:'khair',   ic:'🤲', ar:'أعمالُ الخير',      en:'Good Deeds',       stamp:'💝' },
  { id:'seasons', ic:'🌙', ar:'مواسمُ الخير',      en:'Blessed Seasons',  stamp:'🕌' },
  { id:'games',   ic:'🎲', ar:'ألعابٌ جماعية',     en:'Group Games',      stamp:'🏆' },
],

/* ── سِمات (روح النشاط) ── */
themes: {
  ilm:      { ic:'📚', ar:'عِلم',   en:'Knowledge' },
  tafakkur: { ic:'🌌', ar:'تفكُّر', en:'Reflection' },
  amal:     { ic:'💪', ar:'عَمَل',  en:'Action' },
  laab:     { ic:'🎈', ar:'مرح',    en:'Fun' },
},

/* ── الأركان المرتبطة ── */
corners: {
  aqeeda: { ic:'🕋', ar:'منارة العقيدة',      en:'Faith Minaret',   color:'#C0392B' },
  ibada:  { ic:'🌙', ar:'واحة العبادة',       en:'Worship Oasis',   color:'#117A8B' },
  quran:  { ic:'📖', ar:'بستان القرآن والسنة', en:'Quran Garden',    color:'#1A9B7B' },
  social: { ic:'🏘️', ar:'حيّنا الصغير',       en:'Little District', color:'#D4A017' },
  heart:  { ic:'💚', ar:'ركن القلب السليم',   en:'Pure Heart',      color:'#6C3483' },
  sport:  { ic:'🏊', ar:'النادي الرياضي',     en:'Sports Club',     color:'#27AE60' },
  academy:{ ic:'🔭', ar:'أكاديمية المبدعين',  en:'Academy',         color:'#2980B9' },
},

/* ── الأنشطة ── */
acts: [

/* ═══ أشغال يدوية ═══ */
{
  id:'lantern', cat:'crafts', ic:'🏮', corner:'ibada', themes:['amal','laab'],
  ar:'فانوسُ المسجدِ الورقيّ', en:'Paper Mosque Lantern',
  descAr:'اصنعْ فانوساً جميلاً يُضيءُ ركنَ صلاتِك في البيت.',
  descEn:'Craft a beautiful lantern to light up your prayer corner at home.',
  whyAr:'تعلّمتَ في واحةِ العبادة أنَّ الصلاةَ نورٌ — فلنصنعْ نوراً لركنِ صلاتِنا!',
  whyEn:'In the Worship Oasis you learned that prayer is light — let\'s craft a light for our prayer corner!',
  tools:[
    {ic:'📄', ar:'ورقٌ ملوَّن', en:'Colored paper'},
    {ic:'✂️', ar:'مقصٌّ (بمساعدةِ الأهل)', en:'Scissors (with a parent)'},
    {ic:'🖍️', ar:'ألوان', en:'Crayons'},
    {ic:'🧴', ar:'صمغ', en:'Glue'},
  ],
  steps:[
    {ic:'📄', ar:'اطوِ الورقةَ الملوَّنةَ من المنتصفِ طولياً.', en:'Fold the colored paper in half lengthwise.'},
    {ic:'✂️', ar:'قُصَّ خطوطاً من جهةِ الطيَّةِ دونَ الوصولِ إلى الطرف.', en:'Cut slits from the folded edge, without reaching the end.'},
    {ic:'🔄', ar:'افتحِ الورقةَ ولُفَّها على شكلِ أسطوانةٍ وألصقْ طرفَيها.', en:'Open it, roll it into a cylinder, and glue the edges.'},
    {ic:'🎨', ar:'زيِّنْه بهلالٍ ونجومٍ من الورق.', en:'Decorate it with a paper crescent and stars.'},
    {ic:'🕌', ar:'علِّقْه فوقَ سجّادةِ صلاتِك — مكانُ صلاتِك صارَ أجمل!', en:'Hang it above your prayer mat — your prayer spot just got prettier!'},
  ],
  little:{ar:'الصغارُ يلوِّنون ويزيِّنون، والأهلُ يقصّون.', en:'Little ones color and decorate; parents do the cutting.'},
  big:{ar:'تحدٍّ: اصنعْ ٣ فوانيسَ بأحجامٍ متدرِّجةٍ وعلِّقْها معاً بخيط.', en:'Challenge: make 3 lanterns of different sizes and hang them on one string.'},
  wisdom:{ar:'«الصلاةُ نور» — رواه مسلم', en:'"Prayer is light" — Muslim'},
},
{
  id:'kaaba', cat:'crafts', ic:'🕋', corner:'aqeeda', themes:['ilm','amal'],
  ar:'مجسَّمُ الكعبةِ المشرَّفة', en:'Kaaba Model',
  descAr:'حوِّلْ علبةً قديمةً إلى مجسَّمٍ للكعبةِ تتعلَّمُ به قِبلتَك.',
  descEn:'Turn an old box into a Kaaba model and learn your Qiblah.',
  whyAr:'في منارةِ العقيدةِ عرفتَ بيتَ اللهِ الحرام — الآنَ اصنعْه بيدَيك وتعرَّفْ إلى اتِّجاهِ قِبلتِك.',
  whyEn:'In the Faith Minaret you learned about Allah\'s Sacred House — now build it and find your Qiblah.',
  tools:[
    {ic:'📦', ar:'علبةٌ كرتونيةٌ صغيرة', en:'A small cardboard box'},
    {ic:'🖤', ar:'ورقٌ أو قماشٌ أسود', en:'Black paper or fabric'},
    {ic:'💛', ar:'شريطٌ ذهبيٌّ أو ورقٌ أصفر', en:'Gold ribbon or yellow paper'},
    {ic:'🧴', ar:'صمغ', en:'Glue'},
  ],
  steps:[
    {ic:'📦', ar:'غلِّفِ العلبةَ كلَّها بالورقِ الأسود.', en:'Wrap the whole box in black paper.'},
    {ic:'💛', ar:'ألصقِ الشريطَ الذهبيَّ حولَها قربَ الأعلى — هذا حزامُ الكعبة.', en:'Glue the gold band near the top — that\'s the Kaaba\'s belt.'},
    {ic:'🚪', ar:'ارسمْ باباً ذهبياً صغيراً في أحدِ الجوانب.', en:'Draw a small golden door on one side.'},
    {ic:'🧭', ar:'اسألِ الأهل: أينَ اتِّجاهُ القِبلةِ في بيتِنا؟ وضعِ المجسَّمَ في ذلك الاتجاه.', en:'Ask your parents: where is the Qiblah in our home? Place your model that way.'},
    {ic:'🤲', ar:'صلِّ صلاتَك القادمةَ وأنتَ تعرفُ أنَّك تتوجَّهُ نحوَ هذا البيتِ العظيم.', en:'Pray your next prayer knowing you face this great House.'},
  ],
  little:{ar:'يكفي التغليفُ بالأسودِ ولصقُ شريطٍ واحد.', en:'Wrapping it black and adding one band is enough.'},
  big:{ar:'ابحثْ: كم مرةً يطوفُ الحاجُّ حولَ الكعبة؟ واكتبِ الجوابَ على بطاقةٍ بجانبِ المجسَّم.', en:'Research: how many times do pilgrims circle the Kaaba? Write it on a card next to your model.'},
  wisdom:{ar:'﴿فَوَلِّ وَجْهَكَ شَطْرَ الْمَسْجِدِ الْحَرَامِ﴾ — البقرة:144', en:'"So turn your face toward al-Masjid al-Haram" — 2:144'},
},

/* ═══ تجارب علمية ═══ */
{
  id:'watercycle', cat:'science', ic:'💧', corner:'aqeeda', themes:['ilm','tafakkur'], print:'experiment',
  ar:'دورةُ الماءِ في كيس', en:'Water Cycle in a Bag',
  descAr:'شاهدْ كيفَ يصعدُ الماءُ وينزلُ مطراً — في كيسٍ على نافذتِك!',
  descEn:'Watch water rise and fall as rain — inside a bag on your window!',
  whyAr:'تفكَّرتَ في منارةِ العقيدةِ في خلقِ الله — هذه التجربةُ تُريكَ آيةَ المطرِ أمامَ عينيك.',
  whyEn:'You reflected on Allah\'s creation in the Faith Minaret — this experiment shows you the sign of rain before your eyes.',
  tools:[
    {ic:'🛍️', ar:'كيسٌ شفّافٌ بسحّاب', en:'A clear zip-lock bag'},
    {ic:'💧', ar:'قليلٌ من الماء', en:'A little water'},
    {ic:'🔵', ar:'لونُ طعامٍ أزرق (اختياري)', en:'Blue food coloring (optional)'},
    {ic:'🖊️', ar:'قلمٌ ثابتٌ وشريطٌ لاصق', en:'Marker & tape'},
  ],
  steps:[
    {ic:'🖊️', ar:'ارسمْ على الكيسِ شمساً وغيمةً وبحراً.', en:'Draw a sun, a cloud, and a sea on the bag.'},
    {ic:'💧', ar:'ضعْ قليلاً من الماءِ الملوَّنِ وأغلقِ الكيسَ جيداً.', en:'Add a little colored water and seal the bag well.'},
    {ic:'☀️', ar:'ألصقْه على نافذةٍ مشمسةٍ واتركْه يوماً كاملاً.', en:'Tape it to a sunny window and leave it a full day.'},
    {ic:'👀', ar:'راقبْ: الماءُ يتبخَّرُ ويصعد، ثم يتكثَّفُ وينزلُ قطراتٍ كالمطر!', en:'Watch: the water evaporates and rises, then condenses and falls like rain!'},
    {ic:'📝', ar:'سجِّلْ ما رأيتَ في بطاقةِ التجربةِ العلمية.', en:'Record what you saw on your experiment card.'},
  ],
  little:{ar:'يرسمُ الصغيرُ الشمسَ والغيمة، ويكفي أن يراقبَ القطرات.', en:'Little ones draw the sun and cloud, and just watch the drops.'},
  big:{ar:'أضفْ كوباً ثانياً في الظلِّ وقارنْ: أيُّهما تبخَّرَ أسرع؟ ولماذا؟', en:'Add a second bag in the shade and compare: which evaporated faster? Why?'},
  wisdom:{ar:'﴿وَأَنزَلْنَا مِنَ السَّمَاءِ مَاءً طَهُورًا﴾ — الفرقان:48', en:'"And We send down from the sky pure water" — 25:48'},
},
{
  id:'filter', cat:'science', ic:'🫗', corner:'ibada', themes:['ilm','amal'], print:'experiment',
  ar:'مصفاةُ الماءِ الصغيرة', en:'Little Water Filter',
  descAr:'اصنعْ مصفاةً من الرملِ والحصى وشاهدِ الماءَ العكِرَ يصفو.',
  descEn:'Build a filter from sand and pebbles and watch murky water turn clear.',
  whyAr:'تعلّمتَ في واحةِ العبادةِ أهميةَ الطَّهارةِ والماءِ الطَّهور — اكتشفْ كيفَ يصفو الماء.',
  whyEn:'In the Worship Oasis you learned the value of purity and clean water — discover how water becomes clear.',
  tools:[
    {ic:'🍶', ar:'قارورةٌ بلاستيكيةٌ مقصوصةٌ نصفَين (بمساعدةِ الأهل)', en:'A plastic bottle cut in half (with a parent)'},
    {ic:'🏖️', ar:'رملٌ نظيفٌ وحصىً صغيرة', en:'Clean sand & small pebbles'},
    {ic:'🧻', ar:'قطنٌ أو منديلٌ ورقي', en:'Cotton or a paper towel'},
    {ic:'🥤', ar:'كوبُ ماءٍ معكَّرٍ بقليلٍ من التراب', en:'A cup of water muddied with a little soil'},
  ],
  steps:[
    {ic:'🔄', ar:'اقلبِ النصفَ العلويَّ للقارورةِ كالقمعِ فوقَ النصفِ السفلي.', en:'Flip the bottle\'s top half like a funnel over the bottom half.'},
    {ic:'🧻', ar:'ضعْ في عنقِها القطن، ثم طبقةَ رمل، ثم طبقةَ حصى.', en:'Put cotton in the neck, then a sand layer, then pebbles.'},
    {ic:'🫗', ar:'اسكبِ الماءَ العكِرَ ببطءٍ من الأعلى.', en:'Slowly pour the murky water on top.'},
    {ic:'✨', ar:'راقبِ الماءَ يخرجُ من الأسفلِ أصفى بكثير!', en:'Watch much clearer water drip out below!'},
    {ic:'⚠️', ar:'انتبه: هذا الماءُ للتجربةِ فقط — لا نشربُه.', en:'Careful: this water is only for the experiment — we don\'t drink it.'},
  ],
  little:{ar:'الأهلُ يقصّونَ القارورة، والصغيرُ يرتِّبُ الطبقاتِ ويسكب.', en:'Parents cut the bottle; little ones layer and pour.'},
  big:{ar:'جرِّبْ ترتيباً مختلفاً للطبقات — أيُّ ترتيبٍ يصفّي أفضل؟ سجِّلْ نتيجتَك.', en:'Try a different layer order — which filters best? Record your result.'},
  wisdom:{ar:'«الطُّهورُ شطرُ الإيمان» — رواه مسلم', en:'"Purity is half of faith" — Muslim'},
},

/* ═══ زراعة وعناية ═══ */
{
  id:'seed', cat:'garden', ic:'🌱', corner:'quran', themes:['tafakkur','amal'], print:'plant',
  ar:'بذرتي الصغيرة تنمو', en:'My Little Seed Grows',
  descAr:'ازرعْ بذرةَ فولٍ في قطنٍ وراقبْها تنبتُ يوماً بعدَ يوم.',
  descEn:'Plant a bean seed in cotton and watch it sprout day by day.',
  whyAr:'قرأتَ في بستانِ القرآنِ ﴿أَفَرَأَيْتُم مَّا تَحْرُثُونَ﴾ — الآنَ ازرعْ بيدِك وشاهدْ مَن يُنبِت.',
  whyEn:'In the Quran Garden you read "Have you seen what you sow?" — now plant with your own hand and see Who makes it grow.',
  tools:[
    {ic:'🫘', ar:'حبّاتُ فولٍ أو حمّص', en:'Bean or chickpea seeds'},
    {ic:'☁️', ar:'قطن', en:'Cotton'},
    {ic:'🥛', ar:'كوبٌ شفّاف', en:'A clear cup'},
    {ic:'💧', ar:'ماء', en:'Water'},
  ],
  steps:[
    {ic:'☁️', ar:'بلِّلِ القطنَ وضعْه في الكوب.', en:'Wet the cotton and place it in the cup.'},
    {ic:'🫘', ar:'ضعِ البذرةَ بينَ القطنِ وجدارِ الكوبِ لتراها وهي تنبت.', en:'Tuck the seed between the cotton and the cup wall so you can see it sprout.'},
    {ic:'☀️', ar:'ضعِ الكوبَ قربَ النافذةِ وبلِّلِ القطنَ كلَّ يوم.', en:'Keep the cup by the window and moisten the cotton daily.'},
    {ic:'📏', ar:'سجِّلْ في مفكرةِ نبتتي: متى ظهرَ الجذر؟ ومتى الساق؟', en:'Log in your plant diary: when did the root appear? The stem?'},
    {ic:'🪴', ar:'حينَ تكبرُ انقلْها إلى أصيصٍ فيه تراب — صارتْ نبتتَك أنت!', en:'When it grows, move it to a pot with soil — it\'s your very own plant!'},
  ],
  little:{ar:'مهمةُ الصغير: تبليلُ القطنِ كلَّ صباحٍ بعدَ أذكارِه.', en:'Little one\'s job: moisten the cotton every morning after their adhkar.'},
  big:{ar:'ازرعْ بذرتَين: واحدةً في النورِ وأخرى في الظلام — قارنْ واستنتج.', en:'Plant two seeds: one in light, one in darkness — compare and conclude.'},
  wisdom:{ar:'﴿أَفَرَأَيْتُم مَّا تَحْرُثُونَ ۝ أَأَنتُمْ تَزْرَعُونَهُ أَمْ نَحْنُ الزَّارِعُونَ﴾ — الواقعة:63-64', en:'"Have you seen what you sow? Is it you who makes it grow, or are We the grower?" — 56:63-64'},
},
{
  id:'herbs', cat:'garden', ic:'🌿', corner:'sport', themes:['amal','ilm'],
  ar:'حديقةُ النعناعِ في مطبخِنا', en:'Kitchen Mint Garden',
  descAr:'ازرعْ نعناعاً في أصيصٍ صغيرٍ واصنعْ منه شاياً صحياً لعائلتِك.',
  descEn:'Grow mint in a small pot and make healthy tea for your family.',
  whyAr:'في النادي الرياضيِّ تعلّمتَ أنَّ جسمَك أمانة — الأعشابُ الطبيعيةُ غذاءٌ طيِّبٌ لجسمِك.',
  whyEn:'In the Sports Club you learned your body is a trust — natural herbs are good food for it.',
  tools:[
    {ic:'🪴', ar:'أصيصٌ صغيرٌ فيه تراب', en:'A small pot with soil'},
    {ic:'🌿', ar:'عودُ نعناعٍ طازجٍ من البقالة', en:'A fresh mint sprig from the grocer'},
    {ic:'🥛', ar:'كوبُ ماء', en:'A cup of water'},
  ],
  steps:[
    {ic:'🥛', ar:'ضعْ عودَ النعناعِ في كوبِ ماءٍ أسبوعاً حتى تظهرَ جذورٌ بيضاء.', en:'Stand the mint sprig in a cup of water for a week until white roots appear.'},
    {ic:'🪴', ar:'اغرسْه في الأصيصِ برفقٍ وضعْه قربَ النافذة.', en:'Gently plant it in the pot and set it by the window.'},
    {ic:'💧', ar:'اسقِه كلَّ يومَين ولا تُغرِقْه.', en:'Water it every two days — don\'t drown it.'},
    {ic:'✂️', ar:'بعدَ أسابيعَ اقطفْ أوراقاً واغسلْها جيداً.', en:'After a few weeks, pick some leaves and wash them well.'},
    {ic:'🍵', ar:'اصنعْ مع الأهلِ شايَ نعناعٍ وقدِّمْه لهم بيدِك.', en:'Make mint tea with a parent and serve it to them yourself.'},
  ],
  little:{ar:'يسقي الصغيرُ النبتةَ ويعدُّ أوراقَها كلَّ جمعة.', en:'Little ones water the plant and count its leaves every Friday.'},
  big:{ar:'أضفْ عشبةً ثانيةً (بقدونس أو ريحان) وقارنْ سرعةَ نموِّهما.', en:'Add a second herb (parsley or basil) and compare their growth speed.'},
  wisdom:{ar:'«ما أكلَ أحدٌ طعاماً قطُّ خيراً من أن يأكلَ من عملِ يدِه» — رواه البخاري', en:'"No one eats better food than what he earns by his own hands" — Bukhari'},
},

/* ═══ استكشاف الطبيعة ═══ */
{
  id:'moon', cat:'nature', ic:'🌙', corner:'ibada', themes:['tafakkur','ilm'], print:'moon',
  ar:'مرصدُ القمرِ الصغير', en:'Little Moon Observatory',
  descAr:'راقبِ القمرَ ٧ ليالٍ وارسمْ شكلَه — واكتشفْ سرَّ الشهورِ الهجرية.',
  descEn:'Watch the moon for 7 nights, draw its shape — and discover the secret of Hijri months.',
  whyAr:'الشهورُ الهجريةُ التي تعلّمتَها تبدأ برؤيةِ الهلال — كنْ أنتَ الراصدَ هذا الأسبوع!',
  whyEn:'The Hijri months you learned begin with sighting the crescent — be the observer this week!',
  tools:[
    {ic:'📋', ar:'بطاقةُ «يومياتُ القمر» المطبوعة', en:'The printed Moon Journal card'},
    {ic:'✏️', ar:'قلمُ رصاص', en:'A pencil'},
    {ic:'👨‍👩‍👧', ar:'أحدُ الوالدَين للخروجِ ليلاً', en:'A parent for going out at night'},
  ],
  steps:[
    {ic:'🌆', ar:'بعدَ صلاةِ العشاءِ اخرجْ مع أحدِ والدَيك إلى الشرفةِ أو الحديقة.', en:'After Isha, step out with a parent to the balcony or garden.'},
    {ic:'🌙', ar:'ابحثْ عن القمر: هل هو هلالٌ رفيع؟ نصفٌ؟ بدرٌ مكتمل؟', en:'Find the moon: is it a thin crescent? A half? A full moon?'},
    {ic:'✏️', ar:'ارسمْ شكلَه في خانةِ اليومِ على بطاقتِك.', en:'Draw its shape in today\'s box on your card.'},
    {ic:'🔁', ar:'كرِّرْ ذلك ٧ ليالٍ — ولا بأسَ إن غابَ خلفَ الغيم، اكتبْ «غيوم».', en:'Repeat for 7 nights — if clouds hide it, just write "cloudy".'},
    {ic:'💡', ar:'تأمَّلْ رسوماتِك: القمرُ يتغيَّرُ كلَّ ليلةٍ بنظامٍ دقيقٍ قدَّرَه الله.', en:'Look at your drawings: the moon changes nightly in a precise order Allah decreed.'},
  ],
  little:{ar:'يكفي الصغيرَ ٣ ليالٍ، ويلوِّنُ القمرَ بدلَ رسمِه.', en:'3 nights are enough for little ones — they can color the moon instead of drawing.'},
  big:{ar:'تابعْ شهراً كاملاً وحدِّدْ: متى كانَ البدر؟ وأيُّ ليلةٍ هجريةٍ وافقَها؟', en:'Track a full month: when was the full moon? Which Hijri night was it?'},
  wisdom:{ar:'﴿وَالْقَمَرَ قَدَّرْنَاهُ مَنَازِلَ﴾ — يس:39', en:'"And the moon — We have determined for it phases" — 36:39'},
},
{
  id:'safari', cat:'nature', ic:'🐜', corner:'academy', themes:['ilm','laab'], print:'safari',
  ar:'سفاري الحديقةِ الصغير', en:'Backyard Safari',
  descAr:'خذْ عدسةَ المستكشفِ وعُدَّ المخلوقاتِ في حديقتِك: نملٌ وعصافيرُ وفراشات.',
  descEn:'Grab your explorer\'s eye and count the creatures in your garden: ants, birds, butterflies.',
  whyAr:'علماءُ أكاديميةِ المبدعينَ بدؤوا بالملاحظة — لاحظْ أنتَ مخلوقاتِ اللهِ الصغيرةَ من حولِك.',
  whyEn:'The Academy\'s scientists began with observation — now you observe Allah\'s small creatures around you.',
  tools:[
    {ic:'📋', ar:'بطاقةُ «سفاري الحديقة» المطبوعة', en:'The printed Safari card'},
    {ic:'✏️', ar:'قلم', en:'A pencil'},
    {ic:'🔍', ar:'عدسةٌ مكبِّرة (اختياري)', en:'A magnifying glass (optional)'},
  ],
  steps:[
    {ic:'🚶', ar:'اخرجْ إلى الحديقةِ أو أقربِ مساحةٍ خضراءَ مع أحدِ الأهل.', en:'Head to the garden or nearest green space with a parent.'},
    {ic:'🤫', ar:'قفْ ساكناً دقيقةً كاملة — المستكشفُ الجيدُ هادئ.', en:'Stand still for one full minute — a good explorer is quiet.'},
    {ic:'👀', ar:'ابحثْ عن: نملة، عصفور، فراشة أو نحلة، ورقةٍ مختلفةِ الشكل.', en:'Look for: an ant, a bird, a butterfly or bee, an oddly-shaped leaf.'},
    {ic:'✏️', ar:'سجِّلْ على بطاقتِك كم رأيتَ من كلِّ نوع.', en:'Tally how many of each you saw on your card.'},
    {ic:'🐜', ar:'راقبْ نملةً واحدةً دقيقتَين: إلى أين تذهب؟ ماذا تحمل؟ لا تؤذِها.', en:'Watch one ant for two minutes: where is it going? What is it carrying? Don\'t harm it.'},
  ],
  little:{ar:'يبحثُ الصغيرُ عن شيءٍ واحدٍ فقط: النمل! ويعدُّه بأصابعِه.', en:'Little ones hunt for just one thing: ants! — counting on their fingers.'},
  big:{ar:'اخترْ مخلوقاً واحداً وابحثْ عنه في كتابٍ أو مع الأهل: ماذا يأكل؟ أين يبيت؟', en:'Pick one creature and research it with a parent: what does it eat? Where does it sleep?'},
  wisdom:{ar:'﴿وَمَا مِن دَابَّةٍ فِي الْأَرْضِ إِلَّا عَلَى اللَّهِ رِزْقُهَا﴾ — هود:6', en:'"There is no creature on earth but that upon Allah is its provision" — 11:6'},
},

/* ═══ مهارات حياتية ═══ */
{
  id:'room', cat:'life', ic:'🛏️', corner:'sport', themes:['amal'], print:'skills',
  ar:'غرفتي مملكتي المرتَّبة', en:'My Tidy Kingdom',
  descAr:'رتِّبْ سريرَك وألعابَك بنفسِك أسبوعاً كاملاً — كالجنديِّ الصغير.',
  descEn:'Make your bed and tidy your toys yourself for a whole week — like a little soldier.',
  whyAr:'تعلّمتَ في النادي الرياضيِّ سننَ النظافة — والنظافةُ تبدأ من غرفتِك.',
  whyEn:'You learned the Sunnah of cleanliness in the Sports Club — and cleanliness starts in your room.',
  tools:[
    {ic:'📋', ar:'جدولُ «مهاراتي المنزلية» المطبوع', en:'The printed Home Skills chart'},
    {ic:'💪', ar:'همّةٌ عالية', en:'High spirits'},
  ],
  steps:[
    {ic:'🌅', ar:'كلَّ صباحٍ بعدَ الاستيقاظ: رتِّبْ سريرَك أولَ شيء.', en:'Every morning when you wake: make your bed first thing.'},
    {ic:'🧸', ar:'أعدْ كلَّ لعبةٍ إلى مكانِها بعدَ اللعب — لكلِّ شيءٍ بيت.', en:'Return every toy to its place after playing — everything has a home.'},
    {ic:'👕', ar:'ضعْ ملابسَك المتَّسخةَ في السلةِ بنفسِك.', en:'Put your dirty clothes in the basket yourself.'},
    {ic:'✅', ar:'علِّمْ في جدولِك كلَّ مساء: هل أنجزتَ مهامَّ اليوم؟', en:'Tick your chart each evening: did you finish today\'s tasks?'},
    {ic:'🏆', ar:'أكملْ ٧ أيامٍ متتالية — وأنتَ بطلُ الترتيبِ في البيت!', en:'Complete 7 days in a row — you\'re the home\'s tidiness champion!'},
  ],
  little:{ar:'مهمتانِ فقط للصغار: السريرُ والألعاب.', en:'Just two jobs for little ones: bed and toys.'},
  big:{ar:'أضفْ مهمةً أسبوعية: ترتيبُ خزانتِك أو رفِّ كتبِك كلَّ جمعة.', en:'Add a weekly task: organize your wardrobe or bookshelf every Friday.'},
  wisdom:{ar:'«إنَّ اللهَ جميلٌ يحبُّ الجمال» — رواه مسلم', en:'"Allah is beautiful and loves beauty" — Muslim'},
},
{
  id:'cook', cat:'life', ic:'🥗', corner:'social', themes:['amal','laab'],
  ar:'طبقي الأول بيدي', en:'My First Dish',
  descAr:'أعِدَّ سلطةً أو عصيراً بيدِك — وقدِّمْ طبقاً منه لجارِكم.',
  descEn:'Make a salad or juice with your own hands — and share a plate with your neighbor.',
  whyAr:'في حيِّنا الصغيرِ تعلّمتَ حقَّ الجار — أجملُ تطبيقٍ: طبقٌ صنعتَه بيدِك.',
  whyEn:'In Our Little District you learned the neighbor\'s right — the sweetest way to practice it: a dish you made yourself.',
  tools:[
    {ic:'🥒', ar:'خضارٌ أو فواكهُ مغسولة', en:'Washed vegetables or fruits'},
    {ic:'🔪', ar:'سكينٌ بلاستيكيةٌ آمنة (والأهلُ يقطعونَ الصعب)', en:'A safe plastic knife (parents cut the hard parts)'},
    {ic:'🥣', ar:'وعاءٌ كبير', en:'A big bowl'},
    {ic:'🍽️', ar:'طبقٌ جميلٌ للجيران', en:'A nice plate for the neighbors'},
  ],
  steps:[
    {ic:'🧼', ar:'اغسلْ يدَيك وسمِّ الله.', en:'Wash your hands and say Bismillah.'},
    {ic:'🥒', ar:'قطِّعِ الخضارَ الطريةَ بسكينِك الآمنةِ — والأهلُ يساعدونَك في الباقي.', en:'Chop the soft vegetables with your safe knife — parents help with the rest.'},
    {ic:'🥣', ar:'اخلطْ كلَّ شيءٍ في الوعاءِ وأضفْ قليلاً من الليمونِ والزيت.', en:'Mix everything in the bowl with a splash of lemon and oil.'},
    {ic:'🍽️', ar:'رتِّبْ طبقاً جميلاً واحملْه مع أحدِ والدَيك إلى الجيران.', en:'Arrange a beautiful plate and carry it with a parent to the neighbors.'},
    {ic:'😊', ar:'سلِّمْ عليهم بابتسامة: «هذا من صنعِ يدي!»', en:'Greet them with a smile: "I made this myself!"'},
  ],
  little:{ar:'الصغيرُ يغسلُ الخضارَ ويخلطُ ويزيِّنُ الطبق.', en:'Little ones wash, mix, and decorate the plate.'},
  big:{ar:'خطِّطْ وجبةً كاملةً بسيطةً وأشرفْ على تحضيرِها من الألفِ إلى الياء.', en:'Plan a simple full meal and lead its preparation start to finish.'},
  wisdom:{ar:'«ما زالَ جبريلُ يوصيني بالجارِ حتى ظننتُ أنه سيورِّثُه» — متفق عليه', en:'"Jibreel kept advising me about the neighbor until I thought he would inherit" — Agreed upon'},
},

/* ═══ أعمال الخير ═══ */
{
  id:'sadaqabox', cat:'khair', ic:'🎁', corner:'ibada', themes:['amal'],
  ar:'صندوقُ صدقتي السرّي', en:'My Secret Sadaqah Box',
  descAr:'اصنعْ صندوقَ صدقةٍ جميلاً واملأْه قرشاً قرشاً حتى تتصدَّق.',
  descEn:'Craft a beautiful sadaqah box and fill it coin by coin until you give.',
  whyAr:'عرفتَ في واحةِ العبادةِ كنزَ العطاء — الآنَ اصنعْ كنزَك الصغيرَ الذي يكبرُ كلَّ يوم.',
  whyEn:'You discovered the Treasure of Giving in the Worship Oasis — now craft your own little treasure that grows daily.',
  tools:[
    {ic:'🫙', ar:'مرطبانٌ أو علبةٌ فارغةٌ نظيفة', en:'An empty clean jar or box'},
    {ic:'🎨', ar:'ألوانٌ وورقٌ للتزيين', en:'Colors & paper for decorating'},
    {ic:'✂️', ar:'مقصٌّ لفتحةِ النقود (بمساعدةِ الأهل)', en:'Scissors for the coin slot (with a parent)'},
  ],
  steps:[
    {ic:'🎨', ar:'زيِّنِ الصندوقَ واكتبْ عليه: «صدقتي تُطفئُ الخطايا».', en:'Decorate the box and write on it: "My sadaqah extinguishes sins".'},
    {ic:'✂️', ar:'اطلبْ من الأهلِ فتحَ شقٍّ صغيرٍ للنقودِ في الغطاء.', en:'Ask a parent to cut a small coin slot in the lid.'},
    {ic:'🪙', ar:'ضعْ فيه قرشاً من مصروفِك كلَّ يومٍ أو كلَّ جمعة.', en:'Drop in a coin from your allowance daily or every Friday.'},
    {ic:'🤫', ar:'اجعلْها سراً بينَك وبينَ الله — الصدقةُ الخفيةُ أعظمُ أجراً.', en:'Keep it a secret between you and Allah — hidden charity has greater reward.'},
    {ic:'🕌', ar:'حينَ يمتلئ، اذهبْ مع الأهلِ وتصدَّقْ به على محتاجٍ أو مسجد.', en:'When it\'s full, go with your parents and give it to someone in need or a masjid.'},
  ],
  little:{ar:'يلوِّنُ الصغيرُ الصندوقَ ويضعُ القرشَ بيدِه كلَّ جمعة.', en:'Little ones color the box and drop the coin themselves every Friday.'},
  big:{ar:'احسبْ: لو وفَّرتَ قرشاً يومياً، كم تجمعُ في رمضانَ كامل؟', en:'Calculate: saving one coin a day, how much do you gather in a full Ramadan?'},
  wisdom:{ar:'«الصدقةُ تُطفئُ الخطيئةَ كما يُطفئُ الماءُ النار» — رواه الترمذي', en:'"Charity extinguishes sin as water extinguishes fire" — Tirmidhi'},
},
{
  id:'birr', cat:'khair', ic:'💐', corner:'heart', themes:['amal'], print:'kindness',
  ar:'مهمةُ البرِّ السرّية', en:'Secret Kindness Mission',
  descAr:'نفِّذْ ٣ خدماتٍ سريةٍ لوالدَيك دونَ أن يعرفوا مَن الفاعل!',
  descEn:'Carry out 3 secret acts of service for your parents — without them knowing who did it!',
  whyAr:'في ركنِ القلبِ السليمِ تعلّمتَ أنَّ برَّ الوالدَينِ بابٌ إلى الجنة — افتحِ البابَ اليومَ بعملٍ لا بكلام.',
  whyEn:'In the Pure Heart Corner you learned that honoring parents is a gate to Paradise — open that gate today with action, not words.',
  tools:[
    {ic:'📋', ar:'بطاقةُ «مهمةِ الخيرِ السرية» المطبوعة', en:'The printed Kindness Mission card'},
    {ic:'🤫', ar:'قدرةٌ على كتمانِ السر!', en:'The ability to keep a secret!'},
  ],
  steps:[
    {ic:'🕵️', ar:'راقبْ: ما الذي يُتعِبُ أمَّك أو أباك كلَّ يوم؟', en:'Observe: what tires your mom or dad every day?'},
    {ic:'📝', ar:'اخترْ ٣ خدماتٍ تقدرُ عليها: ترتيبُ الأحذية، تعبئةُ قارورةِ الماء، إحضارُ نظارةِ أبيك...', en:'Pick 3 services you can do: lining up the shoes, refilling the water bottle, fetching dad\'s glasses...'},
    {ic:'🤫', ar:'نفِّذْها في الخفاءِ دونَ أن يراك أحد.', en:'Do them secretly without being seen.'},
    {ic:'🙊', ar:'إذا سألوا «مَن فعلَ هذا؟» ابتسمْ ولا تُجِب!', en:'If they ask "who did this?" — just smile and don\'t tell!'},
    {ic:'🤲', ar:'ادعُ لهما في سجودِك: «ربِّ ارحمهما كما ربّياني صغيراً».', en:'Pray for them in your sujood: "My Lord, have mercy on them as they raised me when I was small".'},
  ],
  little:{ar:'خدمةٌ سريةٌ واحدةٌ تكفي الصغير — والدعاءُ معها.', en:'One secret service is enough for little ones — plus the du\'a.'},
  big:{ar:'اجعلْها عادةً: خدمةٌ سريةٌ واحدةٌ كلَّ يومٍ لمدةِ أسبوع.', en:'Make it a habit: one secret service every day for a week.'},
  wisdom:{ar:'﴿وَقُل رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا﴾ — الإسراء:24', en:'"And say: My Lord, have mercy upon them as they brought me up when I was small" — 17:24'},
},

],
};
