/* corners/stories/minaret-little/akhira.js — رحلة العبور (اليوم الآخر) للصغار (٣–٦)
   ١١ حكاية مبسّطة من محطات «رحلة العبور» في منارة العقيدة — بسلامٍ ورجاء.
   كل صفحة: emoji (بديل مؤقت) + text (سطران سهلان) + prompt (وصف صورة إنجليزي لتوليدها لاحقاً). */
window.MINARET_LITTLE = window.MINARET_LITTLE || {};
window.MINARET_LITTLE.akhira = {
  id:'akhira', icon:'🌉', color:'#5B4B8A', title:'رِحْلَةُ الْعُبُور', tag:'الْيَوْمُ الْآخِر',
  stories:[

{ id:'farm', icon:'🌱', color:'#27AE60', title:'الدُّنْيَا مَزْرَعَة',
  tag:'لِمَاذَا يَوْمٌ آخِر؟',
  pages:[
    { emoji:'🌾', text:'لِمَاذَا يَزْرَعُ الْفَلَّاحُ وَيَتْعَبُ شُهُورًا؟ لِأَنَّهُ يَنْتَظِرُ يَوْمَ الْحَصَاد!',
      prompt:'A cheerful farmer field with green sprouts under a warm sun, harvest anticipation, storybook style' },
    { emoji:'🌱', text:'وَالدُّنْيَا مَزْرَعَةُ الْآخِرَة: كُلُّ صَلَاةٍ وَخَيْرٍ تَزْرَعُهُ هُنَا، تَحْصُدُهُ هُنَاكَ أَضْعَافًا.',
      prompt:'A child planting a small seed in soil with a tiny glowing sprout, hope and growth, warm light' },
    { emoji:'⚖️', text:'وَاللهُ الْعَادِلُ لَا يَتْرُكُ الْمُحْسِنَ بِلَا جَائِزَةٍ وَلَا الظَّالِمَ بِلَا حِسَاب.',
      prompt:'A gentle glowing balance scale under soft light, fairness, calm and reassuring' },
    { emoji:'💚', text:'لِحَيَاتِكَ هَدَفٌ، وَلِرِحْلَتِكَ مَحَطَّةٌ أَخِيرَةٌ جَمِيلَة.',
      prompt:'A path leading toward a warm glowing horizon full of light, purpose and hope, teal and gold' },
  ],
  moral:'كُلُّ يَوْمٍ بَذْرَة: أَزْرَعُ الْخَيْرَ الْيَوْمَ لِأَحْصُدَهُ غَدًا. 💚',
  game:{ type:'sort', title:'أَيُّهَا بَذْرَةُ خَيْرٍ نَزْرَعُهَا؟', bins:['بَذْرَةُ خَيْر 🌱','لَيْسَتْ خَيْرًا 🚫'], items:[
    { e:'🤲', t:'صَلَاةٌ فِي وَقْتِهَا', bin:0 },
    { e:'🤝', t:'مُسَاعَدَةُ صَدِيق', bin:0 },
    { e:'😠', t:'أُوذِي غَيْرِي', bin:1 },
    { e:'😊', t:'كَلِمَةٌ طَيِّبَة', bin:0 } ] },
  act:{ q:'لِمَاذَا خَلَقَنَا اللهُ وَجَعَلَ يَوْمًا آخِرًا؟', yay:'صَحِيح! لِيُكَافِئَ الْمُحْسِنَ وَيُنْصِفَ الْمَظْلُوم', opts:[
    { e:'💚', t:'لِلْحِسَابِ الْعَادِلِ وَالْجَزَاء', ok:true },
    { e:'🎲', t:'بِلَا هَدَف' },
    { e:'😴', t:'لِلنَّوْمِ فَقَط' } ] },
  dua:'اللَّهُمَّ اجْعَلِ الْآخِرَةَ هَمَّنَا' },

{ id:'grave', icon:'🚪', color:'#8E44AD', title:'مَحَطَّةُ الِانْتِظَار',
  tag:'الْقَبْرُ أَوَّلُ مَنَازِلِ الْآخِرَة',
  pages:[
    { emoji:'🛏️', text:'الْقَبْرُ لِلْمُؤْمِنِ لَيْسَ نِهَايَةَ الطَّرِيق، بَلْ غُرْفَةُ انْتِظَارٍ مُرِيحَةٌ قَبْلَ اللِّقَاءِ الْكَبِير.',
      prompt:'A softly glowing peaceful resting chamber with warm light coming through, calm and reassuring, no scary elements' },
    { emoji:'❓', text:'يَأْتِي سُؤَالٌ سَهْل: مَنْ رَبُّك؟ مَا دِينُك؟ مَنْ نَبِيُّك؟',
      prompt:'Three gentle glowing question marks in soft light, calm and clear, warm colors' },
    { emoji:'💚', text:'وَالْمُؤْمِنُ يُجِيبُ بِثَبَاتٍ مِنَ الله: رَبِّيَ الله، دِينِيَ الْإِسْلَام، نَبِيِّي مُحَمَّدٌ ﷺ.',
      prompt:'A calm glowing heart steady and firm surrounded by gentle light, steadfastness, warm' },
    { emoji:'🌸', text:'فَيُفْتَحُ لَهُ بَابٌ إِلَى الْجَنَّةِ يَأْتِيهِ مِنْ نَسِيمِهَا، وَيَنَامُ مُطْمَئِنًّا.',
      prompt:'A gentle open door with paradise breeze and flower petals drifting through, peaceful and hopeful' },
  ],
  moral:'أَعِيشُ الْأَجْوِبَةَ الْيَوْمَ لِأَقُولَهَا هُنَاكَ بِسَلَام. 💚',
  game:{ type:'order', title:'رَتِّبْ أَجْوِبَةَ سُؤَالِ الْقَبْر', items:[
    { e:'💚', t:'رَبِّيَ الله' },
    { e:'🕌', t:'دِينِيَ الْإِسْلَام' },
    { e:'📖', t:'نَبِيِّي مُحَمَّدٌ ﷺ' },
    { e:'🌸', t:'بَابٌ إِلَى الْجَنَّة' } ] },
  act:{ q:'مَاذَا يَكُونُ الْقَبْرُ لِلْمُؤْمِن؟', yay:'أَحْسَنْت! غُرْفَةُ انْتِظَارٍ مُرِيحَةٌ قَبْلَ اللِّقَاء', opts:[
    { e:'🛏️', t:'غُرْفَةُ انْتِظَارٍ مُرِيحَة', ok:true },
    { e:'😨', t:'نِهَايَةُ كُلِّ شَيْء' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ ثَبِّتْنِي بِالْقَوْلِ الثَّابِت' },

{ id:'trumpet', icon:'📯', color:'#2980B9', title:'النَّفْخَةُ وَالْبَعْث',
  tag:'صَبَاحُ الْيَوْمِ الْكَبِير',
  pages:[
    { emoji:'📯', text:'يَأْمُرُ اللهُ إِسْرَافِيلَ فَيَنْفُخُ فِي الصُّور! نَفْخَةٌ يُصْعَقُ لَهَا كُلُّ شَيْء، ثُمَّ نَفْخَةٌ ثَانِيَة.',
      prompt:'A giant glowing golden trumpet-horn sounding in a vast dawn sky, majestic, awe and light' },
    { emoji:'🌅', text:'فَإِذَا الْخَلَائِقُ كُلُّهُم مِنْ آدَمَ إِلَى آخِرِ مَوْلُودٍ يَقُومُونَ أَحْيَاء!',
      prompt:'A luminous dawn with people rising as if waking, hopeful and gentle, warm golden light, no scary detail' },
    { emoji:'🌧️', text:'كَيْفَ؟ الَّذِي أَنْشَأَنَا أَوَّلَ مَرَّةٍ يُعِيدُنَا بِسُهُولَة. وَالْأَرْضُ تَحْيَا بِالْمَطَرِ كُلَّ رَبِيع!',
      prompt:'Dry cracked earth turning green with sprouts after rain, revival, hopeful transformation, warm' },
    { emoji:'💞', text:'وَفِي ذَلِكَ الْيَوْمِ يَلْتَقِي الْأَحِبَّةُ بَعْدَ فِرَاق. فَالْمَوْتُ فِرَاقٌ مُؤَقَّت.',
      prompt:'Two glowing figures reuniting joyfully in warm light, reunion after separation, tender and happy' },
  ],
  moral:'الَّذِي خَلَقَنِي أَوَّلَ مَرَّةٍ قَادِرٌ عَلَى إِعَادَتِي — وَكُلُّ رَبِيعٍ بُرْهَان. 🌅',
  game:{ type:'find', title:'الْأَرْضُ تَحْيَا كُلَّ رَبِيع! اجْمَعِ الْبَرَاعِمَ السِّتَّ النَّابِتَة', target:'🌱', count:6, distractors:['🍂','🪨'], size:12 },
  act:{ q:'كَيْفَ يُعِيدُنَا اللهُ بَعْدَ الْمَوْت؟', yay:'صَحِيح! الَّذِي أَنْشَأَنَا أَوَّلَ مَرَّةٍ يُعِيدُنَا', opts:[
    { e:'🌅', t:'الَّذِي خَلَقَنَا أَوَّلًا يُعِيدُنَا بِسُهُولَة', ok:true },
    { e:'🙅', t:'مُسْتَحِيلٌ أَنْ نَعُود' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُور' },

{ id:'shade', icon:'⛅', color:'#E67E22', title:'ظِلُّ الْعَرْش',
  tag:'أَرْضُ الْمَحْشَر',
  pages:[
    { emoji:'🏟️', text:'يُجْمَعُ النَّاسُ كُلُّهُم فِي أَرْضٍ وَاحِدَة، يَوْمٌ طَوِيلٌ تَدْنُو فِيهِ الشَّمْسُ وَيَشْتَدُّ الْحَرّ.',
      prompt:'A vast open plain with countless tiny figures gathered under a bright sky, immense scale, no scary detail' },
    { emoji:'⛅', text:'لَكِنْ هُنَاكَ سَبْعَةٌ يُظِلُّهُمُ اللهُ فِي ظِلِّهِ يَوْمَ لَا ظِلَّ إِلَّا ظِلُّه!',
      prompt:'A cool comforting patch of shade with soft golden light in a bright landscape, relief and blessing' },
    { emoji:'🧒', text:'وَأَوَّلُهُم: شَابٌّ نَشَأَ فِي عِبَادَةِ الله — هَذَا أَنْتَ إِنْ كَبِرْتَ عَلَى الطَّاعَة!',
      prompt:'A happy child praying on a small rug with warm light, growing up in worship, hopeful and tender' },
    { emoji:'💚', text:'الْمَقْعَدُ فِي الظِّلِّ يُحْجَزُ مِنَ الطُّفُولَة، لَا عِنْدَ الْكِبَر!',
      prompt:'A cozy reserved seat glowing in soft shade with a childs name tag, booked early, warm colors' },
  ],
  moral:'مَقْعَدِي فِي ظِلِّ الْعَرْشِ يُحْجَزُ مِنَ الْآن — مِنْ طُفُولَتِي. ⛅',
  game:{ type:'pairs', title:'صِلْ كُلَّ وَاحِدٍ مِنْ أَهْلِ الظِّلِّ بِصِفَتِه', pairs:[
    ['🧒 شَابّ','نَشَأَ فِي عِبَادَةِ الله'],
    ['🕌 قَلْبٌ مُعَلَّق','بِالْمَسَاجِد'],
    ['🤲 مُتَصَدِّق','أَخْفَى صَدَقَتَه'] ] },
  act:{ q:'مَنْ أَوَّلُ السَّبْعَةِ فِي ظِلِّ الْعَرْش؟', yay:'أَحْسَنْت! شَابٌّ نَشَأَ فِي عِبَادَةِ الله', opts:[
    { e:'🧒', t:'شَابٌّ نَشَأَ فِي عِبَادَةِ الله', ok:true },
    { e:'💰', t:'أَغْنَى رَجُل' },
    { e:'👑', t:'أَقْوَى مَلِك' } ] },
  dua:'اللَّهُمَّ أَظِلَّنِي فِي ظِلِّكَ يَوْمَ لَا ظِلَّ إِلَّا ظِلُّك' },

{ id:'shafaa', icon:'🤲', color:'#C0392B', title:'الشَّفَاعَةُ الْعُظْمَى',
  tag:'أَنَا لَهَا!',
  pages:[
    { emoji:'😟', text:'يَشْتَدُّ الِانْتِظَار، فَيَذْهَبُ النَّاسُ إِلَى الْأَنْبِيَاءِ يَطْلُبُونَ مَنْ يَشْفَعُ لَهُم عِنْدَ الله.',
      prompt:'A great crowd of tiny figures looking hopefully toward a distant glow, seeking help, warm sky' },
    { emoji:'🙇', text:'كُلُّ نَبِيٍّ يَقُول: نَفْسِي نَفْسِي… حَتَّى يَأْتُوا نَبِيَّنَا مُحَمَّدًا ﷺ.',
      prompt:'A soft radiant light where one figure steps forward humbly, chosen one, hopeful glow, no face' },
    { emoji:'💖', text:'فَيَقُولُ الْكَلِمَةَ الْجَمِيلَة: أَنَا لَهَا، أَنَا لَهَا! وَيَسْجُدُ تَحْتَ الْعَرْشِ لِرَبِّه.',
      prompt:'A glowing scene of prostration beneath a radiant throne of light, humility and courage, no face' },
    { emoji:'💚', text:'وَحِينَ يَقُولُ كُلُّ أَحَدٍ نَفْسِي، يَقُولُ نَبِيُّكَ ﷺ: أُمَّتِي أُمَّتِي!',
      prompt:'Warm rays of light embracing a crowd from above, care and mercy, tender and hopeful' },
  ],
  moral:'نَبِيِّي يَحْمِلُ هَمِّي يَوْمَ الْقِيَامَة، فَأَعِيشُ بِمَا يُفْرِحُه. 💖',
  game:{ type:'find', title:'أَكْثِرِ الصَّلَاةَ عَلَى النَّبِيِّ ﷺ! اجْمَعِ الْقُلُوبَ الْخَمْس', target:'💚', count:5, distractors:['☁️','⭐'], size:12 },
  act:{ q:'مَاذَا يَقُولُ نَبِيُّنَا ﷺ يَوْمَ الشَّفَاعَة؟', yay:'صَحِيح! أُمَّتِي أُمَّتِي — رَحْمَةً بِنَا', opts:[
    { e:'💖', t:'أُمَّتِي أُمَّتِي', ok:true },
    { e:'🙈', t:'نَفْسِي نَفْسِي' },
    { e:'🤷', t:'لَا شَيْء' } ] },
  dua:'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَآتِهِ الْوَسِيلَةَ وَالْفَضِيلَة' },

{ id:'records', icon:'📋', color:'#A65DA6', title:'كِتَابُكَ بِيَمِينِك',
  tag:'صُحُفُ الْأَعْمَال',
  pages:[
    { emoji:'📋', text:'فِي الْمَحْشَرِ تَتَطَايَرُ الصُّحُف: كُلُّ إِنْسَانٍ يَتَسَلَّمُ كِتَابَ حَيَاتِهِ كَامِلًا.',
      prompt:'Glowing pages of light flying gently toward open hands, records of deeds, warm and clear' },
    { emoji:'😊', text:'الْمُؤْمِنُ يَأْخُذُ كِتَابَهُ بِيَمِينِهِ فَيَطِيرُ فَرَحًا: هَاؤُمُ اقْرَؤُوا كِتَابِيَه!',
      prompt:'A joyful child holding up a glowing certificate-like book with pride, happy and proud, warm light' },
    { emoji:'✏️', text:'أَخْطَأْتَ كَثِيرًا؟ لَا تَيْأَس! التَّوْبَةُ تَمْحُو، وَالْحَسَنَاتُ تُذْهِبُ السَّيِّئَات.',
      prompt:'A pencil eraser gently wiping a page clean with a soft glow, forgiveness and hope, warm' },
    { emoji:'💛', text:'بَلْ يُبَدِّلُ اللهُ سَيِّئَاتِ التَّائِبِ حَسَنَات! فَكِتَابُكَ مَا زَالَ مَفْتُوحًا.',
      prompt:'A dark page turning golden and bright, transformation of sins to good, hopeful radiant light' },
  ],
  moral:'كِتَابِي مَا زَالَ مَفْتُوحًا وَالْقَلَمُ بِيَدِي — أُجَمِّلُ صَفْحَةً كُلَّ يَوْم. 💛',
  game:{ type:'sort', title:'مَاذَا نَكْتُبُ فِي صَفْحَتِنَا الْجَمِيلَة؟', bins:['نَكْتُبُهَا ✅','نَمْحُوهَا بِالتَّوْبَة 🧽'], items:[
    { e:'🤝', t:'مُسَاعَدَةٌ وَصِدْق', bin:0 },
    { e:'😠', t:'كَذِبٌ وَأَذًى', bin:1 },
    { e:'🙏', t:'صَلَاةٌ وَذِكْر', bin:0 },
    { e:'😤', t:'خَطَأٌ نَنْدَمُ عَلَيْه', bin:1 } ] },
  act:{ q:'أَخْطَأْتُ — هَلْ يُمْكِنُ أَنْ يَصِيرَ كِتَابِي جَمِيلًا؟', yay:'أَحْسَنْت! التَّوْبَةُ تَمْحُو وَتُبَدِّلُ السَّيِّئَاتِ حَسَنَات', opts:[
    { e:'💛', t:'نَعَم! بِالتَّوْبَةِ وَالْحَسَنَات', ok:true },
    { e:'😔', t:'لَا أَمَلَ أَبَدًا' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ آتِنِي كِتَابِي بِيَمِينِي وَحَاسِبْنِي حِسَابًا يَسِيرًا' },

{ id:'scale', icon:'⚖️', color:'#16A085', title:'الْمِيزَان',
  tag:'الْعَدْلُ الْمُطْلَق',
  pages:[
    { emoji:'⚖️', text:'يُنْصَبُ الْمِيزَانُ الْعَظِيمُ يَوْمَ الْقِيَامَة، فَلَا تُظْلَمُ نَفْسٌ شَيْئًا — وَلَوْ مِثْقَالَ حَبَّةٍ صَغِيرَة.',
      prompt:'A magnificent glowing golden balance scale in soft light, perfect justice, awe and calm' },
    { emoji:'🪶', text:'وَالْمُهِمُّ لَيْسَ حَجْمَ الْعَمَلِ بَلْ وَزْنَه: كَلِمَتَانِ خَفِيفَتَانِ ثَقِيلَتَانِ فِي الْمِيزَان!',
      prompt:'A light feather on one scale pan outweighing a heavy stone, surprising weight, gentle wonder' },
    { emoji:'🗣️', text:'سُبْحَانَ اللهِ وَبِحَمْدِه، سُبْحَانَ اللهِ الْعَظِيم — ثَانِيَتَانِ تَقُولُهُمَا وَفِي الْمِيزَانِ جَبَل!',
      prompt:'Words of light rising and forming a glowing mountain on a scale, dhikr weight, radiant' },
    { emoji:'😊', text:'وَأَثْقَلُ شَيْءٍ حُسْنُ الْخُلُق: ابْتِسَامَتُكَ وَصِدْقُكَ وَبِرُّكَ بِأُمِّك.',
      prompt:'A child smiling kindly and helping, warm hearts floating up, good character, tender warm light' },
  ],
  moral:'لَا صَغِيرَ فِي مَمْلَكَةِ الْمِيزَان — كُلُّ ذَرَّةِ خَيْرٍ تُرَى. 🪶',
  game:{ type:'sort', title:'أَيُّهَا ثَقِيلٌ فِي الْمِيزَان؟', bins:['ثَقِيلٌ فِي الْمِيزَان ⚖️','يُنْقِصُ الْمِيزَان 🚫'], items:[
    { e:'😊', t:'حُسْنُ الْخُلُقِ وَالِابْتِسَامَة', bin:0 },
    { e:'🗣️', t:'سُبْحَانَ اللهِ وَبِحَمْدِه', bin:0 },
    { e:'😠', t:'الْكَذِبُ وَالْأَذَى', bin:1 },
    { e:'🤝', t:'مُسَاعَدَةُ النَّاس', bin:0 } ] },
  act:{ q:'أَيُّ الْكَلِمَاتِ ثَقِيلَةٌ فِي الْمِيزَانِ خَفِيفَةٌ عَلَى اللِّسَان؟', yay:'صَحِيح! فِي الْمِيزَانِ جَبَل!', opts:[
    { e:'🗣️', t:'سُبْحَانَ اللهِ وَبِحَمْدِه', ok:true },
    { e:'😴', t:'لَا شَيْء' },
    { e:'😠', t:'كَلَامٌ سَيِّئ' } ] },
  dua:'اللَّهُمَّ ثَقِّلْ مَوَازِينَنَا بِالْحَسَنَاتِ وَحُسْنِ الْخُلُق' },

{ id:'hawd', icon:'⛲', color:'#5B7FD4', title:'الْحَوْضُ الْمَوْرُود',
  tag:'شَرْبَةٌ لَا ظَمَأَ بَعْدَهَا',
  pages:[
    { emoji:'⛲', text:'فِي زِحَامِ ذَلِكَ الْيَوْمِ وَحَرِّهِ، يَنْتَظِرُ الْمُؤْمِنِينَ حَوْضُ النَّبِيِّ ﷺ.',
      prompt:'A beautiful glowing basin of water in a bright landscape, oasis of relief, warm inviting light' },
    { emoji:'🥛', text:'مَاؤُهُ أَبْيَضُ مِنَ اللَّبَن، وَرِيحُهُ أَطْيَبُ مِنَ الْمِسْك، وَأَكْوَابُهُ كَنُجُومِ السَّمَاء!',
      prompt:'A basin of milky white water with sparkling star-like cups around it, magical and pure, night glow' },
    { emoji:'💧', text:'مَنْ شَرِبَ مِنْهُ شَرْبَةً لَمْ يَظْمَأْ بَعْدَهَا أَبَدًا!',
      prompt:'A single cup of shining water with a soft glow, one sip forever, refreshing and pure' },
    { emoji:'💚', text:'وَالنَّبِيُّ ﷺ يَنْتَظِرُ أُمَّتَه: قَالَ عَنَّا نَحْنُ إِخْوَانِي الَّذِينَ آمَنُوا وَلَمْ يَرَوْنِي!',
      prompt:'Warm welcoming light beside the basin as if someone waits lovingly, longing and care, tender' },
  ],
  moral:'نَبِيِّي سَمَّانِي أَخَاهُ وَهُوَ يَنْتَظِرُنِي عَلَى الْحَوْض. 💚',
  game:{ type:'pairs', title:'صِلْ كُلَّ وَصْفٍ بِالْحَوْض', pairs:[
    ['🥛 مَاؤُه','أَبْيَضُ مِنَ اللَّبَن'],
    ['⭐ أَكْوَابُه','كَنُجُومِ السَّمَاء'],
    ['💧 شَرْبَةٌ مِنْه','لَا ظَمَأَ بَعْدَهَا'] ] },
  act:{ q:'مَاذَا يَحْدُثُ لِمَنْ شَرِبَ مِنَ الْحَوْض؟', yay:'أَحْسَنْت! لَا يَظْمَأُ بَعْدَهَا أَبَدًا', opts:[
    { e:'💧', t:'لَا يَظْمَأُ بَعْدَهَا أَبَدًا', ok:true },
    { e:'😴', t:'يَنَام' },
    { e:'🤷', t:'لَا شَيْء' } ] },
  dua:'اللَّهُمَّ اسْقِنَا مِنْ حَوْضِ نَبِيِّكَ شَرْبَةً هَنِيئَة' },

{ id:'sirat', icon:'🌉', color:'#D4A017', title:'الصِّرَاط',
  tag:'جِسْرُ الثَّبَات',
  pages:[
    { emoji:'🌉', text:'آخِرُ مَعْبَرٍ قَبْلَ الْجَنَّة: الصِّرَاط — جِسْرٌ يَعْبُرُهُ الْمُؤْمِنُونَ إِلَى الْجَنَّة.',
      prompt:'A glowing bridge of light stretching toward a bright paradise horizon, hopeful crossing, warm' },
    { emoji:'⚡', text:'يَمُرُّ النَّاسُ عَلَيْهِ عَلَى قَدْرِ أَعْمَالِهِم: مِنْهُم كَالْبَرْقِ، وَمِنْهُم يَمْشِي.',
      prompt:'Figures of light crossing a bridge at different speeds, some fast like lightning, dynamic hopeful' },
    { emoji:'🕌', text:'وَسُرْعَتُكَ هُنَاكَ بِقَدْرِ اسْتِقَامَتِكَ هُنَا: عَلَى الصَّلَاةِ وَالصِّدْقِ وَالْحَلَال.',
      prompt:'A child walking steadily on a straight glowing path, steadfastness, warm confident light' },
    { emoji:'💚', text:'وَأَنْتَ تَتَدَرَّبُ عَلَيْهِ كُلَّ يَوْم: اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ فِي كُلِّ صَلَاة!',
      prompt:'Praying hands with a glowing straight path ahead, daily training for the crossing, warm' },
  ],
  moral:'مَنِ اسْتَقَامَ عَلَى صِرَاطِ الدُّنْيَا ثَبَتَ عَلَى صِرَاطِ الْآخِرَة. 🌉',
  game:{ type:'maze', title:'اعْبُرِ الصِّرَاطَ الْمُسْتَقِيمَ إِلَى الْجَنَّة', avatar:'🚶', goal:'🌸', wall:'🔥', map:['S#...','.#.#.','.#.#.','...#.','##..G'] },
  act:{ q:'مَا الَّذِي يُثَبِّتُ قَدَمِي عَلَى الصِّرَاط؟', yay:'صَحِيح! الِاسْتِقَامَةُ فِي الدُّنْيَا', opts:[
    { e:'🕌', t:'الصَّلَاةُ وَالصِّدْقُ وَالْحَلَال', ok:true },
    { e:'💰', t:'الْمَالُ الْكَثِير' },
    { e:'💪', t:'قُوَّةُ الْعَضَلَات' } ] },
  dua:'اللَّهُمَّ ثَبِّتْ أَقْدَامَنَا عَلَى صِرَاطِك' },

{ id:'janna', icon:'🏡', color:'#27AE60', title:'الْجَنَّةُ بَيْتُ اللَّاحُزْن',
  tag:'مَا لَا عَيْنٌ رَأَت',
  pages:[
    { emoji:'🌸', text:'يَعْبُرُ الْمُؤْمِنُونَ الْجِسْرَ فَتُفْتَحُ لَهُم أَبْوَابُ الْجَنَّة: سَلَامٌ عَلَيْكُم طِبْتُم فَادْخُلُوهَا خَالِدِين!',
      prompt:'Beautiful glowing gates of paradise opening with warm welcoming light and flowers, joyful arrival' },
    { emoji:'✨', text:'فِيهَا مَا لَا عَيْنٌ رَأَت، وَلَا أُذُنٌ سَمِعَت، وَلَا خَطَرَ عَلَى قَلْبِ بَشَر!',
      prompt:'A dazzling paradise garden with rivers, golden palaces and endless fruit, breathtaking beauty, warm' },
    { emoji:'😌', text:'وَأَجْمَلُ مَا فِيهَا: لَا حُزْنَ وَلَا مَرَضَ وَلَا فِرَاقَ وَلَا مَوْت، وَلِقَاءُ الْأَحِبَّة.',
      prompt:'A joyful family reunited in a lush paradise garden, no sadness, warm togetherness, radiant' },
    { emoji:'💚', text:'وَأَعْظَمُ نَعِيمِهَا: النَّظَرُ إِلَى وَجْهِ اللهِ الْكَرِيم.',
      prompt:'Radiant faces looking upward toward a glorious warm light, the greatest bliss, serene and luminous' },
  ],
  moral:'أَجْمَلُ مَا أَتَخَيَّلُه — الْجَنَّةُ أَجْمَلُ مِنْه، وَرِضَا اللهِ أَكْبَر. 💚',
  game:{ type:'find', title:'اقْطِفْ ثِمَارَ الْجَنَّةِ السِّتَّ الَّتِي لَا تَنْقَطِع', target:'🍇', count:6, distractors:['🍂','🌿'], size:12 },
  act:{ q:'مَا أَعْظَمُ نَعِيمٍ فِي الْجَنَّة؟', yay:'أَحْسَنْت! النَّظَرُ إِلَى وَجْهِ اللهِ الْكَرِيم', opts:[
    { e:'💚', t:'النَّظَرُ إِلَى وَجْهِ الله', ok:true },
    { e:'🍔', t:'الطَّعَامُ فَقَط' },
    { e:'😴', t:'النَّوْمُ فَقَط' } ] },
  dua:'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ وَلَذَّةَ النَّظَرِ إِلَى وَجْهِك' },

{ id:'fire', icon:'🚧', color:'#C0392B', title:'تَحْذِيرُ الرَّحِيم',
  tag:'النَّارُ لِمَنْ أَصَرَّ',
  pages:[
    { emoji:'🤱', text:'الْأُمُّ الْحَنُونُ تُمْسِكُ يَدَ طِفْلِهَا: لَا تَلْمَسِ النَّارَ سَتَحْرِقُك! لِأَنَّهَا تُحِبُّه.',
      prompt:'A loving parent gently holding a childs hand near a warning, protective care, warm tender scene' },
    { emoji:'🚧', text:'وَهَكَذَا حَذَّرَنَا اللهُ مِنَ النَّار — لَا لِيُرْعِبَنَا، بَلْ لِأَنَّهُ رَؤُوفٌ بِنَا.',
      prompt:'A gentle warning sign with soft caution glow on a road, guidance and care, no scary detail' },
    { emoji:'🚗', text:'مِثْلَ لَافِتَةِ الْخَطَرِ عَلَى الطَّرِيق: يَضَعُهَا مَنْ يُرِيدُكَ أَنْ تَصِلَ سَالِمًا.',
      prompt:'A caring road sign warning of a bend, a car slowing safely, protective guidance, warm daylight' },
    { emoji:'💚', text:'وَفَتَحَ اللهُ لِلنَّجَاةِ أَلْفَ بَاب: التَّوْبَة، وَالْحَسَنَات، حَتَّى صَدَقَةُ شِقِّ تَمْرَةٍ تَقِي مِنَ النَّار!',
      prompt:'Many glowing open doors of light with a small date-half charity shining, escape and mercy, hopeful' },
  ],
  moral:'حَذَّرَنِي لِأَنَّهُ يُحِبُّنِي — فَأَسِيرُ إِلَى الْجَنَّةِ بِقَلْبٍ مُطْمَئِنّ. 💚',
  game:{ type:'find', title:'ابْنِ حَاجِزًا مِنَ النَّار! اجْمَعْ صَدَقَاتِ الْخَيْرِ الْخَمْس', target:'🤲', count:5, distractors:['🔥','☁️'], size:12 },
  act:{ q:'لِمَاذَا حَذَّرَنَا اللهُ مِنَ النَّار؟', yay:'صَحِيح! لِأَنَّهُ رَؤُوفٌ بِنَا وَيُحِبُّ نَجَاتَنَا', opts:[
    { e:'💚', t:'لِأَنَّهُ رَحِيمٌ يُرِيدُ نَجَاتَنَا', ok:true },
    { e:'😠', t:'لِيُرْعِبَنَا فَقَط' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ أَجِرْنَا مِنَ النَّار، وَأَدْخِلْنَا الْجَنَّةَ مَعَ الْأَبْرَار' },

]};
