/* corners/stories/minaret-little/aman.js — سلسلة الأمان (أركان الإيمان الستة) للصغار (٣–٦)
   ١٧ حكاية مبسّطة من محطات «سلسلة الأمان بالله» في منارة العقيدة — ثمرةُ الإيمان: السكينة.
   كل صفحة: emoji (بديل مؤقت) + text (سطران سهلان) + prompt (وصف صورة إنجليزي لتوليدها لاحقاً). */
window.MINARET_LITTLE = window.MINARET_LITTLE || {};
window.MINARET_LITTLE.aman = {
  id:'aman', icon:'⛓️', color:'#2980B9', title:'سِلْسِلَةُ الْأَمَان', tag:'أَرْكَانُ الْإِيمَان',
  stories:[

{ id:'maiyyah', icon:'🤲', color:'#1ABC9C', title:'أَنْتَ لَسْتَ وَحْدَك',
  tag:'اللهُ مَعَك',
  pages:[
    { emoji:'🛰️', text:'هَلْ شَعَرْتَ يَوْمًا بِالْوَحْدَةِ فِي الظَّلَام؟ لِي بِشَارَة: أَنْتَ لَسْتَ وَحْدَكَ أَبَدًا! اللهُ مَعَكَ أَيْنَمَا كُنْت.',
      prompt:'A child alone in a cozy dim room with a gentle warm glow of presence around them, comfort, not scary' },
    { emoji:'👂', text:'يَسْمَعُ هَمْسَك، وَيَرَى دَمْعَتَك، وَيَعْلَمُ مَا فِي قَلْبِك — لَا يَغِيبُ عَنْكَ لَحْظَة.',
      prompt:'Soft rays of light gently surrounding a small figure, being seen and heard, tender warm scene' },
    { emoji:'🕋', text:'قَالَ النَّبِيُّ ﷺ لِأَبِي بَكْرٍ فِي الْغَار: لَا تَحْزَنْ إِنَّ اللهَ مَعَنَا! فَنَزَلَتِ السَّكِينَة.',
      prompt:'A calm cave interior at night with a soft peaceful light and two gentle glows, safety, serene' },
    { emoji:'💙', text:'فَمَنْ كَانَ اللهُ مَعَه، فَمَنْ يَخَاف؟',
      prompt:'A confident child standing with a warm light around them under a starry sky, security, uplifting' },
  ],
  moral:'اللهُ مَعِي أَيْنَمَا كُنْت، فَلَسْتُ وَحْدِي أَبَدًا. 💙',
  game:{ type:'pairs', title:'صِلْ كُلَّ اسْمٍ بِأَثَرِه', pairs:[
    ['👂 السَّمِيع','يَسْمَعُ هَمْسِي'],
    ['👁️ الْبَصِير','يَرَانِي فِي الظَّلَام'],
    ['💙 مَعِيَّةُ الله','تَطْرُدُ الْوَحْدَةَ وَالْخَوْف'] ] },
  act:{ q:'مَاذَا نَقُولُ عِنْدَ الْوَحْدَةِ أَوِ الْخَوْف؟', yay:'أَحْسَنْت! فَتَنْزِلُ السَّكِينَةُ عَلَى الْقَلْب', opts:[
    { e:'💙', t:'لَا تَحْزَنْ إِنَّ اللهَ مَعَنَا', ok:true },
    { e:'😱', t:'نَصْرُخُ خَوْفًا' },
    { e:'🙈', t:'نَخْتَبِئ' } ] },
  dua:'اللَّهُمَّ أَنْتَ مَعِي فَلَا تَدَعْنِي أَشْعُرُ بِالْوَحْدَة' },

{ id:'qayyum', icon:'🌙', color:'#2980B9', title:'الَّذِي لَا يَنَامُ أَبَدًا',
  tag:'الْقَيُّوم',
  pages:[
    { emoji:'🌙', text:'حِينَ تَنَامُ فِي اللَّيْلِ وَتُغْمِضُ عَيْنَيْك، مَنْ يَحْرُسُ الْعَالَمَ كُلَّه؟',
      prompt:'A peaceful sleeping town under a starry night sky with a watchful gentle glow above, safe and calm' },
    { emoji:'👁️', text:'إِنَّهُ اللهُ الْقَيُّوم: لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْم!',
      prompt:'A serene night sky with a soft radiant light that never dims, wakeful watch, deep blue and gold' },
    { emoji:'😴', text:'أَنْتَ تَتْعَبُ فَتَنَام، وَأَقْوَى رَجُلٍ يَنَام، لَكِنَّ اللهَ لَا يَنَامُ لَحْظَة.',
      prompt:'A cozy child sleeping peacefully in bed with soft moonlight, rest and safety, warm tender scene' },
    { emoji:'💙', text:'فَبَيْنَمَا تَنَامُ مُطْمَئِنًّا، يَبْقَى رَبُّكَ سَاهِرًا يَحْرُسُك.',
      prompt:'Gentle protective light like wings over a sleeping child bedroom, guarded through the night, warm' },
  ],
  moral:'الْقَيُّومُ لَا يَنَام، فَأَنَامُ آمِنًا تَحْتَ حِرَاسَتِه. 👁️',
  game:{ type:'sort', title:'مَنْ يَنَامُ وَمَنْ لَا يَنَامُ أَبَدًا؟', bins:['يَنَامُ وَيَتْعَب 😴','لَا يَنَامُ أَبَدًا 💙'], items:[
    { e:'🧍', t:'الْإِنْسَانُ الْقَوِيّ', bin:0 },
    { e:'💙', t:'اللهُ الْقَيُّوم', bin:1 },
    { e:'🦁', t:'الْحَيَوَانَات', bin:0 },
    { e:'🌙', t:'رَبِّي الَّذِي يَحْرُسُنِي', bin:1 } ] },
  act:{ q:'هَلْ يَنَامُ اللهُ الْقَيُّوم؟', yay:'صَحِيح! يَحْرُسُنَا وَنَحْنُ نَائِمُون', opts:[
    { e:'🌙', t:'لَا! لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْم', ok:true },
    { e:'😴', t:'نَعَم، مِثْلَنَا' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيث' },

{ id:'qadar', icon:'🧭', color:'#8E44AD', title:'الرُّبَّانُ الَّذِي تَثِقُ بِه',
  tag:'الْإِيمَانُ بِالْقَدَر',
  pages:[
    { emoji:'✈️', text:'حِينَ تَرْكَبُ طَائِرَةً وَتَهْتَزُّ قَلِيلًا، هَلْ تَجْرِي لِتَقُودَهَا بِنَفْسِك؟ لَا!',
      prompt:'A cartoon airplane flying through some clouds with a bit of turbulence, calm passengers, bright' },
    { emoji:'🧭', text:'لِأَنَّ هُنَاكَ رُبَّانًا خَبِيرًا يَقُودُهَا، فَتَجْلِسُ مُطْمَئِنًّا وَتَثِقُ بِه.',
      prompt:'A confident cockpit view with steady hands on controls and a clear sky ahead, trust, warm' },
    { emoji:'💫', text:'وَحَيَاتُكَ كَذَلِك: رُبَّانُهَا اللهُ الْحَكِيمُ يَقُودُهَا بِعِلْمٍ وَحِكْمَة.',
      prompt:'A ship steered steadily across a calm glowing sea toward a bright horizon, wise guidance, serene' },
    { emoji:'☂️', text:'مَا أَخْطَأَكَ لَمْ يَكُنْ لِيُصِيبَك، وَمَا أَصَابَكَ لَمْ يَكُنْ لِيُخْطِئَك.',
      prompt:'A child resting calmly under an umbrella in gentle rain, trust and peace, warm soft colors' },
  ],
  moral:'كُلُّ شَيْءٍ بِقَدَرِ اللهِ الْحَكِيم، فَأَعْمَلُ وَأَثِقُ وَأَرْتَاح. ☂️',
  game:{ type:'maze', title:'ثِقْ بِالرُّبَّانِ الْحَكِيم! أَوْصِلِ الطَّائِرَةَ إِلَى الْمَطَار', avatar:'✈️', goal:'🛬', wall:'⛈️', map:['S.#..','..#.#','#...#','..#..','#..#G'] },
  act:{ q:'مَنْ يُدَبِّرُ حَيَاتِي بِعِلْمٍ وَحِكْمَة؟', yay:'أَحْسَنْت! فَأَثِقُ بِتَدْبِيرِهِ وَأَرْتَاح', opts:[
    { e:'💫', t:'اللهُ الْحَكِيمُ رُبَّانُ حَيَاتِي', ok:true },
    { e:'🎲', t:'الصُّدْفَة' },
    { e:'🤷', t:'لَا أَحَد' } ] },
  dua:'رَضِيتُ بِاللهِ رَبًّا، قَدَّرَ اللهُ وَمَا شَاءَ فَعَل' },

{ id:'razzaq', icon:'🌾', color:'#27AE60', title:'الرِّزْقُ الَّذِي يَصِلُ إِلَيْك',
  tag:'الرَّزَّاق',
  pages:[
    { emoji:'🍞', text:'هَلْ خِفْتَ يَوْمًا: مَاذَا لَوْ لَمْ نَجِدْ طَعَامًا؟ اطْمَئِنّ! اللهُ تَكَفَّلَ بِرِزْقِ كُلِّ مَخْلُوق.',
      prompt:'A warm table with bread and fruit and a grateful child, provision and blessing, cozy light' },
    { emoji:'🐦', text:'يُطْعِمُ الطِّفْلَ فِي بَطْنِ أُمِّه، وَالطَّيْرَ فِي عُشِّه، وَالنَّمْلَةَ فِي جُحْرِهَا.',
      prompt:'A bird feeding chicks in a nest and ants gathering food, nature provided for, gentle and warm' },
    { emoji:'🌾', text:'قَالَ النَّبِيُّ ﷺ: يَرْزُقُ الطَّيْرَ تَغْدُو جَائِعَةً وَتَعُودُ شَبْعَى. فَاعْمَلْ وَثِق.',
      prompt:'A bird flying out at dawn over green fields, trust in provision, hopeful morning light' },
    { emoji:'💚', text:'فَلَا تَخَفْ عَلَى رِزْقِك، رِزْقُكَ يَبْحَثُ عَنْكَ كَمَا تَبْحَثُ أَنْتَ عَنْه.',
      prompt:'Gentle rain on abundant orchards heavy with fruit, generous provision, warm golden light' },
  ],
  moral:'الرَّزَّاقُ تَكَفَّلَ بِرِزْقِي، فَأَعْمَلُ وَلَا أَخَاف. 💚',
  game:{ type:'find', title:'اللهُ يَرْزُقُ كُلَّ مَخْلُوق! اجْمَعْ حَبَّاتِ الْقَمْحِ السِّتّ', target:'🌾', count:6, distractors:['🍂','🪨'], size:12 },
  act:{ q:'مَنِ الَّذِي رَزَقَكَ وَأَنْتَ فِي بَطْنِ أُمِّك؟', yay:'أَحْسَنْت! فَلَنْ يَنْسَاكَ الْآن', opts:[
    { e:'🌾', t:'اللهُ الرَّزَّاق', ok:true },
    { e:'🛒', t:'الْمَتْجَر' },
    { e:'🤷', t:'لَا أَحَد' } ] },
  dua:'اللَّهُمَّ يَا رَزَّاقُ ارْزُقْنِي رِزْقًا حَلَالًا طَيِّبًا' },

{ id:'latif', icon:'🌹', color:'#E84393', title:'اللُّطْفُ الْخَفِيّ',
  tag:'اللَّطِيف',
  pages:[
    { emoji:'😢', text:'أَحْيَانًا يَحْدُثُ شَيْءٌ لَا نُحِبُّه، فَنَظُنُّهُ شَرًّا. لَكِنَّ اللهَ اللَّطِيفَ يُخْبِئُ فِيهِ خَيْرًا خَفِيًّا.',
      prompt:'A wrapped gift with a plain outer wrapping hiding a glowing surprise, hidden good, warm' },
    { emoji:'💊', text:'كَالدَّوَاءِ الْمُرِّ يَشْفِي، وَالْجَوْزَةِ قِشْرَتُهَا صُلْبَةٌ وَدَاخِلُهَا لَذِيذ!',
      prompt:'A cracked walnut showing a tasty kernel inside, and a spoon of medicine with a small heart, gentle' },
    { emoji:'🕳️', text:'يُوسُفُ أَلْقَاهُ إِخْوَتُهُ فِي الْبِئْر، فَبَدَا مُصِيبَة — لَكِنَّهَا كَانَتْ طَرِيقَ عِزِّه!',
      prompt:'A well with a soft beam of light rising from it toward a palace, hardship leading to honour, hopeful' },
    { emoji:'🌹', text:'فَثِقْ: خَلْفَ كُلِّ صُعُوبَةٍ لُطْفٌ خَفِيٌّ مِنْ رَبٍّ يُحِبُّك.',
      prompt:'A rose blooming from a thorny stem with soft warm light, beauty from difficulty, tender' },
  ],
  moral:'خَلْفَ كُلِّ صُعُوبَةٍ لُطْفٌ خَفِيٌّ مِنَ اللَّطِيف. 🌹',
  game:{ type:'pairs', title:'صِلْ كُلَّ غِلَافٍ بِمَا يُخْفِيه', pairs:[
    ['💊 الدَّوَاءُ الْمُرّ','يُخْفِي الشِّفَاء'],
    ['🥜 قِشْرَةُ الْجَوْزَة','تُخْفِي لُبًّا لَذِيذًا'],
    ['🕳️ بِئْرُ يُوسُف','كَانَتْ طَرِيقَ عِزِّه'] ] },
  act:{ q:'حَدَثَ لِي شَيْءٌ صَعْب — هَلْ هُوَ شَرٌّ مَحْض؟', yay:'صَحِيح! قَدْ يُخْفِي اللهُ فِيهِ خَيْرًا لَا نَرَاه', opts:[
    { e:'🌹', t:'لَا! خَلْفَهُ لُطْفٌ خَفِيٌّ مِنَ الله', ok:true },
    { e:'😭', t:'نَعَم، لَا خَيْرَ فِيه' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'يَا لَطِيفُ الْطُفْ بِي فِي كُلِّ أَمْرِي' },

{ id:'wakil', icon:'🪂', color:'#0984E3', title:'سَلِّمِ الْأَمْرَ لِمَنْ يُدَبِّر',
  tag:'الْوَكِيل',
  pages:[
    { emoji:'🎒', text:'حِينَ تُسَافِرُ بِالطَّائِرَة، هَلْ تَحْمِلُ حَقِيبَتَكَ الثَّقِيلَةَ عَلَى ظَهْرِكَ طُولَ الرِّحْلَة؟ لَا!',
      prompt:'A traveler handing a heavy suitcase at an airport counter, relief, light and cheerful' },
    { emoji:'🤝', text:'تُسَلِّمُهَا فَيَحْمِلُونَهَا وَتَرْتَاح. فَلِمَاذَا تَحْمِلُ هُمُومَكَ وَحْدَك؟',
      prompt:'A child walking lightly and happily with empty hands, burden lifted, warm bright scene' },
    { emoji:'💙', text:'سَلِّمْ هُمُومَكَ لِلَّهِ الْوَكِيل، الَّذِي يُدَبِّرُ الْكَوْنَ كُلَّهُ بِلَا تَعَب.',
      prompt:'The vast universe of stars turning in gentle harmony, the One who manages all, awe and calm' },
    { emoji:'🪂', text:'وَتَوَكَّلْ عَلَى الْحَيِّ الَّذِي لَا يَمُوت — فَعَنْ أَيِّ شَيْءٍ تَقْلَق؟',
      prompt:'A child gently floating down with a parachute, safe and trusting, calm sky, soft warm light' },
  ],
  moral:'أَعْمَلُ ثُمَّ أُسَلِّمُ أَمْرِي لِلْوَكِيل، فَيَكْفِينِي وَيُدَبِّر. 🪂',
  game:{ type:'sort', title:'مَاذَا يَفْعَلُ الْمُتَوَكِّلُ الذَّكِيّ؟', bins:['تَوَكُّلٌ صَحِيح ✅','خَطَأ 🚫'], items:[
    { e:'📚', t:'يُذَاكِرُ ثُمَّ يَتَوَكَّل', bin:0 },
    { e:'😴', t:'يَنَامُ وَلَا يَعْمَلُ شَيْئًا', bin:1 },
    { e:'🤝', t:'يَأْخُذُ بِالسَّبَبِ وَيَثِقُ بِالله', bin:0 },
    { e:'😰', t:'يَحْمِلُ كُلَّ الْهُمُومِ وَحْدَه', bin:1 } ] },
  act:{ q:'مَاذَا أَفْعَلُ بِهُمُومِيَ الثَّقِيلَة؟', yay:'أَحْسَنْت! أَعْمَلُ ثُمَّ أُسَلِّمُهَا لِلْوَكِيل', opts:[
    { e:'🤝', t:'أُسَلِّمُهَا لِلَّهِ بَعْدَ الْأَخْذِ بِالسَّبَب', ok:true },
    { e:'😰', t:'أَحْمِلُهَا وَحْدِي وَأَقْلَق' },
    { e:'🤷', t:'أَتْرُكُ كُلَّ شَيْء' } ] },
  dua:'حَسْبِيَ اللهُ وَنِعْمَ الْوَكِيل، عَلَيْهِ تَوَكَّلْت' },

{ id:'malaika', icon:'😇', color:'#16A085', title:'الْحُرَّاسُ الَّذِينَ لَا تَرَاهُم',
  tag:'الْمَلَائِكَةُ الْحَفَظَة',
  pages:[
    { emoji:'🛡️', text:'مَعَكَ حُرَّاسٌ لَا تَرَاهُم يَحْفَظُونَكَ بِأَمْرِ الله: إِنَّهُمُ الْمَلَائِكَة!',
      prompt:'A child playing safely with a soft protective glow of light around them, unseen guardians, warm' },
    { emoji:'🌗', text:'يَتَنَاوَبُونَ عَلَيْكَ لَيْلًا وَنَهَارًا، وَيَصْرِفُونَ عَنْكَ أَخْطَارًا كَثِيرَة.',
      prompt:'Gentle wings of light gently shielding a child through day and night, protection, tender warm scene' },
    { emoji:'🦠', text:'مِثْلَ جَيْشِ الْمَنَاعَةِ فِي جِسْمِك: لَا تَرَاهُ لَكِنَّهُ يَحْمِيكَ لَيْلَ نَهَار.',
      prompt:'A friendly illustration of tiny defender cells protecting the body, hidden helpers, bright and gentle' },
    { emoji:'📿', text:'وَدِرْعُكَ الَّذِي يَحْفَظُهُم حَوْلَك: أَذْكَارُ الصَّبَاحِ وَالْمَسَاء.',
      prompt:'A glowing shield of gentle light around a child reading morning dhikr, armour of remembrance, warm' },
  ],
  moral:'اللهُ يَحْرُسُنِي بِمَلَائِكَةٍ مِنْ نُور، وَأَذْكَارِي دِرْعِي. 🛡️',
  game:{ type:'maze', title:'أَنْتَ مَحْرُوسٌ بِأَمْرِ الله! أَوْصِلِ الطِّفْلَ بِأَمَانٍ إِلَى بَيْتِه', avatar:'👦', goal:'🏠', wall:'⚠️', map:['S.#..','.###.','...#.','##...','#..#G'] },
  act:{ q:'مَا دِرْعِي الَّذِي أَلْبَسُهُ كُلَّ صَبَاح؟', yay:'أَحْسَنْت! يَحْفَظُنِي بِإِذْنِ الله', opts:[
    { e:'📿', t:'أَذْكَارُ الصَّبَاحِ وَالْمَسَاء', ok:true },
    { e:'🎮', t:'أَلْعَابِي' },
    { e:'👕', t:'مَلَابِسِي' } ] },
  dua:'بِسْمِ اللهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْء' },

{ id:'akhirah', icon:'⚖️', color:'#B7791F', title:'لَا شَيْءَ يَضِيعُ أَبَدًا',
  tag:'الْإِيمَانُ بِالْيَوْمِ الْآخِر',
  pages:[
    { emoji:'😔', text:'هَلْ شَعَرْتَ بِالظُّلْم؟ أَحَدٌ آذَاكَ وَلَمْ يُعَاقَب، أَوْ عَمِلْتَ خَيْرًا وَلَمْ يَشْكُرْكَ أَحَد؟',
      prompt:'A thoughtful child looking a bit sad but hopeful, wondering about fairness, warm gentle scene' },
    { emoji:'📼', text:'اطْمَئِنّ! لَا شَيْءَ يَضِيعُ عِنْدَ الله. كُلُّ عَمَلٍ مُسَجَّلٌ كَلَقْطَةِ الْإِعَادَة.',
      prompt:'A glowing recording capturing every moment, nothing lost, clear and reassuring illustration' },
    { emoji:'⚖️', text:'يَوْمَ الْقِيَامَةِ تُوضَعُ الْمَوَازِينُ الْعَادِلَة، فَيَأْخُذُ كُلُّ مَظْلُومٍ حَقَّه.',
      prompt:'A perfectly balanced glowing scale of justice under soft light, fairness restored, calm and warm' },
    { emoji:'💚', text:'فَابْتِسَامَتُكَ وَكَلِمَتُكَ الطَّيِّبَةُ مَحْفُوظَة، وَكُلُّ دَمْعَةِ ظُلْمٍ سَتُمْسَح.',
      prompt:'A tear turning into a small glowing star and rising up, comfort and reward, tender warm light' },
  ],
  moral:'لَا شَيْءَ يَضِيعُ، وَالْعَدْلُ الْكَامِلُ آتٍ عِنْدَ اللهِ الْعَدْل. ⚖️',
  game:{ type:'sort', title:'مَاذَا يَحْفَظُهُ اللهُ لِي؟', bins:['مَحْفُوظٌ لَا يَضِيع 💚','لَا يَبْقَى 🚫'], items:[
    { e:'😊', t:'كَلِمَةٌ طَيِّبَة', bin:0 },
    { e:'🤝', t:'مُسَاعَدَةٌ فِي الْخَفَاء', bin:0 },
    { e:'💰', t:'مَالُ الظَّالِمِ الْغَاصِب', bin:1 },
    { e:'🙏', t:'صَبْرِي عَلَى الظُّلْم', bin:0 } ] },
  act:{ q:'هَلْ يَضِيعُ خَيْرِي أَوْ حَقِّي عِنْدَ الله؟', yay:'صَحِيح! كُلُّ شَيْءٍ مَحْفُوظٌ لِيَوْمِ الْعَدْل', opts:[
    { e:'💚', t:'لَا! لَا شَيْءَ يَضِيعُ عِنْدَ الله', ok:true },
    { e:'😞', t:'نَعَم، يَضِيعُ كُلُّهُ' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ لَا تَجْعَلْنِي ظَالِمًا وَلَا مَظْلُومًا، وَارْزُقْنِي الْجَنَّة' },

{ id:'rauf', icon:'💧', color:'#3498DB', title:'مُحِيطُ الرَّحْمَة',
  tag:'الرَّؤُوفُ الرَّحِيم',
  pages:[
    { emoji:'😟', text:'إِذَا أَخْطَأْتَ، يَهْمِسُ الشَّيْطَان: أَفْسَدْتَ كُلَّ شَيْء وَلَنْ يَغْفِرَ اللهُ لَك! هَذَا كَذِبٌ خَطِير.',
      prompt:'A small worried figure with a shadowy whisper nearby, but a warm light of hope shining toward them' },
    { emoji:'💧', text:'قَطْرَةُ حِبْرٍ فِي كُوبٍ تُلَوِّنُه، لَكِنْ فِي مُحِيطٍ هَائِلٍ تَخْتَفِي بِلَا أَثَر!',
      prompt:'A single ink drop dissolving into a vast blue ocean with no trace, mercy vaster than sin, serene' },
    { emoji:'🌊', text:'ذُنُوبُكَ كَقَطْرَةِ حِبْرٍ أَمَامَ مُحِيطِ رَحْمَةِ اللهِ الَّذِي لَا سَاحِلَ لَه.',
      prompt:'An endless calm glowing ocean stretching to the horizon, boundless mercy, warm hopeful light' },
    { emoji:'💚', text:'قَالَ الله: لَا تَقْنَطُوا مِنْ رَحْمَةِ الله، إِنَّ اللهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا. فَلَا تَيْأَس!',
      prompt:'An open door of warm golden light welcoming back a returning figure, forgiveness and hope, tender' },
  ],
  moral:'رَحْمَةُ اللهِ أَوْسَعُ مِنْ ذُنُوبِي، فَأَعُودُ إِلَيْهِ وَلَا أَيْأَس. 💚',
  game:{ type:'find', title:'ارْمِ قَطْرَتَكَ فِي مُحِيطِ الرَّحْمَة! اجْمَعْ قَطَرَاتِ التَّوْبَةِ الْخَمْس', target:'💧', count:5, distractors:['🖤','☁️'], size:12 },
  act:{ q:'أَخْطَأْتُ كَثِيرًا — هَلْ أَيْأَسُ مِنْ رَحْمَةِ الله؟', yay:'أَحْسَنْت! رَحْمَتُهُ أَوْسَعُ مِنْ كُلِّ ذَنْب', opts:[
    { e:'💚', t:'لَا! أَعُودُ إِلَيْهِ وَأَسْتَغْفِر', ok:true },
    { e:'😭', t:'نَعَم، لَا أَمَلَ لِي' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي' },

{ id:'patience', icon:'💎', color:'#9B59B6', title:'الْكَنْزُ دَاخِلَ الشِّدَّة',
  tag:'الْقَدَرُ يَصْنَعُ الْأَبْطَال',
  pages:[
    { emoji:'🏋️', text:'أَحْيَانًا يُقَدِّرُ اللهُ شَيْئًا صَعْبًا نَكْرَهُه، فَنَظُنُّهُ شَرًّا، لَكِنَّ فِيهِ خَيْرًا عَظِيمًا خَفِيًّا.',
      prompt:'A child lifting a small weight with effort and a determined smile, growth through effort, warm' },
    { emoji:'💪', text:'كَالْوَزْنِ الثَّقِيلِ يُقَوِّي الْعَضَلَة، وَالْبَذْرَةِ تَنْشَقُّ فِي الظَّلَامِ لِتَصِيرَ شَجَرَة.',
      prompt:'A seed cracking underground sprouting into a strong tree, transformation, hopeful earthy warm tones' },
    { emoji:'💎', text:'كُلُّ صَبْرٍ يَرْفَعُكَ دَرَجَة، وَيَمْحُو خَطَايَاك، وَيَزْرَعُ فِي قَلْبِكَ قُوَّةً وَحِكْمَة.',
      prompt:'Coal turning into a sparkling diamond under gentle pressure, hardship into treasure, radiant' },
    { emoji:'💚', text:'قَالَ النَّبِيُّ ﷺ: أَمْرُ الْمُؤْمِنِ كُلُّهُ خَيْر! فَهُوَ رَابِحٌ فِي كُلِّ الْأَحْوَال.',
      prompt:'A cheerful child standing strong after a challenge with a warm glow of victory, resilience, uplifting' },
  ],
  moral:'الْقَدَرُ الصَّعْبُ يُخْفِي خَيْرًا، فَأَصْبِرُ وَأَغْنَمُ الْكَنْز. 💎',
  game:{ type:'pairs', title:'صِلْ كُلَّ شِدَّةٍ بِثَمَرَتِهَا', pairs:[
    ['🏋️ الْوَزْنُ الثَّقِيل','عَضَلَةٌ أَقْوَى'],
    ['🌱 الْبَذْرَةُ تَنْشَقّ','شَجَرَةٌ عَظِيمَة'],
    ['💎 الصَّبْرُ عَلَى الْبَلَاء','أَجْرٌ وَرِفْعَة'] ] },
  act:{ q:'حَدَثَ لِي شَيْءٌ صَعْب — مَاذَا أَقُول؟', yay:'أَحْسَنْت! فَخَلْفَ الشِّدَّةِ خَيْرٌ وَكَنْز', opts:[
    { e:'💎', t:'لَعَلَّ فِيهِ خَيْرًا قَدَّرَهُ لِي رَبِّي', ok:true },
    { e:'😩', t:'لِمَاذَا أَنَا؟ حَيَاتِي فَاشِلَة!' },
    { e:'🤷', t:'لَا شَيْء' } ] },
  dua:'اللَّهُمَّ اجْعَلْ لِي فِي كُلِّ قَضَاءٍ خَيْرًا' },

{ id:'muraqaba', icon:'👁️', color:'#6C5CE7', title:'اللهُ يَرَاكَ دَائِمًا',
  tag:'مُرَاقَبَةُ الله',
  pages:[
    { emoji:'🌟', text:'اللهُ يَرَاكَ فِي كُلِّ وَقْت: حِينَ تَلْعَب، وَحِينَ تَنَام، وَحِينَ تَكُونُ وَحْدَكَ وَالْبَابُ مُغْلَق.',
      prompt:'A soft all-seeing warm light gently present in a cozy room, being watched with care, tender' },
    { emoji:'🎁', text:'لَوْ أَعْطَاكَ مُعَلِّمُكَ أَمَانَةً وَقَال: أَنَا أَرَاك، هَلْ تَعْبَثُ بِهَا؟ لَنْ تَجْرُؤ!',
      prompt:'A child carefully guarding a trusted gift box, responsibility and care, warm honest scene' },
    { emoji:'💛', text:'فَالْمُؤْمِنُ الذَّكِيُّ يَتْرُكُ الْخَطَأَ وَلَوْ خَلَا، حَيَاءً مِنَ اللهِ لَا خَوْفًا مِنَ النَّاس.',
      prompt:'A child choosing to return a found wallet with a gentle glow of goodness, honesty, warm light' },
    { emoji:'👁️', text:'فَلَا تَحْتَاجُ رَقِيبًا خَارِجِيًّا، رَقِيبُكَ فِي قَلْبِك: اللهُ يَرَاك.',
      prompt:'A child with hand on heart, aware and sincere, soft warm light of mindfulness, serene' },
  ],
  moral:'اللهُ يَرَانِي دَائِمًا، فَأَسْتَحْيِي مِنْهُ وَأَتْرُكُ الْخَطَأَ وَلَوْ خَلَوْت. 👁️',
  game:{ type:'sort', title:'مَاذَا يَفْعَلُ مَنْ يَعْلَمُ أَنَّ اللهَ يَرَاه؟', bins:['قَلْبٌ مُرَاقِبٌ لِله 💛','قَلْبٌ غَافِل 🚫'], items:[
    { e:'💛', t:'أَرُدُّ الْمَحْفَظَةَ الضَّائِعَة', bin:0 },
    { e:'😈', t:'آخُذُ مَا لَيْسَ لِي فِي الْخَفَاء', bin:1 },
    { e:'🤲', t:'أَصْدُقُ وَلَوْ خَلَوْت', bin:0 },
    { e:'🙈', t:'أُخْطِئُ لِأَنَّ لَا أَحَدَ يَرَانِي', bin:1 } ] },
  act:{ q:'أَنَا وَحْدِي وَلَا أَحَدَ مِنَ النَّاسِ يَرَانِي — مَاذَا أَتَذَكَّر؟', yay:'أَحْسَنْت! فَأَتْرُكُ الْخَطَأَ حَيَاءً مِنْه', opts:[
    { e:'👁️', t:'اللهُ يَرَانِي دَائِمًا', ok:true },
    { e:'🎉', t:'أَفْعَلُ مَا أَشَاء' },
    { e:'🤷', t:'لَا شَيْء' } ] },
  dua:'اللَّهُمَّ ارْزُقْنِي مُرَاقَبَتَكَ فِي السِّرِّ وَالْعَلَن' },

{ id:'risalat', icon:'✉️', color:'#D35400', title:'رَسَائِلُ مِنَ السَّمَاء',
  tag:'الْعِلْمُ وَالْإِيمَانُ مَعًا',
  pages:[
    { emoji:'🌍', text:'حِينَ يَحْدُثُ زِلْزَالٌ أَوْ مَطَرٌ شَدِيد، يَسْأَلُ النَّاس: لِمَاذَا؟',
      prompt:'The Earth from space with gentle weather patterns, wonder and questioning, calm blue and warm' },
    { emoji:'🔔', text:'مِثْلَ جَرَسِ الْمَدْرَسَة: الْعِلْمُ يَشْرَحُ كَيْفَ رَنّ، لَكِنَّ الْمُدِيرَ أَمَرَ بِهِ رِسَالَةً: ادْخُلُوا!',
      prompt:'A friendly school bell ringing with sound waves, a message to gather, bright cheerful illustration' },
    { emoji:'🔬', text:'فَهُنَاكَ أَسْبَابٌ خَلَقَهَا الله (نَأْخُذُ بِالْعِلْم)، لَكِنَّ اللهَ هُوَ الَّذِي أَمَرَهَا.',
      prompt:'A child looking through a microscope with a sense of wonder, science revealing Allah wonders, warm' },
    { emoji:'💚', text:'فَالْأَحْدَاثُ الْكَبِيرَةُ رَسَائِلُ تُذَكِّرُنَا بِاللهِ وَتَدْعُونَا لِلتَّوْبَةِ وَالرَّحْمَة.',
      prompt:'A glowing letter of light descending gently to earth with hearts, a reminder to return, hopeful' },
  ],
  moral:'الْعِلْمُ يُفَسِّرُ «كَيْف»، وَالْإِيمَانُ يُجِيبُ «لِمَاذَا» وَمَنْ وَرَاءَه. 💚',
  game:{ type:'pairs', title:'صِلْ كُلَّ سُؤَالٍ بِمَنْ يُجِيبُه', pairs:[
    ['🔬 «كَيْفَ» حَدَث؟','يَشْرَحُهُ الْعِلْمُ وَالْأَسْبَاب'],
    ['💚 «لِمَاذَا» وَمَنْ وَرَاءَه؟','يُجِيبُهُ الْإِيمَانُ بِالله'],
    ['🌍 الْأَحْدَاثُ الْكُبْرَى','رَسَائِلُ تُذَكِّرُ بِالله'] ] },
  act:{ q:'مَاذَا يُجِيبُ عَنْ سُؤَالِ «لِمَاذَا وَمَنْ وَرَاءَ الْأَحْدَاث»؟', yay:'أَحْسَنْت! الْعِلْمُ وَالْإِيمَانُ يَجْتَمِعَانِ لَا يَتَنَاقَضَان', opts:[
    { e:'💚', t:'الْإِيمَانُ بِالله', ok:true },
    { e:'🎲', t:'الصُّدْفَة' },
    { e:'🤷', t:'لَا أَحَد' } ] },
  dua:'اللَّهُمَّ رُدَّ قُلُوبَنَا إِلَيْكَ رَدًّا جَمِيلًا' },

{ id:'dunyadar', icon:'🛫', color:'#0984E3', title:'صَالَةُ الِانْتِظَار',
  tag:'الدُّنْيَا مَحَطَّةٌ لَا وَطَن',
  pages:[
    { emoji:'🛫', text:'الدُّنْيَا مِثْلُ صَالَةِ انْتِظَارٍ فِي مَطَار: نَجْلِسُ فِيهَا قَلِيلًا ثُمَّ نُسَافِرُ إِلَى وَطَنِنَا الْحَقِيقِيّ.',
      prompt:'A cozy bright airport waiting lounge with a big window and a plane outside, temporary stop, warm' },
    { emoji:'⏳', text:'الْمُسَافِرُ الذَّكِيُّ لَا يَبْنِي بَيْتَهُ فِي الصَّالَة، بَلْ يَتَجَهَّزُ لِرِحْلَتِه.',
      prompt:'A traveler packing a bag purposefully in a lounge, preparing for a journey, focused and warm' },
    { emoji:'🎒', text:'فَلَا نَحْزَنُ إِنْ فَاتَنَا شَيْءٌ صَغِيرٌ فِي الصَّالَة، فَالْوَطَنُ الْجَمِيلُ أَمَامَنَا.',
      prompt:'A child looking hopefully out an airport window toward a bright horizon, anticipation, warm light' },
    { emoji:'🌸', text:'وَطَنُنَا الْحَقِيقِيُّ الْجَنَّة! فَنَجْمَعُ فِي الدُّنْيَا زَادَ الْخَيْرِ لِرِحْلَتِنَا.',
      prompt:'A beautiful glowing paradise garden seen through a doorway of light, the true home, serene and warm' },
  ],
  moral:'الدُّنْيَا مَحَطَّةٌ قَصِيرَة، وَوَطَنِيَ الْحَقِيقِيُّ الْجَنَّة. 🌸',
  game:{ type:'sort', title:'مَاذَا يَفْعَلُ الْمُسَافِرُ الذَّكِيّ؟', bins:['يَتَجَهَّزُ لِلْوَطَن ✅','يَنْسَى رِحْلَتَه 🚫'], items:[
    { e:'🎒', t:'يَجْمَعُ زَادَ الْخَيْر', bin:0 },
    { e:'🏗️', t:'يَبْنِي بَيْتَهُ فِي الصَّالَة', bin:1 },
    { e:'🕌', t:'يُصَلِّي وَيَعْمَلُ صَالِحًا', bin:0 },
    { e:'😤', t:'يَتَعَلَّقُ بِكُلِّ شَيْءٍ زَائِل', bin:1 } ] },
  act:{ q:'مَا هِيَ الدُّنْيَا بِالنِّسْبَةِ لِلْمُؤْمِن؟', yay:'أَحْسَنْت! نَتَزَوَّدُ فِيهَا لِلْوَطَنِ الْبَاقِي', opts:[
    { e:'🛫', t:'مَحَطَّةُ انْتِظَارٍ قَصِيرَة', ok:true },
    { e:'🏠', t:'وَطَنٌ دَائِمٌ نَبْقَى فِيه' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ اجْعَلِ الدُّنْيَا فِي أَيْدِينَا لَا فِي قُلُوبِنَا' },

{ id:'reunion', icon:'🤗', color:'#E84393', title:'لِقَاءُ الْأَحِبَّة',
  tag:'نَجْتَمِعُ فِي الْجَنَّة',
  pages:[
    { emoji:'😢', text:'حِينَ نَفْقِدُ مَنْ نُحِبُّ نَحْزَن. لَكِنَّ الْمَوْتَ فِرَاقٌ مُؤَقَّتٌ لَا دَائِم.',
      prompt:'A gentle bittersweet scene of a child looking at the sky remembering someone, hope amid sadness, warm' },
    { emoji:'🌷', text:'الْمُؤْمِنُونَ الَّذِينَ أَحَبُّوا بَعْضَهُم فِي اللهِ يَجْتَمِعُونَ فِي الْجَنَّةِ مِنْ جَدِيد!',
      prompt:'Loved ones joyfully reuniting in a lush paradise garden full of flowers, reunion, radiant warm light' },
    { emoji:'👨‍👩‍👧‍👦', text:'نَجْلِسُ مَعَ آبَائِنَا وَأَحْبَابِنَا، لَا حُزْنَ وَلَا فِرَاقَ وَلَا مَوْتَ أَبَدًا.',
      prompt:'A happy family together in a beautiful garden under a warm sky, togetherness forever, tender' },
    { emoji:'💞', text:'فَالْوَدَاعُ الْحَقِيقِيُّ غَيْرُ مَوْجُودٍ فِي قَامُوسِ الْمُؤْمِن.',
      prompt:'Two hands reaching and joining with a soft heart of light between them, eternal reunion, warm' },
  ],
  moral:'الْمَوْتُ فِرَاقٌ مُؤَقَّت، وَنَجْتَمِعُ بِأَحِبَّتِنَا فِي الْجَنَّة. 💞',
  game:{ type:'find', title:'لِقَاءُ الْأَحِبَّةِ فِي الْجَنَّة! اجْمَعِ الْقُلُوبَ الْمُجْتَمِعَةَ الْخَمْس', target:'💞', count:5, distractors:['☁️','🌷'], size:12 },
  act:{ q:'هَلْ نَلْتَقِي بِمَنْ نُحِبُّ بَعْدَ الْمَوْت؟', yay:'صَحِيح! يَجْتَمِعُ الْمُؤْمِنُونَ فِي الْجَنَّة', opts:[
    { e:'💞', t:'نَعَم! نَجْتَمِعُ فِي الْجَنَّة', ok:true },
    { e:'😭', t:'لَا، فِرَاقٌ أَبَدِيّ' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ اجْمَعْنَا بِمَنْ نُحِبُّ فِي جَنَّتِكَ لَا نَفْتَرِق' },

{ id:'seeingallah', icon:'✨', color:'#F1C40F', title:'أَعْظَمُ نَعِيم',
  tag:'رُؤْيَةُ اللهِ فِي الْجَنَّة',
  pages:[
    { emoji:'🌸', text:'فِي الْجَنَّةِ نِعَمٌ كَثِيرَة: أَنْهَارٌ وَقُصُورٌ وَفَاكِهَةٌ لَا تَنْقَطِع.',
      prompt:'A dazzling paradise garden with rivers and golden palaces and endless fruit, abundant bliss, radiant' },
    { emoji:'✨', text:'لَكِنَّ أَعْظَمَ نَعِيمٍ عَلَى الْإِطْلَاقِ شَيْءٌ لَا يَصْنَعُهُ ذَهَب.',
      prompt:'A gentle glorious light glowing above a paradise scene, something beyond all treasures, awe' },
    { emoji:'😊', text:'إِنَّهُ النَّظَرُ إِلَى وَجْهِ اللهِ الْكَرِيم! وُجُوهٌ يَوْمَئِذٍ نَاضِرَةٌ إِلَى رَبِّهَا نَاظِرَة.',
      prompt:'Radiant joyful faces of light looking upward toward a warm glorious light, the greatest joy, serene' },
    { emoji:'💛', text:'فَنَدْعُو اللهَ أَنْ يَرْزُقَنَا لَذَّةَ النَّظَرِ إِلَى وَجْهِه.',
      prompt:'Hands raised in dua under a warm heavenly glow, longing for the greatest gift, tender and bright' },
  ],
  moral:'أَجْمَلُ مَا فِي الْجَنَّةِ النَّظَرُ إِلَى وَجْهِ اللهِ الْكَرِيم. ✨',
  game:{ type:'pairs', title:'صِلْ كُلَّ نَعِيمٍ بِوَصْفِه', pairs:[
    ['🏰 الْقُصُور','مِنْ نَعِيمِ الْجَنَّة'],
    ['🍇 الْفَاكِهَة','لَا تَنْقَطِعُ أَبَدًا'],
    ['✨ رُؤْيَةُ وَجْهِ الله','أَعْظَمُ النَّعِيمِ كُلِّه'] ] },
  act:{ q:'مَا أَعْظَمُ نَعِيمٍ فِي الْجَنَّة؟', yay:'أَحْسَنْت! أَعْظَمُ مِنْ كُلِّ الْقُصُورِ وَالْأَنْهَار', opts:[
    { e:'✨', t:'النَّظَرُ إِلَى وَجْهِ اللهِ الْكَرِيم', ok:true },
    { e:'🍔', t:'الطَّعَامُ فَقَط' },
    { e:'🎮', t:'اللَّعِبُ فَقَط' } ] },
  dua:'اللَّهُمَّ إِنِّي أَسْأَلُكَ لَذَّةَ النَّظَرِ إِلَى وَجْهِك' },

{ id:'rusulpath', icon:'🕋', color:'#16A085', title:'الْقَافِلَةُ الْوَاحِدَة',
  tag:'عَلَى طَرِيقِ كُلِّ الرُّسُل',
  pages:[
    { emoji:'🕋', text:'كُلُّ الْأَنْبِيَاءِ — نُوحٌ وَإِبْرَاهِيمُ وَمُوسَى وَعِيسَى وَمُحَمَّدٌ ﷺ — سَارُوا فِي قَافِلَةٍ وَاحِدَة.',
      prompt:'A caravan of glowing lanterns traveling together across a desert toward one destination, unity, warm' },
    { emoji:'💚', text:'وَرِسَالَتُهُم وَاحِدَة: اعْبُدُوا اللهَ وَحْدَهُ لَا شَرِيكَ لَه.',
      prompt:'One radiant guiding star above a long path, one message across time, warm gold and teal' },
    { emoji:'🤝', text:'فَنَحْنُ نُحِبُّهُم جَمِيعًا وَنُؤْمِنُ بِهِم كُلِّهِم، لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِنْ رُسُلِه.',
      prompt:'Many lanterns joined by one beam of light along a shared road, brotherhood of prophets, warm' },
    { emoji:'🧭', text:'وَنَحْنُ نَسِيرُ فِي نَفْسِ الْقَافِلَةِ نَحْوَ اللهِ، فَلَسْنَا وَحْدَنَا فِي الطَّرِيق.',
      prompt:'A child joining a caravan of light on a path toward a warm horizon, belonging, hopeful journey' },
  ],
  moral:'أُومِنُ بِالرُّسُلِ كُلِّهِم، وَأَسِيرُ فِي قَافِلَتِهِمُ الْوَاحِدَةِ نَحْوَ الله. 🧭',
  game:{ type:'order', title:'رَتِّبْ قَافِلَةَ الرُّسُلِ بِالتَّرْتِيب', items:[
    { e:'🚢', t:'نُوح' },
    { e:'🔥', t:'إِبْرَاهِيم' },
    { e:'🌊', t:'مُوسَى' },
    { e:'🕊️', t:'عِيسَى' },
    { e:'🕋', t:'مُحَمَّدٌ ﷺ' } ] },
  act:{ q:'مَا رِسَالَةُ كُلِّ الْأَنْبِيَاء؟', yay:'أَحْسَنْت! رِسَالَةٌ وَاحِدَةٌ عَبْرَ الزَّمَن', opts:[
    { e:'💚', t:'اعْبُدُوا اللهَ وَحْدَه', ok:true },
    { e:'💰', t:'اجْمَعُوا الْمَال' },
    { e:'👑', t:'كُلٌّ دِينٌ مُخْتَلِف' } ] },
  dua:'رَبَّنَا آمَنَّا بِمَا أَنْزَلْتَ وَاتَّبَعْنَا الرَّسُول' },

{ id:'sakeenah', icon:'🏰', color:'#1E8449', title:'حِصْنُ السَّكِينَة',
  tag:'ثَمَرَةُ الْأَمَانِ بِالله',
  pages:[
    { emoji:'🏰', text:'بَنَيْنَا مَعًا حِصْنَ أَمَانِك! أَرْكَانُ الْإِيمَانِ صَارَتْ جُدْرَانًا تَحْمِي قَلْبَك.',
      prompt:'A strong beautiful fortress glowing warmly on a hill under a peaceful sky, safety and completion, radiant' },
    { emoji:'💙', text:'لَا تَخَافُ الْغَد، لِأَنَّ رَبَّكَ الْحَكِيمَ يُدَبِّرُه. وَلَا تَحْزَنُ، لِأَنَّ اللهَ مَعَك.',
      prompt:'A calm content child sitting peacefully inside a warm glowing space, tranquility, serene warm light' },
    { emoji:'🕊️', text:'وَلَا تَيْأَسُ، لِأَنَّ رَحْمَتَهُ وَاسِعَة. وَلَا تَحْسُدُ، لِأَنَّ لِكُلٍّ نَصِيبَهُ الْمَكْتُوب.',
      prompt:'A white dove of peace flying gently over a warm bright landscape, serenity and hope, uplifting' },
    { emoji:'💚', text:'هَذِهِ هِيَ السَّكِينَة: قَلْبٌ مُطْمَئِنٌّ بِاللهِ لَا يَعْرِفُ الْقَلَق.',
      prompt:'A glowing peaceful heart radiating calm light within a fortress, the fruit of faith, warm and serene' },
  ],
  moral:'ثَمَرَةُ إِيمَانِي بِالله: قَلْبٌ مُطْمَئِنٌّ فِي حِصْنٍ لَا تَهْزِمُهُ الْعَوَاصِف. 💚',
  game:{ type:'pairs', title:'صِلْ كُلَّ رُكْنٍ بِثَمَرَتِه', pairs:[
    ['🤲 اللهُ مَعِي','لَا وَحْدَةَ وَلَا خَوْف'],
    ['🧭 الْإِيمَانُ بِالْقَدَر','لَا قَلَقَ عَلَى الْغَد'],
    ['🌊 رَحْمَةُ الله','لَا يَأْسَ أَبَدًا'],
    ['⚖️ الْيَوْمُ الْآخِر','لَا حَسَدَ، لِكُلٍّ نَصِيبُه'] ] },
  act:{ q:'مَا أَعْظَمُ ثَمَرَةٍ لِلْإِيمَانِ بِالله؟', yay:'أَحْسَنْت! قَلْبٌ مُطْمَئِنٌّ لَا يَعْرِفُ الْقَلَق', opts:[
    { e:'💚', t:'السَّكِينَةُ وَطُمَأْنِينَةُ الْقَلْب', ok:true },
    { e:'💰', t:'الْمَالُ الْكَثِير' },
    { e:'🏆', t:'كَأْسٌ ذَهَبِيّ' } ] },
  dua:'اللَّهُمَّ أَنْزِلْ عَلَى قَلْبِيَ السَّكِينَةَ وَالطُّمَأْنِينَة' },

]};
