/* corners/stories/minaret-little/lab.js — مختبر الحقائق للصغار (٣–٦)
   ١٠ حكايات مبسّطة من محطات «مختبر كشف الحقائق» في منارة العقيدة — أدلّةٌ ذكيّة بأمثلةٍ محسوسة.
   كل صفحة: emoji (بديل مؤقت) + text (سطران سهلان) + prompt (وصف صورة إنجليزي لتوليدها لاحقاً). */
window.MINARET_LITTLE = window.MINARET_LITTLE || {};
window.MINARET_LITTLE.lab = {
  id:'lab', icon:'🧪', color:'#8E44AD', title:'مُخْتَبَرُ الْحَقَائِق', tag:'أَسْئِلَةٌ وَأَجْوِبَةٌ ذَكِيَّة',
  stories:[

{ id:'speedometer', icon:'🚗', color:'#E74C3C', title:'عَدَّادُ السُّرْعَةِ الْمَكْسُور',
  tag:'إِنْكَارُ الْقَاعِدَةِ لَا يُلْغِيهَا',
  pages:[
    { emoji:'🚗', text:'بَعْضُ النَّاسِ يَقُولُونَ: لَا نُرِيدُ قَوَاعِدَ وَلَا حِسَابًا! نُرِيدُ أَنْ نَفْعَلَ كُلَّ مَا نَشْتَهِي.',
      prompt:'A cartoon car speeding on a road with warning signs, playful but a bit reckless mood, bright colors' },
    { emoji:'🧰', text:'مِثْلُ سَائِقٍ كَسَرَ عَدَّادَ السُّرْعَة، وَقَال: الْآنَ لَا حُدُودَ لِلسُّرْعَة!',
      prompt:'A broken car speedometer with a cracked glass, close-up, dramatic but cartoonish' },
    { emoji:'🧱', text:'لَكِنَّ الْحُدُودَ لَمْ تَخْتَفِ! هُوَ فَقَطْ أَغْلَقَ عَيْنَيْه، وَسَيَرْتَطِمُ فِي النِّهَايَة.',
      prompt:'A cartoon car gently bumping into a soft wall, stars around, harmless humorous crash' },
    { emoji:'💡', text:'مَنْ يُنْكِرُ اللهَ لِيَهْرُبَ مِنَ الْحِسَاب، فَالْحِسَابُ لَنْ يَخْتَفِيَ أَبَدًا.',
      prompt:'A glowing lightbulb over an open road, idea and realization moment, warm light' },
  ],
  moral:'أَتَعَلَّمُ الْفَرْقَ بَيْنَ «الْحَقّ» وَ«مَا أَشْتَهِي». 💡',
  game:{ type:'sort', title:'أَيُّهُمَا حَقٌّ نَتَّبِعُه، وَأَيُّهُمَا مُجَرَّدُ رَغْبَة؟', bins:['حَقٌّ نَتَّبِعُه ✅','مُجَرَّدُ رَغْبَة 🙈'], items:[
    { e:'📏', t:'قَاعِدَةُ الْمُرُورِ تَحْمِينَا', bin:0 },
    { e:'😴', t:'لَا أُرِيدُ النَّوْمَ مُبَكِّرًا', bin:1 },
    { e:'🪥', t:'تَنْظِيفُ الْأَسْنَانِ مُفِيد', bin:0 },
    { e:'🍬', t:'أُرِيدُ حَلْوَى بِلَا نِهَايَة', bin:1 } ] },
  act:{ q:'إِذَا كَسَرَ السَّائِقُ الْعَدَّاد، هَلْ تَخْتَفِي حُدُودُ السُّرْعَة؟', yay:'صَحِيح! إِنْكَارُ الْقَاعِدَةِ لَا يُلْغِيهَا', opts:[
    { e:'🙅', t:'لَا! تَبْقَى مَوْجُودَةً وَسَيَرْتَطِمُ بِهَا', ok:true },
    { e:'🎉', t:'نَعَم، صَارَ حُرًّا تَمَامًا' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ أَرِنَا الْحَقَّ حَقًّا وَارْزُقْنَا اتِّبَاعَه' },

{ id:'whisper', icon:'😈', color:'#8E44AD', title:'مَنْ خَلَقَ الله؟!',
  tag:'الْخَالِقُ لَا يُخْلَق',
  pages:[
    { emoji:'👂', text:'أَحْيَانًا يَأْتِي هَمْسٌ فِي الْقَلْب: مَنْ خَلَقَ هَذَا؟ مَنْ خَلَقَ ذَاك؟ حَتَّى يَقُول: مَنْ خَلَقَ اللهَ؟!',
      prompt:'A curious child with a big question mark above their head, cozy room, wondering expression from behind' },
    { emoji:'🛑', text:'هَذَا السُّؤَالُ خَطَأ! لِأَنَّ كَلِمَةَ «خَالِق» تَعْنِي مَنْ لَا يَحْتَاجُ مَنْ يَخْلُقُه.',
      prompt:'A gentle stop sign glowing softly, simple clear illustration, calm colors' },
    { emoji:'🎨', text:'مِثْلَ أَنْ تَسْأَل: مَا لَوْنُ الصَّوْت؟ أَوْ كَمْ يَزِنُ الرَّقَمُ سَبْعَة؟ سُؤَالٌ لَا مَعْنَى لَه.',
      prompt:'A funny surreal image of a musical note with a color palette and question marks, playful and abstract' },
    { emoji:'💜', text:'هَذَا الْهَمْسُ مِنَ الشَّيْطَان! لَا نُجَادِلُه، بَلْ نَقُول: آمَنْتُ بِالله، وَنَنْشَغِلُ بِالنَّافِع.',
      prompt:'A purple Islamic geometric shield pattern glowing gently, protection and calm' },
  ],
  moral:'إِذَا جَاءَ هَمْسُ الشَّكِّ أَقُول: آمَنْتُ بِالله! 💜',
  game:{ type:'maze', title:'أَغْلِقْ بَابَ الْوَسْوَسَةِ وَصِلْ إِلَى قَلْبٍ مُطْمَئِنّ', avatar:'👦', goal:'💚', wall:'😈', map:['S.#..','.###.','...#.','##...','#..#G'] },
  act:{ q:'مَاذَا نَقُولُ حِينَ يَأْتِي هَمْسُ: مَنْ خَلَقَ الله؟', yay:'أَحْسَنْت! نَسْتَعِيذُ وَنَقُول: آمَنْتُ بِالله', opts:[
    { e:'💜', t:'آمَنْتُ بِالله وَأَعُوذُ بِالله', ok:true },
    { e:'🗣️', t:'نُجَادِلُ الشَّيْطَانَ طَوِيلًا' },
    { e:'😟', t:'نَقْلَقُ وَنَخَاف' } ] },
  dua:'أَعُوذُ بِاللهِ مِنَ الشَّيْطَانِ الرَّجِيم، آمَنْتُ بِالله' },

{ id:'diver', icon:'🤿', color:'#2980B9', title:'الْغَوَّاصُ بِلَا أُكْسِجِين',
  tag:'نَحْنُ الْفُقَرَاءُ إِلَى الله',
  pages:[
    { emoji:'🤿', text:'تَخَيَّلْ غَوَّاصًا نَزَعَ أُنْبُوبَةَ الْأُكْسِجِينِ وَقَال: أَنَا حُرّ، لَا أَحْتَاجُ الْهَوَاء!',
      prompt:'A cute cartoon diver deep underwater surrounded by colorful fish, oxygen tank on back, bright ocean' },
    { emoji:'😨', text:'مَاذَا سَيَحْدُث؟ سَيَخْتَنِقُ فَوْرًا! لِأَنَّهُ يَحْتَاجُ الْأُكْسِجِينَ فِي كُلِّ لَحْظَة.',
      prompt:'A worried cartoon diver reaching for air bubbles underwater, gentle suspense, no danger shown harshly' },
    { emoji:'🔋', text:'حَتَّى أَغْلَى هَاتِفٍ يَحْتَاجُ الشَّحْن، وَالزَّرْعُ يَحْتَاجُ الْمَاء. كُلُّ شَيْءٍ مُحْتَاج.',
      prompt:'A phone charging and a plant being watered side by side, simple clean illustration, warm light' },
    { emoji:'💙', text:'وَنَحْنُ نَحْتَاجُ اللهَ فِي كُلِّ نَفَس! اللهُ الْغَنِيُّ لَا يَحْتَاجُ أَحَدًا.',
      prompt:'A child taking a deep breath in a sunlit garden, grateful and peaceful, warm glow' },
  ],
  moral:'أَحْتَاجُ اللهَ فِي كُلِّ نَفَس، وَهُوَ الْغَنِيُّ عَنِّي. 💙',
  game:{ type:'pairs', title:'صِلْ كُلَّ شَيْءٍ بِمَا يَحْتَاجُه', pairs:[
    ['📱 الْهَاتِف','🔌 يَحْتَاجُ الشَّحْن'],
    ['🐟 السَّمَكَة','🌊 تَحْتَاجُ الْبَحْر'],
    ['🧍 الْإِنْسَان','💙 يَحْتَاجُ اللهَ ثُمَّ الْهَوَاء'] ] },
  act:{ q:'هَلْ يَحْتَاجُ اللهُ إِلَيْنَا؟', yay:'صَحِيح! هُوَ الْغَنِيُّ وَنَحْنُ الْفُقَرَاءُ إِلَيْه', opts:[
    { e:'🙅', t:'لَا! اللهُ غَنِيٌّ وَنَحْنُ نَحْتَاجُه', ok:true },
    { e:'🤝', t:'نَعَم، يَحْتَاجُنَا مِثْلَنَا' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'يَا رَبِّ أَنَا أَحْتَاجُكَ دَائِمًا فَلَا تَتْرُكْنِي وَحْدِي' },

{ id:'referee', icon:'⚽', color:'#27AE60', title:'مُبَارَاةٌ بِلَا حَكَم',
  tag:'مِنْ أَيْنَ يَأْتِي الْعَدْل؟',
  pages:[
    { emoji:'⚽', text:'تَخَيَّلْ مُبَارَاةَ كُرَةٍ بِلَا حَكَمٍ وَلَا قَوَانِين! لَاعِبٌ يُمْسِكُ الْكُرَةَ بِيَدِهِ وَيَجْرِي.',
      prompt:'A chaotic funny cartoon football match, players in a jumble, no referee, playful mess' },
    { emoji:'😵‍💫', text:'وَآخَرُ يَدْفَعُ صَدِيقَه، وَالْكُلُّ يَصِيح: أَنَا الْفَائِز! تَتَحَوَّلُ الْمُبَارَاةُ إِلَى فَوْضَى.',
      prompt:'Cartoon players tangled with dizzy spirals above them, chaotic but harmless, bright field' },
    { emoji:'⚖️', text:'قَلْبُكَ يَعْرِفُ أَنَّ هَذَا ظُلْم! وَمِنْ أَيْنَ جَاءَ شُعُورُكَ بِالْعَدْل؟',
      prompt:'A glowing golden balance scale under soft light, symbol of fairness, calm and clear' },
    { emoji:'💚', text:'اللهُ الْعَدْلُ وَضَعَ قَوَانِينَ لِيَحْمِيَنَا، وَغَرَسَ فِي قَلْبِنَا مَعْرِفَةَ الْخَيْرِ وَالشَّرّ.',
      prompt:'A fair happy football match with a smiling referee, orderly and joyful, sunny day' },
  ],
  moral:'شُعُورِي بِالْعَدْلِ هَدِيَّةٌ مِنَ اللهِ الْعَدْل. ⚖️',
  game:{ type:'sort', title:'ضَعْ كُلَّ حَالٍ فِي مَكَانِهَا', bins:['بِلَا حَكَم: فَوْضَى 😵‍💫','بِحَكَمٍ عَادِل: نِظَام 💚'], items:[
    { e:'🤾', t:'الْكُلُّ يَأْخُذُ بِالْقُوَّة', bin:0 },
    { e:'🤝', t:'كُلٌّ يَأْخُذُ حَقَّهُ بِعَدْل', bin:1 },
    { e:'😡', t:'الْقَوِيُّ يَظْلِمُ الضَّعِيف', bin:0 },
    { e:'⚖️', t:'حِسَابٌ عَادِلٌ لِلْجَمِيع', bin:1 } ] },
  act:{ q:'لِمَاذَا نَحْتَاجُ إِلَى حَكَمٍ فِي الْمُبَارَاة؟', yay:'أَحْسَنْت! وَاللهُ الْعَدْلُ يَحْكُمُ الْكَوْنَ كُلَّه', opts:[
    { e:'💚', t:'لِيَكُونَ هُنَاكَ عَدْلٌ وَنِظَام', ok:true },
    { e:'🎈', t:'لِلزِّينَةِ فَقَط' },
    { e:'🙅', t:'لَا نَحْتَاجُه' } ] },
  dua:'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ أَنْ أَظْلِمَ أَوْ أُظْلَم' },

{ id:'frog', icon:'🐸', color:'#16A085', title:'الْأَمِيرَةُ وَالضِّفْدَع',
  tag:'الصُّدْفَةُ لَا تَصْنَعُ الْعَجَائِب',
  pages:[
    { emoji:'🐸', text:'فِي قِصَّةِ الْخَيَال، قَبَّلَتِ الْأَمِيرَةُ ضِفْدَعًا فَصَارَ أَمِيرًا! كُلُّنَا نَضْحَكُ وَنَعْرِفُ أَنَّهَا خَيَال.',
      prompt:'A whimsical fairytale scene of a green frog with a tiny crown beside a sparkle, storybook style, playful' },
    { emoji:'🐟', text:'وَبَعْضُهُمْ يَقُول: سَمَكَةٌ صَارَتْ زَاحِفًا ثُمَّ طَائِرًا ثُمَّ إِنْسَانًا بِالصُّدْفَة!',
      prompt:'A playful cartoon line of a fish, a lizard, a bird and a question mark, curious and light' },
    { emoji:'🚗', text:'لَوْ تَرَكْنَا سَيَّارَةً مِلْيَارَ سَنَة، هَلْ تَصِيرُ طَائِرَةً وَحْدَهَا؟ لَا! سَتَصْدَأُ فَقَط.',
      prompt:'An old rusty car in a garage with cobwebs, dust and a clock showing long time passing, gentle humor' },
    { emoji:'💜', text:'الصُّدْفَةُ تَهْدِمُ وَلَا تَبْنِي! اللهُ الْخَالِقُ خَلَقَ كُلَّ نَوْعٍ مُتْقَنًا مِنَ الْبِدَايَة.',
      prompt:'Beautiful distinct animals each perfectly designed, arranged like a gallery, purple and gold frame' },
  ],
  moral:'كُلُّ مَخْلُوقٍ مُتْقَنٌ صَنَعَهُ اللهُ الْخَالِق، لَا الصُّدْفَة. 💜',
  game:{ type:'pairs', title:'صِلْ كُلَّ قِصَّةٍ بِـ«سِحْرِهَا» الْخَيَالِيّ', pairs:[
    ['👸 الْأَمِيرَةُ وَالضِّفْدَع','💋 سِحْرُهَا: قُبْلَة'],
    ['🐟 سَمَكَةٌ تَصِيرُ إِنْسَانًا','⏳ سِحْرُهَا: وَقْتٌ طَوِيل'],
    ['🦋 كُلُّ كَائِنٍ مُتْقَن','💚 خَلْقُ اللهِ الْحَكِيم'] ] },
  act:{ q:'هَلْ تَصِيرُ السَّيَّارَةُ طَائِرَةً وَحْدَهَا مَعَ الْوَقْت؟', yay:'صَحِيح! الصُّدْفَةُ تَهْدِمُ، وَالْخَالِقُ يَبْنِي', opts:[
    { e:'🙅', t:'لَا! سَتَصْدَأُ وَتَتَفَكَّك', ok:true },
    { e:'✈️', t:'نَعَم، تَطِيرُ وَحْدَهَا' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'سُبْحَانَ الْخَالِقِ الْبَارِئِ الْمُصَوِّر' },

{ id:'lego', icon:'🧩', color:'#D4A017', title:'الْقِطَعُ الْمَفْقُودَة',
  tag:'الْكَائِنَاتُ ظَهَرَتْ كَامِلَة',
  pages:[
    { emoji:'🧱', text:'تَخَيَّلْ وَجَدْتَ سَيَّارَةَ لِيجو كَامِلَةً مُتْقَنَة. فَقَالَ أَحَدُهُم: تَطَوَّرَتْ وَحْدَهَا خُطْوَةً خُطْوَة!',
      prompt:'A complete colorful Lego car on a table, neat and well built, bright childrens setting' },
    { emoji:'❓', text:'ستَسْأَلُهُ فَوْرًا: أَيْنَ الْقِطَعُ النَّاقِصَةُ الَّتِي تُثْبِتُ كَلَامَك؟ فَلَا يَجِدُ شَيْئًا!',
      prompt:'Scattered puzzle pieces with a big question mark, some missing, curious mood' },
    { emoji:'⛏️', text:'وَالْعُلَمَاءُ حَفَرُوا الْأَرْضَ فِي كُلِّ مَكَان، فَوَجَدُوا الْكَائِنَاتِ كَامِلَةً فَجْأَة!',
      prompt:'Paleontologists digging and finding complete fossil skeletons, bright discovery scene, cartoon style' },
    { emoji:'💛', text:'لَا أَنْصَافَ وَلَا أَرْبَاع! هَذَا يُثْبِتُ أَنَّ اللهَ أَوْجَدَهَا بِكَلِمَةِ: كُنْ فَيَكُون.',
      prompt:'A radiant word of light Kun appearing over creation forming instantly, golden glow, awe' },
  ],
  moral:'الْأَشْيَاءُ الْمُتْقَنَةُ الْكَامِلَةُ تَأْتِي مِنْ صَانِعٍ حَكِيم. 💛',
  game:{ type:'find', title:'الْأَحَافِيرُ كَامِلَة! جِدْ قِطَعَ اللِّيجو الْأَرْبَعَ الْمُتَشَابِهَة', target:'🧱', count:4, distractors:['🔩','🪨'], size:12 },
  act:{ q:'كَيْفَ وَجَدَ الْعُلَمَاءُ الْكَائِنَاتِ فِي الْأَرْض؟', yay:'صَحِيح! كَامِلَةً، لَا حَلَقَاتٍ نَاقِصَة', opts:[
    { e:'✅', t:'كَامِلَةً مُتْقَنَةً فَجْأَة', ok:true },
    { e:'🧩', t:'أَنْصَافًا وَأَرْبَاعًا كَثِيرَة' },
    { e:'🤷', t:'لَمْ يَجِدُوا شَيْئًا' } ] },
  dua:'سُبْحَانَ مَنْ أَحْسَنَ كُلَّ شَيْءٍ خَلَقَه' },

{ id:'halfeye', icon:'👁️', color:'#9B59B6', title:'نِصْفُ الْعَيْنِ لَا يُبْصِر',
  tag:'التَّصْمِيمُ يَحْتَاجُ كُلَّ أَجْزَائِه',
  pages:[
    { emoji:'👁️', text:'الْعَيْنُ تَحْتَاجُ كُلَّ أَجْزَائِهَا مَعًا: الْعَدَسَةَ وَالْعَصَبَ وَالدِّمَاغَ لِتَرَى.',
      prompt:'A friendly diagram of an eye with glowing connected parts, educational childrens style, soft colors' },
    { emoji:'🌉', text:'مِثْلَ الْجِسْر: هَلْ يَنْفَعُكَ نِصْفُ جِسْرٍ فَوْقَ نَهْر؟ لَا! سَتَقَعُ فِي الْمَاء.',
      prompt:'A half-built bridge over a river ending in mid-air, cartoon style, gentle caution' },
    { emoji:'🧩', text:'إِذَا نَقَصَ جُزْءٌ وَاحِدٌ لَا تَرَى شَيْئًا! لَا بُدَّ أَنْ تُوجَدَ كُلُّهَا دُفْعَةً وَاحِدَة.',
      prompt:'Puzzle pieces clicking together to form a complete glowing eye, satisfying assembly, warm light' },
    { emoji:'💜', text:'هَذَا سَهْلٌ عَلَى اللهِ الْحَكِيمِ الَّذِي صَمَّمَ الْعَيْنَ كَامِلَةً مِنْ أَوَّلِ لَحْظَة.',
      prompt:'A child looking at a beautiful view with bright happy eyes, gratitude, warm sunny scene from behind' },
  ],
  moral:'الْعَيْنُ الْكَامِلَةُ دَلِيلٌ عَلَى مُصَمِّمٍ حَكِيم. 💜',
  game:{ type:'order', title:'رَتِّبْ كَيْفَ تَعْمَلُ الْعَيْنُ لِنَرَى', items:[
    { e:'💡', t:'يَدْخُلُ الضَّوْء' },
    { e:'🔵', t:'تُجَمِّعُهُ الْعَدَسَة' },
    { e:'🔌', t:'يَحْمِلُهُ الْعَصَب' },
    { e:'🧠', t:'يَفْهَمُهُ الدِّمَاغ' } ] },
  act:{ q:'مَاذَا يَحْدُثُ لَوْ نَقَصَ جُزْءٌ وَاحِدٌ مِنَ الْعَيْن؟', yay:'صَحِيح! لِذَلِكَ خَلَقَهَا اللهُ كَامِلَة', opts:[
    { e:'🙈', t:'لَا نَرَى شَيْئًا', ok:true },
    { e:'👀', t:'نَرَى أَفْضَل' },
    { e:'🤷', t:'لَا فَرْق' } ] },
  dua:'الْحَمْدُ لِلَّهِ الَّذِي جَعَلَ لِيَ السَّمْعَ وَالْبَصَر' },

{ id:'code', icon:'💾', color:'#2C7BE5', title:'شِفْرَةُ الْحَيَاة',
  tag:'الْبَرْنَامَجُ يَحْتَاجُ كَاتِبًا',
  pages:[
    { emoji:'🧬', text:'فِي كُلِّ خَلِيَّةٍ مِنْ جِسْمِكَ كِتَابٌ سِرِّيٌّ عَجِيب، يَأْمُرُ جِسْمَكَ كَيْفَ يَنْمُو وَيَشْفَى.',
      prompt:'A glowing colorful DNA helix like a book of light inside a cell, wondrous and clean, blue and gold' },
    { emoji:'⌨️', text:'قَالَ بَعْضُهُم: هَذَا الْبَرْنَامَجُ كَتَبَ نَفْسَهُ بِالصُّدْفَة! فَجَرِّبْ:',
      prompt:'A keyboard with sparkles, question marks floating, playful curiosity' },
    { emoji:'🙈', text:'أَغْمِضْ عَيْنَيْكَ وَاضْرِبْ لَوْحَةَ الْمَفَاتِيحِ عَشْوَائِيًّا. هَلْ تَخْرُجُ قِصَّةٌ جَمِيلَة؟ لَا!',
      prompt:'A screen full of jumbled random letters and symbols, messy text, gentle humor' },
    { emoji:'💙', text:'الشِّفْرَةُ الْمُتْقَنَةُ تَحْتَاجُ كَاتِبًا حَكِيمًا: اللهُ الَّذِي صَوَّرَكَ فَأَحْسَنَ صُورَتَك.',
      prompt:'A neat glowing line of code transforming into a healthy growing child silhouette, warm and hopeful' },
  ],
  moral:'شِفْرَةُ جِسْمِي الْمُتْقَنَةُ صَنَعَهَا اللهُ الْحَكِيم. 💙',
  game:{ type:'sort', title:'أَيُّهُمَا يَحْتَاجُ عَقْلًا وَتَخْطِيطًا؟', bins:['يَحْتَاجُ كَاتِبًا حَكِيمًا 🧠','عَشْوَائِيٌّ بِلَا مَعْنًى 🙈'], items:[
    { e:'📖', t:'قِصَّةٌ مُرَتَّبَةٌ جَمِيلَة', bin:0 },
    { e:'⌨️', t:'ضَرْبٌ عَشْوَائِيٌّ عَلَى الْأَزْرَار', bin:1 },
    { e:'🧬', t:'شِفْرَةُ الْحَيَاةِ الدَّقِيقَة', bin:0 },
    { e:'🌀', t:'رُمُوزٌ مُبَعْثَرَة', bin:1 } ] },
  act:{ q:'هَلْ يَكْتُبُ الْبَرْنَامَجُ نَفْسَهُ بِلَا كَاتِب؟', yay:'أَحْسَنْت! الشِّفْرَةُ الْمُتْقَنَةُ تَحْتَاجُ كَاتِبًا حَكِيمًا', opts:[
    { e:'🙅', t:'لَا! لَا بُدَّ لَهُ مِنْ كَاتِبٍ حَكِيم', ok:true },
    { e:'🎲', t:'نَعَم، بِالصُّدْفَة' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'سُبْحَانَ مَنْ صَوَّرَنِي فَأَحْسَنَ صُورَتِي' },

{ id:'emptybox', icon:'📦', color:'#E67E22', title:'الصُّنْدُوقُ الْفَارِغ',
  tag:'الْعَدَمُ لَا يَخْلُقُ شَيْئًا',
  pages:[
    { emoji:'🌌', text:'يَسْأَلُ النَّاس: مِنْ أَيْنَ جَاءَ الْكَوْن؟ قَالَ بَعْضُهُم: جَاءَ مِنْ لَا شَيْءٍ بِالصُّدْفَة!',
      prompt:'A vast starry universe with galaxies and planets, deep blues and gold, awe and wonder' },
    { emoji:'📦', text:'جَرِّبْ: ضَعْ صُنْدُوقًا فَارِغًا عَلَى الطَّاوِلَةِ وَانْتَظِر. هَلْ يَخْرُجُ مِنْهُ هَاتِفٌ وَحْدَه؟',
      prompt:'An empty cardboard box on a table with a clock beside it, waiting, simple and clear' },
    { emoji:'⏳', text:'انْتَظِرْ أَلْفَ سَنَة… لَنْ يَخْرُجَ شَيْء! لِأَنَّ الْعَدَمَ لَا يُعْطِي وُجُودًا.',
      prompt:'The same empty box covered in dust with a long-time hourglass, still empty, gentle humor' },
    { emoji:'💛', text:'كُلُّ بِنَاءٍ لَهُ بَانٍ، وَالْكَوْنُ الْعَظِيمُ لَهُ خَالِقٌ أَعْظَم: اللهُ الْأَوَّل.',
      prompt:'A magnificent building and above it a starry sky, both pointing to a maker, golden light' },
  ],
  moral:'الْكَوْنُ لَهُ خَالِقٌ عَظِيم، هُوَ اللهُ الْأَوَّل. 💛',
  game:{ type:'pairs', title:'صِلْ كُلَّ شَيْءٍ بِمَنْ أَوْجَدَه', pairs:[
    ['🏠 الْبِنَايَة','👷 لَهَا بَانٍ'],
    ['🖼️ الصُّورَة','🎨 لَهَا رَسَّام'],
    ['🌌 الْكَوْن','💛 لَهُ خَالِقٌ عَظِيم'] ] },
  act:{ q:'هَلْ يَخْرُجُ شَيْءٌ مِنَ الصُّنْدُوقِ الْفَارِغِ وَحْدَه؟', yay:'صَحِيح! الْعَدَمُ لَا يَخْلُقُ شَيْئًا', opts:[
    { e:'🙅', t:'لَا! لَا بُدَّ مِنْ خَالِقٍ أَوَّل', ok:true },
    { e:'✨', t:'نَعَم، بِالصُّدْفَة' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'أَنْتَ الْأَوَّلُ فَلَيْسَ قَبْلَكَ شَيْء' },

{ id:'compass', icon:'🧭', color:'#C0392B', title:'بَوْصَلَةُ الْقَلْب',
  tag:'الْقَلْبُ يَعْرِفُ رَبَّهُ بِالْفِطْرَة',
  pages:[
    { emoji:'🧭', text:'الْبَوْصَلَةُ إِبْرَتُهَا الصَّغِيرَة، مَهْمَا حَرَّكْتَهَا تَعُودُ دَائِمًا لِتُشِيرَ إِلَى الشَّمَال.',
      prompt:'A classic compass with a needle pointing north, close-up, warm wooden desk, clear and calm' },
    { emoji:'❤️', text:'وَفِي قَلْبِ كُلِّ إِنْسَانٍ بَوْصَلَةٌ خَفِيَّةٌ اسْمُهَا الْفِطْرَة، تُشِيرُ دَائِمًا إِلَى الله.',
      prompt:'A softly glowing heart with a tiny compass inside pointing upward to light, tender and warm' },
    { emoji:'🌊', text:'عِنْدَ الْخَطَرِ الشَّدِيدِ يَصْرُخُ النَّاسُ تِلْقَائِيًّا: يَا الله! لِأَنَّ الْقَلْبَ يَعْرِفُ خَالِقَه.',
      prompt:'A person on a boat in big waves raising hands to the sky, hopeful cry for help, dramatic but gentle' },
    { emoji:'💚', text:'وُلِدْنَا وَنَحْنُ نَعْرِفُ أَنَّ لَنَا رَبًّا. ارْجِعْ إِلَى فِطْرَتِكَ تَجِدِ الله.',
      prompt:'A peaceful child with hand on chest looking up at a warm glowing sky, sincere and serene' },
  ],
  moral:'قَلْبِي يَعْرِفُ رَبَّهُ بِالْفِطْرَة، فَأَرْجِعُ إِلَيْه. 💚',
  game:{ type:'maze', title:'اتْبَعِ الْبَوْصَلَةَ فِطْرَتَك، وَصِلْ إِلَى النُّورِ الْهَادِي', avatar:'🧭', goal:'💡', wall:'🌫️', map:['S#...','.#.#.','.#.#.','...#.','##..G'] },
  act:{ q:'لِمَاذَا يَصْرُخُ النَّاسُ «يَا الله» عِنْدَ الْخَطَر؟', yay:'أَحْسَنْت! لِأَنَّ الْقَلْبَ يَعْرِفُ رَبَّهُ بِالْفِطْرَة', opts:[
    { e:'❤️', t:'لِأَنَّ الْقَلْبَ يَعْرِفُ خَالِقَهُ فِطْرَةً', ok:true },
    { e:'📚', t:'لِأَنَّهُمْ حَفِظُوهَا فَقَط' },
    { e:'🤷', t:'بِلَا سَبَب' } ] },
  dua:'اللَّهُمَّ ثَبِّتْ قَلْبِي عَلَى دِينِك' },

]};
