/* corners/stories/minaret-little/maarifa.js — كيف عرفنا الله؟ (سلّم المعرفة) للصغار (٣–٦)
   ٢٠ حكاية مبسّطة من محطات «رحلة المعرفة واليقين» في منارة العقيدة.
   كل صفحة: emoji (بديل مؤقت) + text (سطران سهلان) + prompt (وصف صورة إنجليزي لتوليدها لاحقاً). */
window.MINARET_LITTLE = window.MINARET_LITTLE || {};
window.MINARET_LITTLE.maarifa = {
  id:'maarifa', icon:'🪜', color:'#6C5CE7', title:'كَيْفَ عَرَفْنَا الله؟', tag:'سُلَّمُ الْمَعْرِفَة',
  stories:[

{ id:'footprints', icon:'👣', color:'#2E86DE', title:'آثَارٌ فِي الرَّمْل',
  tag:'الْكَوْنُ مَلِيءٌ بِالْأَدِلَّة',
  pages:[
    { emoji:'🏖️', text:'تَمْشِي عَلَى شَاطِئٍ هَادِئ، فَتَجِدُ آثَارَ أَقْدَامٍ عَلَى الرَّمْل. مَاذَا تَعْرِف؟ أَنَّ إِنْسَانًا مَشَى هُنَا!',
      prompt:'Footprints in smooth beach sand at sunrise, calm sea, clear clues, storybook style' },
    { emoji:'👣', text:'لَمْ تَرَ الْإِنْسَان، لَكِنَّ أَثَرَهُ دَلَّكَ عَلَيْه. وَالْكَوْنُ كُلُّهُ آثَارٌ تَدُلُّ عَلَى الله.',
      prompt:'A single footprint glowing softly leading toward a bright horizon, a trace pointing to its source' },
    { emoji:'⚡', text:'لَا تَرَى الْكَهْرَبَاءَ وَلَا عَقْلَك، لَكِنَّكَ تَعْرِفُهُمَا بِآثَارِهِمَا.',
      prompt:'A glowing lightbulb and swirling thought sparkles, invisible things known by their effects, warm' },
    { emoji:'💫', text:'فَالشَّمْسُ وَالنُّجُومُ وَالشَّجَرُ وَأَنْتَ — كُلُّهَا آثَارٌ تَقُول: هُنَا خَالِقٌ عَظِيم!',
      prompt:'Sun stars trees and a child all connected by gentle light to a radiant source, wonder, warm' },
  ],
  moral:'الْكَوْنُ مَلِيءٌ بِالْآثَارِ الَّتِي تَدُلُّ عَلَى الْخَالِق. 💫',
  game:{ type:'pairs', title:'صِلْ كُلَّ أَثَرٍ بِصَاحِبِه', pairs:[
    ['👣 آثَارُ أَقْدَام','إِنْسَانٌ مَشَى هُنَا'],
    ['⚡ الضَّوْء','كَهْرَبَاءٌ لَا نَرَاهَا'],
    ['💫 الْكَوْنُ الْبَدِيع','خَالِقٌ عَظِيم'] ] },
  act:{ q:'آثَارُ الْأَقْدَامِ تَدُلُّ عَلَى مَاذَا؟', yay:'صَحِيح! وَالْكَوْنُ يَدُلُّ عَلَى الْخَالِق', opts:[
    { e:'👣', t:'أَنَّ أَحَدًا مَشَى هُنَا', ok:true },
    { e:'🎲', t:'صُدْفَةً بِلَا سَبَب' },
    { e:'🤷', t:'لَا شَيْء' } ] },
  dua:'رَبَّنَا مَا خَلَقْتَ هَذَا بَاطِلًا سُبْحَانَك' },

{ id:'painter', icon:'🎨', color:'#E84393', title:'اللَّوْحَةُ وَالرَّسَّام',
  tag:'الْإِتْقَانُ يَدُلُّ عَلَى الْحِكْمَة',
  pages:[
    { emoji:'🖼️', text:'حِينَ تَرَى لَوْحَةً بَدِيعَةً مُتْقَنَة، مَاذَا تَعْرِفُ عَنْ رَسَّامِهَا؟ أَنَّهُ مَاهِرٌ ذَوَّاق!',
      prompt:'A beautiful detailed painting on an easel in a gallery, mastery visible, warm light' },
    { emoji:'🦋', text:'وَانْظُرْ إِلَى الْفَرَاشَةِ وَالْوَرْدَةِ وَعَيْنِك: إِتْقَانٌ مُذْهِلٌ فِي كُلِّ شَيْء!',
      prompt:'A colorful butterfly on a rose with intricate detail, wondrous design in nature, radiant' },
    { emoji:'💡', text:'هَذَا الْإِتْقَانُ الْعَجِيبُ يَدُلُّ عَلَى صَانِعٍ حَكِيمٍ عَلِيمٍ رَحِيم، لَا مُهْمِل.',
      prompt:'A glowing eye diagram and butterfly wing patterns, precise design, awe, warm illustration' },
    { emoji:'💜', text:'سُبْحَانَ اللهِ الْبَدِيعِ أَحْسَنِ الْخَالِقِين!',
      prompt:'A radiant Islamic geometric masterpiece pattern, beauty and perfection, purple and gold' },
  ],
  moral:'الْإِتْقَانُ الْمُذْهِلُ فِي الْكَوْنِ دَلِيلُ خَالِقٍ حَكِيم. 💜',
  game:{ type:'find', title:'تَأَمَّلْ بَدَائِعَ الْخَلْق! اجْمَعِ الْفَرَاشَاتِ الْخَمْس', target:'🦋', count:5, distractors:['🍂','🌿'], size:12 },
  act:{ q:'الْإِتْقَانُ الْجَمِيلُ فِي الْكَوْنِ يَدُلُّ عَلَى مَاذَا؟', yay:'أَحْسَنْت! صَانِعٌ حَكِيمٌ عَلِيم', opts:[
    { e:'💡', t:'صَانِعٌ حَكِيمٌ عَلِيم', ok:true },
    { e:'🎲', t:'صُدْفَةٌ عَشْوَائِيَّة' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'سُبْحَانَ اللهِ الْبَدِيعِ أَحْسَنِ الْخَالِقِين' },

{ id:'onethrone', icon:'👑', color:'#6C5CE7', title:'عَرْشٌ لَا يُقَاسَم',
  tag:'الْخَالِقُ وَاحِد',
  pages:[
    { emoji:'👑', text:'عَرَفْنَا أَنَّ لِلْكَوْنِ خَالِقًا. لَكِنْ هَلْ هُوَ وَاحِدٌ أَمْ خَالِقُونَ كَثِيرُون؟',
      prompt:'A single grand throne under a radiant light, oneness and majesty, deep warm colors' },
    { emoji:'🏀', text:'تَخَيَّلْ فَرِيقًا لَهُ مُدَرِّبَانِ يَتَخَاصَمَان: هَذَا يَقُولُ يَمِينًا وَذَاكَ يَسَارًا. فَوْضَى!',
      prompt:'Two coaches arguing over one confused team, chaos, gentle humor, bright court' },
    { emoji:'🎵', text:'لَكِنَّ الْكَوْنَ مُنَظَّمٌ مُتَنَاغِمٌ كَلَحْنٍ جَمِيل: شَمْسٌ وَقَمَرٌ وَنُجُومٌ بِنِظَام.',
      prompt:'Planets orbiting in neat glowing rings like a symphony, harmony and order, teal and gold' },
    { emoji:'☝️', text:'فَالتَّنَاغُمُ دَلِيلُ قَائِدٍ وَاحِد: اللهُ وَاحِدٌ لَا شَرِيكَ لَه.',
      prompt:'One bright guiding star above a harmonious cosmos, unity, radiant warm light' },
  ],
  moral:'تَنَاغُمُ الْكَوْنِ دَلِيلٌ عَلَى خَالِقٍ وَاحِد. ☝️',
  game:{ type:'sort', title:'أَيُّهُمَا نِظَامٌ وَأَيُّهُمَا فَوْضَى؟', bins:['قَائِدٌ وَاحِد: نِظَام 🎵','قَائِدَانِ: فَوْضَى 🌀'], items:[
    { e:'☀️', t:'الْكَوْنُ الْمُنَظَّم', bin:0 },
    { e:'🏀', t:'مُدَرِّبَانِ يَتَخَاصَمَان', bin:1 },
    { e:'🎼', t:'لَحْنٌ مُتَنَاغِم', bin:0 },
    { e:'💥', t:'إِلَهَانِ يَخْتَلِفَان', bin:1 } ] },
  act:{ q:'كَمْ خَالِقًا لِلْكَوْنِ الْمُنَظَّم؟', yay:'أَحْسَنْت! اللهُ وَاحِدٌ لَا شَرِيكَ لَه', opts:[
    { e:'☝️', t:'خَالِقٌ وَاحِد', ok:true },
    { e:'✌️', t:'خَالِقَانِ اثْنَان' },
    { e:'🔟', t:'كَثِيرُون' } ] },
  dua:'لَا إِلَهَ إِلَّا اللهُ وَحْدَهُ لَا شَرِيكَ لَه' },

{ id:'giftcard', icon:'🎁', color:'#E1A100', title:'الْهَدِيَّةُ بِلَا بِطَاقَة',
  tag:'مَنْ هَذَا الْكَرِيم؟',
  pages:[
    { emoji:'🎁', text:'تَخَيَّلْ وَجَدْتَ هَدِيَّةً جَمِيلَةً بِلَا بِطَاقَةِ اسْم. مَاذَا سَتَفْعَل؟ سَتَبْحَثُ عَنِ الْمُعْطِي لِتَشْكُرَه!',
      prompt:'A beautiful wrapped gift with no name tag, curiosity to find the giver, warm cheerful scene' },
    { emoji:'👀', text:'وَحَوْلَكَ هَدَايَا كَثِيرَة: عَيْنَانِ تُبْصِر، وَأُذُنَانِ تَسْمَع، وَطَعَامٌ وَأَهْلٌ يُحِبُّونَك.',
      prompt:'A child surrounded by glowing gifts of eyes ears food and family love, blessings, warm' },
    { emoji:'❔', text:'مَنِ الَّذِي أَعْطَاكَ كُلَّ هَذَا؟ لَا بُدَّ أَنَّهُ كَرِيمٌ عَظِيمٌ يُحِبُّك.',
      prompt:'A glowing question mark above a pile of gifts, seeking the generous giver, warm hopeful' },
    { emoji:'💛', text:'إِنَّهُ اللهُ الْكَرِيم! فَنُرِيدُ أَنْ نَعْرِفَهُ وَنَشْكُرَه.',
      prompt:'Hands raised in grateful dua under a warm generous light, thankfulness, tender' },
  ],
  moral:'كُلُّ نِعْمَةٍ هَدِيَّةٌ مِنَ اللهِ الْكَرِيم، فَأَعْرِفُهُ وَأَشْكُرُه. 💛',
  game:{ type:'find', title:'عُدَّ هَدَايَا الله! اجْمَعِ الْهَدَايَا الْخَمْس', target:'🎁', count:5, distractors:['📦','🎈'], size:12 },
  act:{ q:'مَنْ أَعْطَاكَ عَيْنَيْكَ وَأُذُنَيْكَ وَأَهْلَك؟', yay:'أَحْسَنْت! اللهُ الْكَرِيمُ الَّذِي يُحِبُّك', opts:[
    { e:'💛', t:'اللهُ الْكَرِيم', ok:true },
    { e:'🛒', t:'الْمَتْجَر' },
    { e:'🤷', t:'لَا أَحَد' } ] },
  dua:'اللَّهُمَّ عَرِّفْنِي بِنَفْسِكَ فَأَنْتَ أَكْرَمُ مَنْ أَعْطَى' },

{ id:'unseenking', icon:'📜', color:'#00B894', title:'هَلْ تَعْرِفُ مَلِكًا لَمْ تَرَه؟',
  tag:'الْعَقْلُ يَحْتَاجُ رِسَالَة',
  pages:[
    { emoji:'✉️', text:'تَخَيَّلْ مَلِكًا عَظِيمًا فِي بَلَدٍ بَعِيدٍ لَمْ تَزُرْه. كَيْفَ تَعْرِفُ اسْمَهُ وَمَاذَا يُحِبّ؟',
      prompt:'A distant palace on a hill with a sealed royal letter in the foreground, mystery, warm dusk' },
    { emoji:'🧠', text:'عَقْلُكَ يَعْرِفُ أَنَّ لِلْبَلَدِ مَلِكًا، لَكِنَّهُ لَا يَعْرِفُ اسْمَهُ إِلَّا إِذَا أَرْسَلَ رِسَالَة.',
      prompt:'A glowing lightbulb next to a question mark, reason reaching its limit, warm illustration' },
    { emoji:'📜', text:'كَذَلِكَ اللهُ: عَقْلُنَا يَعْرِفُ أَنَّ لَهُ خَالِقًا، لَكِنْ لِنَعْرِفَهُ حَقًّا نَحْتَاجُ رِسَالَتَه.',
      prompt:'A scroll of light descending gently from the sky, revelation reaching a seeking heart, hopeful' },
    { emoji:'💚', text:'فَأَرْسَلَ اللهُ رُسُلًا وَكُتُبًا لِيُعَرِّفَنَا بِنَفْسِه.',
      prompt:'A beam of light connecting heaven to an open book, guidance revealed, warm serene' },
  ],
  moral:'الْعَقْلُ يَعْرِفُ أَنَّ لِلْكَوْنِ خَالِقًا، وَالْوَحْيُ يُعَرِّفُنَا بِه. 💚',
  game:{ type:'pairs', title:'صِلْ كُلَّ سُؤَالٍ بِطَرِيقِ مَعْرِفَتِه', pairs:[
    ['🌍 هَلْ هُنَاكَ خَالِق؟','الْعَقْلُ وَالْفِطْرَة'],
    ['📜 مَاذَا يُحِبُّ الله؟','الْوَحْيُ وَالرِّسَالَة'],
    ['🕊️ مَنْ يَحْمِلُ الرِّسَالَة؟','الرُّسُل'] ] },
  act:{ q:'كَيْفَ نَعْرِفُ اسْمَ اللهِ وَمَا يُحِبُّه؟', yay:'أَحْسَنْت! بِرِسَالَتِهِ الَّتِي أَرْسَلَهَا', opts:[
    { e:'📜', t:'بِالْوَحْيِ وَالرُّسُل', ok:true },
    { e:'🤔', t:'نُخَمِّنُ وَحْدَنَا' },
    { e:'🤷', t:'لَا يُمْكِن' } ] },
  dua:'اللَّهُمَّ زِدْنِي عِلْمًا بِكَ وَقُرْبًا مِنْك' },

{ id:'messengers', icon:'🕊️', color:'#0984E3', title:'رُسُلُ الْمَلِك',
  tag:'سِلْسِلَةُ النُّورِ عَبْرَ الزَّمَن',
  pages:[
    { emoji:'📨', text:'مِنْ رَحْمَةِ اللهِ أَنَّهُ أَرْسَلَ رُسُلًا كَثِيرِينَ لِيُعَرِّفُونَا بِه، فِي كُلِّ زَمَنٍ نَبِيّ.',
      prompt:'A line of glowing lanterns across a timeline, messengers through the ages, warm continuity' },
    { emoji:'🚢', text:'نُوحٌ صَنَعَ السَّفِينَة، وَإِبْرَاهِيمُ نَجَا مِنَ النَّار، وَمُوسَى فَلَقَ الْبَحْر.',
      prompt:'An ark, a cool flame, and a parted sea shown as glowing symbols, prophet signs, radiant' },
    { emoji:'🕊️', text:'وَعِيسَى بِمُعْجِزَاتِه، وَمُحَمَّدٌ ﷺ بِالْقُرْآن — كُلُّهُم رُسُلُ الْمَلِكِ الْوَاحِد.',
      prompt:'A gentle dove and a glowing Quran, prophets of one message, warm and serene' },
    { emoji:'💚', text:'وَرِسَالَتُهُم وَاحِدَة: اعْبُدُوا اللهَ وَحْدَه.',
      prompt:'One radiant star above a chain of lanterns, one message across time, teal and gold' },
  ],
  moral:'الرُّسُلُ سِلْسِلَةُ نُورٍ وَاحِدَةٌ تَدْعُو إِلَى اللهِ وَحْدَه. 💚',
  game:{ type:'pairs', title:'صِلْ كُلَّ نَبِيٍّ بِآيَتِهِ الْمَشْهُورَة', pairs:[
    ['🚢 نُوح','صَنَعَ السَّفِينَة'],
    ['🔥 إِبْرَاهِيم','نَجَا مِنَ النَّار'],
    ['🌊 مُوسَى','فَلَقَ الْبَحْر'] ] },
  act:{ q:'مَا رِسَالَةُ كُلِّ الرُّسُل؟', yay:'أَحْسَنْت! رِسَالَةٌ وَاحِدَةٌ عَبْرَ الزَّمَن', opts:[
    { e:'💚', t:'اعْبُدُوا اللهَ وَحْدَه', ok:true },
    { e:'👑', t:'كُلٌّ دِينٌ مُخْتَلِف' },
    { e:'💰', t:'اجْمَعُوا الْمَال' } ] },
  dua:'اللَّهُمَّ صَلِّ عَلَى أَنْبِيَائِكَ وَرُسُلِكَ أَجْمَعِين' },

{ id:'sealedletter', icon:'📖', color:'#00897B', title:'الرِّسَالَةُ الْمَخْتُومَة',
  tag:'الْقُرْآنُ كِتَابُ الْمَلِك',
  pages:[
    { emoji:'📖', text:'وَصَلَتْنَا رِسَالَةُ الْمَلِك: الْقُرْآن! لَكِنْ كَيْفَ نَتَأَكَّدُ أَنَّهَا حَقِيقِيَّةٌ لَمْ تَتَغَيَّر؟',
      prompt:'A glowing Quran on a wooden stand under warm light, the King message, reverent' },
    { emoji:'🛡️', text:'لَمْ يَتَغَيَّرْ فِيهِ حَرْفٌ مُنْذُ أَرْبَعَةَ عَشَرَ قَرْنًا! حَفِظَهُ اللهُ بِنَفْسِه.',
      prompt:'An open Quran wrapped in a protective shield of golden light, preserved and safe, radiant' },
    { emoji:'🌍', text:'وَتَحَدَّى الْجَمِيعَ أَنْ يَأْتُوا بِمِثْلِهِ فَعَجَزُوا، وَفِيهِ أَخْبَارُ غَيْبٍ صَدَقَت.',
      prompt:'A globe with the same open book glowing at many points, unmatched challenge, warm' },
    { emoji:'💚', text:'إِنَّهُ خَتْمُ الله! رِسَالَةٌ صَادِقَةٌ مَحْفُوظَةٌ مِنْ رَبِّ الْعَالَمِين.',
      prompt:'A golden seal of light on a radiant book, authentic and protected, warm serene' },
  ],
  moral:'الْقُرْآنُ رِسَالَةُ اللهِ الْمَحْفُوظَةُ الصَّادِقَة. 💚',
  game:{ type:'pairs', title:'صِلْ كُلَّ دَلِيلٍ عَلَى الْقُرْآنِ بِمَعْنَاه', pairs:[
    ['🛡️ لَمْ يَتَغَيَّرْ حَرْف','كِتَابٌ مَحْفُوظ'],
    ['🌍 تَحَدَّى الْجَمِيع','فَعَجَزُوا عَنْ مِثْلِه'],
    ['🔮 أَخْبَارُ غَيْب','صَدَقَتْ كَمَا قَال'] ] },
  act:{ q:'مَنْ حَفِظَ الْقُرْآنَ مِنَ التَّغْيِير؟', yay:'أَحْسَنْت! لَمْ يَتَغَيَّرْ فِيهِ حَرْف', opts:[
    { e:'🛡️', t:'اللهُ حَفِظَهُ بِنَفْسِه', ok:true },
    { e:'🔒', t:'صُنْدُوقٌ حَدِيدِيّ' },
    { e:'🤷', t:'لَا أَحَد' } ] },
  dua:'اللَّهُمَّ اجْعَلِ الْقُرْآنَ رَبِيعَ قَلْبِي' },

{ id:'truthful', icon:'🤝', color:'#C0392B', title:'الصَّادِقُ الْأَمِين',
  tag:'كَيْفَ نَعْرِفُ النَّبِيَّ الْحَقّ؟',
  pages:[
    { emoji:'🆔', text:'الْمُدَّعُونَ كَثِيرُون! فَكَيْفَ نَعْرِفُ أَنَّ مُحَمَّدًا ﷺ رَسُولٌ حَقٌّ مِنَ الله؟',
      prompt:'A glowing identity badge of light, verifying truth, warm clear illustration' },
    { emoji:'🤝', text:'كَانَ قَبْلَ النُّبُوَّةِ يُسَمَّى «الصَّادِقَ الْأَمِين» — مَا كَذَبَ قَطُّ وَلَا خَان.',
      prompt:'People entrusting valuables to a trusted figure silhouette, honesty and trust, warm, no face' },
    { emoji:'💰', text:'وَلَمْ يَطْلُبْ مَالًا وَلَا مُلْكًا، بَلْ دَعَا لِعِبَادَةِ اللهِ وَحْدَه لَا نَفْسِه.',
      prompt:'An open empty hand refusing gold, seeking nothing worldly, sincerity, warm light, no face' },
    { emoji:'💚', text:'فَمَنْ صَدَقَ فِي كُلِّ حَيَاتِه، لَا يَكْذِبُ عَلَى الله. إِنَّهُ نَبِيٌّ حَقّ.',
      prompt:'A radiant beam of truth, an honest heart, verified prophethood, warm and serene' },
  ],
  moral:'الصَّادِقُ الْأَمِينُ لَا يَكْذِبُ عَلَى الله، فَهُوَ نَبِيٌّ حَقّ. 💚',
  game:{ type:'sort', title:'مَا عَلَامَاتُ النَّبِيِّ الصَّادِق؟', bins:['عَلَامَةُ صِدْق ✅','عَلَامَةُ كَذِب 🚫'], items:[
    { e:'🤝', t:'صَادِقٌ أَمِينٌ لَمْ يَكْذِب', bin:0 },
    { e:'💰', t:'يَطْلُبُ الْمَالَ وَالْمُلْك', bin:1 },
    { e:'🙏', t:'يَدْعُو لِعِبَادَةِ اللهِ وَحْدَه', bin:0 },
    { e:'👑', t:'يَدْعُو لِعِبَادَةِ نَفْسِه', bin:1 } ] },
  act:{ q:'بِمَاذَا كَانَ يُلَقَّبُ النَّبِيُّ ﷺ قَبْلَ النُّبُوَّة؟', yay:'أَحْسَنْت! الصَّادِقُ الْأَمِين', opts:[
    { e:'🤝', t:'الصَّادِقُ الْأَمِين', ok:true },
    { e:'💰', t:'التَّاجِرُ الْغَنِيّ' },
    { e:'👑', t:'الْمَلِك' } ] },
  dua:'اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّد' },

{ id:'names', icon:'🌸', color:'#8E44AD', title:'أَسْمَاءُ الْمَلِكِ الْحُسْنَى',
  tag:'نَوَافِذُ مَعْرِفَةِ الله',
  pages:[
    { emoji:'💎', text:'عَرَّفَنَا اللهُ بِنَفْسِهِ بِأَجْمَلِ طَرِيقَة: أَسْمَاؤُهُ الْحُسْنَى، كُلُّ اسْمٍ نَافِذَةٌ نَعْرِفُهُ مِنْهَا.',
      prompt:'Beautiful glowing windows each shining a different warm light, names as windows, radiant' },
    { emoji:'💚', text:'الرَّحْمَنُ يَرْحَمُنَا، وَالرَّزَّاقُ يُطْعِمُنَا، وَالْغَفَّارُ يَغْفِرُ لَنَا إِذَا أَخْطَأْنَا.',
      prompt:'Three glowing name-windows of mercy, provision, and forgiveness, warm and comforting' },
    { emoji:'❤️', text:'كُلَّمَا عَرَفْتَ اسْمًا مِنْ أَسْمَائِه، أَحْبَبْتَهُ أَكْثَرَ وَاطْمَأَنَّ قَلْبُك.',
      prompt:'A softly glowing heart growing warmer beside names of light, love through knowing, tender' },
    { emoji:'🌸', text:'فَنَحْفَظُ أَسْمَاءَهُ وَنَدْعُوهُ بِهَا.',
      prompt:'A garden of glowing flowers each labeled with a beautiful name of light, serene and warm' },
  ],
  moral:'أَسْمَاءُ اللهِ الْحُسْنَى نَوَافِذُ أُحِبُّهُ وَأَطْمَئِنُّ بِهَا. 🌸',
  game:{ type:'pairs', title:'صِلْ كُلَّ اسْمٍ بِأَثَرِهِ فِي قَلْبِك', pairs:[
    ['💚 الرَّحْمَن','يَرْحَمُنِي'],
    ['🌾 الرَّزَّاق','يُطْعِمُنِي'],
    ['🤲 الْغَفَّار','يَغْفِرُ لِي إِذَا أَخْطَأْت'] ] },
  act:{ q:'مَاذَا تَفْعَلُ أَسْمَاءُ اللهِ الْحُسْنَى فِي قَلْبِي؟', yay:'أَحْسَنْت! أُحِبُّهُ وَأَطْمَئِنُّ إِلَيْه', opts:[
    { e:'❤️', t:'تُعَرِّفُنِي بِهِ فَأُحِبُّهُ وَأَطْمَئِنّ', ok:true },
    { e:'😴', t:'لَا شَيْء' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ إِنِّي أَسْأَلُكَ بِأَسْمَائِكَ الْحُسْنَى كُلِّهَا' },

{ id:'knewloved', icon:'❤️', color:'#D4A017', title:'عَرَفْتُهُ فَأَحْبَبْتُه',
  tag:'قِمَّةُ الرِّحْلَة',
  pages:[
    { emoji:'🏆', text:'وَصَلْنَا إِلَى قِمَّةِ الْجَبَل! لِنَجْمَعْ مَا اكْتَشَفْنَاهُ كَمُحَقِّقٍ ذَكِيّ.',
      prompt:'A child standing joyfully at a mountain summit at sunrise, achievement, warm uplifting light' },
    { emoji:'🌍', text:'الْكَوْنُ الْمُتْقَنُ لَهُ خَالِقٌ وَاحِد، وَنِعَمُهُ الْكَثِيرَةُ تَدُلُّ عَلَى كَرِيم.',
      prompt:'The Earth glowing warmly with rays of blessing, one wise generous Creator, radiant' },
    { emoji:'📖', text:'وَعَرَّفَنَا بِنَفْسِهِ عَبْرَ رُسُلِهِ وَكِتَابِهِ وَأَسْمَائِهِ الْحُسْنَى.',
      prompt:'A glowing book and names of light rising to a warm sky, self-revelation, serene' },
    { emoji:'❤️', text:'عَرَفْتُهُ فَأَحْبَبْتُه، وَأَحْبَبْتُهُ فَعَبَدْتُه!',
      prompt:'A radiant loving heart connected by light to a warm glow above, love leading to worship, tender' },
  ],
  moral:'مَعْرِفَةُ الْمُنْعِمِ تُثْمِرُ حُبًّا وَشُكْرًا وَعِبَادَة. ❤️',
  game:{ type:'order', title:'رَتِّبْ سُلَّمَ الْمَعْرِفَة', items:[
    { e:'🌍', t:'الْكَوْنُ لَهُ خَالِق' },
    { e:'☝️', t:'خَالِقٌ وَاحِدٌ حَكِيم' },
    { e:'📖', t:'عَرَّفَنَا بِنَفْسِهِ بِالْوَحْي' },
    { e:'❤️', t:'عَرَفْتُهُ فَأَحْبَبْتُه' } ] },
  act:{ q:'مَاذَا يَحْدُثُ حِينَ نَعْرِفُ اللهَ حَقًّا؟', yay:'أَحْسَنْت! عَرَفْتُهُ فَأَحْبَبْتُهُ فَعَبَدْتُه', opts:[
    { e:'❤️', t:'نُحِبُّهُ وَنَشْكُرُهُ وَنَعْبُدُه', ok:true },
    { e:'😴', t:'لَا شَيْء' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ ارْزُقْنِي حُبَّكَ وَحُبَّ مَنْ يُحِبُّك' },

{ id:'birds', icon:'🐦', color:'#16A085', title:'إِبْرَاهِيمُ وَالطُّيُور',
  tag:'مِنَ الْمَعْرِفَةِ إِلَى الْيَقِين',
  pages:[
    { emoji:'🐦', text:'الْمَعْرِفَةُ لَهَا دَرَجَات! سَأَلَ إِبْرَاهِيمُ رَبَّه: أَرِنِي كَيْفَ تُحْيِي الْمَوْتَى؟',
      prompt:'Four colorful birds and a gentle figure raising hands to the sky, seeking certainty, warm' },
    { emoji:'❓', text:'قَالَ اللهُ: أَوَلَمْ تُؤْمِن؟ قَال: بَلَى، وَلَكِنْ لِيَطْمَئِنَّ قَلْبِي.',
      prompt:'A glowing heart with a question mark, seeking peace of certainty, warm illustration' },
    { emoji:'✨', text:'فَجَعَلَ عَلَى كُلِّ جَبَلٍ جُزْءًا مِنَ الطُّيُور، ثُمَّ نَادَاهُنَّ فَجِئْنَ حَيَّاتٍ بِإِذْنِ الله!',
      prompt:'Birds flying back to life across mountains toward a caller, miracle of certainty, radiant' },
    { emoji:'💚', text:'الْعِلْمُ بِالْخَبَرِ شَيْء، وَالرُّؤْيَةُ بِالْعَيْنِ يَقِينٌ أَقْوَى. وَالْإِيمَانُ يَزِيدُ كَالشَّمْسِ تُشْرِق.',
      prompt:'A rising sun growing brighter over mountains, faith increasing, hopeful warm light' },
  ],
  moral:'الْإِيمَانُ يَزِيدُ وَيَنْمُو، وَنَطْلُبُ الْيَقِينَ الَّذِي يُطَمْئِنُ الْقَلْب. 💚',
  game:{ type:'find', title:'نَادِ الطُّيُور! اجْمَعِ الطُّيُورَ الْأَرْبَعَةَ الْعَائِدَةَ بِإِذْنِ الله', target:'🐦', count:4, distractors:['⛰️','☁️'], size:12 },
  act:{ q:'لِمَاذَا سَأَلَ إِبْرَاهِيمُ أَنْ يَرَى بِعَيْنِه؟', yay:'أَحْسَنْت! لِيَطْمَئِنَّ قَلْبُهُ بِالْيَقِين', opts:[
    { e:'💚', t:'لِيَطْمَئِنَّ قَلْبُهُ أَكْثَر', ok:true },
    { e:'😕', t:'لِأَنَّهُ شَكَّ بِالله' },
    { e:'🤷', t:'بِلَا سَبَب' } ] },
  dua:'رَبِّ زِدْنِي عِلْمًا وَيَقِينًا وَطُمَأْنِينَة' },

{ id:'clouds', icon:'☁️', color:'#5DADE2', title:'الشَّمْسُ خَلْفَ الْغُيُوم',
  tag:'كَيْفَ نُوَاجِهُ الشُّكُوك؟',
  pages:[
    { emoji:'🌤️', text:'أَحْيَانًا تَأْتِي أَفْكَارٌ تَهْمِس: هَلِ اللهُ مَوْجُود؟ لَا تَخَفْ، هَذَا يَحْدُثُ لِكَثِيرِين.',
      prompt:'The sun mostly hidden behind soft clouds but its light still glowing through, reassuring, warm' },
    { emoji:'☁️', text:'الشَّكُّ كَغَيْمَةٍ تُغَطِّي الشَّمْس. هَلِ اخْتَفَتِ الشَّمْس؟ لَا! هِيَ خَلْفَ الْغَيْمَةِ سَاطِعَة.',
      prompt:'Bright sun rays breaking through gray clouds, truth still there behind doubt, hopeful' },
    { emoji:'📱', text:'وَالشَّكُّ كَإِعْلَانٍ مُفَاجِئٍ يَقْفِزُ عَلَى الشَّاشَة: لَا تُنَاقِشْه، أَغْلِقْهُ وَامْضِ!',
      prompt:'A pop-up notification being gently closed on a screen, ignore the distraction, clean bright' },
    { emoji:'💚', text:'وَكَرَاهَتُكَ لِلشَّكِّ نَفْسِهَا دَلِيلُ إِيمَانِكَ الصَّرِيح. قُلْ: آمَنْتُ بِالله، وَامْضِ.',
      prompt:'A child confidently walking forward into warm light leaving clouds behind, steadfast faith' },
  ],
  moral:'الشَّكُّ غَيْمَةٌ تَمُرّ، وَالشَّمْسُ خَلْفَهَا سَاطِعَة. أَقُول: آمَنْتُ بِالله. 💚',
  game:{ type:'maze', title:'تَجَاوَزْ غُيُومَ الشَّكِّ وَصِلْ إِلَى نُورِ الْيَقِين', avatar:'🚶', goal:'☀️', wall:'☁️', map:['S#...','.#.#.','.#.#.','...#.','##..G'] },
  act:{ q:'مَاذَا أَفْعَلُ حِينَ يَأْتِي هَمْسُ الشَّكّ؟', yay:'أَحْسَنْت! كَإِعْلَانٍ أُغْلِقُهُ وَأَمْضِي', opts:[
    { e:'💚', t:'أَقُولُ آمَنْتُ بِالله وَأَنْشَغِلُ بِالنَّافِع', ok:true },
    { e:'😰', t:'أُنَاقِشُهُ طَوِيلًا وَأَقْلَق' },
    { e:'🤷', t:'أَسْتَسْلِمُ لَه' } ] },
  dua:'رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا' },

{ id:'horizons', icon:'🔭', color:'#6C5CE7', title:'آيَاتٌ فِي الْآفَاقِ وَفِي نَفْسِك',
  tag:'الْيَقِينُ يَنْمُو',
  pages:[
    { emoji:'🌌', text:'كُلَّمَا نَظَرْتَ حَوْلَك، وَجَدْتَ آيَاتٍ تَزِيدُ يَقِينَكَ بِالله: فِي السَّمَاءِ وَفِي نَفْسِك!',
      prompt:'A vast starry cosmos with a child gazing in wonder, signs everywhere, awe and warmth' },
    { emoji:'⭐', text:'فِي الْآفَاق: نُجُومٌ لَا تُعَدّ، وَشَمْسٌ تُشْرِق، وَجِبَالٌ رَاسِيَة، وَبِحَارٌ وَاسِعَة.',
      prompt:'Mountains, sea, sun and countless stars in harmony, cosmic signs, radiant warm colors' },
    { emoji:'🫀', text:'وَفِي نَفْسِك: قَلْبٌ يَنْبِض، وَعَيْنٌ تُبْصِر، وَعَقْلٌ يُفَكِّر — عَجَائِبُ فِي جِسْمِك!',
      prompt:'A friendly diagram of a beating heart and eye with gentle glow, wonders within, warm' },
    { emoji:'💚', text:'كُلُّهَا تَقُول: سُبْحَانَ مَنْ خَلَقَنِي وَأَتْقَنَ صُنْعِي!',
      prompt:'A child looking at their own hands in wonder under warm light, gratitude for creation, tender' },
  ],
  moral:'آيَاتُ اللهِ فِي الْكَوْنِ وَفِي نَفْسِي تَزِيدُ يَقِينِي. 💚',
  game:{ type:'sort', title:'أَيْنَ نَجِدُ آيَاتِ الله؟', bins:['فِي الْآفَاق 🌌','فِي نَفْسِي 🫀'], items:[
    { e:'⭐', t:'النُّجُومُ وَالشَّمْس', bin:0 },
    { e:'🫀', t:'قَلْبِي يَنْبِض', bin:1 },
    { e:'⛰️', t:'الْجِبَالُ وَالْبِحَار', bin:0 },
    { e:'👁️', t:'عَيْنِي تُبْصِر', bin:1 } ] },
  act:{ q:'أَيْنَ نَجِدُ آيَاتِ الله؟', yay:'أَحْسَنْت! فِي الْكَوْنِ وَفِي أَنْفُسِنَا', opts:[
    { e:'💚', t:'فِي الْآفَاقِ وَفِي نَفْسِي', ok:true },
    { e:'📚', t:'فِي مَكَانٍ وَاحِدٍ فَقَط' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'رَبِّ أَرِنِي آيَاتِكَ فِي الْكَوْنِ وَفِي نَفْسِي' },

{ id:'answered', icon:'🤲', color:'#00B894', title:'الدُّعَاءُ الْمُسْتَجَاب',
  tag:'حِينَ تَشْعُرُ بِقُرْبِ الله',
  pages:[
    { emoji:'🤲', text:'هَلْ دَعَوْتَ اللهَ يَوْمًا بِشَيْءٍ فَأَعْطَاكَ إِيَّاه؟ تِلْكَ لَحْظَةٌ تَشْعُرُ فِيهَا بِقُرْبِ الله.',
      prompt:'A child raising hands hopefully to a warm glowing sky, heartfelt prayer, tender' },
    { emoji:'📞', text:'الدُّعَاءُ كَاتِّصَالٍ مُبَاشِرٍ بِالله، بِلَا وَاسِطَةٍ وَلَا انْقِطَاع، فِي أَيِّ وَقْت.',
      prompt:'A beam of light rising from praying hands directly to the heavens, direct connection, warm' },
    { emoji:'💚', text:'وَحِينَ يَسْتَجِيبُ اللهُ دُعَاءَك، يَزْدَادُ يَقِينُكَ أَنَّهُ قَرِيبٌ يَسْمَعُكَ وَيُحِبُّك.',
      prompt:'A hopeful child smiling as a soft light answers their prayer, joy and certainty, warm' },
    { emoji:'🌟', text:'وَإِنْ تَأَخَّرَ، فَهُوَ يَخْتَارُ لَكَ الْأَفْضَل. فَادْعُ دَائِمًا وَلَا تَيْأَس.',
      prompt:'Stars glowing over a peaceful night sky with open hands, trust in timing, serene warm light' },
  ],
  moral:'الدُّعَاءُ اتِّصَالِي الْمُبَاشِرُ بِالله، يَزِيدُ يَقِينِي بِقُرْبِه. 🌟',
  game:{ type:'find', title:'ادْعُ رَبَّكَ الْقَرِيب! اجْمَعِ الْأَيْدِيَ الْمَرْفُوعَةَ الْخَمْس', target:'🤲', count:5, distractors:['☁️','⭐'], size:12 },
  act:{ q:'مَاذَا يَحْدُثُ حِينَ يَسْتَجِيبُ اللهُ دُعَاءَك؟', yay:'أَحْسَنْت! يَزْدَادُ يَقِينُكَ بِقُرْبِه', opts:[
    { e:'💚', t:'أَشْعُرُ أَنَّهُ قَرِيبٌ يَسْمَعُنِي', ok:true },
    { e:'🤷', t:'لَا شَيْء' },
    { e:'😴', t:'أَنْسَاه' } ] },
  dua:'اللَّهُمَّ إِنِّي أَدْعُوكَ فَاسْتَجِبْ لِي' },

{ id:'peace', icon:'🧘', color:'#27AE60', title:'الْقَلْبُ الْمُطْمَئِنّ',
  tag:'ثَمَرَةُ الْيَقِين',
  pages:[
    { emoji:'💚', text:'حِينَ يَعْرِفُ الْقَلْبُ رَبَّهُ وَيُوقِنُ بِه، يَشْعُرُ بِرَاحَةٍ عَجِيبَةٍ لَا يُشْبِهُهَا شَيْء.',
      prompt:'A serene child sitting peacefully with a soft glow around the heart, tranquility, warm garden' },
    { emoji:'🌿', text:'لَا خَوْفَ وَلَا قَلَق، لِأَنَّهُ يَعْلَمُ أَنَّ رَبًّا حَكِيمًا رَحِيمًا يُدَبِّرُ أَمْرَه.',
      prompt:'A calm garden with gentle breeze and soft light, peace of heart, serene warm tones' },
    { emoji:'🕊️', text:'أَلَا بِذِكْرِ اللهِ تَطْمَئِنُّ الْقُلُوب! فَالطُّمَأْنِينَةُ فِي الْقُرْبِ مِنَ الله.',
      prompt:'A white dove resting on a blooming branch in warm light, peace through remembrance, tender' },
    { emoji:'😊', text:'هَذِهِ السَّكِينَةُ أَغْلَى كَنْزٍ يَنَالُهُ الْقَلْبُ الْعَارِفُ بِرَبِّه.',
      prompt:'A glowing peaceful heart like a treasure radiating calm, the greatest gift, warm serene' },
  ],
  moral:'مَعْرِفَةُ اللهِ وَالْيَقِينُ بِهِ تُثْمِرُ قَلْبًا مُطْمَئِنًّا. 😊',
  game:{ type:'sort', title:'مَا الَّذِي يُطَمْئِنُ الْقَلْب؟', bins:['يُطَمْئِنُ الْقَلْب 💚','يُقْلِقُ الْقَلْب 🚫'], items:[
    { e:'🕊️', t:'ذِكْرُ اللهِ وَالْقُرْب مِنْه', bin:0 },
    { e:'😰', t:'الْبُعْدُ عَنِ الله', bin:1 },
    { e:'🤲', t:'الدُّعَاءُ وَالثِّقَةُ بِالله', bin:0 },
    { e:'😤', t:'الْقَلَقُ عَلَى كُلِّ شَيْء', bin:1 } ] },
  act:{ q:'أَيْنَ تَجِدُ الْقُلُوبُ الطُّمَأْنِينَة؟', yay:'أَحْسَنْت! فِي مَعْرِفَةِ اللهِ وَذِكْرِه', opts:[
    { e:'💚', t:'بِذِكْرِ اللهِ وَالْقُرْبِ مِنْه', ok:true },
    { e:'💰', t:'فِي الْمَالِ الْكَثِير' },
    { e:'🎮', t:'فِي اللَّعِبِ فَقَط' } ] },
  dua:'اللَّهُمَّ أَنْزِلْ عَلَى قَلْبِيَ السَّكِينَة' },

{ id:'meeting', icon:'🌙', color:'#34495E', title:'الْيَقِينُ بِاللِّقَاء',
  tag:'الْحَيَاةُ رِحْلَةٌ لَهَا نِهَايَة',
  pages:[
    { emoji:'♾️', text:'الْحَيَاةُ رِحْلَةٌ جَمِيلَةٌ لَهَا نِهَايَة، ثُمَّ نَلْقَى رَبَّنَا الَّذِي عَرَفْنَاهُ وَأَحْبَبْنَاه.',
      prompt:'A path winding toward a warm glowing horizon at dusk, life journey with a destination, serene' },
    { emoji:'🌙', text:'الْمَوْتُ لَيْسَ نِهَايَةَ كُلِّ شَيْء، بَلْ بَابٌ إِلَى لِقَاءِ اللهِ وَالْحَيَاةِ الْبَاقِيَة.',
      prompt:'A gentle doorway of soft moonlight opening to a bright peaceful garden, transition, warm hopeful' },
    { emoji:'🌸', text:'فَالْمُؤْمِنُ لَا يَخَافُ اللِّقَاء، بَلْ يَسْتَعِدُّ لَهُ بِالْخَيْرِ وَيَشْتَاقُ لِرَبِّه.',
      prompt:'A child planting good deeds shown as glowing flowers along a path, preparing joyfully, warm' },
    { emoji:'💚', text:'وَنَحْيَا بِيَقِينٍ أَنَّ اللِّقَاءَ حَقٌّ، فَنَجْعَلُ كُلَّ يَوْمٍ خَيْرًا.',
      prompt:'A hopeful child walking toward warm light with a full heart, certainty of meeting Allah, uplifting' },
  ],
  moral:'أُوقِنُ بِلِقَاءِ رَبِّي، فَأَسْتَعِدُّ لَهُ بِالْخَيْرِ وَلَا أَخَاف. 💚',
  game:{ type:'order', title:'رَتِّبْ رِحْلَةَ الْحَيَاةِ نَحْوَ اللِّقَاء', items:[
    { e:'🌱', t:'نَعِيشُ وَنَزْرَعُ الْخَيْر' },
    { e:'🌙', t:'بَابُ الِانْتِقَال' },
    { e:'♾️', t:'الْحَيَاةُ الْبَاقِيَة' },
    { e:'💚', t:'لِقَاءُ اللهِ الَّذِي أَحْبَبْنَاه' } ] },
  act:{ q:'مَا الْمَوْتُ بِالنِّسْبَةِ لِلْمُؤْمِن؟', yay:'أَحْسَنْت! بَابٌ إِلَى لِقَاءِ الله', opts:[
    { e:'🌙', t:'بَابٌ إِلَى لِقَاءِ اللهِ وَالْبَقَاء', ok:true },
    { e:'😨', t:'نِهَايَةُ كُلِّ شَيْء' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ اجْعَلْ لِقَاءَكَ قُرَّةَ عَيْنِي' },

{ id:'mountain', icon:'⛰️', color:'#B7791F', title:'يَقِينٌ كَالْجَبَل',
  tag:'حِينَ يَصْمُدُ الْإِيمَان',
  pages:[
    { emoji:'🪨', text:'حِينَ يَقْوَى يَقِينُكَ، يَصِيرُ قَلْبُكَ كَالْجَبَلِ الرَّاسِخِ لَا تُزَعْزِعُهُ الرِّيَاح.',
      prompt:'A majestic firm mountain standing steady under a dramatic sky, unshakeable, warm strong light' },
    { emoji:'🌬️', text:'تَأْتِي رِيَاحُ الشُّكُوكِ وَالْمَصَائِبِ فَيَنْحَنِي الضَّعِيفُ وَيَنْكَسِر، أَمَّا الْجَبَلُ فَيَثْبُت.',
      prompt:'Strong wind blowing but a mountain unmoved while weak reeds bend, steadfastness, dramatic warm' },
    { emoji:'🌳', text:'وَالشَّجَرَةُ ذَاتُ الْجُذُورِ الْعَمِيقَةِ تَصْمُدُ فِي الْعَاصِفَة، وَبِلَا جُذُورٍ تَنْكَسِر.',
      prompt:'A deeply rooted tree standing firm in a storm, roots visible, resilience, warm earthy tones' },
    { emoji:'💚', text:'فَنُقَوِّي جُذُورَ يَقِينِنَا بِالْعِلْمِ وَالذِّكْرِ وَالْعَمَلِ الصَّالِح.',
      prompt:'A strong tree with glowing deep roots under warm light, faith rooted in knowledge, uplifting' },
  ],
  moral:'يَقِينِي الْقَوِيُّ كَالْجَبَل: تَأْتِي الرِّيَاحُ وَلَا يَتَزَعْزَع. ⛰️',
  game:{ type:'sort', title:'مَا الَّذِي يُقَوِّي جُذُورَ يَقِينِي؟', bins:['يُقَوِّي الْيَقِين 💪','يُضْعِفُه 🚫'], items:[
    { e:'📖', t:'الْعِلْمُ وَالْقُرْآن', bin:0 },
    { e:'🙏', t:'الذِّكْرُ وَالصَّلَاة', bin:0 },
    { e:'😴', t:'الْغَفْلَةُ وَالْبُعْد', bin:1 },
    { e:'🤝', t:'الْعَمَلُ الصَّالِح', bin:0 } ] },
  act:{ q:'كَيْفَ يَصِيرُ الْيَقِينُ قَوِيًّا كَالْجَبَل؟', yay:'أَحْسَنْت! بِالْجُذُورِ الْعَمِيقَةِ مِنَ الْعِلْمِ وَالْعَمَل', opts:[
    { e:'💚', t:'بِالْعِلْمِ وَالذِّكْرِ وَالْعَمَلِ الصَّالِح', ok:true },
    { e:'😴', t:'بِلَا شَيْء' },
    { e:'💰', t:'بِالْمَال' } ] },
  dua:'يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَى دِينِك' },

{ id:'tawakkul', icon:'🪂', color:'#0984E3', title:'الْيَدُ الَّتِي تُمْسِكُ السَّمَاء',
  tag:'الْيَقِينُ يُثْمِرُ تَوَكُّلًا',
  pages:[
    { emoji:'🤝', text:'حِينَ تُوقِنُ أَنَّ اللهَ قَوِيٌّ حَكِيمٌ يُحِبُّك، تَسْتَطِيعُ أَنْ تُسَلِّمَ أَمْرَكَ إِلَيْهِ بِثِقَة.',
      prompt:'A child confidently handing a worry-shaped bundle to a warm beam of light, trust, serene' },
    { emoji:'🌦️', text:'التَّوَكُّلُ: تَعْمَلُ وَتَأْخُذُ بِالْأَسْبَاب، ثُمَّ تَثِقُ بِتَدْبِيرِ اللهِ لِلنَّتِيجَة.',
      prompt:'A child studying then raising hands in dua, effort and trust together, warm balanced scene' },
    { emoji:'💪', text:'مَنِ الَّذِي يُمْسِكُ السَّمَاءَ أَنْ تَقَع، وَالْأَرْضَ أَنْ تَمِيد؟ إِنَّهُ اللهُ الْقَوِيّ.',
      prompt:'A vast sky and steady earth held by gentle rays of light, divine power holding all, awe warm' },
    { emoji:'💚', text:'فَمَنْ سَلَّمَ أَمْرَهُ لِلْقَوِيِّ الْحَكِيم، عَاشَ خَفِيفَ الْقَلْبِ مُطْمَئِنًّا.',
      prompt:'A child walking lightly and joyfully under a warm sky, burden lifted by trust, uplifting' },
  ],
  moral:'يَقِينِي بِاللهِ يُثْمِرُ تَوَكُّلًا: أَعْمَلُ ثُمَّ أُسَلِّمُ أَمْرِي لَه. 💚',
  game:{ type:'maze', title:'سَلِّمْ أَمْرَكَ لِلْقَوِيِّ الْحَكِيمِ وَصِلْ بِأَمَان', avatar:'🪂', goal:'💚', wall:'⛈️', map:['S.#..','..#.#','#...#','..#..','#..#G'] },
  act:{ q:'مَاذَا أَفْعَلُ بَعْدَ الْأَخْذِ بِالْأَسْبَاب؟', yay:'أَحْسَنْت! أَثِقُ بِتَدْبِيرِ اللهِ الْقَوِيِّ الْحَكِيم', opts:[
    { e:'🤝', t:'أُسَلِّمُ الْأَمْرَ لِلَّهِ وَأَثِق', ok:true },
    { e:'😰', t:'أَقْلَقُ وَأَحْمِلُ كُلَّ شَيْء' },
    { e:'😴', t:'أَتْرُكُ كُلَّ شَيْء' } ] },
  dua:'حَسْبِيَ اللهُ وَنِعْمَ الْوَكِيل، عَلَيْهِ تَوَكَّلْت' },

{ id:'lamp', icon:'🏮', color:'#E67E22', title:'احْمِ مِصْبَاحَك',
  tag:'كَيْفَ نَحْفَظُ الْيَقِين؟',
  pages:[
    { emoji:'🏮', text:'يَقِينُكَ كَمِصْبَاحٍ جَمِيلٍ يُضِيءُ قَلْبَك. لَكِنَّ الْمِصْبَاحَ يَحْتَاجُ أَنْ نَحْمِيَهُ وَنَرْعَاه.',
      prompt:'A warm glowing lantern held carefully in cupped hands at night, light of faith, tender' },
    { emoji:'🌬️', text:'رِيَاحُ الْغَفْلَةِ وَالْأَصْدِقَاءِ السَّيِّئِينَ وَالشَّاشَاتِ الْكَثِيرَةِ قَدْ تُطْفِئُه.',
      prompt:'A protective hand shielding a lantern flame from wind, guarding the light, warm caution' },
    { emoji:'⛽', text:'فَنُغَذِّيهِ بِزَيْتِ الطَّاعَة: الصَّلَاة، الْقُرْآن، الذِّكْر، وَالصُّحْبَةِ الصَّالِحَة.',
      prompt:'Oil being poured to keep a lantern bright, feeding faith with worship, warm golden glow' },
    { emoji:'💚', text:'فَيَبْقَى مِصْبَاحُ يَقِينِكَ سَاطِعًا يُنِيرُ لَكَ الطَّرِيق.',
      prompt:'A bright steady lantern lighting a path forward in the dark, guided faith, warm hopeful' },
  ],
  moral:'أَحْمِي مِصْبَاحَ يَقِينِي وَأُغَذِّيهِ بِالطَّاعَةِ وَالصُّحْبَةِ الصَّالِحَة. 💚',
  game:{ type:'sort', title:'مَا الَّذِي يُغَذِّي مِصْبَاحِي وَمَا الَّذِي يُطْفِئُه؟', bins:['يُغَذِّي الْمِصْبَاح ⛽','يُطْفِئُه 🌬️'], items:[
    { e:'🕌', t:'الصَّلَاةُ وَالْقُرْآن', bin:0 },
    { e:'😴', t:'الْغَفْلَةُ الطَّوِيلَة', bin:1 },
    { e:'🤝', t:'الصُّحْبَةُ الصَّالِحَة', bin:0 },
    { e:'😠', t:'الْأَصْدِقَاءُ السَّيِّئُون', bin:1 } ] },
  act:{ q:'كَيْفَ أَحْفَظُ مِصْبَاحَ يَقِينِي مُضِيئًا؟', yay:'أَحْسَنْت! بِزَيْتِ الطَّاعَةِ وَالصُّحْبَةِ الصَّالِحَة', opts:[
    { e:'⛽', t:'أُغَذِّيهِ بِالصَّلَاةِ وَالْقُرْآنِ وَالذِّكْر', ok:true },
    { e:'🌬️', t:'أَتْرُكُهُ لِلرِّيَاح' },
    { e:'🤷', t:'لَا شَيْء' } ] },
  dua:'اللَّهُمَّ اجْعَلْ فِي قَلْبِي نُورًا وَثَبِّتْه' },

{ id:'summit', icon:'🏔️', color:'#D4A017', title:'قِمَّةُ الْيَقِين',
  tag:'عِشْ بِقَلْبٍ مُمْتَلِئٍ بِالله',
  pages:[
    { emoji:'🌟', text:'وَصَلْنَا إِلَى قِمَّةِ الرِّحْلَة! قَلْبُكَ الْآنَ يَعْرِفُ رَبَّهُ وَيُحِبُّهُ وَيُوقِنُ بِه.',
      prompt:'A child standing joyfully at a snowy summit under a brilliant sky, achievement, radiant warm' },
    { emoji:'💚', text:'لَا تَخَافُ لِأَنَّ اللهَ مَعَك، وَلَا تَقْلَقُ لِأَنَّهُ يُدَبِّرُ أَمْرَك، وَلَا تَيْأَسُ لِأَنَّهُ رَحِيم.',
      prompt:'A serene confident child with a warm glow, freedom from fear and worry, uplifting light' },
    { emoji:'❤️', text:'تَعِيشُ بِقَلْبٍ مُمْتَلِئٍ بِحُبِّ اللهِ وَالثِّقَةِ بِه، فَكُلُّ يَوْمٍ جَمِيلٌ مَعَه.',
      prompt:'A glowing full heart radiating love and light on a mountaintop, heart full of Allah, warm' },
    { emoji:'🏔️', text:'هَذِهِ قِمَّةُ الْيَقِين: أَنْ تَعْرِفَ اللهَ فَتُحِبَّهُ فَتَعْبُدَهُ مُطْمَئِنًّا سَعِيدًا.',
      prompt:'A triumphant summit view at golden sunrise with warm light filling the sky, the peak of faith' },
  ],
  moral:'عَرَفْتُ اللهَ فَأَحْبَبْتُهُ فَعَبَدْتُهُ، فَعِشْتُ بِقَلْبٍ مُمْتَلِئٍ مُطْمَئِنّ. ❤️',
  game:{ type:'pairs', title:'صِلْ كُلَّ ثَمَرَةٍ بِأَصْلِهَا', pairs:[
    ['💚 لَا أَخَاف','اللهُ مَعِي'],
    ['😌 لَا أَقْلَق','اللهُ يُدَبِّرُ أَمْرِي'],
    ['🌊 لَا أَيْأَس','اللهُ رَحِيم'] ] },
  act:{ q:'مَا قِمَّةُ رِحْلَةِ الْمَعْرِفَةِ وَالْيَقِين؟', yay:'أَحْسَنْت! قَلْبٌ مُمْتَلِئٌ بِحُبِّ اللهِ وَالثِّقَةِ بِه', opts:[
    { e:'❤️', t:'أَعْرِفُ اللهَ فَأُحِبُّهُ وَأَعْبُدُهُ مُطْمَئِنًّا', ok:true },
    { e:'💰', t:'أَجْمَعُ الْمَال' },
    { e:'🏆', t:'أَفُوزُ بِكَأْس' } ] },
  dua:'اللَّهُمَّ امْلَأْ قَلْبِي بِحُبِّكَ وَالْيَقِينِ بِك' },

]};
