/* corners/stories/minaret-little/yaqeen.js — رحلة اليقين (مَن صنع كل هذا؟) للصغار (٣–٦)
   ٢٠ حكاية مبسّطة من محطات «رحلة اليقين» — عجائبُ الخلق تدلّ على الخالق.
   كل صفحة: emoji (بديل مؤقت) + text (سطران سهلان) + prompt (وصف صورة إنجليزي لتوليدها لاحقاً). */
window.MINARET_LITTLE = window.MINARET_LITTLE || {};
window.MINARET_LITTLE.yaqeen = {
  id:'yaqeen', icon:'🔎', color:'#0E8A6D', title:'رِحْلَةُ الْيَقِين', tag:'مَنْ صَنَعَ كُلَّ هَذَا؟',
  stories:[

{ id:'dna', icon:'🧬', color:'#27AE60', title:'الشِّفْرَةُ السِّرِّيَّة',
  tag:'كِتَابٌ دَاخِلَ كُلِّ خَلِيَّة',
  pages:[
    { emoji:'🧬', text:'دَاخِلَ كُلِّ خَلِيَّةٍ مِنْ جِسْمِكَ كِتَابٌ سِرِّيٌّ عَجِيبٌ يَأْمُرُ جِسْمَكَ كَيْفَ يَنْمُو وَيَشْفَى.',
      prompt:'A glowing colorful DNA helix like a book of light inside a cell, wondrous, blue and gold' },
    { emoji:'📖', text:'مَكْتُوبٌ بِدِقَّةٍ عَجِيبَةٍ يُحَدِّدُ لَوْنَ عَيْنَيْكَ وَشَعْرِكَ وَطُولَك!',
      prompt:'A glowing code of light forming a healthy growing child silhouette, precise design, warm' },
    { emoji:'⌨️', text:'هَلْ يَكْتُبُ كِتَابٌ بِهَذِهِ الدِّقَّةِ نَفْسَهُ بِلَا كَاتِب؟ مُسْتَحِيل!',
      prompt:'A keyboard with a question mark, code needing an author, clean bright illustration' },
    { emoji:'💚', text:'إِنَّهُ صُنْعُ اللهِ الْحَكِيمِ الَّذِي صَوَّرَكَ فَأَحْسَنَ صُورَتَك.',
      prompt:'A radiant Islamic pattern around a cell of light, masterful design, teal and gold' },
  ],
  moral:'شِفْرَةُ جِسْمِي الْمُتْقَنَةُ دَلِيلٌ عَلَى خَالِقٍ حَكِيم. 💚',
  game:{ type:'sort', title:'أَيُّهُمَا يَحْتَاجُ عَقْلًا وَكَاتِبًا؟', bins:['يَحْتَاجُ كَاتِبًا حَكِيمًا 🧠','عَشْوَائِيّ 🙈'], items:[
    { e:'🧬', t:'شِفْرَةُ الْحَيَاةِ الدَّقِيقَة', bin:0 },
    { e:'🌀', t:'رُمُوزٌ مُبَعْثَرَة', bin:1 },
    { e:'📖', t:'كِتَابٌ مُرَتَّب', bin:0 },
    { e:'⌨️', t:'ضَرْبٌ عَشْوَائِيّ', bin:1 } ] },
  act:{ q:'مَنْ كَتَبَ شِفْرَةَ جِسْمِكَ الْمُتْقَنَة؟', yay:'أَحْسَنْت! اللهُ الْحَكِيمُ الْخَالِق', opts:[
    { e:'💚', t:'اللهُ الْحَكِيم', ok:true },
    { e:'🎲', t:'الصُّدْفَة' },
    { e:'🤷', t:'لَا أَحَد' } ] },
  dua:'سُبْحَانَ مَنْ صَوَّرَنِي فَأَحْسَنَ صُورَتِي' },

{ id:'woodpecker', icon:'🪵', color:'#E67E22', title:'خُوذَةُ الْأَمَان',
  tag:'نَقَّارُ الْخَشَب',
  pages:[
    { emoji:'🪵', text:'نَقَّارُ الْخَشَبِ يَضْرِبُ الشَّجَرَةَ بِرَأْسِهِ آلَافَ الْمَرَّاتِ فِي الْيَوْم! فَلِمَاذَا لَا يَتَأَلَّم؟',
      prompt:'A colorful woodpecker pecking a tree trunk with motion lines, energetic, bright forest, storybook' },
    { emoji:'🛡️', text:'لِأَنَّ اللهَ جَعَلَ فِي رَأْسِهِ خُوذَةً خَاصَّةً تَحْمِي دِمَاغَهُ مِنَ الِارْتِجَاج.',
      prompt:'A cute cross-section of a woodpecker head showing a cushioned protective design, gentle science' },
    { emoji:'🔨', text:'لِسَانُهُ الطَّوِيلُ يَلْتَفُّ حَوْلَ دِمَاغِهِ كَوِسَادَةٍ إِضَافِيَّة! تَصْمِيمٌ عَجِيب.',
      prompt:'A woodpecker with a long tongue wrapping like a cushion, clever design, warm friendly illustration' },
    { emoji:'💚', text:'مَنْ صَمَّمَ هَذِهِ الْخُوذَةَ الْمِثَالِيَّة؟ اللهُ الْخَالِقُ الْحَكِيم.',
      prompt:'A woodpecker perched happily on a tree under warm light, perfect design, serene' },
  ],
  moral:'خُوذَةُ نَقَّارِ الْخَشَبِ الْمُتْقَنَةُ دَلِيلُ خَالِقٍ حَكِيم. 💚',
  game:{ type:'find', title:'جِدْ نَقَّارَاتِ الْخَشَبِ الْأَرْبَعَةَ فِي الْغَابَة', target:'🪵', count:4, distractors:['🌲','🍂'], size:12 },
  act:{ q:'لِمَاذَا لَا يَتَأَلَّمُ رَأْسُ نَقَّارِ الْخَشَب؟', yay:'أَحْسَنْت! خُوذَةٌ صَمَّمَهَا اللهُ لِتَحْمِيَه', opts:[
    { e:'🛡️', t:'خُوذَةٌ خَاصَّةٌ مِنْ صُنْعِ الله', ok:true },
    { e:'🎲', t:'صُدْفَة' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'سُبْحَانَ الْخَالِقِ الْحَكِيم' },

{ id:'bat', icon:'🦇', color:'#5B4B8A', title:'الرُّؤْيَةُ بِالصَّوْت',
  tag:'الْخُفَّاش',
  pages:[
    { emoji:'🦇', text:'الْخُفَّاشُ يَطِيرُ فِي الظَّلَامِ الدَّامِسِ وَلَا يَصْطَدِمُ بِشَيْء! كَيْفَ يَرَى؟',
      prompt:'A bat flying gracefully through a dark cave avoiding rocks, night scene, gentle glow, storybook' },
    { emoji:'🔊', text:'يُطْلِقُ أَصْوَاتًا لَا نَسْمَعُهَا، تَرْتَدُّ إِلَيْهِ فَيَعْرِفُ أَيْنَ كُلُّ شَيْء — يَرَى بِالصَّوْت!',
      prompt:'Sound waves shown as gentle glowing ripples bouncing off objects to a bat, echolocation, warm' },
    { emoji:'📡', text:'صَنَعَ الْبَشَرُ الرَّادَارَ بَعْدَ سِنِينَ طَوِيلَة، وَاللهُ خَلَقَهُ فِي الْخُفَّاشِ مِنْ زَمَان!',
      prompt:'A friendly radar dish beside a bat, both using sound to see, clever comparison, bright' },
    { emoji:'💚', text:'مَنْ عَلَّمَ الْخُفَّاشَ هَذَا؟ اللهُ الَّذِي أَتْقَنَ كُلَّ شَيْء.',
      prompt:'A bat resting peacefully in a cave with soft warm light, wondrous design, serene' },
  ],
  moral:'رَادَارُ الْخُفَّاشِ الْعَجِيبُ دَلِيلٌ عَلَى خَالِقٍ عَلِيم. 💚',
  game:{ type:'maze', title:'سَاعِدِ الْخُفَّاشَ يَعْبُرُ الْكَهْفَ الْمُظْلِمَ بِالصَّوْت', avatar:'🦇', goal:'🌙', wall:'🪨', map:['S#...','.#.#.','.#.#.','...#.','##..G'] },
  act:{ q:'كَيْفَ يَرَى الْخُفَّاشُ فِي الظَّلَام؟', yay:'أَحْسَنْت! بِالصَّوْتِ الَّذِي عَلَّمَهُ اللهُ إِيَّاه', opts:[
    { e:'🔊', t:'بِالصَّوْتِ الَّذِي يَرْتَدُّ إِلَيْه', ok:true },
    { e:'🔦', t:'بِمِصْبَاح' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'سُبْحَانَ مَنْ أَتْقَنَ كُلَّ شَيْءٍ خَلَقَه' },

{ id:'penguin', icon:'🐧', color:'#2980B9', title:'مِعْطَفُ الْجَلِيد',
  tag:'الْبِطْرِيق',
  pages:[
    { emoji:'🐧', text:'الْبِطْرِيقُ يَعِيشُ فِي أَبْرَدِ مَكَانٍ عَلَى الْأَرْض، وَلَا يَتَجَمَّد! كَيْف؟',
      prompt:'A cute penguin standing on ice in a snowy landscape, cozy and warm despite cold, storybook' },
    { emoji:'🧥', text:'أَعْطَاهُ اللهُ رِيشًا كَثِيفًا وَطَبَقَةَ دُهْنٍ كَمِعْطَفٍ دَافِئٍ لَا يَنْزِعُه.',
      prompt:'A penguin with fluffy layered feathers glowing warm inside the cold, natural coat, gentle' },
    { emoji:'🦶', text:'وَأَقْدَامُهُ مُصَمَّمَةٌ بِذَكَاءٍ فَلَا تَتَجَمَّدُ عَلَى الْجَلِيد!',
      prompt:'Close-up of penguin feet on ice with a clever warm design, staying unfrozen, cute illustration' },
    { emoji:'💚', text:'مَنْ فَصَّلَ لِلْبِطْرِيقِ مِعْطَفَهُ الْمِثَالِيّ؟ اللهُ الرَّحِيمُ بِخَلْقِه.',
      prompt:'Penguins huddling warmly together under soft light in snow, cared-for creation, serene' },
  ],
  moral:'مِعْطَفُ الْبِطْرِيقِ الدَّافِئُ دَلِيلُ خَالِقٍ رَحِيمٍ حَكِيم. 💚',
  game:{ type:'pairs', title:'صِلْ كُلَّ حَيَوَانٍ بِمَا يَحْمِيه', pairs:[
    ['🐧 الْبِطْرِيق','مِعْطَفُ الرِّيشِ وَالدُّهْن'],
    ['🐪 الْجَمَل','يَتَحَمَّلُ الْعَطَش'],
    ['🐻‍❄️ الدُّبُّ الْقُطْبِيّ','فَرْوٌ كَثِيف'] ] },
  act:{ q:'لِمَاذَا لَا يَتَجَمَّدُ الْبِطْرِيقُ فِي الْبَرْد؟', yay:'أَحْسَنْت! مِعْطَفٌ صَمَّمَهُ اللهُ لَه', opts:[
    { e:'🧥', t:'رِيشٌ وَدُهْنٌ دَافِئٌ مِنْ صُنْعِ الله', ok:true },
    { e:'🔥', t:'يُشْعِلُ نَارًا' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'سُبْحَانَ الرَّحِيمِ بِخَلْقِه' },

{ id:'spider', icon:'🕷️', color:'#16A085', title:'أَقْوَى مِنَ الْفُولَاذ',
  tag:'الْعَنْكَبُوت',
  pages:[
    { emoji:'🕸️', text:'خَيْطُ الْعَنْكَبُوتِ الرَّفِيعُ أَقْوَى مِنَ الْفُولَاذِ بِنَفْسِ الْوَزْن! أَتُصَدِّق؟',
      prompt:'A dew-covered spider web glistening in morning light, delicate yet strong, storybook' },
    { emoji:'🕷️', text:'يَصْنَعُ الْعَنْكَبُوتُ بَيْتَهُ بِهَنْدَسَةٍ دَقِيقَةٍ مُتْقَنَةٍ بِلَا مِسْطَرَةٍ وَلَا آلَة.',
      prompt:'A perfectly geometric spider web being spun, precise engineering, gentle wonder, warm' },
    { emoji:'🏗️', text:'يَعْجِزُ الْبَشَرُ عَنْ صُنْعِ خَيْطٍ مِثْلِه! فَمَنْ عَلَّمَ الْعَنْكَبُوتَ هَذَا؟',
      prompt:'A tiny spider beside a big construction crane, comparison of engineering skill, playful bright' },
    { emoji:'💚', text:'إِنَّهُ اللهُ الَّذِي أَعْطَى كُلَّ مَخْلُوقٍ مَهَارَتَه.',
      prompt:'A spider resting on a perfect web glowing softly under warm light, gifted design, serene' },
  ],
  moral:'خَيْطُ الْعَنْكَبُوتِ الْعَجِيبُ دَلِيلٌ عَلَى خَالِقٍ عَلِيم. 💚',
  game:{ type:'find', title:'اجْمَعْ بُيُوتَ الْعَنْكَبُوتِ الْخَمْسَ الْمُتْقَنَة', target:'🕸️', count:5, distractors:['🕷️','🍂'], size:12 },
  act:{ q:'خَيْطُ الْعَنْكَبُوتِ الرَّفِيعُ كَيْفَ هُوَ؟', yay:'أَحْسَنْت! أَقْوَى مِنَ الْفُولَاذِ بِصُنْعِ الله', opts:[
    { e:'💪', t:'أَقْوَى مِنَ الْفُولَاذِ بِنَفْسِ الْوَزْن', ok:true },
    { e:'🪶', t:'ضَعِيفٌ يَنْقَطِعُ فَوْرًا' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'سُبْحَانَ مَنْ أَعْطَى كُلَّ شَيْءٍ خَلْقَه' },

{ id:'birds', icon:'🐦', color:'#3498DB', title:'جِهَازُ التَّوْجِيهِ السِّرِّيّ',
  tag:'الطُّيُورُ الْمُهَاجِرَة',
  pages:[
    { emoji:'🐦', text:'تَطِيرُ الطُّيُورُ الْمُهَاجِرَةُ آلَافَ الْكِيلُومِتْرَاتِ عَبْرَ الْبِحَارِ وَلَا تَضِلُّ الطَّرِيق!',
      prompt:'A flock of birds flying across a vast sky over the sea in formation, long journey, warm dawn' },
    { emoji:'🧭', text:'كَيْفَ تَعْرِفُ الطَّرِيق بِلَا خَرِيطَةٍ وَلَا جِهَاز؟ اللهُ جَعَلَ فِيهَا بَوْصَلَةً خَفِيَّة!',
      prompt:'A bird with a gentle glowing compass symbol, natural navigation, clever design, warm' },
    { emoji:'🌍', text:'تَشْعُرُ بِمَجَالِ الْأَرْضِ وَتَتْبَعُ النُّجُومَ فَتَصِلُ إِلَى بَيْتِهَا بِالضَّبْط.',
      prompt:'A bird following stars over a globe at night, guided flight, serene and wondrous' },
    { emoji:'💚', text:'مَنْ عَلَّمَ الطُّيُورَ الطَّرِيق؟ اللهُ الْهَادِي الْعَلِيم.',
      prompt:'Birds arriving at a warm nest at journeys end under gentle light, safe arrival, tender' },
  ],
  moral:'بَوْصَلَةُ الطُّيُورِ الْخَفِيَّةُ دَلِيلُ خَالِقٍ هَادٍ عَلِيم. 💚',
  game:{ type:'maze', title:'أَرْشِدِ الطَّائِرَ الْمُهَاجِرَ إِلَى بَيْتِهِ عَبْرَ الْبَحْر', avatar:'🐦', goal:'🪺', wall:'🌊', map:['S..#.','##.#.','.#...','.#.##','...#G'] },
  act:{ q:'كَيْفَ تَعْرِفُ الطُّيُورُ طَرِيقَهَا الطَّوِيل؟', yay:'أَحْسَنْت! بَوْصَلَةٌ خَفِيَّةٌ مِنْ صُنْعِ الله', opts:[
    { e:'🧭', t:'بَوْصَلَةٌ خَفِيَّةٌ جَعَلَهَا اللهُ فِيهَا', ok:true },
    { e:'📱', t:'بِهَاتِفٍ وَخَرِيطَة' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'سُبْحَانَ اللهِ الْهَادِي الْعَلِيم' },

{ id:'octopus', icon:'🐙', color:'#9B59B6', title:'الْبَدْلَةُ الْمُخْفِيَة',
  tag:'الْأَخْطَبُوط',
  pages:[
    { emoji:'🐙', text:'الْأَخْطَبُوطُ يُغَيِّرُ لَوْنَهُ فِي ثَانِيَةٍ لِيَخْتَفِيَ تَمَامًا! كَأَنَّهُ سِحْر.',
      prompt:'A colorful octopus blending into coral changing colors, camouflage magic, vibrant ocean scene' },
    { emoji:'🎨', text:'يُطَابِقُ لَوْنَ الصَّخْرَةِ وَالرَّمْلِ وَالْمَرْجَانِ فَلَا يَرَاهُ عَدُوُّه.',
      prompt:'An octopus perfectly matching a rocky seabed, invisible camouflage, wondrous, warm ocean light' },
    { emoji:'👗', text:'أَذْكَى بَدْلَةِ تَخَفٍّ فِي الْعَالَم! صَنَعَهَا اللهُ لِيَحْمِيَه.',
      prompt:'An octopus half-blended half-visible showing its color change, amazing design, playful bright' },
    { emoji:'💚', text:'مَنْ أَعْطَى الْأَخْطَبُوطَ هَذِهِ الْقُدْرَة؟ اللهُ الْخَالِقُ الرَّحِيم.',
      prompt:'A content octopus resting among colorful coral under soft light, cared-for creation, serene' },
  ],
  moral:'بَدْلَةُ الْأَخْطَبُوطِ الْعَجِيبَةُ دَلِيلُ خَالِقٍ حَكِيمٍ رَحِيم. 💚',
  game:{ type:'find', title:'جِدِ الْأَخَاطِيبَ الْأَرْبَعَةَ الْمُخْتَبِئَةَ بِأَلْوَانِهَا', target:'🐙', count:4, distractors:['🪨','🐚'], size:12 },
  act:{ q:'كَيْفَ يَخْتَفِي الْأَخْطَبُوطُ مِنْ عَدُوِّه؟', yay:'أَحْسَنْت! يُغَيِّرُ لَوْنَهُ بِقُدْرَةٍ مِنَ الله', opts:[
    { e:'🎨', t:'يُغَيِّرُ لَوْنَهُ لِيُطَابِقَ مَا حَوْلَه', ok:true },
    { e:'🏃', t:'يَجْرِي بَعِيدًا' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'سُبْحَانَ الْخَالِقِ الْحَكِيم' },

{ id:'camel', icon:'🐪', color:'#D4A017', title:'سَيَّارَةُ الصَّحْرَاء',
  tag:'الْجَمَل',
  pages:[
    { emoji:'🐪', text:'الْجَمَلُ يَعِيشُ فِي الصَّحْرَاءِ الْحَارَّةِ أَيَّامًا بِلَا مَاء! كَيْفَ يَتَحَمَّل؟',
      prompt:'A camel walking across golden desert dunes under the sun, resilient, warm storybook style' },
    { emoji:'💧', text:'أَعْطَاهُ اللهُ سَنَامًا يَخْزِنُ الطَّاقَة، وَجِسْمًا يَحْفَظُ الْمَاء.',
      prompt:'A cheerful camel with a prominent hump storing energy, clever desert design, warm bright' },
    { emoji:'👁️', text:'وَرُمُوشًا طَوِيلَةً تَحْمِي عَيْنَيْهِ مِنَ الرَّمْل، وَأَقْدَامًا وَاسِعَةً لَا تَغُوصُ فِي الرَّمْل!',
      prompt:'Close-up of a camel with long eyelashes and wide feet on sand, adapted design, gentle detail' },
    { emoji:'💚', text:'مَنْ جَهَّزَ الْجَمَلَ لِلصَّحْرَاء؟ اللهُ الْحَكِيمُ. أَفَلَا يَنْظُرُونَ إِلَى الْإِبِلِ كَيْفَ خُلِقَت؟',
      prompt:'A camel resting calmly in the desert at sunset under warm light, perfect design, serene' },
  ],
  moral:'الْجَمَلُ الْمُجَهَّزُ لِلصَّحْرَاءِ دَلِيلُ خَالِقٍ حَكِيم. 💚',
  game:{ type:'pairs', title:'صِلْ كُلَّ جُزْءٍ مِنَ الْجَمَلِ بِفَائِدَتِه', pairs:[
    ['🐪 السَّنَام','يَخْزِنُ الطَّاقَة'],
    ['👁️ الرُّمُوشُ الطَّوِيلَة','تَحْمِي مِنَ الرَّمْل'],
    ['🦶 الْأَقْدَامُ الْوَاسِعَة','لَا تَغُوصُ فِي الرَّمْل'] ] },
  act:{ q:'مَنْ جَهَّزَ الْجَمَلَ لِيَعِيشَ فِي الصَّحْرَاء؟', yay:'أَحْسَنْت! اللهُ الْحَكِيمُ خَلَقَهُ مُتْقَنًا', opts:[
    { e:'💚', t:'اللهُ الْخَالِقُ الْحَكِيم', ok:true },
    { e:'🎲', t:'الصُّدْفَة' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'أَفَلَا يَنْظُرُونَ إِلَى الْإِبِلِ كَيْفَ خُلِقَت' },

{ id:'beaver', icon:'🦫', color:'#1ABC9C', title:'مُهَنْدِسُ الْمِيَاه',
  tag:'الْقُنْدُس',
  pages:[
    { emoji:'🦫', text:'الْقُنْدُسُ يَبْنِي سَدًّا كَبِيرًا فِي النَّهْرِ بِأَغْصَانِ الشَّجَرِ بِلَا مُعَلِّمٍ وَلَا هَنْدَسَة!',
      prompt:'A beaver building a dam of branches across a river, busy and clever, warm nature scene' },
    { emoji:'🌊', text:'سَدُّهُ قَوِيٌّ يُوقِفُ الْمَاءَ وَيَصْنَعُ بُحَيْرَةً آمِنَةً لِبَيْتِه.',
      prompt:'A sturdy beaver dam holding back water forming a calm pond, engineering marvel, serene' },
    { emoji:'🏠', text:'وَيَبْنِي بَيْتَهُ بِمَدْخَلٍ تَحْتَ الْمَاءِ لِيَحْمِيَهُ مِنَ الْأَعْدَاء! تَصْمِيمٌ ذَكِيّ.',
      prompt:'A cozy beaver lodge with an underwater entrance shown in cutaway, clever home, warm gentle' },
    { emoji:'💚', text:'مَنْ عَلَّمَ الْقُنْدُسَ الْهَنْدَسَة؟ اللهُ الَّذِي أَلْهَمَ كُلَّ مَخْلُوقٍ عَمَلَه.',
      prompt:'A beaver resting proudly by its dam under warm light, gifted skill, serene illustration' },
  ],
  moral:'هَنْدَسَةُ الْقُنْدُسِ الْعَجِيبَةُ دَلِيلُ خَالِقٍ عَلِيم. 💚',
  game:{ type:'order', title:'رَتِّبْ كَيْفَ يَبْنِي الْقُنْدُسُ سَدَّه', items:[
    { e:'🪵', t:'يَقْطَعُ الْأَغْصَان' },
    { e:'🏗️', t:'يَرُصُّهَا فِي النَّهْر' },
    { e:'🌊', t:'يُوقِفُ الْمَاء' },
    { e:'🏠', t:'يَبْنِي بَيْتَهُ الْآمِن' } ] },
  act:{ q:'مَنْ عَلَّمَ الْقُنْدُسَ بِنَاءَ السَّدّ؟', yay:'أَحْسَنْت! اللهُ أَلْهَمَهُ عَمَلَه', opts:[
    { e:'💚', t:'اللهُ الَّذِي أَلْهَمَه', ok:true },
    { e:'🏫', t:'مَدْرَسَةُ هَنْدَسَة' },
    { e:'🤷', t:'لَا أَحَد' } ] },
  dua:'سُبْحَانَ مَنْ أَلْهَمَ كُلَّ مَخْلُوقٍ عَمَلَه' },

{ id:'bees', icon:'🐝', color:'#F39C12', title:'مَصْنَعُ السُّدَاسِيَّات',
  tag:'النَّحْل',
  pages:[
    { emoji:'🐝', text:'النَّحْلُ يَبْنِي بُيُوتَهُ عَلَى شَكْلِ سُدَاسِيَّاتٍ مُتْقَنَةٍ مُتَسَاوِيَةٍ تَمَامًا!',
      prompt:'A honeycomb of perfect hexagons with bees, geometric precision, golden warm light, storybook' },
    { emoji:'⬡', text:'الشَّكْلُ السُّدَاسِيُّ أَذْكَى شَكْلٍ يُوَفِّرُ الْمَكَانَ وَالشَّمْع — كَيْفَ عَرَفَ النَّحْل؟',
      prompt:'Neat hexagon cells fitting perfectly together, efficient design, bright clean illustration' },
    { emoji:'🍯', text:'ثُمَّ يَصْنَعُ الْعَسَلَ الشِّفَاءَ اللَّذِيذَ الَّذِي ذَكَرَهُ اللهُ فِي الْقُرْآن.',
      prompt:'Golden honey dripping from a honeycomb, sweet and healing, warm inviting glow' },
    { emoji:'💚', text:'مَنْ عَلَّمَ النَّحْلَ هَذَا؟ اللهُ: وَأَوْحَى رَبُّكَ إِلَى النَّحْل.',
      prompt:'Bees flying happily around flowers under warm sun, inspired creatures, serene' },
  ],
  moral:'سُدَاسِيَّاتُ النَّحْلِ الْمُتْقَنَةُ دَلِيلُ خَالِقٍ حَكِيم. 💚',
  game:{ type:'find', title:'اجْمَعْ خَلَايَا الْعَسَلِ السُّدَاسِيَّةَ السِّتّ', target:'⬡', count:6, distractors:['🔺','⭕'], size:12 },
  act:{ q:'مَنْ أَوْحَى إِلَى النَّحْلِ صُنْعَ بُيُوتِهِ وَعَسَلِه؟', yay:'أَحْسَنْت! وَأَوْحَى رَبُّكَ إِلَى النَّحْل', opts:[
    { e:'💚', t:'اللهُ رَبُّ الْعَالَمِين', ok:true },
    { e:'🏫', t:'مَدْرَسَةُ النَّحْل' },
    { e:'🤷', t:'لَا أَحَد' } ] },
  dua:'وَأَوْحَى رَبُّكَ إِلَى النَّحْل، سُبْحَانَ الْحَكِيم' },

{ id:'ants', icon:'🐜', color:'#C0392B', title:'الْمَدِينَةُ تَحْتَ الْأَرْض',
  tag:'النَّمْل',
  pages:[
    { emoji:'🐜', text:'النَّمْلُ يَبْنِي مَدِينَةً كَبِيرَةً تَحْتَ الْأَرْضِ فِيهَا غُرَفٌ وَطُرُقٌ وَمَخَازِن!',
      prompt:'A cutaway of an underground ant colony with tunnels rooms and storage, busy city, warm earthy' },
    { emoji:'🤝', text:'كُلُّ نَمْلَةٍ تَعْرِفُ عَمَلَهَا وَتَتَعَاوَنُ مَعَ أَخَوَاتِهَا بِنِظَامٍ عَجِيب.',
      prompt:'Ants working together carrying items in an organized line, teamwork, gentle bright illustration' },
    { emoji:'🌾', text:'تَخْزِنُ الطَّعَامَ لِلشِّتَاءِ وَتُنَظِّفُ مَدِينَتَهَا — أُمَّةٌ صَغِيرَةٌ مُنَظَّمَة.',
      prompt:'Ants storing grain in tidy underground chambers, planning ahead, warm cooperative scene' },
    { emoji:'💚', text:'مَنْ عَلَّمَ النَّمْلَ هَذَا النِّظَام؟ اللهُ الَّذِي خَلَقَهُم أُمَمًا مِثْلَنَا.',
      prompt:'An ant hill glowing warmly at sunset with tiny ants around it, organized creation, serene' },
  ],
  moral:'مَدِينَةُ النَّمْلِ الْمُنَظَّمَةُ دَلِيلُ خَالِقٍ عَلِيم. 💚',
  game:{ type:'maze', title:'أَوْصِلِ النَّمْلَةَ إِلَى مَخْزَنِ الطَّعَامِ تَحْتَ الْأَرْض', avatar:'🐜', goal:'🌾', wall:'🪨', map:['S.#..','.###.','...#.','##...','#..#G'] },
  act:{ q:'كَيْفَ يَعِيشُ النَّمْلُ فِي مَدِينَتِه؟', yay:'أَحْسَنْت! بِنِظَامٍ وَتَعَاوُنٍ عَلَّمَهُ اللهُ لَهُم', opts:[
    { e:'🤝', t:'بِنِظَامٍ وَتَعَاوُنٍ عَجِيب', ok:true },
    { e:'😴', t:'بِلَا نِظَام' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'سُبْحَانَ مَنْ خَلَقَ كُلَّ شَيْءٍ فَقَدَّرَه' },

{ id:'immune', icon:'🛡️', color:'#E74C3C', title:'الْجَيْشُ الصَّغِير',
  tag:'جِهَازُ الْمَنَاعَة',
  pages:[
    { emoji:'🦠', text:'دَاخِلَ جِسْمِكَ جَيْشٌ صَغِيرٌ لَا تَرَاهُ يُحَارِبُ الْجَرَاثِيمَ لَيْلَ نَهَار!',
      prompt:'Friendly defender cells fighting germs inside the body, tiny army, bright gentle science illustration' },
    { emoji:'⚔️', text:'حِينَ تَدْخُلُ جُرْثُومَةٌ، يُسْرِعُ الْجَيْشُ لِيَحْمِيَكَ وَيَشْفِيَك بِلَا أَنْ تَشْعُر.',
      prompt:'Defender cells rushing to protect against a germ, heroic tiny soldiers, warm bright' },
    { emoji:'🧠', text:'وَيَتَذَكَّرُ الْجُرْثُومَةَ لِيَحْمِيَكَ مِنْهَا مَرَّةً أُخْرَى — جَيْشٌ ذَكِيّ!',
      prompt:'A cell holding a memory badge of a germ, smart immune memory, playful bright illustration' },
    { emoji:'💚', text:'مَنْ جَعَلَ هَذَا الْجَيْشَ فِي جِسْمِك؟ اللهُ الَّذِي يَحْفَظُكَ مِنْ حَيْثُ لَا تَعْلَم.',
      prompt:'A healthy happy child glowing with inner protective light, guarded within, warm serene' },
  ],
  moral:'جَيْشُ الْمَنَاعَةِ الْخَفِيُّ دَلِيلُ خَالِقٍ رَحِيمٍ حَفِيظ. 💚',
  game:{ type:'sort', title:'مَاذَا يَفْعَلُ جَيْشُ الْمَنَاعَة؟', bins:['يَحْمِينِي 🛡️','يُؤْذِينِي 🚫'], items:[
    { e:'⚔️', t:'يُحَارِبُ الْجَرَاثِيم', bin:0 },
    { e:'🧠', t:'يَتَذَكَّرُ الْأَعْدَاء', bin:0 },
    { e:'🩹', t:'يَشْفِي الْجُرُوح', bin:0 },
    { e:'💥', t:'يُخَرِّبُ الْجِسْم', bin:1 } ] },
  act:{ q:'مَنْ جَعَلَ فِي جِسْمِكَ جَيْشًا يَحْمِيك؟', yay:'أَحْسَنْت! اللهُ الَّذِي يَحْفَظُك', opts:[
    { e:'💚', t:'اللهُ الْحَفِيظُ الرَّحِيم', ok:true },
    { e:'💊', t:'الصَّيْدَلِيَّة' },
    { e:'🤷', t:'لَا أَحَد' } ] },
  dua:'سُبْحَانَ اللهِ الْحَفِيظِ الرَّحِيم' },

{ id:'sunmoon', icon:'☀️', color:'#F1C40F', title:'السَّاعَةُ الْمُتْقَنَة',
  tag:'الشَّمْسُ وَالْقَمَر',
  pages:[
    { emoji:'☀️', text:'الشَّمْسُ تُشْرِقُ كُلَّ صَبَاحٍ فِي وَقْتِهَا بِالضَّبْط، وَالْقَمَرُ يَتَغَيَّرُ بِنِظَامٍ عَجِيب.',
      prompt:'The sun rising precisely over a horizon with the moon in the sky, cosmic clockwork, warm dawn' },
    { emoji:'⏰', text:'كَأَنَّهُمَا سَاعَةٌ كَبِيرَةٌ لَا تَتَأَخَّرُ ثَانِيَةً وَلَا تَخْطَأ أَبَدًا!',
      prompt:'A giant celestial clock made of sun and moon movements, perfect timing, radiant illustration' },
    { emoji:'📅', text:'بِهِمَا نَعْرِفُ اللَّيْلَ وَالنَّهَارَ وَالشُّهُورَ وَالسِّنِينَ وَمَوَاقِيتَ الصَّلَاة.',
      prompt:'Day and night cycle with a moon calendar phases, orderly time, warm gentle scene' },
    { emoji:'💚', text:'مَنْ يُدِيرُ هَذِهِ السَّاعَةَ الْمُتْقَنَة؟ اللهُ: الشَّمْسُ وَالْقَمَرُ بِحُسْبَان.',
      prompt:'Sun and moon in a harmonious cosmic dance under a starry sky, divine order, teal and gold' },
  ],
  moral:'سَاعَةُ الشَّمْسِ وَالْقَمَرِ الْمُتْقَنَةُ دَلِيلُ خَالِقٍ حَكِيم. 💚',
  game:{ type:'pairs', title:'صِلْ كُلَّ شَيْءٍ بِفَائِدَتِه', pairs:[
    ['☀️ الشَّمْس','النَّهَارُ وَالدِّفْء'],
    ['🌙 الْقَمَر','اللَّيْلُ وَالشُّهُور'],
    ['⏰ نِظَامُهُمَا','مَوَاقِيتُ الصَّلَاة'] ] },
  act:{ q:'لِمَاذَا تُشْرِقُ الشَّمْسُ فِي وَقْتِهَا دَائِمًا؟', yay:'أَحْسَنْت! بِنِظَامٍ أَتْقَنَهُ الله', opts:[
    { e:'💚', t:'بِنِظَامٍ دَقِيقٍ مِنَ الله', ok:true },
    { e:'🎲', t:'صُدْفَةً كُلَّ يَوْم' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'الشَّمْسُ وَالْقَمَرُ بِحُسْبَان، سُبْحَانَ الْحَكِيم' },

{ id:'water', icon:'☁️', color:'#5DADE2', title:'تَوْصِيلُ السَّحَاب',
  tag:'دَوْرَةُ الْمَاء',
  pages:[
    { emoji:'☁️', text:'الْمَاءُ يَتَبَخَّرُ مِنَ الْبَحْرِ فَيَصْعَدُ سَحَابًا، ثُمَّ يَنْزِلُ مَطَرًا عَذْبًا نَشْرَبُه!',
      prompt:'Water evaporating from the sea, forming clouds, then raining on green land, water cycle, warm bright' },
    { emoji:'💧', text:'مَاءُ الْبَحْرِ مَالِح، لَكِنَّ اللهَ يُنَقِّيهِ فِي السَّحَابِ فَيَنْزِلُ عَذْبًا صَافِيًا.',
      prompt:'A rain cloud releasing pure fresh droplets over fields, natural purification, gentle warm' },
    { emoji:'🚚', text:'السَّحَابُ كَشَاحِنَةِ تَوْصِيلٍ عِمْلَاقَةٍ تَحْمِلُ الْمَاءَ إِلَى الْأَرْضِ الْبَعِيدَة!',
      prompt:'A friendly cloud carrying water like a delivery truck over dry land, provision delivered, playful' },
    { emoji:'💚', text:'مَنْ صَمَّمَ هَذِهِ الدَّوْرَةَ الْعَجِيبَة؟ اللهُ الَّذِي أَنْزَلَ مِنَ السَّمَاءِ مَاءً.',
      prompt:'Green fields blooming after rain under a warm rainbow sky, life-giving water, serene' },
  ],
  moral:'دَوْرَةُ الْمَاءِ الْعَجِيبَةُ دَلِيلُ خَالِقٍ رَحِيمٍ حَكِيم. 💚',
  game:{ type:'order', title:'رَتِّبْ دَوْرَةَ الْمَاء', items:[
    { e:'🌊', t:'الْمَاءُ يَتَبَخَّرُ مِنَ الْبَحْر' },
    { e:'☁️', t:'يَصْعَدُ سَحَابًا' },
    { e:'🌧️', t:'يَنْزِلُ مَطَرًا عَذْبًا' },
    { e:'🌱', t:'يُحْيِي الْأَرْض' } ] },
  act:{ q:'مَاءُ الْبَحْرِ مَالِح، فَكَيْفَ يَنْزِلُ الْمَطَرُ عَذْبًا؟', yay:'أَحْسَنْت! اللهُ يُنَقِّيهِ فِي السَّحَاب', opts:[
    { e:'💧', t:'اللهُ يُنَقِّيهِ فِي السَّحَاب', ok:true },
    { e:'🧂', t:'يَبْقَى مَالِحًا' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'الْحَمْدُ لِلَّهِ الَّذِي أَنْزَلَ مِنَ السَّمَاءِ مَاءً' },

{ id:'trees', icon:'🌳', color:'#27AE60', title:'الْمَصْنَعُ الْأَخْضَر',
  tag:'الْأَشْجَارُ وَالْأُكْسِجِين',
  pages:[
    { emoji:'🌳', text:'الْأَشْجَارُ مَصَانِعُ خَضْرَاءُ صَامِتَة: تَأْخُذُ الْهَوَاءَ الَّذِي نَزْفُرُهُ وَتُعْطِينَا الْأُكْسِجِينَ لِنَتَنَفَّس!',
      prompt:'A lush green tree with gentle arrows showing air exchange, silent green factory, warm bright' },
    { emoji:'🌬️', text:'بِلَا آلَاتٍ وَلَا ضَجِيج، تُنَظِّفُ الْهَوَاءَ وَتَصْنَعُ لَنَا مَا نَحْتَاجُ لِلْحَيَاة.',
      prompt:'Fresh clean air flowing from tree leaves shown as soft glowing breeze, pure air, serene' },
    { emoji:'🍎', text:'وَتُعْطِينَا الظِّلَّ وَالثِّمَارَ وَالْخَشَبَ — هَدَايَا كَثِيرَةٌ مِنْ مَخْلُوقٍ صَامِت.',
      prompt:'A tree giving shade, fruit and shelter to happy children, generous nature, warm cozy scene' },
    { emoji:'💚', text:'مَنْ صَنَعَ هَذَا الْمَصْنَعَ الْأَخْضَرَ الْعَجِيب؟ اللهُ الرَّزَّاقُ الْكَرِيم.',
      prompt:'A grand green tree glowing warmly under sunlight, life-giving gift, serene illustration' },
  ],
  moral:'الْأَشْجَارُ مَصَانِعُ الْأُكْسِجِينِ دَلِيلُ خَالِقٍ رَزَّاقٍ كَرِيم. 💚',
  game:{ type:'find', title:'اغْرِسِ الْأَشْجَار! اجْمَعِ الْأَشْجَارَ الْخَمْسَ الْخَضْرَاء', target:'🌳', count:5, distractors:['🍂','🪨'], size:12 },
  act:{ q:'مَاذَا تُعْطِينَا الْأَشْجَارُ لِنَتَنَفَّس؟', yay:'أَحْسَنْت! الْأُكْسِجِينَ بِفَضْلِ الله', opts:[
    { e:'🌬️', t:'الْأُكْسِجِينَ وَالْهَوَاءَ النَّقِيّ', ok:true },
    { e:'💨', t:'الدُّخَان' },
    { e:'🤷', t:'لَا شَيْء' } ] },
  dua:'الْحَمْدُ لِلَّهِ الرَّزَّاقِ الْكَرِيم' },

{ id:'eye', icon:'👁️', color:'#8E44AD', title:'الْكَامِيرَا الْمُذْهِلَة',
  tag:'الْعَيْن',
  pages:[
    { emoji:'👁️', text:'عَيْنُكَ كَامِيرَا مُذْهِلَةٌ تَرَى مَلَايِينَ الْأَلْوَان، وَتَعْمَلُ فِي النُّورِ وَالظَّلَام!',
      prompt:'A beautiful detailed eye reflecting a colorful scene, ultimate camera, warm gentle illustration' },
    { emoji:'📷', text:'أَغْلَى كَامِيرَا صَنَعَهَا الْبَشَرُ لَا تُضَاهِي عَيْنَكَ الصَّغِيرَة!',
      prompt:'A tiny eye beside a big camera, the eye clearly superior, playful comparison, bright' },
    { emoji:'💧', text:'وَتُنَظِّفُ نَفْسَهَا وَتُصْلِحُ نَفْسَهَا، وَلَهَا رُمُوشٌ وَجُفُونٌ تَحْمِيهَا!',
      prompt:'An eye with protective eyelashes and lids, self-cleaning wonder, gentle detail, warm' },
    { emoji:'💚', text:'مَنْ صَنَعَ هَذِهِ الْكَامِيرَا الْعَجِيبَة؟ اللهُ الَّذِي جَعَلَ لَكَ السَّمْعَ وَالْأَبْصَار.',
      prompt:'A child looking at a beautiful view with bright happy eyes, grateful for sight, warm from behind' },
  ],
  moral:'عَيْنِي الْكَامِيرَا الْعَجِيبَةُ دَلِيلُ خَالِقٍ حَكِيم. 💚',
  game:{ type:'sort', title:'مَنْ صَنَعَ عَيْنَكَ الْعَجِيبَة؟', bins:['صُنْعُ اللهِ الْحَكِيم 💚','لَا يَصْنَعُهَا 🚫'], items:[
    { e:'👁️', t:'الْعَيْنُ الَّتِي تَرَى مَلَايِينَ الْأَلْوَان', bin:0 },
    { e:'📷', t:'أَغْلَى كَامِيرَا بَشَرِيَّة', bin:1 },
    { e:'💧', t:'عَيْنٌ تُنَظِّفُ وَتُصْلِحُ نَفْسَهَا', bin:0 },
    { e:'🎲', t:'الصُّدْفَة', bin:1 } ] },
  act:{ q:'مَنْ جَعَلَ لَكَ عَيْنًا تَرَى؟', yay:'أَحْسَنْت! اللهُ الَّذِي جَعَلَ لَكَ الْأَبْصَار', opts:[
    { e:'💚', t:'اللهُ الْخَالِقُ الْحَكِيم', ok:true },
    { e:'🏭', t:'مَصْنَعُ كَامِيرَات' },
    { e:'🤷', t:'لَا أَحَد' } ] },
  dua:'الْحَمْدُ لِلَّهِ الَّذِي جَعَلَ لِيَ السَّمْعَ وَالْبَصَر' },

{ id:'butterfly', icon:'🦋', color:'#E84393', title:'التَّحَوُّلُ السِّحْرِيّ',
  tag:'الْفَرَاشَة',
  pages:[
    { emoji:'🐛', text:'تَبْدَأُ الْفَرَاشَةُ دُودَةً صَغِيرَةً تَزْحَفُ عَلَى الْأَرْضِ بِبُطْء.',
      prompt:'A small green caterpillar crawling on a leaf, humble beginning, bright cheerful scene' },
    { emoji:'🛡️', text:'ثُمَّ تَصْنَعُ لِنَفْسِهَا شَرْنَقَةً وَتَنَامُ فِيهَا، وَيَحْدُثُ دَاخِلَهَا تَغَيُّرٌ عَجِيب!',
      prompt:'A cocoon hanging on a branch with a soft glow inside, transformation happening, gentle mystery' },
    { emoji:'🦋', text:'ثُمَّ تَخْرُجُ فَرَاشَةً جَمِيلَةً مُلَوَّنَةً تَطِيرُ فِي السَّمَاء! تَحَوُّلٌ مُدْهِش.',
      prompt:'A colorful butterfly emerging from a cocoon and spreading wings, beautiful transformation, radiant' },
    { emoji:'💚', text:'مَنْ صَنَعَ هَذَا التَّحَوُّلَ الْعَجِيب؟ اللهُ الْقَادِرُ عَلَى كُلِّ شَيْء.',
      prompt:'A butterfly flying joyfully among flowers under warm sun, wondrous creation, serene' },
  ],
  moral:'تَحَوُّلُ الْفَرَاشَةِ الْعَجِيبُ دَلِيلُ خَالِقٍ قَادِرٍ حَكِيم. 💚',
  game:{ type:'order', title:'رَتِّبْ تَحَوُّلَ الْفَرَاشَة', items:[
    { e:'🥚', t:'بَيْضَةٌ صَغِيرَة' },
    { e:'🐛', t:'دُودَةٌ تَزْحَف' },
    { e:'🛡️', t:'شَرْنَقَةٌ تَنَامُ فِيهَا' },
    { e:'🦋', t:'فَرَاشَةٌ تَطِير' } ] },
  act:{ q:'مَنْ حَوَّلَ الدُّودَةَ إِلَى فَرَاشَةٍ جَمِيلَة؟', yay:'أَحْسَنْت! اللهُ الْقَادِرُ عَلَى كُلِّ شَيْء', opts:[
    { e:'💚', t:'اللهُ الْخَالِقُ الْقَادِر', ok:true },
    { e:'🪄', t:'سِحْر' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'سُبْحَانَ اللهِ الْقَادِرِ عَلَى كُلِّ شَيْء' },

{ id:'seed', icon:'🌱', color:'#2ECC71', title:'حَيَاةٌ مِنْ خَشَبٍ مَيِّت',
  tag:'الْبِذْرَة',
  pages:[
    { emoji:'🌰', text:'الْبِذْرَةُ صَغِيرَةٌ يَابِسَةٌ كَأَنَّهَا خَشَبٌ مَيِّت. مَنْ يُصَدِّقُ أَنَّهَا تُخْفِي حَيَاة؟',
      prompt:'A tiny dry seed held in a hand, humble and lifeless-looking, warm simple scene' },
    { emoji:'💧', text:'نَزْرَعُهَا فِي التُّرَابِ وَنَسْقِيهَا، فَتَنْشَقُّ وَتَخْرُجُ مِنْهَا حَيَاةٌ خَضْرَاء!',
      prompt:'A seed cracking open with a tiny green sprout emerging from soil, life beginning, warm hopeful' },
    { emoji:'🌳', text:'وَتَكْبَرُ حَتَّى تَصِيرَ شَجَرَةً عَظِيمَةً تُعْطِي ثِمَارًا وَظِلًّا!',
      prompt:'A great fruit-bearing tree grown from a seed, from small to magnificent, radiant warm light' },
    { emoji:'💚', text:'مَنْ أَخْرَجَ الْحَيَّ مِنَ الْمَيِّت؟ اللهُ. وَكَذَلِكَ يُحْيِي الْمَوْتَى يَوْمَ الْقِيَامَة.',
      prompt:'Dry earth turning lush green with new plants after rain, revival, symbol of resurrection, warm' },
  ],
  moral:'إِخْرَاجُ الْحَيِّ مِنَ الْبِذْرَةِ دَلِيلٌ عَلَى قُدْرَةِ اللهِ عَلَى الْبَعْث. 💚',
  game:{ type:'find', title:'ازْرَعِ الْبُذُور! اجْمَعِ الْبَرَاعِمَ السِّتَّةَ النَّابِتَة', target:'🌱', count:6, distractors:['🌰','🍂'], size:12 },
  act:{ q:'مَنْ يُخْرِجُ الشَّجَرَةَ الْحَيَّةَ مِنَ الْبِذْرَةِ الْيَابِسَة؟', yay:'أَحْسَنْت! وَهُوَ الَّذِي يُحْيِي الْمَوْتَى', opts:[
    { e:'💚', t:'اللهُ الَّذِي يُخْرِجُ الْحَيَّ مِنَ الْمَيِّت', ok:true },
    { e:'🎲', t:'الصُّدْفَة' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'سُبْحَانَ مَنْ يُخْرِجُ الْحَيَّ مِنَ الْمَيِّت' },

{ id:'blood', icon:'🩸', color:'#C0392B', title:'جِدَارُ الطَّوَارِئ',
  tag:'تَخَثُّرُ الدَّم',
  pages:[
    { emoji:'🩹', text:'حِينَ تَجْرَحُ إِصْبَعَك، يَخْرُجُ الدَّمُ قَلِيلًا ثُمَّ يَتَوَقَّفُ وَحْدَه! كَيْف؟',
      prompt:'A small bandaged finger with a tiny scratch healing, everyday wonder, gentle bright scene' },
    { emoji:'🧱', text:'يُسْرِعُ جِسْمُكَ فَيَبْنِي جِدَارًا صَغِيرًا يَسُدُّ الْجُرْحَ وَيُوقِفُ الدَّم.',
      prompt:'Tiny cells building a protective wall over a cut like builders, self-repair, friendly science' },
    { emoji:'🩸', text:'لَوْ لَمْ يَتَوَقَّفِ الدَّمُ لَكَانَ الْجُرْحُ الصَّغِيرُ خَطِيرًا! لَكِنَّ اللهَ حَمَاك.',
      prompt:'A healed skin surface with a tiny protective patch, emergency repair complete, warm reassuring' },
    { emoji:'💚', text:'مَنْ جَعَلَ جِسْمَكَ يُصْلِحُ نَفْسَهُ؟ اللهُ الَّذِي أَتْقَنَ صُنْعَك.',
      prompt:'A healthy happy child with a tiny healed spot, cared-for body, warm serene light' },
  ],
  moral:'تَوَقُّفُ الدَّمِ الْعَجِيبُ دَلِيلُ خَالِقٍ رَحِيمٍ حَكِيم. 💚',
  game:{ type:'order', title:'رَتِّبْ كَيْفَ يَتَوَقَّفُ الدَّم', items:[
    { e:'🩹', t:'يَحْدُثُ جُرْحٌ صَغِير' },
    { e:'🏃', t:'تُسْرِعُ خَلَايَا الْإِصْلَاح' },
    { e:'🧱', t:'تَبْنِي جِدَارًا يَسُدُّ الْجُرْح' },
    { e:'✅', t:'يَتَوَقَّفُ الدَّمُ وَيَشْفَى' } ] },
  act:{ q:'لِمَاذَا يَتَوَقَّفُ الدَّمُ وَحْدَهُ عِنْدَ الْجُرْح؟', yay:'أَحْسَنْت! جِسْمُكَ يُصْلِحُ نَفْسَهُ بِصُنْعِ الله', opts:[
    { e:'🧱', t:'جِسْمُكَ يَبْنِي جِدَارًا بِأَمْرِ الله', ok:true },
    { e:'🎲', t:'صُدْفَة' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'سُبْحَانَ مَنْ أَتْقَنَ صُنْعِي' },

{ id:'glowfish', icon:'🐠', color:'#16A085', title:'مَصَابِيحُ فِي الظَّلَام',
  tag:'أَسْمَاكُ الْأَعْمَاق',
  pages:[
    { emoji:'🌑', text:'فِي أَعْمَاقِ الْبَحْرِ ظَلَامٌ دَامِسٌ لَا يَصِلُهُ ضَوْءُ الشَّمْس. كَيْفَ تَعِيشُ الْأَسْمَاكُ هُنَاك؟',
      prompt:'A deep dark ocean scene with faint mysterious glows, the deep sea, calm and wondrous' },
    { emoji:'🏮', text:'أَعْطَى اللهُ بَعْضَ الْأَسْمَاكِ مَصَابِيحَ فِي أَجْسَامِهَا تُضِيءُ فِي الظَّلَام!',
      prompt:'A cute deep-sea fish with a glowing lantern on its head lighting the dark water, bioluminescence' },
    { emoji:'✨', text:'تُضِيءُ لِتَرَى طَرِيقَهَا وَتَجِدَ طَعَامَهَا — مِصْبَاحٌ حَيٌّ لَا يَنْطَفِئ!',
      prompt:'Glowing fish lighting their way in dark water, living lanterns, magical serene ocean scene' },
    { emoji:'💚', text:'مَنْ أَعْطَاهَا هَذِهِ الْمَصَابِيح؟ اللهُ الَّذِي لَمْ يَنْسَ خَلْقَهُ فِي أَعْمَقِ مَكَان.',
      prompt:'A gently glowing fish swimming peacefully in deep warm-lit water, cared-for creation, serene' },
  ],
  moral:'مَصَابِيحُ أَسْمَاكِ الْأَعْمَاقِ دَلِيلُ خَالِقٍ رَحِيمٍ لَا يَنْسَى أَحَدًا. 💚',
  game:{ type:'find', title:'أَضِئِ الْأَعْمَاق! اجْمَعِ الْأَسْمَاكَ الْمُضِيئَةَ الْخَمْس', target:'🐠', count:5, distractors:['🌑','🪨'], size:12 },
  act:{ q:'كَيْفَ تَرَى أَسْمَاكُ الْأَعْمَاقِ فِي الظَّلَام؟', yay:'أَحْسَنْت! مَصَابِيحُ أَعْطَاهَا اللهُ إِيَّاهَا', opts:[
    { e:'🏮', t:'بِمَصَابِيحَ فِي أَجْسَامِهَا مِنْ صُنْعِ الله', ok:true },
    { e:'🔦', t:'بِكَشَّافٍ يَدَوِيّ' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'سُبْحَانَ مَنْ وَسِعَتْ رَحْمَتُهُ كُلَّ شَيْء' },

]};
