/* corners/stories/ibada-little/salah.js — كنز الصلاة للصغار (٣–٦) · ١٠ حكايات
   كل صفحة: emoji (بديل مؤقت) + text (سطران سهلان) + prompt (وصف صورة إنجليزي لتوليدها لاحقاً).
   ملاحظة فنية: لا نُصوِّر وجوهًا تفصيلية للأنبياء. */
window.IBADA_LITTLE = window.IBADA_LITTLE || {};
window.IBADA_LITTLE.salah = {
  id:'salah', icon:'🕌', color:'#117A8B', title:'كَنْزُ الصَّلَاة', tag:'لِقَائِيَ الْيَوْمِيُّ مَعَ الله',
  stories:[

{ id:'gift', icon:'🎁', color:'#117A8B', title:'هَدِيَّةٌ مِنَ السَّمَاء',
  tag:'لِمَاذَا نُصَلِّي؟',
  pages:[
    { emoji:'🌙', text:'الصَّلَاةُ هَدِيَّةٌ أَعْطَاهَا اللهُ لِنَبِيِّنَا ﷺ فِي رِحْلَةِ الْإِسْرَاءِ وَالْمِعْرَاجِ فَوْقَ السَّبْعِ سَمَاوَات.',
      prompt:'A starry night sky with a soft glowing path rising through seven layers of light, sacred journey, no figures' },
    { emoji:'📞', text:'إِنَّهَا لِقَاؤُكَ الْيَوْمِيُّ مَعَ اللهِ خَمْسَ مَرَّات، تُكَلِّمُهُ وَيَسْمَعُك.',
      prompt:'A child on a prayer rug with a warm beam of light connecting up to the sky, daily meeting, tender' },
    { emoji:'💧', text:'قَالَ النَّبِيُّ ﷺ: الصَّلَاةُ كَنَهْرٍ أَمَامَ بَيْتِك، تَغْتَسِلُ فِيهِ خَمْسًا فَلَا يَبْقَى مِنْ أَخْطَائِكَ شَيْء!',
      prompt:'A clear flowing river beside a cozy home, purity and renewal, warm bright scene' },
    { emoji:'💚', text:'فَكُلُّ صَلَاةٍ تَغْسِلُ الْقَلْبَ وَتُقَرِّبُكَ مِنَ الله.',
      prompt:'A glowing clean heart with gentle light, purified by prayer, warm serene' },
  ],
  moral:'الصَّلَاةُ هَدِيَّةٌ وَلِقَاءٌ يَوْمِيٌّ مَعَ اللهِ يَغْسِلُ قَلْبِي. 💚',
  game:{ type:'pairs', title:'صِلْ كُلَّ شَيْءٍ بِمَعْنَاه', pairs:[
    ['🎁 الصَّلَاة','هَدِيَّةٌ مِنَ الله'],
    ['📞 كُلُّ صَلَاة','لِقَاءٌ مَعَ الله'],
    ['💧 النَّهْرُ الْجَارِي','يَغْسِلُ الْأَخْطَاء'] ] },
  act:{ q:'مَاذَا تَكُونُ الصَّلَاةُ لَنَا؟', yay:'أَحْسَنْت! هَدِيَّةٌ وَلِقَاءٌ يَوْمِيٌّ مَعَ الله', opts:[
    { e:'💚', t:'هَدِيَّةٌ وَلِقَاءٌ مَعَ الله', ok:true },
    { e:'😴', t:'شَيْءٌ ثَقِيلٌ مُمِلّ' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ اجْعَلِ الصَّلَاةَ قُرَّةَ عَيْنِي' },

{ id:'wudu', icon:'💧', color:'#2980B9', title:'الْوُضُوءُ النُّورَانِيّ',
  tag:'أَتَطَهَّرُ قَبْلَ اللِّقَاء',
  pages:[
    { emoji:'💧', text:'قَبْلَ الصَّلَاةِ نَتَوَضَّأ: نَغْسِلُ الْوَجْهَ وَالْيَدَيْنِ وَنَمْسَحُ الرَّأْسَ وَنَغْسِلُ الْقَدَمَيْن.',
      prompt:'A child washing hands and face with clean water at a basin, wudu, warm bright bathroom, no face detail' },
    { emoji:'✨', text:'قَالَ النَّبِيُّ ﷺ: مَعَ كُلِّ قَطْرَةِ وُضُوءٍ تَتَسَاقَطُ خَطَايَاكَ الصَّغِيرَة!',
      prompt:'Water droplets falling with tiny sparkles of light washing away, purity, gentle glow' },
    { emoji:'🌟', text:'وَيَوْمَ الْقِيَامَةِ تَلْمَعُ أَعْضَاءُ الْوُضُوءِ نُورًا، فَيَعْرِفُ النَّبِيُّ ﷺ أُمَّتَهُ بِهَا!',
      prompt:'Glowing radiant hands and face shining with light, mark of the believers, warm serene' },
    { emoji:'💙', text:'فَأَتَوَضَّأُ بِفَرَحٍ وَأُسَمِّي: بِسْمِ الله.',
      prompt:'A happy child with glistening clean hands ready for prayer, joy of purity, warm light' },
  ],
  moral:'الْوُضُوءُ يُطَهِّرُنِي وَيَجْعَلُ أَعْضَائِي تَلْمَعُ نُورًا. 💙',
  game:{ type:'order', title:'رَتِّبْ خُطُوَاتِ الْوُضُوء', items:[
    { e:'🤲', t:'أَغْسِلُ يَدَيّ' },
    { e:'😊', t:'أَغْسِلُ وَجْهِي' },
    { e:'💧', t:'أَمْسَحُ رَأْسِي' },
    { e:'🦶', t:'أَغْسِلُ قَدَمَيّ' } ] },
  act:{ q:'مَاذَا نَفْعَلُ قَبْلَ الصَّلَاة؟', yay:'أَحْسَنْت! الْوُضُوءُ يُطَهِّرُنَا لِلِقَاءِ الله', opts:[
    { e:'💧', t:'نَتَوَضَّأُ وَنَتَطَهَّر', ok:true },
    { e:'🍽️', t:'نَأْكُل' },
    { e:'😴', t:'نَنَام' } ] },
  dua:'أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللهُ وَأَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُه' },

{ id:'adhan', icon:'📢', color:'#27AE60', title:'نِدَاءُ الْأَذَان',
  tag:'اللهُ يُنَادِينِي لِلِقَائِه',
  pages:[
    { emoji:'📢', text:'حِينَ يَحِينُ وَقْتُ الصَّلَاة، يَرْتَفِعُ الْأَذَانُ مِنَ الْمَسَاجِد: اللهُ أَكْبَر، حَيَّ عَلَى الصَّلَاة!',
      prompt:'A slender minaret at golden hour with warm call-to-prayer light spreading over rooftops, serene' },
    { emoji:'💚', text:'إِنَّهُ نِدَاءُ الْحَبِيبِ لَك: تَعَالَ إِلَى الرَّاحَةِ وَالسَّعَادَة، تَعَالَ إِلَى الله!',
      prompt:'Soft golden sound waves spreading warmly from a minaret over a town, inviting call, tender' },
    { emoji:'🗣️', text:'نُرَدِّدُ خَلْفَ الْمُؤَذِّن، ثُمَّ نَدْعُو لِلنَّبِيِّ ﷺ بِالْوَسِيلَة.',
      prompt:'A child listening and responding with a peaceful smile near a window, answering the adhan, warm' },
    { emoji:'🏃', text:'فَنُلَبِّي فَوْرًا بِفَرَحٍ كَمَا يُلَبِّي الْبَطَل!',
      prompt:'A child hurrying happily toward a prayer rug when called, eager response, bright warm scene' },
  ],
  moral:'الْأَذَانُ نِدَاءُ اللهِ لِي، فَأُلَبِّي فَوْرًا بِفَرَح. 🏃',
  game:{ type:'find', title:'الْأَذَانُ يَرْتَفِع! اجْمَعِ الْمَآذِنَ الْخَمْس', target:'🕌', count:5, distractors:['🏠','🌴'], size:12 },
  act:{ q:'مَاذَا نَفْعَلُ حِينَ نَسْمَعُ الْأَذَان؟', yay:'أَحْسَنْت! نُلَبِّي نِدَاءَ اللهِ بِفَرَح', opts:[
    { e:'🏃', t:'نُلَبِّي وَنَسْتَعِدُّ لِلصَّلَاة', ok:true },
    { e:'📺', t:'نُكْمِلُ مُشَاهَدَةَ التِّلْفَاز' },
    { e:'🙉', t:'لَا نَهْتَمّ' } ] },
  dua:'اللَّهُمَّ رَبَّ هَذِهِ الدَّعْوَةِ التَّامَّةِ آتِ مُحَمَّدًا الْوَسِيلَة' },

{ id:'how', icon:'🧎', color:'#8E44AD', title:'كَيْفَ أُصَلِّي؟',
  tag:'حَرَكَاتُ الصَّلَاةِ الْجَمِيلَة',
  pages:[
    { emoji:'🙌', text:'نَبْدَأُ بِتَكْبِيرَةِ الْإِحْرَام: نَرْفَعُ أَيْدِيَنَا وَنَقُول: اللهُ أَكْبَر! فَنَدْخُلُ فِي لِقَاءِ الله.',
      prompt:'A child raising hands to begin prayer on a soft rug, takbir, warm reverent scene, from behind' },
    { emoji:'🧍', text:'نَقْرَأُ الْفَاتِحَةَ وَنَحْنُ قَائِمُون، ثُمَّ نَرْكَعُ فَنُعَظِّمُ رَبَّنَا.',
      prompt:'A child standing then bowing in prayer, ruku, gentle warm light, respectful posture from behind' },
    { emoji:'🧎', text:'ثُمَّ نَسْجُدُ وَجِبَاهُنَا عَلَى الْأَرْض — وَهَذَا أَقْرَبُ مَا نَكُونُ مِنَ الله!',
      prompt:'A child in prostration on a prayer rug with a soft glow, sujud closeness to Allah, tender warm' },
    { emoji:'🤲', text:'ثُمَّ نَجْلِسُ لِلتَّشَهُّدِ وَنُسَلِّمُ يَمِينًا وَيَسَارًا: السَّلَامُ عَلَيْكُم.',
      prompt:'A child sitting calmly at the end of prayer turning to give salam, peaceful, warm serene' },
  ],
  moral:'فِي السُّجُودِ أَكُونُ أَقْرَبَ مَا يَكُونُ الْعَبْدُ مِنْ رَبِّه. 🧎',
  game:{ type:'order', title:'رَتِّبْ حَرَكَاتِ الصَّلَاة', items:[
    { e:'🙌', t:'تَكْبِيرَةُ الْإِحْرَام' },
    { e:'🧍', t:'الْقِيَامُ وَالْفَاتِحَة' },
    { e:'🧎', t:'الرُّكُوعُ ثُمَّ السُّجُود' },
    { e:'🤲', t:'التَّشَهُّدُ وَالسَّلَام' } ] },
  act:{ q:'مَتَى نَكُونُ أَقْرَبَ مَا نَكُونُ مِنَ الله؟', yay:'صَحِيح! فِي السُّجُودِ فَأَكْثِرْ فِيهِ الدُّعَاء', opts:[
    { e:'🧎', t:'فِي السُّجُود', ok:true },
    { e:'🏃', t:'وَنَحْنُ نَجْرِي' },
    { e:'😴', t:'وَنَحْنُ نَنَام' } ] },
  dua:'سُبْحَانَ رَبِّيَ الْأَعْلَى' },

{ id:'khushu', icon:'💗', color:'#E84393', title:'قَلْبِي فِي الصَّلَاة',
  tag:'الْخُشُوعُ حُضُورُ الْقَلْب',
  pages:[
    { emoji:'💗', text:'الصَّلَاةُ لَيْسَتْ حَرَكَاتٍ فَقَط، بَلْ قَلْبٌ حَاضِرٌ يَتَذَكَّرُ أَنَّهُ يَقِفُ بَيْنَ يَدَيِ الله.',
      prompt:'A child praying with a softly glowing heart, presence of heart, warm tender scene from behind' },
    { emoji:'🕊️', text:'حِينَ أَفْهَمُ مَا أَقُولُ وَأَشْعُرُ أَنَّ اللهَ يَسْمَعُنِي، تَنْزِلُ السَّكِينَةُ عَلَى قَلْبِي.',
      prompt:'A white dove and gentle light around a peaceful child at prayer, tranquility, serene warm' },
    { emoji:'🎯', text:'كَانَ النَّبِيُّ ﷺ يَقُول: أَرِحْنَا بِهَا يَا بِلَال! لِأَنَّ الصَّلَاةَ رَاحَةٌ لَا عِبْء.',
      prompt:'A calm prayer space with warm light streaming in, prayer as rest, cozy serene scene' },
    { emoji:'💚', text:'فَأُصَلِّي بِقَلْبِي لَا بِجِسْمِي فَقَط، وَأَتَذَكَّرُ أَنِّي أُكَلِّمُ الله.',
      prompt:'A content child finishing prayer with a peaceful smile and warm glow, heart at rest, tender' },
  ],
  moral:'أُصَلِّي بِقَلْبٍ حَاضِرٍ يَتَذَكَّرُ أَنَّهُ يَقِفُ بَيْنَ يَدَيِ الله. 💚',
  game:{ type:'sort', title:'مَا الَّذِي يُحْضِرُ قَلْبِي فِي الصَّلَاة؟', bins:['يُحْضِرُ الْقَلْب 💗','يُشَتِّتُه 🚫'], items:[
    { e:'🤔', t:'أَفْهَمُ مَا أَقُول', bin:0 },
    { e:'📱', t:'أُفَكِّرُ فِي الْأَلْعَاب', bin:1 },
    { e:'🕊️', t:'أَشْعُرُ أَنَّ اللهَ يَسْمَعُنِي', bin:0 },
    { e:'🏃', t:'أَسْتَعْجِلُ بِلَا تَدَبُّر', bin:1 } ] },
  act:{ q:'مَا الْخُشُوعُ فِي الصَّلَاة؟', yay:'أَحْسَنْت! قَلْبٌ حَاضِرٌ يَتَذَكَّرُ الله', opts:[
    { e:'💗', t:'حُضُورُ الْقَلْبِ مَعَ اللهِ', ok:true },
    { e:'🏃', t:'الْإِسْرَاعُ بِلَا تَفْكِير' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'أَرِحْنَا بِالصَّلَاةِ يَا رَبّ' },

{ id:'times', icon:'🕐', color:'#F39C12', title:'الصَّلَوَاتُ الْخَمْس',
  tag:'مَوَاعِيدُ لِقَائِي مَعَ الله',
  pages:[
    { emoji:'🌅', text:'نُصَلِّي خَمْسَ صَلَوَاتٍ فِي الْيَوْم: الْفَجْرُ عِنْدَ شُرُوقِ الصَّبَاح، وَالظُّهْرُ فِي وَسَطِ النَّهَار.',
      prompt:'A sunrise and midday sun over a peaceful town with a minaret, prayer times, warm bright' },
    { emoji:'🌇', text:'وَالْعَصْرُ بَعْدَ الظُّهْر، وَالْمَغْرِبُ عِنْدَ غُرُوبِ الشَّمْس، وَالْعِشَاءُ فِي اللَّيْل.',
      prompt:'A sunset and evening sky over rooftops with warm glow, afternoon to night prayers, serene' },
    { emoji:'🕐', text:'خَمْسُ مَوَاعِيدَ نَتَذَكَّرُ فِيهَا اللهَ فَلَا نَنْسَاهُ طُولَ الْيَوْم.',
      prompt:'A gentle clock with five glowing marks around a day cycle, five appointments, warm illustration' },
    { emoji:'💚', text:'فَأُصَلِّي كُلَّ صَلَاةٍ فِي وَقْتِهَا، فَأَحَبُّ الْأَعْمَالِ الصَّلَاةُ عَلَى وَقْتِهَا.',
      prompt:'A child praying on time as the sky changes color behind, punctual prayer, warm hopeful' },
  ],
  moral:'أُصَلِّي الْخَمْسَ فِي أَوْقَاتِهَا فَلَا أَنْسَى اللهَ طُولَ الْيَوْم. 💚',
  game:{ type:'order', title:'رَتِّبِ الصَّلَوَاتِ الْخَمْسَ فِي الْيَوْم', items:[
    { e:'🌅', t:'الْفَجْر' },
    { e:'☀️', t:'الظُّهْر' },
    { e:'🌤️', t:'الْعَصْر' },
    { e:'🌇', t:'الْمَغْرِب' },
    { e:'🌙', t:'الْعِشَاء' } ] },
  act:{ q:'كَمْ صَلَاةً نُصَلِّي فِي الْيَوْم؟', yay:'أَحْسَنْت! خَمْسُ صَلَوَاتٍ فِي أَوْقَاتِهَا', opts:[
    { e:'🖐️', t:'خَمْسُ صَلَوَات', ok:true },
    { e:'☝️', t:'صَلَاةٌ وَاحِدَة' },
    { e:'🔟', t:'عَشْر' } ] },
  dua:'اللَّهُمَّ أَعِنِّي عَلَى الصَّلَاةِ فِي وَقْتِهَا' },

{ id:'masjid', icon:'🕌', color:'#16A085', title:'بَيْتُ اللهِ الْمَسْجِد',
  tag:'أَحَبُّ الْأَمَاكِنِ إِلَى الله',
  pages:[
    { emoji:'🕌', text:'الْمَسْجِدُ بَيْتُ الله، وَأَحَبُّ الْبِقَاعِ إِلَيْه. حِينَ نَدْخُلُهُ نَشْعُرُ بِالسَّكِينَة.',
      prompt:'A beautiful mosque with warm light and soft carpets, house of Allah, welcoming serene scene' },
    { emoji:'👟', text:'نَدْخُلُ بِالْقَدَمِ الْيُمْنَى وَنَقُول: اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِك.',
      prompt:'A child stepping into a mosque with the right foot, shoes neatly placed, respectful, warm' },
    { emoji:'🤝', text:'الصَّلَاةُ فِي جَمَاعَةٍ أَعْظَمُ أَجْرًا، وَنَقِفُ صَفًّا وَاحِدًا كَالْإِخْوَة.',
      prompt:'Rows of worshippers standing together in a mosque shown gently, congregation unity, warm from behind' },
    { emoji:'💚', text:'وَمَنْ تَعَلَّقَ قَلْبُهُ بِالْمَسَاجِدِ أَظَلَّهُ اللهُ فِي ظِلِّهِ يَوْمَ الْقِيَامَة.',
      prompt:'A child heading happily toward a glowing mosque at dawn, love of the mosque, warm hopeful' },
  ],
  moral:'الْمَسْجِدُ بَيْتُ الله، وَأُحِبُّ الصَّلَاةَ فِيهِ مَعَ الْجَمَاعَة. 💚',
  game:{ type:'find', title:'اذْهَبْ إِلَى بَيْتِ الله! اجْمَعِ الْمَسَاجِدَ الْخَمْس', target:'🕌', count:5, distractors:['🏠','🏢'], size:12 },
  act:{ q:'مَا أَحَبُّ الْأَمَاكِنِ إِلَى الله؟', yay:'أَحْسَنْت! الْمَسَاجِدُ بُيُوتُ الله', opts:[
    { e:'🕌', t:'الْمَسَاجِد', ok:true },
    { e:'🏬', t:'الْأَسْوَاق' },
    { e:'🎡', t:'الْمَلَاهِي' } ] },
  dua:'اللَّهُمَّ اجْعَلْ قَلْبِي مُعَلَّقًا بِبُيُوتِك' },

{ id:'jumuah', icon:'📅', color:'#5B4B8A', title:'يَوْمُ الْجُمُعَة',
  tag:'عِيدُ الْأُسْبُوع',
  pages:[
    { emoji:'📅', text:'يَوْمُ الْجُمُعَةِ أَفْضَلُ أَيَّامِ الْأُسْبُوع، وَهُوَ عِيدُ الْمُسْلِمِينَ كُلَّ أُسْبُوع!',
      prompt:'A bright cheerful town on a special day with a glowing mosque, the best day, festive warm' },
    { emoji:'🚿', text:'نَغْتَسِلُ وَنَلْبَسُ أَجْمَلَ ثِيَابِنَا وَنَتَطَيَّبُ وَنَذْهَبُ مُبَكِّرِينَ إِلَى الْمَسْجِد.',
      prompt:'A child in clean nice clothes heading to the mosque, preparation for Jumuah, warm bright' },
    { emoji:'👂', text:'نَسْتَمِعُ إِلَى الْخُطْبَةِ بِإِنْصَات، ثُمَّ نُصَلِّي الْجُمُعَةَ مَعَ النَّاس.',
      prompt:'Worshippers listening quietly to a sermon in a mosque, attentive congregation, warm from behind' },
    { emoji:'💚', text:'وَفِيهِ سَاعَةٌ لَا يُرَدُّ فِيهَا الدُّعَاء، فَنُكْثِرُ الصَّلَاةَ عَلَى النَّبِيِّ ﷺ.',
      prompt:'Hands raised in dua under warm Friday light near a mosque, blessed hour, tender serene' },
  ],
  moral:'الْجُمُعَةُ عِيدُ أُسْبُوعِي، أَتَطَهَّرُ وَأُبَكِّرُ وَأُكْثِرُ الدُّعَاء. 💚',
  game:{ type:'sort', title:'مَاذَا نَفْعَلُ يَوْمَ الْجُمُعَة؟', bins:['مِنْ آدَابِ الْجُمُعَة ✅','لَيْسَ مِنْهَا 🚫'], items:[
    { e:'🚿', t:'الِاغْتِسَالُ وَالتَّطَيُّب', bin:0 },
    { e:'👂', t:'الْإِنْصَاتُ لِلْخُطْبَة', bin:0 },
    { e:'🗣️', t:'الْكَلَامُ أَثْنَاءَ الْخُطْبَة', bin:1 },
    { e:'🤲', t:'الْإِكْثَارُ مِنَ الدُّعَاء', bin:0 } ] },
  act:{ q:'مَا أَفْضَلُ أَيَّامِ الْأُسْبُوع؟', yay:'أَحْسَنْت! يَوْمُ الْجُمُعَةِ عِيدُ الْمُسْلِمِين', opts:[
    { e:'📅', t:'يَوْمُ الْجُمُعَة', ok:true },
    { e:'🎮', t:'يَوْمُ اللَّعِب' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّد' },

{ id:'sunnah', icon:'➕', color:'#D4A017', title:'صَلَوَاتٌ زِيَادَة',
  tag:'السُّنَنُ وَالنَّوَافِل',
  pages:[
    { emoji:'➕', text:'بَعْدَ الصَّلَوَاتِ الْمَفْرُوضَة، هُنَاكَ صَلَوَاتٌ زِيَادَةٌ نَتَقَرَّبُ بِهَا إِلَى اللهِ أَكْثَر.',
      prompt:'A child praying extra with a small glow of extra reward, voluntary prayer, warm tender' },
    { emoji:'🏠', text:'مِثْلُ السُّنَنِ الرَّوَاتِبِ قَبْلَ الْفَرْضِ وَبَعْدَه، وَمَنْ صَلَّاهَا بَنَى اللهُ لَهُ بَيْتًا فِي الْجَنَّة!',
      prompt:'A glowing house in a paradise garden being built, reward of sunnah prayers, radiant warm' },
    { emoji:'🌙', text:'وَصَلَاةُ الْوِتْرِ فِي اللَّيْل، وَصَلَاةُ الضُّحَى فِي الصَّبَاح — كَنْزٌ لِمَنْ أَرَادَ الْمَزِيد.',
      prompt:'A peaceful night prayer scene and a bright morning prayer, extra treasures, warm serene' },
    { emoji:'💚', text:'كُلَّمَا زِدْتَ مِنَ النَّوَافِلِ أَحَبَّكَ الله. فَأُصَلِّي زِيَادَةً حُبًّا لِرَبِّي.',
      prompt:'A child praying with a warm growing glow of love around them, drawing near to Allah, tender' },
  ],
  moral:'الصَّلَوَاتُ الزِّيَادَةُ تُقَرِّبُنِي مِنَ اللهِ وَيُحِبُّنِي بِهَا. 💚',
  game:{ type:'pairs', title:'صِلْ كُلَّ صَلَاةِ زِيَادَةٍ بِوَقْتِهَا', pairs:[
    ['🌙 الْوِتْر','فِي اللَّيْل'],
    ['🌅 الضُّحَى','فِي الصَّبَاح'],
    ['🏠 السُّنَنُ الرَّوَاتِب','قَبْلَ الْفَرْضِ وَبَعْدَه'] ] },
  act:{ q:'مَاذَا يَحْدُثُ حِينَ أُكْثِرُ مِنْ صَلَوَاتِ الزِّيَادَة؟', yay:'أَحْسَنْت! يُقَرِّبُنِي وَيُحِبُّنِي الله', opts:[
    { e:'💚', t:'يُحِبُّنِي اللهُ وَأَقْتَرِبُ مِنْه', ok:true },
    { e:'😴', t:'لَا شَيْء' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ ابْنِ لِي بَيْتًا فِي الْجَنَّة' },

{ id:'righteous', icon:'⭐', color:'#C0392B', title:'الصَّالِحُونَ وَالصَّلَاة',
  tag:'أَبْطَالٌ أَحَبُّوا الصَّلَاة',
  pages:[
    { emoji:'⭐', text:'أَحَبَّ الصَّالِحُونَ الصَّلَاةَ حُبًّا عَظِيمًا. كَانَ النَّبِيُّ ﷺ يَقُومُ يُصَلِّي حَتَّى تَتَوَرَّمَ قَدَمَاه شُكْرًا لِرَبِّه.',
      prompt:'A softly glowing prayer niche at night with a warm rug, devotion of the righteous, serene no figure' },
    { emoji:'🕌', text:'وَخُبَيْبٌ الصَّحَابِيُّ طَلَبَ أَنْ يُصَلِّيَ رَكْعَتَيْنِ قَبْلَ مَوْتِه، لِأَنَّ الصَّلَاةَ رَاحَةُ قَلْبِه.',
      prompt:'A serene figure praying two rak\'ahs in soft light, prayer as final comfort, warm reverent no face' },
    { emoji:'👶', text:'وَعَلَّمَنَا النَّبِيُّ ﷺ أَنْ نُعَوِّدَ أَنْفُسَنَا الصَّلَاةَ صِغَارًا لِنُحِبَّهَا كِبَارًا.',
      prompt:'A young child happily praying beside a warm glow, learning prayer early, tender bright scene' },
    { emoji:'💚', text:'فَأَكُونُ مِثْلَهُم: أُحِبُّ صَلَاتِي وَأُحَافِظُ عَلَيْهَا وَأَجْعَلُهَا فَرَحِي.',
      prompt:'A joyful child on a prayer rug with a full warm heart of light, loving prayer, uplifting' },
  ],
  moral:'أَقْتَدِي بِالصَّالِحِينَ: أُحِبُّ صَلَاتِي وَأُحَافِظُ عَلَيْهَا. 💚',
  game:{ type:'find', title:'أَحِبَّ الصَّلَاة! اجْمَعِ الْقُلُوبَ الْمُحِبَّةَ لِلصَّلَاةِ الْخَمْس', target:'💚', count:5, distractors:['🕌','⭐'], size:12 },
  act:{ q:'كَيْفَ أَكُونُ مِثْلَ الصَّالِحِينَ مَعَ الصَّلَاة؟', yay:'أَحْسَنْت! أُحِبُّهَا وَأُحَافِظُ عَلَيْهَا', opts:[
    { e:'💚', t:'أُحِبُّهَا وَأُحَافِظُ عَلَيْهَا فِي وَقْتِهَا', ok:true },
    { e:'⏰', t:'أُؤَخِّرُهَا دَائِمًا' },
    { e:'🙈', t:'أَنْسَاهَا' } ] },
  dua:'اللَّهُمَّ اجْعَلْنِي مِنَ الْمُحَافِظِينَ عَلَى الصَّلَاة' },

]};
