/* ═══════════════════════════════════════════════════════════════
   QURAN STORIES INDEX — non-prophet stories (Heroes' Fortress)
   Full content per story in qstories-data/<slug>.js
   ─────────────────────────────────────────────────────────────── */
window.QS_INDEX = [
  { slug:'luqman',     num:1, emoji:'🧓', nameAr:'لُقمان الحكيم',   nameEn:'Luqman the Wise',
    metaAr:'وصايا الأب لابنه', metaEn:'A father\u2019s wisdom', surahAr:'سورة لقمان', surahEn:'Surah Luqman' },
  { slug:'kahf',       num:2, emoji:'🕳️', nameAr:'أصحاب الكهف',     nameEn:'People of the Cave',
    metaAr:'فتية آمنوا بربهم', metaEn:'Youth who believed', surahAr:'سورة الكهف', surahEn:'Surah Al-Kahf' },
  { slug:'qarun',      num:3, emoji:'💰', nameAr:'قارون',           nameEn:'Qarun',
    metaAr:'الغني المغرور', metaEn:'The arrogant rich man', surahAr:'سورة القصص', surahEn:'Surah Al-Qasas' },
  { slug:'dhulqarnayn',num:4, emoji:'🛡️', nameAr:'ذو القرنين',      nameEn:'Dhul-Qarnayn',
    metaAr:'الملك العادل والسد', metaEn:'The just king & the dam', surahAr:'سورة الكهف', surahEn:'Surah Al-Kahf' },
  { slug:'twogardens', num:5, emoji:'🌳', nameAr:'صاحب الجنّتَين',   nameEn:'The Two Gardens',
    metaAr:'الغنيُّ المغرور وصاحبُه', metaEn:'The proud rich man', surahAr:'سورة الكهف', surahEn:'Surah Al-Kahf' },
  { slug:'uzayr',      num:6, emoji:'🌅', nameAr:'حِمار العُزَير',    nameEn:'Uzayr & the Donkey',
    metaAr:'مئةُ عامٍ ثم البَعث', metaEn:'A hundred years, then revived', surahAr:'سورة البقرة', surahEn:'Surah Al-Baqarah' },
  { slug:'gardenowners',num:7, emoji:'🌴', nameAr:'أصحاب الجَنّة',    nameEn:'Owners of the Garden',
    metaAr:'البُخلُ يَمحَقُ البركة', metaEn:'Greed wipes out blessing', surahAr:'سورة القلم', surahEn:'Surah Al-Qalam' },
  { slug:'elephant',   num:8, emoji:'🐘', nameAr:'أصحاب الفيل',       nameEn:'The Elephant Army',
    metaAr:'كيف حَمى اللهُ بيتَه', metaEn:'Allah protects His House', surahAr:'سورة الفيل', surahEn:'Surah Al-Fil' },
  { slug:'saba',       num:9, emoji:'🏞️', nameAr:'سَبَأ',             nameEn:'Sheba (Saba\u2019)',
    metaAr:'بلدةٌ كَفَرَت بالنِّعمة', metaEn:'A land that denied its blessings', surahAr:'سورة سبأ', surahEn:'Surah Saba\u2019' },
  { slug:'fleedeath',  num:10, emoji:'🌄', nameAr:'الفِرارُ من الموت', nameEn:'Fleeing from Death',
    metaAr:'لا يُغني حَذَرٌ من قَدَر', metaEn:'No escape from the decree', surahAr:'سورة البقرة', surahEn:'Surah Al-Baqarah' },
  { slug:'rass',       num:11, emoji:'🌲', nameAr:'أصحاب الرَّسّ',     nameEn:'People of the Well',
    metaAr:'عبدوا شجرةً وكذَّبوا نبيَّهم', metaEn:'Tree-worshippers who denied their prophet', surahAr:'الفرقان · ق', surahEn:'Al-Furqan · Qaf' },
  { slug:'harutmarut', num:12, emoji:'👼', nameAr:'هاروت وماروت',      nameEn:'Harut & Marut',
    metaAr:'المَلَكانِ والتحذيرُ من السِّحر', metaEn:'The angels\u2019 warning against magic', surahAr:'سورة البقرة', surahEn:'Surah Al-Baqarah' },
  { slug:'khidr',      num:13, emoji:'🧭', nameAr:'الخَضِر وموسى',      nameEn:'Al-Khidr & Musa',
    metaAr:'حِكمةٌ خفيّةٌ وراءَ الأمور', metaEn:'Hidden wisdom behind events', surahAr:'سورة الكهف', surahEn:'Surah Al-Kahf' },
  { slug:'ukhdud',     num:14, emoji:'🔥', nameAr:'أصحاب الأخدود',     nameEn:'People of the Ditch',
    metaAr:'الغُلامُ المؤمنُ والمَلِك', metaEn:'The believing boy & the king', surahAr:'سورة البروج', surahEn:'Surah Al-Buruj' },
  { slug:'adamsons',   num:15, emoji:'👬', nameAr:'ابنا آدم',          nameEn:'The Sons of Adam',
    metaAr:'أوّلُ حَسَدٍ على الأرض', metaEn:'The first envy on earth', surahAr:'سورة المائدة', surahEn:'Surah Al-Ma\u2019idah' },
  { slug:'sabt',       num:16, emoji:'🐟', nameAr:'أصحاب السَّبت',     nameEn:'People of the Sabbath',
    metaAr:'الحِيلةُ على أمرِ الله', metaEn:'Scheming around Allah\u2019s command', surahAr:'سورة الأعراف', surahEn:'Surah Al-A\u2019raf' },
  { slug:'cow',        num:17, emoji:'🐄', nameAr:'بقرةُ بني إسرائيل',  nameEn:'The Cow of Bani Israel',
    metaAr:'طاعةٌ بلا تَردُّد', metaEn:'Obedience without delay', surahAr:'سورة البقرة', surahEn:'Surah Al-Baqarah' },
  { slug:'dirar',      num:18, emoji:'🕌', nameAr:'مسجدُ الضِّرار',     nameEn:'The Mosque of Harm',
    metaAr:'العِبرةُ بالنيّةِ والقلب', metaEn:'It is intention that counts', surahAr:'سورة التوبة', surahEn:'Surah At-Tawbah' },
  { slug:'fitna',      num:19, emoji:'🤝', nameAr:'إطفاءُ الفتنة',      nameEn:'Quenching the Discord',
    metaAr:'الأُخوّةُ تُطفئُ العَصبيّة', metaEn:'Brotherhood ends tribalism', surahAr:'آل عمران', surahEn:'Aal-\u02bdImran' },
  { slug:'adam',       num:20, emoji:'🌍', nameAr:'خَلقُ آدم',          nameEn:'The Creation of Adam',
    metaAr:'شرفُ العِلمِ وخطرُ الكِبر', metaEn:'The honor of knowledge', surahAr:'سورة البقرة', surahEn:'Surah Al-Baqarah' },
];
window.QSTORIES = window.QSTORIES || {};
