/* ════════════════════════════════════════════════════════════════
   هل تعلم؟ — ١٠٠ معلومة تُدهِشُ الطفلَ وتُقرِّبُه من عظمةِ الله:
   معجزاتٌ وعجائبُ في خلقِ الله، والكونِ والحيوانِ وجسمِ الإنسان،
   وفضائلُ الأعمالِ الصالحة. تُعرَضُ كبطاقاتٍ تُقلَّبُ واحدةً تلوَ الأخرى.
   ════════════════════════════════════════════════════════════════ */
window.DYK = [
  /* ═══ 🕋 معجزاتٌ وآياتٌ في القرآن والسنة ═══ */
  { cat:'quran', ic:'🐝', ar:'ذكرَ اللهُ النحلةَ في سورةٍ باسمِها، ويخرجُ من بطونِها عسلٌ فيه شفاءٌ للناس، ولا يُنتِجُ العسلَ إلا النحلُ الإناث!', en:'Allah named a whole surah after the bee, and from its belly comes honey that heals people — and only female bees make honey!' },
  { cat:'quran', ic:'🌊', ar:'أخبرَ القرآنُ عن «البحرَين» أحدُهما عذبٌ والآخرُ مِلحٌ لا يختلطان، وقد وجدَ العلماءُ حاجزاً بين مياهِ البحارِ يمنعُ اختلاطَها.', en:'The Qur\'an speaks of two seas — one sweet, one salty — that do not mix; scientists found a barrier between waters that keeps them apart.' },
  { cat:'quran', ic:'👶', ar:'وصفَ القرآنُ مراحلَ خلقِ الجنينِ في بطنِ أمِّه (نطفة ثم علقة ثم مضغة) قبلَ أن يكتشفَها العلمُ الحديثُ بأكثرَ من ألفِ عام.', en:'The Qur\'an described the stages of the baby\'s creation in the womb over a thousand years before modern science discovered them.' },
  { cat:'quran', ic:'🌙', ar:'انشقَّ القمرُ نصفَين معجزةً للنبيِّ ﷺ، وقد صوَّرتْ مركباتُ الفضاءِ خطاً طويلاً على سطحِ القمرِ يُشبِهُ أثرَ التئامٍ قديم.', en:'The moon split in two as a miracle for the Prophet ﷺ; spacecraft photographed a long seam-like line across the moon\'s surface.' },
  { cat:'quran', ic:'🏔️', ar:'سمَّى القرآنُ الجبالَ «أوتاداً»، والعلمُ يقولُ إن للجبالِ جذوراً عميقةً تحتَ الأرضِ تُثبِّتُها كالوتد.', en:'The Qur\'an calls mountains "pegs"; science shows mountains have deep roots underground that anchor them like a peg.' },
  { cat:'quran', ic:'🩸', ar:'حرَّمَ اللهُ الدمَ وأكلَ لحمِ الخنزير، واكتشفَ العلمُ أن لحمَ الخنزيرِ يحملُ طفيلياتٍ وأمراضاً كثيرة.', en:'Allah forbade blood and pork; science found pork carries many parasites and diseases.' },
  { cat:'quran', ic:'☝️', ar:'أخبرَ القرآنُ أن أطرافَ الأصابعِ تُميِّزُ كلَّ إنسان، واكتشفَ العلمُ أن بصمةَ كلِّ إصبعٍ فريدةٌ لا تتكرَّر.', en:'The Qur\'an mentions the fingertips; science discovered every fingerprint is unique and never repeats.' },
  { cat:'quran', ic:'🐜', ar:'تكلَّمَتْ نملةٌ في القرآنِ تُحذِّرُ قومَها من جيشِ سليمان، والعلمُ أثبتَ أن النملَ يتواصلُ ويُنذِرُ بعضُه بعضاً.', en:'An ant spoke in the Qur\'an, warning its colony of Sulayman\'s army; science proved ants communicate and warn one another.' },
  { cat:'quran', ic:'🕸️', ar:'ضربَ اللهُ بيتَ العنكبوتِ مثلاً لأوهنِ البيوت، وخيوطُه رغم ضعفِها الظاهرِ أقوى من الفولاذِ بنفسِ الوزن!', en:'Allah gave the spider\'s house as a parable of frailty — yet its silk, though it looks weak, is stronger than steel by weight!' },
  { cat:'quran', ic:'📖', ar:'القرآنُ الكريمُ لم يتغيَّرْ حرفٌ واحدٌ منذُ أكثرَ من ١٤٠٠ سنة، لأن اللهَ تكفَّلَ بحفظِه.', en:'Not a single letter of the Qur\'an has changed in over 1400 years, because Allah promised to preserve it.' },
  { cat:'quran', ic:'🌅', ar:'أقسمَ اللهُ بالفجرِ والضحى والليل، وكلُّها آياتٌ دقيقةٌ في نظامِ الأرضِ ودورانِها حولَ نفسِها.', en:'Allah swore by the dawn, the forenoon, and the night — all precise signs in Earth\'s order and rotation.' },
  { cat:'quran', ic:'🐋', ar:'ابتلعَ الحوتُ يونسَ عليه السلام ونجا حياً، وبعضُ الحيتانِ حلقُها واسعٌ فعلاً بما يكفي لابتلاعِ إنسان.', en:'A whale swallowed Yunus and he survived; some whales truly have throats wide enough to swallow a human.' },
  { cat:'quran', ic:'🔥', ar:'كانتِ النارُ برداً وسلاماً على إبراهيم — والنارُ لا تُبرِّدُ إلا بأمرِ خالقِها.', en:'The fire became cool and safe for Ibrahim — fire cools only by the command of its Creator.' },
  { cat:'quran', ic:'🌾', ar:'حبةٌ واحدةٌ تُنبِتُ سبعَ سنابلَ في كلِّ سنبلةٍ مئةُ حبة — مثلٌ ضربَه اللهُ لمُضاعفةِ الصدقة.', en:'One seed grows seven ears, each with a hundred grains — a parable Allah gave for multiplying charity.' },
  { cat:'quran', ic:'💧', ar:'قال اللهُ: ﴿وجعلنا من الماءِ كلَّ شيءٍ حي﴾ — والعلمُ يؤكِّدُ أن الماءَ أساسُ كلِّ كائنٍ حي.', en:'Allah said: "We made every living thing from water" — science confirms water is the basis of all life.' },
  { cat:'quran', ic:'🌍', ar:'وصفَ القرآنُ الأرضَ بأنها «دَحاها» أي جعلَها كالبيضةِ المُنبسِطة، والأرضُ فعلاً كرويةٌ منبعجةٌ قليلاً عند القُطبَين.', en:'The Qur\'an describes the earth as spread egg-like; the earth is indeed a slightly flattened sphere at the poles.' },
  { cat:'quran', ic:'⭐', ar:'كلُّ نجمٍ عليه حافظٌ بأمرِ الله، والنجومُ زينةٌ للسماءِ وعلاماتٌ يُهتدى بها في الظلام.', en:'Every star has a guardian by Allah\'s command; the stars adorn the sky and guide travelers in the dark.' },
  { cat:'quran', ic:'🌧️', ar:'يُنزِلُ اللهُ المطرَ بقَدَرٍ معلوم، ولو نزلَ دفعةً واحدةً لأغرقَ الأرض، لكنه ينزلُ بحكمةٍ ورحمة.', en:'Allah sends rain in a measured amount; if it fell all at once it would flood the earth — but it falls with wisdom and mercy.' },
  { cat:'quran', ic:'🍯', ar:'في العسلِ شفاءٌ للناسِ كما قال القرآن، وأثبتَ العلمُ أنه يقتلُ الجراثيمَ ويشفي الجروح.', en:'There is healing for people in honey, as the Qur\'an says; science proved it kills germs and heals wounds.' },
  { cat:'quran', ic:'👁️', ar:'قال النبيُّ ﷺ إن للعينِ حقاً في النوم، والعلمُ يؤكِّدُ أن النومَ ضروريٌّ لراحةِ الدماغِ والجسم.', en:'The Prophet ﷺ said the eye has a right to sleep; science confirms sleep is essential for the brain and body.' },

  /* ═══ 🌌 عجائبُ الكونِ والفلك ═══ */
  { cat:'kawn', ic:'☀️', ar:'الشمسُ أكبرُ من الأرضِ بأكثرَ من مليونِ مرة، ومع ذلك هي نجمٌ متوسِّطٌ بين نجومِ الكون!', en:'The sun is more than a million times bigger than Earth — yet it is only a medium-sized star among the universe\'s stars!' },
  { cat:'kawn', ic:'🚀', ar:'ضوءُ الشمسِ يصلُ إلى الأرضِ في ٨ دقائقَ تقريباً، رغم أن بينهما نحوَ ١٥٠ مليونَ كيلومتر.', en:'Sunlight reaches Earth in about 8 minutes, though about 150 million kilometers separate them.' },
  { cat:'kawn', ic:'🌕', ar:'القمرُ يبتعدُ عن الأرضِ نحوَ ٤ سنتيمتراتٍ كلَّ سنة، بنظامٍ دقيقٍ خلقَه الله.', en:'The moon drifts about 4 cm away from Earth each year, in a precise order created by Allah.' },
  { cat:'kawn', ic:'🪐', ar:'كوكبُ زُحَل خفيفٌ جداً حتى إنه لو وُضِعَ في محيطٍ ضخمٍ من الماءِ لَطَفا فوقَه!', en:'Saturn is so light that if placed in a giant ocean of water, it would float!' },
  { cat:'kawn', ic:'💫', ar:'في مجرَّتِنا وحدَها أكثرُ من ١٠٠ مليارِ نجم، وفي الكونِ مليارات المجرَّات — سبحان الخالق!', en:'Our galaxy alone has over 100 billion stars, and the universe has billions of galaxies — glory to the Creator!' },
  { cat:'kawn', ic:'🌡️', ar:'الأرضُ تقعُ في المسافةِ المثاليةِ من الشمس: لو اقتربتْ لاحترقنا، ولو ابتعدتْ لتجمَّدنا.', en:'Earth sits at the perfect distance from the sun: closer and we\'d burn, farther and we\'d freeze.' },
  { cat:'kawn', ic:'🌠', ar:'الشُّهُبُ التي نراها ليلاً هي صخورٌ صغيرةٌ تحترقُ عند دخولِها غلافَ الأرضِ الجوي.', en:'The shooting stars we see at night are small rocks burning up as they enter Earth\'s atmosphere.' },
  { cat:'kawn', ic:'🧲', ar:'للأرضِ مجالٌ مغناطيسيٌّ يحميها من إشعاعاتِ الشمسِ الضارة، كالدرعِ غيرِ المرئي.', en:'Earth has a magnetic field that shields it from the sun\'s harmful radiation, like an invisible armor.' },
  { cat:'kawn', ic:'🌈', ar:'قوسُ قزحٍ يظهرُ حين تنكسرُ أشعةُ الشمسِ في قطراتِ المطرِ فتنقسمُ إلى سبعةِ ألوان.', en:'A rainbow appears when sunlight bends inside raindrops and splits into seven colors.' },
  { cat:'kawn', ic:'❄️', ar:'كلُّ ندفةِ ثلجٍ لها شكلٌ سداسيٌّ فريدٌ لا يتكرَّرُ أبداً، من دقةِ خلقِ الله.', en:'Every snowflake has a unique six-sided shape that never repeats — from the precision of Allah\'s creation.' },
  { cat:'kawn', ic:'🌊', ar:'حركةُ المدِّ والجزرِ في البحارِ سببُها جاذبيةُ القمرِ للأرض.', en:'The tides of the seas are caused by the moon\'s gravity pulling on the Earth.' },
  { cat:'kawn', ic:'🌬️', ar:'الرياحُ تنقلُ حبوبَ اللقاحِ والبذورَ فتُساعِدُ النباتاتِ على التكاثرِ في كلِّ مكان.', en:'Wind carries pollen and seeds, helping plants reproduce everywhere.' },
  { cat:'kawn', ic:'⚡', ar:'البرقُ أسخنُ من سطحِ الشمس، وسرعتُه تفوقُ تصوُّرَنا، ومع ذلك يحفظُنا اللهُ منه.', en:'A lightning bolt is hotter than the sun\'s surface and unimaginably fast — yet Allah protects us from it.' },
  { cat:'kawn', ic:'🏜️', ar:'الصحراءُ الكبرى قد تُغطَّى بالثلجِ نادراً، وبعضُ الصحاري كانتْ بحاراً قبلَ ملايينِ السنين.', en:'The Sahara can rarely be covered in snow, and some deserts were seas millions of years ago.' },
  { cat:'kawn', ic:'🌋', ar:'داخلُ الأرضِ حارٌّ جداً كالشمس، والبراكينُ منافذُ تخرجُ منها هذه الحرارة.', en:'The inside of the Earth is as hot as the sun, and volcanoes are vents that release this heat.' },

  /* ═══ 🐾 عجائبُ الحيوان ═══ */
  { cat:'hayawan', ic:'🐜', ar:'النملةُ تحملُ أضعافَ وزنِها، ولا تنامُ أبداً، وتتعرَّفُ على طريقِها برائحةٍ خاصة.', en:'An ant can carry many times its own weight, never sleeps, and finds its way by a special scent.' },
  { cat:'hayawan', ic:'🐘', ar:'الفيلُ يبكي بالدموعِ حين يحزن، ويتذكَّرُ أصدقاءَه بعد سنوات، وله ذاكرةٌ قوية.', en:'An elephant sheds tears when sad, remembers its friends after years, and has a strong memory.' },
  { cat:'hayawan', ic:'🐬', ar:'الدلافينُ تنامُ بنصفِ دماغِها فقط ليبقى النصفُ الآخرُ مستيقظاً للتنفُّسِ والحذر.', en:'Dolphins sleep with only half their brain, keeping the other half awake to breathe and stay alert.' },
  { cat:'hayawan', ic:'🦇', ar:'الخفافيشُ ترى في الظلامِ بالصوتِ (السونار)، تُرسِلُ أصواتاً وتسمعُ صداها لتعرفَ ما حولَها.', en:'Bats "see" in the dark using sound (sonar) — they send out sounds and hear the echoes to sense their surroundings.' },
  { cat:'hayawan', ic:'🐪', ar:'الجملُ يخزنُ الدهنَ في سنامِه (لا الماء)، ويتحمَّلُ العطشَ أياماً في الصحراء.', en:'A camel stores fat in its hump (not water) and can endure thirst for days in the desert.' },
  { cat:'hayawan', ic:'🐝', ar:'النحلةُ ترقصُ رقصةً خاصةً لتُخبِرَ أخواتِها بمكانِ الزهور!', en:'A bee dances a special dance to tell its sisters where the flowers are!' },
  { cat:'hayawan', ic:'🦉', ar:'البومةُ تُديرُ رأسَها ٢٧٠ درجةً تقريباً لترى خلفَها دون أن تُحرِّكَ جسمَها.', en:'An owl can turn its head about 270 degrees to look behind it without moving its body.' },
  { cat:'hayawan', ic:'🐢', ar:'بعضُ السلاحفِ تعيشُ أكثرَ من ١٥٠ سنة، وتحملُ بيتَها على ظهرِها طولَ حياتِها.', en:'Some tortoises live over 150 years and carry their home on their back their whole life.' },
  { cat:'hayawan', ic:'🦋', ar:'الفراشةُ تتذوَّقُ الطعامَ بأقدامِها، وكانتْ يوماً يرقةً زاحفةً قبلَ أن تتحوَّلَ إلى جمال.', en:'A butterfly tastes food with its feet, and was once a crawling caterpillar before turning beautiful.' },
  { cat:'hayawan', ic:'🐙', ar:'للأخطبوطِ ثلاثةُ قلوبٍ ودمُه أزرقُ اللون، ويستطيعُ تغييرَ لونِه ليختبئ.', en:'An octopus has three hearts and blue blood, and can change its color to hide.' },
  { cat:'hayawan', ic:'🦒', ar:'رقبةُ الزرافةِ الطويلةُ فيها نفسُ عددِ فقراتِ رقبةِ الإنسانِ (سبع فقرات)!', en:'A giraffe\'s long neck has the same number of neck bones as a human — seven!' },
  { cat:'hayawan', ic:'🐧', ar:'البطريقُ يعيشُ في أبردِ مكانٍ على الأرض، والأبُ هو الذي يحضنُ البيضةَ حتى تفقس.', en:'Penguins live in the coldest place on Earth, and it is the father who keeps the egg warm until it hatches.' },
  { cat:'hayawan', ic:'🐜', ar:'وزنُ كلِّ النملِ على الأرضِ يُقارِبُ وزنَ كلِّ البشرِ مجتمعين!', en:'The combined weight of all ants on Earth is nearly equal to the weight of all humans together!' },
  { cat:'hayawan', ic:'🕊️', ar:'الحمامُ يعرفُ طريقَ عودتِه إلى بيتِه من مسافاتٍ بعيدةٍ جداً، بإلهامٍ من الله.', en:'Pigeons find their way home from very far distances, by inspiration from Allah.' },
  { cat:'hayawan', ic:'🐛', ar:'دودةُ القزِّ تنسجُ خيطاً واحداً طولُه قد يبلغُ كيلومتراً كاملاً لتصنعَ شرنقتَها!', en:'A silkworm spins a single thread that can reach a full kilometer long to make its cocoon!' },
  { cat:'hayawan', ic:'🦈', ar:'بعضُ أسماكِ القرشِ تشمُّ قطرةَ دمٍ واحدةً في كميةٍ هائلةٍ من الماء.', en:'Some sharks can smell a single drop of blood in a huge amount of water.' },
  { cat:'hayawan', ic:'🐦', ar:'بعضُ الطيورِ المهاجرةِ تطيرُ آلافَ الكيلومتراتِ دون أن تضل، تهتدي بالنجومِ والشمس.', en:'Some migrating birds fly thousands of kilometers without getting lost, guided by the stars and sun.' },
  { cat:'hayawan', ic:'🐸', ar:'بعضُ الضفادعِ تتجمَّدُ في الشتاءِ تماماً ثم تعودُ للحياةِ في الربيع!', en:'Some frogs freeze completely in winter, then come back to life in spring!' },
  { cat:'hayawan', ic:'🐌', ar:'الحلزونُ يمشي على طبقةٍ من المخاطِ تحميه حتى لو مشى على حدِّ سكين!', en:'A snail glides on a layer of slime that protects it — even if it crawls along a knife\'s edge!' },
  { cat:'hayawan', ic:'🦂', ar:'العقربُ يستطيعُ الصيامَ عن الطعامِ أشهُراً طويلة، ويلمعُ تحت ضوءٍ خاص.', en:'A scorpion can go without food for many months, and glows under a special light.' },

  /* ═══ 🧠 عجائبُ جسمِ الإنسان ═══ */
  { cat:'jism', ic:'❤️', ar:'قلبُك ينبضُ نحوَ ١٠٠ ألفِ مرةٍ كلَّ يومٍ دون أن يتعبَ أو يتوقَّف — نعمةٌ من الله.', en:'Your heart beats about 100,000 times every day without tiring or stopping — a blessing from Allah.' },
  { cat:'jism', ic:'🧠', ar:'دماغُك فيه مليارات الخلايا، ويعملُ حتى وأنتَ نائم، وسرعةُ إشاراتِه أسرعُ من السيارة!', en:'Your brain has billions of cells, works even while you sleep, and its signals travel faster than a car!' },
  { cat:'jism', ic:'🫁', ar:'تتنفَّسُ نحوَ ٢٠ ألفَ مرةٍ في اليومِ دون أن تُفكِّرَ في ذلك — سبحان مَن دبَّرَ جسمَك.', en:'You breathe about 20,000 times a day without even thinking about it — glory to the One who ordered your body.' },
  { cat:'jism', ic:'🦴', ar:'يُولَدُ الطفلُ بنحوِ ٣٠٠ عظمة، وتلتحمُ لتصيرَ ٢٠٦ عظاماً عندَ الكبر.', en:'A baby is born with about 300 bones, which fuse into 206 bones by adulthood.' },
  { cat:'jism', ic:'👁️', ar:'عينُك تُميِّزُ ملايينَ الألوان، وترمشُ نحوَ ١٥ ألفَ مرةٍ يومياً لتبقى نظيفةً رطبة.', en:'Your eye distinguishes millions of colors and blinks about 15,000 times a day to stay clean and moist.' },
  { cat:'jism', ic:'👅', ar:'لسانُك يحملُ آلافَ البراعمِ الذوقية، ولكلِّ إنسانٍ بصمةُ لسانٍ مختلفة!', en:'Your tongue holds thousands of taste buds, and every person has a different tongue print!' },
  { cat:'jism', ic:'🩸', ar:'لو مددتَ أوعيةَ الدمِ في جسمِك لطافتْ حولَ الأرضِ أكثرَ من مرتَين!', en:'If you stretched out the blood vessels in your body, they would circle the Earth more than twice!' },
  { cat:'jism', ic:'💪', ar:'أقوى عضلةٍ في جسمِك بالنسبةِ لحجمِها هي عضلةُ الفكِّ التي تمضغُ بها.', en:'The strongest muscle in your body for its size is the jaw muscle you chew with.' },
  { cat:'jism', ic:'👃', ar:'أنفُك يتذكَّرُ أكثرَ من ٥٠ ألفَ رائحةٍ مختلفة، ويُنبِّهُك للخطرِ كرائحةِ الدخان.', en:'Your nose can remember over 50,000 different smells and warns you of danger, like smoke.' },
  { cat:'jism', ic:'🦷', ar:'مِيناءُ السنِّ أصلبُ مادةٍ في جسمِ الإنسان، أصلبُ من العظم.', en:'Tooth enamel is the hardest substance in the human body — harder than bone.' },
  { cat:'jism', ic:'😴', ar:'أثناءَ النومِ يُنظِّفُ الدماغُ نفسَه ويُرتِّبُ ما تعلَّمتَه في النهار.', en:'While you sleep, your brain cleans itself and organizes what you learned during the day.' },
  { cat:'jism', ic:'🩹', ar:'جلدُك يُجدِّدُ نفسَه باستمرار، وتخسرُ ملايينَ الخلايا الجلديةِ وتُعوِّضُها كلَّ يوم.', en:'Your skin renews itself constantly — you lose millions of skin cells and replace them every day.' },
  { cat:'jism', ic:'👂', ar:'أذنُك تُوازِنُ جسمَك، ولذلك حين تدورُ كثيراً تشعرُ بالدوار.', en:'Your ear keeps your body balanced — that\'s why you feel dizzy when you spin a lot.' },
  { cat:'jism', ic:'💧', ar:'أكثرُ من نصفِ جسمِك ماء، ولذلك أمرَنا اللهُ بشربِ الماءِ والاعتدالِ فيه.', en:'More than half your body is water, which is why Allah guided us to drink water in moderation.' },
  { cat:'jism', ic:'🖐️', ar:'بصمةُ أصابعِك تتكوَّنُ وأنتَ جنينٌ في بطنِ أمِّك ولا تتغيَّرُ طولَ حياتِك.', en:'Your fingerprints form while you are a baby in the womb and never change your whole life.' },

  /* ═══ 🤲 فضائلُ الأعمالِ الصالحة ═══ */
  { cat:'amal', ic:'😊', ar:'التبسُّمُ في وجهِ أخيكَ صدقةٌ تُؤجَرُ عليها، كما قال النبيُّ ﷺ.', en:'Smiling at your brother is a charity you are rewarded for, as the Prophet ﷺ said.' },
  { cat:'amal', ic:'📿', ar:'مَن قال «سبحان الله وبحمده» مئةَ مرةٍ في اليومِ غُفِرتْ ذنوبُه ولو كانتْ مثلَ زبدِ البحر.', en:'Whoever says "Subhan Allah wa bihamdih" a hundred times a day has their sins forgiven, even if like the foam of the sea.' },
  { cat:'amal', ic:'🕌', ar:'صلاةُ الجماعةِ تفوقُ صلاةَ الفردِ بسبعٍ وعشرينَ درجة.', en:'Praying in congregation is twenty-seven times better than praying alone.' },
  { cat:'amal', ic:'📖', ar:'مَن قرأ حرفاً من القرآنِ فله حسنة، والحسنةُ بعشرِ أمثالِها.', en:'Whoever reads one letter of the Qur\'an earns a good deed, and each good deed is multiplied by ten.' },
  { cat:'amal', ic:'🤲', ar:'الدعاءُ سلاحُ المؤمن، ويُستجابُ خاصةً في الثلثِ الأخيرِ من الليلِ وبين الأذانِ والإقامة.', en:'Supplication is the believer\'s weapon, answered especially in the last third of the night and between the adhan and iqamah.' },
  { cat:'amal', ic:'💧', ar:'مَن سقى ماءً أو أطعمَ جائعاً كُتِبَ له أجرٌ عظيم، حتى سقيُ الحيوانِ فيه أجر.', en:'Whoever gives water or feeds the hungry earns a great reward — even giving water to an animal is rewarded.' },
  { cat:'amal', ic:'👪', ar:'برُّ الوالدَين من أحبِّ الأعمالِ إلى الله، ورضاهُما بابٌ من أبوابِ الجنة.', en:'Kindness to parents is among the most beloved deeds to Allah, and their pleasure is a gate of Paradise.' },
  { cat:'amal', ic:'🌳', ar:'مَن غرسَ شجرةً فأكلَ منها إنسانٌ أو طيرٌ أو حيوانٌ كُتِبَ له صدقة.', en:'Whoever plants a tree from which a person, bird, or animal eats has a charity recorded for them.' },
  { cat:'amal', ic:'🧹', ar:'إماطةُ الأذى عن الطريقِ (كحجرٍ أو شوك) شعبةٌ من شعبِ الإيمان.', en:'Removing harm from the road (like a stone or thorns) is a branch of faith.' },
  { cat:'amal', ic:'🌙', ar:'مَن صام رمضانَ إيماناً واحتساباً غُفِرَ له ما تقدَّمَ من ذنبِه.', en:'Whoever fasts Ramadan with faith and hope has their past sins forgiven.' },
  { cat:'amal', ic:'💰', ar:'الصدقةُ لا تُنقِصُ المال، بل تُبارِكُه وتُطفِئُ الخطايا كما يُطفِئُ الماءُ النار.', en:'Charity does not decrease wealth; it blesses it and wipes out sins as water puts out fire.' },
  { cat:'amal', ic:'🤝', ar:'المسلمُ أخو المسلم، ومَن فرَّجَ عن أخيه كربةً فرَّجَ اللهُ عنه كربةً يومَ القيامة.', en:'A Muslim is the brother of a Muslim; whoever relieves his brother\'s distress, Allah relieves his distress on the Day of Judgment.' },
  { cat:'amal', ic:'🕋', ar:'العمرةُ إلى العمرةِ كفارةٌ لما بينهما، والحجُّ المبرورُ ليس له جزاءٌ إلا الجنة.', en:'One Umrah to the next erases what is between them, and an accepted Hajj has no reward but Paradise.' },
  { cat:'amal', ic:'🌸', ar:'الكلمةُ الطيبةُ صدقة، وقولُ الحقِّ والرفقُ في الكلامِ يفتحُ القلوب.', en:'A kind word is charity, and speaking the truth gently opens hearts.' },
  { cat:'amal', ic:'⏰', ar:'ركعتا الفجرِ (سنة) خيرٌ من الدنيا وما فيها، كما أخبرَ النبيُّ ﷺ.', en:'The two units of the dawn (sunnah) prayer are better than the world and all it contains, as the Prophet ﷺ said.' },
  { cat:'amal', ic:'📚', ar:'مَن سلكَ طريقاً يطلبُ فيه علماً سهَّلَ اللهُ له طريقاً إلى الجنة.', en:'Whoever travels a path seeking knowledge, Allah eases for them a path to Paradise.' },
  { cat:'amal', ic:'🤲', ar:'دعوةُ المسلمِ لأخيه بظهرِ الغيبِ مستجابة، ويقولُ الملَك: ولكَ مِثلُها.', en:'A Muslim\'s prayer for his brother in his absence is answered, and the angel says: And the same for you.' },
  { cat:'amal', ic:'😇', ar:'مَن كظمَ غيظَه وهو قادرٌ على إنفاذِه دعاه اللهُ على رؤوسِ الخلائقِ ليختارَ من الحورِ ما يشاء.', en:'Whoever restrains his anger while able to act on it, Allah will call him before all creation to choose his reward.' },
  { cat:'amal', ic:'🌟', ar:'أحبُّ الأعمالِ إلى اللهِ أدومُها وإن قلّ — فالقليلُ الدائمُ خيرٌ من الكثيرِ المنقطع.', en:'The most beloved deeds to Allah are the most consistent, even if small — a little that is regular beats a lot that stops.' },
  { cat:'amal', ic:'🌺', ar:'مَن قال «لا إله إلا الله» صادقاً من قلبِه دخلَ الجنة، فهي مفتاحُ الجنةِ وأثقلُ ما في الميزان.', en:'Whoever says "There is no god but Allah" sincerely from the heart enters Paradise — it is the key to Paradise and the heaviest thing on the scale.' },

  /* ═══ 🌿 عجائبُ الطبيعةِ والنبات ═══ */
  { cat:'kawn', ic:'🌳', ar:'الأشجارُ تتنفَّسُ عكسَنا: تأخذُ الغازَ الذي نُخرِجُه وتُعطينا الأكسجينَ الذي نتنفَّسُه — نظامٌ بديعٌ من الله.', en:'Trees breathe opposite to us: they take in the gas we breathe out and give us the oxygen we breathe in — a marvelous system from Allah.' },
  { cat:'kawn', ic:'🌻', ar:'زهرةُ عبَّادِ الشمسِ تُديرُ وجهَها مع الشمسِ من الشروقِ إلى الغروب!', en:'The sunflower turns its face to follow the sun from sunrise to sunset!' },
  { cat:'kawn', ic:'💦', ar:'الماءُ نفسُه يدورُ منذُ خلقِ الأرض: يتبخَّرُ فيصعدُ سحاباً ثم ينزلُ مطراً، ولا يزيدُ ولا ينقص.', en:'The very same water has cycled since Earth was created: it evaporates into clouds, then falls as rain — never increasing or decreasing.' },
  { cat:'kawn', ic:'🍂', ar:'أوراقُ الشجرِ تتلوَّنُ في الخريفِ لأن الأخضرَ يختفي فتظهرُ الألوانُ التي كانتْ مخبوءةً تحتَه.', en:'Leaves change color in autumn because the green fades, revealing the colors that were hidden beneath it.' },
  { cat:'hayawan', ic:'🐳', ar:'الحوتُ الأزرقُ أضخمُ مخلوقٍ عاش على الأرض، وقلبُه بحجمِ سيارةٍ صغيرة!', en:'The blue whale is the largest creature ever to live on Earth, and its heart is the size of a small car!' },
  { cat:'hayawan', ic:'🐆', ar:'الفهدُ أسرعُ حيوانٍ على اليابسة، يعدو بسرعةٍ تفوقُ السياراتِ في الطريق.', en:'The cheetah is the fastest land animal, running faster than cars on the road.' },
  { cat:'jism', ic:'🧬', ar:'في كلِّ خليةٍ من جسمِك «شفرةٌ» خاصةٌ بك وحدَك، لا يُشبِهُك فيها أحدٌ في العالم.', en:'Every cell in your body carries a "code" unique to you alone — no one else in the world matches it.' },
  { cat:'jism', ic:'😀', ar:'تحتاجُ لتحريكِ عضلاتٍ عندَ العبوسِ أكثرَ مما تحتاجُ عندَ الابتسام — فالابتسامةُ أسهلُ وأجمل!', en:'Frowning uses more muscles than smiling — so a smile is easier and more beautiful!' },
  { cat:'jism', ic:'🌡️', ar:'جسمُك يُحافِظُ على حرارتِه ثابتةً تقريباً مهما تغيَّرَ الجوُّ حولَك، بتدبيرٍ من الله.', en:'Your body keeps its temperature almost constant no matter how the weather around you changes, by Allah\'s design.' },
  { cat:'amal', ic:'🌙', ar:'ليلةُ القدرِ خيرٌ من ألفِ شهر، والعملُ الصالحُ فيها كأنه عملُ أكثرَ من ٨٣ سنة!', en:'The Night of Decree is better than a thousand months — a good deed in it is like the deeds of more than 83 years!' }
];
