/* corners/stories/minaret-little/tawheed.js — رحلة التوحيد للصغار (٣–٦)
   ١٠ حكايات كاملة مبسّطة من محطات «قصر الملك الواحد» في منارة العقيدة.
   كل صفحة: emoji (بديل مؤقت) + text (سرد سهل) + prompt (وصف صورة لتوليدها لاحقاً).
   ملاحظة فنية: الأوصاف لا تُصوِّر الأنبياءَ ولا وجوهَهم إطلاقاً. */
window.MINARET_LITTLE = window.MINARET_LITTLE || {};
window.MINARET_LITTLE.tawheed = {
  id:'tawheed', icon:'🕌', color:'#16A085',
  title:'قَصْرُ الْمَلِكِ الْوَاحِد', tag:'اللهُ وَاحِدٌ لَا شَرِيكَ لَه',
  stories:[

{ id:'emperor', icon:'👑', color:'#6C5CE7', title:'سُؤَالُ الْعَالِمِ الذَّكِيّ',
  tag:'اللهُ لَا يَحْتَاجُ وَلَدًا',
  pages:[
    { emoji:'🏰', text:'كَانَ هُنَاكَ عَالِمٌ مُسْلِمٌ ذَكِيٌّ جِدًّا اسْمُهُ الْبَاقِلَّانِي. سَافَرَ إِلَى قَصْرِ مَلِكٍ بَعِيد، وَكَانَ فِي الْقَصْرِ رِجَالٌ يَقُولُونَ كَلَامًا غَيْرَ صَحِيحٍ عَنِ الله.',
      prompt:'A wise Muslim scholar in flowing robes and turban seen from behind, walking toward a grand distant palace with golden domes, sunset sky' },
    { emoji:'🗣️', text:'قَالُوا: لِلَّهِ وَلَد! فَحَزِنَ الْعَالِمُ مِنْ هَذَا الْكَلَام، لِأَنَّ اللهَ لَيْسَ مِثْلَنَا أَبَدًا.',
      prompt:'Inside an ornate palace hall, a group of robed men talking, warm candlelight, marble columns, seen from a distance, no faces detailed' },
    { emoji:'💡', text:'فَفَكَّرَ الْعَالِمُ بِسُؤَالٍ ذَكِيّ. سَأَلَ كَبِيرَهُمْ بِهُدُوء: كَيْفَ حَالُ زَوْجَتِكَ وَأَوْلَادِك؟',
      prompt:'A glowing lightbulb idea moment: a scholar silhouette with a thought bubble, cozy warm palace interior' },
    { emoji:'😠', text:'غَضِبَ الرَّجُلُ وَقَال: أَنَا لَا أَتَزَوَّجُ وَلَا أُنْجِبُ أَوْلَادًا، أَنَا أَكْبَرُ مِنْ ذَلِك!',
      prompt:'An old robed man with crossed arms looking proud and upset, standing in a palace hall, cartoon style, gentle humor' },
    { emoji:'😊', text:'فَابْتَسَمَ الْعَالِمُ وَقَال: عَجَبًا! تَرْفُضُهَا لِنَفْسِك، وَتَقُولُهَا عَنِ اللهِ رَبِّ الْعَالَمِين؟! فَسَكَتَ الْجَمِيع.',
      prompt:'A serene smiling scholar silhouette raising one finger wisely, palace audience silent and amazed, soft golden light' },
    { emoji:'🌙', text:'نَحْنُ نَتَزَوَّجُ وَنُنْجِبُ لِأَنَّنَا نَحْتَاجُ مَنْ يُسَاعِدُنَا. أَمَّا اللهُ فَقَوِيٌّ غَنِيٌّ لَا يَحْتَاجُ أَحَدًا أَبَدًا.',
      prompt:'A peaceful night sky with a crescent moon and stars over a sleeping village, calm and cozy' },
    { emoji:'💜', text:'قُلْ هُوَ اللهُ أَحَد، اللهُ الصَّمَد، لَمْ يَلِدْ وَلَمْ يُولَد، وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَد.',
      prompt:'Beautiful Islamic geometric pattern in purple and gold radiating like a star, ornamental, serene' },
  ],
  moral:'اللهُ الصَّمَدُ لَا يَحْتَاجُ شَيْئًا، وَكُلُّنَا نَحْتَاجُه. 💜',
  game:{ type:'pairs', title:'صِلْ كُلَّ وَاحِدٍ بِصِفَتِهِ الصَّحِيحَة', pairs:[
    ['🧍 الْإِنْسَان','🍽️ يَحْتَاجُ وَيَأْكُل'],
    ['🤖 الْآلَة','🔌 تَحْتَاجُ الْكَهْرَبَاء'],
    ['💜 اللهُ الصَّمَد','💪 لَا يَحْتَاجُ شَيْئًا'] ] },
  act:{ q:'هَلْ يَحْتَاجُ اللهُ وَلَدًا؟', yay:'أَحْسَنْت! اللهُ الصَّمَدُ الْغَنِيُّ لَا يَحْتَاجُ أَحَدًا', opts:[
    { e:'🤔', t:'نَعَم، مِثْلَنَا' },
    { e:'🙅', t:'لَا! اللهُ غَنِيٌّ لَا يَحْتَاجُ شَيْئًا', ok:true },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'قُلْ هُوَ اللهُ أَحَد، اللهُ الصَّمَد' },

{ id:'pilot', icon:'✈️', color:'#2980B9', title:'الطَّيَّارُ الْمَرْبُوط',
  tag:'اللهُ حَيٌّ لَا يَمُوت',
  pages:[
    { emoji:'✈️', text:'هَلْ رَكِبْتَ طَائِرَةً مِنْ قَبْل؟ الطَّائِرَةُ تَحْتَاجُ طَيَّارًا يَقُودُهَا طُولَ الْوَقْت.',
      prompt:'A cheerful cartoon airplane flying through fluffy clouds in a bright blue sky, children book style' },
    { emoji:'🪢', text:'تَخَيَّلْ أَنَّ الطَّيَّارَ مَرْبُوطٌ بِالْحِبَالِ فِي الزَّاوِيَة! هَلْ يَسْتَطِيعُ أَنْ يَقُودَ الطَّائِرَة؟ لَا! سَتَقَعُ الطَّائِرَة.',
      prompt:'Inside a cartoon cockpit, a pilot chair empty with tangled ropes in the corner, alarm colors, funny worried mood, no people' },
    { emoji:'🌍', text:'وَالدُّنْيَا كُلُّهَا أَكْبَرُ مِنَ الطَّائِرَة: الشَّمْسُ تُشْرِق، وَالْمَطَرُ يَنْزِل، وَالسَّمَاءُ لَا تَقَع. مَنْ يُدَبِّرُ كُلَّ هَذَا؟',
      prompt:'The round Earth from space with a smiling sun, rain clouds over green lands, stars around, wonder and awe, childrens illustration' },
    { emoji:'💪', text:'الَّذِي يُدَبِّرُ الدُّنْيَا لَازِمٌ يَكُونُ حَيًّا قَوِيًّا لَا يَنَامُ وَلَا يَتْعَبُ أَبَدًا. وَهَذَا هُوَ اللهُ وَحْدَه!',
      prompt:'Rays of golden light breaking through clouds over mountains and sea, majestic and warm, no figures' },
    { emoji:'🛌', text:'أَنَا وَأَنْتَ نَنَامُ كُلَّ لَيْلَة. أَمَّا اللهُ فَلَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْم، يَحْرُسُنَا وَنَحْنُ نَائِمُون.',
      prompt:'A cozy child bedroom at night, teddy bear on the bed, soft moonlight through the window, safe peaceful feeling' },
    { emoji:'💙', text:'فَمَنْ قَالَ إِنَّ الْإِلَهَ يُرْبَطُ أَوْ يَمُوت، فَكَلَامُهُ غَلَط. اللهُ الْحَيُّ الْقَيُّومُ لَا يَمُوتُ أَبَدًا.',
      prompt:'A strong lighthouse shining bright over calm night sea, stars above, reassuring glow' },
  ],
  moral:'اللهُ الْحَيُّ الْقَيُّومُ يَحْرُسُنِي دَائِمًا، حَتَّى وَأَنَا نَائِم. 💙',
  game:{ type:'maze', title:'الطَّيَّارُ الْيَقِظُ يَقُودُ الطَّائِرَة! أَوْصِلْهَا إِلَى الْمَطَارِ بَيْنَ الْغُيُوم', avatar:'✈️', goal:'🛬', wall:'⛈️', map:['S.#..','..#.#','#...#','..#..','#..#G'] },
  act:{ q:'هَلْ يَنَامُ الله؟', yay:'صَحِيح! لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْم', opts:[
    { e:'🌙', t:'لَا يَنَامُ أَبَدًا، يَحْرُسُنَا دَائِمًا', ok:true },
    { e:'😴', t:'يَنَامُ بِاللَّيْلِ مِثْلَنَا' },
    { e:'⏰', t:'يَنَامُ قَلِيلًا' } ] },
  dua:'يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيث' },

{ id:'twocaptains', icon:'🚢', color:'#16A085', title:'سَفِينَةٌ بِقُبْطَانَيْن',
  tag:'لَوْ كَانَ إِلَهَانِ لَفَسَدَ الْكَوْن',
  pages:[
    { emoji:'🚢', text:'كَانَ هُنَاكَ سَفِينَةٌ كَبِيرَةٌ جَمِيلَة، تَحْتَاجُ قُبْطَانًا وَاحِدًا يَقُودُهَا فِي الْبَحْر.',
      prompt:'A beautiful big wooden ship with white sails on sparkling turquoise sea, seagulls, sunny day, storybook style' },
    { emoji:'👨‍✈️👨‍✈️', text:'تَخَيَّلْ أَنَّ لِلسَّفِينَةِ قُبْطَانَيْن! قَالَ الْأَوَّل: نَذْهَبُ يَمِينًا! وَقَالَ الثَّانِي: بَلْ يَسَارًا!',
      prompt:'Two cartoon ship captains back to back pointing in opposite directions on a ship deck, confused funny mood' },
    { emoji:'🌀', text:'صَارَتِ السَّفِينَةُ تَلُفُّ وَتَدُور، وَلَا تَصِلُ إِلَى أَيِّ مَكَان! الْقِيَادَةُ لَا تَكُونُ إِلَّا لِوَاحِد.',
      prompt:'A ship spinning in circles leaving a swirly trail in the sea, dizzy stars around it, gentle humor' },
    { emoji:'🌌', text:'وَالدُّنْيَا كُلُّهَا مِثْلُ سَفِينَةٍ عَظِيمَة: شَمْسٌ وَقَمَرٌ وَنُجُومٌ وَبِحَار، كُلُّهَا تَمْشِي بِنِظَامٍ جَمِيل.',
      prompt:'A vast starry night sky with planets, a glowing moon and shooting stars over a calm ocean, wonder, deep blues and gold' },
    { emoji:'☝️', text:'لَوْ كَانَ هُنَاكَ إِلَهَان، لَاخْتَلَفَا مِثْلَ الْقُبْطَانَيْن، وَلَفَسَدَتِ الدُّنْيَا. لَكِنَّ الدُّنْيَا مُرَتَّبَةٌ جَمِيلَة!',
      prompt:'Perfectly ordered solar system with planets orbiting the sun in neat glowing rings, harmony and beauty' },
    { emoji:'💚', text:'فَاللهُ وَاحِدٌ لَا شَرِيكَ لَه، هُوَ وَحْدَهُ الْمَلِكُ الَّذِي يُدَبِّرُ كُلَّ شَيْء. لَا إِلَهَ إِلَّا الله!',
      prompt:'One radiant golden star shining above all, Islamic geometric ornament frame, teal and gold palette' },
  ],
  moral:'اللهُ وَاحِدٌ لَا شَرِيكَ لَه — لِذَلِكَ الْكَوْنُ جَمِيلٌ مُرَتَّب. 💚',
  game:{ type:'order', title:'رَتِّبْ رِحْلَةَ السَّفِينَةِ السَّعِيدَةِ ذَاتِ الْقُبْطَانِ الْوَاحِد', items:[
    { e:'⚓', t:'قُبْطَانٌ وَاحِدٌ يُمْسِكُ الدَّفَّة' },
    { e:'🧭', t:'يَخْتَارُ طَرِيقًا وَاحِدًا' },
    { e:'🌊', t:'يَعْبُرُ الْأَمْوَاجَ بِثَبَات' },
    { e:'🏝️', t:'تَصِلُ السَّفِينَةُ بِسَلَام' } ] },
  act:{ q:'كَمْ قُبْطَانًا تَحْتَاجُ السَّفِينَةُ لِتَصِلَ بِسَلَام؟', yay:'أَحْسَنْت! وَالْكَوْنُ كُلُّهُ رَبُّهُ وَاحِد', opts:[
    { e:'✌️', t:'قُبْطَانَيْنِ يَتَخَاصَمَان' },
    { e:'🖐️', t:'خَمْسَةَ قَبَاطِنَة' },
    { e:'☝️', t:'قُبْطَانًا وَاحِدًا فَقَط', ok:true } ] },
  dua:'لَا إِلَهَ إِلَّا اللهُ وَحْدَهُ لَا شَرِيكَ لَه' },

{ id:'axe', icon:'🪓', color:'#E67E22', title:'الْفَأْسُ فَوْقَ الصَّنَمِ الْكَبِير',
  tag:'الصَّنَمُ لَا يَسْمَعُ وَلَا يَنْفَع',
  pages:[
    { emoji:'🗿', text:'كَانَ قَوْمُ سَيِّدِنَا إِبْرَاهِيمَ يَسْجُدُونَ لِأَصْنَامٍ مِنْ حِجَارَة! وَالْحَجَرُ لَا يَسْمَعُ وَلَا يَتَكَلَّمُ وَلَا يَتَحَرَّك.',
      prompt:'Ancient stone idols of different sizes standing in a temple courtyard, silent and lifeless, dusty warm light, no people' },
    { emoji:'🎪', text:'وَفِي يَوْمِ عِيدِهِمْ خَرَجُوا كُلُّهُمْ مِنَ الْمَدِينَة، وَبَقِيَ إِبْرَاهِيمُ مَعَ الْأَصْنَامِ وَحْدَهَا.',
      prompt:'An empty ancient town street with colorful festival flags, everyone gone, quiet morning light' },
    { emoji:'🪓', text:'فَكَسَّرَ إِبْرَاهِيمُ الْأَصْنَامَ الصَّغِيرَةَ كُلَّهَا، وَعَلَّقَ الْفَأْسَ عَلَى رَقَبَةِ الصَّنَمِ الْكَبِير!',
      prompt:'Broken stone idol pieces scattered on a temple floor, one big stone idol standing with an axe hanging on its neck, cartoon style, no people' },
    { emoji:'😲', text:'رَجَعَ الْقَوْمُ وَغَضِبُوا: مَنْ كَسَّرَ آلِهَتَنَا؟! فَقَالَ إِبْرَاهِيم: اسْأَلُوا الْكَبِير، هَا هُوَ الْفَأْسُ عِنْدَه!',
      prompt:'Crowd silhouettes with surprised gestures gathered around a big stone idol with an axe, dramatic but funny mood' },
    { emoji:'🤫', text:'فَسَكَتُوا، لِأَنَّهُمْ يَعْرِفُون: الصَّنَمُ لَا يَتَكَلَّمُ وَلَا يَتَحَرَّك! فَكَيْفَ يَكُونُ إِلَهًا؟',
      prompt:'A close-up of a silent stone idol face with a tiny bird perched on its head, dust and cobwebs, gentle humor, no people' },
    { emoji:'🧸', text:'جَرِّبْ: ضَعْ لُعْبَتَكَ أَمَامَكَ وَقُلْ لَهَا: نَاوِلِينِي كُوبًا! هَلْ تَفْعَل؟ لَا! الَّذِي لَا يَنْفَعُ نَفْسَهُ لَا يُعْبَد.',
      prompt:'A cute teddy bear sitting next to an empty cup on a childs table, waiting, soft home light, playful' },
    { emoji:'🧡', text:'نَحْنُ نَعْبُدُ اللهَ وَحْدَه: الَّذِي يَسْمَعُنَا وَيَرَانَا وَيَرْزُقُنَا وَيُحِبُّنَا.',
      prompt:'Warm golden light rays over a child hands raised in dua, seen from behind, cozy room, tender feeling' },
  ],
  moral:'أَعْبُدُ اللهَ الَّذِي يَسْمَعُنِي وَيَرَانِي، لَا شَيْئًا لَا يَتَحَرَّك. 🧡',
  game:{ type:'find', title:'الْأَصْنَامُ لَا تَتَحَرَّك! جِدِ الْعَصَافِيرَ الْحَيَّةَ الثَّلَاثَةَ بَيْنَهَا', target:'🐦', count:3, distractors:['🗿'], size:12 },
  act:{ q:'هَلْ يَسْتَطِيعُ الصَّنَمُ أَنْ يَسْمَعَ أَوْ يَتَكَلَّم؟', yay:'صَحِيح! لِذَلِكَ نَعْبُدُ اللهَ الَّذِي يَسْمَعُنَا وَيَرَانَا', opts:[
    { e:'🗣️', t:'نَعَم، يَتَكَلَّمُ كَثِيرًا' },
    { e:'🙊', t:'لَا! لَا يَسْمَعُ وَلَا يَتَكَلَّمُ وَلَا يَتَحَرَّك', ok:true },
    { e:'🎵', t:'يُغَنِّي أَحْيَانًا' } ] },
  dua:'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِين' },

{ id:'employee', icon:'🐑', color:'#27AE60', title:'خَمْسَةُ رُعَاةٍ لِخَرُوفٍ وَاحِد',
  tag:'رَبٌّ وَاحِدٌ يَعْنِي رَاحَة',
  pages:[
    { emoji:'🐑', text:'كَانَ هُنَاكَ خَرُوفٌ صَغِيرٌ لَطِيف، لَهُ خَمْسَةُ رُعَاةٍ يَتَخَاصَمُونَ طُولَ الْوَقْت!',
      prompt:'A cute fluffy little sheep looking confused between five shepherd staffs planted around it, green meadow, storybook style' },
    { emoji:'🗯️', text:'قَالَ الْأَوَّل: اذْهَبْ يَمِينًا! وَقَالَ الثَّانِي: بَلْ يَسَارًا! وَقَالَ الثَّالِث: قِفْ مَكَانَك!',
      prompt:'Five colorful arrows pointing different directions above a dizzy cartoon sheep, funny chaos' },
    { emoji:'😵‍💫', text:'صَارَ الْخَرُوفُ حَائِرًا تَعْبَانًا، لَا يَعْرِفُ مَنْ يَسْمَعُ مِنْهُم، وَلَا يَنَامُ مِنَ الْقَلَق.',
      prompt:'A tired dizzy cartoon sheep with spiral eyes sitting in a meadow at dusk, sympathetic humor' },
    { emoji:'🐑💚', text:'وَكَانَ هُنَاكَ خَرُوفٌ آخَرُ لَهُ رَاعٍ وَاحِدٌ طَيِّبٌ يُحِبُّه، يَعْرِفُ مَتَى يَأْكُلُ وَمَتَى يَنَام. فَعَاشَ سَعِيدًا هَانِئًا.',
      prompt:'A happy sheep resting beside one kind shepherd silhouette under a tree, sunset meadow, peaceful and warm' },
    { emoji:'⚖️', text:'سَأَلَ الله: هَلْ يَسْتَوِي الِاثْنَان؟ طَبْعًا لَا! رَبٌّ وَاحِدٌ يَعْنِي قَلْبٌ مُرْتَاح.',
      prompt:'A balanced golden scale glowing under soft light, one side peaceful, ornamental Islamic frame' },
    { emoji:'💚', text:'الْحَمْدُ لِلَّه! لَنَا رَبٌّ وَاحِدٌ رَحِيمٌ يُحِبُّنَا وَيَكْفِينَا، فَقُلُوبُنَا مُطْمَئِنَّة.',
      prompt:'A cozy home at evening with warm windows glowing, family silhouettes inside, crescent moon above, safe and content' },
  ],
  moral:'رَبِّي وَاحِدٌ يُحِبُّنِي — فَقَلْبِي مُرْتَاحٌ مُطْمَئِنّ. 💚',
  game:{ type:'sort', title:'ضَعْ كُلَّ وَاحِدٍ فِي السَّلَّةِ الصَّحِيحَة', bins:['قَلْبٌ مُرْتَاح 💚','قَلْبٌ حَائِر 😵‍💫'], items:[
    { e:'🐑', t:'خَرُوفٌ لَهُ رَاعٍ وَاحِدٌ طَيِّب', bin:0 },
    { e:'🐏', t:'خَرُوفٌ لَهُ خَمْسَةُ رُعَاةٍ يَتَخَاصَمُون', bin:1 },
    { e:'😵‍💫', t:'مُوَظَّفٌ لَهُ مُدَرَاءُ كَثِيرُونَ مُتَخَاصِمُون', bin:1 },
    { e:'👦', t:'طِفْلٌ رَبُّهُ وَاحِدٌ يُحِبُّه', bin:0 } ] },
  act:{ q:'أَيُّ خَرُوفٍ عَاشَ سَعِيدًا مُطْمَئِنًّا؟', yay:'أَحْسَنْت! رَبٌّ وَاحِدٌ يَعْنِي قَلْبٌ مُرْتَاح', opts:[
    { e:'😵‍💫', t:'الَّذِي لَهُ خَمْسَةُ رُعَاةٍ يَتَخَاصَمُون' },
    { e:'💚', t:'الَّذِي لَهُ رَاعٍ وَاحِدٌ طَيِّب', ok:true } ] },
  dua:'اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَام' },

{ id:'sunrise', icon:'🌅', color:'#F1C40F', title:'تَحَدِّي الشَّمْس',
  tag:'الْمَلِكُ الْحَقِيقِيُّ يَمْلِكُ كُلَّ شَيْء',
  pages:[
    { emoji:'👑', text:'كَانَ هُنَاكَ مَلِكٌ مُتَكَبِّرٌ اسْمُهُ النَّمْرُود، قَال: أَنَا إِلَه! فَوَقَفَ أَمَامَهُ سَيِّدُنَا إِبْرَاهِيمُ الشُّجَاع.',
      prompt:'A grand arrogant throne room with an oversized golden throne and crown, dramatic shadows, no faces, storybook style' },
    { emoji:'🌱', text:'قَالَ إِبْرَاهِيم: رَبِّي يُحْيِي وَيُمِيت، هُوَ الَّذِي يُعْطِي الْحَيَاة. فَاحْتَالَ الْمَلِكُ بِحِيلَةٍ سَخِيفَة.',
      prompt:'A tiny green seedling sprouting from dark soil with morning dew, symbol of life, macro view, hopeful light' },
    { emoji:'🌅', text:'فَقَالَ إِبْرَاهِيم: اللهُ يَأْتِي بِالشَّمْسِ مِنَ الْمَشْرِق، هَيَّا أَنْتَ أَحْضِرْهَا مِنَ الْمَغْرِب!',
      prompt:'A glorious sunrise over eastern hills, giant warm sun rising with golden rays, birds flying, majestic' },
    { emoji:'😶', text:'سَكَتَ الْمَلِكُ وَلَمْ يَسْتَطِعْ أَنْ يَقُولَ شَيْئًا! لِأَنَّهُ لَا يَسْتَطِيعُ أَنْ يُحَرِّكَ الشَّمْسَ أَبَدًا.',
      prompt:'The empty throne with the crown fallen sideways, sunset light through big windows, silence, gentle humor' },
    { emoji:'🌞', text:'جَرِّبْ أَنْت: قُلْ لِلشَّمْسِ عِنْدَ الْغُرُوب: انْتَظِرِي دَقِيقَة! هَلْ تَسْمَعُك؟ لَا! الشَّمْسُ تُطِيعُ اللهَ وَحْدَه.',
      prompt:'A child silhouette on a hill waving at a big setting sun, playful innocent moment, orange sky' },
    { emoji:'💛', text:'الْمَلِكُ الْحَقِيقِيُّ هُوَ الله: لَهُ الْمُلْكُ كُلُّه، وَالشَّمْسُ وَالْقَمَرُ وَالنُّجُومُ جُنُودُهُ تُطِيعُه.',
      prompt:'Sun moon and stars arranged like obedient glowing jewels in a majestic sky mandala, gold and deep blue' },
  ],
  moral:'الْمُلْكُ كُلُّهُ لِلَّه — وَالشَّمْسُ تُطِيعُهُ كُلَّ صَبَاح. 💛',
  game:{ type:'maze', title:'رَافِقِ الشَّمْسَ فِي رِحْلَتِهَا مِنَ الْمَشْرِقِ إِلَى الْمَغْرِب', avatar:'☀️', goal:'🌇', wall:'☁️', map:['S....','.###.','.#...','.#.#.','...#G'] },
  act:{ q:'مَنْ يَأْمُرُ الشَّمْسَ فَتُشْرِقُ كُلَّ صَبَاح؟', yay:'صَحِيح! الشَّمْسُ جُنْدِيٌّ مِنْ جُنُودِ الله', opts:[
    { e:'👑', t:'الْمَلِكُ الْمُتَكَبِّر' },
    { e:'👨', t:'النَّاس' },
    { e:'💛', t:'اللهُ وَحْدَه', ok:true } ] },
  dua:'لَكَ الْمُلْكُ وَلَكَ الْحَمْدُ وَأَنْتَ عَلَى كُلِّ شَيْءٍ قَدِير' },

{ id:'hungry', icon:'🍽️', color:'#E74C3C', title:'الْإِلَهُ لَا يَجُوع',
  tag:'مَنْ يَأْكُلُ وَيَحْتَاجُ لَا يَكُونُ إِلَهًا',
  pages:[
    { emoji:'🍽️', text:'أَنَا وَأَنْتَ نَجُوعُ كُلَّ يَوْم، فَنَأْكُلُ وَنَشْرَب. وَمَنْ يَأْكُلُ فَهُوَ يَحْتَاجُ الطَّعَام.',
      prompt:'A cheerful family dinner table with warm food, bread and fruit, cozy kitchen light, no faces detailed' },
    { emoji:'🔌', text:'تَخَيَّلْ آلَةً تَقُول: أَنَا أَقْوَى شَيْءٍ فِي الدُّنْيَا! ثُمَّ تَنْظُرُ خَلْفَهَا فَتَجِدُهَا مَوْصُولَةً بِسِلْكِ الْكَهْرَبَاء!',
      prompt:'A boastful cartoon robot flexing, with an electric cord plugged into a wall socket behind it, funny reveal' },
    { emoji:'🪫', text:'لَوْ نَزَعْتَ السِّلْكَ لَانْطَفَأَتْ! فَهِيَ لَيْسَتْ قَوِيَّة، بَلْ مُحْتَاجَةٌ لِلْكَهْرَبَاء.',
      prompt:'The cartoon robot switched off and slumped, unplugged cord on the floor, dim light, gentle humor' },
    { emoji:'🤔', text:'وَبَعْضُ النَّاسِ عَبَدُوا بَشَرًا يَأْكُلُونَ وَيَنَامُونَ وَيَتْعَبُون! وَمَنْ يَحْتَاجُ الطَّعَامَ وَالنَّوْمَ كَيْفَ يَكُونُ إِلَهًا؟',
      prompt:'An empty dinner plate with question marks floating above it, simple thoughtful scene' },
    { emoji:'🤲', text:'اللهُ الْغَنِيُّ لَا يَجُوعُ وَلَا يَنَامُ وَلَا يَحْتَاجُ شَيْئًا أَبَدًا. هُوَ الَّذِي يُطْعِمُنَا كُلَّنَا!',
      prompt:'Gentle rain falling on green fields and orchards heavy with fruit, generous nature, warm light' },
    { emoji:'❤️', text:'عِنْدَ طَعَامِكَ الْقَادِمِ تَذَكَّرْ: أَنَا أَجُوعُ وَاللهُ يُطْعِمُنِي. الْحَمْدُ لِلَّهِ الْغَنِيِّ الْكَرِيم.',
      prompt:'A child hands holding a warm bowl of soup, steam rising in a heart shape, cozy and grateful' },
  ],
  moral:'اللهُ يُطْعِمُنَا وَلَا يُطْعَم — الْحَمْدُ لِلَّهِ الْغَنِيّ. ❤️',
  game:{ type:'sort', title:'مَنْ يَجُوعُ وَيَحْتَاج، وَمَنْ لَا يَحْتَاجُ أَبَدًا؟', bins:['يَجُوعُ وَيَحْتَاج 🍽️','لَا يَحْتَاجُ أَبَدًا 💪'], items:[
    { e:'👦', t:'الطِّفْل', bin:0 },
    { e:'🐱', t:'الْقِطَّة', bin:0 },
    { e:'🤖', t:'الْآلَةُ الْمَوْصُولَةُ بِالْكَهْرَبَاء', bin:0 },
    { e:'💜', t:'اللهُ الْغَنِيُّ الصَّمَد', bin:1 } ] },
  act:{ q:'هَلْ يَجُوعُ اللهُ مِثْلَنَا؟', yay:'أَحْسَنْت! هُوَ الْغَنِيُّ الَّذِي يُطْعِمُنَا كُلَّنَا', opts:[
    { e:'🍽️', t:'نَعَم، يَأْكُلُ وَيَشْرَب' },
    { e:'🙅', t:'لَا! اللهُ لَا يَجُوعُ وَلَا يَحْتَاجُ أَبَدًا', ok:true },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ أَنْتَ الْغَنِيُّ وَنَحْنُ الْفُقَرَاءُ إِلَيْك' },

{ id:'signature', icon:'✍️', color:'#8E44AD', title:'التَّوْقِيعُ الْوَاحِد',
  tag:'صَانِعٌ وَاحِدٌ لِلْكَوْنِ كُلِّه',
  pages:[
    { emoji:'📱', text:'عِنْدَمَا تَرَى هَاتِفًا وَسَاعَةً وَحَاسُوبًا مِنْ نَفْسِ الشَّرِكَة، تَجِدُهَا مُتَشَابِهَةً تَعْمَلُ بِنَفْسِ الطَّرِيقَة.',
      prompt:'A matching set of cartoon devices phone tablet and smartwatch glowing with the same design style on a desk, tidy and harmonious' },
    { emoji:'🏷️', text:'فَتَعْرِفُ فَوْرًا: صَانِعُهَا وَاحِد! لِأَنَّ كُلَّ صَانِعٍ لَهُ بَصْمَتُهُ الْخَاصَّة.',
      prompt:'One elegant golden signature seal stamped on matching boxes, consistent branding, minimal and clean' },
    { emoji:'🍎', text:'انْظُرْ لِلدُّنْيَا: نَفْسُ الْقَانُونِ الَّذِي يُسْقِطُ التُّفَّاحَةَ مِنَ الشَّجَرَة، يُمْسِكُ الْقَمَرَ فِي السَّمَاء!',
      prompt:'A red apple falling from a tree while the moon glows above, invisible arcs connecting them, magical physics, children illustration' },
    { emoji:'🐜🐘', text:'وَالنَّمْلَةُ الصَّغِيرَةُ وَالْفِيلُ الْكَبِيرُ وَأَنَا وَأَنْت — كُلُّنَا مَخْلُوقُونَ بِنَفْسِ حُرُوفِ الْحَيَاة!',
      prompt:'A tiny ant and a big friendly elephant looking at each other, DNA-like colorful ribbon connecting them playfully' },
    { emoji:'🧩', text:'الدُّنْيَا كُلُّهَا قِطْعَةٌ وَاحِدَةٌ مُتَنَاسِقَة، مِثْلَ لَوْحَةٍ عَلَيْهَا تَوْقِيعٌ وَاحِد.',
      prompt:'A vast beautiful landscape painting with mountains sea sky and animals fitting together like puzzle pieces in harmony' },
    { emoji:'💜', text:'لَوْ صَنَعَهَا آلِهَةٌ كَثِيرُونَ لَاخْتَلَفَتْ وَتَخَرَّبَت. لَكِنَّهَا جَمِيلَةٌ مُرَتَّبَة — فَصَانِعُهَا وَاحِد: اللهُ الْأَحَد!',
      prompt:'Perfect symmetric Islamic star pattern radiating in purple and gold, unity and oneness, ornamental' },
  ],
  moral:'كُلُّ الْكَوْنِ صَنْعَةُ اللهِ الْوَاحِدِ الْأَحَد. 💜',
  game:{ type:'memory', title:'صَانِعٌ وَاحِد! اقْلِبِ الْبِطَاقَاتِ وَجِدْ كُلَّ جِهَازٍ وَتَوْأَمَه', pairs:['📱','⌚','💻'] },
  act:{ q:'الْكَوْنُ كُلُّهُ مُرَتَّبٌ مُتَنَاسِق — فَكَمْ صَانِعُه؟', yay:'صَحِيح! هُوَ اللهُ الْوَاحِدُ الْأَحَد', opts:[
    { e:'☝️', t:'صَانِعٌ وَاحِدٌ أَحَد', ok:true },
    { e:'✌️', t:'صَانِعَانِ اثْنَان' },
    { e:'🔟', t:'صُنَّاعٌ كَثِيرُون' } ] },
  dua:'هُوَ اللهُ الْوَاحِدُ الْأَحَد' },

{ id:'neversets', icon:'⭐', color:'#5B4B8A', title:'رَبِّي لَا يَغِيب',
  tag:'مَا يَغِيبُ لَا يَكُونُ رَبًّا',
  pages:[
    { emoji:'🌃', text:'كَانَ قَوْمُ إِبْرَاهِيمَ يَعْبُدُونَ النُّجُومَ وَالْقَمَرَ وَالشَّمْس! فَأَرَادَ أَنْ يُعَلِّمَهُمْ بِطَرِيقَةٍ ذَكِيَّة.',
      prompt:'Ancient people silhouettes on rooftops gazing at a starry night sky, mysterious mood, deep blue and gold' },
    { emoji:'⭐', text:'لَمَّا جَاءَ اللَّيْلُ رَأَى نَجْمًا لَامِعًا. قَال: هَذَا رَبِّي؟ فَلَمَّا غَابَ النَّجْمُ قَال: لَا أُحِبُّ الَّذِي يَغِيب!',
      prompt:'One bright star twinkling then fading behind clouds over a desert horizon, night scene, storybook style' },
    { emoji:'🌙', text:'ثُمَّ رَأَى الْقَمَرَ كَبِيرًا جَمِيلًا. قَال: هَذَا رَبِّي؟ فَلَمَّا غَابَ الْقَمَرُ قَال: هَذَا يَغِيبُ أَيْضًا!',
      prompt:'A big beautiful full moon setting behind dark hills, its light fading, calm night' },
    { emoji:'☀️', text:'ثُمَّ رَأَى الشَّمْسَ وَهِيَ أَكْبَرُ شَيْء. قَال: هَذَا رَبِّي؟ فَلَمَّا غَرَبَتِ الشَّمْسُ قَال: كُلُّهَا تَغِيب!',
      prompt:'A giant orange sun sinking below the sea horizon, sky turning purple, end of day feeling' },
    { emoji:'🔦', text:'مِثْلَ مِصْبَاحِكَ الصَّغِير: يُضِيءُ ثُمَّ تَنْفَدُ بَطَّارِيَّتُهُ وَيَنْطَفِئ. الَّذِي يَنْطَفِئُ وَيَغِيبُ لَا يَكُونُ رَبًّا.',
      prompt:'A small flashlight flickering off in a dark cozy room, battery symbol low, simple and clear' },
    { emoji:'💫', text:'فَقَالَ إِبْرَاهِيم: رَبِّيَ الَّذِي خَلَقَ النَّجْمَ وَالْقَمَرَ وَالشَّمْس، وَهُوَ لَا يَغِيبُ وَلَا يَنَامُ أَبَدًا!',
      prompt:'Dawn breaking with all stars fading but glorious divine light filling the sky above mountains, hopeful and majestic' },
  ],
  moral:'النُّجُومُ تَغِيبُ وَرَبِّي لَا يَغِيبُ أَبَدًا. 💫',
  game:{ type:'find', title:'النُّجُومُ تَغِيبُ عِنْدَ الصَّبَاح! جِدِ النُّجُومَ الْأَرْبَعَ قَبْلَ أَنْ تَخْتَفِي', target:'⭐', count:4, distractors:['☁️','🐦'], size:12 },
  act:{ q:'مَنِ الَّذِي لَا يَغِيبُ وَلَا يَنْطَفِئُ أَبَدًا؟', yay:'أَحْسَنْت! كُلُّ شَيْءٍ يَغِيبُ إِلَّا اللهُ الْبَاقِي', opts:[
    { e:'⭐', t:'النَّجْمُ اللَّامِع' },
    { e:'☀️', t:'الشَّمْسُ الْكَبِيرَة' },
    { e:'💫', t:'اللهُ الْبَاقِي', ok:true } ] },
  dua:'يَا حَيُّ يَا قَيُّومُ يَا بَاقِي' },

{ id:'web', icon:'🕸️', color:'#C0392B', title:'بَيْتُ الْعَنْكَبُوت',
  tag:'لَا حِمَايَةَ إِلَّا بِالله',
  pages:[
    { emoji:'🕷️', text:'بَنَى عَنْكَبُوتٌ صَغِيرٌ بَيْتًا مِنْ خُيُوطٍ رَفِيعَة، وَقَالَ بِفَخْر: هَذَا حِصْنِي الْقَوِيّ!',
      prompt:'A cute cartoon spider proudly standing on its delicate web between two branches, morning dew drops, soft light' },
    { emoji:'💨', text:'فَجَاءَتْ نَسْمَةُ هَوَاءٍ صَغِيرَة... فَتَمَزَّقَ الْبَيْتُ كُلُّه! بَيْتُ الْعَنْكَبُوتِ أَضْعَفُ الْبُيُوت.',
      prompt:'A gentle breeze with floating leaves tearing a spider web apart, threads flying, the little spider surprised' },
    { emoji:'📄', text:'تَخَيَّلْ فَارِسًا يَذْهَبُ لِلْمُغَامَرَةِ وَدِرْعُهُ مِنْ وَرَق! أَوْ مِظَلَّتُهُ شَبَكَةُ عَنْكَبُوت! هَلْ تَحْمِيه؟ لَا!',
      prompt:'A funny cartoon knight holding a paper shield that is folding over, gentle rain falling, humorous' },
    { emoji:'🧿', text:'وَبَعْضُ النَّاسِ يُعَلِّقُونَ خَرَزَةً أَوْ خَيْطًا وَيَقُولُون: هَذَا يَحْمِينَا! وَهِيَ لَا تَحْمِي نَفْسَهَا مِنَ الْغُبَار.',
      prompt:'A small blue bead charm hanging on a string covered with dust, cobwebs around it, still life, meaningful' },
    { emoji:'🏰', text:'الْحِمَايَةُ الْحَقِيقِيَّةُ عِنْدَ اللهِ الْقَوِيِّ وَحْدَه. مَنْ تَعَلَّقَ بِاللهِ فَهُوَ فِي أَقْوَى حِصْن!',
      prompt:'A magnificent strong fortress on a hill glowing with warm light, safe under a starry protective sky' },
    { emoji:'🛡️', text:'فَإِذَا خِفْتَ يَوْمًا فَقُلْ: حَسْبِيَ اللهُ وَنِعْمَ الْوَكِيل — اللهُ يَكْفِينِي وَيَحْمِينِي.',
      prompt:'A child sleeping peacefully under a blanket, soft light like gentle wings of protection over the room, tender and safe' },
  ],
  moral:'أَتَعَلَّقُ بِاللهِ وَحْدَه — فَهُوَ أَقْوَى حِصْن. 🛡️',
  game:{ type:'maze', title:'اعْبُرْ بَيْنَ الْخُيُوطِ الْوَاهِيَةِ إِلَى الْحِصْنِ الْقَوِيّ', avatar:'👦', goal:'🏰', wall:'🕸️', map:['S#...','.#.#.','.#.#.','...#.','##..G'] },
  act:{ q:'مَنْ يَحْمِينِي حِمَايَةً حَقِيقِيَّة؟', yay:'صَحِيح! حَسْبِيَ اللهُ وَنِعْمَ الْوَكِيل', opts:[
    { e:'🧿', t:'الْخَرَزَةُ الزَّرْقَاء' },
    { e:'🛡️', t:'اللهُ الْقَوِيُّ الْوَلِيّ', ok:true },
    { e:'🕸️', t:'بَيْتُ الْعَنْكَبُوت' } ] },
  dua:'حَسْبِيَ اللهُ وَنِعْمَ الْوَكِيل' },

]};
