/* corners/stories/minaret-little/thabat.js — أبطال الثبات (قصص الإيمان والصبر) للصغار (٣–٦)
   ١٢ حكاية مبسّطة من محطات «رحلة الأبطال» في منارة العقيدة.
   كل صفحة: emoji (بديل مؤقت) + text (سطران سهلان) + prompt (وصف صورة إنجليزي لتوليدها لاحقاً).
   ملاحظة فنية: لا نُصوِّر الأنبياءَ ولا وجوهَهم. */
window.MINARET_LITTLE = window.MINARET_LITTLE || {};
window.MINARET_LITTLE.thabat = {
  id:'thabat', icon:'🏔️', color:'#C0392B', title:'أَبْطَالُ الثَّبَات', tag:'قِصَصُ الْإِيمَانِ وَالصَّبْر',
  stories:[

{ id:'ghulam', icon:'🧒', color:'#C0392B', title:'الْغُلَامُ الْمُؤْمِن',
  tag:'بَطَلٌ صَغِيرٌ ثَبَت',
  pages:[
    { emoji:'🧒', text:'كَانَ غُلَامٌ صَغِيرٌ مِثْلُكَ آمَنَ بِاللهِ الْوَاحِد، وَصَارَ اللهُ يَشْفِي عَلَى يَدَيْهِ الْمَرْضَى.',
      prompt:'A young boy with a gentle glow around him in an ancient town, kindness and faith, storybook style' },
    { emoji:'🙏', text:'وَكَانَ يَقُولُ دَائِمًا: أَنَا لَا أَشْفِي، إِنَّمَا يَشْفِي الله! لَمْ يَتَكَبَّرْ يَوْمًا.',
      prompt:'A humble child pointing upward with a soft light, attributing all to Allah, warm and tender' },
    { emoji:'👑', text:'عَذَّبَهُ الْمَلِكُ الظَّالِمُ فَلَمْ يَتْرُكْ إِيمَانَه، وَقَال: قُلْ بِسْمِ اللهِ رَبِّ الْغُلَام.',
      prompt:'A brave small figure standing firm before a large shadowy throne, courage, dramatic but gentle' },
    { emoji:'💚', text:'فَآمَنَتِ الْمَدِينَةُ كُلُّهَا! بَطَلٌ صَغِيرٌ هَدَى اللهُ بِهِ النَّاسَ جَمِيعًا.',
      prompt:'A whole town of tiny figures raising hands in belief under a radiant sky, mass guidance, uplifting' },
  ],
  moral:'لَسْتُ صَغِيرًا عَلَى الْإِيمَانِ الْقَوِيّ — قَلْبُ الطِّفْلِ يَتَّسِعُ لِأَعْظَمِ يَقِين. 💚',
  game:{ type:'order', title:'رَتِّبْ قِصَّةَ الْغُلَامِ الْبَطَل', items:[
    { e:'📖', t:'تَعَلَّمَ الْإِيمَانَ بِالله' },
    { e:'🙏', t:'قَالَ: اللهُ يَشْفِي' },
    { e:'👑', t:'ثَبَتَ أَمَامَ الْمَلِك' },
    { e:'💚', t:'آمَنَتِ الْمَدِينَة' } ] },
  act:{ q:'مَاذَا كَانَ الْغُلَامُ يَقُولُ عِنْدَ الشِّفَاء؟', yay:'أَحْسَنْت! نَسَبَ الشِّفَاءَ لِلَّهِ وَلَمْ يَتَكَبَّر', opts:[
    { e:'🙏', t:'إِنَّمَا يَشْفِي الله', ok:true },
    { e:'😤', t:'أَنَا الْقَوِيّ' },
    { e:'🤷', t:'لَا شَيْء' } ] },
  dua:'اللَّهُمَّ ثَبِّتْنِي عَلَى دِينِكَ كَمَا ثَبَّتَّ الْغُلَامَ الْمُؤْمِن' },

{ id:'kahf', icon:'🕳️', color:'#2C7A6B', title:'فِتْيَةُ الْكَهْف',
  tag:'شَبَابٌ آمَنُوا بِرَبِّهِم',
  pages:[
    { emoji:'🕳️', text:'شَبَابٌ عَاشُوا فِي مَدِينَةٍ تَعْبُدُ الْأَصْنَام، فَفَكَّرُوا وَعَرَفُوا أَنَّ الرَّبَّ الْحَقَّ هُوَ خَالِقُ السَّمَاء.',
      prompt:'A group of young figures gazing thoughtfully at the sky away from stone idols, realization, warm dawn' },
    { emoji:'🗣️', text:'وَقَفُوا بِشَجَاعَةٍ وَقَالُوا: رَبُّنَا رَبُّ السَّمَاوَاتِ وَالْأَرْضِ لَنْ نَدْعُوَ غَيْرَه!',
      prompt:'Young figures standing firm together with a soft glow, brave stand, unity, warm light' },
    { emoji:'⛰️', text:'وَلَجَؤُوا إِلَى كَهْفٍ لِيَحْفَظُوا دِينَهُم، فَأَنَامَهُمُ اللهُ فِيهِ ثَلَاثَمِئَةٍ وَتِسْعَ سِنِين!',
      prompt:'A peaceful cave in a mountain with soft light and a faithful dog at the entrance, protection, serene' },
    { emoji:'🐕', text:'وَحَفِظَهُمُ اللهُ بِكَلْبِهِم عَلَى الْبَاب، ثُمَّ أَيْقَظَهُم آيَةً عَلَى قُدْرَتِه.',
      prompt:'A loyal dog guarding a glowing cave entrance under stars, faithful watch, warm and safe' },
  ],
  moral:'دِينِي أَغْلَى مِنْ كُلِّ شَيْء، وَأَبْتَعِدُ عَنِ السُّوءِ لِأَحْفَظَه. ⛰️',
  game:{ type:'maze', title:'أَوْصِلِ الْفِتْيَةَ إِلَى كَهْفِ الْأَمَان', avatar:'🚶', goal:'🕳️', wall:'🗿', map:['S.#..','.###.','...#.','##...','#..#G'] },
  act:{ q:'لِمَاذَا لَجَأَ الْفِتْيَةُ إِلَى الْكَهْف؟', yay:'صَحِيح! لِيَحْفَظُوا دِينَهُم', opts:[
    { e:'⛰️', t:'لِيَحْفَظُوا إِيمَانَهُم', ok:true },
    { e:'🏖️', t:'لِلنُّزْهَة' },
    { e:'😴', t:'لِلنَّوْمِ فَقَط' } ] },
  dua:'رَبَّنَا آتِنَا مِنْ لَدُنْكَ رَحْمَةً وَهَيِّئْ لَنَا مِنْ أَمْرِنَا رَشَدًا' },

{ id:'sahara', icon:'🪄', color:'#8E44AD', title:'سَحَرَةُ فِرْعَوْن',
  tag:'مِنْ أَعْدَاءٍ إِلَى مُؤْمِنِين',
  pages:[
    { emoji:'🪄', text:'جَمَعَ فِرْعَوْنُ أَمْهَرَ السَّحَرَةِ لِيَتَحَدَّوْا مُوسَى، طَمَعًا فِي الْمَالِ وَالْجَاه.',
      prompt:'A grand ancient arena with magical ropes and staffs on the ground, spectacle, dramatic warm light' },
    { emoji:'🐍', text:'أَلْقَى مُوسَى عَصَاهُ بِأَمْرِ اللهِ فَصَارَتْ ثُعْبَانًا ابْتَلَعَ كُلَّ سِحْرِهِم!',
      prompt:'A large serpent of light swallowing scattered magic ropes, miracle over trickery, awe' },
    { emoji:'🙇', text:'فَعَرَفَ السَّحَرَةُ أَنَّ هَذَا لَيْسَ سِحْرًا بَلْ آيَةٌ مِنَ الله، فَسَجَدُوا فَوْرًا!',
      prompt:'Figures falling into prostration before a burst of divine light, sudden faith, reverent, no faces' },
    { emoji:'💪', text:'هَدَّدَهُم فِرْعَوْنُ بِالْقَتْل، فَقَالُوا: لَنْ نُؤْثِرَكَ عَلَى الْحَقّ! وَاللهُ خَيْرٌ وَأَبْقَى.',
      prompt:'Figures standing firm with hearts like mountains facing a shadowy throne, courage, warm glow' },
  ],
  moral:'الشُّجَاعَةُ أَنْ أَتْبَعَ الْحَقَّ فَوْرَ أَنْ أَعْرِفَه، مَهْمَا كَانَ الثَّمَن. 🙇',
  game:{ type:'sort', title:'كَيْفَ تَغَيَّرَ السَّحَرَةُ فِي يَوْمٍ وَاحِد؟', bins:['فِي الصَّبَاح 🌅','فِي الْمَسَاء 🌙'], items:[
    { e:'💰', t:'يَطْلُبُونَ مَالَ فِرْعَوْن', bin:0 },
    { e:'💚', t:'شُهَدَاءُ يَطْلُبُونَ الْجَنَّة', bin:1 },
    { e:'🙇', t:'آمَنُوا بِرَبِّ مُوسَى', bin:1 },
    { e:'🪄', t:'سَحَرَةٌ يَخْدُمُونَ الْبَاطِل', bin:0 } ] },
  act:{ q:'مَاذَا فَعَلَ السَّحَرَةُ حِينَ رَأَوُا الْمُعْجِزَة؟', yay:'أَحْسَنْت! تَبِعُوا الْحَقَّ فَوْرًا وَلَمْ يَخَافُوا', opts:[
    { e:'🙇', t:'سَجَدُوا وَآمَنُوا بِالله', ok:true },
    { e:'🏃', t:'هَرَبُوا خَائِفِين' },
    { e:'💰', t:'أَخَذُوا الْمَالَ وَسَكَتُوا' } ] },
  dua:'رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَتَوَفَّنَا مُسْلِمِين' },

{ id:'asiya', icon:'👑', color:'#B0578D', title:'آسِيَةُ فِي الْقَصْر',
  tag:'مُؤْمِنَةٌ فِي بَيْتِ الطَّاغِيَة',
  pages:[
    { emoji:'🏯', text:'آسِيَةُ زَوْجَةُ فِرْعَوْنَ عَاشَتْ فِي أَفْخَمِ قَصْر، لَكِنَّهَا آمَنَتْ بِاللهِ الْوَاحِدِ فِي السِّرّ.',
      prompt:'A luxurious golden palace with a soft light in one window, hidden faith within grandeur, warm' },
    { emoji:'💪', text:'عَذَّبَهَا فِرْعَوْنُ لِتَتْرُكَ إِيمَانَهَا، فَثَبَتَتْ وَلَمْ تَتْرُكْ رَبَّهَا أَبَدًا.',
      prompt:'A steadfast glowing figure with hands raised to the sky, unbroken faith, warm resilient light' },
    { emoji:'🤲', text:'رَفَعَتْ يَدَيْهَا وَدَعَت: رَبِّ ابْنِ لِي عِنْدَكَ بَيْتًا فِي الْجَنَّة!',
      prompt:'Hands raised to a radiant sky with a glimpse of a heavenly house of light, hopeful dua, serene' },
    { emoji:'🏡', text:'فَأَرَاهَا اللهُ بَيْتَهَا فِي الْجَنَّةِ فَابْتَسَمَت، وَصَارَتْ مَثَلًا لِكُلِّ الْمُؤْمِنِين.',
      prompt:'A beautiful glowing house in a paradise garden with warm welcoming light, reward and peace' },
  ],
  moral:'الْإِيمَانُ لَا يَحْتَاجُ ظُرُوفًا سَهْلَة، بَلْ قَلْبًا صَادِقًا يُرِيدُ اللهَ أَوَّلًا. 👑',
  act:{ q:'مَاذَا طَلَبَتْ آسِيَةُ وَهِيَ تُعَذَّب؟', yay:'صَحِيح! طَلَبَتْ بَيْتًا فِي الْجَنَّةِ قُرْبَ رَبِّهَا', opts:[
    { e:'🏡', t:'بَيْتًا فِي الْجَنَّة', ok:true },
    { e:'💰', t:'مَالًا أَكْثَر' },
    { e:'👑', t:'قَصْرًا أَكْبَر' } ] },
  game:{ type:'pairs', title:'صِلْ كُلَّ شَيْءٍ بِمَعْنَاه', pairs:[
    ['🏯 قَصْرُ فِرْعَوْن','مُلْكٌ زَائِلٌ تَرَكَتْه'],
    ['🏡 بَيْتُ الْجَنَّة','بَاقٍ لَا يَزُول'],
    ['💚 آسِيَة','مَثَلٌ لِكُلِّ مُؤْمِن'] ] },
  dua:'رَبِّ ابْنِ لِي عِنْدَكَ بَيْتًا فِي الْجَنَّة وَنَجِّنِي مِنْ كُلِّ ظَالِم' },

{ id:'ibrahim', icon:'🪵', color:'#2E8B57', title:'إِبْرَاهِيمُ فِي النَّار',
  tag:'حَسْبُنَا الله',
  pages:[
    { emoji:'🗿', text:'وَقَفَ إِبْرَاهِيمُ وَحْدَهُ أَمَامَ قَوْمِهِ وَكَسَّرَ أَصْنَامَهُم لِيُثْبِتَ أَنَّهَا لَا تَنْفَعُ وَلَا تَضُرّ.',
      prompt:'Broken stone idols in a temple with one axe leaning, a lone brave figure silhouette, warm dusty light' },
    { emoji:'🔥', text:'فَغَضِبُوا وَأَشْعَلُوا نَارًا عَظِيمَةً كَالْجَبَل، وَرَمَوْهُ فِيهَا.',
      prompt:'A towering blazing fire like a mountain, dramatic but not gory, orange and gold flames' },
    { emoji:'🛡️', text:'فَقَالَ إِبْرَاهِيمُ الْكَلِمَةَ الْعَظِيمَة: حَسْبُنَا اللهُ وَنِعْمَ الْوَكِيل!',
      prompt:'A glowing shield of light forming around a figure amid flames, trust and protection, radiant' },
    { emoji:'❄️', text:'فَأَمَرَ اللهُ النَّار: يَا نَارُ كُونِي بَرْدًا وَسَلَامًا! فَخَرَجَ سَالِمًا لَمْ تَمَسَّهُ.',
      prompt:'Flames turning cool with gentle snowflakes and green sprouts appearing, miracle of coolness, serene' },
  ],
  moral:'مَنْ كَانَ اللهُ مَعَه فَهُوَ الْأَقْوَى، وَلَوْ وَقَفَ وَحْدَهُ أَمَامَ الْجَمِيع. 🛡️',
  game:{ type:'find', title:'النَّارُ صَارَتْ بَرْدًا! اجْمَعْ نُدَفَ الثَّلْجِ الْخَمْس', target:'❄️', count:5, distractors:['🔥','🌿'], size:12 },
  act:{ q:'مَاذَا قَالَ إِبْرَاهِيمُ وَهُوَ يُلْقَى فِي النَّار؟', yay:'صَحِيح! فَحَمَاهُ اللهُ وَجَعَلَهَا بَرْدًا وَسَلَامًا', opts:[
    { e:'🛡️', t:'حَسْبُنَا اللهُ وَنِعْمَ الْوَكِيل', ok:true },
    { e:'😱', t:'سَاعِدُونِي!' },
    { e:'🤫', t:'سَكَتَ خَائِفًا' } ] },
  dua:'حَسْبُنَا اللهُ وَنِعْمَ الْوَكِيل' },

{ id:'bilal', icon:'⛓️', color:'#C26A1E', title:'بِلَالٌ — أَحَدٌ أَحَد',
  tag:'قَلْبٌ حُرٌّ لَا يُؤْسَر',
  pages:[
    { emoji:'☀️', text:'كَانَ بِلَالٌ عَبْدًا فَقِيرًا، آمَنَ بِاللهِ لِأَنَّهُ عَرَفَ أَنَّ النَّاسَ سَوَاءٌ لَا فَرْقَ إِلَّا بِالتَّقْوَى.',
      prompt:'A dignified figure standing tall in the desert sun with a peaceful glow, equality and faith, warm' },
    { emoji:'🪨', text:'عَذَّبَهُ سَيِّدُهُ عَلَى الرَّمْلِ الْمُحْرِقِ وَوَضَعَ صَخْرَةً عَلَى صَدْرِهِ لِيَتْرُكَ دِينَه.',
      prompt:'A heavy boulder on hot desert sand under a blazing sun, hardship, dramatic but gentle, warm tones' },
    { emoji:'☝️', text:'فَمَاذَا قَالَ تَحْتَ الْعَذَاب؟ كَلِمَةً وَاحِدَة: أَحَدٌ… أَحَد! رَبِّي اللهُ الْوَاحِد.',
      prompt:'A single finger raised toward a radiant sky with a soft glow of steadfastness, unwavering faith' },
    { emoji:'🕌', text:'ثُمَّ اشْتَرَاهُ أَبُو بَكْرٍ وَأَعْتَقَه، فَصَارَ أَوَّلَ مُؤَذِّنٍ فِي الْإِسْلَامِ فَوْقَ الْكَعْبَة!',
      prompt:'A figure calling the adhan atop a high place at dawn, voice rising, honor and triumph, golden light' },
  ],
  moral:'قِيمَتِي عِنْدَ اللهِ بِإِيمَانِي لَا بِمَالِي، وَقَلْبِي الْمُؤْمِنُ حُرٌّ لَا يُؤْسَر. ☝️',
  game:{ type:'sort', title:'مَا مِيزَانُ الْقِيمَةِ عِنْدَ الله؟', bins:['يَرْفَعُ عِنْدَ الله ⬆️','لَا قِيمَةَ لَهُ عِنْدَ الله 🚫'], items:[
    { e:'🕌', t:'التَّقْوَى وَالْإِيمَان', bin:0 },
    { e:'💰', t:'كَثْرَةُ الْمَال', bin:1 },
    { e:'🤝', t:'الصِّدْقُ وَالْعَمَلُ الطَّيِّب', bin:0 },
    { e:'👗', t:'الْمَظْهَرُ وَالثِّيَاب', bin:1 } ] },
  act:{ q:'مَا الَّذِي يَرْفَعُ قِيمَتِي عِنْدَ الله؟', yay:'أَحْسَنْت! التَّقْوَى وَالْإِيمَان، لَا الْمَالُ وَالْقُوَّة', opts:[
    { e:'☝️', t:'إِيمَانِي وَتَقْوَايَ', ok:true },
    { e:'💰', t:'مَالِي' },
    { e:'💪', t:'قُوَّةُ عَضَلَاتِي' } ] },
  dua:'اللَّهُمَّ اجْعَلْنِي مِنَ الْمُتَّقِينَ وَارْفَعْ قَدْرِي بِطَاعَتِك' },

{ id:'yasir', icon:'🤲', color:'#A03050', title:'آلُ يَاسِر',
  tag:'أَوَّلُ بَيْتٍ صَبَر',
  pages:[
    { emoji:'🌹', text:'عَائِلَةٌ كَامِلَةٌ صَبَرَتْ مَعًا: يَاسِرٌ وَزَوْجَتُهُ سُمَيَّةُ وَابْنُهُمَا عَمَّار، مِنْ أَوَائِلِ مَنْ آمَن.',
      prompt:'A family of gentle glowing figures standing together in unity, warmth and togetherness, soft light' },
    { emoji:'☀️', text:'عُذِّبُوا عَلَى رَمْلِ مَكَّةَ الْمُحْرِق، وَكَانَ النَّبِيُّ ﷺ يُثَبِّتُهُم: صَبْرًا آلَ يَاسِر!',
      prompt:'Desert sand under harsh sun with a comforting soft light over three figures, patience, warm hopeful' },
    { emoji:'🌷', text:'فَإِنَّ مَوْعِدَكُمُ الْجَنَّة! فَتَحَوَّلَ أَلَمُهُم إِلَى أَمَلٍ وَنُور.',
      prompt:'A ray of paradise light shining down on the family, hope amid hardship, uplifting golden glow' },
    { emoji:'💚', text:'وَسُمَيَّةُ ثَبَتَتْ حَتَّى صَارَتْ أَوَّلَ شَهِيدَةٍ فِي الْإِسْلَام، ثَابِتَةً عَلَى إِيمَانِهَا.',
      prompt:'A single rose glowing softly with light rising to the sky, honor and sacrifice, tender and warm' },
  ],
  moral:'الْبَلَاءُ امْتِحَانٌ يَرْفَعُ دَرَجَتِي، وَالثَّبَاتُ أَقْوَى حِينَ يَكُونُ بَيْتِي بَيْتَ إِيمَان. 💚',
  game:{ type:'find', title:'ثَبَّتَهُمُ النَّبِيُّ ﷺ! اجْمَعِ الْقُلُوبَ الصَّابِرَةَ الْخَمْس', target:'💚', count:5, distractors:['☀️','🪨'], size:12 },
  act:{ q:'بِمَاذَا ثَبَّتَ النَّبِيُّ ﷺ آلَ يَاسِر؟', yay:'صَحِيح! بَشَّرَهُم بِالْجَنَّة', opts:[
    { e:'🌷', t:'صَبْرًا آلَ يَاسِر، مَوْعِدُكُمُ الْجَنَّة', ok:true },
    { e:'💰', t:'وَعَدَهُم بِالْمَال' },
    { e:'🏃', t:'قَالَ لَهُم اهْرُبُوا' } ] },
  dua:'اللَّهُمَّ اجْعَلْ بَيْتَنَا بَيْتَ إِيمَانٍ وَطَاعَة' },

{ id:'mashita', icon:'💇', color:'#A8527C', title:'مَاشِطَةُ فِرْعَوْن',
  tag:'أُمٌّ وَأَطْفَالُهَا',
  pages:[
    { emoji:'💇', text:'كَانَتْ تُمَشِّطُ شَعْرَ ابْنَةِ فِرْعَوْن، فَسَقَطَ الْمُشْطُ فَقَالَت: بِسْمِ الله!',
      prompt:'A comb resting by soft light in a palace room, a moment of faith, warm gentle scene, no faces' },
    { emoji:'🗣️', text:'قَالَتْ بِشَجَاعَة: رَبِّي وَرَبُّكِ وَرَبُّ أَبِيكِ اللهُ! فَعَلِمَ فِرْعَوْنُ وَأَرَادَ أَنْ تَكْفُر.',
      prompt:'A brave glowing figure speaking truth in a grand hall, courage before power, warm light, no face' },
    { emoji:'👶', text:'فَثَبَتَتْ هِيَ وَأَطْفَالُهَا، حَتَّى أَنْطَقَ اللهُ رَضِيعَهَا: يَا أُمَّاهُ اصْبِرِي فَإِنَّكِ عَلَى الْحَقّ!',
      prompt:'A soft glowing light around a baby with rays of reassurance, miracle of speech, tender and warm' },
    { emoji:'🌸', text:'فَصَارُوا جَمِيعًا إِلَى الْجَنَّة، وَشَمَّ النَّبِيُّ ﷺ عِطْرَهَا لَيْلَةَ الْإِسْرَاء.',
      prompt:'A trail of beautiful fragrance shown as glowing flower petals rising to a starry sky, paradise scent' },
  ],
  moral:'الْإِيمَانُ أَغْلَى مِنْ أَعَزِّ مَا أَمْلِك، وَاللهُ يُثَبِّتُنِي مِنْ حَيْثُ لَا أَحْتَسِب. 🌸',
  game:{ type:'order', title:'رَتِّبْ قِصَّةَ الْمَاشِطَةِ الثَّابِتَة', items:[
    { e:'💇', t:'سَقَطَ الْمُشْطُ فَقَالَتْ بِسْمِ الله' },
    { e:'🗣️', t:'قَالَتِ الْحَقَّ بِشَجَاعَة' },
    { e:'👶', t:'أَنْطَقَ اللهُ رَضِيعَهَا' },
    { e:'🌸', t:'صَارُوا إِلَى الْجَنَّة' } ] },
  act:{ q:'مَاذَا قَالَ الرَّضِيعُ لِأُمِّهِ؟', yay:'صَحِيح! ثَبَّتَهَا اللهُ بِلِسَانِ رَضِيعِهَا', opts:[
    { e:'👶', t:'اصْبِرِي فَإِنَّكِ عَلَى الْحَقّ', ok:true },
    { e:'😢', t:'بَكَى فَقَط' },
    { e:'🤫', t:'لَمْ يَقُلْ شَيْئًا' } ] },
  dua:'اللَّهُمَّ يَا مُثَبِّتَ الْقُلُوب، ثَبِّتْنِي وَأَهْلِي عَلَى دِينِك' },

{ id:'khubayb', icon:'🕌', color:'#33691E', title:'خُبَيْبٌ — رَكْعَتَانِ قَبْلَ الْوَدَاع',
  tag:'الصَّلَاةُ رَاحَةُ الْقَلْب',
  pages:[
    { emoji:'📿', text:'خُبَيْبٌ صَحَابِيٌّ أَسَرَهُ أَعْدَاؤُهُ وَأَرَادُوا قَتْلَه، فَطَلَبَ أَنْ يُصَلِّيَ رَكْعَتَيْنِ أَوَّلًا.',
      prompt:'A figure standing in humble prayer at dawn with a soft glow, devotion in hardship, warm and serene' },
    { emoji:'🕌', text:'فَصَلَّى رَكْعَتَيْنِ خَاشِعَتَيْنِ جَمِيلَتَيْن، لِأَنَّ الصَّلَاةَ كَانَتْ أَحَبَّ شَيْءٍ إِلَى قَلْبِه.',
      prompt:'A peaceful prayer scene with warm light streaming down, tranquility and focus, gentle glow' },
    { emoji:'💪', text:'ثُمَّ قَال: لَوْلَا أَنْ تَظُنُّوا أَنِّي أَخَافُ الْمَوْتَ لَزِدْت! لَمْ يَخَفِ الْمَوْتَ أَبَدًا.',
      prompt:'A calm brave figure with steady posture and a soft glow of courage, fearlessness, warm light' },
    { emoji:'💚', text:'فَصَارَ أَوَّلَ مَنْ صَلَّى رَكْعَتَيْنِ قَبْلَ الشَّهَادَة، وَمَاتَ وَقَلْبُهُ مُعَلَّقٌ بِرَبِّه.',
      prompt:'A heart of light connected by a gentle beam to a radiant sky, connection to Allah, serene and warm' },
  ],
  moral:'صَلَاتِي رَاحَةُ قَلْبِي وَلِقَائِي بِرَبِّي، لَا عِبْءٌ أُؤَخِّرُه. 🕌',
  game:{ type:'maze', title:'أَوْصِلْ خُبَيْبًا إِلَى مُصَلَّاهُ لِيُصَلِّيَ رَكْعَتَيْه', avatar:'🚶', goal:'🕌', wall:'⛓️', map:['S#...','.#.#.','.#.#.','...#.','##..G'] },
  act:{ q:'لِمَاذَا طَلَبَ خُبَيْبٌ الصَّلَاةَ قَبْلَ مَوْتِه؟', yay:'أَحْسَنْت! لِأَنَّهَا رَاحَةُ قَلْبِهِ وَلِقَاؤُهُ بِرَبِّه', opts:[
    { e:'💚', t:'لِأَنَّهَا أَحَبُّ شَيْءٍ إِلَى قَلْبِه', ok:true },
    { e:'⏰', t:'لِيُؤَخِّرَ الْوَقْت' },
    { e:'🤷', t:'بِلَا سَبَب' } ] },
  dua:'اللَّهُمَّ اجْعَلِ الصَّلَاةَ قُرَّةَ عَيْنِي وَرَاحَةَ قَلْبِي' },

{ id:'habib', icon:'🏃', color:'#1E8C7E', title:'مُؤْمِنُ سُورَةِ يس',
  tag:'يَا لَيْتَ قَوْمِي يَعْلَمُون',
  pages:[
    { emoji:'🏃', text:'رَجُلٌ عَادِيٌّ سَمِعَ بِالرُّسُلِ فَآمَنَ فَوْرًا، وَجَاءَ يَرْكُضُ مِنْ أَقْصَى الْمَدِينَةِ لِيَنْصُرَهُم.',
      prompt:'A figure running eagerly through a town toward messengers, zeal for good, warm dynamic light' },
    { emoji:'🗣️', text:'قَالَ لِقَوْمِه: يَا قَوْمِ اتَّبِعُوا الْمُرْسَلِينَ الَّذِينَ لَا يَسْأَلُونَكُم أَجْرًا!',
      prompt:'A brave figure addressing a crowd with a soft glow, calling to good, warm hopeful scene, no face' },
    { emoji:'💚', text:'فَغَضِبَ قَوْمُهُ وَقَتَلُوهُ ظُلْمًا لِأَنَّهُ دَعَا إِلَى الله.',
      prompt:'A soft light rising to the sky from a peaceful scene, sacrifice for truth, gentle and warm, no gore' },
    { emoji:'🌸', text:'وَفِي الْجَنَّةِ لَمْ يَتَمَنَّ الِانْتِقَام، بَلْ قَال: يَا لَيْتَ قَوْمِي يَعْلَمُونَ بِمَا غَفَرَ لِي رَبِّي!',
      prompt:'A serene figure in a paradise garden wishing goodness for others, mercy and forgiveness, radiant' },
  ],
  moral:'لَسْتُ عَادِيًّا صَغِيرًا: كَلِمَةُ خَيْرٍ أَدْعُو بِهَا قَدْ تَرْفَعُنِي عِنْدَ الله. 🏃',
  game:{ type:'find', title:'كُنْ دَاعِيًا لِلْخَيْر! اجْمَعِ الْقُلُوبَ الْمُحِبَّةَ الْخَمْس', target:'💚', count:5, distractors:['🚪','😠'], size:12 },
  act:{ q:'مَاذَا تَمَنَّى مُؤْمِنُ يس فِي الْجَنَّة؟', yay:'صَحِيح! تَمَنَّى الْخَيْرَ حَتَّى لِقَاتِلِيه', opts:[
    { e:'🌸', t:'لَيْتَ قَوْمِي يَعْلَمُونَ نَعِيمَ الْإِيمَان', ok:true },
    { e:'⚔️', t:'الِانْتِقَامَ مِنْهُم' },
    { e:'🤷', t:'لَا شَيْء' } ] },
  dua:'اللَّهُمَّ اهْدِ قَوْمِي وَأَحْبَابِي وَاجْعَلْنِي مِنَ الْمُكْرَمِين' },

{ id:'dajjal', icon:'🧔', color:'#3D5A80', title:'الثَّابِتُ أَمَامَ الدَّجَّال',
  tag:'الْعِلْمُ دِرْعٌ يَحْمِينِي',
  pages:[
    { emoji:'🛡️', text:'فِي آخِرِ الزَّمَانِ يَخْرُجُ الدَّجَّالُ يَدَّعِي الرُّبُوبِيَّةَ وَيُرِي النَّاسَ عَجَائِبَ اخْتِبَارًا.',
      prompt:'A stormy horizon with a shadowy deceptive figure far away, trial and test, dramatic but not scary, muted' },
    { emoji:'🗣️', text:'فَيَخْرُجُ إِلَيْهِ رَجُلٌ مُؤْمِنٌ وَيَقُولُ بِشَجَاعَة: أَشْهَدُ أَنَّكَ الدَّجَّالُ الَّذِي حَذَّرَنَا مِنْهُ النَّبِيُّ ﷺ!',
      prompt:'A brave lone figure standing firm and pointing with truth, courage before deception, warm glow, no face' },
    { emoji:'💡', text:'عَرَفَهُ لِأَنَّهُ تَعَلَّمَ عَلَامَاتِه: أَعْوَرُ، مَكْتُوبٌ بَيْنَ عَيْنَيْهِ كَافِر، لَا يَدْخُلُ مَكَّةَ وَالْمَدِينَة.',
      prompt:'A glowing lightbulb of knowledge shielding a figure, learning as protection, warm clear illustration' },
    { emoji:'🕌', text:'فَثَبَتَ بِعِلْمِهِ وَإِيمَانِه، وَصَارَ أَعْظَمَ النَّاسِ شَهَادَةً عِنْدَ رَبِّ الْعَالَمِين!',
      prompt:'A steadfast figure with a shield of light standing tall, honor and certainty, radiant warm glow' },
  ],
  moral:'الْعِلْمُ بِدِينِي دِرْعٌ يَحْمِينِي مِنَ الْخُدَع، وَاللهُ يُثَبِّتُ مَنِ اسْتَقَام. 🛡️',
  game:{ type:'sort', title:'مَا أَسْلِحَتِي ضِدَّ الْخُدَع؟', bins:['سِلَاحٌ يَحْمِينِي 🛡️','لَا يَنْفَع 🚫'], items:[
    { e:'📖', t:'حِفْظُ سُورَةِ الْكَهْف', bin:0 },
    { e:'🤲', t:'الِاسْتِعَاذَةُ مِنَ الدَّجَّال', bin:0 },
    { e:'💡', t:'مَعْرِفَةُ عَلَامَاتِه', bin:0 },
    { e:'😴', t:'الْجَهْلُ وَعَدَمُ التَّعَلُّم', bin:1 } ] },
  act:{ q:'كَيْفَ عَرَفَ الرَّجُلُ الدَّجَّالَ فَلَمْ يَنْخَدِع؟', yay:'أَحْسَنْت! الْعِلْمُ دِرْعٌ يَحْمِي مِنَ الْخُدَع', opts:[
    { e:'💡', t:'لِأَنَّهُ تَعَلَّمَ عَلَامَاتِهِ مِنَ النَّبِيِّ ﷺ', ok:true },
    { e:'🎲', t:'صُدْفَةً' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ فِتْنَةِ الْمَسِيحِ الدَّجَّال' },

{ id:'musab', icon:'🎖️', color:'#7B5EA7', title:'مُصْعَبُ بْنُ عُمَيْر',
  tag:'مِنَ التَّرَفِ إِلَى الْفِدَاء',
  pages:[
    { emoji:'🤍', text:'كَانَ مُصْعَبٌ أَجْمَلَ شَابٍّ فِي مَكَّةَ وَأَكْثَرَهُم نَعِيمًا، يَلْبَسُ أَفْخَرَ الثِّيَاب.',
      prompt:'An elegant well-dressed young figure in a rich setting, luxury and youth, warm golden light, no face' },
    { emoji:'📖', text:'ثُمَّ سَمِعَ بِالْإِسْلَامِ فَآمَنَ قَلْبُه، فَتَرَكَ التَّرَفَ كُلَّهُ مِنْ أَجْلِ دِينِه.',
      prompt:'A simple old garment beside abandoned fine clothes with a soft glow of choice, faith over luxury, warm' },
    { emoji:'🕌', text:'اخْتَارَهُ النَّبِيُّ ﷺ أَوَّلَ سَفِيرٍ لِلْإِسْلَام، فَعَلَّمَ أَهْلَ الْمَدِينَةِ الْقُرْآن.',
      prompt:'A figure teaching an open glowing Quran to eager listeners, spreading knowledge, warm hopeful light' },
    { emoji:'🎖️', text:'ثُمَّ اسْتُشْهِدَ فِي أُحُدٍ يَحْمِلُ الرَّايَة، وَرَبِحَ الْجَنَّةَ وَالْخُلُودَ إِلَى الْأَبَد.',
      prompt:'A banner of light held high on a hill at dawn, honor and eternity, triumphant warm glow, no face' },
  ],
  moral:'الدُّنْيَا تَزُولُ وَالْإِيمَانُ يَبْقَى — أَتَمَسَّكُ بِدِينِي مَهْمَا كَانَ الثَّمَن. 🎖️',
  game:{ type:'pairs', title:'صِلْ كُلَّ مَرْحَلَةٍ مِنْ حَيَاةِ مُصْعَب', pairs:[
    ['👗 قَبْلَ الْإِسْلَام','أَنْعَمُ شَابٍّ فِي مَكَّة'],
    ['📖 بَعْدَ الْإِسْلَام','تَرَكَ التَّرَفَ لِدِينِه'],
    ['🎖️ فِي أُحُد','شَهِيدٌ رَبِحَ الْجَنَّة'] ] },
  act:{ q:'مَاذَا اخْتَارَ مُصْعَبٌ الْغَنِيّ؟', yay:'أَحْسَنْت! اخْتَارَ دِينَهُ عَلَى كُلِّ نَعِيمِه', opts:[
    { e:'🤍', t:'دِينَهُ عَلَى كُلِّ الْمَالِ وَالتَّرَف', ok:true },
    { e:'💰', t:'الْمَالَ وَالثِّيَاب' },
    { e:'👑', t:'الْجَاهَ وَالْمَنْصِب' } ] },
  dua:'اللَّهُمَّ ثَبِّتْنِي عَلَى دِينِكَ حَتَّى أَلْقَاك' },

]};
