/* corners/stories/ibada-little/adhkar.js — درع الأذكار للصغار (٣–٦) · ١٠ حكايات */
window.IBADA_LITTLE = window.IBADA_LITTLE || {};
window.IBADA_LITTLE.adhkar = {
  id:'adhkar', icon:'📿', color:'#2980B9', title:'دِرْعُ الْأَذْكَار', tag:'كَلِمَاتٌ تَحْرُسُنِي',
  stories:[

{ id:'shield', icon:'🛡️', color:'#2980B9', title:'الدِّرْعُ الَّذِي لَا يُرَى',
  tag:'مَا هِيَ الْأَذْكَار؟',
  pages:[
    { emoji:'🛡️', text:'الْأَذْكَارُ كَلِمَاتٌ جَمِيلَةٌ نَقُولُهَا فَتَصِيرُ دِرْعًا مِنْ نُورٍ يَحْمِينَا بِإِذْنِ الله.',
      prompt:'A child surrounded by a gentle glowing shield of light while playing, invisible protection, warm' },
    { emoji:'💬', text:'مِثْلُ: سُبْحَانَ الله، الْحَمْدُ لِله، لَا إِلَهَ إِلَّا الله، اللهُ أَكْبَر.',
      prompt:'Glowing words of light floating gently around a happy child, beautiful dhikr, warm serene' },
    { emoji:'😌', text:'كُلَّمَا ذَكَرْتَ اللهَ اطْمَأَنَّ قَلْبُك: أَلَا بِذِكْرِ اللهِ تَطْمَئِنُّ الْقُلُوب.',
      prompt:'A calm child with a glowing peaceful heart, remembrance bringing calm, tender warm light' },
    { emoji:'💙', text:'فَلِسَانِي رَطْبٌ دَائِمًا بِذِكْرِ الله.',
      prompt:'A cheerful child with soft light near the lips speaking dhikr, tongue busy with remembrance, warm' },
  ],
  moral:'الْأَذْكَارُ دِرْعِي مِنْ نُورٍ وَطُمَأْنِينَةُ قَلْبِي. 💙',
  game:{ type:'find', title:'اجْمَعْ كَلِمَاتِ الذِّكْرِ الْخَمْسَ الْمُضِيئَة', target:'📿', count:5, distractors:['☁️','⭐'], size:12 },
  act:{ q:'مَاذَا تَفْعَلُ الْأَذْكَارُ لِقَلْبِي؟', yay:'أَحْسَنْت! تَحْمِينِي وَتُطَمْئِنُ قَلْبِي', opts:[
    { e:'💙', t:'تَحْمِينِي وَتُطَمْئِنُ قَلْبِي', ok:true },
    { e:'😴', t:'لَا شَيْء' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'أَلَا بِذِكْرِ اللهِ تَطْمَئِنُّ الْقُلُوب' },

{ id:'morning', icon:'🌅', color:'#F39C12', title:'حِصْنُ الصَّبَاح',
  tag:'أَذْكَارُ الصَّبَاح',
  pages:[
    { emoji:'🌅', text:'حِينَ أَسْتَيْقِظُ صَبَاحًا، أَلْبَسُ دِرْعِي: أَذْكَارَ الصَّبَاحِ الَّتِي تَحْرُسُنِي طُولَ الْيَوْم.',
      prompt:'A child waking up cheerfully with morning light, starting the day with dhikr, warm cozy' },
    { emoji:'☀️', text:'أَقُول: أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّه، وَبِكَ اللَّهُمَّ أَصْبَحْنَا.',
      prompt:'Warm morning sun rising over a home with soft glowing words, morning remembrance, serene' },
    { emoji:'🛡️', text:'وَأَقُول: بِسْمِ اللهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاء.',
      prompt:'A gentle protective dome of light forming over a child at morning, name of Allah shielding, warm' },
    { emoji:'💚', text:'فَأَمْضِي فِي يَوْمِي آمِنًا مَحْرُوسًا بِإِذْنِ الله.',
      prompt:'A happy child heading out into the day with a soft glow of protection, secure morning, bright' },
  ],
  moral:'أَذْكَارُ الصَّبَاحِ دِرْعِي الَّذِي يَحْرُسُنِي طُولَ الْيَوْم. 💚',
  game:{ type:'order', title:'رَتِّبْ بِدَايَةَ يَوْمِي بِالْأَذْكَار', items:[
    { e:'😴', t:'أَسْتَيْقِظُ وَأَحْمَدُ الله' },
    { e:'☀️', t:'أَقُولُ أَذْكَارَ الصَّبَاح' },
    { e:'🛡️', t:'أَلْبَسُ دِرْعَ الْحِمَايَة' },
    { e:'🏃', t:'أَمْضِي فِي يَوْمِي آمِنًا' } ] },
  act:{ q:'مَتَى نَقُولُ أَذْكَارَ الصَّبَاح؟', yay:'أَحْسَنْت! فِي الصَّبَاحِ لِتَحْرُسَنَا طُولَ الْيَوْم', opts:[
    { e:'🌅', t:'فِي أَوَّلِ الصَّبَاح', ok:true },
    { e:'🌙', t:'فِي مُنْتَصَفِ اللَّيْل' },
    { e:'🤷', t:'لَا وَقْتَ لَهَا' } ] },
  dua:'بِسْمِ اللهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْء' },

{ id:'evening', icon:'🌙', color:'#5B4B8A', title:'حِصْنُ الْمَسَاء',
  tag:'أَذْكَارُ الْمَسَاء',
  pages:[
    { emoji:'🌇', text:'وَحِينَ يَأْتِي الْمَسَاء، أَلْبَسُ دِرْعِي مِنْ جَدِيد: أَذْكَارَ الْمَسَاءِ الَّتِي تَحْرُسُنِي فِي اللَّيْل.',
      prompt:'A child at dusk saying evening dhikr with a warm glow, evening protection, cozy serene' },
    { emoji:'🌙', text:'أَقُول: أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّه، وَأَعُوذُ بِكَلِمَاتِ اللهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَق.',
      prompt:'Evening sky with moon and soft glowing words over a home, evening remembrance, tender' },
    { emoji:'🛏️', text:'وَقَبْلَ النَّوْمِ أَقْرَأُ آيَةَ الْكُرْسِيّ، فَيَكُونُ عَلَيَّ حَافِظٌ مِنَ اللهِ حَتَّى الصَّبَاح.',
      prompt:'A child in bed with a gentle protective light overhead, Ayat al-Kursi guarding sleep, warm' },
    { emoji:'💚', text:'فَأَنَامُ مُطْمَئِنًّا مَحْرُوسًا لَا يَقْرَبُنِي شَيْطَان.',
      prompt:'A peacefully sleeping child under soft moonlight with a warm protective glow, safe sleep, tender' },
  ],
  moral:'أَذْكَارُ الْمَسَاءِ وَآيَةُ الْكُرْسِيِّ تَحْرُسَانِي فِي نَوْمِي. 💚',
  game:{ type:'pairs', title:'صِلْ كُلَّ ذِكْرٍ بِوَقْتِه', pairs:[
    ['🌅 أَصْبَحْنَا وَأَصْبَحَ الْمُلْك','فِي الصَّبَاح'],
    ['🌙 أَمْسَيْنَا وَأَمْسَى الْمُلْك','فِي الْمَسَاء'],
    ['🛏️ آيَةُ الْكُرْسِيّ','قَبْلَ النَّوْم'] ] },
  act:{ q:'مَاذَا نَقْرَأُ قَبْلَ النَّوْمِ لِيَحْرُسَنَا الله؟', yay:'أَحْسَنْت! آيَةُ الْكُرْسِيّ حَافِظٌ حَتَّى الصَّبَاح', opts:[
    { e:'🛏️', t:'آيَةُ الْكُرْسِيّ', ok:true },
    { e:'📺', t:'نُشَاهِدُ التِّلْفَاز' },
    { e:'🤷', t:'لَا شَيْء' } ] },
  dua:'اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّوم' },

{ id:'tasbih', icon:'💫', color:'#16A085', title:'الْكَلِمَاتُ الثَّقِيلَة',
  tag:'خَفِيفَةٌ عَلَى اللِّسَان',
  pages:[
    { emoji:'💫', text:'قَالَ النَّبِيُّ ﷺ: كَلِمَتَانِ خَفِيفَتَانِ عَلَى اللِّسَان، ثَقِيلَتَانِ فِي الْمِيزَان.',
      prompt:'A light feather on a scale outweighing a heavy stone, light words heavy in reward, gentle wonder' },
    { emoji:'🗣️', text:'هُمَا: سُبْحَانَ اللهِ وَبِحَمْدِه، سُبْحَانَ اللهِ الْعَظِيم. ثَانِيَتَانِ تَقُولُهُمَا وَفِي الْمِيزَانِ جَبَل!',
      prompt:'Words of light rising to form a glowing mountain on a scale, heavy reward, radiant' },
    { emoji:'🌴', text:'وَمَنْ قَالَ سُبْحَانَ اللهِ غُرِسَتْ لَهُ نَخْلَةٌ فِي الْجَنَّة!',
      prompt:'A palm tree of light growing in a paradise garden from a spoken word, reward planted, warm' },
    { emoji:'💚', text:'فَأُكْثِرُ مِنْهَا كُلَّ يَوْم، فَأَزْرَعُ بُسْتَانًا فِي الْجَنَّة.',
      prompt:'A lush paradise garden of glowing palm trees, garden grown by dhikr, radiant serene' },
  ],
  moral:'كَلِمَاتُ التَّسْبِيحِ خَفِيفَةٌ تَزْرَعُ لِي بُسْتَانًا فِي الْجَنَّة. 💚',
  game:{ type:'find', title:'كُلُّ تَسْبِيحَةٍ نَخْلَة! اجْمَعِ النَّخَلَاتِ السِّتَّ فِي جَنَّتِك', target:'🌴', count:6, distractors:['🍂','🪨'], size:12 },
  act:{ q:'أَيُّ الْكَلِمَاتِ خَفِيفَةٌ ثَقِيلَةٌ فِي الْمِيزَان؟', yay:'أَحْسَنْت! فِي الْمِيزَانِ جَبَل', opts:[
    { e:'💫', t:'سُبْحَانَ اللهِ وَبِحَمْدِه', ok:true },
    { e:'😴', t:'لَا شَيْء' },
    { e:'😠', t:'كَلَامٌ سَيِّئ' } ] },
  dua:'سُبْحَانَ اللهِ وَبِحَمْدِه سُبْحَانَ اللهِ الْعَظِيم' },

{ id:'istighfar', icon:'🌧️', color:'#3498DB', title:'كَلِمَةٌ تَغْسِلُ الْقَلْب',
  tag:'الِاسْتِغْفَار',
  pages:[
    { emoji:'🌧️', text:'إِذَا أَخْطَأْتُ، أَقُول: أَسْتَغْفِرُ اللهَ وَأَتُوبُ إِلَيْه — فَتُغْسَلُ خَطِيئَتِي كَالْمَطَر.',
      prompt:'Gentle rain washing a surface clean with soft light, forgiveness like rain, warm hopeful' },
    { emoji:'🌱', text:'وَالِاسْتِغْفَارُ يَجْلِبُ الرِّزْقَ وَالْمَطَرَ وَالْخَيْر: اسْتَغْفِرُوا رَبَّكُم يُرْسِلِ السَّمَاءَ مِدْرَارًا.',
      prompt:'Rain falling on green sprouting fields after istighfar, blessings and provision, warm' },
    { emoji:'😊', text:'كَانَ النَّبِيُّ ﷺ يَسْتَغْفِرُ فِي الْيَوْمِ أَكْثَرَ مِنْ سَبْعِينَ مَرَّة، وَهُوَ مَغْفُورٌ لَه!',
      prompt:'A softly glowing prayer space, abundant istighfar, humility and light, serene no figure' },
    { emoji:'💚', text:'فَأُكْثِرُ الِاسْتِغْفَارَ فَيَغْفِرُ اللهُ لِي وَيَرْزُقُنِي.',
      prompt:'A child with a clean glowing heart under gentle rain of light, forgiven and blessed, tender' },
  ],
  moral:'الِاسْتِغْفَارُ يَغْسِلُ خَطَايَايَ وَيَجْلِبُ الْخَيْرَ وَالرِّزْق. 💚',
  game:{ type:'find', title:'اغْسِلْ قَلْبَكَ بِالِاسْتِغْفَار! اجْمَعْ قَطَرَاتِ الْمَغْفِرَةِ الْخَمْس', target:'🌧️', count:5, distractors:['🖤','☁️'], size:12 },
  act:{ q:'مَاذَا نَقُولُ إِذَا أَخْطَأْنَا؟', yay:'أَحْسَنْت! فَتُغْسَلُ خَطَايَانَا', opts:[
    { e:'🌧️', t:'أَسْتَغْفِرُ اللهَ وَأَتُوبُ إِلَيْه', ok:true },
    { e:'😤', t:'نُخْفِي الْخَطَأ' },
    { e:'🤷', t:'لَا شَيْء' } ] },
  dua:'أَسْتَغْفِرُ اللهَ وَأَتُوبُ إِلَيْه' },

{ id:'salawat', icon:'💝', color:'#E84393', title:'هَدِيَّةٌ لِلْحَبِيب',
  tag:'الصَّلَاةُ عَلَى النَّبِيِّ ﷺ',
  pages:[
    { emoji:'💝', text:'أَجْمَلُ هَدِيَّةٍ نُقَدِّمُهَا لِنَبِيِّنَا ﷺ: الصَّلَاةُ عَلَيْه — اللَّهُمَّ صَلِّ عَلَى مُحَمَّد.',
      prompt:'A glowing gift of light rising toward a warm radiant glow in the sky, gift to the Prophet, tender' },
    { emoji:'🔟', text:'مَنْ صَلَّى عَلَى النَّبِيِّ ﷺ مَرَّةً وَاحِدَة، صَلَّى اللهُ عَلَيْهِ عَشْرًا!',
      prompt:'One glowing heart multiplying into ten shining stars, tenfold reward, warm radiant' },
    { emoji:'🤲', text:'وَهِيَ سَبَبٌ لِإِجَابَةِ الدُّعَاءِ وَنَيْلِ شَفَاعَتِهِ ﷺ يَوْمَ الْقِيَامَة.',
      prompt:'Hands raised in dua wrapped in warm light, salawat opening blessings, serene' },
    { emoji:'💚', text:'فَأُكْثِرُ الصَّلَاةَ عَلَيْهِ حُبًّا لَه، خَاصَّةً يَوْمَ الْجُمُعَة.',
      prompt:'A child with a loving glowing heart sending blessings, love of the Prophet, warm tender' },
  ],
  moral:'الصَّلَاةُ عَلَى النَّبِيِّ ﷺ هَدِيَّةٌ يُضَاعِفُهَا اللهُ عَشْرًا. 💚',
  game:{ type:'find', title:'صَلِّ عَلَى النَّبِيِّ ﷺ! اجْمَعِ الْقُلُوبَ الْمُحِبَّةَ الْخَمْس', target:'💝', count:5, distractors:['☁️','⭐'], size:12 },
  act:{ q:'مَنْ صَلَّى عَلَى النَّبِيِّ ﷺ مَرَّة، كَمْ يُصَلِّي اللهُ عَلَيْه؟', yay:'أَحْسَنْت! عَشْرَ مَرَّات', opts:[
    { e:'🔟', t:'عَشْرَ مَرَّات', ok:true },
    { e:'☝️', t:'مَرَّةً وَاحِدَة' },
    { e:'🤷', t:'لَا شَيْء' } ] },
  dua:'اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّد' },

{ id:'tahlil', icon:'☝️', color:'#8E44AD', title:'أَفْضَلُ الذِّكْر',
  tag:'لَا إِلَهَ إِلَّا الله',
  pages:[
    { emoji:'☝️', text:'أَفْضَلُ الذِّكْرِ كُلِّه: لَا إِلَهَ إِلَّا الله — كَلِمَةُ التَّوْحِيدِ الْعَظِيمَة.',
      prompt:'One radiant star of light shining above all, the greatest word, gold and teal, serene' },
    { emoji:'🔑', text:'إِنَّهَا مِفْتَاحُ الْجَنَّة! مَنْ كَانَ آخِرُ كَلَامِهِ لَا إِلَهَ إِلَّا الله دَخَلَ الْجَنَّة.',
      prompt:'A glowing golden key opening a gate of paradise light, key to Paradise, warm radiant' },
    { emoji:'⚖️', text:'وَهِيَ أَثْقَلُ شَيْءٍ فِي الْمِيزَان، تَمْلَأُ مَا بَيْنَ السَّمَاءِ وَالْأَرْض!',
      prompt:'A scale tipping heavily with words of light filling the sky, heaviest in the balance, radiant' },
    { emoji:'💚', text:'فَأُكْثِرُ مِنْهَا وَأَجْعَلُهَا حَبِيبَةً إِلَى قَلْبِي وَلِسَانِي.',
      prompt:'A child with a glowing heart repeating the word of tawheed, love of dhikr, warm tender' },
  ],
  moral:'لَا إِلَهَ إِلَّا اللهُ أَفْضَلُ الذِّكْرِ وَمِفْتَاحُ الْجَنَّة. 💚',
  game:{ type:'sort', title:'أَيُّهَا كَلِمَاتُ ذِكْرٍ جَمِيلَة؟', bins:['ذِكْرٌ جَمِيل ✅','لَيْسَ ذِكْرًا 🚫'], items:[
    { e:'☝️', t:'لَا إِلَهَ إِلَّا الله', bin:0 },
    { e:'💫', t:'سُبْحَانَ الله', bin:0 },
    { e:'😠', t:'كَلَامٌ سَيِّئ', bin:1 },
    { e:'💝', t:'الصَّلَاةُ عَلَى النَّبِيّ', bin:0 } ] },
  act:{ q:'مَا أَفْضَلُ الذِّكْرِ كُلِّه؟', yay:'أَحْسَنْت! مِفْتَاحُ الْجَنَّة', opts:[
    { e:'☝️', t:'لَا إِلَهَ إِلَّا الله', ok:true },
    { e:'😴', t:'لَا شَيْء' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'لَا إِلَهَ إِلَّا اللهُ وَحْدَهُ لَا شَرِيكَ لَه' },

{ id:'sneeze', icon:'🤧', color:'#27AE60', title:'أَذْكَارُ كُلِّ يَوْم',
  tag:'ذِكْرٌ فِي كُلِّ حَال',
  pages:[
    { emoji:'🍽️', text:'قَبْلَ الْأَكْلِ أَقُول: بِسْمِ الله، وَبَعْدَه: الْحَمْدُ لِله. فَيُبَارَكُ لِي فِي طَعَامِي.',
      prompt:'A child saying grace before a warm meal, remembrance at eating, cozy bright kitchen' },
    { emoji:'🤧', text:'وَإِذَا عَطَسْتُ أَقُول: الْحَمْدُ لِله، فَيَرُدُّ عَلَيَّ صَاحِبِي: يَرْحَمُكَ الله.',
      prompt:'A child sneezing and a friend responding kindly, dhikr of sneezing, cheerful warm scene' },
    { emoji:'🚪', text:'وَإِذَا دَخَلْتُ بَيْتِي سَمَّيْتُ الله، وَإِذَا خَرَجْتُ قُلْت: بِسْمِ اللهِ تَوَكَّلْتُ عَلَى الله.',
      prompt:'A child at a doorway saying bismillah with a soft glow, dhikr of entering and leaving, warm' },
    { emoji:'💚', text:'فَحَيَاتِي كُلُّهَا ذِكْرٌ لِله: فِي أَكْلِي وَنَوْمِي وَلَعِبِي.',
      prompt:'A child through a happy day surrounded by gentle glowing words, life full of remembrance, warm' },
  ],
  moral:'أَذْكُرُ اللهَ فِي كُلِّ حَال: أَكْلِي وَعُطَاسِي وَدُخُولِي وَخُرُوجِي. 💚',
  game:{ type:'pairs', title:'صِلْ كُلَّ حَالٍ بِذِكْرِه', pairs:[
    ['🍽️ قَبْلَ الْأَكْل','بِسْمِ الله'],
    ['🤧 عِنْدَ الْعُطَاس','الْحَمْدُ لِله'],
    ['🚪 عِنْدَ الْخُرُوج','بِسْمِ اللهِ تَوَكَّلْتُ عَلَى الله'] ] },
  act:{ q:'مَاذَا أَقُولُ إِذَا عَطَسْت؟', yay:'أَحْسَنْت! الْحَمْدُ لِله', opts:[
    { e:'🤧', t:'الْحَمْدُ لِله', ok:true },
    { e:'😴', t:'لَا شَيْء' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'الْحَمْدُ لِلَّهِ عَلَى كُلِّ حَال' },

{ id:'protection', icon:'🌟', color:'#C0392B', title:'الْمُعَوِّذَات',
  tag:'قُلْ هُوَ اللهُ أَحَد وَالْمُعَوِّذَتَان',
  pages:[
    { emoji:'📖', text:'ثَلَاثُ سُوَرٍ قَصِيرَةٍ تَحْمِينَا: قُلْ هُوَ اللهُ أَحَد، وَقُلْ أَعُوذُ بِرَبِّ الْفَلَق، وَقُلْ أَعُوذُ بِرَبِّ النَّاس.',
      prompt:'Three glowing short surahs of light forming a protective circle, the three quls, warm serene' },
    { emoji:'🛡️', text:'مَنْ قَرَأَهَا ثَلَاثًا صَبَاحًا وَمَسَاءً كَفَتْهُ مِنْ كُلِّ شَيْء بِإِذْنِ الله.',
      prompt:'A gentle protective dome of light around a child from these surahs, complete protection, warm' },
    { emoji:'🛏️', text:'وَكَانَ النَّبِيُّ ﷺ يَقْرَؤُهَا وَيَمْسَحُ بِهِمَا جَسَدَهُ قَبْلَ النَّوْم.',
      prompt:'A child reciting and gently wiping over themselves before bed with soft light, sunnah, cozy warm' },
    { emoji:'💚', text:'فَأَحْفَظُهَا وَأَقْرَؤُهَا فَأَكُونُ مَحْرُوسًا بِكَلَامِ الله.',
      prompt:'A peacefully sleeping child wrapped in soft protective light of Quran, guarded, tender warm' },
  ],
  moral:'الْمُعَوِّذَاتُ تَحْمِينِي مِنْ كُلِّ شَرٍّ بِإِذْنِ الله. 💚',
  game:{ type:'order', title:'رَتِّبِ السُّوَرَ الثَّلَاثَ الْحَامِيَة', items:[
    { e:'1️⃣', t:'قُلْ هُوَ اللهُ أَحَد' },
    { e:'2️⃣', t:'قُلْ أَعُوذُ بِرَبِّ الْفَلَق' },
    { e:'3️⃣', t:'قُلْ أَعُوذُ بِرَبِّ النَّاس' },
    { e:'🛡️', t:'ثَلَاثًا صَبَاحًا وَمَسَاء' } ] },
  act:{ q:'كَمْ مَرَّةً نَقْرَأُ الْمُعَوِّذَاتِ صَبَاحًا وَمَسَاء؟', yay:'أَحْسَنْت! ثَلَاثًا فَتَكْفِينَا مِنْ كُلِّ شَيْء', opts:[
    { e:'3️⃣', t:'ثَلَاثَ مَرَّات', ok:true },
    { e:'🔟', t:'عَشْرَ مَرَّات' },
    { e:'🤷', t:'لَا نَقْرَؤُهَا' } ] },
  dua:'قُلْ هُوَ اللهُ أَحَد، اللهُ الصَّمَد' },

{ id:'heart', icon:'💚', color:'#1E8449', title:'قَلْبٌ عَامِرٌ بِالله',
  tag:'ثَمَرَةُ الذِّكْر',
  pages:[
    { emoji:'💚', text:'مَنْ يَذْكُرُ اللهَ دَائِمًا يَصِيرُ قَلْبُهُ حَيًّا مُطْمَئِنًّا، وَمَنْ يَنْسَاهُ يَصِيرُ قَلْبُهُ قَاسِيًا حَزِينًا.',
      prompt:'A glowing warm heart full of light beside a comparison of a dim one, living heart, gentle' },
    { emoji:'🌿', text:'قَالَ النَّبِيُّ ﷺ: مَثَلُ الَّذِي يَذْكُرُ رَبَّهُ وَاَلَّذِي لَا يَذْكُرُهُ كَمَثَلِ الْحَيِّ وَالْمَيِّت.',
      prompt:'A green living plant beside a dry one, remembrance as life, gentle warm illustration' },
    { emoji:'🕊️', text:'الذِّكْرُ يَطْرُدُ الشَّيْطَانَ وَالْحُزْنَ وَالْقَلَق، وَيَمْلَأُ الْقَلْبَ نُورًا وَسَكِينَة.',
      prompt:'A dove of peace and warm light filling a heart, dhikr driving away sadness, serene' },
    { emoji:'🌟', text:'فَأَجْعَلُ لِسَانِي رَطْبًا بِذِكْرِ الله، فَيَحْيَا قَلْبِي وَأَسْعَد.',
      prompt:'A joyful child with a bright full heart of light under warm sky, heart alive with remembrance' },
  ],
  moral:'ذِكْرُ اللهِ يُحْيِي قَلْبِي وَيَمْلَؤُهُ نُورًا وَسَعَادَة. 🌟',
  game:{ type:'sort', title:'مَاذَا يَفْعَلُ الذِّكْرُ بِالْقَلْب؟', bins:['يُحْيِي الْقَلْب 💚','خِلَافُ الذِّكْر 🚫'], items:[
    { e:'🕊️', t:'يَجْلِبُ السَّكِينَة', bin:0 },
    { e:'🌿', t:'يُحْيِي الْقَلْب', bin:0 },
    { e:'😰', t:'الْغَفْلَةُ تُقْسِي الْقَلْب', bin:1 },
    { e:'🌟', t:'يَمْلَؤُهُ نُورًا', bin:0 } ] },
  act:{ q:'مَا مَثَلُ الَّذِي يَذْكُرُ اللهَ وَالَّذِي لَا يَذْكُرُه؟', yay:'أَحْسَنْت! كَمَثَلِ الْحَيِّ وَالْمَيِّت', opts:[
    { e:'💚', t:'كَالْحَيِّ وَالْمَيِّت', ok:true },
    { e:'🤷', t:'لَا فَرْق' },
    { e:'😴', t:'لَا أَعْرِف' } ] },
  dua:'يَا مُقَلِّبَ الْقُلُوبِ اجْعَلْ قَلْبِي عَامِرًا بِذِكْرِك' },

]};
