/* corners/stories/ibada-little/zakah.js — كنز يكبر (الزكاة والصدقة) للصغار (٣–٦) · ٨ حكايات */
window.IBADA_LITTLE = window.IBADA_LITTLE || {};
window.IBADA_LITTLE.zakah = {
  id:'zakah', icon:'🎁', color:'#27AE60', title:'كَنْزٌ يَكْبُر', tag:'الْعَطَاءُ وَالصَّدَقَة',
  stories:[

{ id:'grows', icon:'🌱', color:'#27AE60', title:'الْكَنْزُ الَّذِي يَكْبُر',
  tag:'كُلَّمَا أَعْطَيْتَ زَاد',
  pages:[
    { emoji:'🎁', text:'الصَّدَقَةُ عَجِيبَة: كُلَّمَا أَعْطَيْتَ مِنْ مَالِكَ لَا يَنْقُص، بَلْ يُبَارِكُ اللهُ فِيهِ وَيَزِيد!',
      prompt:'A coin being given that sparkles and multiplies with light, charity growing, warm bright' },
    { emoji:'🌱', text:'مِثْلُ الْبِذْرَةِ الْوَاحِدَةِ تَصِيرُ سُنْبُلَةً فِيهَا مِئَةُ حَبَّة! اللهُ يُضَاعِفُ الصَّدَقَة.',
      prompt:'A single seed growing into a wheat stalk of a hundred grains, multiplied charity, warm' },
    { emoji:'🤝', text:'قَالَ النَّبِيُّ ﷺ: مَا نَقَصَتْ صَدَقَةٌ مِنْ مَال — بَلْ تَزِيدُهُ بَرَكَةً وَخَيْرًا.',
      prompt:'A hand giving a coin to another with a soft glow between them, generosity, warm tender' },
    { emoji:'💚', text:'فَأُعْطِي وَأَنَا فَرْحَانٌ، وَاثِقٌ أَنَّ اللهَ يُخْلِفُ عَلَيَّ خَيْرًا.',
      prompt:'A joyful child giving and receiving blessings shown as glowing light, cheerful giving, warm' },
  ],
  moral:'الصَّدَقَةُ لَا تُنْقِصُ الْمَال، بَلْ يُبَارِكُ اللهُ فِيهِ وَيَزِيد. 💚',
  game:{ type:'find', title:'ازْرَعْ صَدَقَتَك! اجْمَعِ السَّنَابِلَ الْخَمْسَ الَّتِي نَمَتْ', target:'🌱', count:5, distractors:['🍂','🪨'], size:12 },
  act:{ q:'هَلْ تُنْقِصُ الصَّدَقَةُ الْمَال؟', yay:'أَحْسَنْت! بَلْ يُبَارِكُ اللهُ فِيهِ وَيَزِيد', opts:[
    { e:'💚', t:'لَا! تَزِيدُهُ بَرَكَة', ok:true },
    { e:'😢', t:'نَعَم، يَنْقُصُ وَيَضِيع' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ بَارِكْ لَنَا فِيمَا رَزَقْتَنَا وَاجْعَلْنَا مِنَ الْمُنْفِقِين' },

{ id:'smile', icon:'😊', color:'#F39C12', title:'كُلُّ مَعْرُوفٍ صَدَقَة',
  tag:'الصَّدَقَةُ لَيْسَتْ مَالًا فَقَط',
  pages:[
    { emoji:'😊', text:'قَالَ النَّبِيُّ ﷺ: تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ صَدَقَة! فَحَتَّى الِابْتِسَامَةُ لَهَا أَجْر.',
      prompt:'A child smiling warmly at a friend with a soft glow, a smile as charity, cheerful warm' },
    { emoji:'🤝', text:'وَمُسَاعَدَتُكَ لِأَحَدٍ صَدَقَة، وَكَلِمَتُكَ الطَّيِّبَةُ صَدَقَة، وَإِمَاطَةُ الْأَذَى عَنِ الطَّرِيقِ صَدَقَة.',
      prompt:'A child helping carry something and removing a stone from a path, small good deeds, warm bright' },
    { emoji:'💧', text:'حَتَّى أَنْ تَسْقِيَ قِطَّةً أَوْ عُصْفُورًا صَدَقَة! فِي كُلِّ كَبِدٍ رَطْبَةٍ أَجْر.',
      prompt:'A child giving water to a thirsty kitten and bird, kindness to animals, tender warm scene' },
    { emoji:'💚', text:'فَأَسْتَطِيعُ أَنْ أَتَصَدَّقَ كُلَّ يَوْمٍ وَلَوْ لَمْ يَكُنْ مَعِي مَال!',
      prompt:'A happy child doing many small kind acts through a day, everyday charity, warm uplifting' },
  ],
  moral:'كُلُّ مَعْرُوفٍ صَدَقَة: ابْتِسَامَتِي، وَمُسَاعَدَتِي، وَكَلِمَتِي الطَّيِّبَة. 💚',
  game:{ type:'sort', title:'أَيُّهَا صَدَقَة؟', bins:['صَدَقَة ✅','لَيْسَ صَدَقَة 🚫'], items:[
    { e:'😊', t:'ابْتِسَامَةٌ لِأَخِي', bin:0 },
    { e:'🤝', t:'مُسَاعَدَةُ مُحْتَاج', bin:0 },
    { e:'😠', t:'كَلِمَةٌ سَيِّئَة', bin:1 },
    { e:'💧', t:'سَقْيُ قِطَّةٍ عَطْشَى', bin:0 } ] },
  act:{ q:'هَلِ الِابْتِسَامَةُ صَدَقَة؟', yay:'أَحْسَنْت! كُلُّ مَعْرُوفٍ صَدَقَة', opts:[
    { e:'😊', t:'نَعَم! تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ صَدَقَة', ok:true },
    { e:'💰', t:'لَا، الصَّدَقَةُ مَالٌ فَقَط' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ اجْعَلْنِي مِفْتَاحًا لِلْخَيْر' },

{ id:'secret', icon:'🤫', color:'#5B4B8A', title:'الْعَطَاءُ فِي السِّرّ',
  tag:'يَدٌ لَا تَعْلَمُ الْأُخْرَى',
  pages:[
    { emoji:'🤫', text:'أَجْمَلُ الصَّدَقَةِ مَا كَانَتْ فِي السِّرّ، لَا يَرَاهَا أَحَدٌ إِلَّا الله.',
      prompt:'A child quietly slipping a coin into a charity box unseen, secret giving, warm gentle' },
    { emoji:'🌑', text:'قَالَ النَّبِيُّ ﷺ عَنِ السَّبْعَة: وَرَجُلٌ تَصَدَّقَ بِصَدَقَةٍ فَأَخْفَاهَا حَتَّى لَا تَعْلَمَ شِمَالُهُ مَا أَنْفَقَتْ يَمِينُه.',
      prompt:'One hand giving while the other is unaware, hidden charity, symbolic warm gentle scene' },
    { emoji:'⛅', text:'وَهُوَ مِنَ السَّبْعَةِ الَّذِينَ يُظِلُّهُمُ اللهُ يَوْمَ الْقِيَامَة!',
      prompt:'A cool patch of shade with warm light in a bright landscape, reward of secret charity, serene' },
    { emoji:'💚', text:'فَأُعْطِي فِي السِّرِّ بِلَا رِيَاءٍ، لِأَنَّ اللهَ يَرَانِي وَهَذَا يَكْفِينِي.',
      prompt:'A child giving quietly with a warm glow of sincerity, giving for Allah alone, tender' },
  ],
  moral:'أَجْمَلُ الصَّدَقَةِ مَا كَانَتْ فِي السِّرِّ لِلهِ وَحْدَه. 💚',
  game:{ type:'sort', title:'أَيُّ صَدَقَةٍ أَجْمَل؟', bins:['فِي السِّرِّ لِله 💚','لِلرِّيَاءِ أَمَامَ النَّاس 🚫'], items:[
    { e:'🤫', t:'أُعْطِي بِلَا أَنْ يَرَانِي أَحَد', bin:0 },
    { e:'📢', t:'أُعْطِي لِيَمْدَحَنِي النَّاس', bin:1 },
    { e:'💚', t:'أُخْفِي صَدَقَتِي لِله', bin:0 },
    { e:'🤳', t:'أُصَوِّرُهَا لِأَتَفَاخَر', bin:1 } ] },
  act:{ q:'مَا أَجْمَلُ أَنْوَاعِ الصَّدَقَة؟', yay:'أَحْسَنْت! فِي السِّرِّ لِله', opts:[
    { e:'🤫', t:'الصَّدَقَةُ فِي السِّرّ', ok:true },
    { e:'📢', t:'أَمَامَ النَّاسِ لِلْمَدْح' },
    { e:'🤷', t:'لَا فَرْق' } ] },
  dua:'اللَّهُمَّ اجْعَلْ عَمَلِي خَالِصًا لِوَجْهِك' },

{ id:'zakahfard', icon:'💰', color:'#16A085', title:'الزَّكَاةُ رُكْنٌ عَظِيم',
  tag:'حَقُّ الْفُقَرَاءِ فِي الْمَال',
  pages:[
    { emoji:'🕌', text:'الزَّكَاةُ رُكْنٌ مِنْ أَرْكَانِ الْإِسْلَامِ الْخَمْسَة، وَهِيَ فَرْضٌ عَلَى مَنْ عِنْدَهُ مَالٌ كَثِير.',
      prompt:'Five glowing pillars of light with one highlighted for zakah, pillar of Islam, warm serene' },
    { emoji:'🤲', text:'يُعْطِي الْغَنِيُّ جُزْءًا صَغِيرًا مِنْ مَالِهِ لِلْفُقَرَاءِ وَالْمُحْتَاجِين، فَهُوَ حَقٌّ لَهُم.',
      prompt:'A wealthy hand sharing coins with those in need, wealth shared, warm compassionate scene' },
    { emoji:'🧼', text:'الزَّكَاةُ تُطَهِّرُ الْمَالَ وَتُنَظِّفُ الْقَلْبَ مِنَ الْبُخْلِ وَحُبِّ الدُّنْيَا.',
      prompt:'Coins glowing pure and a clean heart of light, zakah purifying wealth and heart, warm' },
    { emoji:'💚', text:'فَالْمَالُ لِلهِ، وَنَحْنُ نُعْطِي مِنْهُ مَنْ أَمَرَنَا اللهُ أَنْ نُعْطِيَه.',
      prompt:'A community sharing joyfully, rich and poor together, zakah building care, warm uplifting' },
  ],
  moral:'الزَّكَاةُ رُكْنٌ يُطَهِّرُ الْمَالَ وَيُعْطِي الْفُقَرَاءَ حَقَّهُم. 💚',
  game:{ type:'pairs', title:'صِلْ كُلَّ شَيْءٍ بِمَعْنَاه', pairs:[
    ['🕌 الزَّكَاة','رُكْنٌ مِنْ أَرْكَانِ الْإِسْلَام'],
    ['🤲 حَقُّ الْفُقَرَاء','فِي مَالِ الْأَغْنِيَاء'],
    ['🧼 الزَّكَاة','تُطَهِّرُ الْمَالَ وَالْقَلْب'] ] },
  act:{ q:'مَاذَا تَفْعَلُ الزَّكَاةُ بِالْمَالِ وَالْقَلْب؟', yay:'أَحْسَنْت! تُطَهِّرُهُمَا مِنَ الْبُخْل', opts:[
    { e:'🧼', t:'تُطَهِّرُ الْمَالَ وَالْقَلْب', ok:true },
    { e:'💔', t:'تُنْقِصُ الْمَالَ وَتُحْزِن' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ طَهِّرْ قَلْبِي مِنَ الْبُخْل' },

{ id:'sharing', icon:'🍎', color:'#E67E22', title:'أُحِبُّ الْمُشَارَكَة',
  tag:'الْإِيثَارُ وَحُبُّ الْخَيْرِ لِلْغَيْر',
  pages:[
    { emoji:'🍎', text:'حِينَ أُشَارِكُ صَدِيقِي طَعَامِي أَوْ لُعْبَتِي، أَفْرَحُ وَيَفْرَح، وَيُحِبُّنِي الله.',
      prompt:'Two children happily sharing an apple and a toy, joy of sharing, warm cheerful scene' },
    { emoji:'💞', text:'لَا يُؤْمِنُ أَحَدُكُم حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِه.',
      prompt:'Two children with connected hearts of light sharing kindly, loving for others, tender warm' },
    { emoji:'🎁', text:'وَأَحْيَانًا أُقَدِّمُ مَا أُحِبُّهُ لِغَيْرِي وَأُوثِرُهُ عَلَى نَفْسِي — وَهَذَا خُلُقُ الْأَبْطَال.',
      prompt:'A child giving away a favorite treat to another with a warm smile, altruism, uplifting warm' },
    { emoji:'💚', text:'فَقَلْبِي كَبِيرٌ يُحِبُّ الْعَطَاءَ وَالْمُشَارَكَة.',
      prompt:'A child with a big glowing generous heart sharing with friends, big-hearted giving, warm' },
  ],
  moral:'أُحِبُّ لِأَخِي مَا أُحِبُّ لِنَفْسِي، وَأُشَارِكُهُ بِفَرَح. 💚',
  game:{ type:'sort', title:'أَيُّهَا خُلُقُ الْعَطَاء؟', bins:['عَطَاءٌ جَمِيل 💚','أَنَانِيَّة 🚫'], items:[
    { e:'🍎', t:'أُشَارِكُ طَعَامِي', bin:0 },
    { e:'🙅', t:'أَمْنَعُ عَنِ الْجَمِيع', bin:1 },
    { e:'🎁', t:'أُوثِرُ غَيْرِي عَلَى نَفْسِي', bin:0 },
    { e:'😤', t:'كُلُّ شَيْءٍ لِي وَحْدِي', bin:1 } ] },
  act:{ q:'مَتَى يَكْمُلُ إِيمَانُ الْمُسْلِم؟', yay:'أَحْسَنْت! حِينَ يُحِبُّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِه', opts:[
    { e:'💞', t:'حِينَ يُحِبُّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِه', ok:true },
    { e:'😤', t:'حِينَ يَأْخُذُ كُلَّ شَيْء' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ اجْعَلْنِي مِنَ الْمُؤْثِرِينَ الْمُحِبِّينَ لِلْخَيْر' },

{ id:'sadaqajaria', icon:'🌳', color:'#27AE60', title:'الصَّدَقَةُ الَّتِي لَا تَنْقَطِع',
  tag:'خَيْرٌ يَبْقَى بَعْدَنَا',
  pages:[
    { emoji:'🌳', text:'بَعْضُ الصَّدَقَاتِ يَبْقَى أَجْرُهَا حَتَّى بَعْدَ أَنْ نَكْبَر: مَنْ غَرَسَ شَجَرَةً فَأَكَلَ مِنْهَا طَيْرٌ أَوْ إِنْسَانٌ فَلَهُ أَجْر!',
      prompt:'A large fruit tree with birds and people benefiting, ongoing charity, warm generous scene' },
    { emoji:'💧', text:'وَمَنْ حَفَرَ بِئْرًا يَشْرَبُ مِنْهُ النَّاس، أَوْ عَلَّمَ غَيْرَهُ خَيْرًا، بَقِيَ أَجْرُهُ يَجْرِي.',
      prompt:'A water well with people drinking and a child teaching another, lasting good deeds, warm' },
    { emoji:'📖', text:'قَالَ النَّبِيُّ ﷺ: إِذَا مَاتَ الْإِنْسَانُ انْقَطَعَ عَمَلُهُ إِلَّا مِنْ ثَلَاث… مِنْهَا صَدَقَةٌ جَارِيَة.',
      prompt:'A glowing chain of good continuing over time, ongoing reward, warm hopeful illustration' },
    { emoji:'💚', text:'فَأَزْرَعُ خَيْرًا يَبْقَى، وَأُعَلِّمُ صَدِيقِي دُعَاءً أَوْ آيَة.',
      prompt:'A child planting a tree and teaching a friend, sowing lasting good, warm uplifting' },
  ],
  moral:'أَزْرَعُ خَيْرًا يَبْقَى أَجْرُهُ يَجْرِي حَتَّى بَعْدَ مَا أَكْبَر. 💚',
  game:{ type:'find', title:'ازْرَعْ صَدَقَةً جَارِيَة! اجْمَعِ الْأَشْجَارَ الْخَمْسَ الْمُثْمِرَة', target:'🌳', count:5, distractors:['🍂','🪨'], size:12 },
  act:{ q:'مَا الصَّدَقَةُ الَّتِي يَبْقَى أَجْرُهَا؟', yay:'أَحْسَنْت! كَغَرْسِ شَجَرَةٍ يَنْتَفِعُ بِهَا النَّاس', opts:[
    { e:'🌳', t:'الصَّدَقَةُ الْجَارِيَةُ كَغَرْسِ شَجَرَة', ok:true },
    { e:'🍬', t:'أَكْلُ الْحَلْوَى' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ اجْعَلْ لِي صَدَقَةً جَارِيَةً تَنْفَعُ النَّاس' },

{ id:'joy', icon:'😃', color:'#E84393', title:'فَرْحَةُ الْمُعْطِي',
  tag:'الْيَدُ الْعُلْيَا خَيْرٌ مِنَ السُّفْلَى',
  pages:[
    { emoji:'😃', text:'الَّذِي يُعْطِي أَسْعَدُ مِنَ الَّذِي يَأْخُذ! قَالَ النَّبِيُّ ﷺ: الْيَدُ الْعُلْيَا خَيْرٌ مِنَ الْيَدِ السُّفْلَى.',
      prompt:'A joyful child giving a gift, happier than receiving, upper giving hand, warm bright' },
    { emoji:'😊', text:'حِينَ تُدْخِلُ الْفَرَحَ عَلَى قَلْبِ مُحْتَاج، تَشْعُرُ بِسَعَادَةٍ عَجِيبَةٍ فِي قَلْبِك.',
      prompt:'A child seeing a needy person smile after receiving help, joy of giving, warm tender' },
    { emoji:'💝', text:'أَحَبُّ النَّاسِ إِلَى اللهِ أَنْفَعُهُم لِلنَّاس، وَأَحَبُّ الْأَعْمَالِ إِدْخَالُ السُّرُورِ عَلَى مُسْلِم.',
      prompt:'A child spreading joy to others with warm glowing hearts around, beloved deeds, uplifting' },
    { emoji:'💚', text:'فَأُحِبُّ أَنْ أَكُونَ مُعْطِيًا نَافِعًا سَعِيدًا.',
      prompt:'A happy giving child radiating warm light surrounded by grateful friends, joy of generosity' },
  ],
  moral:'الْمُعْطِي أَسْعَدُ مِنَ الْآخِذ، وَإِدْخَالُ الْفَرَحِ عَلَى غَيْرِي عِبَادَة. 💚',
  game:{ type:'sort', title:'أَيُّ يَدٍ خَيْر؟', bins:['الْيَدُ الْعُلْيَا (تُعْطِي) 💚','الْيَدُ السُّفْلَى (تَأْخُذ) 🤲'], items:[
    { e:'🎁', t:'أُعْطِي مُحْتَاجًا', bin:0 },
    { e:'😊', t:'أُدْخِلُ الْفَرَحَ عَلَى غَيْرِي', bin:0 },
    { e:'🙏', t:'أَطْلُبُ مِنَ النَّاسِ دَائِمًا', bin:1 },
    { e:'💝', t:'أَنْفَعُ النَّاسَ بِمَا عِنْدِي', bin:0 } ] },
  act:{ q:'مَنْ أَسْعَد: الْمُعْطِي أَمِ الْآخِذ؟', yay:'أَحْسَنْت! الْيَدُ الْعُلْيَا خَيْرٌ مِنَ السُّفْلَى', opts:[
    { e:'😃', t:'الْمُعْطِي أَسْعَد', ok:true },
    { e:'😞', t:'الْآخِذُ أَسْعَد' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ اجْعَلْنِي مِنَ الْمُعْطِينَ النَّافِعِين' },

{ id:'gratitude', icon:'🙏', color:'#C0392B', title:'أَشْكُرُ نِعْمَةَ الْمَال',
  tag:'الشُّكْرُ بِالْعَطَاء',
  pages:[
    { emoji:'🎁', text:'كُلُّ مَا عِنْدِي مِنْ مَالٍ وَطَعَامٍ وَلُعَبٍ نِعْمَةٌ مِنَ الله، فَأَشْكُرُهُ عَلَيْهَا.',
      prompt:'A grateful child looking at their blessings with a thankful heart, gratitude, warm cozy' },
    { emoji:'🤲', text:'وَمِنْ شُكْرِ النِّعْمَةِ أَنْ أُعْطِيَ مِنْهَا لِمَنْ لَا يَجِد.',
      prompt:'A child sharing part of their blessings with someone in need, gratitude in action, warm' },
    { emoji:'📈', text:'قَالَ الله: لَئِنْ شَكَرْتُمْ لَأَزِيدَنَّكُم! فَالشُّكْرُ يَزِيدُ النِّعْمَة.',
      prompt:'Blessings multiplying with light as thanks is given, gratitude increasing gifts, warm radiant' },
    { emoji:'💚', text:'فَأَشْكُرُ اللهَ بِلِسَانِي، وَأَشْكُرُهُ بِعَطَائِي لِلْمُحْتَاجِين.',
      prompt:'A joyful thankful child giving and praising with a full warm heart, complete gratitude, uplifting' },
  ],
  moral:'أَشْكُرُ نِعَمَ اللهِ بِلِسَانِي وَبِعَطَائِي، فَتَزِيدَ الْبَرَكَة. 💚',
  game:{ type:'pairs', title:'صِلْ كُلَّ نِعْمَةٍ بِشُكْرِهَا', pairs:[
    ['💰 الْمَال','أُعْطِي مِنْهُ الْمُحْتَاج'],
    ['🍎 الطَّعَام','أُشَارِكُهُ وَأَحْمَدُ الله'],
    ['❤️ الصِّحَّة','أَسْتَعْمِلُهَا فِي الْخَيْر'] ] },
  act:{ q:'كَيْفَ أَشْكُرُ اللهَ عَلَى الْمَال؟', yay:'أَحْسَنْت! فَيَزِيدُنِي اللهُ مِنْ فَضْلِه', opts:[
    { e:'🤲', t:'أَحْمَدُهُ وَأُعْطِي مِنْهُ الْمُحْتَاجِين', ok:true },
    { e:'😤', t:'أَحْتَفِظُ بِهِ وَحْدِي بُخْلًا' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'لَئِنْ شَكَرْتُمْ لَأَزِيدَنَّكُم، اللَّهُمَّ أَعِنِّي عَلَى شُكْرِك' },

]};
