/* parents-videos.js — curated YouTube channels / series / podcasts for parents.
   Names provided by the site owner. Each opens a YouTube search for the exact
   name (reliable routing). Owner can later replace `q` with an exact channel
   or playlist URL via `url:` to enable in-page embedding. */
window.PARENTS_VIDEOS = {
  cats: [
    { id:'kids', icon:'🧒', ar:'سلاسل وقصص للأطفال', en:'Kids series & stories', items:[
      { ar:'حلقات الحبيب وقصص الأنبياء — نبيل العوضي', en:'Al-Habib & Prophets’ Stories — Nabil al-Awadi' },
      { ar:'قائد لم يُهزَم (سيرتون كيدز) — خالد بن الوليد', en:'The Undefeated Commander — Khalid ibn al-Walid (SeerahToon Kids)' },
      { ar:'سلسلة أبطال الإسلام', en:'Heroes of Islam series', url:'https://youtube.com/playlist?list=PLO7nbsS9Q8mHv9ZTq3xWn63Q2u3yowiLl' },
      { ar:'قناة One Way Production', en:'One Way Production', url:'https://youtube.com/@onewayproduction' },
      { ar:'قناة روائع إسلامية', en:'Rawae‘ Islamiyya', url:'https://youtube.com/@rawayieaslamia' },
      { ar:'قناة أمة تون', en:'Ummah Toon', url:'https://youtube.com/@ummahtoon' },
      { ar:'تعلّم مع زكريا', en:'Learn with Zakariya', url:'https://youtube.com/@learnwithzakaria' },
      { ar:'سراج للأطفال', en:'Siraj for Kids', url:'https://youtube.com/@sirajshowofficial' },
      { ar:'قناة مبدعون', en:'Mubdi‘oon', url:'https://youtube.com/@mobdeoon' },
      { ar:'قناة داود', en:'Dawood Kids TV', url:'https://youtube.com/@dawoodkidstv' },
      { ar:'سلسلة علماء المسلمين (١)', en:'Muslim Scientists series (1)', url:'https://youtube.com/playlist?list=PLsDEtQxRG8bE-JKKPx0vCAAK0R511rrT8' },
      { ar:'سلسلة علماء المسلمين (٢)', en:'Muslim Scientists series (2)', url:'https://youtube.com/playlist?list=PLmrET10kAE94VLoOE3p5g1qx3gLKIEhwU' },
    ]},
    { id:'scholars', icon:'🎓', ar:'علماء ودعاة', en:'Scholars & preachers', items:[
      { ar:'رحلة اليقين — د. إياد قنيبي', en:'Journey of Certainty — Dr. Iyad Qunaibi', url:'https://youtube.com/@eyadqunaibi' },
      { ar:'العلماء المسلمون — الجزيرة / قناة العلم نور', en:'Muslim Scientists — Al Jazeera / Al-‘Ilm Noor' },
      { ar:'قناة أمجد سمير', en:'Amjad Sameer', url:'https://youtube.com/@amgad_samir' },
      { ar:'قناة أحمد السيد', en:'Ahmad al-Sayed', url:'https://youtube.com/@alsayyed_ah' },
      { ar:'قناة أحمد العربي', en:'Ahmad al-Arabi', url:'https://youtube.com/@drahmedelarabyofficial' },
      { ar:'قناة أحمد عبد المنعم', en:'Ahmad Abdel-Mon‘em' },
      { ar:'قناة د. راغب السرجاني', en:'Dr. Ragheb al-Sergany', url:'https://youtube.com/@raghebelsergany' },
      { ar:'قناة علاء حامد', en:'Alaa Hamid', url:'https://youtube.com/@3laahamed' },
      { ar:'قناة الشيخ الحويني', en:'Sheikh al-Huwaini', url:'https://youtube.com/@alhuwayni' },
      { ar:'قناة الشيخ سمير مصطفى', en:'Sheikh Samir Mostafa', url:'https://youtube.com/@samirmoustafa' },
      { ar:'قناة د. نايف بن نهار', en:'Dr. Naif bin Nahar', url:'https://youtube.com/playlist?list=PLO7nbsS9Q8mHv9ZTq3xWn63Q2u3yowiLl' },
      { ar:'فقه النفس — عبد الرحمن ذاكر الهاشمي', en:'Fiqh al-Nafs — Abdulrahman Thakir al-Hashimi' },
      { ar:'فيديوهات دريد إبراهيم الموصلي', en:'Duraid Ibrahim al-Mawsili', url:'https://youtube.com/@duraidebraheemalmuselli' },
      { ar:'قناة بيسان الباز', en:'Bissan El-Baz', url:'https://youtube.com/@bissanelbaz' },
      { ar:'إنه القرآن', en:'It’s the Quran', url:'https://youtube.com/@itsthequranofficial' },
      { ar:'قناة د. خالد الجابر', en:'Dr. Khalid al-Jaber', url:'https://youtube.com/@drkhalidaljaber' },
      { ar:'قناة فهد الكندري', en:'Fahad al-Kandari', url:'https://youtube.com/channel/UCTRGcT1KQVoQA1vdNLlbjhw' },
      { ar:'قناة إسلام ويب', en:'IslamWeb' },
      { ar:'قناة مسجد الفرقان بمانشستر', en:'Al-Furqan Mosque, Manchester', url:'https://youtube.com/@alfurqanmcr' },
    ]},
    { id:'podcasts', icon:'🎙️', ar:'بودكاست', en:'Podcasts', items:[
      { ar:'بودكاست فاهم', en:'Fahem Podcast', url:'https://youtube.com/@fahem.podcast' },
      { ar:'بودكاست فنجان', en:'Finjan Podcast' },
      { ar:'بودكاست وعي', en:'Wa‘y Podcast', url:'https://youtube.com/@waie' },
      { ar:'بودكاست بدون ورق', en:'Bidoon Waraq Podcast', url:'https://youtube.com/@bidonwaraq' },
      { ar:'بودكاست إرساء', en:'Irsaa Podcast', url:'https://youtube.com/@ersaasite' },
      { ar:'إذاعة ثمانية', en:'Thmanyah Podcasts', url:'https://youtube.com/@thmanyahpodcasts' },
      { ar:'سما القدس', en:'Sama al-Quds', url:'https://youtube.com/@samaqudspl' },
      { ar:'حوارات د. نايف بن نهار', en:'Dr. Naif bin Nahar — talks', url:'https://youtube.com/playlist?list=PLdk8aQPGcSOwBIGH6zOwbYFvS_lY-lnh6' },
    ]},
    { id:'parenting', icon:'👨‍👩‍👧', ar:'تربية الأبناء', en:'Raising children', items:[
      { ar:'التربية — د. محمد بهجت', en:'Tarbiyah — Dr. Muhammad Bahjat' },
      { ar:'د. مطلق الجاسر في التربية', en:'Dr. Mutlaq al-Jasser on parenting' },
      { ar:'فيديوهات التربية — د. محمد الشعال', en:'Parenting videos — Dr. Muhammad al-Sha‘‘al', url:'https://youtube.com/playlist?list=PLMPqxr1nu2Zc_vfl_Kinxm2sJwUMjRucs' },
      { ar:'فيديو في التربية', en:'Parenting video', url:'https://youtu.be/Pb-1-rIvoFs' },
      { ar:'التربية — د. آلاء نصيف', en:'Parenting — Dr. Alaa Nasif', url:'https://youtu.be/vBfIhYgpk7s' },
      { ar:'قناة سولافا سليم', en:'Solafa Saleem' },
    ]},
    { id:'ibadat', icon:'🕌', ar:'تعليم العبادات', en:'Teaching acts of worship', items:[
      { ar:'تعليم الصلاة', en:'Teaching Prayer', url:'https://www.youtube.com/watch?v=QIi6YSJfPTw' },
      { ar:'تعليم الوضوء', en:'Teaching Wudu', url:'https://youtu.be/HMERx-0_Koo' },
      { ar:'مناسك الحج', en:'Hajj Rituals', url:'https://www.youtube.com/watch?v=hb2KwtxJpj8' },
    ]},
    { id:'anasheed', icon:'🎵', ar:'أناشيد ومتون وشعر', en:'Anasheed, poems & texts', items:[
      { ar:'قناة أحمد النفيس', en:'Ahmad al-Nufais', url:'https://youtube.com/@ahmad_alnufais' },
      { ar:'متن تلقين العقيدة', en:'Talqeen al-‘Aqeedah (text)', url:'https://youtu.be/I9jRSojUD3U' },
      { ar:'متن تحفة الأطفال', en:'Tuhfat al-Atfal (text)', url:'https://youtu.be/BkhBBzlcbZw' },
      { ar:'متن المنيرة في مهمّ السيرة', en:'Al-Muneerah on the Seerah (text)', url:'https://youtu.be/Z4SvAOrckN8' },
      { ar:'منظومة أحسن الأخلاق', en:'Ahsan al-Akhlaq (poem)', url:'https://youtu.be/XdyoMAyYUB8' },
      { ar:'قناة ريحانة', en:'Rayhana Kids TV', url:'https://youtube.com/@rayhanakidstv' },
      { ar:'قناة صوت الجنة', en:'Paradise’s Voice', url:'https://youtube.com/@paradisesvoice' },
    ]},
  ],
  apps: [
    { ar:'مصحف التجويد', en:'Tajweed Mushaf', desc:{ar:'القرآن بألوان أحكام التجويد',en:'Qur’an with tajweed color-coding'} },
    { ar:'الحفظ الميسّر', en:'Easy Memorization', desc:{ar:'برنامج تسهيل حفظ القرآن',en:'Qur’an memorization helper'} },
    { ar:'تدارُس القرآن', en:'Tadarus al-Qur’an', desc:{ar:'متابعة الورد والمراجعة',en:'Daily recitation & review tracker'} },
    { ar:'جامع الكتب التسعة', en:'The Nine Hadith Books', desc:{ar:'موسوعة كتب الحديث التسعة',en:'The nine canonical hadith collections'} },
    { ar:'حفّاظ المتون', en:'Huffadh al-Mutoon', desc:{ar:'حفظ ومراجعة المتون العلمية',en:'Memorize & revise classic texts'} },
    { ar:'الكلم الطيّب', en:'Al-Kalim al-Tayyib', desc:{ar:'أذكار وأدعية وفوائد',en:'Adhkar, du‘as & benefits'} },
    { ar:'ملتقى الخطباء', en:'Khutaba Forum', desc:{ar:'خطب ومواد للخطباء والدعاة',en:'Sermons & resources for speakers'} },
    { ar:'نيّات', en:'Niyyat', desc:{ar:'تذكير بالنوايا والأعمال الصالحة',en:'Intentions & good-deeds reminder'} },
    { ar:'سهل', en:'Sahl', desc:{ar:'تطبيق تعليمي إسلامي ميسّر',en:'Simple Islamic learning app'} },
  ],
  sites: [
    { ar:'الدرر السنية', en:'Dorar.net', desc:{ar:'موسوعات حديثية وعقدية محقّقة',en:'Verified hadith & creed encyclopedias'}, url:'https://dorar.net/' },
    { ar:'قرآن بيديا', en:'Quranpedia', desc:{ar:'موسوعة القرآن الكريم',en:'Qur’an encyclopedia'}, url:'https://quranpedia.net/' },
    { ar:'التربية القرآنية', en:'Quranic Tarbiyah', desc:{ar:'التربية في ضوء القرآن',en:'Upbringing in light of the Qur’an'}, url:'https://quranictarbiyah.com/' },
    { ar:'قصة الإسلام', en:'IslamStory', desc:{ar:'موقع د. راغب السرجاني للتاريخ',en:'Dr. al-Sergany’s Islamic history'}, url:'https://www.islamstory.com/' },
    { ar:'طريق الإسلام', en:'IslamWay', desc:{ar:'مقالات وصوتيات ودروس',en:'Articles, audio & lessons'}, url:'https://ar.islamway.net/' },
    { ar:'إسلام ويب', en:'IslamWeb', desc:{ar:'فتاوى ومقالات وبحوث',en:'Fatwas, articles & research'}, url:'https://www.islamweb.net/ar/' },
    { ar:'موسوعة الأطفال (إسلام)', en:'Kids Islam Encyclopedia', desc:{ar:'موسوعة إسلامية للأطفال',en:'Islamic encyclopedia for kids'}, url:'https://kids.islamenc.com/ar/home' },
    { ar:'كلم طيّب', en:'Kalemtayeb', desc:{ar:'محتوى دعوي وتربوي مبسّط',en:'Simplified da‘wah & tarbiyah'}, url:'https://kalemtayeb.com/' },
    { ar:'حصن المسلم', en:'Hisn al-Muslim', desc:{ar:'أذكار وأدعية اليوم والليلة',en:'Daily adhkar & supplications'}, url:'https://hisnmuslim.com/i/ar/1' },
    { ar:'التدبّر', en:'Al-Tadabbur', desc:{ar:'تدبّر القرآن الكريم',en:'Reflecting on the Qur’an'}, url:'https://altadabbur.com/' },
  ],
};
