/* ═══════════════════════════════════════════════════════════════
   AL-ARBA'IN AN-NAWAWIYYAH — index (42 hadiths)
   Full content per hadith in hadith-data/h<NN>.js
   ─────────────────────────────────────────────────────────────── */
window.HADITH_INDEX = [
  { slug:'h01', num:1,  emoji:'🎯', titleAr:'إنما الأعمال بالنيّات', titleEn:'Deeds by Intentions', themeAr:'النيّة والإخلاص', themeEn:'Intention & sincerity' },
  { slug:'h02', num:2,  emoji:'👼', titleAr:'حديث جبريل', titleEn:'Hadith of Jibril', themeAr:'الإسلام والإيمان والإحسان', themeEn:'Islam, Iman & Ihsan' },
  { slug:'h03', num:3,  emoji:'🕌', titleAr:'أركان الإسلام', titleEn:'Pillars of Islam', themeAr:'بُني الإسلام على خمس', themeEn:'Islam built on five' },
  { slug:'h04', num:4,  emoji:'⏳', titleAr:'خلق الإنسان', titleEn:'Creation of Man', themeAr:'القَدَر وخواتيم الأعمال', themeEn:'Destiny & final deeds' },
  { slug:'h05', num:5,  emoji:'🚫', titleAr:'ردّ البدعة', titleEn:'Rejecting Innovation', themeAr:'كل محدثة بدعة', themeEn:'Following the Sunnah' },
  { slug:'h06', num:6,  emoji:'✅', titleAr:'الحلال والحرام', titleEn:'Lawful & Unlawful', themeAr:'الحلال بيّن والحرام بيّن', themeEn:'The clear & the doubtful' },
  { slug:'h07', num:7,  emoji:'💚', titleAr:'الدين النصيحة', titleEn:'Religion is Sincerity', themeAr:'النصيحة لله ولرسوله', themeEn:'Sincere goodwill' },
  { slug:'h08', num:8,  emoji:'🛡️', titleAr:'حرمة المسلم', titleEn:'Sanctity of the Muslim', themeAr:'عصمة الدم والمال', themeEn:'Protected life & wealth' },
  { slug:'h09', num:9,  emoji:'📋', titleAr:'ما استطعتم', titleEn:'As Much As You Can', themeAr:'افعلوا ما استطعتم', themeEn:'Do what you can' },
  { slug:'h10', num:10, emoji:'🍃', titleAr:'الطيّب من الكسب', titleEn:'Allah is Pure', themeAr:'الله طيّب لا يقبل إلا طيّبًا', themeEn:'Pure earnings & food' },
  { slug:'h11', num:11, emoji:'🤔', titleAr:'دع ما يَريبك', titleEn:'Leave What Doubts You', themeAr:'ترك الشبهات', themeEn:'Avoiding doubt' },
  { slug:'h12', num:12, emoji:'🎈', titleAr:'ترك ما لا يعني', titleEn:'Leave the Useless', themeAr:'حسن الإسلام', themeEn:'Excellence of Islam' },
  { slug:'h13', num:13, emoji:'🤝', titleAr:'حبّ الخير للناس', titleEn:'Love for Others', themeAr:'كمال الإيمان', themeEn:'Completeness of faith' },
  { slug:'h14', num:14, emoji:'⚖️', titleAr:'حرمة دم المسلم', titleEn:'Sanctity of Blood', themeAr:'متى يحل الدم', themeEn:'When blood is lawful' },
  { slug:'h15', num:15, emoji:'🗣️', titleAr:'قل خيرًا أو اصمت', titleEn:'Speak Good or Be Silent', themeAr:'إكرام الجار والضيف', themeEn:'Honoring neighbor & guest' },
  { slug:'h16', num:16, emoji:'😤', titleAr:'لا تغضب', titleEn:'Do Not Get Angry', themeAr:'كظم الغيظ', themeEn:'Controlling anger' },
  { slug:'h17', num:17, emoji:'✨', titleAr:'الإحسان في كل شيء', titleEn:'Excellence in All', themeAr:'إتقان العمل', themeEn:'Perfecting deeds' },
  { slug:'h18', num:18, emoji:'😊', titleAr:'اتق الله حيثما كنت', titleEn:'Fear Allah Anywhere', themeAr:'التقوى وحسن الخلق', themeEn:'Piety & good character' },
  { slug:'h19', num:19, emoji:'🤲', titleAr:'احفظ الله يحفظك', titleEn:'Guard Allah, He Guards You', themeAr:'التوكّل والمعيّة', themeEn:'Trust & reliance' },
  { slug:'h20', num:20, emoji:'🙈', titleAr:'الحياء', titleEn:'Modesty (Haya)', themeAr:'إذا لم تستحِ فاصنع', themeEn:'If you have no shame' },
  { slug:'h21', num:21, emoji:'🧭', titleAr:'قل آمنت ثم استقم', titleEn:'Believe & Be Steadfast', themeAr:'الاستقامة', themeEn:'Uprightness' },
  { slug:'h22', num:22, emoji:'🚪', titleAr:'الطريق إلى الجنة', titleEn:'The Way to Paradise', themeAr:'الفرائض تُدخل الجنة', themeEn:'Duties lead to Jannah' },
  { slug:'h23', num:23, emoji:'🌟', titleAr:'الطهور شطر الإيمان', titleEn:'Purity is Half of Faith', themeAr:'أبواب الخير', themeEn:'Doors of goodness' },
  { slug:'h24', num:24, emoji:'🙏', titleAr:'تحريم الظلم', titleEn:'Allah Forbids Oppression', themeAr:'الحديث القدسي', themeEn:'Divine hadith of mercy' },
  { slug:'h25', num:25, emoji:'💝', titleAr:'أبواب الصدقة', titleEn:'Doors of Charity', themeAr:'كل معروف صدقة', themeEn:'Every good is charity' },
  { slug:'h26', num:26, emoji:'⚖️', titleAr:'العدل صدقة', titleEn:'Justice is Charity', themeAr:'كل سُلامى صدقة', themeEn:'A charity each day' },
  { slug:'h27', num:27, emoji:'❤️', titleAr:'البِرّ حسن الخلق', titleEn:'Righteousness is Character', themeAr:'البر والإثم', themeEn:'Virtue & sin' },
  { slug:'h28', num:28, emoji:'📿', titleAr:'الوصية بالسنة', titleEn:'Hold to the Sunnah', themeAr:'السمع والطاعة', themeEn:'Following the Sunnah' },
  { slug:'h29', num:29, emoji:'🚪', titleAr:'أبواب الخير', titleEn:'Gates of Good', themeAr:'الطريق إلى الجنة', themeEn:'The path to Jannah' },
  { slug:'h30', num:30, emoji:'🛑', titleAr:'حدود الله', titleEn:'The Limits of Allah', themeAr:'الفرائض والحدود', themeEn:'Duties & limits' },
  { slug:'h31', num:31, emoji:'🌍', titleAr:'الزهد في الدنيا', titleEn:'Detachment from Dunya', themeAr:'ازهد يحبّك الله', themeEn:'Be detached, be loved' },
  { slug:'h32', num:32, emoji:'🚯', titleAr:'لا ضرر ولا ضرار', titleEn:'No Harm', themeAr:'منع الضرر', themeEn:'Causing no harm' },
  { slug:'h33', num:33, emoji:'⚖️', titleAr:'البيّنة واليمين', titleEn:'Proof & Oath', themeAr:'قواعد القضاء', themeEn:'Rules of justice' },
  { slug:'h34', num:34, emoji:'✋', titleAr:'تغيير المنكر', titleEn:'Changing Wrong', themeAr:'من رأى منكرًا', themeEn:'Forbidding evil' },
  { slug:'h35', num:35, emoji:'🤲', titleAr:'الأخوّة الإيمانية', titleEn:'Islamic Brotherhood', themeAr:'كونوا عباد الله إخوانًا', themeEn:'Be brothers' },
  { slug:'h36', num:36, emoji:'🕊️', titleAr:'تفريج الكُرَب', titleEn:'Relieving Distress', themeAr:'من فرّج عن مسلم', themeEn:'Helping others' },
  { slug:'h37', num:37, emoji:'🌈', titleAr:'الحسنات والسيّئات', titleEn:'Good & Bad Deeds', themeAr:'كرم الله في الجزاء', themeEn:'Allah\u2019s generous reward' },
  { slug:'h38', num:38, emoji:'💞', titleAr:'أولياء الله', titleEn:'The Friends of Allah', themeAr:'القرب بالنوافل', themeEn:'Nearness through worship' },
  { slug:'h39', num:39, emoji:'😌', titleAr:'رفع الحرج', titleEn:'Pardon & Ease', themeAr:'تجاوز الله عن الخطأ', themeEn:'Forgiveness of mistakes' },
  { slug:'h40', num:40, emoji:'🌿', titleAr:'كن في الدنيا غريبًا', titleEn:'Be a Stranger', themeAr:'قِصَر الأمل', themeEn:'Short hopes, good deeds' },
  { slug:'h41', num:41, emoji:'💗', titleAr:'اتّباع الهوى', titleEn:'Following Guidance', themeAr:'محبّة ما جاء به النبي ﷺ', themeEn:'Loving the message' },
  { slug:'h42', num:42, emoji:'🌊', titleAr:'سَعة مغفرة الله', titleEn:'Allah\u2019s Vast Forgiveness', themeAr:'الدعاء والرجاء', themeEn:'Hope & forgiveness' },
];
window.HADITHS = window.HADITHS || {};
