/* ═══════════════════════════════════════════════════════════════
   سُورَةُ النَّازِعَات · An-Nazi'at (79) — "والنازعات غرقا"
   Verified Uthmani text.
   ─────────────────────────────────────────────────────────────── */
window.SURAHS.naziat = {
  tagline: { ar:'البعثُ حق، وقصّةُ موسى وفرعون', en:'Resurrection is real, and the tale of Musa & Pharaoh' },

  verses: [
    { ar:'وَٱلنَّٰزِعَٰتِ غَرْقًا',
      trans:{ ar:'أُقسِمُ بالملائكةِ التي تَنزِعُ أرواحَ الكفّارِ بشدّة.', en:'By those [angels] who extract with violence.' },
      std:'By those [angels] who extract with violence,',
      words:[ { w:'ٱلنَّٰزِعَٰتِ', c:'#B5811F', m:{ ar:'الملائكةُ التي تَنزِعُ الأرواح', en:'the angels who draw out [souls]' } },
              { w:'غَرْقًا', m:{ ar:'نَزعاً شديداً من الأعماق', en:'with deep, forceful drawing' } } ] },
    { ar:'وَٱلنَّٰشِطَٰتِ نَشْطًا',
      trans:{ ar:'والملائكةِ التي تَقبِضُ أرواحَ المؤمنينَ برِفقٍ وسهولة.', en:'And [by] those who remove with ease.' },
      std:'And [by] those who remove with ease,',
      words:[ { w:'ٱلنَّٰشِطَٰتِ', c:'#1A9B7B', m:{ ar:'الملائكةُ تَقبِضُ أرواحَ المؤمنينَ برِفق', en:'angels who draw believers\u2019 souls gently' } } ] },
    { ar:'وَٱلسَّٰبِحَٰتِ سَبْحًا',
      trans:{ ar:'والملائكةِ التي تَسبَحُ في نزولِها من السماء.', en:'And [by] those who glide [as if] swimming.' },
      std:'And [by] those who glide [as if] swimming,',
      words:[ { w:'ٱلسَّٰبِحَٰتِ', c:'#1A9B7B', m:{ ar:'الملائكةُ تَسبَحُ مُسرِعةً بأمرِ الله', en:'angels gliding swiftly by Allah\u2019s command' } } ] },
    { ar:'فَٱلسَّٰبِقَٰتِ سَبْقًا',
      trans:{ ar:'فالملائكةِ التي تَسبِقُ إلى تنفيذِ أمرِ الله.', en:'And those who race each other in a race.' },
      std:'And those who race each other in a race,',
      words:[ { w:'ٱلسَّٰبِقَٰتِ', c:'#1A9B7B', m:{ ar:'تُسارِعُ إلى طاعةِ الله', en:'racing to obey Allah' } } ] },
    { ar:'فَٱلْمُدَبِّرَٰتِ أَمْرًا',
      trans:{ ar:'فالملائكةِ التي تُنفِّذُ ما أمرَها اللهُ به من تدبير.', en:'And those who arrange [each] matter.' },
      std:'And those who arrange [each] matter,',
      words:[ { w:'ٱلْمُدَبِّرَٰتِ', c:'#1A9B7B', m:{ ar:'تُنفِّذُ أوامرَ اللهِ في الكون', en:'carrying out Allah\u2019s commands in the world' } } ] },
    { ar:'يَوْمَ تَرْجُفُ ٱلرَّاجِفَةُ',
      trans:{ ar:'يومَ تَضطرِبُ الأرضُ بالنفخةِ الأولى للقيامة.', en:'On the Day the quaking blast convulses.' },
      std:'On the Day the quaking blast convulses',
      words:[ { w:'ٱلرَّاجِفَةُ', c:'#8E44AD', m:{ ar:'النفخةُ الأولى التي تُرجِفُ كلَّ شيء', en:'the first Blast that convulses everything' } } ] },
    { ar:'تَتْبَعُهَا ٱلرَّادِفَةُ',
      trans:{ ar:'تَتبَعُها النفخةُ الثانيةُ للبعث.', en:'There will follow it the subsequent [one].' },
      std:'There will follow it the subsequent [one].',
      words:[ { w:'ٱلرَّادِفَةُ', c:'#8E44AD', m:{ ar:'النفخةُ الثانيةُ التي يكونُ بها البعث', en:'the second Blast — the resurrection' } } ] },
    { ar:'قُلُوبٌ يَوْمَئِذٍ وَاجِفَةٌ',
      trans:{ ar:'قلوبٌ يومَئذٍ خائفةٌ مُضطرِبةٌ من الهَول.', en:'Hearts, that Day, will tremble.' },
      std:'Hearts, that Day, will tremble,',
      words:[ { w:'وَاجِفَةٌ', c:'#8E44AD', m:{ ar:'خائفةٌ شديدةُ الاضطراب', en:'trembling, deeply anxious' } } ] },
    { ar:'أَبْصَٰرُهَا خَٰشِعَةٌ',
      trans:{ ar:'أبصارُ أصحابِها ذليلةٌ خاضعةٌ من الخوف.', en:'Their eyes humbled.' },
      std:'Their eyes humbled.',
      words:[ { w:'خَٰشِعَةٌ', c:'#8E44AD', m:{ ar:'ذليلةٌ خاضعةٌ من شدّةِ الفزع', en:'humbled and lowered from terror' } } ] },
    { ar:'يَقُولُونَ أَءِنَّا لَمَرْدُودُونَ فِى ٱلْحَافِرَةِ',
      trans:{ ar:'يقولُ المُنكِرونَ مُستبعِدين: أنُرَدُّ أحياءً بعد الموت؟', en:'They are [presently] saying: Will we indeed be returned to [our] former state?' },
      std:'They are [presently] saying, "Will we indeed be returned to [our] former state —',
      words:[ { w:'لَمَرْدُودُونَ', c:'#8E44AD', m:{ ar:'مَردودونَ أحياءً بعد الموت', en:'returned to life after death' } },
              { w:'ٱلْحَافِرَةِ', m:{ ar:'الحالةِ الأولى (الحياة)', en:'the former state (life)' } } ] },
    { ar:'أَءِذَا كُنَّا عِظَٰمًا نَّخِرَةً',
      trans:{ ar:'أنُبعَثُ إذا صِرنا عِظاماً باليةً مُتفتِّتة؟', en:'Even if we should be decayed bones?' },
      std:'Even if we should be decayed bones?"',
      words:[ { w:'عِظَٰمًا نَّخِرَةً', c:'#8E44AD', m:{ ar:'عِظاماً باليةً مُتفتِّتة', en:'decayed, crumbling bones' } } ] },
    { ar:'قَالُوا۟ تِلْكَ إِذًا كَرَّةٌ خَاسِرَةٌ',
      trans:{ ar:'قالوا مُستهزئين: تلك رَجعةٌ فيها خسارةٌ إن صحَّت!', en:'They say: That, then, would be a losing return.' },
      std:'They say, "That, then, would be a losing return."',
      words:[ { w:'كَرَّةٌ خَاسِرَةٌ', c:'#8E44AD', m:{ ar:'رَجعةٌ خاسرةٌ (يَستبعِدونها)', en:'a losing return (which they doubt)' } } ] },
    { ar:'فَإِنَّمَا هِىَ زَجْرَةٌ وَٰحِدَةٌ',
      trans:{ ar:'فإنما البعثُ صيحةٌ واحدةٌ من إسرافيل.', en:'Indeed, it will be but one shout.' },
      std:'Indeed, it will be but one shout,',
      words:[ { w:'زَجْرَةٌ وَٰحِدَةٌ', c:'#1A9B7B', m:{ ar:'صيحةٌ واحدةٌ (النفخةُ الثانية)', en:'a single shout (the second Blast)' } } ] },
    { ar:'فَإِذَا هُم بِٱلسَّاهِرَةِ',
      trans:{ ar:'فإذا هم أحياءٌ على وجهِ الأرضِ قائمونَ للحساب.', en:'And suddenly they will be [alert] upon the earth\u2019s surface.' },
      std:'And suddenly they will be [alert] upon the earth\u2019s surface.',
      words:[ { w:'ٱلسَّاهِرَةِ', c:'#1A9B7B', m:{ ar:'وجهُ الأرضِ المُستوي للحشر', en:'the surface of the earth, for the gathering' } } ] },
    { ar:'هَلْ أَتَىٰكَ حَدِيثُ مُوسَىٰٓ',
      trans:{ ar:'هل جاءَك يا محمدُ خبرُ موسى عليه السلام مع فرعون؟', en:'Has there reached you the story of Moses?' },
      std:'Has there reached you the story of Moses? —',
      words:[ { w:'حَدِيثُ مُوسَىٰٓ', c:'#B5811F', m:{ ar:'قصّةُ موسى مع فرعونَ الطاغية', en:'the story of Musa with the tyrant Pharaoh' } } ] },
    { ar:'إِذْ نَادَىٰهُ رَبُّهُۥ بِٱلْوَادِ ٱلْمُقَدَّسِ طُوًى',
      trans:{ ar:'حين ناداهُ ربُّه في الوادي المُقدَّسِ المُسمّى «طُوى».', en:'When his Lord called to him in the sacred valley of Tuwa.' },
      std:'When his Lord called to him in the sacred valley of Tuwa,',
      words:[ { w:'ٱلْوَادِ ٱلْمُقَدَّسِ طُوًى', c:'#1A9B7B', m:{ ar:'وادٍ مُبارَكٌ كلَّمَ اللهُ فيه موسى', en:'the sacred valley where Allah spoke to Musa' } } ] },
    { ar:'ٱذْهَبْ إِلَىٰ فِرْعَوْنَ إِنَّهُۥ طَغَىٰ',
      trans:{ ar:'اذهَب إلى فرعونَ فإنه تجاوزَ الحدَّ في الظُّلمِ والكُفر.', en:'Go to Pharaoh. Indeed, he has transgressed.' },
      std:'Go to Pharaoh. Indeed, he has transgressed.',
      words:[ { w:'فِرْعَوْنَ', c:'#B5811F', m:{ ar:'الملكُ الطاغيةُ الذي ادّعى الألوهيّة', en:'Pharaoh — the tyrant who claimed divinity' } },
              { w:'طَغَىٰ', c:'#8E44AD', m:{ ar:'تجاوزَ الحدَّ وتكبَّر', en:'transgressed and grew arrogant' } } ] },
    { ar:'فَقُلْ هَل لَّكَ إِلَىٰٓ أَن تَزَكَّىٰ',
      trans:{ ar:'فقُل له برِفق: هل لك رغبةٌ في أن تتطهَّرَ من الكُفر؟', en:'And say: Would you [be willing to] purify yourself?' },
      std:'And say to him, "Would you [be willing to] purify yourself',
      words:[ { w:'أَن تَزَكَّىٰ', c:'#1A9B7B', m:{ ar:'تتطهَّرَ من الكُفرِ بالإيمان', en:'purify yourself [from disbelief] through faith' } } ] },
    { ar:'وَأَهْدِيَكَ إِلَىٰ رَبِّكَ فَتَخْشَىٰ',
      trans:{ ar:'وأُرشِدَك إلى معرفةِ ربِّك فتخافَه وتُطيعَه.', en:'And let me guide you to your Lord so you would fear [Him]?' },
      std:'And let me guide you to your Lord so you would fear [Him]?"',
      words:[ { w:'وَأَهْدِيَكَ إِلَىٰ رَبِّكَ', c:'#1A9B7B', m:{ ar:'أدُلُّك على ربِّك الحقّ', en:'guide you to your true Lord' } },
              { w:'فَتَخْشَىٰ', m:{ ar:'تخافَ اللهَ فتُطيعَه', en:'so you fear Him and obey' } } ] },
    { ar:'فَأَرَىٰهُ ٱلْءَايَةَ ٱلْكُبْرَىٰ',
      trans:{ ar:'فأرى موسى فرعونَ المعجزةَ الكبرى (العصا أو اليد).', en:'And he showed him the greatest sign.' },
      std:'And he showed him the greatest sign,',
      words:[ { w:'ٱلْءَايَةَ ٱلْكُبْرَىٰ', c:'#1A9B7B', m:{ ar:'المعجزةُ العظيمةُ (انقلابُ العصا حيّة)', en:'the greatest sign — the staff turning into a snake' } } ] },
    { ar:'فَكَذَّبَ وَعَصَىٰ',
      trans:{ ar:'فكذَّبَ فرعونُ بالمعجزةِ وعصى أمرَ الله.', en:'But Pharaoh denied and disobeyed.' },
      std:'But Pharaoh denied and disobeyed.',
      words:[ { w:'كَذَّبَ وَعَصَىٰ', c:'#8E44AD', m:{ ar:'أنكرَ الحقَّ وعصى ربَّه', en:'denied the truth and disobeyed' } } ] },
    { ar:'ثُمَّ أَدْبَرَ يَسْعَىٰ',
      trans:{ ar:'ثم أعرضَ عن الإيمانِ وسعى في الإفسادِ ومُحاربةِ الحق.', en:'Then he turned his back, striving.' },
      std:'Then he turned his back, striving,',
      words:[ { w:'أَدْبَرَ يَسْعَىٰ', c:'#8E44AD', m:{ ar:'أعرضَ وسعى في مُحاربةِ موسى', en:'turned away, striving against [the truth]' } } ] },
    { ar:'فَحَشَرَ فَنَادَىٰ',
      trans:{ ar:'فجمعَ السحرةَ والناسَ ونادى فيهم.', en:'And he gathered [his people] and called out.' },
      std:'And he gathered [his people] and called out',
      words:[ { w:'فَحَشَرَ فَنَادَىٰ', c:'#8E44AD', m:{ ar:'جمعَ جنودَه وقومَه ونادى فيهم', en:'gathered his people and proclaimed' } } ] },
    { ar:'فَقَالَ أَنَا۠ رَبُّكُمُ ٱلْأَعْلَىٰ',
      trans:{ ar:'فقال مُتكبِّراً: أنا ربُّكمُ الأعلى! (دعوى الألوهيّة).', en:'And said: I am your most exalted lord.' },
      std:'And said, "I am your most exalted lord."',
      words:[ { w:'أَنَا۠ رَبُّكُمُ ٱلْأَعْلَىٰ', c:'#8E44AD', m:{ ar:'ادّعاءُ فرعونَ الألوهيّةَ كُفراً وطُغياناً', en:'Pharaoh\u2019s claim to be a god — disbelief and tyranny' } } ] },
    { ar:'فَأَخَذَهُ ٱللَّهُ نَكَالَ ٱلْءَاخِرَةِ وَٱلْأُولَىٰ',
      trans:{ ar:'فأخذهُ اللهُ بعذابِ الآخرةِ والدنيا (الغرقِ ثم النار).', en:'So Allah seized him in exemplary punishment for the last and the first [transgression].' },
      std:'So Allah seized him in exemplary punishment for the last and the first [transgression].',
      words:[ { w:'نَكَالَ ٱلْءَاخِرَةِ وَٱلْأُولَىٰ', c:'#8E44AD', m:{ ar:'عقوبةُ الدنيا (الغرق) والآخرة (النار)', en:'punishment in this world (drowning) and the next (Fire)' } } ] },
    { ar:'إِنَّ فِى ذَٰلِكَ لَعِبْرَةً لِّمَن يَخْشَىٰٓ',
      trans:{ ar:'إنَّ في قصّةِ فرعونَ عِبرةً لمن يَخافُ اللهَ.', en:'Indeed in that is a lesson for whoever would fear [Allah].' },
      std:'Indeed in that is a warning for whoever would fear [Allah].',
      words:[ { w:'لَعِبْرَةً', c:'#1A9B7B', m:{ ar:'عِظةً وعِبرةً نتعلَّمُ منها', en:'a lesson to learn from' } },
              { w:'لِّمَن يَخْشَىٰٓ', m:{ ar:'لمن يَخافُ اللهَ ويَتّعِظ', en:'for whoever fears Allah and heeds' } } ] },
    { ar:'ءَأَنتُمْ أَشَدُّ خَلْقًا أَمِ ٱلسَّمَآءُ ۚ بَنَىٰهَا',
      trans:{ ar:'أأنتم أصعبُ خَلقاً أم السماءُ التي بناها الله؟', en:'Are you a more difficult creation or the heaven? He constructed it.' },
      std:'Are you a more difficult creation or the heaven? He constructed it.',
      words:[ { w:'أَشَدُّ خَلْقًا', c:'#8E44AD', m:{ ar:'أصعبُ في الخَلقِ (دليلٌ على البعث)', en:'harder to create (a proof of resurrection)' } },
              { w:'بَنَىٰهَا', c:'#1A9B7B', m:{ ar:'بنى اللهُ السماءَ العظيمة', en:'Allah built the mighty sky' } } ] },
    { ar:'رَفَعَ سَمْكَهَا فَسَوَّىٰهَا',
      trans:{ ar:'رفعَ ارتفاعَها وأتقنَ بناءَها بلا عيب.', en:'He raised its ceiling and proportioned it.' },
      std:'He raised its ceiling and proportioned it.',
      words:[ { w:'رَفَعَ سَمْكَهَا', c:'#1A9B7B', m:{ ar:'رفعَها عاليةً بلا أعمدة', en:'raised it high without pillars' } } ] },
    { ar:'وَأَغْطَشَ لَيْلَهَا وَأَخْرَجَ ضُحَىٰهَا',
      trans:{ ar:'وأظلمَ ليلَها وأظهرَ ضوءَ نهارِها.', en:'And He darkened its night and extracted its brightness.' },
      std:'And He darkened its night and extracted its brightness,',
      words:[ { w:'أَغْطَشَ لَيْلَهَا', c:'#8E44AD', m:{ ar:'جعلَ الليلَ مُظلِماً', en:'made its night dark' } },
              { w:'أَخْرَجَ ضُحَىٰهَا', c:'#1A9B7B', m:{ ar:'أظهرَ ضوءَ النهار', en:'brought forth its daylight' } } ] },
    { ar:'وَٱلْأَرْضَ بَعْدَ ذَٰلِكَ دَحَىٰهَا',
      trans:{ ar:'والأرضَ بعد ذلك بسطَها ومهَّدَها للعيش.', en:'And after that He spread the earth.' },
      std:'And after that He spread the earth.',
      words:[ { w:'دَحَىٰهَا', c:'#1A9B7B', m:{ ar:'بسطَها ومهَّدَها', en:'spread and prepared it' } } ] },
    { ar:'أَخْرَجَ مِنْهَا مَآءَهَا وَمَرْعَىٰهَا',
      trans:{ ar:'أخرجَ من الأرضِ ماءَها ونباتَها.', en:'He extracted from it its water and its pasture.' },
      std:'He extracted from it its water and its pasture,',
      words:[ { w:'مَآءَهَا وَمَرْعَىٰهَا', c:'#1A9B7B', m:{ ar:'الماءَ والنباتَ للحياة', en:'its water and pasture for life' } } ] },
    { ar:'وَٱلْجِبَالَ أَرْسَىٰهَا',
      trans:{ ar:'والجبالَ ثبَّتَها في الأرضِ رواسي.', en:'And the mountains He set firmly.' },
      std:'And the mountains He set firmly',
      words:[ { w:'أَرْسَىٰهَا', c:'#1A9B7B', m:{ ar:'ثبَّتَها رواسيَ تُثبِّتُ الأرض', en:'set them firm to stabilize the earth' } } ] },
    { ar:'مَتَٰعًا لَّكُمْ وَلِأَنْعَٰمِكُمْ',
      trans:{ ar:'كلُّ ذلك مَنفعةً لكم ولأنعامِكم.', en:'As provision for you and your grazing livestock.' },
      std:'As provision for you and your grazing livestock.',
      words:[ { w:'مَتَٰعًا لَّكُمْ', c:'#1A9B7B', m:{ ar:'مَنفعةً ورزقاً لكم ولحيواناتِكم', en:'provision for you and your animals' } } ] },
    { ar:'فَإِذَا جَآءَتِ ٱلطَّآمَّةُ ٱلْكُبْرَىٰ',
      trans:{ ar:'فإذا جاءتِ القيامةُ الكبرى التي تَطُمُّ كلَّ شيء.', en:'But when there comes the greatest Overwhelming Calamity.' },
      std:'But when there comes the greatest Overwhelming Calamity —',
      words:[ { w:'ٱلطَّآمَّةُ ٱلْكُبْرَىٰ', c:'#8E44AD', m:{ ar:'القيامةُ الكبرى التي تَغمُرُ كلَّ شيء', en:'the great Calamity that overwhelms all' } } ] },
    { ar:'يَوْمَ يَتَذَكَّرُ ٱلْإِنسَٰنُ مَا سَعَىٰ',
      trans:{ ar:'يومَ يتذكَّرُ الإنسانُ كلَّ ما عَمِلَ في حياتِه.', en:'The Day when man will remember that for which he strove.' },
      std:'The Day when man will remember that for which he strove,',
      words:[ { w:'مَا سَعَىٰ', c:'#8E44AD', m:{ ar:'ما عَمِلَ من خيرٍ أو شر', en:'all the good or evil he did' } } ] },
    { ar:'وَبُرِّزَتِ ٱلْجَحِيمُ لِمَن يَرَىٰ',
      trans:{ ar:'وأُظهِرَتِ النارُ لكلِّ مَن يَنظُر.', en:'And Hellfire will be exposed for [all] those who see.' },
      std:'And Hellfire will be exposed for [all] those who see —',
      words:[ { w:'بُرِّزَتِ ٱلْجَحِيمُ', c:'#8E44AD', m:{ ar:'أُظهِرَت وكُشِفَت النار', en:'Hell is brought into open view' } } ] },
    { ar:'فَأَمَّا مَن طَغَىٰ',
      trans:{ ar:'فأمّا مَن تجاوزَ الحدَّ وتكبَّرَ على الله.', en:'So as for he who transgressed.' },
      std:'So as for he who transgressed',
      words:[ { w:'طَغَىٰ', c:'#8E44AD', m:{ ar:'تجاوزَ الحدَّ في الكُفرِ والمعصية', en:'transgressed in disbelief and sin' } } ] },
    { ar:'وَءَاثَرَ ٱلْحَيَوٰةَ ٱلدُّنْيَا',
      trans:{ ar:'وفضَّلَ الحياةَ الدنيا على الآخرة.', en:'And preferred the life of this world.' },
      std:'And preferred the life of this world,',
      words:[ { w:'ءَاثَرَ ٱلْحَيَوٰةَ ٱلدُّنْيَا', c:'#8E44AD', m:{ ar:'قدَّمَ الدنيا على الآخرة', en:'preferred this world over the Hereafter' } } ] },
    { ar:'فَإِنَّ ٱلْجَحِيمَ هِىَ ٱلْمَأْوَىٰ',
      trans:{ ar:'فإنَّ النارَ هي مسكنُه ومأواه.', en:'Then indeed, Hellfire will be [his] refuge.' },
      std:'Then indeed, Hellfire will be [his] refuge.',
      words:[ { w:'ٱلْمَأْوَىٰ', c:'#8E44AD', m:{ ar:'المسكنُ والمصير', en:'the refuge and final abode' } } ] },
    { ar:'وَأَمَّا مَنْ خَافَ مَقَامَ رَبِّهِۦ وَنَهَى ٱلنَّفْسَ عَنِ ٱلْهَوَىٰ',
      trans:{ ar:'وأمّا مَن خافَ وقوفَه بين يدي ربِّه، ومنعَ نفسَه عن اتّباعِ هواها.', en:'But as for he who feared the position of his Lord and prevented the soul from [unlawful] inclination.' },
      std:'But as for he who feared the position of his Lord and prevented the soul from [unlawful] inclination,',
      words:[ { w:'خَافَ مَقَامَ رَبِّهِۦ', c:'#1A9B7B', m:{ ar:'خافَ وقوفَه للحسابِ أمام الله', en:'feared standing before his Lord for judgement' } },
              { w:'نَهَى ٱلنَّفْسَ عَنِ ٱلْهَوَىٰ', c:'#1A9B7B', m:{ ar:'منعَ نفسَه عن الشهواتِ المُحرَّمة', en:'restrained the soul from forbidden desires' } } ] },
    { ar:'فَإِنَّ ٱلْجَنَّةَ هِىَ ٱلْمَأْوَىٰ',
      trans:{ ar:'فإنَّ الجنّةَ هي مسكنُه ومأواه.', en:'Then indeed, Paradise will be [his] refuge.' },
      std:'Then indeed, Paradise will be [his] refuge.',
      words:[ { w:'ٱلْجَنَّةَ هِىَ ٱلْمَأْوَىٰ', c:'#1A9B7B', m:{ ar:'الجنّةُ مسكنُه جزاءَ خوفِه وطاعتِه', en:'Paradise is his abode, for his fear and obedience' } } ] },
    { ar:'يَسْـَٔلُونَكَ عَنِ ٱلسَّاعَةِ أَيَّانَ مُرْسَىٰهَا',
      trans:{ ar:'يَسألونَك يا محمدُ عن القيامةِ متى وقتُها؟', en:'They ask you, [O Muhammad], about the Hour: when is its arrival?' },
      std:'They ask you, [O Muhammad], about the Hour: when is its arrival?',
      words:[ { w:'ٱلسَّاعَةِ', c:'#8E44AD', m:{ ar:'القيامة', en:'the Hour — the Resurrection' } },
              { w:'أَيَّانَ مُرْسَىٰهَا', m:{ ar:'متى وقتُ وقوعِها؟', en:'when will it occur?' } } ] },
    { ar:'فِيمَ أَنتَ مِن ذِكْرَىٰهَا',
      trans:{ ar:'لستَ في شيءٍ من علمِ وقتِها، فعِلمُها عند الله.', en:'In what [position] are you that you should mention it?' },
      std:'In what [position] are you that you should mention it?',
      words:[ { w:'فِيمَ أَنتَ مِن ذِكْرَىٰهَا', c:'#8E44AD', m:{ ar:'لا عِلمَ لك بوقتِها، فلا تَنشغِل به', en:'you have no knowledge of its time' } } ] },
    { ar:'إِلَىٰ رَبِّكَ مُنتَهَىٰهَآ',
      trans:{ ar:'إلى ربِّك وحدَه عِلمُ وقتِ القيامةِ ومُنتهاها.', en:'To your Lord is its finality.' },
      std:'To your Lord is its finality.',
      words:[ { w:'إِلَىٰ رَبِّكَ مُنتَهَىٰهَآ', c:'#1A9B7B', m:{ ar:'عِلمُ وقتِها عند اللهِ وحده', en:'its knowledge rests with Allah alone' } } ] },
    { ar:'إِنَّمَآ أَنتَ مُنذِرُ مَن يَخْشَىٰهَا',
      trans:{ ar:'إنما مهمّتُك يا محمدُ إنذارُ مَن يَخافُ القيامة.', en:'You are only a warner for those who fear it.' },
      std:'You are only a warner for those who fear it.',
      words:[ { w:'مُنذِرُ', c:'#1A9B7B', m:{ ar:'مُحذِّرٌ تُبلِّغُ ولا تُجبِر', en:'a warner who conveys, not compels' } } ] },
    { ar:'كَأَنَّهُمْ يَوْمَ يَرَوْنَهَا لَمْ يَلْبَثُوٓا۟ إِلَّا عَشِيَّةً أَوْ ضُحَىٰهَا',
      trans:{ ar:'كأنهم يومَ يَرَونَ القيامةَ لم يَبقَوا في الدنيا إلا عشيّةً أو ضُحاها (وقتاً قصيراً).', en:'It will be, on the Day they see it, as though they had not remained [in the world] except for an afternoon or a morning thereof.' },
      std:'It will be, on the Day they see it, as though they had not remained [in the world] except for an afternoon or a morning thereof.',
      words:[ { w:'لَمْ يَلْبَثُوٓا۟ إِلَّا عَشِيَّةً', c:'#8E44AD', m:{ ar:'كأنَّ الدنيا كانت وقتاً قصيراً جداً', en:'as if this world lasted only a brief while' } } ] },
  ],

  about: {
    intro: { ar:'سُورةُ <b>النّازعات</b> تُقسِمُ بالملائكةِ التي تقبِضُ الأرواح، ثمَّ تُثبِتُ البعث، وتحكي قصَّةَ <b>موسى مع فرعون</b> عبرةً لمَن تكبَّر، ثمَّ تُذكِّرُ بأهوالِ يومِ القيامة.', en:'<b>An-Nazi‘at</b> swears by the angels that take souls, then affirms resurrection, tells the story of <b>Musa and Pharaoh</b> as a lesson for the arrogant, and warns of the terrors of Judgement Day.' },
    names: [
      { name:{ar:'النّازعات', en:'An-Nazi‘at (Those Who Pull Out)'},
        why:{ar:'أقسَمَ اللهُ بالملائكةِ التي تنزِعُ الأرواحَ بقوّة.', en:'Allah swears by the angels that pull souls out forcefully.'} },
    ],
    virtues: [
      { text:{ar:'تُذكِّرُ بموقفِ قبضِ الرُّوحِ وأهوالِ الآخرة، فتحمِلُ القلبَ على الاستعدادِ وتركِ الهوى.', en:'It reminds of the moment the soul is taken and the terrors of the Hereafter, moving the heart to prepare and abandon vain desire.'} },
      { text:{ar:'فيها قصَّةُ <b>موسى وفرعون</b>: درسٌ أنَّ المتكبِّرَ يهلِك، وأنَّ العاقبةَ للمتقين.', en:'It contains the story of <b>Musa and Pharaoh</b>: a lesson that the arrogant perish and the end belongs to the righteous.'} },
    ],
    traits: [
      {ar:'مكِّيَّةٌ، ستُّ وأربعونَ آيةً.', en:'Meccan, forty-six verses.'},
      {ar:'قَسَمٌ بالملائكة، وإثباتٌ للبعث، وقصةُ موسى، ومشاهدُ القيامة.', en:'An oath by the angels, proof of resurrection, the story of Musa, and scenes of Judgement.'},
      {ar:'تُحذِّرُ من الطغيانِ وإيثارِ الدنيا، وتأمُرُ بخوفِ الله.', en:'It warns against tyranny and preferring this world, and commands the fear of Allah.'},
    ],
  },

  tafsir: [
    { ayah:{ar:'١-١٤',en:'1-14'}, ar:'يُقسِمُ اللهُ بـ<b>الملائكة</b> في أحوالها: تَنزِعُ الأرواحَ، وتُدبِّرُ الأمر، أنَّ <b>البعثَ حق</b>. يومَ <b>تَرجُفُ الراجفة</b> (النفخةُ الأولى) وتَتبَعُها <b>الرادفة</b> (الثانية)، تَخافُ القلوبُ وتَذِلُّ الأبصار. والكفّارُ يَستبعِدونَ البعثَ: <b>﴿أَءِنَّا لَمَرْدُودُونَ﴾</b>؟ لكنه <b>﴿زَجْرَةٌ وَٰحِدَةٌ﴾</b> فإذا هم أحياء!', en:'Allah swears by <b>the angels</b> in their states — drawing out souls, arranging affairs — that <b>resurrection is real</b>. On the Day <b>the convulsion strikes</b> (first Blast) followed by <b>the subsequent</b> (second), hearts tremble and eyes are humbled. The disbelievers doubt resurrection: <b>"Will we be returned?"</b> But it is <b>"one shout"</b> and suddenly they are alive!' },
    { ayah:{ar:'١٥-٢٦',en:'15-26'}, ar:'ثم قصّةُ <b>موسى وفرعون</b>: أرسلَ اللهُ موسى ليدعوَ فرعونَ برِفق: <b>﴿هَل لَّكَ إِلَىٰٓ أَن تَزَكَّىٰ﴾</b>. وأراهُ المعجزةَ الكبرى، لكنَّ فرعونَ <b>كذَّبَ وعصى</b>، وادّعى: <b>﴿أَنَا۠ رَبُّكُمُ ٱلْأَعْلَىٰ﴾</b>! فأهلكَهُ اللهُ بالغرقِ والنار. <b>﴿إِنَّ فِى ذَٰلِكَ لَعِبْرَةً﴾</b> لمن يَخشى.', en:'Then the story of <b>Musa and Pharaoh</b>: Allah sent Musa to call Pharaoh gently: <b>"Would you purify yourself?"</b> He showed him the greatest sign, but Pharaoh <b>denied and disobeyed</b>, claiming: <b>"I am your most exalted lord!"</b> So Allah destroyed him by drowning and Fire. <b>"In that is a lesson"</b> for whoever fears.' },
    { ayah:{ar:'٢٧-٣٣',en:'27-33'}, ar:'ثم دليلٌ على البعث: <b>﴿ءَأَنتُمْ أَشَدُّ خَلْقًا أَمِ ٱلسَّمَآءُ﴾</b> — السماءُ أعظمُ خَلقاً منكم، فمَن بناها يَقدِرُ على بعثِكم! ويَذكُرُ نِعَمَه: رفعَ السماء، وأظلمَ الليلَ وأنارَ النهار، وبسطَ الأرضَ، وأخرجَ الماءَ والنبات، وثبَّتَ الجبال — <b>﴿مَتَٰعًا لَّكُمْ﴾</b>.', en:'Then a proof of resurrection: <b>"Are you a harder creation or the heaven?"</b> — the sky is greater in creation than you, so whoever built it can resurrect you! He mentions His blessings: raised the sky, darkened night and lit day, spread the earth, brought forth water and plants, set the mountains firm — <b>"as provision for you."</b>' },
    { ayah:{ar:'٣٤-٤٦',en:'34-46'}, ar:'ثم <b>الطامّةُ الكبرى</b> (القيامة): يتذكَّرُ الإنسانُ عملَه، وتُبرَزُ النار. فمَن <b>طغى وآثرَ الدنيا</b> فالنارُ مأواه، ومَن <b>خافَ مقامَ ربِّه ونهى النفسَ عن الهوى</b> فالجنّةُ مأواه. وحين يَسألونَ عن وقتِ القيامة، فعِلمُها عند اللهِ وحده، والنبيُّ <b>مُنذِرٌ</b>، وكأنهم يومَ يَرَونها لم يَلبَثوا إلا قليلاً.', en:'Then <b>the great Calamity</b> (Resurrection): man remembers his deeds, and Hell is exposed. Whoever <b>transgressed and preferred this world</b> — Hell is his abode; whoever <b>feared standing before his Lord and restrained his soul from desire</b> — Paradise is his abode. When they ask about the Hour\u2019s time, its knowledge is with Allah alone, and the Prophet is <b>a warner</b>; on the Day they see it, it is as if they stayed only a little.' },
  ],

  tadabbur: [
    { q:{ar:'ما العِبرةُ من قصّةِ فرعون؟', en:'What is the lesson from Pharaoh\u2019s story?'},
      a:{ar:'أنَّ <b>التكبُّرَ والطُّغيانَ</b> عاقبتُهما الهلاك. فرعونُ ادّعى الألوهيّةَ فأغرقَهُ الله. فلا أتكبَّر، وأخافُ اللهَ وأُطيعُه.', en:'That <b>arrogance and transgression</b> end in destruction. Pharaoh claimed divinity, so Allah drowned him. So I am not arrogant; I fear Allah and obey Him.'} },
    { q:{ar:'ما الطريقانِ في نهايةِ السورة؟', en:'What are the two paths at the surah\u2019s end?'},
      a:{ar:'مَن <b>طغى وآثرَ الدنيا</b> فمأواهُ النار. ومَن <b>خافَ مقامَ ربِّه ومنعَ نفسَه عن الهوى</b> فمأواهُ الجنّة. فأختارُ طريقَ خوفِ اللهِ وضبطِ النفس.', en:'Whoever <b>transgressed and preferred this world</b> — his abode is Hell. Whoever <b>feared standing before his Lord and restrained his soul from desire</b> — his abode is Paradise. So I choose the path of fearing Allah and self-control.'} },
    { q:{ar:'متى تقومُ القيامة؟', en:'When will the Hour come?'},
      a:{ar:'عِلمُها <b>عند اللهِ وحده</b>: <b>﴿إِلَىٰ رَبِّكَ مُنتَهَىٰهَآ﴾</b>. فلا أنشغِلُ بوقتِها، بل أستعِدُّ لها بالعملِ الصالح.', en:'Its knowledge is <b>with Allah alone</b>: <b>"To your Lord is its finality."</b> So I don\u2019t busy myself with its timing, but prepare for it with good deeds.'} },
  ],

  story: {
    title:{ar:'موسى وفرعونُ المتكبِّر', en:'Musa and the arrogant Pharaoh'},
    emoji:'🌊',
    pages:[
      { emoji:'👼', text:{ ar:'أقسمَ اللهُ بـ<b>الملائكةِ</b> التي تَقبِضُ الأرواحَ وتُدبِّرُ أمرَ الكونِ بإذنِه، أنَّ <b>البعثَ حق</b>! يومَ تأتي النفختان: الأولى تُرجِفُ كلَّ شيء، والثانيةُ يَقومُ بها الناسُ أحياء. وكان الكفّارُ يَستبعِدون: «كيف نُبعَثُ ونحن عِظامٌ بالية؟»', en:'Allah swore by <b>the angels</b> who take souls and arrange the universe by His leave, that <b>resurrection is real</b>! When the two Blasts come: the first convulses everything, and by the second people rise alive. The disbelievers doubted: "How will we be resurrected when we are decayed bones?"' } },
      { emoji:'🔥', text:{ ar:'ثم حكى اللهُ قصّةَ <b>موسى مع فرعون</b>. أرسلَ اللهُ موسى إلى فرعونَ الطاغية، وعلَّمَهُ أن يدعوَه <b>برِفقٍ ولُطف</b>: «هل لك أن تتطهَّرَ من الكُفر؟ وأدُلَّك على ربِّك فتخافَه؟» دعوةٌ جميلةٌ هادئة.', en:'Then Allah told the story of <b>Musa and Pharaoh</b>. Allah sent Musa to the tyrant Pharaoh, teaching him to call him <b>gently and kindly</b>: "Would you purify yourself from disbelief? And let me guide you to your Lord so you fear Him?" A beautiful, calm call.' } },
      { emoji:'😡', text:{ ar:'فأرى موسى فرعونَ <b>المعجزةَ الكبرى</b> (العصا تتحوَّلُ ثعباناً). لكنَّ فرعونَ <b>كذَّبَ وعصى</b> وتكبَّر، وجمعَ الناسَ وقال بغرورٍ عجيب: <b>﴿أَنَا۠ رَبُّكُمُ ٱلْأَعْلَىٰ﴾</b> — أنا ربُّكمُ الأعلى! فما أشدَّ كُفرَه وطُغيانَه!', en:'Musa showed Pharaoh <b>the greatest sign</b> (the staff turning into a snake). But Pharaoh <b>denied, disobeyed</b>, and grew arrogant, gathered the people and said with astonishing pride: <b>"I am your most exalted lord!"</b> — how severe his disbelief and tyranny!' } },
      { emoji:'💛', text:{ ar:'فأخذهُ اللهُ بعذابِ الدنيا (الغرقِ في البحر) والآخرة (النار)! <b>﴿إِنَّ فِى ذَٰلِكَ لَعِبْرَةً لِّمَن يَخْشَىٰ﴾</b>. ثم بيَّنَ اللهُ الطريقَين: مَن <b>طغى وآثرَ الدنيا</b> فالنار، ومَن <b>خافَ ربَّه ومنعَ نفسَه عن الحرام</b> فالجنّة. فالدرس: لا تتكبَّر، خَف اللهَ، واضبِط نفسَك عن الهوى.', en:'So Allah seized him with punishment in this world (drowning in the sea) and the next (the Fire)! <b>"Indeed in that is a lesson for whoever fears."</b> Then Allah showed the two paths: whoever <b>transgressed and preferred this world</b> — the Fire; whoever <b>feared his Lord and restrained his soul from the forbidden</b> — Paradise. The lesson: don\u2019t be arrogant, fear Allah, and control your desires.' } },
    ],
  },

  game: {
    kind:'order',
    prompt:{ ar:'رتّب كلمات الآية', en:'Put the verse in order' },
    words:['ٱذْهَبْ','إِلَىٰ','فِرْعَوْنَ','إِنَّهُۥ','طَغَىٰ'],
  },

  practice: [
    { icon:'🤲', title:{ar:'خَفْ مقامَ ربِّك', en:'Fear standing before your Lord'},
      body:{ar:'«وأمّا مَن خافَ مقامَ ربّه»: اترُكِ المعصيةَ حياءً من الله.', en:'“As for him who feared standing before his Lord”: leave sin out of shyness before Allah.'} },
    { icon:'🚫', title:{ar:'امنَعْ نفسَك عن الهوى', en:'Restrain yourself from desire'},
      body:{ar:'«ونهى النفسَ عن الهوى» فمأواه الجنة، فامنعْ نفسَك عمّا لا يُرضي الله.', en:'“And restrained himself from desire” — his home is Paradise; hold back from what displeases Allah.'} },
    { icon:'👑', title:{ar:'لا تتكبَّرْ كفرعون', en:'Never be arrogant like Pharaoh'},
      body:{ar:'فرعونُ تكبَّرَ فأغرَقَه الله، فتواضَعْ دائماً.', en:'Pharaoh was arrogant so Allah drowned him — always stay humble.'} },
    { icon:'📜', title:{ar:'استعدِّ للآخرة', en:'Prepare for the Hereafter'},
      body:{ar:'تذكَّرْ أنَّ الرُّوحَ تُقبَضُ يوماً، فاعمَلْ لذلك اليوم.', en:'Remember the soul will be taken one day — work for that day.'} },
  ],

  lesson: { ar:'أخافُ مقامَ ربّي وأمنعُ نفسي عن الهوى، فمأواي الجنّة؛ ولا أتكبَّر كفرعون.', en:'I fear standing before my Lord and restrain my soul from desire, so my abode is Paradise; I am not arrogant like Pharaoh.' },
  action: { ar:'اليوم سأمنعُ نفسي عن شيءٍ تشتهيه مِمّا لا يُرضي الله، تذكُّراً لوقوفي بين يديه.', en:'Today I will restrain myself from something my soul desires that displeases Allah, remembering I will stand before Him.' },
};


/* ───── ROOM 5: Treasures (stickers + certificate) ───── */
window.SURAHS.naziat.icon = "🌊";
window.SURAHS.naziat.treasures = [
  {
    "icon": "😇",
    "color": "#27AE60",
    "title": {
      "ar": "المَلائِكةُ النَّازِعات",
      "en": "The Angels Who Pull"
    }
  },
  {
    "icon": "🌊",
    "color": "#1ABC9C",
    "title": {
      "ar": "مُوسى وفِرعَون",
      "en": "Musa & Pharaoh"
    }
  },
  {
    "icon": "⛰️",
    "color": "#F4D03F",
    "title": {
      "ar": "الجِبالُ المُرساة",
      "en": "The Anchored Mountains"
    }
  },
  {
    "icon": "⏳",
    "color": "#2980B9",
    "title": {
      "ar": "عِلمُ السَّاعة",
      "en": "Knowledge of the Hour"
    }
  },
  {
    "icon": "🪴",
    "color": "#E67E22",
    "title": {
      "ar": "جنَّةُ المَأوى",
      "en": "The Garden of Refuge"
    }
  },
  {
    "icon": "💚",
    "color": "#8E44AD",
    "title": {
      "ar": "خَوفُ المَقام",
      "en": "Awe of Standing before Allah"
    }
  }
];
window.SURAHS.naziat.certificate = {
  "subtitle": {
    "ar": "تُمنَحُ هذه الشَّهادةُ لِمَن أتمَّ رِحلةَ سُورةِ النَّازِعَات",
    "en": "Awarded to the one who completed the journey of Surah An-Nazi'at"
  },
  "statement": {
    "ar": "لِتدبُّرِه/تدبُّرِها قِصَّةَ <b>مُوسى وفِرعَون</b> وآياتِ السَّاعة، ولِيَعلَمَ أنَّ مَن خافَ مَقامَ رَبِّهِ ونَهى النَّفسَ عن الهَوى فالجنَّةُ مَأواه.",
    "en": "For reflecting on the story of <b>Musa and Pharaoh</b> and the signs of the Hour — learning that whoever fears standing before their Lord and restrains the soul from desire, Paradise is their home."
  }
};
