/* ═══════════════════════════════════════════════════════════════
   SURAH INDEX — order, emblem, tree, meta for the Quran Garden.
   Full content per surah lives in quran-data/<slug>.js
   ─────────────────────────────────────────────────────────────── */
window.SURAH_INDEX = [
  { slug:'fatihah', num:1,   emoji:'🕋', tree:'🌳', nameAr:'الفَاتِحَة', nameEn:'Al-Fatihah',
    metaAr:'مكية · ٧ آيات', metaEn:'Meccan · 7 verses' },
  { slug:'naba',    num:78,  emoji:'📰', tree:'🌳', nameAr:'النَّبَأ',     nameEn:'An-Naba\u2019',
    metaAr:'مكية · ٤٠ آية', metaEn:'Meccan · 40 verses' },
  { slug:'naziat',  num:79,  emoji:'🌊', tree:'🌴', nameAr:'النَّازِعَات', nameEn:'An-Nazi\u02bdat',
    metaAr:'مكية · ٤٦ آية', metaEn:'Meccan · 46 verses' },
  { slug:'abasa',   num:80,  emoji:'🤲', tree:'🌿', nameAr:'عَبَس',       nameEn:'\u02bdAbasa',
    metaAr:'مكية · ٤٢ آية', metaEn:'Meccan · 42 verses' },
  { slug:'takwir',  num:81,  emoji:'🌑', tree:'🌃', nameAr:'التَّكْوِير',  nameEn:'At-Takwir',
    metaAr:'مكية · ٢٩ آية', metaEn:'Meccan · 29 verses' },
  { slug:'infitar', num:82,  emoji:'⭐', tree:'🌌', nameAr:'الانْفِطَار', nameEn:'Al-Infitar',
    metaAr:'مكية · ١٩ آية', metaEn:'Meccan · 19 verses' },
  { slug:'mutaffifin',num:83, emoji:'⚖️', tree:'🌵', nameAr:'المُطَفِّفِين', nameEn:'Al-Mutaffifin',
    metaAr:'مكية · ٣٦ آية', metaEn:'Meccan · 36 verses' },
  { slug:'inshiqaq',num:84,  emoji:'📜', tree:'🌙', nameAr:'الانْشِقَاق', nameEn:'Al-Inshiqaq',
    metaAr:'مكية · ٢٥ آية', metaEn:'Meccan · 25 verses' },
  { slug:'buruj',   num:85,  emoji:'🔥', tree:'🌟', nameAr:'البُرُوج',    nameEn:'Al-Buruj',
    metaAr:'مكية · ٢٢ آية', metaEn:'Meccan · 22 verses' },
  { slug:'tariq',   num:86,  emoji:'⭐', tree:'🌃', nameAr:'الطَّارِق',   nameEn:'At-Tariq',
    metaAr:'مكية · ١٧ آية', metaEn:'Meccan · 17 verses' },
  { slug:'ala',     num:87,  emoji:'🌿', tree:'🌾', nameAr:'الأَعْلَى',   nameEn:'Al-A\u02bdla',
    metaAr:'مكية · ١٩ آية', metaEn:'Meccan · 19 verses' },
  { slug:'ghashiyah',num:88, emoji:'🐪', tree:'🌴', nameAr:'الغَاشِيَة',  nameEn:'Al-Ghashiyah',
    metaAr:'مكية · ٢٦ آية', metaEn:'Meccan · 26 verses' },
  { slug:'fajr',    num:89,  emoji:'🌅', tree:'🌳', nameAr:'الفَجْر',     nameEn:'Al-Fajr',
    metaAr:'مكية · ٣٠ آية', metaEn:'Meccan · 30 verses' },
  { slug:'balad',   num:90,  emoji:'⛰️', tree:'🌵', nameAr:'البَلَد',     nameEn:'Al-Balad',
    metaAr:'مكية · ٢٠ آية', metaEn:'Meccan · 20 verses' },
  { slug:'shams',   num:91,  emoji:'☀️', tree:'🌻', nameAr:'الشَّمْس',    nameEn:'Ash-Shams',
    metaAr:'مكية · ١٥ آية', metaEn:'Meccan · 15 verses' },
  { slug:'layl',    num:92,  emoji:'🌙', tree:'🌳', nameAr:'اللَّيْل',    nameEn:'Al-Layl',
    metaAr:'مكية · ٢١ آية', metaEn:'Meccan · 21 verses' },
  { slug:'duha',    num:93,  emoji:'🌄', tree:'🌅', nameAr:'الضُّحَى',    nameEn:'Ad-Duha',
    metaAr:'مكية · ١١ آية', metaEn:'Meccan · 11 verses' },
  { slug:'sharh',   num:94,  emoji:'🌈', tree:'🌱', nameAr:'الشَّرْح',    nameEn:'Ash-Sharh',
    metaAr:'مكية · ٨ آيات', metaEn:'Meccan · 8 verses' },
  { slug:'tin',     num:95,  emoji:'🫒', tree:'🌳', nameAr:'التِّين',     nameEn:'At-Tin',
    metaAr:'مكية · ٨ آيات', metaEn:'Meccan · 8 verses' },
  { slug:'alaq',    num:96,  emoji:'📖', tree:'🌴', nameAr:'العَلَق',     nameEn:'Al-\u02bdAlaq',
    metaAr:'مكية · ١٩ آية', metaEn:'Meccan · 19 verses' },
  { slug:'qadr',    num:97,  emoji:'🌙', tree:'⭐', nameAr:'القَدْر',     nameEn:'Al-Qadr',
    metaAr:'مكية · ٥ آيات', metaEn:'Meccan · 5 verses' },
  { slug:'bayyinah',num:98,  emoji:'⭐', tree:'🌿', nameAr:'البَيِّنَة',  nameEn:'Al-Bayyinah',
    metaAr:'مدنية · ٨ آيات', metaEn:'Medinan · 8 verses' },
  { slug:'zalzalah',num:99,  emoji:'🌍', tree:'🌋', nameAr:'الزَّلْزَلَة', nameEn:'Az-Zalzalah',
    metaAr:'مدنية · ٨ آيات', metaEn:'Medinan · 8 verses' },
  { slug:'adiyat',  num:100, emoji:'🐎', tree:'🌾', nameAr:'العَادِيَات', nameEn:'Al-Adiyat',
    metaAr:'مكية · ١١ آية', metaEn:'Meccan · 11 verses' },
  { slug:'qariah',  num:101, emoji:'⚖️', tree:'🌳', nameAr:'القَارِعَة', nameEn:'Al-Qari\u2019ah',
    metaAr:'مكية · ١١ آية', metaEn:'Meccan · 11 verses' },
  { slug:'takathur',num:102, emoji:'🏺', tree:'🌴', nameAr:'التَّكَاثُر', nameEn:'At-Takathur',
    metaAr:'مكية · ٨ آيات', metaEn:'Meccan · 8 verses' },
  { slug:'asr',     num:103, emoji:'⏳', tree:'🌱', nameAr:'العَصْر',    nameEn:'Al-Asr',
    metaAr:'مكية · ٣ آيات', metaEn:'Meccan · 3 verses' },
  { slug:'humazah', num:104, emoji:'💰', tree:'🌵', nameAr:'الهُمَزَة',  nameEn:'Al-Humazah',
    metaAr:'مكية · ٩ آيات', metaEn:'Meccan · 9 verses' },
  { slug:'fil',     num:105, emoji:'🐘', tree:'🌳', nameAr:'الفِيل',     nameEn:'Al-Fil',
    metaAr:'مكية · ٥ آيات', metaEn:'Meccan · 5 verses' },
  { slug:'quraysh', num:106, emoji:'🕋', tree:'🌴', nameAr:'قُرَيْش',    nameEn:'Quraysh',
    metaAr:'مكية · ٤ آيات', metaEn:'Meccan · 4 verses' },
  { slug:'maun',    num:107, emoji:'🤲', tree:'🌸', nameAr:'المَاعُون',  nameEn:'Al-Ma\u2019un',
    metaAr:'مكية · ٧ آيات', metaEn:'Meccan · 7 verses' },
  { slug:'kawthar', num:108, emoji:'🌊', tree:'🌲', nameAr:'الكَوْثَر',  nameEn:'Al-Kawthar',
    metaAr:'مكية · ٣ آيات', metaEn:'Meccan · 3 verses' },
  { slug:'kafirun', num:109, emoji:'🛡️', tree:'🌳', nameAr:'الكَافِرُون', nameEn:'Al-Kafirun',
    metaAr:'مكية · ٦ آيات', metaEn:'Meccan · 6 verses' },
  { slug:'nasr',    num:110, emoji:'🕊️', tree:'🌷', nameAr:'النَّصْر',   nameEn:'An-Nasr',
    metaAr:'مدنية · ٣ آيات', metaEn:'Medinan · 3 verses' },
  { slug:'masad',   num:111, emoji:'🔥', tree:'🌵', nameAr:'المَسَد',    nameEn:'Al-Masad',
    metaAr:'مكية · ٥ آيات', metaEn:'Meccan · 5 verses' },
  { slug:'ikhlas',  num:112, emoji:'🌟', tree:'🌟', nameAr:'الإِخْلَاص', nameEn:'Al-Ikhlas',
    metaAr:'مكية · ٤ آيات', metaEn:'Meccan · 4 verses' },
  { slug:'falaq',   num:113, emoji:'🌅', tree:'🌴', nameAr:'الفَلَق',    nameEn:'Al-Falaq',
    metaAr:'مكية · ٥ آيات', metaEn:'Meccan · 5 verses' },
  { slug:'nas',     num:114, emoji:'🛡️', tree:'🌸', nameAr:'النَّاس',    nameEn:'An-Nas',
    metaAr:'مكية · ٦ آيات', metaEn:'Meccan · 6 verses' },
];
window.SURAHS = window.SURAHS || {};
