/* corners/stories/seerah-little/akhlaq.js — السيرة: أخلاقه ووداعه ﷺ للصغار (٣–٦) · ٨ حكايات */
window.SEERAH_LITTLE = window.SEERAH_LITTLE || {};
window.SEERAH_LITTLE.akhlaq = {
  id:'akhlaq', icon:'💚', color:'#1F8B6E', title:'أَخْلَاقُهُ وَوَدَاعُهُ ﷺ', tag:'الرَّحْمَةُ الْمُهْدَاة',
  stories:[

{ id:'khuluq', icon:'💚', color:'#1F8B6E', title:'أَحْسَنُ النَّاسِ خُلُقًا',
  tag:'وَإِنَّكَ لَعَلَى خُلُقٍ عَظِيم',
  pages:[
    { emoji:'💚', text:'كَانَ النَّبِيُّ ﷺ أَحْسَنَ النَّاسِ خُلُقًا، حَتَّى قَالَ اللهُ عَنْه: وَإِنَّكَ لَعَلَى خُلُقٍ عَظِيم.',
      prompt:'A gentle radiant figure surrounded by warmth and kindness, great character, warm, no face' },
    { emoji:'😊', text:'كَانَ بَشُوشًا مُبْتَسِمًا، لَيِّنَ الْكَلَام، لَا يَغْضَبُ لِنَفْسِه، وَيُحِبُّ الْخَيْرَ لِلْجَمِيع.',
      prompt:'A warm smiling presence bringing comfort to people, gentleness, warm bright, no face detail' },
    { emoji:'🤝', text:'قَالَ ﷺ: إِنَّمَا بُعِثْتُ لِأُتَمِّمَ مَكَارِمَ الْأَخْلَاق — فَالدِّينُ كُلُّهُ أَخْلَاقٌ حَسَنَة.',
      prompt:'Beautiful character shown as a glowing crown of virtues, perfecting good manners, warm serene' },
    { emoji:'💛', text:'فَأَقْتَدِي بِأَخْلَاقِه: أَبْتَسِمُ، وَأَلِينُ فِي كَلَامِي، وَأُحِبُّ الْخَيْرَ لِلنَّاس.',
      prompt:'A cheerful kind child spreading smiles among friends, good character, uplifting warm' },
  ],
  moral:'الدِّينُ أَخْلَاق، وَأَقْتَدِي بِأَحْسَنِ النَّاسِ خُلُقًا نَبِيِّي ﷺ. 💛',
  game:{ type:'sort', title:'أَيُّهَا مِنْ حُسْنِ الْخُلُق؟', bins:['خُلُقٌ حَسَن 💚','خُلُقٌ سَيِّئ 🚫'], items:[
    { e:'😊', t:'الِابْتِسَامَةُ وَلِينُ الْكَلَام', bin:0 },
    { e:'😠', t:'الْغَضَبُ وَالصُّرَاخ', bin:1 },
    { e:'🤝', t:'حُبُّ الْخَيْرِ لِلنَّاس', bin:0 },
    { e:'🙄', t:'الْكِبْرُ وَالسُّخْرِيَة', bin:1 } ] },
  act:{ q:'بِمَ وَصَفَ اللهُ خُلُقَ النَّبِيِّ ﷺ؟', yay:'أَحْسَنْت! خُلُقٌ عَظِيم', opts:[
    { e:'💚', t:'عَلَى خُلُقٍ عَظِيم', ok:true },
    { e:'😠', t:'خُلُقٌ سَيِّئ' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ حَسِّنْ خُلُقِي كَمَا حَسَّنْتَ خَلْقِي' },

{ id:'rahma', icon:'👶', color:'#E84393', title:'رَحْمَتُهُ بِالصِّغَار',
  tag:'يُحِبُّ الْأَطْفَال',
  pages:[
    { emoji:'👶', text:'كَانَ النَّبِيُّ ﷺ يُحِبُّ الْأَطْفَالَ حُبًّا شَدِيدًا، يُلَاعِبُهُم وَيُقَبِّلُهُم وَيَمْسَحُ عَلَى رُؤُوسِهِم.',
      prompt:'A caring figure gently playing with joyful children, love of children, warm tender, no face detail' },
    { emoji:'🕌', text:'وَكَانَ يُخَفِّفُ الصَّلَاةَ إِذَا سَمِعَ بُكَاءَ طِفْلٍ رَحْمَةً بِأُمِّه!',
      prompt:'A prayer scene with gentle care for a crying child nearby, mercy in worship, warm serene, no faces' },
    { emoji:'🐦', text:'وَمَازَحَ طِفْلًا صَغِيرًا مَاتَ عُصْفُورُهُ فَقَال: يَا أَبَا عُمَيْر، مَا فَعَلَ النُّغَيْر؟',
      prompt:'A kind gentle moment comforting a small child about a pet bird, tenderness, warm bright, no faces' },
    { emoji:'💚', text:'فَأَتَعَلَّمُ الرَّحْمَةَ بِالصِّغَار: أُلَاعِبُ إِخْوَتِي الصِّغَارَ وَأَرْفُقُ بِهِم.',
      prompt:'A child kindly playing with younger siblings, gentleness with little ones, warm uplifting' },
  ],
  moral:'أَرْحَمُ الصِّغَارَ وَأُلَاعِبُهُم وَأَرْفُقُ بِهِم كَمَا فَعَلَ النَّبِيُّ ﷺ. 💚',
  game:{ type:'find', title:'ارْحَمِ الصِّغَار! اجْمَعِ الْقُلُوبَ الرَّحِيمَةَ الْخَمْس', target:'💚', count:5, distractors:['👶','🐦'], size:12 },
  act:{ q:'مَاذَا كَانَ يَفْعَلُ النَّبِيُّ ﷺ إِذَا سَمِعَ بُكَاءَ طِفْلٍ فِي الصَّلَاة؟', yay:'أَحْسَنْت! يُخَفِّفُ الصَّلَاةَ رَحْمَةً بِأُمِّه', opts:[
    { e:'🕌', t:'يُخَفِّفُ الصَّلَاةَ رَحْمَة', ok:true },
    { e:'😠', t:'يَغْضَب' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ اجْعَلْنِي رَحِيمًا بِالصِّغَارِ وَالضُّعَفَاء' },

{ id:'sidq', icon:'🤝', color:'#B8862E', title:'الصِّدْقُ وَالْأَمَانَة',
  tag:'أَقْوَالُهُ وَأَفْعَالُهُ',
  pages:[
    { emoji:'🤝', text:'كَانَ النَّبِيُّ ﷺ أَصْدَقَ النَّاسِ وَأَأْمَنَهُم، لَا يَكْذِبُ أَبَدًا وَلَا يُخْلِفُ وَعْدَهُ وَلَا يَخُونُ أَمَانَة.',
      prompt:'A trustworthy figure keeping a promise and a trust, honesty embodied, warm dignified, no face' },
    { emoji:'💬', text:'عَلَّمَنَا أَنَّ الصِّدْقَ يَهْدِي إِلَى الْبِرّ، وَالْبِرَّ يَهْدِي إِلَى الْجَنَّة.',
      prompt:'A path of light from honesty leading toward paradise, truthfulness leading to good, warm serene' },
    { emoji:'🚫', text:'وَنَهَى عَنِ الْكَذِبِ حَتَّى فِي الْمِزَاح، وَعَنْ إِخْلَافِ الْوَعْدِ وَخِيَانَةِ الْأَمَانَة.',
      prompt:'A gentle reminder against lying even in jest, integrity, warm clear illustration' },
    { emoji:'💚', text:'فَأَكُونُ صَادِقًا أَمِينًا فِي كُلِّ شَيْء: فِي كَلَامِي وَوَعْدِي وَأَمَانَتِي.',
      prompt:'A child telling the truth and keeping a promise proudly, honesty and trust, warm uplifting' },
  ],
  moral:'أَكُونُ صَادِقًا أَمِينًا فِي كَلَامِي وَوَعْدِي، فَالصِّدْقُ يَهْدِي لِلْجَنَّة. 💚',
  game:{ type:'sort', title:'أَيُّهَا صِدْقٌ وَأَمَانَة؟', bins:['صِدْقٌ وَأَمَانَة ✅','كَذِبٌ وَخِيَانَة 🚫'], items:[
    { e:'🤝', t:'أَحْفَظُ الْوَعْدَ وَالْأَمَانَة', bin:0 },
    { e:'🤥', t:'أَكْذِبُ فِي الْمِزَاح', bin:1 },
    { e:'😊', t:'أَقُولُ الصِّدْقَ دَائِمًا', bin:0 },
    { e:'👀', t:'أَخُونُ مَا اؤْتُمِنْتُ عَلَيْه', bin:1 } ] },
  act:{ q:'إِلَامَ يَهْدِي الصِّدْق؟', yay:'أَحْسَنْت! الصِّدْقُ يَهْدِي إِلَى الْبِرِّ وَالْجَنَّة', opts:[
    { e:'💚', t:'إِلَى الْبِرِّ ثُمَّ الْجَنَّة', ok:true },
    { e:'😞', t:'إِلَى الْمَشَاكِل' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ اجْعَلْنِي صَادِقًا أَمِينًا كَنَبِيِّكَ ﷺ' },

{ id:'humble', icon:'🙇', color:'#8E44AD', title:'تَوَاضُعُهُ ﷺ',
  tag:'سَيِّدُ النَّاسِ وَأَشَدُّهُم تَوَاضُعًا',
  pages:[
    { emoji:'🙇', text:'مَعَ أَنَّهُ سَيِّدُ الْخَلْق، كَانَ النَّبِيُّ ﷺ مُتَوَاضِعًا: يَخْدِمُ نَفْسَهُ وَأَهْلَه، وَيَجْلِسُ مَعَ الْفُقَرَاء.',
      prompt:'A humble leader doing his own chores and sitting with the poor, humility, warm, no face detail' },
    { emoji:'🧹', text:'كَانَ يَخْصِفُ نَعْلَهُ، وَيَحْلُبُ شَاتَه، وَيُعِينُ فِي أَعْمَالِ الْبَيْت، وَلَا يَتَكَبَّرُ عَلَى أَحَد.',
      prompt:'A great figure mending his own sandal and helping at home, self-reliance and humility, warm, no faces' },
    { emoji:'🍞', text:'وَكَانَ يُجِيبُ دَعْوَةَ الْفَقِير، وَيَجْلِسُ حَيْثُ يَنْتَهِي بِهِ الْمَجْلِس، وَلَا يُحِبُّ أَنْ يَقُومَ لَهُ النَّاس.',
      prompt:'A modest figure sitting simply among people without seeking special treatment, humility, warm bright' },
    { emoji:'💚', text:'فَأَتَعَلَّمُ التَّوَاضُع: مَهْمَا عَلَا قَدْرِي أَبْقَى مُتَوَاضِعًا أَخْدِمُ نَفْسِي وَأُسَاعِدُ أَهْلِي.',
      prompt:'A child helping at home humbly with a smile, humility and service, warm uplifting' },
  ],
  moral:'التَّوَاضُعُ خُلُقُ الْعُظَمَاء، وَأَخْدِمُ نَفْسِي وَأَهْلِي وَلَا أَتَكَبَّر. 💚',
  game:{ type:'sort', title:'أَيُّهَا مِنَ التَّوَاضُع؟', bins:['تَوَاضُع 💚','كِبْر 🚫'], items:[
    { e:'🧹', t:'أُسَاعِدُ فِي أَعْمَالِ الْبَيْت', bin:0 },
    { e:'😤', t:'أَتَكَبَّرُ عَلَى النَّاس', bin:1 },
    { e:'🤝', t:'أَجْلِسُ مَعَ الْجَمِيع', bin:0 },
    { e:'🙄', t:'أَحْتَقِرُ الْفُقَرَاء', bin:1 } ] },
  act:{ q:'كَيْفَ كَانَ تَوَاضُعُ النَّبِيِّ ﷺ؟', yay:'أَحْسَنْت! يَخْدِمُ نَفْسَهُ وَلَا يَتَكَبَّر', opts:[
    { e:'🙇', t:'يَخْدِمُ نَفْسَهُ وَيُعِينُ أَهْلَه', ok:true },
    { e:'😤', t:'يَتَكَبَّرُ عَلَى النَّاس' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ ارْزُقْنِي التَّوَاضُعَ وَحُبَّ النَّاس' },

{ id:'animals', icon:'🐈', color:'#16A085', title:'رِفْقُهُ بِالْحَيَوَان',
  tag:'الرَّحْمَةُ بِكُلِّ مَخْلُوق',
  pages:[
    { emoji:'🐈', text:'كَانَ النَّبِيُّ ﷺ رَحِيمًا بِالْحَيَوَان، يَنْهَى عَنْ إِيذَائِهِ وَتَحْمِيلِهِ فَوْقَ طَاقَتِه.',
      prompt:'Gentle care for animals like a cat and a camel, mercy to animals, warm tender scene, no faces' },
    { emoji:'🐪', text:'رَأَى جَمَلًا جَائِعًا مُتْعَبًا فَحَزِن، وَقَالَ لِصَاحِبِه: اتَّقِ اللهَ فِي هَذِهِ الْبَهِيمَة!',
      prompt:'A caring figure showing concern for a tired camel, compassion for a suffering animal, warm, no faces' },
    { emoji:'💧', text:'وَأَخْبَرَ ﷺ أَنَّ امْرَأَةً دَخَلَتِ الْجَنَّةَ فِي كَلْبٍ سَقَتْه، وَأُخْرَى دَخَلَتِ النَّارَ فِي هِرَّةٍ حَبَسَتْهَا.',
      prompt:'Water given kindly to a thirsty dog with a warm glow, mercy rewarded, warm gentle, no faces' },
    { emoji:'💚', text:'فَأَتَعَلَّمُ الرَّحْمَةَ بِالْحَيَوَان: أُطْعِمُه، وَأَسْقِيه، وَلَا أُؤْذِيه.',
      prompt:'A child feeding and giving water to a cat and birds kindly, mercy to animals, warm uplifting' },
  ],
  moral:'أَرْحَمُ الْحَيَوَان: أُطْعِمُهُ وَأَسْقِيهِ وَلَا أُؤْذِيه. 💚',
  game:{ type:'sort', title:'كَيْفَ نُعَامِلُ الْحَيَوَان؟', bins:['رَحْمَةٌ 💚','قَسْوَةٌ 🚫'], items:[
    { e:'💧', t:'أَسْقِي الْقِطَّةَ الْعَطْشَى', bin:0 },
    { e:'😠', t:'أُؤْذِي الْحَيَوَان', bin:1 },
    { e:'🍖', t:'أُطْعِمُ الْجَائِع', bin:0 },
    { e:'🔒', t:'أَحْبِسُهُ بِلَا طَعَام', bin:1 } ] },
  act:{ q:'امْرَأَةٌ دَخَلَتِ الْجَنَّة، بِمَاذَا؟', yay:'أَحْسَنْت! سَقَتْ كَلْبًا عَطْشَان', opts:[
    { e:'💧', t:'سَقَتْ كَلْبًا عَطْشَان', ok:true },
    { e:'😴', t:'نَامَتْ كَثِيرًا' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ ارْزُقْنِي الرَّحْمَةَ بِكُلِّ مَخْلُوق' },

{ id:'wada', icon:'🏔️', color:'#D4A017', title:'حَجَّةُ الْوَدَاع',
  tag:'وَصِيَّةُ النَّبِيِّ ﷺ الْأَخِيرَة',
  pages:[
    { emoji:'🏔️', text:'فِي آخِرِ حَيَاتِه، حَجَّ النَّبِيُّ ﷺ حَجَّةً وَاحِدَة، وَخَطَبَ فِي النَّاسِ خُطْبَةً عَظِيمَةً وَدَّعَهُم فِيهَا.',
      prompt:'A vast gathering of pilgrims on a plain listening to a farewell address, the Farewell, warm reverent, no faces' },
    { emoji:'🤝', text:'قَال: إِنَّ دِمَاءَكُم وَأَمْوَالَكُم عَلَيْكُم حَرَام — فَلَا ظُلْمَ وَلَا اعْتِدَاءَ بَيْنَكُم.',
      prompt:'A message of justice and sanctity of rights glowing over a crowd, protection of rights, warm, no faces' },
    { emoji:'⚖️', text:'وَقَال: لَا فَضْلَ لِعَرَبِيٍّ عَلَى أَعْجَمِيٍّ إِلَّا بِالتَّقْوَى — كُلُّ النَّاسِ سَوَاءٌ عِنْدَ الله.',
      prompt:'Diverse people standing equal under warm light, equality of all people, warm bright, no faces' },
    { emoji:'💚', text:'وَأَوْصَى بِالنِّسَاءِ وَالضُّعَفَاء، وَبِالتَّمَسُّكِ بِالْقُرْآنِ وَالسُّنَّة، وَقَال: أَلَا هَلْ بَلَّغْت؟',
      prompt:'A caring final counsel with the Quran glowing, holding to guidance, warm serene, no faces' },
  ],
  moral:'وَصِيَّةُ النَّبِيِّ ﷺ: الْعَدْلُ وَالْمُسَاوَاةُ وَالتَّمَسُّكُ بِالْقُرْآنِ وَالسُّنَّة. 💚',
  game:{ type:'pairs', title:'صِلْ كُلَّ وَصِيَّةٍ بِمَعْنَاهَا', pairs:[
    ['🤝 الدِّمَاءُ وَالْأَمْوَال','حَرَامٌ لَا ظُلْمَ فِيهَا'],
    ['⚖️ لَا فَضْلَ لِأَحَد','إِلَّا بِالتَّقْوَى'],
    ['📖 التَّمَسُّك','بِالْقُرْآنِ وَالسُّنَّة'] ] },
  act:{ q:'بِمَ يَتَفَاضَلُ النَّاسُ عِنْدَ اللهِ فِي خُطْبَةِ الْوَدَاع؟', yay:'أَحْسَنْت! بِالتَّقْوَى لَا بِالْعِرْقِ', opts:[
    { e:'⚖️', t:'بِالتَّقْوَى', ok:true },
    { e:'💰', t:'بِالْمَال' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ ثَبِّتْنَا عَلَى الْقُرْآنِ وَالسُّنَّة' },

{ id:'wafat', icon:'🕊️', color:'#5B4B8A', title:'وَفَاةُ النَّبِيِّ ﷺ',
  tag:'لِقَاءُ الرَّفِيقِ الْأَعْلَى',
  pages:[
    { emoji:'😢', text:'بَعْدَ حَجَّةِ الْوَدَاع، مَرِضَ النَّبِيُّ ﷺ، ثُمَّ تُوُفِّيَ وَانْتَقَلَ إِلَى رَبِّه، فَحَزِنَ الْمُسْلِمُونَ حُزْنًا عَظِيمًا.',
      prompt:'A soft somber but hopeful scene with warm light over Madinah, grief of loss, no faces, tender' },
    { emoji:'🗣️', text:'قَامَ أَبُو بَكْرٍ وَقَال: مَنْ كَانَ يَعْبُدُ مُحَمَّدًا فَإِنَّ مُحَمَّدًا قَدْ مَات، وَمَنْ كَانَ يَعْبُدُ اللهَ فَإِنَّ اللهَ حَيٌّ لَا يَمُوت.',
      prompt:'A steadfast figure calming a grieving crowd with wisdom, firmness in loss, warm, no faces' },
    { emoji:'📖', text:'تَرَكَ لَنَا النَّبِيُّ ﷺ الْقُرْآنَ وَالسُّنَّة، فَمَنْ تَمَسَّكَ بِهِمَا لَنْ يَضِلَّ أَبَدًا.',
      prompt:'A glowing Quran and light of guidance remaining, the lasting legacy, warm serene' },
    { emoji:'💚', text:'مَاتَ جَسَدُهُ ﷺ لَكِنَّ سُنَّتَهُ وَمَحَبَّتَهُ حَيَّةٌ فِي قُلُوبِنَا، وَنَلْقَاهُ فِي الْجَنَّةِ إِنْ أَحْبَبْنَاهُ وَاتَّبَعْنَاه.',
      prompt:'A warm eternal light connecting hearts to the Prophet legacy, enduring love, uplifting serene' },
  ],
  moral:'نُحِبُّ النَّبِيَّ ﷺ وَنَتَّبِعُ سُنَّتَه، فَنَلْقَاهُ فِي الْجَنَّة. 💚',
  game:{ type:'sort', title:'كَيْفَ نُحِبُّ النَّبِيَّ ﷺ حَقًّا؟', bins:['حُبٌّ صَحِيح 💚','لَيْسَ حُبًّا 🚫'], items:[
    { e:'📖', t:'أَتَّبِعُ سُنَّتَه', bin:0 },
    { e:'💝', t:'أُكْثِرُ الصَّلَاةَ عَلَيْه', bin:0 },
    { e:'🙅', t:'أُخَالِفُ هَدْيَه', bin:1 },
    { e:'😴', t:'أَنْسَاهُ وَلَا أَتَعَلَّمُ عَنْه', bin:1 } ] },
  act:{ q:'مَاذَا تَرَكَ لَنَا النَّبِيُّ ﷺ لِنَهْتَدِيَ بِه؟', yay:'أَحْسَنْت! الْقُرْآنَ وَالسُّنَّة', opts:[
    { e:'📖', t:'الْقُرْآنَ وَالسُّنَّة', ok:true },
    { e:'💰', t:'مَالًا كَثِيرًا' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّد، وَاجْمَعْنَا بِهِ فِي الْجَنَّة' },

{ id:'love', icon:'💝', color:'#C0392B', title:'كَيْفَ أُحِبُّ نَبِيِّي؟',
  tag:'مَحَبَّةُ النَّبِيِّ ﷺ',
  pages:[
    { emoji:'💝', text:'مَحَبَّةُ النَّبِيِّ ﷺ مِنْ أَعْظَمِ الْإِيمَان: قَالَ ﷺ لَا يُؤْمِنُ أَحَدُكُم حَتَّى أَكُونَ أَحَبَّ إِلَيْهِ مِنْ نَفْسِه.',
      prompt:'A glowing heart full of love and light, love of the Prophet, warm tender' },
    { emoji:'💚', text:'أُحِبُّهُ بِاتِّبَاعِ سُنَّتِه: كَيْفَ أَكَل، وَنَام، وَتَعَامَلَ مَعَ النَّاسِ بِالرَّحْمَةِ وَالصِّدْق.',
      prompt:'A child following the Prophet sunnah in daily life joyfully, love through following, warm bright' },
    { emoji:'💌', text:'وَأُكْثِرُ الصَّلَاةَ عَلَيْه: اللَّهُمَّ صَلِّ عَلَى مُحَمَّد — فَمَنْ صَلَّى عَلَيْهِ مَرَّةً صَلَّى اللهُ عَلَيْهِ عَشْرًا.',
      prompt:'Hearts of light rising as blessings upon the Prophet, sending salawat, warm radiant' },
    { emoji:'🌟', text:'فَأُحِبُّ نَبِيِّي ﷺ، وَأَتَعَلَّمُ سِيرَتَه، وَأَقْتَدِي بِأَخْلَاقِه، لِأَكُونَ مِنْ أُمَّتِهِ الْمُحِبِّين.',
      prompt:'A child aspiring toward the Prophet light with a full heart, aspiration and love, uplifting warm' },
  ],
  moral:'أُحِبُّ نَبِيِّي ﷺ بِاتِّبَاعِ سُنَّتِهِ وَالصَّلَاةِ عَلَيْهِ وَالِاقْتِدَاءِ بِأَخْلَاقِه. 🌟',
  game:{ type:'order', title:'رَتِّبْ مَرَاحِلَ حَيَاةِ النَّبِيِّ ﷺ', items:[
    { e:'🌟', t:'الْمَوْلِدُ وَالنَّشْأَة' },
    { e:'📜', t:'الْبِعْثَةُ وَالدَّعْوَة' },
    { e:'🌙', t:'الْهِجْرَةُ وَبِنَاءُ الْمَدِينَة' },
    { e:'🕋', t:'فَتْحُ مَكَّةَ وَالْوَدَاع' } ] },
  act:{ q:'كَيْفَ أُحِبُّ نَبِيِّي ﷺ حَقًّا؟', yay:'أَحْسَنْت! بِاتِّبَاعِ سُنَّتِهِ وَالصَّلَاةِ عَلَيْه', opts:[
    { e:'💚', t:'أَتَّبِعُ سُنَّتَهُ وَأُصَلِّي عَلَيْه', ok:true },
    { e:'😴', t:'أَقُولُ أُحِبُّهُ فَقَط دُونَ عَمَل' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ ارْزُقْنِي حُبَّكَ وَحُبَّ نَبِيِّكَ ﷺ وَاتِّبَاعَ سُنَّتِه' },

]};
