/* corners/stories/seerah-little/bitha.js — السيرة: البعثة والدعوة للصغار (٣–٦) · ٨ حكايات */
window.SEERAH_LITTLE = window.SEERAH_LITTLE || {};
window.SEERAH_LITTLE.bitha = {
  id:'bitha', icon:'📜', color:'#C9A227', title:'الْبِعْثَةُ وَالدَّعْوَة', tag:'نُزُولُ الْوَحْيِ وَصَبْرُ مَكَّة',
  stories:[

{ id:'iqra', icon:'📜', color:'#C9A227', title:'اقْرَأْ!',
  tag:'أَوَّلُ نُزُولِ الْوَحْي',
  pages:[
    { emoji:'⛰️', text:'كَانَ النَّبِيُّ ﷺ يَتَعَبَّدُ فِي غَارِ حِرَاء، فَجَاءَهُ الْمَلَكُ جِبْرِيلُ فَجْأَةً وَقَال: اقْرَأْ!',
      prompt:'A mountain cave at night with a gentle burst of light at the entrance, the first revelation, no figures' },
    { emoji:'😰', text:'قَالَ النَّبِيُّ ﷺ: مَا أَنَا بِقَارِئ! فَضَمَّهُ جِبْرِيلُ ثُمَّ قَال: اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَق.',
      prompt:'Soft radiant words of light forming in a cave, the words Iqra, awe and warmth, no figures' },
    { emoji:'🏠', text:'رَجَعَ النَّبِيُّ ﷺ خَائِفًا يَرْتَجِف، فَطَمْأَنَتْهُ زَوْجَتُهُ خَدِيجَة وَقَالَت: أَبْشِرْ، وَاللهِ لَا يُخْزِيكَ اللهُ أَبَدًا.',
      prompt:'A cozy warm home with comforting light, reassurance and care, no faces, tender' },
    { emoji:'💚', text:'هَكَذَا بَدَأَ نُزُولُ الْقُرْآن، أَعْظَمِ كِتَابٍ فِي التَّارِيخ، وَبَدَأَتْ رِسَالَةُ النَّبِيِّ ﷺ.',
      prompt:'A radiant light descending from the sky over Makkah, the start of the message, warm hopeful' },
  ],
  moral:'أَوَّلُ كَلِمَةٍ فِي الْقُرْآنِ «اقْرَأْ» — دِينِي دِينُ الْعِلْمِ وَالنُّور. 💚',
  game:{ type:'pairs', title:'صِلْ كُلَّ شَيْءٍ بِمَعْنَاه', pairs:[
    ['⛰️ غَارُ حِرَاء','مَكَانُ نُزُولِ الْوَحْي'],
    ['📜 أَوَّلُ كَلِمَة','اقْرَأْ'],
    ['💞 خَدِيجَة','طَمْأَنَتِ النَّبِيَّ ﷺ'] ] },
  act:{ q:'مَا أَوَّلُ كَلِمَةٍ نَزَلَتْ مِنَ الْقُرْآن؟', yay:'أَحْسَنْت! اقْرَأْ — دِينُنَا دِينُ الْعِلْم', opts:[
    { e:'📜', t:'اقْرَأْ', ok:true },
    { e:'😴', t:'نَمْ' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ عَلِّمْنَا مَا يَنْفَعُنَا وَزِدْنَا عِلْمًا' },

{ id:'secret', icon:'🤫', color:'#5B4B8A', title:'الدَّعْوَةُ السِّرِّيَّة',
  tag:'أَوَّلُ الْمُؤْمِنِين',
  pages:[
    { emoji:'🤫', text:'بَدَأَ النَّبِيُّ ﷺ يَدْعُو النَّاسَ إِلَى اللهِ سِرًّا، لِأَنَّ الْمُشْرِكِينَ كَانُوا أَقْوِيَاءَ يُؤْذُونَ الْمُسْلِمِين.',
      prompt:'A small gathering by candlelight in an old Makkan house, secret teaching, warm, no faces' },
    { emoji:'💞', text:'فَآمَنَتْ زَوْجَتُهُ خَدِيجَة، وَصَدِيقُهُ أَبُو بَكْر، وَابْنُ عَمِّهِ عَلِيٌّ الصَّغِير، وَمَوْلَاهُ زَيْد.',
      prompt:'A few glowing hearts of early believers together, first Muslims, warm tender scene' },
    { emoji:'🏡', text:'كَانُوا يَجْتَمِعُونَ فِي بَيْتِ الْأَرْقَمِ يَتَعَلَّمُونَ الْقُرْآنَ وَيُصَلُّون.',
      prompt:'A quiet house with soft light where believers learn, the house of Al-Arqam, warm serene, no faces' },
    { emoji:'💚', text:'كَانُوا قِلَّةً لَكِنَّ إِيمَانَهُم قَوِيّ، فَصَبَرُوا وَثَبَتُوا مِنْ أَجْلِ الْحَقّ.',
      prompt:'A small but steadfast group with glowing hearts, few but firm, warm uplifting' },
  ],
  moral:'الْحَقُّ يَبْدَأُ صَغِيرًا، وَأَهْلُهُ قِلَّةٌ لَكِنْ صَبْرُهُم يَصْنَعُ الْعَظَائِم. 💚',
  game:{ type:'find', title:'اجْمَعْ قُلُوبَ أَوَّلِ الْمُؤْمِنِينَ الْخَمْس', target:'💚', count:5, distractors:['🗿','☁️'], size:12 },
  act:{ q:'أَيْنَ كَانَ الْمُسْلِمُونَ الْأَوَائِلُ يَجْتَمِعُون؟', yay:'أَحْسَنْت! فِي بَيْتِ الْأَرْقَم', opts:[
    { e:'🏡', t:'فِي بَيْتِ الْأَرْقَم', ok:true },
    { e:'🏬', t:'فِي السُّوق' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ ثَبِّتْنِي عَلَى الْحَقِّ وَلَوْ كُنْتُ وَحْدِي' },

{ id:'safa', icon:'📢', color:'#E67E22', title:'الدَّعْوَةُ الْجَهْرِيَّة',
  tag:'عَلَى جَبَلِ الصَّفَا',
  pages:[
    { emoji:'📢', text:'أَمَرَ اللهُ نَبِيَّهُ ﷺ أَنْ يُعْلِنَ الدَّعْوَة، فَصَعِدَ جَبَلَ الصَّفَا وَنَادَى قَوْمَه.',
      prompt:'A figure calling from a hill to a gathering crowd below in old Makkah, public call, warm, no faces' },
    { emoji:'🤔', text:'سَأَلَهُم: لَوْ أَخْبَرْتُكُم أَنَّ خَيْلًا خَلْفَ الْجَبَلِ تُرِيدُ أَنْ تُهَاجِمَكُم، أَتُصَدِّقُونَنِي؟ قَالُوا: نَعَم، مَا جَرَّبْنَا عَلَيْكَ كَذِبًا!',
      prompt:'A crowd listening attentively to a trusted speaker, trust in his honesty, warm, no faces' },
    { emoji:'☝️', text:'فَقَال: إِنِّي نَذِيرٌ لَكُم، اعْبُدُوا اللهَ وَحْدَهُ وَاتْرُكُوا الْأَصْنَام! لَكِنَّ أَكْثَرَهُم رَفَضُوا وَآذَوْه.',
      prompt:'A figure calling to worship one God, stone idols in background, warm reverent, no face detail' },
    { emoji:'💚', text:'فَصَبَرَ النَّبِيُّ ﷺ وَاسْتَمَرَّ يَدْعُو بِالْحِكْمَةِ وَالرِّفْق، وَلَمْ يَيْأَس.',
      prompt:'A patient figure continuing to call with gentleness under warm light, perseverance, no face' },
  ],
  moral:'أَدْعُو إِلَى الْخَيْرِ بِالْحِكْمَةِ وَالرِّفْق، وَأَصْبِرُ وَلَا أَيْأَس. 💚',
  game:{ type:'sort', title:'كَيْفَ نَدْعُو إِلَى الْخَيْر؟', bins:['بِالْحِكْمَةِ وَالرِّفْق ✅','خَطَأ 🚫'], items:[
    { e:'😊', t:'بِالْكَلَامِ الطَّيِّبِ وَالصَّبْر', bin:0 },
    { e:'😠', t:'بِالْغَضَبِ وَالْإِجْبَار', bin:1 },
    { e:'🤲', t:'بِالدُّعَاءِ لِلنَّاسِ بِالْهِدَايَة', bin:0 },
    { e:'🙅', t:'بِالسُّخْرِيَةِ مِنْهُم', bin:1 } ] },
  act:{ q:'أَيْنَ أَعْلَنَ النَّبِيُّ ﷺ دَعْوَتَه؟', yay:'أَحْسَنْت! عَلَى جَبَلِ الصَّفَا', opts:[
    { e:'📢', t:'عَلَى جَبَلِ الصَّفَا', ok:true },
    { e:'🕋', t:'دَاخِلَ الْكَعْبَة' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ اهْدِ قَوْمِي فَإِنَّهُم لَا يَعْلَمُون' },

{ id:'harm', icon:'🛡️', color:'#8E2E2E', title:'صَبْرٌ عَلَى الْأَذَى',
  tag:'ثَبَاتُ النَّبِيِّ ﷺ',
  pages:[
    { emoji:'😠', text:'آذَى الْمُشْرِكُونَ النَّبِيَّ ﷺ كَثِيرًا: سَخِرُوا مِنْهُ، وَوَضَعُوا الشَّوْكَ فِي طَرِيقِه، وَآذَوْا أَصْحَابَه.',
      prompt:'A path with thorns and a calm dignified figure walking, harm and patience, warm, no face' },
    { emoji:'💚', text:'وَمَعَ كُلِّ هَذَا الْأَذَى، صَبَرَ النَّبِيُّ ﷺ وَلَمْ يَنْتَقِم، بَلْ دَعَا لَهُم بِالْهِدَايَة.',
      prompt:'A serene figure forgiving and praying for others with warm light, patience and mercy, no face' },
    { emoji:'🌟', text:'حِينَ آذَاهُ أَهْلُ الطَّائِف، جَاءَهُ مَلَكُ الْجِبَالِ لِيُهْلِكَهُم، فَقَال: بَلْ أَرْجُو أَنْ يُخْرِجَ اللهُ مِنْ ذُرِّيَّتِهِم مَنْ يَعْبُدُه!',
      prompt:'A figure showing mercy even to those who harmed him, hope for their descendants, warm tender' },
    { emoji:'💛', text:'فَأَتَعَلَّمُ الصَّبْرَ وَالْعَفْو: إِذَا آذَانِي أَحَدٌ صَبَرْتُ وَعَفَوْتُ وَدَعَوْتُ لَهُ بِالْخَيْر.',
      prompt:'A child forgiving a friend with a warm smile, patience and pardon, uplifting bright' },
  ],
  moral:'أَصْبِرُ عَلَى الْأَذَى وَأَعْفُو كَمَا صَبَرَ النَّبِيُّ ﷺ وَعَفَا. 💛',
  game:{ type:'sort', title:'مَاذَا أَفْعَلُ إِذَا آذَانِي أَحَد؟', bins:['صَبْرٌ وَعَفْو 💚','انْتِقَامٌ 🚫'], items:[
    { e:'💚', t:'أَصْبِرُ وَأَعْفُو', bin:0 },
    { e:'😡', t:'أَنْتَقِمُ بِالْأَسْوَأ', bin:1 },
    { e:'🤲', t:'أَدْعُو لَهُ بِالْهِدَايَة', bin:0 },
    { e:'👊', t:'أُبَادِلُهُ الْأَذَى', bin:1 } ] },
  act:{ q:'مَاذَا فَعَلَ النَّبِيُّ ﷺ حِينَ آذَاهُ أَهْلُ الطَّائِف؟', yay:'أَحْسَنْت! صَبَرَ وَدَعَا لَهُم بِالْخَيْر', opts:[
    { e:'💚', t:'صَبَرَ وَرَجَا لَهُمُ الْهِدَايَة', ok:true },
    { e:'😡', t:'دَعَا عَلَيْهِم بِالْهَلَاك' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ ارْزُقْنِي الصَّبْرَ وَالْعَفْوَ عَنِ النَّاس' },

{ id:'weak', icon:'⛓️', color:'#C0392B', title:'أَبْطَالُ الثَّبَات',
  tag:'بِلَالٌ وَآلُ يَاسِر',
  pages:[
    { emoji:'☀️', text:'عُذِّبَ الضُّعَفَاءُ مِنَ الْمُسْلِمِينَ عَذَابًا شَدِيدًا لِيَتْرُكُوا دِينَهُم، لَكِنَّهُم ثَبَتُوا.',
      prompt:'Hot desert sand under a blazing sun, hardship of the early believers, warm but gentle, no faces' },
    { emoji:'⛓️', text:'بِلَالٌ عُذِّبَ عَلَى الرَّمْلِ الْحَارِّ وَهُوَ يَقُول: أَحَدٌ أَحَد! رَبِّيَ اللهُ الْوَاحِد.',
      prompt:'A single finger raised to the sky with steadfast light, Bilal saying Ahad, warm, no face' },
    { emoji:'🌹', text:'وَآلُ يَاسِرٍ صَبَرُوا، فَبَشَّرَهُمُ النَّبِيُّ ﷺ: صَبْرًا آلَ يَاسِر، فَإِنَّ مَوْعِدَكُمُ الْجَنَّة!',
      prompt:'A family standing firm with a ray of paradise light, patience rewarded, warm tender, no faces' },
    { emoji:'💚', text:'فَأَتَعَلَّمُ الثَّبَات: أَتَمَسَّكُ بِدِينِي وَلَوْ سَخِرَ مِنِّي أَحَدٌ أَوْ آذَانِي.',
      prompt:'A brave child holding firm with a glowing heart, steadfast faith, warm uplifting' },
  ],
  moral:'أَثْبُتُ عَلَى دِينِي كَمَا ثَبَتَ بِلَالٌ وَآلُ يَاسِر. 💚',
  game:{ type:'find', title:'اثْبُتْ عَلَى الْحَقّ! اجْمَعِ الْقُلُوبَ الثَّابِتَةَ الْخَمْس', target:'💚', count:5, distractors:['⛓️','☀️'], size:12 },
  act:{ q:'مَاذَا كَانَ يَقُولُ بِلَالٌ تَحْتَ الْعَذَاب؟', yay:'أَحْسَنْت! أَحَدٌ أَحَد — ثَبَاتٌ عَظِيم', opts:[
    { e:'☝️', t:'أَحَدٌ أَحَد', ok:true },
    { e:'😱', t:'أَتْرُكُ دِينِي' },
    { e:'🤷', t:'لَا شَيْء' } ] },
  dua:'اللَّهُمَّ ثَبِّتْنِي عَلَى دِينِكَ حَتَّى أَلْقَاك' },

{ id:'habasha', icon:'🚢', color:'#2E9E7E', title:'الْهِجْرَةُ إِلَى الْحَبَشَة',
  tag:'الْمَلِكُ الْعَادِلُ النَّجَاشِيّ',
  pages:[
    { emoji:'🚢', text:'لَمَّا اشْتَدَّ الْأَذَى، أَمَرَ النَّبِيُّ ﷺ بَعْضَ الْمُسْلِمِينَ أَنْ يُهَاجِرُوا إِلَى الْحَبَشَة، فِيهَا مَلِكٌ عَادِلٌ اسْمُهُ النَّجَاشِيّ.',
      prompt:'A boat crossing the sea toward a safe distant land, migration to Abyssinia, warm hopeful, no faces' },
    { emoji:'👑', text:'اسْتَقْبَلَهُمُ النَّجَاشِيُّ بِكَرَم، فَقَرَأَ عَلَيْهِ جَعْفَرٌ آيَاتٍ مِنَ الْقُرْآن، فَبَكَى الْمَلِكُ وَحَمَاهُم.',
      prompt:'A just king listening with tears to recited verses, a fair ruler, warm reverent, no faces' },
    { emoji:'⚖️', text:'رَفَضَ النَّجَاشِيُّ أَنْ يُسَلِّمَهُم لِلْمُشْرِكِين، وَقَال: لَنْ أُسَلِّمَهُم! فَعَاشُوا آمِنِينَ فِي عَدْلِه.',
      prompt:'A protective just king shielding refugees, justice and refuge, warm dignified, no faces' },
    { emoji:'💚', text:'فَأَتَعَلَّمُ أَنَّ الْعَدْلَ خُلُقٌ عَظِيم، وَأَنَّ اللهَ يُهَيِّئُ لِعِبَادِهِ مَنْ يَحْمِيهِم.',
      prompt:'Refugees living safely in a welcoming land, safety under justice, warm bright scene' },
  ],
  moral:'الْعَدْلُ يَحْمِي النَّاس، وَاللهُ يُهَيِّئُ لِعِبَادِهِ مَنْ يَنْصُرُهُم. 💚',
  game:{ type:'maze', title:'أَبْحِرْ بِالْمُهَاجِرِينَ إِلَى أَرْضِ الْحَبَشَةِ الْآمِنَة', avatar:'🚢', goal:'🏝️', wall:'🌊', map:['S..#.','##.#.','.#...','.#.##','...#G'] },
  act:{ q:'مَنِ الْمَلِكُ الَّذِي حَمَى الْمُهَاجِرِينَ فِي الْحَبَشَة؟', yay:'أَحْسَنْت! النَّجَاشِيُّ الْمَلِكُ الْعَادِل', opts:[
    { e:'👑', t:'النَّجَاشِيُّ الْعَادِل', ok:true },
    { e:'😠', t:'مَلِكٌ ظَالِم' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ اجْعَلْنِي عَادِلًا مُحِبًّا لِلْعَدْل' },

{ id:'grief', icon:'😢', color:'#5B4B8A', title:'عَامُ الْحُزْن',
  tag:'وَفَاةُ خَدِيجَةَ وَأَبِي طَالِب',
  pages:[
    { emoji:'😢', text:'فِي سَنَةٍ وَاحِدَة، تُوُفِّيَتْ زَوْجَتُهُ خَدِيجَة، وَعَمُّهُ أَبُو طَالِبٍ الَّذِي كَانَ يَحْمِيه، فَحَزِنَ النَّبِيُّ ﷺ حُزْنًا شَدِيدًا.',
      prompt:'A soft melancholic but hopeful scene with warm light, a year of loss, no faces, tender' },
    { emoji:'🌙', text:'فَأَكْرَمَهُ اللهُ بِرِحْلَةِ الْإِسْرَاءِ وَالْمِعْرَاج: أُسْرِيَ بِهِ إِلَى الْقُدْسِ ثُمَّ عُرِجَ بِهِ إِلَى السَّمَاء.',
      prompt:'A path of light rising through the heavens at night, the Night Journey as comfort, warm radiant' },
    { emoji:'🕌', text:'وَفِيهَا فُرِضَتِ الصَّلَاةُ الْخَمْس — هَدِيَّةٌ مِنَ اللهِ تُرِيحُ الْقَلْبَ الْحَزِين.',
      prompt:'Five gentle points of light representing the five prayers, a gift from heaven, warm serene' },
    { emoji:'💚', text:'فَأَتَعَلَّمُ أَنَّ بَعْدَ كُلِّ حُزْنٍ فَرَجًا، وَأَنَّ الصَّلَاةَ رَاحَةُ الْقَلْبِ الْحَزِين.',
      prompt:'A comforted heart finding rest in prayer with warm light, relief after grief, tender' },
  ],
  moral:'بَعْدَ كُلِّ حُزْنٍ فَرَج، وَالصَّلَاةُ رَاحَةٌ لِقَلْبِي. 💚',
  game:{ type:'pairs', title:'صِلْ كُلَّ شَيْءٍ بِمَعْنَاه', pairs:[
    ['😢 عَامُ الْحُزْن','وَفَاةُ خَدِيجَةَ وَأَبِي طَالِب'],
    ['🌙 الْإِسْرَاءُ وَالْمِعْرَاج','هَدِيَّةٌ بَعْدَ الْحُزْن'],
    ['🕌 فُرِضَت','الصَّلَوَاتُ الْخَمْس'] ] },
  act:{ q:'مَاذَا فُرِضَ فِي رِحْلَةِ الْإِسْرَاءِ وَالْمِعْرَاج؟', yay:'أَحْسَنْت! الصَّلَوَاتُ الْخَمْس', opts:[
    { e:'🕌', t:'الصَّلَوَاتُ الْخَمْس', ok:true },
    { e:'🌙', t:'الصِّيَام' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ اجْعَلِ الصَّلَاةَ قُرَّةَ عَيْنِي وَرَاحَةَ قَلْبِي' },

{ id:'nusrah', icon:'🤝', color:'#1F8B6E', title:'بَيْعَةُ الْأَنْصَار',
  tag:'أَهْلُ الْمَدِينَةِ يُؤْمِنُون',
  pages:[
    { emoji:'🤝', text:'عَرَضَ النَّبِيُّ ﷺ دَعْوَتَهُ عَلَى الْقَبَائِلِ فِي مَوْسِمِ الْحَجّ، فَآمَنَ بِهِ نَفَرٌ مِنْ أَهْلِ الْمَدِينَة.',
      prompt:'Travelers meeting and pledging under warm light in a valley, meeting the Ansar, no faces' },
    { emoji:'🌟', text:'رَجَعُوا إِلَى الْمَدِينَةِ وَنَشَرُوا الْإِسْلَام، ثُمَّ جَاؤُوا وَبَايَعُوا النَّبِيَّ ﷺ عَلَى نُصْرَتِهِ وَحِمَايَتِه.',
      prompt:'A pledge of loyalty with joined hands and light, the pledge of support, warm reverent, no faces' },
    { emoji:'🏙️', text:'فَصَارَتِ الْمَدِينَةُ أَرْضًا آمِنَةً تَنْتَظِرُ النَّبِيَّ ﷺ وَأَصْحَابَه، وَفَتَحَتْ لَهُم قُلُوبَهَا وَبُيُوتَهَا.',
      prompt:'A welcoming green city at dawn awaiting arrival, Madinah ready, warm hopeful scene' },
    { emoji:'💚', text:'فَأَتَعَلَّمُ نُصْرَةَ الْحَقّ: أَقِفُ مَعَ الْخَيْرِ وَأَنْصُرُ إِخْوَانِي وَأُكْرِمُ ضَيْفِي.',
      prompt:'Children welcoming and helping newcomers warmly, support and hospitality, uplifting bright' },
  ],
  moral:'أَنْصُرُ الْحَقَّ وَأُكْرِمُ إِخْوَانِي كَمَا فَعَلَ الْأَنْصَار. 💚',
  game:{ type:'order', title:'رَتِّبْ مَرَاحِلَ الدَّعْوَةِ فِي مَكَّة', items:[
    { e:'📜', t:'نُزُولُ الْوَحْيِ فِي حِرَاء' },
    { e:'🤫', t:'الدَّعْوَةُ السِّرِّيَّة' },
    { e:'📢', t:'الدَّعْوَةُ الْجَهْرِيَّة' },
    { e:'🤝', t:'بَيْعَةُ الْأَنْصَار' } ] },
  act:{ q:'مَنِ الَّذِينَ بَايَعُوا النَّبِيَّ ﷺ عَلَى نُصْرَتِه؟', yay:'أَحْسَنْت! الْأَنْصَارُ أَهْلُ الْمَدِينَة', opts:[
    { e:'🤝', t:'الْأَنْصَارُ مِنْ أَهْلِ الْمَدِينَة', ok:true },
    { e:'😠', t:'مُشْرِكُو مَكَّة' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ اجْعَلْنِي نَاصِرًا لِلْحَقِّ مُعِينًا لِإِخْوَانِي' },

]};
