/* corners/stories/seerah-little/hijra.js — السيرة: الهجرة إلى المدينة للصغار (٣–٦) · ٨ حكايات */
window.SEERAH_LITTLE = window.SEERAH_LITTLE || {};
window.SEERAH_LITTLE.hijra = {
  id:'hijra', icon:'🌙', color:'#2980B9', title:'الْهِجْرَةُ إِلَى الْمَدِينَة', tag:'رِحْلَةُ النُّور',
  stories:[

{ id:'plot', icon:'😠', color:'#8E2E2E', title:'مَكْرُ الْمُشْرِكِين',
  tag:'أَرَادُوا إِيذَاءَ النَّبِيِّ ﷺ',
  pages:[
    { emoji:'😠', text:'لَمَّا كَثُرَ الْمُسْلِمُونَ وَعَرَفَ الْمُشْرِكُونَ أَنَّهُم سَيُهَاجِرُون، خَافُوا وَتَآمَرُوا عَلَى إِيذَاءِ النَّبِيِّ ﷺ.',
      prompt:'Shadowy plotters in an old Makkan hall by dim light, a scheme, warm tense mood, no faces' },
    { emoji:'🛡️', text:'لَكِنَّ اللهَ يَحْمِي نَبِيَّه! أَخْبَرَهُ اللهُ بِمَكْرِهِم وَأَمَرَهُ بِالْهِجْرَةِ إِلَى الْمَدِينَة.',
      prompt:'A gentle protective light over a figure, divine protection, warm reassuring, no face' },
    { emoji:'🌙', text:'خَرَجَ النَّبِيُّ ﷺ لَيْلًا وَتَرَكَ عَلِيًّا يَنَامُ فِي فِرَاشِه، وَاللهُ أَعْمَى أَبْصَارَهُم عَنْه.',
      prompt:'A quiet night departure from a house under starlight, the escape, warm serene, no faces' },
    { emoji:'💚', text:'فَأَتَعَلَّمُ أَنَّ اللهَ يَحْفَظُ أَوْلِيَاءَه، وَأَنَّ مَكْرَ الظَّالِمِينَ لَا يَضُرُّ مَنْ حَفِظَهُ الله.',
      prompt:'A safe figure walking under a protective starry sky, safety by Allah, warm hopeful' },
  ],
  moral:'اللهُ يَحْفَظُ أَوْلِيَاءَه، وَمَكْرُ الظَّالِمِينَ لَا يَضُرُّ مَنْ حَفِظَهُ الله. 💚',
  game:{ type:'pairs', title:'صِلْ كُلَّ شَيْءٍ بِمَعْنَاه', pairs:[
    ['😠 الْمُشْرِكُون','تَآمَرُوا عَلَى النَّبِيّ'],
    ['🛡️ اللهُ','حَمَى نَبِيَّه'],
    ['🦁 عَلِيّ','نَامَ فِي فِرَاشِ النَّبِيّ'] ] },
  act:{ q:'مَنْ حَمَى النَّبِيَّ ﷺ مِنْ مَكْرِ الْمُشْرِكِين؟', yay:'أَحْسَنْت! اللهُ حَافِظُ أَوْلِيَائِه', opts:[
    { e:'🛡️', t:'اللهُ حَفِظَه', ok:true },
    { e:'💰', t:'الْمَال' },
    { e:'🤷', t:'لَا أَحَد' } ] },
  dua:'حَسْبِيَ اللهُ وَنِعْمَ الْوَكِيل' },

{ id:'cave', icon:'🕳️', color:'#5B4B8A', title:'غَارُ ثَوْر',
  tag:'لَا تَحْزَنْ إِنَّ اللهَ مَعَنَا',
  pages:[
    { emoji:'🌙', text:'خَرَجَ النَّبِيُّ ﷺ مَعَ صَاحِبِهِ أَبِي بَكْر، وَاخْتَبَآ فِي غَارِ ثَوْرٍ ثَلَاثَةَ أَيَّام.',
      prompt:'Two travelers hidden in a mountain cave at night, the cave of Thawr, warm serene, no faces' },
    { emoji:'🕷️', text:'أَمَرَ اللهُ عَنْكَبُوتًا فَنَسَجَ بَيْتَهُ عَلَى بَابِ الْغَار، وَحَمَامَةً فَبَاضَتْ عِنْدَه.',
      prompt:'A spider web and a nesting dove at a cave entrance with soft light, hidden protection, warm' },
    { emoji:'👣', text:'جَاءَ الْأَعْدَاءُ حَتَّى وَقَفُوا فَوْقَ الْغَار! فَقَالَ النَّبِيُّ ﷺ لِأَبِي بَكْر: لَا تَحْزَنْ إِنَّ اللهَ مَعَنَا.',
      prompt:'Feet visible at a cave mouth above, calm believers inside with light, suspense and peace, no faces' },
    { emoji:'💚', text:'فَحَفِظَهُمَا اللهُ وَلَمْ يَرَهُمَا أَحَد! مَنْ كَانَ اللهُ مَعَهُ فَلَنْ يَصِلَ إِلَيْهِ سُوء.',
      prompt:'A protected cave glowing softly as danger passes, divine safety, warm reassuring' },
  ],
  moral:'لَا تَحْزَنْ إِنَّ اللهَ مَعَنَا — مَنْ كَانَ اللهُ مَعَهُ فَلَا يَخَاف. 💚',
  game:{ type:'find', title:'حَمَى اللهُ الْغَار! اجْمَعْ عَلَامَاتِ الْحِفْظِ الْخَمْس', target:'🕸️', count:5, distractors:['🌵','🪨'], size:12 },
  act:{ q:'مَاذَا قَالَ النَّبِيُّ ﷺ لِأَبِي بَكْرٍ فِي الْغَار؟', yay:'أَحْسَنْت! فَاطْمَأَنَّ قَلْبُه', opts:[
    { e:'💚', t:'لَا تَحْزَنْ إِنَّ اللهَ مَعَنَا', ok:true },
    { e:'😱', t:'اهْرُبْ بِسُرْعَة!' },
    { e:'🤷', t:'لَا شَيْء' } ] },
  dua:'لَا تَحْزَنْ إِنَّ اللهَ مَعَنَا' },

{ id:'suraqa', icon:'🐎', color:'#D4A017', title:'مُطَارَدَةُ سُرَاقَة',
  tag:'الْفَرَسُ تَغُوصُ فِي الرَّمْل',
  pages:[
    { emoji:'🐎', text:'جَعَلَ الْمُشْرِكُونَ جَائِزَةً كَبِيرَةً لِمَنْ يُمْسِكُ النَّبِيَّ ﷺ، فَطَارَدَهُ فَارِسٌ اسْمُهُ سُرَاقَة.',
      prompt:'A horseman galloping across the desert in pursuit, the chase, warm tense, no faces' },
    { emoji:'🕳️', text:'وَكُلَّمَا اقْتَرَبَ سُرَاقَةُ مِنَ النَّبِيِّ ﷺ، غَاصَتْ قَوَائِمُ فَرَسِهِ فِي الرَّمْل!',
      prompt:'A horse legs sinking into desert sand mid-gallop, divine intervention, warm dramatic, no faces' },
    { emoji:'🤲', text:'فَعَرَفَ سُرَاقَةُ أَنَّ اللهَ يَحْمِي النَّبِيّ، فَطَلَبَ الْأَمَانَ وَرَجَع، وَأَسْلَمَ بَعْدَ ذَلِك.',
      prompt:'A humbled horseman turning back peacefully, a heart softening, warm reflective, no faces' },
    { emoji:'💚', text:'فَأَتَعَلَّمُ أَنَّ حِفْظَ اللهِ أَقْوَى مِنْ كُلِّ الْأَعْدَاءِ وَالْأَسْبَاب.',
      prompt:'A safe traveler continuing under a warm protective sky, unstoppable divine protection, hopeful' },
  ],
  moral:'حِفْظُ اللهِ أَقْوَى مِنْ كُلِّ الْأَعْدَاء، فَمَنْ حَفِظَهُ اللهُ لَا يُغْلَب. 💚',
  game:{ type:'maze', title:'أَوْصِلِ النَّبِيَّ ﷺ بِأَمَانٍ بَعِيدًا عَنِ الْمُطَارِد', avatar:'🚶', goal:'🌙', wall:'🐎', map:['S..#.','##.#.','.#...','.#.##','...#G'] },
  act:{ q:'مَاذَا حَدَثَ لِفَرَسِ سُرَاقَةَ كُلَّمَا اقْتَرَب؟', yay:'أَحْسَنْت! غَاصَتْ فِي الرَّمْلِ بِحِفْظِ الله', opts:[
    { e:'🕳️', t:'غَاصَتْ قَوَائِمُهَا فِي الرَّمْل', ok:true },
    { e:'💨', t:'طَارَتْ' },
    { e:'🤷', t:'لَا شَيْء' } ] },
  dua:'اللَّهُمَّ احْفَظْنِي بِحِفْظِكَ الَّذِي لَا يُغْلَب' },

{ id:'welcome', icon:'🌴', color:'#27AE60', title:'طَلَعَ الْبَدْرُ عَلَيْنَا',
  tag:'فَرْحَةُ أَهْلِ الْمَدِينَة',
  pages:[
    { emoji:'🌴', text:'وَصَلَ النَّبِيُّ ﷺ إِلَى الْمَدِينَة، فَفَرِحَ أَهْلُهَا فَرَحًا عَظِيمًا وَخَرَجُوا لِاسْتِقْبَالِه.',
      prompt:'A joyful crowd welcoming an arrival in a green oasis town, jubilant reception, warm bright, no faces' },
    { emoji:'🥳', text:'أَنْشَدَ الْأَطْفَالُ وَالنَّاس: طَلَعَ الْبَدْرُ عَلَيْنَا مِنْ ثَنِيَّاتِ الْوَدَاع!',
      prompt:'Children singing joyfully with lanterns to welcome, a happy celebration, warm festive, no faces' },
    { emoji:'🏙️', text:'صَارَتْ «يَثْرِب» تُسَمَّى «الْمَدِينَةَ الْمُنَوَّرَة» — مَدِينَةَ النَّبِيِّ ﷺ الْمُضِيئَة بِالنُّور.',
      prompt:'A radiant town glowing warmly at dusk, the illuminated city, serene warm scene' },
    { emoji:'💚', text:'فَأَتَعَلَّمُ أَنْ أَسْتَقْبِلَ إِخْوَانِي وَضُيُوفِي بِفَرَحٍ وَتَرْحِيبٍ وَحُبّ.',
      prompt:'Children warmly welcoming a guest with smiles, joyful hospitality, warm bright' },
  ],
  moral:'أَسْتَقْبِلُ إِخْوَانِي وَضُيُوفِي بِالْفَرَحِ وَالتَّرْحِيبِ وَالْحُبّ. 💚',
  game:{ type:'find', title:'اسْتَقْبِلِ النَّبِيَّ ﷺ بِالْفَرَح! اجْمَعِ الْفَوَانِيسَ الْخَمْس', target:'🏮', count:5, distractors:['🌴','🌙'], size:12 },
  act:{ q:'بِمَاذَا سُمِّيَتْ يَثْرِبُ بَعْدَ قُدُومِ النَّبِيِّ ﷺ؟', yay:'أَحْسَنْت! الْمَدِينَةُ الْمُنَوَّرَة', opts:[
    { e:'🏙️', t:'الْمَدِينَةُ الْمُنَوَّرَة', ok:true },
    { e:'🏜️', t:'بَقِيَتْ يَثْرِب' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ اجْعَلْنِي مِحْبَابًا لِإِخْوَانِي مُرَحِّبًا بِضُيُوفِي' },

{ id:'masjid', icon:'🕌', color:'#16A085', title:'بِنَاءُ الْمَسْجِد',
  tag:'أَوَّلُ عَمَلٍ فِي الْمَدِينَة',
  pages:[
    { emoji:'🕌', text:'أَوَّلُ مَا فَعَلَهُ النَّبِيُّ ﷺ فِي الْمَدِينَةِ أَنْ بَنَى الْمَسْجِد، لِيَكُونَ بَيْتًا لِلَّهِ وَمَدْرَسَةً لِلْمُسْلِمِين.',
      prompt:'Building a simple mosque of palm trunks and mud, the first mosque, warm cooperative scene, no faces' },
    { emoji:'🧱', text:'وَعَمِلَ النَّبِيُّ ﷺ بِنَفْسِهِ مَعَ أَصْحَابِهِ يَحْمِلُ الطُّوبَ وَالْحِجَارَة، وَلَمْ يَتَكَبَّر.',
      prompt:'People carrying bricks together to build, humble teamwork, warm bright scene, no faces' },
    { emoji:'📚', text:'صَارَ الْمَسْجِدُ مَكَانَ الصَّلَاةِ وَتَعَلُّمِ الْقُرْآنِ وَاجْتِمَاعِ الْمُسْلِمِينَ وَقَضَاءِ حَوَائِجِهِم.',
      prompt:'A warm mosque interior with people learning and praying, center of community, serene, no faces' },
    { emoji:'💚', text:'فَأَتَعَلَّمُ أَنَّ الْمَسْجِدَ بَيْتُ الله، وَأَنَّ الْعَمَلَ بِالْيَدِ لَا يَعِيبُ أَحَدًا.',
      prompt:'A child helping build/clean a mosque cheerfully, love of the mosque, warm uplifting' },
  ],
  moral:'الْمَسْجِدُ بَيْتُ اللهِ وَقَلْبُ الْمُجْتَمَع، وَأُحِبُّهُ وَأَعْتَنِي بِه. 💚',
  game:{ type:'order', title:'رَتِّبْ خُطُوَاتِ بِنَاءِ الْمَسْجِد', items:[
    { e:'📍', t:'اخْتِيَارُ الْمَكَان' },
    { e:'🧱', t:'حَمْلُ الطُّوبِ وَالْحِجَارَة' },
    { e:'🕌', t:'بِنَاءُ الْمَسْجِد' },
    { e:'📚', t:'الصَّلَاةُ وَالتَّعَلُّمُ فِيه' } ] },
  act:{ q:'مَا أَوَّلُ مَا بَنَاهُ النَّبِيُّ ﷺ فِي الْمَدِينَة؟', yay:'أَحْسَنْت! بَنَى الْمَسْجِد', opts:[
    { e:'🕌', t:'الْمَسْجِد', ok:true },
    { e:'🏰', t:'قَصْرًا' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ اجْعَلْ قَلْبِي مُعَلَّقًا بِبُيُوتِك' },

{ id:'brotherhood', icon:'🤝', color:'#E67E22', title:'الْمُؤَاخَاة',
  tag:'الْمُهَاجِرُونَ وَالْأَنْصَار',
  pages:[
    { emoji:'🤝', text:'آخَى النَّبِيُّ ﷺ بَيْنَ الْمُهَاجِرِينَ (مِنْ مَكَّة) وَالْأَنْصَارِ (أَهْلِ الْمَدِينَة)، فَصَارُوا كَالْإِخْوَة.',
      prompt:'Two groups joining hands as brothers, the pairing of migrants and helpers, warm unity, no faces' },
    { emoji:'🎁', text:'قَاسَمَ الْأَنْصَارُ إِخْوَانَهُمُ الْمُهَاجِرِينَ بُيُوتَهُم وَأَمْوَالَهُم بِكُلِّ فَرَح!',
      prompt:'People sharing homes and food generously, extraordinary generosity, warm bright scene, no faces' },
    { emoji:'💞', text:'أَحَبَّ بَعْضُهُم بَعْضًا فِي الله، وَآثَرُوا إِخْوَانَهُم عَلَى أَنْفُسِهِم — أَعْظَمُ أُخُوَّةٍ فِي التَّارِيخ.',
      prompt:'Hearts of light joined in brotherhood, love for Allah sake, warm tender scene' },
    { emoji:'💚', text:'فَأَتَعَلَّمُ الْأُخُوَّة: أُحِبُّ إِخْوَانِي وَأُشَارِكُهُم وَأُوثِرُهُم عَلَى نَفْسِي.',
      prompt:'Children sharing and caring for one another warmly, brotherhood, uplifting bright' },
  ],
  moral:'الْمُؤْمِنُونَ إِخْوَة: أُحِبُّهُم وَأُشَارِكُهُم وَأُوثِرُهُم عَلَى نَفْسِي. 💚',
  game:{ type:'sort', title:'أَيُّهَا مِنَ الْأُخُوَّة؟', bins:['أُخُوَّةٌ 💚','أَنَانِيَّة 🚫'], items:[
    { e:'🎁', t:'أُشَارِكُ أَخِي', bin:0 },
    { e:'😤', t:'كُلُّ شَيْءٍ لِي وَحْدِي', bin:1 },
    { e:'🤝', t:'أُسَاعِدُ الْمُحْتَاج', bin:0 },
    { e:'🙅', t:'أَبْخَلُ عَلَى إِخْوَانِي', bin:1 } ] },
  act:{ q:'بَيْنَ مَنْ آخَى النَّبِيُّ ﷺ فِي الْمَدِينَة؟', yay:'أَحْسَنْت! بَيْنَ الْمُهَاجِرِينَ وَالْأَنْصَار', opts:[
    { e:'🤝', t:'الْمُهَاجِرِينَ وَالْأَنْصَار', ok:true },
    { e:'😠', t:'الْأَعْدَاء' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ أَلِّفْ بَيْنَ قُلُوبِنَا وَاجْعَلْنَا إِخْوَانًا مُتَحَابِّين' },

{ id:'covenant', icon:'📜', color:'#5B4B8A', title:'دَوْلَةُ الْعَدْل',
  tag:'وَثِيقَةُ الْمَدِينَة',
  pages:[
    { emoji:'📜', text:'أَقَامَ النَّبِيُّ ﷺ فِي الْمَدِينَةِ أَوَّلَ دَوْلَةِ عَدْلٍ فِي الْإِسْلَام، وَكَتَبَ وَثِيقَةً تُنَظِّمُ حَيَاةَ النَّاس.',
      prompt:'A scroll of agreement with warm light, the Constitution of Madinah, dignified, no faces' },
    { emoji:'⚖️', text:'عَامَلَ النَّبِيُّ ﷺ كُلَّ النَّاسِ بِالْعَدْل، مُسْلِمِينَ وَغَيْرَهُم، وَأَعْطَى كُلَّ ذِي حَقٍّ حَقَّه.',
      prompt:'A fair balance scale glowing over a diverse community, justice for all, warm serene' },
    { emoji:'🤝', text:'عَاشَ النَّاسُ فِي أَمْنٍ وَسَلَام، وَصَارَتِ الْمَدِينَةُ مِثَالًا لِلْعَدْلِ وَالتَّعَاوُن.',
      prompt:'A peaceful thriving town where people cooperate, a just society, warm bright scene, no faces' },
    { emoji:'💚', text:'فَأَتَعَلَّمُ الْعَدْلَ: أُعَامِلُ الْجَمِيعَ بِإِنْصَافٍ وَلَا أَظْلِمُ أَحَدًا.',
      prompt:'A child sharing fairly among friends, fairness and justice, warm uplifting' },
  ],
  moral:'أَعْدِلُ مَعَ الْجَمِيعِ وَلَا أَظْلِمُ أَحَدًا، فَالْعَدْلُ أَسَاسُ الْمُجْتَمَع. 💚',
  game:{ type:'sort', title:'أَيُّهَا مِنَ الْعَدْل؟', bins:['عَدْل ✅','ظُلْم 🚫'], items:[
    { e:'⚖️', t:'أُعْطِي كُلَّ ذِي حَقٍّ حَقَّه', bin:0 },
    { e:'😤', t:'أُحَابِي صَدِيقِي عَلَى الْحَقّ', bin:1 },
    { e:'🤝', t:'أُنْصِفُ الْجَمِيع', bin:0 },
    { e:'👊', t:'أَظْلِمُ الضَّعِيف', bin:1 } ] },
  act:{ q:'كَيْفَ عَامَلَ النَّبِيُّ ﷺ النَّاسَ فِي الْمَدِينَة؟', yay:'أَحْسَنْت! بِالْعَدْلِ مَعَ الْجَمِيع', opts:[
    { e:'⚖️', t:'بِالْعَدْلِ مَعَ الْجَمِيع', ok:true },
    { e:'😠', t:'بِالظُّلْم' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ اجْعَلْنِي عَادِلًا لَا أَظْلِمُ أَحَدًا' },

{ id:'lesson', icon:'🌟', color:'#1F8B6E', title:'دُرُوسُ الْهِجْرَة',
  tag:'التَّضْحِيَةُ وَالتَّوَكُّل',
  pages:[
    { emoji:'🌟', text:'الْهِجْرَةُ حَدَثٌ عَظِيمٌ عَلَّمَنَا دُرُوسًا كَثِيرَة: أَعْظَمُهَا التَّوَكُّلُ عَلَى اللهِ وَالْأَخْذُ بِالْأَسْبَاب.',
      prompt:'A starlit journey path toward a bright destination, lessons of the Hijra, warm hopeful' },
    { emoji:'💪', text:'تَرَكَ الْمُهَاجِرُونَ بُيُوتَهُم وَأَمْوَالَهُم مِنْ أَجْلِ دِينِهِم — تَضْحِيَةٌ عَظِيمَةٌ لِلَّه.',
      prompt:'People leaving homes for the sake of faith with resolve, sacrifice, warm dignified, no faces' },
    { emoji:'📅', text:'وَمِنْ عَظَمَتِهَا أَنَّ الْمُسْلِمِينَ جَعَلُوا الْهِجْرَةَ بِدَايَةَ التَّقْوِيمِ الْإِسْلَامِيّ (التَّارِيخِ الْهِجْرِيّ).',
      prompt:'A calendar starting fresh with warm light, the Hijri calendar begins, serene' },
    { emoji:'💚', text:'فَأَتَعَلَّمُ أَنْ أُضَحِّيَ مِنْ أَجْلِ الْخَيْر، وَأَتَوَكَّلَ عَلَى اللهِ فِي كُلِّ أَمْرِي.',
      prompt:'A child taking a brave good step with trust, sacrifice and trust, warm uplifting' },
  ],
  moral:'أُضَحِّي مِنْ أَجْلِ الْخَيْر، وَآخُذُ بِالْأَسْبَابِ وَأَتَوَكَّلُ عَلَى الله. 💚',
  game:{ type:'order', title:'رَتِّبْ رِحْلَةَ الْهِجْرَة', items:[
    { e:'😠', t:'مَكْرُ الْمُشْرِكِين' },
    { e:'🕳️', t:'الِاخْتِبَاءُ فِي الْغَار' },
    { e:'🐎', t:'مُطَارَدَةُ سُرَاقَة' },
    { e:'🌴', t:'الْوُصُولُ إِلَى الْمَدِينَة' } ] },
  act:{ q:'مَاذَا جَعَلَ الْمُسْلِمُونَ بِدَايَةَ تَقْوِيمِهِم؟', yay:'أَحْسَنْت! الْهِجْرَةَ إِلَى الْمَدِينَة', opts:[
    { e:'📅', t:'الْهِجْرَةَ النَّبَوِيَّة', ok:true },
    { e:'🎂', t:'أَعْيَادَهُم' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ ارْزُقْنِي التَّضْحِيَةَ لِأَجْلِكَ وَالتَّوَكُّلَ عَلَيْك' },

]};
