/* corners/stories/seerah-little/mawlid.js — السيرة: المولد والنشأة للصغار (٣–٦) · ٨ حكايات */
window.SEERAH_LITTLE = window.SEERAH_LITTLE || {};
window.SEERAH_LITTLE.mawlid = {
  id:'mawlid', icon:'🌟', color:'#2E9E7E', title:'الْمَوْلِدُ وَالنَّشْأَة', tag:'طُفُولَةُ النَّبِيِّ ﷺ',
  stories:[

{ id:'birth', icon:'🌟', color:'#2E9E7E', title:'مَوْلِدُ النَّبِيِّ ﷺ',
  tag:'وُلِدَ فِي عَامِ الْفِيل',
  pages:[
    { emoji:'🌟', text:'فِي مَكَّةَ الْمُكَرَّمَةِ وُلِدَ أَعْظَمُ إِنْسَانٍ فِي التَّارِيخ: نَبِيُّنَا مُحَمَّدٌ ﷺ، فِي يَوْمِ الِاثْنَيْن.',
      prompt:'A gentle warm glow over the city of Makkah at dawn, the birth of the Prophet, no faces, reverent' },
    { emoji:'👶', text:'وُلِدَ فِي «عَامِ الْفِيل»، وَكَانَ يَتِيمًا: تُوُفِّيَ أَبُوهُ عَبْدُ الله قَبْلَ أَنْ يُولَد.',
      prompt:'A soft cradle with warm light in an old Makkan home, tender and peaceful, no face shown' },
    { emoji:'🕋', text:'وَسَمَّاهُ جَدُّهُ عَبْدُ الْمُطَّلِبِ «مُحَمَّدًا» — أَيِ الَّذِي يُحْمَدُ كَثِيرًا.',
      prompt:'The Kaaba in old Makkah with warm morning light, naming ceremony atmosphere, serene' },
    { emoji:'💚', text:'وُلِدَ ﷺ رَحْمَةً لِلْعَالَمِين، لِيَهْدِيَ النَّاسَ إِلَى اللهِ وَيُعَلِّمَهُمُ الْخَيْر.',
      prompt:'Rays of mercy-light spreading gently over the world from Makkah, mercy to all, warm radiant' },
  ],
  moral:'وُلِدَ نَبِيُّنَا ﷺ رَحْمَةً لِلْعَالَمِين، وَأُحِبُّهُ أَكْثَرَ مِنْ نَفْسِي. 💚',
  game:{ type:'pairs', title:'صِلْ كُلَّ شَيْءٍ بِمَعْنَاه', pairs:[
    ['🌟 مَوْلِدُهُ ﷺ','فِي مَكَّةَ عَامَ الْفِيل'],
    ['📛 اسْمُهُ مُحَمَّد','الَّذِي يُحْمَدُ كَثِيرًا'],
    ['💚 بُعِثَ','رَحْمَةً لِلْعَالَمِين'] ] },
  act:{ q:'أَيْنَ وُلِدَ النَّبِيُّ ﷺ؟', yay:'أَحْسَنْت! فِي مَكَّةَ الْمُكَرَّمَة', opts:[
    { e:'🕋', t:'فِي مَكَّةَ الْمُكَرَّمَة', ok:true },
    { e:'🏙️', t:'فِي الْمَدِينَة' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّد' },

{ id:'halima', icon:'🐑', color:'#C9A227', title:'فِي بَادِيَةِ بَنِي سَعْد',
  tag:'حَلِيمَةُ السَّعْدِيَّة',
  pages:[
    { emoji:'🐑', text:'أَرْضَعَتِ النَّبِيَّ ﷺ فِي صِغَرِهِ مُرْضِعَةٌ طَيِّبَةٌ اسْمُهَا حَلِيمَةُ السَّعْدِيَّة، فِي بَادِيَةٍ هَوَاؤُهَا نَقِيّ.',
      prompt:'A peaceful desert village with sheep and a caring nurse, warm pastoral scene, no faces' },
    { emoji:'✨', text:'وَمُنْذُ جَاءَهُم بُورِكَ لَهُم فِي كُلِّ شَيْء: كَثُرَ خَيْرُهُم وَغَنَمُهُم وَلَبَنُهُم!',
      prompt:'Abundant sheep and green pasture with soft golden light, blessing and abundance, warm' },
    { emoji:'🌿', text:'نَشَأَ ﷺ فِي الْبَادِيَةِ قَوِيًّا فَصِيحَ اللِّسَان، بَعِيدًا عَنْ ضَجِيجِ الْمَدِينَة.',
      prompt:'A healthy child playing in a clean open desert with sheep, wholesome upbringing, warm bright' },
    { emoji:'💚', text:'فَالنَّبِيُّ ﷺ يُحِبُّ الْبَسَاطَةَ وَالطُّهْرَ مُنْذُ صِغَرِه.',
      prompt:'A simple pure desert dawn with soft light, purity and simplicity, serene' },
  ],
  moral:'نَشَأَ نَبِيُّنَا ﷺ طَاهِرًا بَسِيطًا، وَالْبَرَكَةُ تَتْبَعُ أَهْلَ الْخَيْر. 💚',
  game:{ type:'find', title:'الْبَرَكَةُ فِي غَنَمِ حَلِيمَة! اجْمَعِ الْأَغْنَامَ الْخَمْس', target:'🐑', count:5, distractors:['🌵','🪨'], size:12 },
  act:{ q:'مَاذَا حَدَثَ لِبَيْتِ حَلِيمَةَ حِينَ جَاءَهَا النَّبِيُّ ﷺ؟', yay:'أَحْسَنْت! نَزَلَتِ الْبَرَكَةُ وَكَثُرَ الْخَيْر', opts:[
    { e:'✨', t:'نَزَلَتِ الْبَرَكَةُ وَكَثُرَ خَيْرُهُم', ok:true },
    { e:'😢', t:'قَلَّ خَيْرُهُم' },
    { e:'🤷', t:'لَا شَيْء' } ] },
  dua:'اللَّهُمَّ بَارِكْ لَنَا فِي رِزْقِنَا' },

{ id:'orphan', icon:'💔', color:'#5B4B8A', title:'الْيَتِيمُ الَّذِي رَعَاهُ الله',
  tag:'فَقْدُ الْأُمِّ وَالْجَدّ',
  pages:[
    { emoji:'💔', text:'حِينَ بَلَغَ النَّبِيُّ ﷺ سِتَّ سِنِين، تُوُفِّيَتْ أُمُّهُ آمِنَة، فَصَارَ يَتِيمَ الْأَبِ وَالْأُمّ.',
      prompt:'A soft melancholic but hopeful desert scene with warm light, loss and care, no faces, tender' },
    { emoji:'👴', text:'فَكَفَلَهُ جَدُّهُ عَبْدُ الْمُطَّلِبِ وَأَحَبَّهُ حُبًّا شَدِيدًا، ثُمَّ تُوُفِّيَ الْجَدُّ أَيْضًا.',
      prompt:'An elderly caring figure with a child under warm light, guardianship and love, no face detail' },
    { emoji:'🤝', text:'فَكَفَلَهُ عَمُّهُ أَبُو طَالِبٍ وَاعْتَنَى بِهِ وَأَحَبَّه. وَاللهُ كَانَ يَرْعَاهُ وَيَحْفَظُه.',
      prompt:'An uncle protectively caring for a boy, family kindness, warm supportive scene, no faces' },
    { emoji:'💚', text:'قَالَ الله: أَلَمْ يَجِدْكَ يَتِيمًا فَآوَى؟ فَاللهُ يَرْعَى الْيَتِيمَ وَيُحِبُّ مَنْ يَرْحَمُه.',
      prompt:'Gentle protective light over a child, Allah caring for the orphan, warm tender' },
  ],
  moral:'اللهُ يَرْعَى الْيَتِيم، وَأَنَا أَرْحَمُ الْيَتِيمَ وَأُحْسِنُ إِلَيْه. 💚',
  game:{ type:'sort', title:'كَيْفَ نُعَامِلُ الْيَتِيم؟', bins:['إِحْسَانٌ وَرَحْمَة 💚','خَطَأ 🚫'], items:[
    { e:'🤗', t:'أُحْسِنُ إِلَيْهِ وَأُلَاعِبُه', bin:0 },
    { e:'😠', t:'أُؤْذِيهِ وَأَحْزِنُه', bin:1 },
    { e:'🎁', t:'أُشَارِكُهُ طَعَامِي', bin:0 },
    { e:'🙅', t:'أَسْخَرُ مِنْه', bin:1 } ] },
  act:{ q:'مَنْ رَعَى النَّبِيَّ ﷺ بَعْدَ وَفَاةِ جَدِّه؟', yay:'أَحْسَنْت! عَمُّهُ أَبُو طَالِب، وَاللهُ يَرْعَاه', opts:[
    { e:'🤝', t:'عَمُّهُ أَبُو طَالِب', ok:true },
    { e:'🤷', t:'لَا أَحَد' },
    { e:'👑', t:'مَلِكُ مَكَّة' } ] },
  dua:'اللَّهُمَّ ارْحَمِ الْأَيْتَامَ وَاجْبُرْ قُلُوبَهُم' },

{ id:'shepherd', icon:'🐐', color:'#27AE60', title:'رَاعِي الْغَنَم',
  tag:'الْعَمَلُ الشَّرِيف',
  pages:[
    { emoji:'🐐', text:'حِينَ كَبِرَ النَّبِيُّ ﷺ قَلِيلًا، عَمِلَ فِي رَعْيِ الْغَنَمِ لِيُسَاعِدَ عَمَّهُ وَيَكْسِبَ رِزْقَهُ بِيَدِه.',
      prompt:'A young shepherd tending goats on a hillside at golden hour, honest work, warm, no face detail' },
    { emoji:'💪', text:'قَالَ ﷺ: مَا مِنْ نَبِيٍّ إِلَّا رَعَى الْغَنَم. فَالْعَمَلُ الشَّرِيفُ لَا يَعِيبُ صَاحِبَه.',
      prompt:'Goats grazing peacefully with a caring shepherd silhouette, dignity of work, warm pastoral' },
    { emoji:'🧠', text:'وَتَعَلَّمَ مِنْ رَعْيِ الْغَنَمِ الصَّبْرَ وَالرِّفْقَ وَالْمَسْؤُولِيَّة.',
      prompt:'A shepherd gently guiding goats, learning patience and responsibility, warm gentle scene' },
    { emoji:'💚', text:'فَأَتَعَلَّمُ أَنْ أَعْمَلَ وَأُسَاعِدَ أَهْلِي، وَأَنَّ كُلَّ عَمَلٍ حَلَالٍ شَرِيف.',
      prompt:'A child helping family with a task cheerfully, honest helpful work, warm bright' },
  ],
  moral:'الْعَمَلُ الشَّرِيفُ لَا يَعِيبُ صَاحِبَه، وَأُسَاعِدُ أَهْلِي بِفَرَح. 💚',
  game:{ type:'maze', title:'ارْعَ الْغَنَمَ وَأَوْصِلْهَا إِلَى الْمَرْعَى بِأَمَان', avatar:'🐐', goal:'🌿', wall:'🪨', map:['S.#..','.###.','...#.','##...','#..#G'] },
  act:{ q:'بِمَاذَا عَمِلَ النَّبِيُّ ﷺ فِي صِغَرِه؟', yay:'أَحْسَنْت! رَعْيُ الْغَنَمِ عَمَلٌ شَرِيف', opts:[
    { e:'🐐', t:'رَعْيِ الْغَنَم', ok:true },
    { e:'👑', t:'كَانَ مَلِكًا' },
    { e:'🤷', t:'لَمْ يَعْمَل' } ] },
  dua:'اللَّهُمَّ ارْزُقْنِي رِزْقًا حَلَالًا طَيِّبًا' },

{ id:'amin', icon:'🤝', color:'#B8862E', title:'الصَّادِقُ الْأَمِين',
  tag:'أَحَبَّهُ النَّاسُ لِصِدْقِه',
  pages:[
    { emoji:'🤝', text:'كَبِرَ النَّبِيُّ ﷺ وَهُوَ أَصْدَقُ النَّاسِ وَأَأْمَنُهُم، حَتَّى سَمَّاهُ أَهْلُ مَكَّةَ «الصَّادِقَ الْأَمِين».',
      prompt:'People trusting a noble figure with their belongings, honesty and trust, warm, no face detail' },
    { emoji:'💰', text:'كَانُوا يَضَعُونَ أَمَانَاتِهِمُ الثَّمِينَةَ عِنْدَه، لِأَنَّهُ لَا يَكْذِبُ وَلَا يَخُونُ أَبَدًا.',
      prompt:'Precious items entrusted safely to trusted hands, safekeeping of trusts, warm gentle' },
    { emoji:'🕋', text:'وَحِينَ اخْتَلَفَتْ قَبَائِلُ مَكَّةَ عَلَى وَضْعِ الْحَجَرِ الْأَسْوَد، اخْتَارُوهُ حَكَمًا فَأَرْضَى الْجَمِيع بِحِكْمَتِه.',
      prompt:'The Kaaba with a cloth carrying a stone lifted by tribes together, wise solution, warm reverent' },
    { emoji:'💚', text:'فَأَكُونُ صَادِقًا أَمِينًا مِثْلَه، فَالصِّدْقُ يَجْعَلُ النَّاسَ يُحِبُّونَنِي وَيَثِقُونَ بِي.',
      prompt:'A trustworthy child returning something to a friend with a smile, honesty, warm bright' },
  ],
  moral:'أَكُونُ صَادِقًا أَمِينًا مِثْلَ النَّبِيِّ ﷺ، فَالصِّدْقُ يُحَبِّبُنِي لِلنَّاس. 💚',
  game:{ type:'sort', title:'مَنِ الصَّادِقُ الْأَمِين؟', bins:['صِدْقٌ وَأَمَانَة ✅','كَذِبٌ وَخِيَانَة 🚫'], items:[
    { e:'🤝', t:'أَحْفَظُ الْأَمَانَة', bin:0 },
    { e:'🤥', t:'أَكْذِبُ عَلَى النَّاس', bin:1 },
    { e:'😊', t:'أَقُولُ الصِّدْقَ دَائِمًا', bin:0 },
    { e:'👀', t:'آخُذُ مَا لَيْسَ لِي', bin:1 } ] },
  act:{ q:'بِمَاذَا لَقَّبَ أَهْلُ مَكَّةَ النَّبِيَّ ﷺ قَبْلَ الْبِعْثَة؟', yay:'أَحْسَنْت! الصَّادِقُ الْأَمِين', opts:[
    { e:'🤝', t:'الصَّادِقُ الْأَمِين', ok:true },
    { e:'💰', t:'التَّاجِرُ الْغَنِيّ' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ اجْعَلْنِي صَادِقًا أَمِينًا' },

{ id:'khadija', icon:'💞', color:'#E84393', title:'زَوْجَتُهُ خَدِيجَة',
  tag:'خَيْرُ زَوْجَةٍ وَأَوَّلُ مُؤْمِنَة',
  pages:[
    { emoji:'💼', text:'عَمِلَ النَّبِيُّ ﷺ فِي التِّجَارَةِ لِسَيِّدَةٍ عَظِيمَةٍ اسْمُهَا خَدِيجَة، فَأُعْجِبَتْ بِصِدْقِهِ وَأَمَانَتِه.',
      prompt:'A trade caravan with goods in old Arabia, honest commerce, warm desert scene, no faces' },
    { emoji:'💞', text:'فَتَزَوَّجَهَا، وَكَانَتْ خَيْرَ زَوْجَةٍ: تُحِبُّهُ وَتُسَانِدُهُ وَتُعِينُهُ عَلَى الْخَيْر.',
      prompt:'A cozy warm home with soft light symbolizing a loving supportive marriage, no faces, tender' },
    { emoji:'🤍', text:'وَحِينَ نَزَلَ الْوَحْيُ وَخَافَ، طَمْأَنَتْهُ خَدِيجَةُ وَقَالَت: وَاللهِ لَا يُخْزِيكَ اللهُ أَبَدًا.',
      prompt:'A reassuring warm domestic scene with gentle light, comfort and support, no faces, tender' },
    { emoji:'💚', text:'كَانَتْ أَوَّلَ مَنْ آمَنَ بِهِ ﷺ، فَأَحَبَّهَا حُبًّا عَظِيمًا وَلَمْ يَنْسَهَا أَبَدًا.',
      prompt:'Two glowing hearts of light joined warmly, faithful love, serene warm scene' },
  ],
  moral:'الزَّوْجَةُ الصَّالِحَةُ سَنَدٌ وَعَوْن، وَخَدِيجَةُ خَيْرُ نِسَاءِ زَمَانِهَا. 💚',
  game:{ type:'pairs', title:'صِلْ كُلَّ شَيْءٍ عَنْ خَدِيجَة', pairs:[
    ['💼 عَمِلَ عِنْدَهَا','فِي التِّجَارَة'],
    ['🤍 أَوَّلُ مَنْ آمَن','بِالنَّبِيِّ ﷺ'],
    ['💞 طَمْأَنَتْه','عِنْدَ نُزُولِ الْوَحْي'] ] },
  act:{ q:'مَنْ أَوَّلُ مَنْ آمَنَ بِالنَّبِيِّ ﷺ؟', yay:'أَحْسَنْت! زَوْجَتُهُ خَدِيجَة رضي الله عنها', opts:[
    { e:'💞', t:'زَوْجَتُهُ خَدِيجَة', ok:true },
    { e:'🤷', t:'لَا أَحَد' },
    { e:'👑', t:'مَلِكُ مَكَّة' } ] },
  dua:'اللَّهُمَّ ارْزُقْنَا الصُّحْبَةَ الصَّالِحَة' },

{ id:'akhlaq', icon:'💚', color:'#1F8B6E', title:'أَخْلَاقُهُ قَبْلَ الْبِعْثَة',
  tag:'أَحْسَنُ النَّاسِ خُلُقًا',
  pages:[
    { emoji:'💚', text:'كَانَ النَّبِيُّ ﷺ قَبْلَ الْبِعْثَةِ أَحْسَنَ النَّاسِ خُلُقًا: يَصِلُ رَحِمَهُ، وَيُكْرِمُ ضَيْفَه، وَيُعِينُ الْمُحْتَاج.',
      prompt:'A noble figure helping the needy and welcoming guests, beautiful character, warm, no face' },
    { emoji:'🚫', text:'لَمْ يَعْبُدْ صَنَمًا قَطُّ، وَلَمْ يَكْذِبْ، وَلَمْ يَفْعَلْ سُوءًا — حَفِظَهُ اللهُ لِرِسَالَتِه.',
      prompt:'Stone idols in the background with a pure figure turning away, purity from falsehood, warm' },
    { emoji:'🤲', text:'وَكَانَ يُحِبُّ الْخَلْوَةَ وَالتَّفَكُّرَ فِي خَلْقِ اللهِ فِي غَارِ حِرَاء.',
      prompt:'A serene mountain cave with soft light at dusk, contemplation, warm reverent, no figure' },
    { emoji:'💛', text:'فَأَقْتَدِي بِأَخْلَاقِه: أَصِلُ أَهْلِي، وَأُكْرِمُ ضَيْفِي، وَأُسَاعِدُ الْمُحْتَاج.',
      prompt:'A child helping family and guests kindly, following the Prophet character, warm bright' },
  ],
  moral:'أَقْتَدِي بِأَخْلَاقِ النَّبِيِّ ﷺ: صِلَةُ الرَّحِمِ وَإِكْرَامُ الضَّيْفِ وَعَوْنُ الْمُحْتَاج. 💛',
  game:{ type:'find', title:'اقْتَدِ بِأَخْلَاقِهِ ﷺ! اجْمَعِ الْقُلُوبَ الطَّيِّبَةَ الْخَمْس', target:'💚', count:5, distractors:['🗿','☁️'], size:12 },
  act:{ q:'كَيْفَ كَانَ خُلُقُ النَّبِيِّ ﷺ قَبْلَ الْبِعْثَة؟', yay:'أَحْسَنْت! أَحْسَنَ النَّاسِ خُلُقًا', opts:[
    { e:'💚', t:'أَحْسَنَ النَّاسِ خُلُقًا', ok:true },
    { e:'😠', t:'سَيِّئَ الْخُلُق' },
    { e:'🤷', t:'لَا أَعْرِف' } ] },
  dua:'اللَّهُمَّ حَسِّنْ خُلُقِي كَمَا حَسَّنْتَ خَلْقِي' },

{ id:'hira', icon:'📜', color:'#C9A227', title:'قُرْبَ الْبِعْثَة',
  tag:'التَّهَيُّؤُ لِلرِّسَالَة',
  pages:[
    { emoji:'⛰️', text:'حِينَ اقْتَرَبَ عُمْرُ النَّبِيِّ ﷺ مِنَ الْأَرْبَعِين، صَارَ يُحِبُّ الْبُعْدَ عَنِ النَّاسِ لِيَتَفَكَّرَ فِي خَالِقِ الْكَوْن.',
      prompt:'A mountain with a cave overlooking Makkah at dusk, seeking solitude, warm serene, no figure' },
    { emoji:'😴', text:'وَكَانَ يَرَى رُؤْيَا صَادِقَةً فِي نَوْمِه، فَتَقَعُ كَمَا رَآهَا تَمَامًا — عَلَامَةٌ عَلَى قُرْبِ الْخَيْر.',
      prompt:'A soft dawn breaking gently, true dreams coming true, hopeful warm light, symbolic' },
    { emoji:'🕊️', text:'كَانَ اللهُ يُهَيِّئُهُ لِأَمْرٍ عَظِيم: أَنْ يَكُونَ نَبِيًّا وَرَسُولًا لِلْعَالَمِين.',
      prompt:'A gentle dove and warm light over a mountain cave, preparation for prophethood, serene' },
    { emoji:'💚', text:'وَقَرِيبًا سَيَنْزِلُ الْوَحْيُ وَتَبْدَأُ أَعْظَمُ قِصَّةٍ فِي التَّارِيخ… نُكْمِلُهَا فِي الرِّحْلَةِ الْقَادِمَة!',
      prompt:'A radiant light beginning to descend toward a mountain cave, dawn of revelation, warm hopeful' },
  ],
  moral:'اللهُ يُهَيِّئُ أَحْبَابَهُ لِلْخَيْر، وَأَتَفَكَّرُ فِي خَلْقِ اللهِ فَأُحِبُّه. 💚',
  game:{ type:'order', title:'رَتِّبْ مَرَاحِلَ طُفُولَةِ النَّبِيِّ ﷺ', items:[
    { e:'🌟', t:'الْمَوْلِدُ فِي مَكَّة' },
    { e:'🐑', t:'النَّشْأَةُ فِي الْبَادِيَة' },
    { e:'🐐', t:'رَعْيُ الْغَنَم' },
    { e:'⛰️', t:'التَّفَكُّرُ فِي حِرَاء' } ] },
  act:{ q:'مَاذَا كَانَ يَفْعَلُ النَّبِيُّ ﷺ فِي غَارِ حِرَاء؟', yay:'أَحْسَنْت! يَتَفَكَّرُ فِي خَالِقِ الْكَوْن', opts:[
    { e:'🤲', t:'يَتَفَكَّرُ فِي خَلْقِ الله', ok:true },
    { e:'😴', t:'يَنَامُ فَقَط' },
    { e:'🎮', t:'يَلْعَب' } ] },
  dua:'اللَّهُمَّ اجْعَلْنِي مِمَّنْ يَتَفَكَّرُ فِي خَلْقِكَ فَيُحِبُّك' },

]};
